// KINEO-INTERFACE-16-LINGUAS-2026-09-21 — interface em ar. Só copy autoral da interface: nunca prompt,
// título, resultado, nome de motor ou erro de API. Frase fora daqui cai em inglês (components/InterfaceLanguage.tsx).
// Gerado de scratchpad/tr-ar.js sobre o corpus vivo de frases (415); números e "Kineo" preservados por construção.
export const DICT: Record<string, string> = {
  'Generation failed': 'فشل الإنشاء',
  'You can retry safely.': 'يمكنك إعادة المحاولة بأمان.',
  'This engine is not available on your account right now': 'هذا المحرك غير متاح في حسابك حاليًا',
  'Retrying the same engine will stop at this same place. Pick another engine to keep going.': 'إعادة المحاولة بنفس المحرك ستتوقف عند نفس النقطة. اختر محركًا آخر للمتابعة.',
  'The engine is cooling down after two refunded attempts': 'المحرك يبرد بعد محاولتين تم استرداد رصيدهما',
  'Starting another one right now stops at this same place. Give it a few minutes.': 'بدء محاولة أخرى الآن يتوقف عند نفس النقطة. امنحه بضع دقائق.',
  'Starting another one right now stops at this same place. The button below unlocks by itself.': 'بدء محاولة أخرى الآن يتوقف عند نفس النقطة. الزر أدناه يُفتح من تلقاء نفسه.',
  'We stopped waiting on this render instead of leaving you hanging': 'توقفنا عن انتظار هذا التصيير بدلًا من تركك معلقًا',
  'This one ran far longer than any video that finishes here. Starting again is worth it.': 'استغرق هذا وقتًا أطول بكثير من أي فيديو يكتمل هنا. البدء من جديد يستحق.',
  'The video engine is busy — this is on our side, not your idea': 'محرك الفيديو مشغول — الخلل من جهتنا، لا من فكرتك',
  'Nothing about your text is wrong. Trying again in a few minutes usually goes straight through.': 'لا خطأ في نصك. إعادة المحاولة بعد بضع دقائق تنجح عادةً من أول مرة.',
  'Create Video': 'إنشاء فيديو',
  'Create a new video': 'إنشاء فيديو جديد',
  'AI Avatar Studio': 'استوديو الأفاتار بالذكاء الاصطناعي',
  'Viral Templates': 'قوالب رائجة',
  'Channel Builder': 'منشئ القنوات',
  'Invite & Earn': 'ادعُ واربح',
  'Start free': 'ابدأ مجانًا',
  'Try 7 days for $1': 'جرّب 7 أيام مقابل $1',
  'Pick a lane': 'اختر مسارًا',
  'All free tools': 'كل الأدوات المجانية',
  'Terms of Service': 'شروط الخدمة',
  'Trust Center': 'مركز الثقة',
  'Review & publish': 'راجع وانشر',
  'Your image': 'صورتك',
  'Cost per image': 'التكلفة لكل صورة',
  'No videos yet': 'لا فيديوهات بعد',
  'No audio yet': 'لا صوت بعد',
  '🎬 Studio — generate video': '🎬 Studio — إنشاء فيديو',
  '🎨 Images — create image': '🎨 الصور — إنشاء صورة',
  '🎙 Audio — text to speech': '🎙 الصوت — تحويل النص إلى كلام',
  'Type it. See it. Six image engines, one screen.': 'اكتبها. شاهدها. ستة محركات صور، شاشة واحدة.',
  'Type it. Hear it. Four voice engines, one screen.': 'اكتبها. اسمعها. أربعة محركات صوت، شاشة واحدة.',
  'Everything you’ve created, in one place.': 'كل ما أنشأته، في مكان واحد.',
  'Add credits →': 'إضافة رصيد →',
  'Upscale any result to 2x for 1 credit.': 'كبّر أي نتيجة إلى 2x مقابل 1 رصيد.',
  'We couldn’t load your images right now.': 'تعذر تحميل صورك الآن.',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'صورك ورصيدك في أمان — إنها مجرد عثرة قراءة مؤقتة.',
  'We couldn’t load your audio right now.': 'تعذر تحميل صوتك الآن.',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'صوتك ورصيدك في أمان — إنها مجرد عثرة قراءة مؤقتة.',
  'We couldn’t load part of your library right now.': 'تعذر تحميل جزء من مكتبتك الآن.',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'فيديوهاتك ورصيدك في أمان — إنها مجرد عثرة قراءة مؤقتة.',
  '↻ Try again': '↻ حاول مجددًا',
  '⬇ Download': '⬇ تنزيل',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': 'أعجبك صوت؟ يبني Studio الفيلم كله حوله — المشاهد والترجمة والموسيقى.',
  'Open Studio →': 'افتح Studio →',
  'open the Studio': 'افتح Studio',
  'Next episode →': 'الحلقة التالية →',
  'create your first image': 'أنشئ صورتك الأولى',
  'generate your first voiceover': 'أنشئ تعليقك الصوتي الأول',
  'Instant drafts': 'مسودات فورية',
  'Deep prompt understanding': 'فهم عميق للأمر النصي',
  'Perfect text rendering': 'عرض نص مثالي',
  'Create Image': 'إنشاء صورة',
  'Click-magnet YouTube covers': 'أغلفة YouTube تجذب النقرات',
  'Bring any image to life': 'أعطِ الحياة لأي صورة',
  'Instant narration': 'سرد فوري',
  'Four voice engines': 'أربعة محركات صوت',
  'A face that speaks your script': 'وجه ينطق نصك',
  'Every control, one screen': 'كل عناصر التحكم، شاشة واحدة',
  'Today’s trending topics': 'مواضيع اليوم الرائجة',
  'Real renders, every engine': 'تصييرات حقيقية، كل محرك',
  'Type an idea — watch it become a film.': 'اكتب فكرة — وشاهدها تتحول إلى فيلم.',
  'Start with the full toolkit': 'ابدأ بمجموعة الأدوات الكاملة',
  'Kineo’s own engine — 3–7 min': 'محرك Kineo الخاص — 3–7 دقائق',
  'The workhorse AI video engine': 'محرك فيديو الذكاء الاصطناعي للعمل اليومي',
  'Cinematic motion & camera': 'حركة وكاميرا سينمائية',
  'Film scenes, native voice & lip sync': 'مشاهد سينمائية، صوت أصلي ومزامنة شفاه',
  'Talking video from one photo': 'فيديو ناطق من صورة واحدة',
  'From idea to posted Short in 3 steps.': 'من الفكرة إلى Short منشور في 3 خطوات.',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'بلا تصوير، بلا مونتاج، بلا خط زمني. اكتب مرة واحدة — و Kineo يتولى الباقي.',
  'Step 1': 'الخطوة 1',
  'Kineo builds it': 'Kineo يبنيه',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'يكتب الذكاء الاصطناعي نصًا مبنيًا على الاحتفاظ بالمشاهد، ويسجل التعليق الصوتي، ويطابق اللقطات، ويدمج الترجمة — فيديو 9:16 جاهز.',
  'Download & post': 'نزّل وانشر',
  'Why Kineo': 'لماذا Kineo',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'معظم الأدوات تعيد قص فيديو طويل صوّرته مسبقًا. Kineo يبنيه من الصفر.',
  'See how to make Shorts without filming →': 'شاهد كيف تصنع Shorts بلا تصوير →',
  'Generates the Short from just an idea': 'ينشئ الـ Short من مجرد فكرة',
  'Writes the script for you': 'يكتب النص لك',
  'Finds and matches footage': 'يجد اللقطات ويطابقها',
  'your upload': 'ملفك المرفوع',
  'AI image studio included': 'استوديو صور بالذكاء الاصطناعي مضمّن',
  'Voice studio (text-to-speech)': 'استوديو صوت (تحويل النص إلى كلام)',
  'One-click HD film enhance': 'تحسين الفيلم إلى HD بنقرة واحدة',
  'One idea — or a whole toolkit.': 'فكرة واحدة — أو مجموعة أدوات كاملة.',
  'Try AI Presenter →': 'جرّب المقدّم بالذكاء الاصطناعي →',
  'Transparent Clips': 'مقاطع شفافة',
  'UGC Product Ads': 'إعلانات منتجات بأسلوب UGC',
  'Animate a photo →': 'حرّك صورة →',
  'Make a thumbnail →': 'اصنع صورة مصغرة →',
  'Free AI Shorts': 'Shorts مجانية بالذكاء الاصطناعي',
  'Start with a niche that already works.': 'ابدأ بمجال يعمل بالفعل.',
  'Not sure? Take the quiz →': 'غير متأكد؟ خذ الاختبار →',
  'Pick your engine. Ship a Short today.': 'اختر محركك. انشر Short اليوم.',
  'Cancel anytime': 'ألغِ في أي وقت',
  'Generate image →': 'إنشاء صورة →',
  'Generate audio →': 'إنشاء صوت →',
  'Paid plans unlock clean MP4s.': 'الخطط المدفوعة تفتح ملفات MP4 نظيفة.',
  'Best for starting out': 'الأفضل للبداية',
  'Best value per film': 'أفضل قيمة لكل فيلم',
  'on Nano Banana': 'على Nano Banana',
  'Every video engine incl. MiniMax H3': 'كل محركات الفيديو بما فيها MiniMax H3',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'MP4 بلا علامة مائية · 100 مشروع · تخزين 90 يومًا',
  ', finished': '، مكتمل',
  '— every engine unlocked': '— كل المحركات مفتوحة',
  '· voice + karaoke captions + score': '· صوت + ترجمة كاريوكي + موسيقى',
  '500 projects · forever storage': '500 مشروع · تخزين دائم',
  'Cancel anytime — 7-day money-back': 'ألغِ في أي وقت — استرداد خلال 7 أيام',
  'films on Omni Flash': 'أفلام على Omni Flash',
  '· 2 free HD enhances / month': '· 2 تحسين HD مجاني / شهريًا',
  'Unlimited projects · forever storage': 'مشاريع غير محدودة · تخزين دائم',
  'Everything in Creator': 'كل ما في Creator',
  'Calculate your cost per Short →': 'احسب تكلفتك لكل Short →',
  'How much do Shorts pay? →': 'كم تدفع Shorts؟ →',
  'Highest-RPM niches →': 'المجالات الأعلى في RPM →',
  'read the full review →': 'اقرأ المراجعة الكاملة →',
  'a single line is enough — or paste a full script': 'سطر واحد يكفي — أو الصق نصًا كاملًا',
  '1080×1920 · Full HD master': '1080×1920 · نسخة رئيسية Full HD',
  'Every film is delivered as a 1080×1920 Full HD master (engines render natively at 720–768p and are mastered up). For maximum sharpness, run ✨HD Enhance on the finished film.': 'يُسلَّم كل فيلم كنسخة رئيسية 1080×1920 Full HD (تصيّر المحركات أصلًا بدقة 720–768p ثم تُرفع). للحصول على أقصى حدة، شغّل ✨HD Enhance على الفيلم المكتمل.',
  'Your idea first. Review the settings, then generate.': 'فكرتك أولًا. راجع الإعدادات، ثم أنشئ.',
  '📷 Photo': '📷 صورة',
  '🖼️ Upload a different photo': '🖼️ ارفع صورة مختلفة',
  '🎙️ Generating…': '🎙️ جارٍ الإنشاء…',
  '🎙️ Cloning the voice…': '🎙️ جارٍ استنساخ الصوت…',
  '🎙️ Upload a different sample': '🎙️ ارفع عينة مختلفة',
  '⏹ Stop & clone': '⏹ أوقف واستنسخ',
  '🎭 Generate my avatar video': '🎭 أنشئ فيديو الأفاتار الخاص بي',
  'Continue exactly where ChatGPT stopped.': 'تابع من حيث توقف ChatGPT بالضبط.',
  '✨ Let AI structure it': '✨ دع الذكاء الاصطناعي يبنيه',
  'Optional settings': 'إعدادات اختيارية',
  'optional — a pre-tested move added to your prompt': 'اختياري — حركة مجرّبة مسبقًا تُضاف إلى أمرك النصي',
  'Reference image': 'صورة مرجعية',
  '🖼️ Start your video from an image — coming soon': '🖼️ ابدأ فيديوك من صورة — قريبًا',
  'Estimated cost': 'التكلفة التقديرية',
  'Your credits buy': 'رصيدك يكفي لـ',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'الصوت وترجمة الكاريوكي والموسيقى مضمّنة. إذا فشل التصيير، يعود رصيدك فورًا.',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'نفس الموضوع، خطاف وخاتمة جديدان — الفكرة مكتوبة مسبقًا.',
  'Build next episode →': 'ابنِ الحلقة التالية →',
  'Episode 2 →': 'الحلقة 2 →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'مقدّم ناطق بالذكاء الاصطناعي من صورة — بمزامنة شفاه، واستوديو خاص به',
  'Your face. Your script.': 'وجهك. نصك.',
  'Everything you need to make yourself speak — nothing you don’t.': 'كل ما تحتاجه لتجعل نفسك تتكلم — ولا شيء زائد.',
  'BEST MOTION': 'أفضل حركة',
  '1.5 · Realism': '1.5 · واقعية',
  '🎬 Put me in a scene': '🎬 ضعني في مشهد',
  'use original photo': 'استخدم الصورة الأصلية',
  '✍️ Say exactly this — word for word': '✍️ قل هذا بالضبط — كلمة بكلمة',
  '✨ Expand into a full Short script (45–60s)': '✨ وسّع إلى نص Short كامل (45–60 ثانية)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 وضع إعلان المنتج — بِع منتجًا بأسلوب UGC',
  'Free — fills the script box above, then generate with your presenter.': 'مجاني — يملأ مربع النص أعلاه، ثم أنشئ مع مقدّمك.',
  '2.5 · Speak in your own voice': '2.5 · تكلم بصوتك أنت',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ تم استنساخ الصوت — سيتحدث السرد بهذا الصوت.',
  'use a default voice': 'استخدم صوتًا افتراضيًا',
  '🎬 Full video — face the whole time': '🎬 فيديو كامل — الوجه طوال الوقت',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 مقدّم بالذكاء الاصطناعي — سريع وطبيعي · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro — جودة صورة ممتازة · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 Body Motion — الجذع واليدان والإيماءات · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ كلاسيكي — رأس متحدث · 110 cr',
  'you have': 'لديك',
  'to create your avatar video.': 'لإنشاء فيديو الأفاتار الخاص بك.',
  '5 · Gesture clips — transparent background': '5 · مقاطع إيماءات — خلفية شفافة',
  'auto-refunded if it fails': 'استرداد تلقائي عند الفشل',
  '⬇️ Download transparent WebM': '⬇️ نزّل WebM الشفاف',
  '⬇️ Original MP4 (with background)': '⬇️ MP4 الأصلي (مع الخلفية)',
  'Pick a face to preview': 'اختر وجهًا للمعاينة',
  '↺ Make another': '↺ اصنع آخر',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'أشخاص، حيوانات أليفة، منتجات، صور عائلية قديمة — ارفع صورة أو الصق رابط صورة عامًا وشاهدها تتحرك.',
  'The photo': 'الصورة',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': 'JPG/PNG حتى 8 ميغابايت. تُنزَّل الروابط العامة وتُتحقق بأمان على خادمنا.',
  'sign in': 'تسجيل الدخول',
  'Kineo will fetch and validate it on the server when you animate.': 'سيجلبه Kineo ويتحقق منه على الخادم عند التحريك.',
  'Upload a photo to preview': 'ارفع صورة للمعاينة',
  '🖼️ Upload a photo': '🖼️ ارفع صورة',
  '✨ Bring it to life': '✨ أعطها الحياة',
  'Uploading your photo…': 'جارٍ رفع صورتك…',
  'Bringing your photo to life… (1–3 min)': 'جارٍ إحياء صورتك… (1–3 دقائق)',
  'Alive!': 'حيّة!',
  '🌬️ Subtle & real': '🌬️ خفيف وواقعي',
  '😊 Person comes alive': '😊 الشخص يدبّ فيه الحياة',
  'Type your idea first': 'اكتب فكرتك أولًا',
  '📖 True Story': '📖 قصة حقيقية',
  'Paste your ChatGPT script': 'الصق نصك من ChatGPT',
  'First Short complete': 'اكتمل أول Short',
  'Keep your show moving': 'حافظ على استمرار برنامجك',
  'Cheapest way to see your idea as a film': 'أرخص طريقة لترى فكرتك فيلمًا',
  'Slow Dolly-In': 'دولي بطيء للداخل',
  'FPV Drone': 'طائرة FPV',
  'Macro Detail': 'تفاصيل ماكرو',
  'Sharing & creator options': 'المشاركة وخيارات صانع المحتوى',
  'We couldn’t load your videos right now': 'تعذر تحميل فيديوهاتك الآن',
  'Your videos and credits are safe — this is a temporary read hiccup, not a lost library.': 'فيديوهاتك ورصيدك في أمان — إنها عثرة قراءة مؤقتة، لا مكتبة مفقودة.',
  '⚡ Generate Video': '⚡ إنشاء الفيديو',
  'Prefer clean exports now? Starter includes': 'تفضّل تصديرات نظيفة الآن؟ يتضمن Starter',
  'credits each month for': 'رصيد شهريًا مقابل',
  'Your existing files stay available. Starter applies to new exports after checkout.': 'ملفاتك الحالية تبقى متاحة. يسري Starter على التصديرات الجديدة بعد الدفع.',
  'Build Next Episode First': 'ابنِ الحلقة التالية أولًا',
  'Video unavailable': 'الفيديو غير متاح',
  'Free MP4 includes the Kineo watermark': 'MP4 المجاني يتضمن علامة Kineo المائية',
  'Free distribution · latest Short': 'توزيع مجاني · أحدث Short',
  'Send it to one person for feedback': 'أرسله لشخص واحد لأخذ رأيه',
  'Copy a public watch page for your finished video. Your friend can watch it without logging in, then use “Make one like this” if the idea inspires them.': 'انسخ صفحة مشاهدة عامة لفيديوك المكتمل. يمكن لصديقك مشاهدته دون تسجيل دخول، ثم استخدام "اصنع واحدًا مثله" إذا ألهمته الفكرة.',
  'Public watch links are temporarily paused': 'روابط المشاهدة العامة متوقفة مؤقتًا',
  'Your video stays in your account. Download the MP4 if you want to send it directly; Kineo will not publish a public page without an explicit visibility choice.': 'يبقى فيديوك في حسابك. نزّل MP4 إن أردت إرساله مباشرة؛ لن ينشر Kineo صفحة عامة دون اختيار ظهور صريح.',
  'Loading…': 'جارٍ التحميل…',
  'For new videos ·': 'للفيديوهات الجديدة ·',
  'Published it?': 'هل نشرته؟',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'واضحة، من الأمام، شخص واحد. لحركة الجسم استخدم صورة من الخصر إلى الأعلى أو بطول الجسم مع ظهور اليدين. تُزال الأشرطة السوداء تلقائيًا.',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'أفضل نتيجة احترافية: ارفع مقطعًا عموديًا 5–20 ثانية يؤدي الإيماءات الحقيقية التي تريدها، بطول يقارب النص. يستبدل Sync-3 الكلام مع الحفاظ على الوجه وحركة الجسم الحقيقيين. MP4/MOV حتى 40 ميغابايت.',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'أؤكد أن لدي الحق في استخدام صورة هذا الشخص وأوافق على تحريكها بالذكاء الاصطناعي.',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': 'ارفع عينة صوت واضحة ~30-60 ثانية (متحدث واحد، ضوضاء خلفية قليلة) وسيُقرأ السرد بهذا الصوت. استخدم فقط صوتًا يحق لك استخدامه.',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'فيديوهات كلمة بكلمة تُظهر وجهك طوال الوقت (فهي قصيرة — لا حاجة للقطات مساندة).',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'فيديوهات الواقعية القصوى والمشهد المبني تُبقي المقدّم على الشاشة طوال السرد.',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ مقدمة خطّافة — أنت تفتتح، واللقطات المساندة تروي القصة',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'مقاطع قصيرة لمقدّمك يلوّح ويشير ويقدّم — تُسلَّم بصيغة WebM بخلفية شفافة حقيقية. أسقطها مباشرة في Storyline أو Premiere أو CapCut أو أي شريحة. بلا شاشة خضراء، بلا عزل.',
  'Cinematic film — 9-image consistency': 'فيلم سينمائي — اتساق 9 صور',
  '#1-ranked video model — Aug 2026 arena': 'نموذج الفيديو رقم 1 في التصنيف — ساحة أغسطس 2026',
  'Cinematic motion and camera work': 'حركة وعمل كاميرا سينمائيان',
  'Shorts money & growth': 'المال والنمو من Shorts',
  'Compare Kineo with 27 AI video tools →': 'قارن Kineo بـ 27 أداة فيديو بالذكاء الاصطناعي →',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'مقدّمون ناطقون، شخصيات قابلة لإعادة الاستخدام، مقاطع شفافة، إعلانات منتجات — بالإضافة إلى كل ما يلزم لاكتشاف الترند وركوبه.',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'صورة واحدة + نصك — فيديو ناطق بمزامنة شفاه بجودة الاستوديو، على طريقة HeyGen.',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'احفظ شخصية مرة واحدة — نفس الوجه بالضبط في كل فيديو وصورة مصغرة تصنعها.',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'إيماءات المقدّم — تلويح، إشارة، تقديم — بصيغة WebM بخلفية شفافة حقيقية.',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'الصق أي منتج — واحصل على إعلان 15-30 ثانية بأسلوب صانعي المحتوى، مكتوبًا ومنطوقًا لك.',
  'Bring any still photo to life as a moving, postable video.': 'أعطِ الحياة لأي صورة ثابتة كفيديو متحرك جاهز للنشر.',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'صور مصغرة تستحق النقر بأسلوب أكبر القنوات — من أمر نصي.',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'لكل مجال أدناه صفحة إنشاء خاصة، وأوامر نصية مضبوطة، وأمثلة حقيقية.',
  'Is the video really mine to post?': 'هل الفيديو ملكي حقًا لأنشره؟',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'الخطط المدفوعة تفتح MP4 النظيف بلا علامة مائية لـ YouTube أو TikTok أو Reels.',
  'Do I need any editing skills?': 'هل أحتاج مهارات مونتاج؟',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'لا. تكتب فكرة واحدة والذكاء الاصطناعي يكتب النص ويسجل الصوت ويجد اللقطات ويضيف الترجمة.',
  'Is there a watermark?': 'هل هناك علامة مائية؟',
  'Paid plans export clean, watermark-free MP4s.': 'الخطط المدفوعة تصدّر MP4 نظيفًا بلا علامة مائية.',
  'Can Kineo also generate images and voiceovers?': 'هل ينشئ Kineo الصور والتعليقات الصوتية أيضًا؟',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'نعم — يتضمن Kineo استوديو صور بالذكاء الاصطناعي (6 محركات منها FLUX و Seedream و Nano Banana Pro، ابتداءً من 1 رصيد للصورة) واستوديو صوت بـ 4 محركات لتحويل النص إلى كلام (ابتداءً من 1 رصيد لكل 1000 حرف). كل ما تصنعه يعيش في مكتبتك.',
  'Can I make my videos sharper?': 'هل يمكنني جعل فيديوهاتي أكثر حدة؟',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'لكل فيديو خيار تحسين بنقرة واحدة مدعوم بترميم الأفلام من Topaz — يزيل آثار الضغط ويستعيد التفاصيل ويضيف حبيبات سينمائية دقيقة. 10 رصيد لكل فيديو؛ تتضمن خطة Studio 2 تحسين مجاني شهريًا.',
  'Can I use my own script?': 'هل يمكنني استخدام نصي الخاص؟',
  'What if a generation fails?': 'ماذا لو فشل الإنشاء؟',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'يعود رصيدك تلقائيًا لحظة فشل التصيير — بلا تذكرة دعم، بلا انتظار. تدفع فقط مقابل الفيديوهات التي تحصل عليها فعلًا.',
  'Can I cancel anytime?': 'هل يمكنني الإلغاء في أي وقت؟',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'في أي وقت، بنقرة واحدة. الخطط شهرية ويتجدد رصيدك كل شهر.',
  'Can I run a whole channel with the same host?': 'هل يمكنني تشغيل قناة كاملة بنفس المقدّم؟',
  'Can I monetize the videos?': 'هل يمكنني تحقيق الدخل من الفيديوهات؟',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'نعم. كل فيديو ملكك لتحتفظ به وتنشره وتربح منه — بما في ذلك برنامج شركاء YouTube و TikTok و Reels. لا حاجة لترخيص إضافي.',
  'Can I use the videos commercially, or for client work?': 'هل يمكنني استخدام الفيديوهات تجاريًا أو في أعمال للعملاء؟',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'نعم. تسمح شروطنا باستخدام Kineo لأغراض شخصية أو تجارية مشروعة وتؤكد احتفاظك بملكية الفيديوهات التي تنشئها، فيمكنك نشرها والربح منها وتسليمها لعميل ضمن خدمتك المدفوعة. لا ترخيص إضافي، لا عائد لكل فيديو. حدان يأتيان من نفس الشروط: لا يمكنك إعادة بيع Kineo نفسه أو إعادة توزيعه، والمقاطع المخزنة داخل التصيير مرخصة للاستخدام في فيديوك المكتمل لا لإعادة رفعها كلقطات مستقلة. الخطط المدفوعة تصدّر MP4 النظيف بلا علامة مائية.',
  'How long does one video take?': 'كم يستغرق الفيديو الواحد؟',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'ينتهي وضع Fast عادةً خلال 3–7 دقائق. الفيديوهات المولّدة بالذكاء الاصطناعي والسينمائية تستغرق وقتًا أطول قليلًا لأن كل مشهد يُنشأ قبل تركيب MP4 النهائي.',
  'How much does Kineo cost?': 'كم يكلف Kineo؟',
  'Kineo has three monthly plans: Starter at $': 'لدى Kineo ثلاث خطط شهرية: Starter بـ $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'رصيد. يُصرف الرصيد لكل فيديو، وتعتمد تكلفة الفيديو على المحرك الذي تختاره، فتصيير Fast والفيلم السينمائي يخرجان من نفس الرصيد بمعدلات مختلفة جدًا.',
  'Which AI video engines can I use in Kineo?': 'ما محركات الفيديو بالذكاء الاصطناعي التي يمكنني استخدامها في Kineo؟',
  ', behind one interface and one balance:': '، خلف واجهة واحدة ورصيد واحد:',
  'What is the best AI video generator for faceless YouTube channels?': 'ما أفضل مولّد فيديو بالذكاء الاصطناعي لقنوات YouTube بلا وجه؟',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'نعم. المستخدمون المجانيون الذين لم يدفعوا قط يمكنهم تنزيل MP4 ذي العلامة المائية ومشاركته ونشره.',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'أفلام التجربة تحمل علامة مائية صغيرة — يمكنك تنزيل MP4 ومشاركته ونشره. بعد التجربة، يحمل فيديو Fast المجاني علامة مائية.',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'التنزيلات المجانية تحمل علامة مائية؛ الخطط المدفوعة تفتح MP4 النظيف.',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'تنزيلات التجربة تحمل علامة مائية، وكذلك فيديو Fast المجاني بعد التجربة، والخطط المدفوعة تصدّر نظيفًا دائمًا.',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'يمنح الوصول المجاني المستخدمين الجدد حتى 3 فيديوهات Fast بعلامة مائية كل 24 ساعة، بلا بطاقة. يمكنك تنزيلها ومشاركتها.',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'أنشئ ونزّل وشارك حتى 3 فيديوهات Fast بعلامة مائية كل 24 ساعة، بلا بطاقة.',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'أنشئ وشاهد ونزّل وشارك حتى 3 فيديوهات Fast بعلامة مائية كل 24 ساعة — بلا بطاقة.',
  'create, watch, download and share up to 3 Fast videos every 24h': 'أنشئ وشاهد ونزّل وشارك حتى 3 فيديوهات Fast كل 24 ساعة',
  '— no card, watermark included.': '— بلا بطاقة، مع علامة مائية.',
  'AI image generator — 6 engines': 'مولّد صور بالذكاء الاصطناعي — 6 محركات',
  'AI voice generator (text to speech)': 'مولّد صوت بالذكاء الاصطناعي (تحويل النص إلى كلام)',
  'AI video upscaler & enhancer': 'رافع دقة الفيديو ومحسّنه بالذكاء الاصطناعي',
  'Trending Shorts ideas today': 'أفكار Shorts الرائجة اليوم',
  'AI Avatar video — your face, any script': 'فيديو أفاتار بالذكاء الاصطناعي — وجهك، أي نص',
  'Kineo facts & numbers (citable)': 'حقائق وأرقام Kineo (قابلة للاقتباس)',
  'Free AI Shorts generator': 'مولّد Shorts مجاني بالذكاء الاصطناعي',
  'YouTube Shorts from a topic': 'YouTube Shorts من موضوع',
  'ChatGPT script to YouTube Short': 'من نص ChatGPT إلى YouTube Short',
  'Shorts without filming': 'Shorts بلا تصوير',
  'Faceless niche picker': 'منتقي المجال بلا وجه',
  'State of AI Shorts 2026': 'حالة Shorts بالذكاء الاصطناعي 2026',
  'AI Shorts for agencies & client work': 'Shorts بالذكاء الاصطناعي للوكالات وأعمال العملاء',
  'Trust Center — privacy, payments & ownership': 'مركز الثقة — الخصوصية والمدفوعات والملكية',
  'Affiliate program - 30% recurring': 'برنامج الشركاء - 30% متكررة',
  'Free AI Shorts by niche': 'Shorts مجانية بالذكاء الاصطناعي حسب المجال',
  'Free script generator': 'مولّد نصوص مجاني',
  'Product video ad script': 'نص إعلان فيديو لمنتج',
  'Client video brief generator': 'مولّد موجز فيديو للعملاء',
  'Free hook generator': 'مولّد خطافات مجاني',
  'Shorts script timer': 'مؤقّت نص Shorts',
  'Shorts money calculator': 'حاسبة أرباح Shorts',
  'How much do Shorts pay?': 'كم تدفع Shorts؟',
  'Best AI Shorts generators': 'أفضل مولّدات Shorts بالذكاء الاصطناعي',
  'TikTok vs Shorts: which pays more?': 'TikTok مقابل Shorts: أيهما يدفع أكثر؟',
  'All comparisons': 'كل المقارنات',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · جميع الحقوق محفوظة',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'يعتمد على ما إذا كنت تريد لقطات مخزنة مجمّعة أو لقطات مولّدة. أدوات مثل InVideo و AutoShorts تقص مقاطع مخزنة على نصك، وهو أرخص ومناسب لفيديوهات النقاط الحوارية. يولّد Kineo اللقطات بنماذج مثل Veo 3.1 و Kling 3، ويحافظ على سردك كلمة بكلمة بدل إعادة كتابته، ويستهدف 60 ثانية أو أكثر ليتأهل الفيديو لبرنامج TikTok Creator Rewards. إن كانت قناتك تعيش على مشاهد لا يملكها غيرك، فالتوليد يفوز؛ وإن كانت تعيش على الكمية، فالمخزون أرخص.',
  'Paste the complete script from ChatGPT here…': 'الصق النص الكامل من ChatGPT هنا…',
  'Paste the idea from ChatGPT here…': 'الصق الفكرة من ChatGPT هنا…',
  'What’s your video about? One idea in — a finished film out: voiced, scored and captioned.': 'عمّ يدور فيديوك؟ فكرة واحدة تدخل — وفيلم مكتمل يخرج: بصوت وموسيقى وترجمة.',
  'Settings and generation': 'الإعدادات والإنشاء',
  'Search your videos…': 'ابحث في فيديوهاتك…',
  'Search your audio…': 'ابحث في صوتياتك…',
  'Search your images by engine': 'ابحث في صورك حسب المحرك',
  'No playable videos in your library yet. Check your latest project above.': 'لا فيديوهات قابلة للتشغيل في مكتبتك بعد. تحقق من أحدث مشروع لك أعلاه.',
  'Make a finished Short →': 'اصنع Short مكتملًا →',
  'Video Editing & Creator Tools': 'تحرير الفيديو وأدوات صانعي المحتوى',
  'Trim, resize, change speed, mute or add text. Edit a file you already have, right in your browser. Your script and planning tools are still here below.': 'قص، غيّر الحجم، غيّر السرعة، اكتم الصوت أو أضف نصًا. حرّر ملفًا لديك بالفعل، مباشرة في متصفحك. أدوات النص والتخطيط لا تزال هنا بالأسفل.',
  '5 local editing tools': '5 أدوات تحرير محلية',
  'No generation credits to edit': 'التحرير لا يستهلك رصيد الإنشاء',
  'Edit video': 'تحرير الفيديو',
  'Files up to 100 MB and 3 minutes. Local, real-time export up to 1280 px on the long edge. MP4 or WebM depending on your browser; downloads are not saved to My Videos.': 'ملفات حتى 100 ميغابايت و 3 دقائق. تصدير محلي في الوقت الفعلي حتى 1280 بكسل على الضلع الأطول. MP4 أو WebM حسب متصفحك؛ التنزيلات لا تُحفظ في فيديوهاتي.',
  'Video Trimmer': 'قصّ الفيديو',
  'Cut the beginning or end and keep only the clip you need.': 'اقطع البداية أو النهاية واحتفظ بالمقطع الذي تحتاجه فقط.',
  'Video Resizer': 'تغيير حجم الفيديو',
  'Go vertical, square or wide. Fit the frame or crop to fill.': 'عمودي أو مربع أو عريض. لائم الإطار أو اقصص للملء.',
  'Video Speed Changer': 'تغيير سرعة الفيديو',
  'Slow it down or speed it up, from 0.5× to 2×.': 'أبطئه أو سرّعه، من 0.5× إلى 2×.',
  'Remove Audio': 'إزالة الصوت',
  'Download a copy without the original audio.': 'نزّل نسخة بدون الصوت الأصلي.',
  'Add Text to Video': 'إضافة نص إلى الفيديو',
  'Add a title or message that stays on screen. Not automatic subtitles.': 'أضف عنوانًا أو رسالة تبقى على الشاشة. ليست ترجمة تلقائية.',
  'No account · current Kineo plans': 'بلا حساب · خطط Kineo الحالية',
  'No account · fair-use limit': 'بلا حساب · حد الاستخدام العادل',
  'No account · unlimited in browser': 'بلا حساب · غير محدود في المتصفح',
  'Edit an existing video here. Create a new one with Kineo.': 'حرّر فيديو موجودًا هنا. أنشئ فيديو جديدًا مع Kineo.',
  'Create an AI video →': 'أنشئ فيديو بالذكاء الاصطناعي →',
  'Edit your video, preview the changes, then export a copy.': 'حرّر فيديوك، عاين التغييرات، ثم صدّر نسخة.',
  'Video preview': 'معاينة الفيديو',
  'Preview is silent. The download keeps audio unless Mute is selected.': 'المعاينة صامتة. يحتفظ التنزيل بالصوت ما لم يُحدَّد كتم الصوت.',
  'Start with your video': 'ابدأ بفيديوك',
  'Choose a local file. It stays on this device.': 'اختر ملفًا محليًا. يبقى على هذا الجهاز.',
  'Choose video file': 'اختر ملف فيديو',
  'Video file': 'ملف الفيديو',
  'Video settings': 'إعدادات الفيديو',
  'Aspect ratio': 'نسبة العرض إلى الارتفاع',
  'Playback speed': 'سرعة التشغيل',
  'On-screen text (100 characters, 3 lines)': 'نص على الشاشة (100 حرف، 3 أسطر)',
  'Add a title or message': 'أضف عنوانًا أو رسالة',
  'Export edited video': 'تصدير الفيديو المحرَّر',
  'Export happens in real time. Keep this tab visible. Re-encoded at up to 1280 px on the long edge; format depends on your browser.': 'يتم التصدير في الوقت الفعلي. أبقِ هذا التبويب ظاهرًا. يُعاد الترميز حتى 1280 بكسل على الضلع الأطول؛ الصيغة تعتمد على متصفحك.',
  'Making a 4-second sample on your device…': 'جارٍ إنشاء عينة 4 ثوانٍ على جهازك…',
  'Reading your file…': 'جارٍ قراءة ملفك…',
  'Export result': 'نتيجة التصدير',
  'Your edited video': 'فيديوك المحرَّر',
  'Local download only. This copy is not saved to My Videos.': 'تنزيل محلي فقط. هذه النسخة لا تُحفظ في فيديوهاتي.',
  'Exported video': 'الفيديو المصدَّر',
  'No upload. No generation credits. Your original is never overwritten.': 'بلا رفع. بلا رصيد إنشاء. لا يُستبدل ملفك الأصلي أبدًا.',
  'Up to 100 MB · 3 minutes · MP4/WebM input recommended. These are basic editing tools, not the CapCut app.': 'حتى 100 ميغابايت · 3 دقائق · يُنصح بإدخال MP4/WebM. هذه أدوات تحرير أساسية، وليست تطبيق CapCut.',
  'Need a new video? Open Kineo Studio →': 'تحتاج فيديو جديدًا؟ افتح Kineo Studio →',
  'This browser cannot export video here. Try the latest desktop Chrome or Edge.': 'لا يمكن لهذا المتصفح تصدير الفيديو هنا. جرّب أحدث Chrome أو Edge على سطح المكتب.',
  'Choose a non-empty video file of up to 100 MB.': 'اختر ملف فيديو غير فارغ حتى 100 ميغابايت.',
  'Use a playable clip of up to 3 minutes. Very large dimensions are not supported.': 'استخدم مقطعًا قابلًا للتشغيل حتى 3 دقائق. الأبعاد الكبيرة جدًا غير مدعومة.',
  'Check the start and end: select at least 0.25 seconds within your clip.': 'تحقق من البداية والنهاية: حدد 0.25 ثانية على الأقل داخل مقطعك.',
  'Choose a speed between 0.5× and 2×.': 'اختر سرعة بين 0.5× و 2×.',
  'Use up to 100 characters and 3 lines of text.': 'استخدم حتى 100 حرف و 3 أسطر من النص.',
  'Choose a supported aspect ratio, framing and text position.': 'اختر نسبة عرض وتأطيرًا وموضع نص مدعومة.',
  'This file could not be decoded. Try an MP4 (H.264) or WebM file.': 'تعذر فك ترميز هذا الملف. جرّب ملف MP4 (H.264) أو WebM.',
  'Export stopped because this tab was hidden. Keep it open and visible, then export again. Your original is safe.': 'توقف التصدير لأن هذا التبويب كان مخفيًا. أبقه مفتوحًا وظاهرًا، ثم صدّر مجددًا. ملفك الأصلي في أمان.',
  'Export stopped making progress. Try a shorter clip or desktop Chrome. Your original is unchanged.': 'توقف التصدير عن التقدم. جرّب مقطعًا أقصر أو Chrome على سطح المكتب. ملفك الأصلي لم يتغير.',
  'Audio could not start. Try exporting again, or choose Mute video.': 'تعذر بدء الصوت. جرّب التصدير مجددًا أو اختر كتم صوت الفيديو.',
  'The browser blocked playback. Try exporting again from this tab.': 'حظر المتصفح التشغيل. جرّب التصدير مجددًا من هذا التبويب.',
  'Cancelled. Your original file is unchanged.': 'أُلغي. ملفك الأصلي لم يتغير.',
  'Could not finish this export. Try a shorter clip or another supported browser.': 'تعذر إكمال هذا التصدير. جرّب مقطعًا أقصر أو متصفحًا مدعومًا آخر.',
  'The browser produced an incomplete file, so we did not offer it for download. Try again with this tab visible, or use desktop Chrome.': 'أنتج المتصفح ملفًا غير مكتمل، لذا لم نعرضه للتنزيل. حاول مجددًا مع إبقاء هذا التبويب ظاهرًا، أو استخدم Chrome على سطح المكتب.',
  'Create new video': 'إنشاء فيديو جديد',
  'Your idea': 'فكرتك',
  'Natural': 'طبيعي',
  'Working…': 'جارٍ العمل…',
  '🎲 Surprise me': '🎲 فاجئني',
  '📝 Use my script as is': '📝 استخدم نصي كما هو',
  'Camera preset': 'إعداد الكاميرا المسبق',
  'Your latest videos': 'أحدث فيديوهاتك',
  'Presenter': 'المقدّم',
  '1 · Who’s talking': '1 · من يتكلم',
  '🎭 your characters': '🎭 شخصياتك',
  '🎯 Max realism — animate my real photo': '🎯 واقعية قصوى — حرّك صورتي الحقيقية',
  '✓ Scene ready — preview on the right.': '✓ المشهد جاهز — المعاينة على اليمين.',
  '2 · What they say': '2 · ماذا يقولون',
  '3 · How it looks': '3 · كيف يبدو',
  'Motion': 'الحركة',
  '⬇ Download MP4': '⬇ تنزيل MP4',
  'One photo. Suddenly alive.': 'صورة واحدة. وفجأة حيّة.',
  'Cost per clip': 'التكلفة لكل مقطع',
  '↺ Animate another': '↺ حرّك أخرى',
  'Grow': 'انمُ',
  'Sending to the motion engine…': 'جارٍ الإرسال إلى محرك الحركة…',
  '📊 Facts': '📊 حقائق',
  'Turn it into episode 2': 'حوّله إلى الحلقة 2',
  'Start here': 'ابدأ هنا',
  'Engine': 'المحرك',
  'Highly aesthetic, by xAI': 'جمالي للغاية، من xAI',
  'Google’s best image model': 'أفضل نموذج صور من Google',
  'AI voiceover included': 'تعليق صوتي بالذكاء الاصطناعي مضمّن',
  '6 engines': '6 محركات',
  'AI Presenter': 'مقدّم بالذكاء الاصطناعي',
  'Lock a character →': 'ثبّت شخصية →',
  'Make a clip →': 'اصنع مقطعًا →',
  'Make an ad →': 'اصنع إعلانًا →',
  'Generate free →': 'أنشئ مجانًا →',
  'Creating…': 'جارٍ الإنشاء…',
  'Describe your image first': 'صف صورتك أولًا',
  'Type your script first': 'اكتب نصك أولًا',
  'From the founder': 'من المؤسس',
  'Faceless video generator': 'مولّد فيديو بلا وجه',
  'Text to video Shorts': 'Shorts من النص إلى الفيديو',
  'Cheapest AI Shorts maker': 'أرخص صانع Shorts بالذكاء الاصطناعي',
  'Faceless channel ideas (2026)': 'أفكار قنوات بلا وجه (2026)',
  'Shorts idea widget': 'أداة أفكار Shorts',
  'Live case study: our channel on Autopilot': 'دراسة حالة حيّة: قناتنا على Autopilot',
  'Free YouTube Shorts scripts': 'نصوص YouTube Shorts مجانية',
  'Comment to Short script': 'من تعليق إلى نص Short',
  'Business video content planner': 'مخطط محتوى فيديو للشركات',
  'Real estate video maker': 'صانع فيديو للعقارات',
  'Shorts title & hashtag generator': 'مولّد عناوين ووسوم Shorts',
  'Free viral score': 'درجة انتشار مجانية',
  'Make money clipping with AI': 'اربح المال من القص بالذكاء الاصطناعي',
  'Shorts RPM by niche (2026)': 'RPM لـ Shorts حسب المجال (2026)',
  'Can you monetize AI videos?': 'هل يمكن الربح من فيديوهات الذكاء الاصطناعي؟',
}
