// KINEO-INTERFACE-16-LINGUAS-2026-09-21 — interface em de. Só copy autoral da interface: nunca prompt,
// título, resultado, nome de motor ou erro de API. Frase fora daqui cai em inglês (components/InterfaceLanguage.tsx).
// Gerado de scratchpad/tr-de.js sobre o corpus vivo de frases (415); números e "Kineo" preservados por construção.
export const DICT: Record<string, string> = {
  'Videos for businesses': 'Videos für Unternehmen',
  'Generation failed': 'Generierung fehlgeschlagen',
  'You can retry safely.': 'Du kannst es gefahrlos noch einmal versuchen.',
  'This engine is not available on your account right now': 'Diese Engine ist auf deinem Konto gerade nicht verfügbar',
  'Retrying the same engine will stop at this same place. Pick another engine to keep going.': 'Ein erneuter Versuch mit derselben Engine bleibt an derselben Stelle stehen. Wähle eine andere Engine, um weiterzumachen.',
  'The engine is cooling down after two refunded attempts': 'Die Engine kühlt nach zwei erstatteten Versuchen ab',
  'Starting another one right now stops at this same place. Give it a few minutes.': 'Jetzt noch einen zu starten bleibt an derselben Stelle stehen. Gib ihr ein paar Minuten.',
  'Starting another one right now stops at this same place. The button below unlocks by itself.': 'Jetzt noch einen zu starten bleibt an derselben Stelle stehen. Der Button unten schaltet sich von selbst frei.',
  'We stopped waiting on this render instead of leaving you hanging': 'Wir haben aufgehört, auf dieses Rendering zu warten, statt dich hängen zu lassen',
  'This one ran far longer than any video that finishes here. Starting again is worth it.': 'Dieses lief viel länger als jedes Video, das hier fertig wird. Ein Neustart lohnt sich.',
  'The video engine is busy — this is on our side, not your idea': 'Die Video-Engine ist ausgelastet — das liegt an uns, nicht an deiner Idee',
  'Nothing about your text is wrong. Trying again in a few minutes usually goes straight through.': 'An deinem Text ist nichts falsch. Ein erneuter Versuch in ein paar Minuten geht meist direkt durch.',
  'Create Video': 'Video erstellen',
  'Create a new video': 'Ein neues Video erstellen',
  'AI Avatar Studio': 'KI-Avatar-Studio',
  'Viral Templates': 'Virale Vorlagen',
  'Channel Builder': 'Kanal-Builder',
  'Invite & Earn': 'Einladen & verdienen',
  'Start free': 'Kostenlos starten',
  'Try 7 days for $1': '7 Tage für $1 testen',
  'Pick a lane': 'Wähle einen Weg',
  'All free tools': 'Alle kostenlosen Tools',
  'Terms of Service': 'Nutzungsbedingungen',
  'Trust Center': 'Trust Center',
  'Review & publish': 'Prüfen & veröffentlichen',
  'Your image': 'Dein Bild',
  'Cost per image': 'Kosten pro Bild',
  'No videos yet': 'Noch keine Videos',
  'No audio yet': 'Noch kein Audio',
  '🎬 Studio — generate video': '🎬 Studio — Video generieren',
  '🎨 Images — create image': '🎨 Bilder — Bild erstellen',
  '🎙 Audio — text to speech': '🎙 Audio — Text zu Sprache',
  'Type it. See it. Six image engines, one screen.': 'Tippen. Sehen. Sechs Bild-Engines, ein Bildschirm.',
  'Type it. Hear it. Four voice engines, one screen.': 'Tippen. Hören. Vier Stimm-Engines, ein Bildschirm.',
  'Everything you’ve created, in one place.': 'Alles, was du erstellt hast, an einem Ort.',
  'Add credits →': 'Credits hinzufügen →',
  'Upscale any result to 2x for 1 credit.': 'Jedes Ergebnis für 1 Credit auf 2x hochskalieren.',
  'We couldn’t load your images right now.': 'Deine Bilder konnten gerade nicht geladen werden.',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'Deine Bilder und Credits sind sicher — das ist nur ein vorübergehender Lesefehler.',
  'We couldn’t load your audio right now.': 'Dein Audio konnte gerade nicht geladen werden.',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'Dein Audio und deine Credits sind sicher — das ist nur ein vorübergehender Lesefehler.',
  'We couldn’t load part of your library right now.': 'Ein Teil deiner Bibliothek konnte gerade nicht geladen werden.',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'Deine Videos und Credits sind sicher — das ist nur ein vorübergehender Lesefehler.',
  '↻ Try again': '↻ Erneut versuchen',
  '⬇ Download': '⬇ Herunterladen',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': 'Gefällt dir eine Stimme? Das Studio baut den ganzen Film um sie herum — Bilder, Untertitel und Musik.',
  'Open Studio →': 'Studio öffnen →',
  'open the Studio': 'öffne das Studio',
  'Next episode →': 'Nächste Folge →',
  'create your first image': 'erstelle dein erstes Bild',
  'generate your first voiceover': 'generiere dein erstes Voiceover',
  'Instant drafts': 'Sofortige Entwürfe',
  'Deep prompt understanding': 'Tiefes Prompt-Verständnis',
  'Perfect text rendering': 'Perfekte Textdarstellung',
  'Create Image': 'Bild erstellen',
  'Click-magnet YouTube covers': 'YouTube-Cover, die Klicks anziehen',
  'Bring any image to life': 'Erwecke jedes Bild zum Leben',
  'Instant narration': 'Sofortige Erzählung',
  'Four voice engines': 'Vier Stimm-Engines',
  'A face that speaks your script': 'Ein Gesicht, das dein Skript spricht',
  'Every control, one screen': 'Jede Einstellung, ein Bildschirm',
  'Today’s trending topics': 'Die Trend-Themen von heute',
  'Real renders, every engine': 'Echte Renderings, jede Engine',
  'Type an idea — watch it become a film.': 'Tippe eine Idee — sieh zu, wie sie zum Film wird.',
  'Start with the full toolkit': 'Starte mit dem kompletten Werkzeugkasten',
  'Kineo’s own engine — 3–7 min': 'Kineos eigene Engine — 3–7 Min.',
  'The workhorse AI video engine': 'Die Arbeitspferd-Engine für KI-Video',
  'Cinematic motion & camera': 'Filmische Bewegung & Kamera',
  'Film scenes, native voice & lip sync': 'Filmszenen, native Stimme & Lippensynchronisation',
  'Talking video from one photo': 'Sprechendes Video aus einem Foto',
  'From idea to posted Short in 3 steps.': 'Von der Idee zum veröffentlichten Short in 3 Schritten.',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'Kein Filmen, kein Schneiden, keine Timeline. Einmal tippen — Kineo erledigt den Rest.',
  'Step 1': 'Schritt 1',
  'Kineo builds it': 'Kineo baut es',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'Die KI schreibt ein auf Retention ausgelegtes Skript, nimmt das Voiceover auf, passt das Bildmaterial an und brennt Untertitel ein — ein fertiges 9:16-Video.',
  'Download & post': 'Herunterladen & posten',
  'Why Kineo': 'Warum Kineo',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'Die meisten Tools schneiden ein langes Video neu, das du schon gefilmt hast. Kineo baut es von Grund auf.',
  'See how to make Shorts without filming →': 'So machst du Shorts ohne zu filmen →',
  'Generates the Short from just an idea': 'Generiert den Short aus nur einer Idee',
  'Writes the script for you': 'Schreibt das Skript für dich',
  'Finds and matches footage': 'Findet und passt Bildmaterial an',
  'your upload': 'dein Upload',
  'AI image studio included': 'KI-Bildstudio inklusive',
  'Voice studio (text-to-speech)': 'Stimmstudio (Text zu Sprache)',
  'One-click HD film enhance': 'HD-Filmverbesserung mit einem Klick',
  'One idea — or a whole toolkit.': 'Eine Idee — oder ein ganzer Werkzeugkasten.',
  'Try AI Presenter →': 'KI-Presenter ausprobieren →',
  'Transparent Clips': 'Transparente Clips',
  'UGC Product Ads': 'UGC-Produktanzeigen',
  'Animate a photo →': 'Foto animieren →',
  'Make a thumbnail →': 'Thumbnail erstellen →',
  'Free AI Shorts': 'Kostenlose KI-Shorts',
  'Start with a niche that already works.': 'Starte mit einer Nische, die schon funktioniert.',
  'Not sure? Take the quiz →': 'Unsicher? Mach das Quiz →',
  'Pick your engine. Ship a Short today.': 'Wähle deine Engine. Veröffentliche heute einen Short.',
  'Cancel anytime': 'Jederzeit kündbar',
  'Generate image →': 'Bild generieren →',
  'Generate audio →': 'Audio generieren →',
  'Paid plans unlock clean MP4s.': 'Bezahlte Pläne schalten saubere MP4s frei.',
  'Best for starting out': 'Ideal für den Einstieg',
  'Best value per film': 'Bester Wert pro Film',
  'on Nano Banana': 'auf Nano Banana',
  'Every video engine incl. MiniMax H3': 'Jede Video-Engine inkl. MiniMax H3',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'MP4 ohne Wasserzeichen · 100 Projekte · 90 Tage Speicher',
  ', finished': ', fertig',
  '— every engine unlocked': '— jede Engine freigeschaltet',
  '· voice + karaoke captions + score': '· Stimme + Karaoke-Untertitel + Musik',
  '500 projects · forever storage': '500 Projekte · dauerhafter Speicher',
  'Cancel anytime — 7-day money-back': 'Jederzeit kündbar — 7 Tage Geld-zurück',
  'films on Omni Flash': 'Filme auf Omni Flash',
  '· 2 free HD enhances / month': '· 2 kostenlose HD-Verbesserungen / Monat',
  'Unlimited projects · forever storage': 'Unbegrenzte Projekte · dauerhafter Speicher',
  'Everything in Creator': 'Alles aus Creator',
  'Calculate your cost per Short →': 'Berechne deine Kosten pro Short →',
  'How much do Shorts pay? →': 'Wie viel zahlen Shorts? →',
  'Highest-RPM niches →': 'Nischen mit dem höchsten RPM →',
  'read the full review →': 'die vollständige Bewertung lesen →',
  'a single line is enough — or paste a full script': 'eine einzige Zeile reicht — oder füge ein komplettes Skript ein',
  '1080×1920 · Full HD master': '1080×1920 · Full-HD-Master',
  'Every film is delivered as a 1080×1920 Full HD master (engines render natively at 720–768p and are mastered up). For maximum sharpness, run ✨HD Enhance on the finished film.': 'Jeder Film wird als 1080×1920-Full-HD-Master geliefert (die Engines rendern nativ in 720–768p und werden hochgemastert). Für maximale Schärfe lass ✨HD Enhance über den fertigen Film laufen.',
  'Your idea first. Review the settings, then generate.': 'Zuerst deine Idee. Prüfe die Einstellungen, dann generiere.',
  '📷 Photo': '📷 Foto',
  '🖼️ Upload a different photo': '🖼️ Anderes Foto hochladen',
  '🎙️ Generating…': '🎙️ Wird generiert…',
  '🎙️ Cloning the voice…': '🎙️ Stimme wird geklont…',
  '🎙️ Upload a different sample': '🎙️ Andere Probe hochladen',
  '⏹ Stop & clone': '⏹ Stoppen & klonen',
  '🎭 Generate my avatar video': '🎭 Mein Avatar-Video generieren',
  'Continue exactly where ChatGPT stopped.': 'Mach genau da weiter, wo ChatGPT aufgehört hat.',
  '✨ Let AI structure it': '✨ KI strukturieren lassen',
  'Optional settings': 'Optionale Einstellungen',
  'optional — a pre-tested move added to your prompt': 'optional — eine vorgetestete Bewegung, die deinem Prompt hinzugefügt wird',
  'Reference image': 'Referenzbild',
  '🖼️ Start your video from an image — coming soon': '🖼️ Starte dein Video aus einem Bild — bald verfügbar',
  'Estimated cost': 'Geschätzte Kosten',
  'Your credits buy': 'Deine Credits reichen für',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'Stimme, Karaoke-Untertitel und Musik inklusive. Schlägt ein Rendering fehl, kommen deine Credits sofort zurück.',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'Gleiches Thema, neuer Hook und neue Pointe — die Idee ist schon vorgeschrieben.',
  'Build next episode →': 'Nächste Folge bauen →',
  'Episode 2 →': 'Folge 2 →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'Sprechender KI-Presenter aus einem Foto — lippensynchron, eigenes Studio',
  'Your face. Your script.': 'Dein Gesicht. Dein Skript.',
  'Everything you need to make yourself speak — nothing you don’t.': 'Alles, was du brauchst, um dich sprechen zu lassen — nichts, was du nicht brauchst.',
  'BEST MOTION': 'BESTE BEWEGUNG',
  '1.5 · Realism': '1.5 · Realismus',
  '🎬 Put me in a scene': '🎬 Setz mich in eine Szene',
  'use original photo': 'Originalfoto verwenden',
  '✍️ Say exactly this — word for word': '✍️ Sag genau das — Wort für Wort',
  '✨ Expand into a full Short script (45–60s)': '✨ Zu einem kompletten Short-Skript ausbauen (45–60 s)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 Produktanzeigen-Modus — ein Produkt im UGC-Stil verkaufen',
  'Free — fills the script box above, then generate with your presenter.': 'Kostenlos — füllt das Skriptfeld oben, dann generiere mit deinem Presenter.',
  '2.5 · Speak in your own voice': '2.5 · Sprich mit deiner eigenen Stimme',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ Stimme geklont — die Erzählung spricht mit dieser Stimme.',
  'use a default voice': 'Standardstimme verwenden',
  '🎬 Full video — face the whole time': '🎬 Ganzes Video — Gesicht die ganze Zeit',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 KI-Presenter — schnell & natürlich · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro — Premium-Fotoqualität · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 Body Motion — Oberkörper, Hände & Gesten · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ Klassisch — Talking Head · 110 cr',
  'you have': 'du hast',
  'to create your avatar video.': 'um dein Avatar-Video zu erstellen.',
  '5 · Gesture clips — transparent background': '5 · Gesten-Clips — transparenter Hintergrund',
  'auto-refunded if it fails': 'automatische Erstattung bei Fehlschlag',
  '⬇️ Download transparent WebM': '⬇️ Transparentes WebM herunterladen',
  '⬇️ Original MP4 (with background)': '⬇️ Original-MP4 (mit Hintergrund)',
  'Pick a face to preview': 'Wähle ein Gesicht für die Vorschau',
  '↺ Make another': '↺ Noch eins machen',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'Menschen, Haustiere, Produkte, alte Familienbilder — lade ein Foto hoch oder füge einen öffentlichen Bildlink ein und sieh zu, wie es sich bewegt.',
  'The photo': 'Das Foto',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': 'JPG/PNG bis 8 MB. Öffentliche Links werden sicher auf unserem Server heruntergeladen und geprüft.',
  'sign in': 'anmelden',
  'Kineo will fetch and validate it on the server when you animate.': 'Kineo holt und prüft es auf dem Server, wenn du animierst.',
  'Upload a photo to preview': 'Lade ein Foto für die Vorschau hoch',
  '🖼️ Upload a photo': '🖼️ Foto hochladen',
  '✨ Bring it to life': '✨ Zum Leben erwecken',
  'Uploading your photo…': 'Dein Foto wird hochgeladen…',
  'Bringing your photo to life… (1–3 min)': 'Dein Foto wird zum Leben erweckt… (1–3 Min.)',
  'Alive!': 'Lebendig!',
  '🌬️ Subtle & real': '🌬️ Subtil & echt',
  '😊 Person comes alive': '😊 Person wird lebendig',
  'Type your idea first': 'Tippe zuerst deine Idee',
  '📖 True Story': '📖 Wahre Geschichte',
  'Paste your ChatGPT script': 'Füge dein ChatGPT-Skript ein',
  'First Short complete': 'Erster Short fertig',
  'Keep your show moving': 'Halte deine Show am Laufen',
  'Cheapest way to see your idea as a film': 'Der günstigste Weg, deine Idee als Film zu sehen',
  'Slow Dolly-In': 'Langsames Dolly-In',
  'FPV Drone': 'FPV-Drohne',
  'Macro Detail': 'Makro-Detail',
  'Sharing & creator options': 'Teilen & Creator-Optionen',
  'We couldn’t load your videos right now': 'Deine Videos konnten gerade nicht geladen werden',
  'Your videos and credits are safe — this is a temporary read hiccup, not a lost library.': 'Deine Videos und Credits sind sicher — das ist ein vorübergehender Lesefehler, keine verlorene Bibliothek.',
  '⚡ Generate Video': '⚡ Video generieren',
  'Prefer clean exports now? Starter includes': 'Lieber jetzt saubere Exporte? Starter enthält',
  'credits each month for': 'Credits pro Monat für',
  'Your existing files stay available. Starter applies to new exports after checkout.': 'Deine vorhandenen Dateien bleiben verfügbar. Starter gilt für neue Exporte nach dem Checkout.',
  'Build Next Episode First': 'Erst die nächste Folge bauen',
  'Video unavailable': 'Video nicht verfügbar',
  'Free MP4 includes the Kineo watermark': 'Das kostenlose MP4 enthält das Kineo-Wasserzeichen',
  'Free distribution · latest Short': 'Kostenlose Verbreitung · neuester Short',
  'Send it to one person for feedback': 'Schick es einer Person für Feedback',
  'Copy a public watch page for your finished video. Your friend can watch it without logging in, then use “Make one like this” if the idea inspires them.': 'Kopiere eine öffentliche Ansichtsseite für dein fertiges Video. Dein Freund kann es ohne Anmeldung ansehen und dann „Eins wie dieses machen“ nutzen, wenn die Idee inspiriert.',
  'Public watch links are temporarily paused': 'Öffentliche Ansichtslinks sind vorübergehend pausiert',
  'Your video stays in your account. Download the MP4 if you want to send it directly; Kineo will not publish a public page without an explicit visibility choice.': 'Dein Video bleibt in deinem Konto. Lade das MP4 herunter, wenn du es direkt verschicken willst; Kineo veröffentlicht keine öffentliche Seite ohne eine ausdrückliche Sichtbarkeitsentscheidung.',
  'Loading…': 'Wird geladen…',
  'For new videos ·': 'Für neue Videos ·',
  'Published it?': 'Veröffentlicht?',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'Scharf, frontal, eine Person. Für Körperbewegung ein Foto ab Hüfte oder in Ganzkörperansicht mit beiden Händen sichtbar verwenden. Schwarze Balken werden automatisch entfernt.',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'Bestes professionelles Ergebnis: lade einen vertikalen 5–20-s-Clip mit den echten gewünschten Gesten hoch, ungefähr so lang wie das Skript. Sync-3 ersetzt die Sprache und bewahrt das echte Gesicht und die Körperbewegung. MP4/MOV bis 40 MB.',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'Ich bestätige, dass ich das Recht habe, das Bild dieser Person zu nutzen, und stimme zu, dass es per KI animiert wird.',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': 'Lade eine klare Stimmprobe von ~30-60 s hoch (ein Sprecher, wenig Hintergrundgeräusche) und die Erzählung wird mit dieser Stimme gesprochen. Nutze nur eine Stimme, die du nutzen darfst.',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'Wort-für-Wort-Videos zeigen dein Gesicht die ganze Zeit (sie sind kurz — kein B-Roll nötig).',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'Videos mit maximalem Realismus und gebauter Szene behalten den Presenter während der gesamten Erzählung im Bild.',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ Hook-Intro — du eröffnest, B-Roll erzählt die Geschichte',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'Kurze Clips deines Presenters beim Winken, Zeigen, Präsentieren — als WebM mit ECHTEM transparentem Hintergrund. Direkt in Storyline, Premiere, CapCut oder jede Folie ziehen. Kein Greenscreen, kein Keying.',
  'Cinematic film — 9-image consistency': 'Filmischer Film — Konsistenz über 9 Bilder',
  '#1-ranked video model — Aug 2026 arena': 'Videomodell auf Platz 1 — Arena Aug. 2026',
  'Cinematic motion and camera work': 'Filmische Bewegung und Kameraarbeit',
  'Shorts money & growth': 'Geld & Wachstum mit Shorts',
  'Compare Kineo with 27 AI video tools →': 'Vergleiche Kineo mit 27 KI-Video-Tools →',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'Sprechende Presenter, wiederverwendbare Charaktere, transparente Clips, Produktanzeigen — plus alles, um einen Trend zu finden und zu reiten.',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'Ein Foto + dein Skript — ein sprechendes Video mit Lippensynchronisation in Studioqualität, im HeyGen-Stil.',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'Speichere einen Charakter einmal — exakt dasselbe Gesicht in jedem Video und Thumbnail, das du machst.',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'Presenter-Gesten — winken, zeigen, präsentieren — als WebM mit echtem transparentem Hintergrund.',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'Füge ein beliebiges Produkt ein — erhalte eine 15-30-s-Anzeige im Creator-Stil, geskriptet und eingesprochen.',
  'Bring any still photo to life as a moving, postable video.': 'Erwecke jedes Standbild als bewegtes, postbares Video zum Leben.',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'Klickstarke Thumbnails im Stil der größten Kanäle — aus einem Prompt.',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'Jede Nische unten hat ihre eigene Generator-Seite, abgestimmte Prompts und echte Beispiele.',
  'Is the video really mine to post?': 'Gehört das Video wirklich mir, um es zu posten?',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'Bezahlte Pläne schalten das saubere MP4 ohne Wasserzeichen für YouTube, TikTok oder Reels frei.',
  'Do I need any editing skills?': 'Brauche ich Schnittkenntnisse?',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'Keine. Du tippst eine Idee und die KI schreibt das Skript, nimmt die Stimme auf, findet das Bildmaterial und fügt Untertitel hinzu.',
  'Is there a watermark?': 'Gibt es ein Wasserzeichen?',
  'Paid plans export clean, watermark-free MP4s.': 'Bezahlte Pläne exportieren saubere MP4s ohne Wasserzeichen.',
  'Can Kineo also generate images and voiceovers?': 'Kann Kineo auch Bilder und Voiceovers generieren?',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'Ja — Kineo enthält ein KI-Bildstudio (6 Engines inkl. FLUX, Seedream und Nano Banana Pro, ab 1 Credit pro Bild) und ein Stimmstudio mit 4 Text-zu-Sprache-Engines (ab 1 Credit pro 1000 Zeichen). Alles, was du erstellst, liegt in deiner Bibliothek.',
  'Can I make my videos sharper?': 'Kann ich meine Videos schärfer machen?',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'Jedes Video hat eine Ein-Klick-Verbesserung mit Topaz-Filmrestaurierung — sie entfernt Kompressionsartefakte, holt Details zurück und fügt feines Filmkorn hinzu. 10 Credits pro Video; der Studio-Plan enthält 2 kostenlose Verbesserungen pro Monat.',
  'Can I use my own script?': 'Kann ich mein eigenes Skript verwenden?',
  'What if a generation fails?': 'Was, wenn eine Generierung fehlschlägt?',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'Deine Credits kommen automatisch zurück, sobald ein Rendering fehlschlägt — kein Support-Ticket, kein Warten. Du zahlst nur für Videos, die du wirklich bekommst.',
  'Can I cancel anytime?': 'Kann ich jederzeit kündigen?',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'Jederzeit, mit einem Klick. Pläne laufen monatlich und deine Credits werden jeden Monat aufgefrischt.',
  'Can I run a whole channel with the same host?': 'Kann ich einen ganzen Kanal mit demselben Host betreiben?',
  'Can I monetize the videos?': 'Kann ich die Videos monetarisieren?',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'Ja. Jedes Video gehört dir — behalten, posten und monetarisieren, auch im YouTube-Partnerprogramm, auf TikTok und Reels. Keine zusätzliche Lizenz nötig.',
  'Can I use the videos commercially, or for client work?': 'Kann ich die Videos kommerziell oder für Kundenarbeit nutzen?',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'Ja. Unsere Bedingungen erlauben die Nutzung von Kineo für rechtmäßige private oder kommerzielle Zwecke und bestätigen, dass du Eigentümer der generierten Videos bleibst — du kannst sie posten, monetarisieren und als Teil deiner eigenen bezahlten Leistung an einen Kunden liefern. Keine zusätzliche Lizenz, keine Gebühr pro Video. Zwei Grenzen ergeben sich aus denselben Bedingungen: Du darfst Kineo selbst nicht weiterverkaufen oder weiterverbreiten, und die Stock-Clips in einem Rendering sind für dein fertiges Video lizenziert, nicht für den erneuten Upload als eigenständiges Stock-Material. Bezahlte Pläne exportieren das saubere MP4 ohne Wasserzeichen.',
  'How long does one video take?': 'Wie lange dauert ein Video?',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'Der Fast-Modus ist meist in 3–7 Minuten fertig. KI-generierte und filmische Videos dauern etwas länger, weil jede Szene generiert wird, bevor das finale MP4 zusammengesetzt wird.',
  'How much does Kineo cost?': 'Was kostet Kineo?',
  'Kineo has three monthly plans: Starter at $': 'Kineo hat drei Monatspläne: Starter ab $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'Credits. Credits werden pro Video ausgegeben, und wie viele ein Video kostet, hängt von der gewählten Engine ab — ein Fast-Rendering und ein filmischer Film kommen aus demselben Guthaben, zu sehr unterschiedlichen Preisen.',
  'Which AI video engines can I use in Kineo?': 'Welche KI-Video-Engines kann ich in Kineo nutzen?',
  ', behind one interface and one balance:': ', hinter einer Oberfläche und einem Guthaben:',
  'What is the best AI video generator for faceless YouTube channels?': 'Was ist der beste KI-Videogenerator für gesichtslose YouTube-Kanäle?',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'Ja. Kostenlose Nutzer, die nie bezahlt haben, können das MP4 mit Wasserzeichen herunterladen, teilen und posten.',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'Testfilme tragen ein kleines Wasserzeichen — du kannst das MP4 herunterladen, teilen und posten. Nach dem Test trägt das kostenlose Fast-Video ein Wasserzeichen.',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'Kostenlose Downloads tragen ein Wasserzeichen; bezahlte Pläne schalten das saubere MP4 frei.',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'Test-Downloads tragen ein Wasserzeichen, ebenso das kostenlose Fast-Video nach dem Test, und bezahlte Pläne exportieren immer sauber.',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'Der kostenlose Zugang gibt neuen Nutzern bis zu 3 Fast-Videos mit Wasserzeichen alle 24 Stunden, ohne Karte. Du kannst sie herunterladen und teilen.',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'Erstelle, lade herunter und teile bis zu 3 Fast-Videos mit Wasserzeichen alle 24 h, ohne Karte.',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'Erstelle, sieh an, lade herunter und teile bis zu 3 Fast-Videos mit Wasserzeichen alle 24 h — ohne Karte.',
  'create, watch, download and share up to 3 Fast videos every 24h': 'erstelle, sieh an, lade herunter und teile bis zu 3 Fast-Videos alle 24 h',
  '— no card, watermark included.': '— ohne Karte, Wasserzeichen inklusive.',
  'AI image generator — 6 engines': 'KI-Bildgenerator — 6 Engines',
  'AI voice generator (text to speech)': 'KI-Stimmgenerator (Text zu Sprache)',
  'AI video upscaler & enhancer': 'KI-Video-Upscaler & -Verbesserer',
  'Trending Shorts ideas today': 'Trend-Ideen für Shorts heute',
  'AI Avatar video — your face, any script': 'KI-Avatar-Video — dein Gesicht, jedes Skript',
  'Kineo facts & numbers (citable)': 'Kineo-Fakten & Zahlen (zitierbar)',
  'Free AI Shorts generator': 'Kostenloser KI-Shorts-Generator',
  'YouTube Shorts from a topic': 'YouTube Shorts aus einem Thema',
  'ChatGPT script to YouTube Short': 'ChatGPT-Skript zu YouTube Short',
  'Shorts without filming': 'Shorts ohne Filmen',
  'Faceless niche picker': 'Nischen-Finder für gesichtslose Kanäle',
  'State of AI Shorts 2026': 'State of AI Shorts 2026',
  'AI Shorts for agencies & client work': 'KI-Shorts für Agenturen & Kundenarbeit',
  'Trust Center — privacy, payments & ownership': 'Trust Center — Datenschutz, Zahlungen & Eigentum',
  'Affiliate program - 30% recurring': 'Partnerprogramm - 30 % wiederkehrend',
  'Free AI Shorts by niche': 'Kostenlose KI-Shorts nach Nische',
  'Free script generator': 'Kostenloser Skript-Generator',
  'Product video ad script': 'Skript für Produkt-Videoanzeige',
  'Client video brief generator': 'Generator für Kunden-Videobriefings',
  'Free hook generator': 'Kostenloser Hook-Generator',
  'Shorts script timer': 'Shorts-Skript-Timer',
  'Shorts money calculator': 'Shorts-Einnahmenrechner',
  'How much do Shorts pay?': 'Wie viel zahlen Shorts?',
  'Best AI Shorts generators': 'Beste KI-Shorts-Generatoren',
  'TikTok vs Shorts: which pays more?': 'TikTok vs. Shorts: was zahlt mehr?',
  'All comparisons': 'Alle Vergleiche',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · Alle Rechte vorbehalten',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'Das hängt davon ab, ob du zusammengeschnittenes Stock-Material oder generiertes Material willst. Tools wie InVideo und AutoShorts schneiden Stock-Clips auf dein Skript — günstiger und für Talking-Point-Videos ausreichend. Kineo generiert das Material mit Modellen wie Veo 3.1 und Kling 3, behält deine Erzählung Wort für Wort statt sie umzuschreiben, und zielt auf 60 Sekunden oder mehr, damit das Video für TikTok Creator Rewards qualifiziert. Lebt dein Kanal von Bildern, die niemand sonst hat, gewinnt die Generierung; lebt er von Volumen, ist Stock günstiger.',
  'Paste the complete script from ChatGPT here…': 'Füge hier das komplette Skript aus ChatGPT ein…',
  'Paste the idea from ChatGPT here…': 'Füge hier die Idee aus ChatGPT ein…',
  'What’s your video about? One idea in — a finished film out: voiced, scored and captioned.': 'Worum geht es in deinem Video? Eine Idee rein — ein fertiger Film raus: vertont, mit Musik und Untertiteln.',
  'Settings and generation': 'Einstellungen und Generierung',
  'Search your videos…': 'Deine Videos durchsuchen…',
  'Search your audio…': 'Dein Audio durchsuchen…',
  'Search your images by engine': 'Deine Bilder nach Engine durchsuchen',
  'No playable videos in your library yet. Check your latest project above.': 'Noch keine abspielbaren Videos in deiner Bibliothek. Sieh dir dein neuestes Projekt oben an.',
  'Make a finished Short →': 'Einen fertigen Short machen →',
  'Video Editing & Creator Tools': 'Videobearbeitung & Creator-Tools',
  'Trim, resize, change speed, mute or add text. Edit a file you already have, right in your browser. Your script and planning tools are still here below.': 'Schneiden, skalieren, Geschwindigkeit ändern, stummschalten oder Text hinzufügen. Bearbeite eine Datei, die du schon hast, direkt im Browser. Deine Skript- und Planungstools findest du weiter unten.',
  '5 local editing tools': '5 lokale Bearbeitungstools',
  'No generation credits to edit': 'Keine Generierungs-Credits fürs Bearbeiten',
  'Edit video': 'Video bearbeiten',
  'Files up to 100 MB and 3 minutes. Local, real-time export up to 1280 px on the long edge. MP4 or WebM depending on your browser; downloads are not saved to My Videos.': 'Dateien bis 100 MB und 3 Minuten. Lokaler Echtzeit-Export bis 1280 px an der langen Kante. MP4 oder WebM je nach Browser; Downloads werden nicht in Meine Videos gespeichert.',
  'Video Trimmer': 'Video-Trimmer',
  'Cut the beginning or end and keep only the clip you need.': 'Anfang oder Ende abschneiden und nur den Clip behalten, den du brauchst.',
  'Video Resizer': 'Video-Resizer',
  'Go vertical, square or wide. Fit the frame or crop to fill.': 'Hochkant, quadratisch oder breit. Ins Bild einpassen oder zum Füllen zuschneiden.',
  'Video Speed Changer': 'Video-Geschwindigkeit ändern',
  'Slow it down or speed it up, from 0.5× to 2×.': 'Verlangsamen oder beschleunigen, von 0.5× bis 2×.',
  'Remove Audio': 'Audio entfernen',
  'Download a copy without the original audio.': 'Eine Kopie ohne das Original-Audio herunterladen.',
  'Add Text to Video': 'Text zum Video hinzufügen',
  'Add a title or message that stays on screen. Not automatic subtitles.': 'Füge einen Titel oder eine Nachricht hinzu, die im Bild bleibt. Keine automatischen Untertitel.',
  'No account · current Kineo plans': 'Kein Konto · aktuelle Kineo-Pläne',
  'No account · fair-use limit': 'Kein Konto · Fair-Use-Limit',
  'No account · unlimited in browser': 'Kein Konto · unbegrenzt im Browser',
  'Edit an existing video here. Create a new one with Kineo.': 'Bearbeite hier ein vorhandenes Video. Erstelle ein neues mit Kineo.',
  'Create an AI video →': 'KI-Video erstellen →',
  'Edit your video, preview the changes, then export a copy.': 'Bearbeite dein Video, prüfe die Änderungen in der Vorschau und exportiere dann eine Kopie.',
  'Video preview': 'Videovorschau',
  'Preview is silent. The download keeps audio unless Mute is selected.': 'Die Vorschau ist stumm. Der Download behält das Audio, sofern nicht Stumm gewählt ist.',
  'Start with your video': 'Starte mit deinem Video',
  'Choose a local file. It stays on this device.': 'Wähle eine lokale Datei. Sie bleibt auf diesem Gerät.',
  'Choose video file': 'Videodatei wählen',
  'Video file': 'Videodatei',
  'Video settings': 'Videoeinstellungen',
  'Aspect ratio': 'Seitenverhältnis',
  'Playback speed': 'Wiedergabegeschwindigkeit',
  'On-screen text (100 characters, 3 lines)': 'Text im Bild (100 Zeichen, 3 Zeilen)',
  'Add a title or message': 'Titel oder Nachricht hinzufügen',
  'Export edited video': 'Bearbeitetes Video exportieren',
  'Export happens in real time. Keep this tab visible. Re-encoded at up to 1280 px on the long edge; format depends on your browser.': 'Der Export läuft in Echtzeit. Lass diesen Tab sichtbar. Neu kodiert bis 1280 px an der langen Kante; das Format hängt vom Browser ab.',
  'Making a 4-second sample on your device…': 'Eine 4-Sekunden-Probe wird auf deinem Gerät erstellt…',
  'Reading your file…': 'Deine Datei wird gelesen…',
  'Export result': 'Exportergebnis',
  'Your edited video': 'Dein bearbeitetes Video',
  'Local download only. This copy is not saved to My Videos.': 'Nur lokaler Download. Diese Kopie wird nicht in Meine Videos gespeichert.',
  'Exported video': 'Exportiertes Video',
  'No upload. No generation credits. Your original is never overwritten.': 'Kein Upload. Keine Generierungs-Credits. Dein Original wird nie überschrieben.',
  'Up to 100 MB · 3 minutes · MP4/WebM input recommended. These are basic editing tools, not the CapCut app.': 'Bis 100 MB · 3 Minuten · MP4/WebM als Eingabe empfohlen. Das sind einfache Bearbeitungstools, nicht die CapCut-App.',
  'Need a new video? Open Kineo Studio →': 'Neues Video nötig? Öffne Kineo Studio →',
  'This browser cannot export video here. Try the latest desktop Chrome or Edge.': 'Dieser Browser kann hier kein Video exportieren. Probiere das neueste Desktop-Chrome oder -Edge.',
  'Choose a non-empty video file of up to 100 MB.': 'Wähle eine nicht leere Videodatei bis 100 MB.',
  'Use a playable clip of up to 3 minutes. Very large dimensions are not supported.': 'Verwende einen abspielbaren Clip bis 3 Minuten. Sehr große Abmessungen werden nicht unterstützt.',
  'Check the start and end: select at least 0.25 seconds within your clip.': 'Prüfe Anfang und Ende: wähle mindestens 0.25 Sekunden innerhalb deines Clips.',
  'Choose a speed between 0.5× and 2×.': 'Wähle eine Geschwindigkeit zwischen 0.5× und 2×.',
  'Use up to 100 characters and 3 lines of text.': 'Verwende höchstens 100 Zeichen und 3 Textzeilen.',
  'Choose a supported aspect ratio, framing and text position.': 'Wähle ein unterstütztes Seitenverhältnis, einen Bildausschnitt und eine Textposition.',
  'This file could not be decoded. Try an MP4 (H.264) or WebM file.': 'Diese Datei konnte nicht dekodiert werden. Probiere eine MP4- (H.264) oder WebM-Datei.',
  'Export stopped because this tab was hidden. Keep it open and visible, then export again. Your original is safe.': 'Der Export wurde gestoppt, weil dieser Tab ausgeblendet war. Lass ihn offen und sichtbar und exportiere erneut. Dein Original ist sicher.',
  'Export stopped making progress. Try a shorter clip or desktop Chrome. Your original is unchanged.': 'Der Export macht keine Fortschritte mehr. Probiere einen kürzeren Clip oder Desktop-Chrome. Dein Original ist unverändert.',
  'Audio could not start. Try exporting again, or choose Mute video.': 'Audio konnte nicht starten. Exportiere erneut oder wähle Video stummschalten.',
  'The browser blocked playback. Try exporting again from this tab.': 'Der Browser hat die Wiedergabe blockiert. Exportiere erneut aus diesem Tab.',
  'Cancelled. Your original file is unchanged.': 'Abgebrochen. Deine Originaldatei ist unverändert.',
  'Could not finish this export. Try a shorter clip or another supported browser.': 'Dieser Export konnte nicht abgeschlossen werden. Probiere einen kürzeren Clip oder einen anderen unterstützten Browser.',
  'The browser produced an incomplete file, so we did not offer it for download. Try again with this tab visible, or use desktop Chrome.': 'Der Browser hat eine unvollständige Datei erzeugt, deshalb haben wir sie nicht zum Download angeboten. Versuche es erneut mit sichtbarem Tab oder nutze Desktop-Chrome.',
  'Create new video': 'Neues Video erstellen',
  'Your idea': 'Deine Idee',
  'Natural': 'Natürlich',
  'Working…': 'Arbeitet…',
  '🎲 Surprise me': '🎲 Überrasch mich',
  '📝 Use my script as is': '📝 Mein Skript unverändert verwenden',
  'Camera preset': 'Kamera-Preset',
  'Your latest videos': 'Deine neuesten Videos',
  'Presenter': 'Presenter',
  '1 · Who’s talking': '1 · Wer spricht',
  '🎭 your characters': '🎭 deine Charaktere',
  '🎯 Max realism — animate my real photo': '🎯 Maximaler Realismus — mein echtes Foto animieren',
  '✓ Scene ready — preview on the right.': '✓ Szene bereit — Vorschau rechts.',
  '2 · What they say': '2 · Was sie sagen',
  '3 · How it looks': '3 · Wie es aussieht',
  'Motion': 'Bewegung',
  '⬇ Download MP4': '⬇ MP4 herunterladen',
  'One photo. Suddenly alive.': 'Ein Foto. Plötzlich lebendig.',
  'Cost per clip': 'Kosten pro Clip',
  '↺ Animate another': '↺ Noch eins animieren',
  'Grow': 'Wachsen',
  'Sending to the motion engine…': 'Wird an die Bewegungs-Engine gesendet…',
  '📊 Facts': '📊 Fakten',
  'Turn it into episode 2': 'Zu Folge 2 machen',
  'Start here': 'Hier starten',
  'Engine': 'Engine',
  'Highly aesthetic, by xAI': 'Sehr ästhetisch, von xAI',
  'Google’s best image model': 'Googles bestes Bildmodell',
  'AI voiceover included': 'KI-Voiceover inklusive',
  '6 engines': '6 Engines',
  'AI Presenter': 'KI-Presenter',
  'Lock a character →': 'Charakter festlegen →',
  'Make a clip →': 'Clip erstellen →',
  'Make an ad →': 'Anzeige erstellen →',
  'Generate free →': 'Kostenlos generieren →',
  'Creating…': 'Wird erstellt…',
  'Describe your image first': 'Beschreibe zuerst dein Bild',
  'Type your script first': 'Tippe zuerst dein Skript',
  'From the founder': 'Vom Gründer',
  'Faceless video generator': 'Generator für gesichtslose Videos',
  'Text to video Shorts': 'Text-zu-Video-Shorts',
  'Cheapest AI Shorts maker': 'Günstigster KI-Shorts-Maker',
  'Faceless channel ideas (2026)': 'Ideen für gesichtslose Kanäle (2026)',
  'Shorts idea widget': 'Shorts-Ideen-Widget',
  'Live case study: our channel on Autopilot': 'Live-Fallstudie: unser Kanal auf Autopilot',
  'Free YouTube Shorts scripts': 'Kostenlose YouTube-Shorts-Skripte',
  'Comment to Short script': 'Vom Kommentar zum Short-Skript',
  'Business video content planner': 'Videocontent-Planer für Unternehmen',
  'Real estate video maker': 'Video-Maker für Immobilien',
  'Shorts title & hashtag generator': 'Titel- & Hashtag-Generator für Shorts',
  'Free viral score': 'Kostenloser Viral-Score',
  'Make money clipping with AI': 'Geld verdienen mit KI-Clipping',
  'Shorts RPM by niche (2026)': 'Shorts-RPM nach Nische (2026)',
  'Can you monetize AI videos?': 'Kann man KI-Videos monetarisieren?',
}
