// KINEO-INTERFACE-16-LINGUAS-2026-09-21 — interface em fr. Só copy autoral da interface: nunca prompt,
// título, resultado, nome de motor ou erro de API. Frase fora daqui cai em inglês (components/InterfaceLanguage.tsx).
// Gerado de scratchpad/tr-fr.js sobre o corpus vivo de frases (415); números e "Kineo" preservados por construção.
export const DICT: Record<string, string> = {
  'Videos for businesses': 'Vidéos pour entreprises',
  'Generation failed': 'La génération a échoué',
  'You can retry safely.': 'Vous pouvez réessayer sans risque.',
  'This engine is not available on your account right now': 'Ce moteur n’est pas disponible sur votre compte pour le moment',
  'Retrying the same engine will stop at this same place. Pick another engine to keep going.': 'Réessayer avec le même moteur s’arrêtera au même endroit. Choisissez un autre moteur pour continuer.',
  'The engine is cooling down after two refunded attempts': 'Le moteur refroidit après deux tentatives remboursées',
  'Starting another one right now stops at this same place. Give it a few minutes.': 'En lancer une autre maintenant s’arrête au même endroit. Patientez quelques minutes.',
  'Starting another one right now stops at this same place. The button below unlocks by itself.': 'En lancer une autre maintenant s’arrête au même endroit. Le bouton ci-dessous se débloque tout seul.',
  'We stopped waiting on this render instead of leaving you hanging': 'Nous avons cessé d’attendre ce rendu plutôt que de vous laisser sans réponse',
  'This one ran far longer than any video that finishes here. Starting again is worth it.': 'Celui-ci a duré bien plus longtemps que toute vidéo qui aboutit ici. Recommencer en vaut la peine.',
  'The video engine is busy — this is on our side, not your idea': 'Le moteur vidéo est occupé — c’est de notre côté, pas de votre idée',
  'Nothing about your text is wrong. Trying again in a few minutes usually goes straight through.': 'Votre texte n’a rien d’anormal. Réessayer dans quelques minutes passe généralement du premier coup.',
  'Create Video': 'Créer une vidéo',
  'Create a new video': 'Créer une nouvelle vidéo',
  'AI Avatar Studio': 'Studio d’avatar IA',
  'Viral Templates': 'Modèles viraux',
  'Channel Builder': 'Créateur de chaîne',
  'Invite & Earn': 'Parrainez et gagnez',
  'Start free': 'Commencer gratuitement',
  'Try 7 days for $1': 'Essayez 7 jours pour 1 $',
  'Pick a lane': 'Choisissez une voie',
  'All free tools': 'Tous les outils gratuits',
  'Terms of Service': 'Conditions d’utilisation',
  'Trust Center': 'Centre de confiance',
  'Review & publish': 'Vérifier et publier',
  'Your image': 'Votre image',
  'Cost per image': 'Coût par image',
  'No videos yet': 'Aucune vidéo pour l’instant',
  'No audio yet': 'Aucun audio pour l’instant',
  '🎬 Studio — generate video': '🎬 Studio — générer une vidéo',
  '🎨 Images — create image': '🎨 Images — créer une image',
  '🎙 Audio — text to speech': '🎙 Audio — synthèse vocale',
  'Type it. See it. Six image engines, one screen.': 'Tapez-le. Voyez-le. Six moteurs d’image, un seul écran.',
  'Type it. Hear it. Four voice engines, one screen.': 'Tapez-le. Écoutez-le. Quatre moteurs de voix, un seul écran.',
  'Everything you’ve created, in one place.': 'Tout ce que vous avez créé, au même endroit.',
  'Add credits →': 'Ajouter des crédits →',
  'Upscale any result to 2x for 1 credit.': 'Agrandissez n’importe quel résultat en 2x pour 1 crédit.',
  'We couldn’t load your images right now.': 'Impossible de charger vos images pour le moment.',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'Vos images et vos crédits sont en sécurité — ce n’est qu’un souci de lecture temporaire.',
  'We couldn’t load your audio right now.': 'Impossible de charger votre audio pour le moment.',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'Votre audio et vos crédits sont en sécurité — ce n’est qu’un souci de lecture temporaire.',
  'We couldn’t load part of your library right now.': 'Impossible de charger une partie de votre bibliothèque pour le moment.',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'Vos vidéos et vos crédits sont en sécurité — ce n’est qu’un souci de lecture temporaire.',
  '↻ Try again': '↻ Réessayer',
  '⬇ Download': '⬇ Télécharger',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': 'Une voix vous plaît ? Le Studio construit tout le film autour d’elle — visuels, sous-titres et musique.',
  'Open Studio →': 'Ouvrir le Studio →',
  'open the Studio': 'ouvrez le Studio',
  'Next episode →': 'Épisode suivant →',
  'create your first image': 'créez votre première image',
  'generate your first voiceover': 'générez votre première voix off',
  'Instant drafts': 'Brouillons instantanés',
  'Deep prompt understanding': 'Compréhension fine du prompt',
  'Perfect text rendering': 'Rendu de texte parfait',
  'Create Image': 'Créer une image',
  'Click-magnet YouTube covers': 'Miniatures YouTube qui attirent le clic',
  'Bring any image to life': 'Donnez vie à n’importe quelle image',
  'Instant narration': 'Narration instantanée',
  'Four voice engines': 'Quatre moteurs de voix',
  'A face that speaks your script': 'Un visage qui dit votre script',
  'Every control, one screen': 'Tous les réglages, un seul écran',
  'Today’s trending topics': 'Sujets tendance du jour',
  'Real renders, every engine': 'Rendus réels, tous les moteurs',
  'Type an idea — watch it become a film.': 'Tapez une idée — regardez-la devenir un film.',
  'Start with the full toolkit': 'Commencez avec la boîte à outils complète',
  'Kineo’s own engine — 3–7 min': 'Le moteur maison de Kineo — 3–7 min',
  'The workhorse AI video engine': 'Le moteur vidéo IA de tous les jours',
  'Cinematic motion & camera': 'Mouvement et caméra cinématographiques',
  'Film scenes, native voice & lip sync': 'Scènes de film, voix native et synchronisation labiale',
  'Talking video from one photo': 'Vidéo parlante à partir d’une photo',
  'From idea to posted Short in 3 steps.': 'De l’idée au Short publié en 3 étapes.',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'Pas de tournage, pas de montage, pas de timeline. Tapez une fois — Kineo fait le reste.',
  'Step 1': 'Étape 1',
  'Kineo builds it': 'Kineo le construit',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'L’IA écrit un script structuré pour la rétention, enregistre la voix off, associe les images et incruste les sous-titres — une vidéo 9:16 terminée.',
  'Download & post': 'Téléchargez et publiez',
  'Why Kineo': 'Pourquoi Kineo',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'La plupart des outils redécoupent une longue vidéo que vous avez déjà filmée. Kineo la construit de zéro.',
  'See how to make Shorts without filming →': 'Voir comment faire des Shorts sans filmer →',
  'Generates the Short from just an idea': 'Génère le Short à partir d’une simple idée',
  'Writes the script for you': 'Écrit le script pour vous',
  'Finds and matches footage': 'Trouve et associe les images',
  'your upload': 'votre fichier',
  'AI image studio included': 'Studio d’images IA inclus',
  'Voice studio (text-to-speech)': 'Studio vocal (synthèse vocale)',
  'One-click HD film enhance': 'Amélioration HD du film en un clic',
  'One idea — or a whole toolkit.': 'Une idée — ou toute une boîte à outils.',
  'Try AI Presenter →': 'Essayer le Présentateur IA →',
  'Transparent Clips': 'Clips transparents',
  'UGC Product Ads': 'Publicités produit UGC',
  'Animate a photo →': 'Animer une photo →',
  'Make a thumbnail →': 'Créer une miniature →',
  'Free AI Shorts': 'Shorts IA gratuits',
  'Start with a niche that already works.': 'Commencez par une niche qui marche déjà.',
  'Not sure? Take the quiz →': 'Pas sûr ? Faites le quiz →',
  'Pick your engine. Ship a Short today.': 'Choisissez votre moteur. Publiez un Short aujourd’hui.',
  'Cancel anytime': 'Annulez à tout moment',
  'Generate image →': 'Générer une image →',
  'Generate audio →': 'Générer un audio →',
  'Paid plans unlock clean MP4s.': 'Les offres payantes débloquent les MP4 propres.',
  'Best for starting out': 'Idéal pour débuter',
  'Best value per film': 'Meilleur rapport par film',
  'on Nano Banana': 'sur Nano Banana',
  'Every video engine incl. MiniMax H3': 'Tous les moteurs vidéo, MiniMax H3 inclus',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'MP4 sans filigrane · 100 projets · stockage 90 jours',
  ', finished': ', terminé',
  '— every engine unlocked': '— tous les moteurs débloqués',
  '· voice + karaoke captions + score': '· voix + sous-titres karaoké + musique',
  '500 projects · forever storage': '500 projets · stockage illimité dans le temps',
  'Cancel anytime — 7-day money-back': 'Annulez à tout moment — satisfait ou remboursé 7 jours',
  'films on Omni Flash': 'films sur Omni Flash',
  '· 2 free HD enhances / month': '· 2 améliorations HD gratuites / mois',
  'Unlimited projects · forever storage': 'Projets illimités · stockage illimité dans le temps',
  'Everything in Creator': 'Tout ce qu’il y a dans Creator',
  'Calculate your cost per Short →': 'Calculez votre coût par Short →',
  'How much do Shorts pay? →': 'Combien rapportent les Shorts ? →',
  'Highest-RPM niches →': 'Niches au RPM le plus élevé →',
  'read the full review →': 'lire l’avis complet →',
  'a single line is enough — or paste a full script': 'une seule ligne suffit — ou collez un script complet',
  '1080×1920 · Full HD master': '1080×1920 · master Full HD',
  'Every film is delivered as a 1080×1920 Full HD master (engines render natively at 720–768p and are mastered up). For maximum sharpness, run ✨HD Enhance on the finished film.': 'Chaque film est livré en master 1080×1920 Full HD (les moteurs rendent nativement en 720–768p puis sont masterisés vers le haut). Pour une netteté maximale, lancez ✨HD Enhance sur le film terminé.',
  'Your idea first. Review the settings, then generate.': 'Votre idée d’abord. Vérifiez les réglages, puis générez.',
  '📷 Photo': '📷 Photo',
  '🖼️ Upload a different photo': '🖼️ Envoyer une autre photo',
  '🎙️ Generating…': '🎙️ Génération…',
  '🎙️ Cloning the voice…': '🎙️ Clonage de la voix…',
  '🎙️ Upload a different sample': '🎙️ Envoyer un autre échantillon',
  '⏹ Stop & clone': '⏹ Arrêter et cloner',
  '🎭 Generate my avatar video': '🎭 Générer ma vidéo avatar',
  'Continue exactly where ChatGPT stopped.': 'Reprenez exactement là où ChatGPT s’est arrêté.',
  '✨ Let AI structure it': '✨ Laisser l’IA structurer',
  'Optional settings': 'Réglages facultatifs',
  'optional — a pre-tested move added to your prompt': 'facultatif — un mouvement pré-testé ajouté à votre prompt',
  'Reference image': 'Image de référence',
  '🖼️ Start your video from an image — coming soon': '🖼️ Démarrer votre vidéo à partir d’une image — bientôt',
  'Estimated cost': 'Coût estimé',
  'Your credits buy': 'Vos crédits permettent',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'Voix, sous-titres karaoké et musique inclus. Si un rendu échoue, vos crédits reviennent aussitôt.',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'Même sujet, nouvelle accroche et nouvelle chute — l’idée est déjà écrite.',
  'Build next episode →': 'Créer l’épisode suivant →',
  'Episode 2 →': 'Épisode 2 →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'Présentateur IA parlant à partir d’une photo — synchronisé, son propre studio',
  'Your face. Your script.': 'Votre visage. Votre script.',
  'Everything you need to make yourself speak — nothing you don’t.': 'Tout ce qu’il faut pour vous faire parler — rien de superflu.',
  'BEST MOTION': 'MEILLEUR MOUVEMENT',
  '1.5 · Realism': '1.5 · Réalisme',
  '🎬 Put me in a scene': '🎬 Mettez-moi dans une scène',
  'use original photo': 'utiliser la photo originale',
  '✍️ Say exactly this — word for word': '✍️ Dites exactement ceci — mot pour mot',
  '✨ Expand into a full Short script (45–60s)': '✨ Développer en script de Short complet (45–60 s)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 Mode publicité produit — vendez un produit façon UGC',
  'Free — fills the script box above, then generate with your presenter.': 'Gratuit — remplit la zone de script ci-dessus, puis générez avec votre présentateur.',
  '2.5 · Speak in your own voice': '2.5 · Parlez avec votre propre voix',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ Voix clonée — la narration utilisera cette voix.',
  'use a default voice': 'utiliser une voix par défaut',
  '🎬 Full video — face the whole time': '🎬 Vidéo complète — le visage tout du long',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 Présentateur IA — rapide et naturel · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro — qualité photo premium · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 Body Motion — buste, mains et gestes · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ Classique — talking head · 110 cr',
  'you have': 'vous avez',
  'to create your avatar video.': 'pour créer votre vidéo avatar.',
  '5 · Gesture clips — transparent background': '5 · Clips de gestes — fond transparent',
  'auto-refunded if it fails': 'remboursé automatiquement en cas d’échec',
  '⬇️ Download transparent WebM': '⬇️ Télécharger le WebM transparent',
  '⬇️ Original MP4 (with background)': '⬇️ MP4 original (avec fond)',
  'Pick a face to preview': 'Choisissez un visage à prévisualiser',
  '↺ Make another': '↺ En faire un autre',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'Personnes, animaux, produits, vieilles photos de famille — envoyez une photo ou collez un lien d’image public et regardez-la bouger.',
  'The photo': 'La photo',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': 'JPG/PNG jusqu’à 8 Mo. Les liens publics sont téléchargés et vérifiés en toute sécurité sur notre serveur.',
  'sign in': 'se connecter',
  'Kineo will fetch and validate it on the server when you animate.': 'Kineo la récupérera et la vérifiera sur le serveur au moment de l’animation.',
  'Upload a photo to preview': 'Envoyez une photo pour prévisualiser',
  '🖼️ Upload a photo': '🖼️ Envoyer une photo',
  '✨ Bring it to life': '✨ Lui donner vie',
  'Uploading your photo…': 'Envoi de votre photo…',
  'Bringing your photo to life… (1–3 min)': 'Votre photo prend vie… (1–3 min)',
  'Alive!': 'Vivante !',
  '🌬️ Subtle & real': '🌬️ Subtil et réel',
  '😊 Person comes alive': '😊 La personne prend vie',
  'Type your idea first': 'Tapez d’abord votre idée',
  '📖 True Story': '📖 Histoire vraie',
  'Paste your ChatGPT script': 'Collez votre script ChatGPT',
  'First Short complete': 'Premier Short terminé',
  'Keep your show moving': 'Gardez votre émission en mouvement',
  'Cheapest way to see your idea as a film': 'Le moyen le moins cher de voir votre idée en film',
  'Slow Dolly-In': 'Dolly-in lent',
  'FPV Drone': 'Drone FPV',
  'Macro Detail': 'Détail macro',
  'Sharing & creator options': 'Partage et options créateur',
  'We couldn’t load your videos right now': 'Impossible de charger vos vidéos pour le moment',
  'Your videos and credits are safe — this is a temporary read hiccup, not a lost library.': 'Vos vidéos et vos crédits sont en sécurité — c’est un souci de lecture temporaire, pas une bibliothèque perdue.',
  '⚡ Generate Video': '⚡ Générer la vidéo',
  'Prefer clean exports now? Starter includes': 'Vous préférez des exports propres dès maintenant ? Starter inclut',
  'credits each month for': 'crédits par mois pour',
  'Your existing files stay available. Starter applies to new exports after checkout.': 'Vos fichiers existants restent disponibles. Starter s’applique aux nouveaux exports après le paiement.',
  'Build Next Episode First': 'Créer d’abord l’épisode suivant',
  'Video unavailable': 'Vidéo indisponible',
  'Free MP4 includes the Kineo watermark': 'Le MP4 gratuit inclut le filigrane Kineo',
  'Free distribution · latest Short': 'Diffusion gratuite · dernier Short',
  'Send it to one person for feedback': 'Envoyez-le à une personne pour avoir son avis',
  'Copy a public watch page for your finished video. Your friend can watch it without logging in, then use “Make one like this” if the idea inspires them.': 'Copiez une page de visionnage publique de votre vidéo terminée. Votre ami peut la regarder sans se connecter, puis utiliser « Faire pareil » si l’idée l’inspire.',
  'Public watch links are temporarily paused': 'Les liens de visionnage publics sont temporairement suspendus',
  'Your video stays in your account. Download the MP4 if you want to send it directly; Kineo will not publish a public page without an explicit visibility choice.': 'Votre vidéo reste dans votre compte. Téléchargez le MP4 pour l’envoyer directement ; Kineo ne publiera pas de page publique sans un choix de visibilité explicite.',
  'Loading…': 'Chargement…',
  'For new videos ·': 'Pour les nouvelles vidéos ·',
  'Published it?': 'Vous l’avez publiée ?',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'Nette, de face, une seule personne. Pour le mouvement du corps, utilisez une photo à mi-corps ou en pied avec les deux mains visibles. Les bandes noires sont retirées automatiquement.',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'Meilleur résultat professionnel : envoyez un clip vertical de 5–20 s avec les vrais gestes souhaités, d’une durée proche du script. Sync-3 remplace la parole en préservant le vrai visage et les mouvements. MP4/MOV jusqu’à 40 Mo.',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'Je confirme avoir le droit d’utiliser l’image de cette personne et consens à ce qu’elle soit animée par IA.',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': 'Envoyez un échantillon de voix clair de ~30-60 s (une seule voix, peu de bruit de fond) et la narration sera dite avec cette voix. N’utilisez qu’une voix que vous avez le droit d’utiliser.',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'Les vidéos mot pour mot montrent votre visage tout du long (elles sont courtes — pas besoin de b-roll).',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'Les vidéos réalisme maximal et scène construite gardent le présentateur à l’écran pendant toute la narration.',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ Intro accroche — vous ouvrez, le b-roll raconte l’histoire',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'Courts clips de votre présentateur qui salue, pointe, présente — livrés en WebM avec un VRAI fond transparent. Glissez-les directement dans Storyline, Premiere, CapCut ou n’importe quelle diapositive. Pas de fond vert, pas de détourage.',
  'Cinematic film — 9-image consistency': 'Film cinématographique — cohérence sur 9 images',
  '#1-ranked video model — Aug 2026 arena': 'Modèle vidéo n° 1 du classement — arène d’août 2026',
  'Cinematic motion and camera work': 'Mouvement et travail de caméra cinématographiques',
  'Shorts money & growth': 'Argent et croissance avec les Shorts',
  'Compare Kineo with 27 AI video tools →': 'Comparez Kineo à 27 outils vidéo IA →',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'Présentateurs parlants, personnages réutilisables, clips transparents, publicités produit — et tout pour repérer et surfer une tendance.',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'Une photo + votre script — une vidéo parlante avec synchronisation labiale de studio, façon HeyGen.',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'Enregistrez un personnage une fois — exactement le même visage dans chaque vidéo et miniature.',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'Gestes de présentateur — saluer, pointer, présenter — en WebM avec un vrai fond transparent.',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'Collez n’importe quel produit — obtenez une pub de 15-30 s façon créateur, scénarisée et dite pour vous.',
  'Bring any still photo to life as a moving, postable video.': 'Donnez vie à n’importe quelle photo fixe sous forme de vidéo animée, prête à publier.',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'Miniatures qui font cliquer, dans le style des plus grandes chaînes — à partir d’un prompt.',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'Chaque niche ci-dessous a sa propre page de génération, ses prompts ajustés et des exemples réels.',
  'Is the video really mine to post?': 'La vidéo m’appartient-elle vraiment pour la publier ?',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'Les offres payantes débloquent le MP4 propre, sans filigrane, pour YouTube, TikTok ou Reels.',
  'Do I need any editing skills?': 'Faut-il savoir monter ?',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'Non. Vous tapez une idée et l’IA écrit le script, enregistre la voix, trouve les images et ajoute les sous-titres.',
  'Is there a watermark?': 'Y a-t-il un filigrane ?',
  'Paid plans export clean, watermark-free MP4s.': 'Les offres payantes exportent des MP4 propres, sans filigrane.',
  'Can Kineo also generate images and voiceovers?': 'Kineo génère-t-il aussi des images et des voix off ?',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'Oui — Kineo inclut un studio d’images IA (6 moteurs dont FLUX, Seedream et Nano Banana Pro, à partir de 1 crédit par image) et un studio vocal avec 4 moteurs de synthèse vocale (à partir de 1 crédit pour 1000 caractères). Tout ce que vous créez vit dans votre Bibliothèque.',
  'Can I make my videos sharper?': 'Puis-je rendre mes vidéos plus nettes ?',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'Chaque vidéo a une option d’amélioration en un clic propulsée par la restauration de film Topaz — elle supprime les artefacts de compression, récupère les détails et ajoute un grain cinématographique fin. 10 crédits par vidéo ; l’offre Studio inclut 2 améliorations gratuites par mois.',
  'Can I use my own script?': 'Puis-je utiliser mon propre script ?',
  'What if a generation fails?': 'Et si une génération échoue ?',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'Vos crédits reviennent automatiquement dès qu’un rendu échoue — sans ticket, sans attente. Vous ne payez que les vidéos que vous recevez vraiment.',
  'Can I cancel anytime?': 'Puis-je annuler à tout moment ?',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'À tout moment, en un clic. Les offres sont mensuelles et vos crédits se renouvellent chaque mois.',
  'Can I run a whole channel with the same host?': 'Puis-je faire tourner toute une chaîne avec le même présentateur ?',
  'Can I monetize the videos?': 'Puis-je monétiser les vidéos ?',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'Oui. Chaque vidéo vous appartient : gardez-la, publiez-la et monétisez-la — y compris via le Programme Partenaire YouTube, TikTok et Reels. Aucune licence supplémentaire.',
  'Can I use the videos commercially, or for client work?': 'Puis-je utiliser les vidéos à des fins commerciales ou pour des clients ?',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'Oui. Nos conditions autorisent l’usage de Kineo à des fins personnelles ou commerciales licites et confirment que vous conservez la propriété des vidéos générées : vous pouvez les publier, les monétiser et les livrer à un client dans le cadre de votre propre prestation payante. Aucune licence supplémentaire, aucune redevance par vidéo. Deux limites découlent des mêmes conditions : vous ne pouvez pas revendre ni redistribuer Kineo lui-même, et les clips de banque contenus dans un rendu sont licenciés pour votre vidéo finale, pas pour être remis en ligne comme footage autonome. Les offres payantes exportent le MP4 propre, sans filigrane.',
  'How long does one video take?': 'Combien de temps prend une vidéo ?',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'Le mode Fast se termine généralement en 3–7 minutes. Les vidéos générées par IA et cinématographiques prennent un peu plus de temps, car chaque scène est générée avant la composition du MP4 final.',
  'How much does Kineo cost?': 'Combien coûte Kineo ?',
  'Kineo has three monthly plans: Starter at $': 'Kineo propose trois offres mensuelles : Starter à $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'crédits. Les crédits sont dépensés par vidéo, et le coût d’une vidéo dépend du moteur choisi : un rendu Fast et un film cinématographique puisent dans le même solde à des rythmes très différents.',
  'Which AI video engines can I use in Kineo?': 'Quels moteurs vidéo IA puis-je utiliser dans Kineo ?',
  ', behind one interface and one balance:': ', derrière une seule interface et un seul solde :',
  'What is the best AI video generator for faceless YouTube channels?': 'Quel est le meilleur générateur vidéo IA pour les chaînes YouTube sans visage ?',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'Oui. Les utilisateurs gratuits n’ayant jamais payé peuvent télécharger, partager et publier le MP4 filigrané.',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'Les films d’essai portent un petit filigrane — vous pouvez télécharger, partager et publier le MP4. Après l’essai, la vidéo Fast gratuite porte un filigrane.',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'Les téléchargements gratuits portent un filigrane ; les offres payantes débloquent le MP4 propre.',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'Les téléchargements d’essai portent un filigrane, tout comme la vidéo Fast gratuite après l’essai, et les offres payantes exportent toujours propre.',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'L’accès gratuit donne aux nouveaux utilisateurs jusqu’à 3 vidéos Fast filigranées toutes les 24 heures, sans carte. Vous pouvez les télécharger et les partager.',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'Créez, téléchargez et partagez jusqu’à 3 vidéos Fast filigranées toutes les 24 h, sans carte.',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'Créez, regardez, téléchargez et partagez jusqu’à 3 vidéos Fast filigranées toutes les 24 h — sans carte.',
  'create, watch, download and share up to 3 Fast videos every 24h': 'créez, regardez, téléchargez et partagez jusqu’à 3 vidéos Fast toutes les 24 h',
  '— no card, watermark included.': '— sans carte, filigrane inclus.',
  'AI image generator — 6 engines': 'Générateur d’images IA — 6 moteurs',
  'AI voice generator (text to speech)': 'Générateur de voix IA (synthèse vocale)',
  'AI video upscaler & enhancer': 'Upscaler et amélioration vidéo IA',
  'Trending Shorts ideas today': 'Idées de Shorts tendance aujourd’hui',
  'AI Avatar video — your face, any script': 'Vidéo avatar IA — votre visage, n’importe quel script',
  'Kineo facts & numbers (citable)': 'Faits et chiffres Kineo (citables)',
  'Free AI Shorts generator': 'Générateur de Shorts IA gratuit',
  'YouTube Shorts from a topic': 'Shorts YouTube à partir d’un sujet',
  'ChatGPT script to YouTube Short': 'Script ChatGPT vers Short YouTube',
  'Shorts without filming': 'Shorts sans filmer',
  'Faceless niche picker': 'Sélecteur de niche sans visage',
  'State of AI Shorts 2026': 'État des Shorts IA 2026',
  'AI Shorts for agencies & client work': 'Shorts IA pour agences et clients',
  'Trust Center — privacy, payments & ownership': 'Centre de confiance — confidentialité, paiements et propriété',
  'Affiliate program - 30% recurring': 'Programme d’affiliation - 30 % récurrent',
  'Free AI Shorts by niche': 'Shorts IA gratuits par niche',
  'Free script generator': 'Générateur de script gratuit',
  'Product video ad script': 'Script de pub vidéo produit',
  'Client video brief generator': 'Générateur de brief vidéo client',
  'Free hook generator': 'Générateur d’accroches gratuit',
  'Shorts script timer': 'Chronomètre de script Shorts',
  'Shorts money calculator': 'Calculateur de revenus Shorts',
  'How much do Shorts pay?': 'Combien rapportent les Shorts ?',
  'Best AI Shorts generators': 'Meilleurs générateurs de Shorts IA',
  'TikTok vs Shorts: which pays more?': 'TikTok vs Shorts : lequel paie le plus ?',
  'All comparisons': 'Toutes les comparaisons',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · Tous droits réservés',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'Cela dépend : voulez-vous des images de banque assemblées ou des images générées ? Des outils comme InVideo et AutoShorts découpent des clips de banque sur votre script — moins cher, et suffisant pour des vidéos à points de discussion. Kineo génère les images avec des modèles comme Veo 3.1 et Kling 3, garde votre narration mot pour mot au lieu de la réécrire, et vise 60 secondes ou plus pour que la vidéo soit éligible au TikTok Creator Rewards. Si votre chaîne vit de visuels que personne d’autre n’a, la génération gagne ; si elle vit du volume, la banque est moins chère.',
  'Paste the complete script from ChatGPT here…': 'Collez ici le script complet de ChatGPT…',
  'Paste the idea from ChatGPT here…': 'Collez ici l’idée de ChatGPT…',
  'What’s your video about? One idea in — a finished film out: voiced, scored and captioned.': 'De quoi parle votre vidéo ? Une idée entre — un film terminé sort : voix, musique et sous-titres.',
  'Settings and generation': 'Réglages et génération',
  'Search your videos…': 'Rechercher dans vos vidéos…',
  'Search your audio…': 'Rechercher dans votre audio…',
  'Search your images by engine': 'Rechercher vos images par moteur',
  'No playable videos in your library yet. Check your latest project above.': 'Aucune vidéo lisible dans votre bibliothèque pour l’instant. Consultez votre dernier projet ci-dessus.',
  'Make a finished Short →': 'Créer un Short terminé →',
  'Video Editing & Creator Tools': 'Montage vidéo et outils pour créateurs',
  'Trim, resize, change speed, mute or add text. Edit a file you already have, right in your browser. Your script and planning tools are still here below.': 'Coupez, redimensionnez, changez la vitesse, coupez le son ou ajoutez du texte. Modifiez un fichier que vous avez déjà, directement dans votre navigateur. Vos outils de script et de planification sont toujours là, plus bas.',
  '5 local editing tools': '5 outils de montage locaux',
  'No generation credits to edit': 'Aucun crédit de génération pour monter',
  'Edit video': 'Monter la vidéo',
  'Files up to 100 MB and 3 minutes. Local, real-time export up to 1280 px on the long edge. MP4 or WebM depending on your browser; downloads are not saved to My Videos.': 'Fichiers jusqu’à 100 Mo et 3 minutes. Export local en temps réel jusqu’à 1280 px sur le grand côté. MP4 ou WebM selon votre navigateur ; les téléchargements ne sont pas enregistrés dans Mes vidéos.',
  'Video Trimmer': 'Découpeur vidéo',
  'Cut the beginning or end and keep only the clip you need.': 'Coupez le début ou la fin et gardez seulement le passage voulu.',
  'Video Resizer': 'Redimensionneur vidéo',
  'Go vertical, square or wide. Fit the frame or crop to fill.': 'Vertical, carré ou large. Ajustez au cadre ou recadrez pour remplir.',
  'Video Speed Changer': 'Changeur de vitesse vidéo',
  'Slow it down or speed it up, from 0.5× to 2×.': 'Ralentissez ou accélérez, de 0.5× à 2×.',
  'Remove Audio': 'Supprimer l’audio',
  'Download a copy without the original audio.': 'Téléchargez une copie sans l’audio d’origine.',
  'Add Text to Video': 'Ajouter du texte à la vidéo',
  'Add a title or message that stays on screen. Not automatic subtitles.': 'Ajoutez un titre ou un message qui reste à l’écran. Pas de sous-titres automatiques.',
  'No account · current Kineo plans': 'Sans compte · offres Kineo actuelles',
  'No account · fair-use limit': 'Sans compte · limite d’usage raisonnable',
  'No account · unlimited in browser': 'Sans compte · illimité dans le navigateur',
  'Edit an existing video here. Create a new one with Kineo.': 'Montez ici une vidéo existante. Créez-en une nouvelle avec Kineo.',
  'Create an AI video →': 'Créer une vidéo IA →',
  'Edit your video, preview the changes, then export a copy.': 'Montez votre vidéo, prévisualisez les changements, puis exportez une copie.',
  'Video preview': 'Aperçu vidéo',
  'Preview is silent. The download keeps audio unless Mute is selected.': 'L’aperçu est muet. Le téléchargement garde l’audio sauf si Muet est sélectionné.',
  'Start with your video': 'Commencez avec votre vidéo',
  'Choose a local file. It stays on this device.': 'Choisissez un fichier local. Il reste sur cet appareil.',
  'Choose video file': 'Choisir un fichier vidéo',
  'Video file': 'Fichier vidéo',
  'Video settings': 'Réglages vidéo',
  'Aspect ratio': 'Format d’image',
  'Playback speed': 'Vitesse de lecture',
  'On-screen text (100 characters, 3 lines)': 'Texte à l’écran (100 caractères, 3 lignes)',
  'Add a title or message': 'Ajoutez un titre ou un message',
  'Export edited video': 'Exporter la vidéo montée',
  'Export happens in real time. Keep this tab visible. Re-encoded at up to 1280 px on the long edge; format depends on your browser.': 'L’export se fait en temps réel. Gardez cet onglet visible. Réencodé jusqu’à 1280 px sur le grand côté ; le format dépend de votre navigateur.',
  'Making a 4-second sample on your device…': 'Création d’un échantillon de 4 secondes sur votre appareil…',
  'Reading your file…': 'Lecture de votre fichier…',
  'Export result': 'Résultat de l’export',
  'Your edited video': 'Votre vidéo montée',
  'Local download only. This copy is not saved to My Videos.': 'Téléchargement local uniquement. Cette copie n’est pas enregistrée dans Mes vidéos.',
  'Exported video': 'Vidéo exportée',
  'No upload. No generation credits. Your original is never overwritten.': 'Aucun envoi. Aucun crédit de génération. Votre original n’est jamais écrasé.',
  'Up to 100 MB · 3 minutes · MP4/WebM input recommended. These are basic editing tools, not the CapCut app.': 'Jusqu’à 100 Mo · 3 minutes · entrée MP4/WebM recommandée. Ce sont des outils de montage basiques, pas l’application CapCut.',
  'Need a new video? Open Kineo Studio →': 'Besoin d’une nouvelle vidéo ? Ouvrez Kineo Studio →',
  'This browser cannot export video here. Try the latest desktop Chrome or Edge.': 'Ce navigateur ne peut pas exporter de vidéo ici. Essayez la dernière version de Chrome ou Edge sur ordinateur.',
  'Choose a non-empty video file of up to 100 MB.': 'Choisissez un fichier vidéo non vide de 100 Mo maximum.',
  'Use a playable clip of up to 3 minutes. Very large dimensions are not supported.': 'Utilisez un clip lisible de 3 minutes maximum. Les très grandes dimensions ne sont pas prises en charge.',
  'Check the start and end: select at least 0.25 seconds within your clip.': 'Vérifiez le début et la fin : sélectionnez au moins 0.25 seconde dans votre clip.',
  'Choose a speed between 0.5× and 2×.': 'Choisissez une vitesse entre 0.5× et 2×.',
  'Use up to 100 characters and 3 lines of text.': 'Utilisez au maximum 100 caractères et 3 lignes de texte.',
  'Choose a supported aspect ratio, framing and text position.': 'Choisissez un format, un cadrage et une position de texte pris en charge.',
  'This file could not be decoded. Try an MP4 (H.264) or WebM file.': 'Ce fichier n’a pas pu être décodé. Essayez un fichier MP4 (H.264) ou WebM.',
  'Export stopped because this tab was hidden. Keep it open and visible, then export again. Your original is safe.': 'L’export s’est arrêté parce que cet onglet a été masqué. Gardez-le ouvert et visible, puis relancez l’export. Votre original est intact.',
  'Export stopped making progress. Try a shorter clip or desktop Chrome. Your original is unchanged.': 'L’export ne progresse plus. Essayez un clip plus court ou Chrome sur ordinateur. Votre original est inchangé.',
  'Audio could not start. Try exporting again, or choose Mute video.': 'L’audio n’a pas pu démarrer. Relancez l’export ou choisissez Vidéo muette.',
  'The browser blocked playback. Try exporting again from this tab.': 'Le navigateur a bloqué la lecture. Relancez l’export depuis cet onglet.',
  'Cancelled. Your original file is unchanged.': 'Annulé. Votre fichier original est inchangé.',
  'Could not finish this export. Try a shorter clip or another supported browser.': 'Impossible de terminer cet export. Essayez un clip plus court ou un autre navigateur pris en charge.',
  'The browser produced an incomplete file, so we did not offer it for download. Try again with this tab visible, or use desktop Chrome.': 'Le navigateur a produit un fichier incomplet, nous ne l’avons donc pas proposé au téléchargement. Réessayez avec cet onglet visible, ou utilisez Chrome sur ordinateur.',
  'Create new video': 'Créer une nouvelle vidéo',
  'Your idea': 'Votre idée',
  'Natural': 'Naturel',
  'Working…': 'En cours…',
  '🎲 Surprise me': '🎲 Surprenez-moi',
  '📝 Use my script as is': '📝 Utiliser mon script tel quel',
  'Camera preset': 'Préréglage caméra',
  'Your latest videos': 'Vos dernières vidéos',
  'Presenter': 'Présentateur',
  '1 · Who’s talking': '1 · Qui parle',
  '🎭 your characters': '🎭 vos personnages',
  '🎯 Max realism — animate my real photo': '🎯 Réalisme maximal — animer ma vraie photo',
  '✓ Scene ready — preview on the right.': '✓ Scène prête — aperçu à droite.',
  '2 · What they say': '2 · Ce qu’ils disent',
  '3 · How it looks': '3 · Le rendu',
  'Motion': 'Mouvement',
  '⬇ Download MP4': '⬇ Télécharger le MP4',
  'One photo. Suddenly alive.': 'Une photo. Soudain vivante.',
  'Cost per clip': 'Coût par clip',
  '↺ Animate another': '↺ Animer une autre',
  'Grow': 'Grandir',
  'Sending to the motion engine…': 'Envoi au moteur de mouvement…',
  '📊 Facts': '📊 Faits',
  'Turn it into episode 2': 'En faire l’épisode 2',
  'Start here': 'Commencez ici',
  'Engine': 'Moteur',
  'Highly aesthetic, by xAI': 'Très esthétique, par xAI',
  'Google’s best image model': 'Le meilleur modèle d’image de Google',
  'AI voiceover included': 'Voix off IA incluse',
  '6 engines': '6 moteurs',
  'AI Presenter': 'Présentateur IA',
  'Lock a character →': 'Fixer un personnage →',
  'Make a clip →': 'Créer un clip →',
  'Make an ad →': 'Créer une pub →',
  'Generate free →': 'Générer gratuitement →',
  'Creating…': 'Création…',
  'Describe your image first': 'Décrivez d’abord votre image',
  'Type your script first': 'Tapez d’abord votre script',
  'From the founder': 'Du fondateur',
  'Faceless video generator': 'Générateur de vidéos sans visage',
  'Text to video Shorts': 'Shorts texte vers vidéo',
  'Cheapest AI Shorts maker': 'Le créateur de Shorts IA le moins cher',
  'Faceless channel ideas (2026)': 'Idées de chaînes sans visage (2026)',
  'Shorts idea widget': 'Widget d’idées de Shorts',
  'Live case study: our channel on Autopilot': 'Étude de cas en direct : notre chaîne en Autopilot',
  'Free YouTube Shorts scripts': 'Scripts gratuits de Shorts YouTube',
  'Comment to Short script': 'Du commentaire au script de Short',
  'Business video content planner': 'Planificateur de contenu vidéo pour entreprises',
  'Real estate video maker': 'Créateur de vidéos immobilières',
  'Shorts title & hashtag generator': 'Générateur de titres et hashtags pour Shorts',
  'Free viral score': 'Score viral gratuit',
  'Make money clipping with AI': 'Gagnez de l’argent en faisant des clips avec l’IA',
  'Shorts RPM by niche (2026)': 'RPM des Shorts par niche (2026)',
  'Can you monetize AI videos?': 'Peut-on monétiser des vidéos IA ?',
}
