// KINEO-INTERFACE-16-LINGUAS-2026-09-21 — interface em id. Só copy autoral da interface: nunca prompt,
// título, resultado, nome de motor ou erro de API. Frase fora daqui cai em inglês (components/InterfaceLanguage.tsx).
// Gerado de scratchpad/tr-id.js sobre o corpus vivo de frases (415); números e "Kineo" preservados por construção.
export const DICT: Record<string, string> = {
  'Videos for businesses': 'Video untuk bisnis',
  'Generation failed': 'Pembuatan gagal',
  'You can retry safely.': 'Anda bisa mencoba lagi dengan aman.',
  'This engine is not available on your account right now': 'Mesin ini sedang tidak tersedia di akun Anda',
  'Retrying the same engine will stop at this same place. Pick another engine to keep going.': 'Mencoba lagi dengan mesin yang sama akan berhenti di titik yang sama. Pilih mesin lain untuk melanjutkan.',
  'The engine is cooling down after two refunded attempts': 'Mesin sedang mendingin setelah dua percobaan yang dikembalikan kreditnya',
  'Starting another one right now stops at this same place. Give it a few minutes.': 'Memulai yang lain sekarang akan berhenti di titik yang sama. Beri waktu beberapa menit.',
  'Starting another one right now stops at this same place. The button below unlocks by itself.': 'Memulai yang lain sekarang akan berhenti di titik yang sama. Tombol di bawah akan terbuka sendiri.',
  'We stopped waiting on this render instead of leaving you hanging': 'Kami berhenti menunggu render ini daripada membiarkan Anda menggantung',
  'This one ran far longer than any video that finishes here. Starting again is worth it.': 'Yang ini berjalan jauh lebih lama dari video mana pun yang selesai di sini. Memulai lagi layak dilakukan.',
  'The video engine is busy — this is on our side, not your idea': 'Mesin video sedang sibuk — ini dari sisi kami, bukan ide Anda',
  'Nothing about your text is wrong. Trying again in a few minutes usually goes straight through.': 'Tidak ada yang salah dengan teks Anda. Mencoba lagi dalam beberapa menit biasanya langsung berhasil.',
  'Create Video': 'Buat Video',
  'Create a new video': 'Buat video baru',
  'AI Avatar Studio': 'Studio Avatar AI',
  'Viral Templates': 'Template Viral',
  'Channel Builder': 'Pembangun Channel',
  'Invite & Earn': 'Undang & Dapatkan',
  'Start free': 'Mulai gratis',
  'Try 7 days for $1': 'Coba 7 hari seharga $1',
  'Pick a lane': 'Pilih jalur',
  'All free tools': 'Semua alat gratis',
  'Terms of Service': 'Ketentuan Layanan',
  'Trust Center': 'Pusat Kepercayaan',
  'Review & publish': 'Tinjau & publikasikan',
  'Your image': 'Gambar Anda',
  'Cost per image': 'Biaya per gambar',
  'No videos yet': 'Belum ada video',
  'No audio yet': 'Belum ada audio',
  '🎬 Studio — generate video': '🎬 Studio — buat video',
  '🎨 Images — create image': '🎨 Gambar — buat gambar',
  '🎙 Audio — text to speech': '🎙 Audio — teks ke suara',
  'Type it. See it. Six image engines, one screen.': 'Ketik. Lihat. Enam mesin gambar, satu layar.',
  'Type it. Hear it. Four voice engines, one screen.': 'Ketik. Dengar. Empat mesin suara, satu layar.',
  'Everything you’ve created, in one place.': 'Semua yang Anda buat, di satu tempat.',
  'Add credits →': 'Tambah kredit →',
  'Upscale any result to 2x for 1 credit.': 'Perbesar hasil apa pun ke 2x dengan 1 kredit.',
  'We couldn’t load your images right now.': 'Kami tidak bisa memuat gambar Anda saat ini.',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'Gambar dan kredit Anda aman — ini hanya gangguan baca sementara.',
  'We couldn’t load your audio right now.': 'Kami tidak bisa memuat audio Anda saat ini.',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'Audio dan kredit Anda aman — ini hanya gangguan baca sementara.',
  'We couldn’t load part of your library right now.': 'Kami tidak bisa memuat sebagian pustaka Anda saat ini.',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'Video dan kredit Anda aman — ini hanya gangguan baca sementara.',
  '↻ Try again': '↻ Coba lagi',
  '⬇ Download': '⬇ Unduh',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': 'Suka suatu suara? Studio membangun seluruh film di sekitarnya — visual, teks, dan musik.',
  'Open Studio →': 'Buka Studio →',
  'open the Studio': 'buka Studio',
  'Next episode →': 'Episode berikutnya →',
  'create your first image': 'buat gambar pertama Anda',
  'generate your first voiceover': 'buat sulih suara pertama Anda',
  'Instant drafts': 'Draf instan',
  'Deep prompt understanding': 'Pemahaman prompt yang dalam',
  'Perfect text rendering': 'Render teks sempurna',
  'Create Image': 'Buat Gambar',
  'Click-magnet YouTube covers': 'Sampul YouTube yang memancing klik',
  'Bring any image to life': 'Hidupkan gambar apa pun',
  'Instant narration': 'Narasi instan',
  'Four voice engines': 'Empat mesin suara',
  'A face that speaks your script': 'Wajah yang mengucapkan naskah Anda',
  'Every control, one screen': 'Semua kontrol, satu layar',
  'Today’s trending topics': 'Topik tren hari ini',
  'Real renders, every engine': 'Render asli, setiap mesin',
  'Type an idea — watch it become a film.': 'Ketik satu ide — lihat ia menjadi film.',
  'Start with the full toolkit': 'Mulai dengan toolkit lengkap',
  'Kineo’s own engine — 3–7 min': 'Mesin milik Kineo — 3–7 mnt',
  'The workhorse AI video engine': 'Mesin video AI andalan sehari-hari',
  'Cinematic motion & camera': 'Gerakan & kamera sinematik',
  'Film scenes, native voice & lip sync': 'Adegan film, suara asli & sinkronisasi bibir',
  'Talking video from one photo': 'Video berbicara dari satu foto',
  'From idea to posted Short in 3 steps.': 'Dari ide ke Short yang terunggah dalam 3 langkah.',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'Tanpa syuting, tanpa editing, tanpa timeline. Ketik sekali — Kineo mengerjakan sisanya.',
  'Step 1': 'Langkah 1',
  'Kineo builds it': 'Kineo membangunnya',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'AI menulis naskah yang disusun untuk retensi, merekam sulih suara, mencocokkan footage, dan menanam teks — video 9:16 yang jadi.',
  'Download & post': 'Unduh & unggah',
  'Why Kineo': 'Mengapa Kineo',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'Kebanyakan alat memotong ulang video panjang yang sudah Anda rekam. Kineo membangunnya dari nol.',
  'See how to make Shorts without filming →': 'Lihat cara membuat Shorts tanpa syuting →',
  'Generates the Short from just an idea': 'Membuat Short hanya dari satu ide',
  'Writes the script for you': 'Menulis naskah untuk Anda',
  'Finds and matches footage': 'Mencari dan mencocokkan footage',
  'your upload': 'unggahan Anda',
  'AI image studio included': 'Studio gambar AI termasuk',
  'Voice studio (text-to-speech)': 'Studio suara (teks ke suara)',
  'One-click HD film enhance': 'Peningkatan HD film sekali klik',
  'One idea — or a whole toolkit.': 'Satu ide — atau satu toolkit lengkap.',
  'Try AI Presenter →': 'Coba Presenter AI →',
  'Transparent Clips': 'Klip Transparan',
  'UGC Product Ads': 'Iklan Produk UGC',
  'Animate a photo →': 'Animasikan foto →',
  'Make a thumbnail →': 'Buat thumbnail →',
  'Free AI Shorts': 'Shorts AI Gratis',
  'Start with a niche that already works.': 'Mulai dengan niche yang sudah terbukti.',
  'Not sure? Take the quiz →': 'Belum yakin? Ikuti kuis →',
  'Pick your engine. Ship a Short today.': 'Pilih mesin Anda. Unggah Short hari ini.',
  'Cancel anytime': 'Batalkan kapan saja',
  'Generate image →': 'Buat gambar →',
  'Generate audio →': 'Buat audio →',
  'Paid plans unlock clean MP4s.': 'Paket berbayar membuka MP4 bersih.',
  'Best for starting out': 'Terbaik untuk memulai',
  'Best value per film': 'Nilai terbaik per film',
  'on Nano Banana': 'di Nano Banana',
  'Every video engine incl. MiniMax H3': 'Semua mesin video termasuk MiniMax H3',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'MP4 tanpa watermark · 100 proyek · penyimpanan 90 hari',
  ', finished': ', selesai',
  '— every engine unlocked': '— semua mesin terbuka',
  '· voice + karaoke captions + score': '· suara + teks karaoke + musik',
  '500 projects · forever storage': '500 proyek · penyimpanan selamanya',
  'Cancel anytime — 7-day money-back': 'Batalkan kapan saja — garansi uang kembali 7 hari',
  'films on Omni Flash': 'film di Omni Flash',
  '· 2 free HD enhances / month': '· 2 peningkatan HD gratis / bulan',
  'Unlimited projects · forever storage': 'Proyek tak terbatas · penyimpanan selamanya',
  'Everything in Creator': 'Semua yang ada di Creator',
  'Calculate your cost per Short →': 'Hitung biaya per Short Anda →',
  'How much do Shorts pay? →': 'Berapa bayaran Shorts? →',
  'Highest-RPM niches →': 'Niche dengan RPM tertinggi →',
  'read the full review →': 'baca ulasan lengkap →',
  'a single line is enough — or paste a full script': 'satu baris saja cukup — atau tempel naskah lengkap',
  '1080×1920 · Full HD master': '1080×1920 · master Full HD',
  'Every film is delivered as a 1080×1920 Full HD master (engines render natively at 720–768p and are mastered up). For maximum sharpness, run ✨HD Enhance on the finished film.': 'Setiap film dikirim sebagai master 1080×1920 Full HD (mesin merender secara native di 720–768p lalu dimaster ke atas). Untuk ketajaman maksimal, jalankan ✨HD Enhance pada film yang sudah jadi.',
  'Your idea first. Review the settings, then generate.': 'Ide Anda dulu. Tinjau pengaturannya, lalu buat.',
  '📷 Photo': '📷 Foto',
  '🖼️ Upload a different photo': '🖼️ Unggah foto lain',
  '🎙️ Generating…': '🎙️ Membuat…',
  '🎙️ Cloning the voice…': '🎙️ Mengkloning suara…',
  '🎙️ Upload a different sample': '🎙️ Unggah sampel lain',
  '⏹ Stop & clone': '⏹ Berhenti & kloning',
  '🎭 Generate my avatar video': '🎭 Buat video avatar saya',
  'Continue exactly where ChatGPT stopped.': 'Lanjutkan persis dari tempat ChatGPT berhenti.',
  '✨ Let AI structure it': '✨ Biarkan AI menyusunnya',
  'Optional settings': 'Pengaturan opsional',
  'optional — a pre-tested move added to your prompt': 'opsional — gerakan yang sudah teruji ditambahkan ke prompt Anda',
  'Reference image': 'Gambar referensi',
  '🖼️ Start your video from an image — coming soon': '🖼️ Mulai video Anda dari gambar — segera hadir',
  'Estimated cost': 'Perkiraan biaya',
  'Your credits buy': 'Kredit Anda cukup untuk',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'Suara, teks karaoke, dan musik termasuk. Jika render gagal, kredit Anda langsung kembali.',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'Topik sama, hook dan payoff baru — idenya sudah ditulis.',
  'Build next episode →': 'Bangun episode berikutnya →',
  'Episode 2 →': 'Episode 2 →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'Presenter AI berbicara dari satu foto — sinkron bibir, studio sendiri',
  'Your face. Your script.': 'Wajah Anda. Naskah Anda.',
  'Everything you need to make yourself speak — nothing you don’t.': 'Semua yang Anda butuhkan untuk membuat diri Anda berbicara — tanpa yang tidak perlu.',
  'BEST MOTION': 'GERAKAN TERBAIK',
  '1.5 · Realism': '1.5 · Realisme',
  '🎬 Put me in a scene': '🎬 Tempatkan saya di sebuah adegan',
  'use original photo': 'gunakan foto asli',
  '✍️ Say exactly this — word for word': '✍️ Ucapkan persis ini — kata demi kata',
  '✨ Expand into a full Short script (45–60s)': '✨ Kembangkan menjadi naskah Short lengkap (45–60 dtk)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 Mode Iklan Produk — jual produk gaya UGC',
  'Free — fills the script box above, then generate with your presenter.': 'Gratis — mengisi kotak naskah di atas, lalu buat dengan presenter Anda.',
  '2.5 · Speak in your own voice': '2.5 · Bicara dengan suara Anda sendiri',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ Suara dikloning — narasi akan berbicara dengan suara ini.',
  'use a default voice': 'gunakan suara default',
  '🎬 Full video — face the whole time': '🎬 Video penuh — wajah sepanjang waktu',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 Presenter AI — cepat & alami · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro — kualitas foto premium · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 Body Motion — tubuh, tangan & gerakan · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ Klasik — talking head · 110 cr',
  'you have': 'Anda punya',
  'to create your avatar video.': 'untuk membuat video avatar Anda.',
  '5 · Gesture clips — transparent background': '5 · Klip gerakan — latar transparan',
  'auto-refunded if it fails': 'dikembalikan otomatis jika gagal',
  '⬇️ Download transparent WebM': '⬇️ Unduh WebM transparan',
  '⬇️ Original MP4 (with background)': '⬇️ MP4 asli (dengan latar)',
  'Pick a face to preview': 'Pilih wajah untuk pratinjau',
  '↺ Make another': '↺ Buat lagi',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'Orang, hewan peliharaan, produk, foto keluarga lama — unggah foto atau tempel tautan gambar publik dan lihat ia bergerak.',
  'The photo': 'Foto',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': 'JPG/PNG hingga 8 MB. Tautan publik diunduh dan divalidasi dengan aman di server kami.',
  'sign in': 'masuk',
  'Kineo will fetch and validate it on the server when you animate.': 'Kineo akan mengambil dan memvalidasinya di server saat Anda menganimasikan.',
  'Upload a photo to preview': 'Unggah foto untuk pratinjau',
  '🖼️ Upload a photo': '🖼️ Unggah foto',
  '✨ Bring it to life': '✨ Hidupkan',
  'Uploading your photo…': 'Mengunggah foto Anda…',
  'Bringing your photo to life… (1–3 min)': 'Menghidupkan foto Anda… (1–3 mnt)',
  'Alive!': 'Hidup!',
  '🌬️ Subtle & real': '🌬️ Halus & nyata',
  '😊 Person comes alive': '😊 Orangnya menjadi hidup',
  'Type your idea first': 'Ketik ide Anda dulu',
  '📖 True Story': '📖 Kisah Nyata',
  'Paste your ChatGPT script': 'Tempel naskah ChatGPT Anda',
  'First Short complete': 'Short pertama selesai',
  'Keep your show moving': 'Jaga acara Anda tetap berjalan',
  'Cheapest way to see your idea as a film': 'Cara termurah melihat ide Anda menjadi film',
  'Slow Dolly-In': 'Dolly-In Perlahan',
  'FPV Drone': 'Drone FPV',
  'Macro Detail': 'Detail Makro',
  'Sharing & creator options': 'Berbagi & opsi kreator',
  'We couldn’t load your videos right now': 'Kami tidak bisa memuat video Anda saat ini',
  'Your videos and credits are safe — this is a temporary read hiccup, not a lost library.': 'Video dan kredit Anda aman — ini gangguan baca sementara, bukan pustaka yang hilang.',
  '⚡ Generate Video': '⚡ Buat Video',
  'Prefer clean exports now? Starter includes': 'Ingin ekspor bersih sekarang? Starter mencakup',
  'credits each month for': 'kredit setiap bulan untuk',
  'Your existing files stay available. Starter applies to new exports after checkout.': 'File Anda yang ada tetap tersedia. Starter berlaku untuk ekspor baru setelah checkout.',
  'Build Next Episode First': 'Bangun Episode Berikutnya Dulu',
  'Video unavailable': 'Video tidak tersedia',
  'Free MP4 includes the Kineo watermark': 'MP4 gratis menyertakan watermark Kineo',
  'Free distribution · latest Short': 'Distribusi gratis · Short terbaru',
  'Send it to one person for feedback': 'Kirim ke satu orang untuk masukan',
  'Copy a public watch page for your finished video. Your friend can watch it without logging in, then use “Make one like this” if the idea inspires them.': 'Salin halaman tonton publik untuk video Anda yang sudah jadi. Teman Anda bisa menontonnya tanpa masuk, lalu memakai “Buat yang seperti ini” jika idenya menginspirasi.',
  'Public watch links are temporarily paused': 'Tautan tonton publik sementara dijeda',
  'Your video stays in your account. Download the MP4 if you want to send it directly; Kineo will not publish a public page without an explicit visibility choice.': 'Video Anda tetap di akun Anda. Unduh MP4 jika ingin mengirimnya langsung; Kineo tidak akan menerbitkan halaman publik tanpa pilihan visibilitas yang eksplisit.',
  'Loading…': 'Memuat…',
  'For new videos ·': 'Untuk video baru ·',
  'Published it?': 'Sudah diunggah?',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'Tajam, menghadap depan, satu orang. Untuk gerakan tubuh, gunakan foto setengah badan/seluruh badan dengan kedua tangan terlihat. Bilah hitam dihapus otomatis.',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'Hasil profesional terbaik: unggah klip vertikal 5–20 dtk yang melakukan gerakan asli yang Anda inginkan, kira-kira sepanjang naskah. Sync-3 mengganti ucapan sambil mempertahankan wajah dan gerakan tubuh asli. MP4/MOV hingga 40 MB.',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'Saya mengonfirmasi bahwa saya berhak menggunakan citra orang ini dan menyetujui animasi oleh AI.',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': 'Unggah sampel suara jernih ~30-60 dtk (satu pembicara, sedikit derau latar) dan narasi akan diucapkan dengan suara itu. Gunakan hanya suara yang berhak Anda pakai.',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'Video kata demi kata selalu menampilkan wajah Anda sepanjang waktu (pendek — tidak butuh b-roll).',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'Video realisme maksimal dan adegan buatan menjaga presenter di layar selama seluruh narasi.',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ Intro hook — Anda membuka, b-roll menceritakan kisahnya',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'Klip pendek presenter Anda melambai, menunjuk, mempresentasikan — dikirim sebagai WebM dengan latar transparan ASLI. Seret langsung ke Storyline, Premiere, CapCut, atau slide apa pun. Tanpa green screen, tanpa keying.',
  'Cinematic film — 9-image consistency': 'Film sinematik — konsistensi 9 gambar',
  '#1-ranked video model — Aug 2026 arena': 'Model video peringkat #1 — arena Agu 2026',
  'Cinematic motion and camera work': 'Gerakan sinematik dan kerja kamera',
  'Shorts money & growth': 'Uang & pertumbuhan dari Shorts',
  'Compare Kineo with 27 AI video tools →': 'Bandingkan Kineo dengan 27 alat video AI →',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'Presenter berbicara, karakter yang bisa dipakai ulang, klip transparan, iklan produk — plus semua yang dibutuhkan untuk menemukan dan menunggangi tren.',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'Satu foto + naskah Anda — video berbicara dengan sinkron bibir kelas studio, gaya HeyGen.',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'Simpan karakter sekali — wajah yang persis sama di setiap video dan thumbnail yang Anda buat.',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'Gerakan presenter — melambai, menunjuk, mempresentasikan — sebagai WebM dengan latar transparan asli.',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'Tempel produk apa pun — dapatkan iklan 15-30 dtk gaya kreator, ditulis dan diucapkan untuk Anda.',
  'Bring any still photo to life as a moving, postable video.': 'Hidupkan foto diam apa pun menjadi video bergerak yang siap diunggah.',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'Thumbnail yang layak diklik dengan gaya channel terbesar — dari satu prompt.',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'Setiap niche di bawah punya halaman generator sendiri, prompt yang disetel, dan contoh nyata.',
  'Is the video really mine to post?': 'Apakah video ini benar-benar milik saya untuk diunggah?',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'Paket berbayar membuka MP4 bersih tanpa watermark untuk YouTube, TikTok, atau Reels.',
  'Do I need any editing skills?': 'Apakah saya perlu keahlian editing?',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'Tidak. Anda mengetik satu ide dan AI menulis naskah, merekam suara, mencari footage, dan menambahkan teks.',
  'Is there a watermark?': 'Apakah ada watermark?',
  'Paid plans export clean, watermark-free MP4s.': 'Paket berbayar mengekspor MP4 bersih tanpa watermark.',
  'Can Kineo also generate images and voiceovers?': 'Apakah Kineo juga bisa membuat gambar dan sulih suara?',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'Ya — Kineo menyertakan studio gambar AI (6 mesin termasuk FLUX, Seedream, dan Nano Banana Pro, mulai 1 kredit per gambar) dan studio suara dengan 4 mesin teks-ke-suara (mulai 1 kredit per 1000 karakter). Semua yang Anda buat tersimpan di Pustaka Anda.',
  'Can I make my videos sharper?': 'Bisakah saya membuat video lebih tajam?',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'Setiap video punya opsi Enhance sekali klik yang ditenagai restorasi film Topaz — menghilangkan artefak kompresi, memulihkan detail, dan menambahkan grain sinematik halus. 10 kredit per video; paket Studio menyertakan 2 peningkatan gratis per bulan.',
  'Can I use my own script?': 'Bisakah saya memakai naskah sendiri?',
  'What if a generation fails?': 'Bagaimana jika pembuatan gagal?',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'Kredit Anda kembali otomatis begitu render gagal — tanpa tiket dukungan, tanpa menunggu. Anda hanya membayar video yang benar-benar Anda dapatkan.',
  'Can I cancel anytime?': 'Bisakah saya membatalkan kapan saja?',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'Kapan saja, sekali klik. Paket bersifat bulanan dan kredit Anda diperbarui setiap bulan.',
  'Can I run a whole channel with the same host?': 'Bisakah saya menjalankan seluruh channel dengan host yang sama?',
  'Can I monetize the videos?': 'Bisakah saya memonetisasi videonya?',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'Ya. Setiap video milik Anda untuk disimpan, diunggah, dan dimonetisasi — termasuk YouTube Partner Program, TikTok, dan Reels. Tidak perlu lisensi tambahan.',
  'Can I use the videos commercially, or for client work?': 'Bisakah saya memakai video secara komersial atau untuk pekerjaan klien?',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'Ya. Ketentuan kami mengizinkan Anda memakai Kineo untuk tujuan pribadi atau komersial yang sah dan menegaskan Anda tetap memiliki video yang Anda buat, sehingga Anda bisa mengunggahnya, memonetisasinya, dan menyerahkannya ke klien sebagai bagian dari layanan berbayar Anda sendiri. Tanpa lisensi tambahan, tanpa royalti per video. Dua batasan datang dari ketentuan yang sama: Anda tidak boleh menjual kembali atau mendistribusikan ulang Kineo itu sendiri, dan klip stok di dalam render dilisensikan untuk dipakai di video jadi Anda, bukan untuk diunggah ulang sebagai footage stok mandiri. Paket berbayar mengekspor MP4 bersih tanpa watermark.',
  'How long does one video take?': 'Berapa lama satu video dibuat?',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'Mode Fast biasanya selesai dalam 3–7 menit. Video buatan AI dan sinematik butuh sedikit lebih lama karena setiap adegan dibuat sebelum MP4 akhir disusun.',
  'How much does Kineo cost?': 'Berapa biaya Kineo?',
  'Kineo has three monthly plans: Starter at $': 'Kineo punya tiga paket bulanan: Starter seharga $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'kredit. Kredit dipakai per video, dan biaya sebuah video tergantung mesin yang Anda pilih, jadi render Fast dan film sinematik keluar dari saldo yang sama dengan tarif yang sangat berbeda.',
  'Which AI video engines can I use in Kineo?': 'Mesin video AI apa saja yang bisa saya pakai di Kineo?',
  ', behind one interface and one balance:': ', di balik satu antarmuka dan satu saldo:',
  'What is the best AI video generator for faceless YouTube channels?': 'Apa generator video AI terbaik untuk channel YouTube tanpa wajah?',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'Ya. Pengguna gratis yang belum pernah membayar bisa mengunduh, membagikan, dan mengunggah MP4 ber-watermark.',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'Film uji coba membawa watermark kecil — Anda bisa mengunduh, membagikan, dan mengunggah MP4-nya. Setelah uji coba, video Fast gratis membawa watermark.',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'Unduhan gratis membawa watermark; paket berbayar membuka MP4 bersih.',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'Unduhan uji coba membawa watermark, begitu juga video Fast gratis setelah uji coba, dan paket berbayar selalu mengekspor bersih.',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'Akses gratis memberi pengguna baru hingga 3 video Fast ber-watermark setiap 24 jam, tanpa kartu. Anda bisa mengunduh dan membagikannya.',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'Buat, unduh, dan bagikan hingga 3 video Fast ber-watermark setiap 24 jam, tanpa kartu.',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'Buat, tonton, unduh, dan bagikan hingga 3 video Fast ber-watermark setiap 24 jam — tanpa kartu.',
  'create, watch, download and share up to 3 Fast videos every 24h': 'buat, tonton, unduh, dan bagikan hingga 3 video Fast setiap 24 jam',
  '— no card, watermark included.': '— tanpa kartu, termasuk watermark.',
  'AI image generator — 6 engines': 'Generator gambar AI — 6 mesin',
  'AI voice generator (text to speech)': 'Generator suara AI (teks ke suara)',
  'AI video upscaler & enhancer': 'Upscaler & penyempurna video AI',
  'Trending Shorts ideas today': 'Ide Shorts yang tren hari ini',
  'AI Avatar video — your face, any script': 'Video Avatar AI — wajah Anda, naskah apa pun',
  'Kineo facts & numbers (citable)': 'Fakta & angka Kineo (dapat dikutip)',
  'Free AI Shorts generator': 'Generator Shorts AI gratis',
  'YouTube Shorts from a topic': 'YouTube Shorts dari sebuah topik',
  'ChatGPT script to YouTube Short': 'Naskah ChatGPT ke YouTube Short',
  'Shorts without filming': 'Shorts tanpa syuting',
  'Faceless niche picker': 'Pemilih niche tanpa wajah',
  'State of AI Shorts 2026': 'State of AI Shorts 2026',
  'AI Shorts for agencies & client work': 'Shorts AI untuk agensi & pekerjaan klien',
  'Trust Center — privacy, payments & ownership': 'Pusat Kepercayaan — privasi, pembayaran & kepemilikan',
  'Affiliate program - 30% recurring': 'Program afiliasi - 30% berulang',
  'Free AI Shorts by niche': 'Shorts AI gratis per niche',
  'Free script generator': 'Generator naskah gratis',
  'Product video ad script': 'Naskah iklan video produk',
  'Client video brief generator': 'Generator brief video klien',
  'Free hook generator': 'Generator hook gratis',
  'Shorts script timer': 'Pengatur waktu naskah Shorts',
  'Shorts money calculator': 'Kalkulator penghasilan Shorts',
  'How much do Shorts pay?': 'Berapa bayaran Shorts?',
  'Best AI Shorts generators': 'Generator Shorts AI terbaik',
  'TikTok vs Shorts: which pays more?': 'TikTok vs Shorts: mana yang membayar lebih?',
  'All comparisons': 'Semua perbandingan',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · Hak cipta dilindungi',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'Tergantung apakah Anda ingin footage stok yang dirangkai atau footage yang dibuat. Alat seperti InVideo dan AutoShorts memotong klip stok sesuai naskah Anda, yang lebih murah dan cukup untuk video poin pembicaraan. Kineo membuat footage dengan model seperti Veo 3.1 dan Kling 3, menjaga narasi Anda kata demi kata alih-alih menulis ulang, dan menargetkan 60 detik atau lebih agar video memenuhi syarat TikTok Creator Rewards. Jika channel Anda hidup dari visual yang tidak dimiliki orang lain, generasi menang; jika hidup dari volume, stok lebih murah.',
  'Paste the complete script from ChatGPT here…': 'Tempel naskah lengkap dari ChatGPT di sini…',
  'Paste the idea from ChatGPT here…': 'Tempel ide dari ChatGPT di sini…',
  'What’s your video about? One idea in — a finished film out: voiced, scored and captioned.': 'Video Anda tentang apa? Satu ide masuk — film jadi keluar: bersuara, bermusik, dan berteks.',
  'Settings and generation': 'Pengaturan dan pembuatan',
  'Search your videos…': 'Cari video Anda…',
  'Search your audio…': 'Cari audio Anda…',
  'Search your images by engine': 'Cari gambar Anda berdasarkan mesin',
  'No playable videos in your library yet. Check your latest project above.': 'Belum ada video yang bisa diputar di pustaka Anda. Periksa proyek terbaru Anda di atas.',
  'Make a finished Short →': 'Buat Short yang jadi →',
  'Video Editing & Creator Tools': 'Editing Video & Alat Kreator',
  'Trim, resize, change speed, mute or add text. Edit a file you already have, right in your browser. Your script and planning tools are still here below.': 'Potong, ubah ukuran, ubah kecepatan, bisukan, atau tambahkan teks. Edit file yang sudah Anda miliki, langsung di browser. Alat naskah dan perencanaan Anda masih ada di bawah.',
  '5 local editing tools': '5 alat editing lokal',
  'No generation credits to edit': 'Editing tidak memakai kredit pembuatan',
  'Edit video': 'Edit video',
  'Files up to 100 MB and 3 minutes. Local, real-time export up to 1280 px on the long edge. MP4 or WebM depending on your browser; downloads are not saved to My Videos.': 'File hingga 100 MB dan 3 menit. Ekspor lokal real-time hingga 1280 px di sisi panjang. MP4 atau WebM tergantung browser Anda; unduhan tidak disimpan ke Video Saya.',
  'Video Trimmer': 'Pemotong Video',
  'Cut the beginning or end and keep only the clip you need.': 'Potong awal atau akhir dan simpan hanya klip yang Anda perlukan.',
  'Video Resizer': 'Pengubah Ukuran Video',
  'Go vertical, square or wide. Fit the frame or crop to fill.': 'Vertikal, persegi, atau lebar. Sesuaikan bingkai atau pangkas untuk mengisi.',
  'Video Speed Changer': 'Pengubah Kecepatan Video',
  'Slow it down or speed it up, from 0.5× to 2×.': 'Perlambat atau percepat, dari 0.5× hingga 2×.',
  'Remove Audio': 'Hapus Audio',
  'Download a copy without the original audio.': 'Unduh salinan tanpa audio asli.',
  'Add Text to Video': 'Tambah Teks ke Video',
  'Add a title or message that stays on screen. Not automatic subtitles.': 'Tambahkan judul atau pesan yang tetap di layar. Bukan subtitle otomatis.',
  'No account · current Kineo plans': 'Tanpa akun · paket Kineo saat ini',
  'No account · fair-use limit': 'Tanpa akun · batas penggunaan wajar',
  'No account · unlimited in browser': 'Tanpa akun · tak terbatas di browser',
  'Edit an existing video here. Create a new one with Kineo.': 'Edit video yang ada di sini. Buat yang baru dengan Kineo.',
  'Create an AI video →': 'Buat video AI →',
  'Edit your video, preview the changes, then export a copy.': 'Edit video Anda, pratinjau perubahannya, lalu ekspor salinan.',
  'Video preview': 'Pratinjau video',
  'Preview is silent. The download keeps audio unless Mute is selected.': 'Pratinjau tanpa suara. Unduhan tetap menyertakan audio kecuali Bisukan dipilih.',
  'Start with your video': 'Mulai dengan video Anda',
  'Choose a local file. It stays on this device.': 'Pilih file lokal. File tetap di perangkat ini.',
  'Choose video file': 'Pilih file video',
  'Video file': 'File video',
  'Video settings': 'Pengaturan video',
  'Aspect ratio': 'Rasio aspek',
  'Playback speed': 'Kecepatan pemutaran',
  'On-screen text (100 characters, 3 lines)': 'Teks di layar (100 karakter, 3 baris)',
  'Add a title or message': 'Tambahkan judul atau pesan',
  'Export edited video': 'Ekspor video yang diedit',
  'Export happens in real time. Keep this tab visible. Re-encoded at up to 1280 px on the long edge; format depends on your browser.': 'Ekspor berjalan secara real-time. Biarkan tab ini terlihat. Dienkode ulang hingga 1280 px di sisi panjang; format tergantung browser Anda.',
  'Making a 4-second sample on your device…': 'Membuat sampel 4 detik di perangkat Anda…',
  'Reading your file…': 'Membaca file Anda…',
  'Export result': 'Hasil ekspor',
  'Your edited video': 'Video Anda yang diedit',
  'Local download only. This copy is not saved to My Videos.': 'Unduhan lokal saja. Salinan ini tidak disimpan ke Video Saya.',
  'Exported video': 'Video yang diekspor',
  'No upload. No generation credits. Your original is never overwritten.': 'Tanpa unggah. Tanpa kredit pembuatan. File asli Anda tidak pernah ditimpa.',
  'Up to 100 MB · 3 minutes · MP4/WebM input recommended. These are basic editing tools, not the CapCut app.': 'Hingga 100 MB · 3 menit · input MP4/WebM disarankan. Ini alat editing dasar, bukan aplikasi CapCut.',
  'Need a new video? Open Kineo Studio →': 'Butuh video baru? Buka Kineo Studio →',
  'This browser cannot export video here. Try the latest desktop Chrome or Edge.': 'Browser ini tidak bisa mengekspor video di sini. Coba Chrome atau Edge desktop terbaru.',
  'Choose a non-empty video file of up to 100 MB.': 'Pilih file video yang tidak kosong hingga 100 MB.',
  'Use a playable clip of up to 3 minutes. Very large dimensions are not supported.': 'Gunakan klip yang bisa diputar hingga 3 menit. Dimensi yang sangat besar tidak didukung.',
  'Check the start and end: select at least 0.25 seconds within your clip.': 'Periksa awal dan akhir: pilih setidaknya 0.25 detik di dalam klip Anda.',
  'Choose a speed between 0.5× and 2×.': 'Pilih kecepatan antara 0.5× dan 2×.',
  'Use up to 100 characters and 3 lines of text.': 'Gunakan hingga 100 karakter dan 3 baris teks.',
  'Choose a supported aspect ratio, framing and text position.': 'Pilih rasio aspek, pembingkaian, dan posisi teks yang didukung.',
  'This file could not be decoded. Try an MP4 (H.264) or WebM file.': 'File ini tidak bisa didekode. Coba file MP4 (H.264) atau WebM.',
  'Export stopped because this tab was hidden. Keep it open and visible, then export again. Your original is safe.': 'Ekspor berhenti karena tab ini disembunyikan. Biarkan terbuka dan terlihat, lalu ekspor lagi. File asli Anda aman.',
  'Export stopped making progress. Try a shorter clip or desktop Chrome. Your original is unchanged.': 'Ekspor berhenti berjalan. Coba klip yang lebih pendek atau Chrome desktop. File asli Anda tidak berubah.',
  'Audio could not start. Try exporting again, or choose Mute video.': 'Audio tidak bisa dimulai. Coba ekspor lagi, atau pilih Bisukan video.',
  'The browser blocked playback. Try exporting again from this tab.': 'Browser memblokir pemutaran. Coba ekspor lagi dari tab ini.',
  'Cancelled. Your original file is unchanged.': 'Dibatalkan. File asli Anda tidak berubah.',
  'Could not finish this export. Try a shorter clip or another supported browser.': 'Ekspor ini tidak bisa diselesaikan. Coba klip yang lebih pendek atau browser lain yang didukung.',
  'The browser produced an incomplete file, so we did not offer it for download. Try again with this tab visible, or use desktop Chrome.': 'Browser menghasilkan file yang tidak lengkap, jadi kami tidak menawarkannya untuk diunduh. Coba lagi dengan tab ini terlihat, atau gunakan Chrome desktop.',
  'Create new video': 'Buat video baru',
  'Your idea': 'Ide Anda',
  'Natural': 'Alami',
  'Working…': 'Memproses…',
  '🎲 Surprise me': '🎲 Kejutkan saya',
  '📝 Use my script as is': '📝 Gunakan naskah saya apa adanya',
  'Camera preset': 'Preset kamera',
  'Your latest videos': 'Video terbaru Anda',
  'Presenter': 'Presenter',
  '1 · Who’s talking': '1 · Siapa yang bicara',
  '🎭 your characters': '🎭 karakter Anda',
  '🎯 Max realism — animate my real photo': '🎯 Realisme maksimal — animasikan foto asli saya',
  '✓ Scene ready — preview on the right.': '✓ Adegan siap — pratinjau di kanan.',
  '2 · What they say': '2 · Apa yang mereka katakan',
  '3 · How it looks': '3 · Tampilannya',
  'Motion': 'Gerakan',
  '⬇ Download MP4': '⬇ Unduh MP4',
  'One photo. Suddenly alive.': 'Satu foto. Tiba-tiba hidup.',
  'Cost per clip': 'Biaya per klip',
  '↺ Animate another': '↺ Animasikan lagi',
  'Grow': 'Bertumbuh',
  'Sending to the motion engine…': 'Mengirim ke mesin gerakan…',
  '📊 Facts': '📊 Fakta',
  'Turn it into episode 2': 'Jadikan episode 2',
  'Start here': 'Mulai di sini',
  'Engine': 'Mesin',
  'Highly aesthetic, by xAI': 'Sangat estetis, oleh xAI',
  'Google’s best image model': 'Model gambar terbaik Google',
  'AI voiceover included': 'Sulih suara AI termasuk',
  '6 engines': '6 mesin',
  'AI Presenter': 'Presenter AI',
  'Lock a character →': 'Kunci karakter →',
  'Make a clip →': 'Buat klip →',
  'Make an ad →': 'Buat iklan →',
  'Generate free →': 'Buat gratis →',
  'Creating…': 'Membuat…',
  'Describe your image first': 'Deskripsikan gambar Anda dulu',
  'Type your script first': 'Ketik naskah Anda dulu',
  'From the founder': 'Dari pendiri',
  'Faceless video generator': 'Generator video tanpa wajah',
  'Text to video Shorts': 'Shorts teks ke video',
  'Cheapest AI Shorts maker': 'Pembuat Shorts AI termurah',
  'Faceless channel ideas (2026)': 'Ide channel tanpa wajah (2026)',
  'Shorts idea widget': 'Widget ide Shorts',
  'Live case study: our channel on Autopilot': 'Studi kasus langsung: channel kami di Autopilot',
  'Free YouTube Shorts scripts': 'Naskah YouTube Shorts gratis',
  'Comment to Short script': 'Komentar menjadi naskah Short',
  'Business video content planner': 'Perencana konten video bisnis',
  'Real estate video maker': 'Pembuat video properti',
  'Shorts title & hashtag generator': 'Generator judul & hashtag Shorts',
  'Free viral score': 'Skor viral gratis',
  'Make money clipping with AI': 'Hasilkan uang dengan clipping AI',
  'Shorts RPM by niche (2026)': 'RPM Shorts per niche (2026)',
  'Can you monetize AI videos?': 'Bisakah video AI dimonetisasi?',
}
