// KINEO-INTERFACE-16-LINGUAS-2026-09-21 — interface em it. Só copy autoral da interface: nunca prompt,
// título, resultado, nome de motor ou erro de API. Frase fora daqui cai em inglês (components/InterfaceLanguage.tsx).
// Gerado de scratchpad/tr-it.js sobre o corpus vivo de frases (415); números e "Kineo" preservados por construção.
export const DICT: Record<string, string> = {
  'Videos for businesses': 'Video per aziende',
  'Generation failed': 'Generazione non riuscita',
  'You can retry safely.': 'Puoi riprovare in tutta sicurezza.',
  'This engine is not available on your account right now': 'Questo motore non è disponibile sul tuo account in questo momento',
  'Retrying the same engine will stop at this same place. Pick another engine to keep going.': 'Riprovare con lo stesso motore si fermerà nello stesso punto. Scegli un altro motore per continuare.',
  'The engine is cooling down after two refunded attempts': 'Il motore si sta raffreddando dopo due tentativi rimborsati',
  'Starting another one right now stops at this same place. Give it a few minutes.': 'Avviarne un altro adesso si ferma nello stesso punto. Dagli qualche minuto.',
  'Starting another one right now stops at this same place. The button below unlocks by itself.': 'Avviarne un altro adesso si ferma nello stesso punto. Il pulsante qui sotto si sblocca da solo.',
  'We stopped waiting on this render instead of leaving you hanging': 'Abbiamo smesso di aspettare questo render invece di lasciarti in sospeso',
  'This one ran far longer than any video that finishes here. Starting again is worth it.': 'Questo è durato molto più di qualsiasi video che finisce qui. Vale la pena ricominciare.',
  'The video engine is busy — this is on our side, not your idea': 'Il motore video è occupato — dipende da noi, non dalla tua idea',
  'Nothing about your text is wrong. Trying again in a few minutes usually goes straight through.': 'Non c’è nulla di sbagliato nel tuo testo. Riprovare tra qualche minuto di solito va a buon fine subito.',
  'Create Video': 'Crea video',
  'Create a new video': 'Crea un nuovo video',
  'AI Avatar Studio': 'Studio Avatar IA',
  'Viral Templates': 'Modelli virali',
  'Channel Builder': 'Costruttore di canali',
  'Invite & Earn': 'Invita e guadagna',
  'Start free': 'Inizia gratis',
  'Try 7 days for $1': 'Prova 7 giorni a $1',
  'Pick a lane': 'Scegli un percorso',
  'All free tools': 'Tutti gli strumenti gratuiti',
  'Terms of Service': 'Termini di servizio',
  'Trust Center': 'Centro fiducia',
  'Review & publish': 'Rivedi e pubblica',
  'Your image': 'La tua immagine',
  'Cost per image': 'Costo per immagine',
  'No videos yet': 'Ancora nessun video',
  'No audio yet': 'Ancora nessun audio',
  '🎬 Studio — generate video': '🎬 Studio — genera video',
  '🎨 Images — create image': '🎨 Immagini — crea immagine',
  '🎙 Audio — text to speech': '🎙 Audio — da testo a voce',
  'Type it. See it. Six image engines, one screen.': 'Scrivilo. Guardalo. Sei motori di immagini, una sola schermata.',
  'Type it. Hear it. Four voice engines, one screen.': 'Scrivilo. Ascoltalo. Quattro motori vocali, una sola schermata.',
  'Everything you’ve created, in one place.': 'Tutto ciò che hai creato, in un unico posto.',
  'Add credits →': 'Aggiungi crediti →',
  'Upscale any result to 2x for 1 credit.': 'Ingrandisci qualsiasi risultato a 2x per 1 credito.',
  'We couldn’t load your images right now.': 'Non riusciamo a caricare le tue immagini in questo momento.',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'Le tue immagini e i tuoi crediti sono al sicuro — è solo un intoppo temporaneo di lettura.',
  'We couldn’t load your audio right now.': 'Non riusciamo a caricare il tuo audio in questo momento.',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'Il tuo audio e i tuoi crediti sono al sicuro — è solo un intoppo temporaneo di lettura.',
  'We couldn’t load part of your library right now.': 'Non riusciamo a caricare parte della tua libreria in questo momento.',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'I tuoi video e i tuoi crediti sono al sicuro — è solo un intoppo temporaneo di lettura.',
  '↻ Try again': '↻ Riprova',
  '⬇ Download': '⬇ Scarica',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': 'Ti piace una voce? Lo Studio costruisce l’intero film attorno a lei — immagini, sottotitoli e colonna sonora.',
  'Open Studio →': 'Apri lo Studio →',
  'open the Studio': 'apri lo Studio',
  'Next episode →': 'Prossimo episodio →',
  'create your first image': 'crea la tua prima immagine',
  'generate your first voiceover': 'genera la tua prima voce narrante',
  'Instant drafts': 'Bozze istantanee',
  'Deep prompt understanding': 'Comprensione profonda del prompt',
  'Perfect text rendering': 'Resa del testo perfetta',
  'Create Image': 'Crea immagine',
  'Click-magnet YouTube covers': 'Copertine YouTube che attirano clic',
  'Bring any image to life': 'Dai vita a qualsiasi immagine',
  'Instant narration': 'Narrazione istantanea',
  'Four voice engines': 'Quattro motori vocali',
  'A face that speaks your script': 'Un volto che dice il tuo copione',
  'Every control, one screen': 'Ogni controllo, una schermata',
  'Today’s trending topics': 'Argomenti di tendenza di oggi',
  'Real renders, every engine': 'Render reali, ogni motore',
  'Type an idea — watch it become a film.': 'Scrivi un’idea — guardala diventare un film.',
  'Start with the full toolkit': 'Inizia con il kit completo',
  'Kineo’s own engine — 3–7 min': 'Il motore di Kineo — 3–7 min',
  'The workhorse AI video engine': 'Il motore video IA da lavoro',
  'Cinematic motion & camera': 'Movimento e camera cinematografici',
  'Film scenes, native voice & lip sync': 'Scene da film, voce nativa e sincronizzazione labiale',
  'Talking video from one photo': 'Video parlante da una foto',
  'From idea to posted Short in 3 steps.': 'Dall’idea allo Short pubblicato in 3 passaggi.',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'Niente riprese, niente montaggio, niente timeline. Scrivi una volta — Kineo fa il resto.',
  'Step 1': 'Passaggio 1',
  'Kineo builds it': 'Kineo lo costruisce',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'L’IA scrive un copione strutturato per la retention, registra la voce narrante, abbina le immagini e imprime i sottotitoli — un video 9:16 finito.',
  'Download & post': 'Scarica e pubblica',
  'Why Kineo': 'Perché Kineo',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'La maggior parte degli strumenti ritaglia un video lungo che hai già girato. Kineo lo costruisce da zero.',
  'See how to make Shorts without filming →': 'Scopri come fare Shorts senza girare →',
  'Generates the Short from just an idea': 'Genera lo Short da una semplice idea',
  'Writes the script for you': 'Scrive il copione per te',
  'Finds and matches footage': 'Trova e abbina le immagini',
  'your upload': 'il tuo upload',
  'AI image studio included': 'Studio immagini IA incluso',
  'Voice studio (text-to-speech)': 'Studio vocale (da testo a voce)',
  'One-click HD film enhance': 'Miglioramento HD del film con un clic',
  'One idea — or a whole toolkit.': 'Un’idea — o un intero kit di strumenti.',
  'Try AI Presenter →': 'Prova il Presentatore IA →',
  'Transparent Clips': 'Clip trasparenti',
  'UGC Product Ads': 'Annunci prodotto UGC',
  'Animate a photo →': 'Anima una foto →',
  'Make a thumbnail →': 'Crea una miniatura →',
  'Free AI Shorts': 'Shorts IA gratis',
  'Start with a niche that already works.': 'Parti da una nicchia che già funziona.',
  'Not sure? Take the quiz →': 'Non sei sicuro? Fai il quiz →',
  'Pick your engine. Ship a Short today.': 'Scegli il motore. Pubblica uno Short oggi.',
  'Cancel anytime': 'Annulla quando vuoi',
  'Generate image →': 'Genera immagine →',
  'Generate audio →': 'Genera audio →',
  'Paid plans unlock clean MP4s.': 'I piani a pagamento sbloccano gli MP4 puliti.',
  'Best for starting out': 'Ideale per iniziare',
  'Best value per film': 'Miglior valore per film',
  'on Nano Banana': 'su Nano Banana',
  'Every video engine incl. MiniMax H3': 'Tutti i motori video, incl. MiniMax H3',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'MP4 senza filigrana · 100 progetti · archiviazione 90 giorni',
  ', finished': ', finito',
  '— every engine unlocked': '— tutti i motori sbloccati',
  '· voice + karaoke captions + score': '· voce + sottotitoli karaoke + colonna sonora',
  '500 projects · forever storage': '500 progetti · archiviazione per sempre',
  'Cancel anytime — 7-day money-back': 'Annulla quando vuoi — 7 giorni soddisfatti o rimborsati',
  'films on Omni Flash': 'film su Omni Flash',
  '· 2 free HD enhances / month': '· 2 miglioramenti HD gratuiti / mese',
  'Unlimited projects · forever storage': 'Progetti illimitati · archiviazione per sempre',
  'Everything in Creator': 'Tutto ciò che c’è in Creator',
  'Calculate your cost per Short →': 'Calcola il tuo costo per Short →',
  'How much do Shorts pay? →': 'Quanto pagano gli Shorts? →',
  'Highest-RPM niches →': 'Nicchie con l’RPM più alto →',
  'read the full review →': 'leggi la recensione completa →',
  'a single line is enough — or paste a full script': 'basta una sola riga — oppure incolla un copione completo',
  '1080×1920 · Full HD master': '1080×1920 · master Full HD',
  'Every film is delivered as a 1080×1920 Full HD master (engines render natively at 720–768p and are mastered up). For maximum sharpness, run ✨HD Enhance on the finished film.': 'Ogni film viene consegnato come master 1080×1920 Full HD (i motori renderizzano nativamente a 720–768p e vengono masterizzati verso l’alto). Per la massima nitidezza, esegui ✨HD Enhance sul film finito.',
  'Your idea first. Review the settings, then generate.': 'Prima la tua idea. Controlla le impostazioni, poi genera.',
  '📷 Photo': '📷 Foto',
  '🖼️ Upload a different photo': '🖼️ Carica un’altra foto',
  '🎙️ Generating…': '🎙️ Generazione in corso…',
  '🎙️ Cloning the voice…': '🎙️ Clonazione della voce…',
  '🎙️ Upload a different sample': '🎙️ Carica un altro campione',
  '⏹ Stop & clone': '⏹ Ferma e clona',
  '🎭 Generate my avatar video': '🎭 Genera il mio video avatar',
  'Continue exactly where ChatGPT stopped.': 'Continua esattamente da dove si è fermato ChatGPT.',
  '✨ Let AI structure it': '✨ Lascia che l’IA lo strutturi',
  'Optional settings': 'Impostazioni opzionali',
  'optional — a pre-tested move added to your prompt': 'opzionale — un movimento pre-testato aggiunto al tuo prompt',
  'Reference image': 'Immagine di riferimento',
  '🖼️ Start your video from an image — coming soon': '🖼️ Inizia il tuo video da un’immagine — presto disponibile',
  'Estimated cost': 'Costo stimato',
  'Your credits buy': 'I tuoi crediti bastano per',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'Voce, sottotitoli karaoke e colonna sonora inclusi. Se un render fallisce, i tuoi crediti tornano subito.',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'Stesso argomento, nuovo hook e nuovo finale — l’idea è già scritta.',
  'Build next episode →': 'Costruisci il prossimo episodio →',
  'Episode 2 →': 'Episodio 2 →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'Presentatore IA parlante da una foto — labiale sincronizzato, uno studio tutto suo',
  'Your face. Your script.': 'Il tuo volto. Il tuo copione.',
  'Everything you need to make yourself speak — nothing you don’t.': 'Tutto ciò che ti serve per farti parlare — niente di superfluo.',
  'BEST MOTION': 'MIGLIOR MOVIMENTO',
  '1.5 · Realism': '1.5 · Realismo',
  '🎬 Put me in a scene': '🎬 Mettimi in una scena',
  'use original photo': 'usa la foto originale',
  '✍️ Say exactly this — word for word': '✍️ Di’ esattamente questo — parola per parola',
  '✨ Expand into a full Short script (45–60s)': '✨ Espandi in un copione completo per Short (45–60 s)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 Modalità annuncio prodotto — vendi un prodotto in stile UGC',
  'Free — fills the script box above, then generate with your presenter.': 'Gratis — riempie il campo del copione qui sopra, poi genera con il tuo presentatore.',
  '2.5 · Speak in your own voice': '2.5 · Parla con la tua voce',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ Voce clonata — la narrazione userà questa voce.',
  'use a default voice': 'usa una voce predefinita',
  '🎬 Full video — face the whole time': '🎬 Video completo — il volto per tutto il tempo',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 Presentatore IA — veloce e naturale · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro — qualità foto premium · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 Body Motion — busto, mani e gesti · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ Classico — talking head · 110 cr',
  'you have': 'hai',
  'to create your avatar video.': 'per creare il tuo video avatar.',
  '5 · Gesture clips — transparent background': '5 · Clip di gesti — sfondo trasparente',
  'auto-refunded if it fails': 'rimborso automatico in caso di errore',
  '⬇️ Download transparent WebM': '⬇️ Scarica WebM trasparente',
  '⬇️ Original MP4 (with background)': '⬇️ MP4 originale (con sfondo)',
  'Pick a face to preview': 'Scegli un volto per l’anteprima',
  '↺ Make another': '↺ Fanne un altro',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'Persone, animali, prodotti, vecchie foto di famiglia — carica una foto o incolla un link pubblico a un’immagine e guardala muoversi.',
  'The photo': 'La foto',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': 'JPG/PNG fino a 8 MB. I link pubblici vengono scaricati e verificati in sicurezza sul nostro server.',
  'sign in': 'accedi',
  'Kineo will fetch and validate it on the server when you animate.': 'Kineo la recupererà e verificherà sul server quando animerai.',
  'Upload a photo to preview': 'Carica una foto per l’anteprima',
  '🖼️ Upload a photo': '🖼️ Carica una foto',
  '✨ Bring it to life': '✨ Dalle vita',
  'Uploading your photo…': 'Caricamento della tua foto…',
  'Bringing your photo to life… (1–3 min)': 'Stiamo dando vita alla tua foto… (1–3 min)',
  'Alive!': 'Viva!',
  '🌬️ Subtle & real': '🌬️ Sottile e reale',
  '😊 Person comes alive': '😊 La persona prende vita',
  'Type your idea first': 'Scrivi prima la tua idea',
  '📖 True Story': '📖 Storia vera',
  'Paste your ChatGPT script': 'Incolla il tuo copione da ChatGPT',
  'First Short complete': 'Primo Short completato',
  'Keep your show moving': 'Tieni in movimento il tuo show',
  'Cheapest way to see your idea as a film': 'Il modo più economico per vedere la tua idea come film',
  'Slow Dolly-In': 'Dolly-in lento',
  'FPV Drone': 'Drone FPV',
  'Macro Detail': 'Dettaglio macro',
  'Sharing & creator options': 'Condivisione e opzioni per creator',
  'We couldn’t load your videos right now': 'Non riusciamo a caricare i tuoi video in questo momento',
  'Your videos and credits are safe — this is a temporary read hiccup, not a lost library.': 'I tuoi video e i tuoi crediti sono al sicuro — è un intoppo temporaneo di lettura, non una libreria persa.',
  '⚡ Generate Video': '⚡ Genera video',
  'Prefer clean exports now? Starter includes': 'Preferisci export puliti adesso? Starter include',
  'credits each month for': 'crediti al mese per',
  'Your existing files stay available. Starter applies to new exports after checkout.': 'I tuoi file esistenti restano disponibili. Starter vale per i nuovi export dopo il checkout.',
  'Build Next Episode First': 'Prima costruisci il prossimo episodio',
  'Video unavailable': 'Video non disponibile',
  'Free MP4 includes the Kineo watermark': 'L’MP4 gratuito include la filigrana Kineo',
  'Free distribution · latest Short': 'Distribuzione gratuita · ultimo Short',
  'Send it to one person for feedback': 'Invialo a una persona per un feedback',
  'Copy a public watch page for your finished video. Your friend can watch it without logging in, then use “Make one like this” if the idea inspires them.': 'Copia una pagina pubblica di visione per il tuo video finito. Il tuo amico può guardarlo senza accedere e poi usare “Fanne uno così” se l’idea lo ispira.',
  'Public watch links are temporarily paused': 'I link pubblici di visione sono temporaneamente sospesi',
  'Your video stays in your account. Download the MP4 if you want to send it directly; Kineo will not publish a public page without an explicit visibility choice.': 'Il tuo video resta nel tuo account. Scarica l’MP4 se vuoi inviarlo direttamente; Kineo non pubblicherà una pagina pubblica senza una scelta esplicita di visibilità.',
  'Loading…': 'Caricamento…',
  'For new videos ·': 'Per i nuovi video ·',
  'Published it?': 'L’hai pubblicato?',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'Nitida, frontale, una sola persona. Per il movimento del corpo usa una foto a mezzo busto o a figura intera con entrambe le mani visibili. Le bande nere vengono rimosse automaticamente.',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'Miglior risultato professionale: carica una clip verticale di 5–20 s con i gesti reali che vuoi, di durata simile al copione. Sync-3 sostituisce il parlato preservando il volto e il movimento reali. MP4/MOV fino a 40 MB.',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'Confermo di avere il diritto di usare l’immagine di questa persona e acconsento a che venga animata dall’IA.',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': 'Carica un campione vocale chiaro di ~30-60 s (una sola voce, poco rumore di fondo) e la narrazione sarà detta con quella voce. Usa solo una voce che hai il diritto di usare.',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'I video parola per parola mostrano il tuo volto per tutto il tempo (sono brevi — niente b-roll necessario).',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'I video a massimo realismo e a scena costruita tengono il presentatore sullo schermo per tutta la narrazione.',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ Intro con hook — tu apri, il b-roll racconta la storia',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'Brevi clip del tuo presentatore che saluta, indica, presenta — consegnate in WebM con uno sfondo trasparente VERO. Trascinale direttamente in Storyline, Premiere, CapCut o in qualsiasi slide. Niente green screen, niente scontorno.',
  'Cinematic film — 9-image consistency': 'Film cinematografico — coerenza su 9 immagini',
  '#1-ranked video model — Aug 2026 arena': 'Modello video n. 1 in classifica — arena ago 2026',
  'Cinematic motion and camera work': 'Movimento e lavoro di camera cinematografici',
  'Shorts money & growth': 'Soldi e crescita con gli Shorts',
  'Compare Kineo with 27 AI video tools →': 'Confronta Kineo con 27 strumenti video IA →',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'Presentatori parlanti, personaggi riutilizzabili, clip trasparenti, annunci prodotto — più tutto il necessario per trovare e cavalcare una tendenza.',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'Una foto + il tuo copione — un video parlante con sincronizzazione labiale da studio, in stile HeyGen.',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'Salva un personaggio una volta — esattamente lo stesso volto in ogni video e miniatura che crei.',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'Gesti da presentatore — salutare, indicare, presentare — in WebM con un vero sfondo trasparente.',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'Incolla qualsiasi prodotto — ottieni un annuncio di 15-30 s in stile creator, sceneggiato e parlato per te.',
  'Bring any still photo to life as a moving, postable video.': 'Dai vita a qualsiasi foto statica come video in movimento, pronto da pubblicare.',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'Miniature che invitano al clic nello stile dei canali più grandi — da un prompt.',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'Ogni nicchia qui sotto ha la propria pagina di generazione, prompt calibrati ed esempi reali.',
  'Is the video really mine to post?': 'Il video è davvero mio da pubblicare?',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'I piani a pagamento sbloccano l’MP4 pulito, senza filigrana, per YouTube, TikTok o Reels.',
  'Do I need any editing skills?': 'Servono competenze di montaggio?',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'Nessuna. Scrivi un’idea e l’IA scrive il copione, registra la voce, trova le immagini e aggiunge i sottotitoli.',
  'Is there a watermark?': 'C’è una filigrana?',
  'Paid plans export clean, watermark-free MP4s.': 'I piani a pagamento esportano MP4 puliti, senza filigrana.',
  'Can Kineo also generate images and voiceovers?': 'Kineo genera anche immagini e voci narranti?',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'Sì — Kineo include uno studio immagini IA (6 motori tra cui FLUX, Seedream e Nano Banana Pro, da 1 credito per immagine) e uno studio vocale con 4 motori da testo a voce (da 1 credito ogni 1000 caratteri). Tutto ciò che crei vive nella tua Libreria.',
  'Can I make my videos sharper?': 'Posso rendere i miei video più nitidi?',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'Ogni video ha un’opzione di miglioramento con un clic basata sul restauro cinematografico Topaz — rimuove gli artefatti di compressione, recupera i dettagli e aggiunge una grana cinematografica fine. 10 crediti per video; il piano Studio include 2 miglioramenti gratuiti al mese.',
  'Can I use my own script?': 'Posso usare il mio copione?',
  'What if a generation fails?': 'E se una generazione fallisce?',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'I tuoi crediti tornano automaticamente nel momento in cui un render fallisce — niente ticket, niente attese. Paghi solo i video che ricevi davvero.',
  'Can I cancel anytime?': 'Posso annullare quando voglio?',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'Quando vuoi, con un clic. I piani sono mensili e i tuoi crediti si rinnovano ogni mese.',
  'Can I run a whole channel with the same host?': 'Posso gestire un intero canale con lo stesso presentatore?',
  'Can I monetize the videos?': 'Posso monetizzare i video?',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'Sì. Ogni video è tuo da tenere, pubblicare e monetizzare — incluso il Programma partner di YouTube, TikTok e Reels. Nessuna licenza aggiuntiva.',
  'Can I use the videos commercially, or for client work?': 'Posso usare i video a scopo commerciale o per lavori per clienti?',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'Sì. I nostri termini ti permettono di usare Kineo per scopi personali o commerciali leciti e confermano che mantieni la proprietà dei video che generi, quindi puoi pubblicarli, monetizzarli e consegnarli a un cliente come parte del tuo servizio a pagamento. Nessuna licenza aggiuntiva, nessuna royalty per video. Due limiti derivano dagli stessi termini: non puoi rivendere o ridistribuire Kineo in sé, e le clip stock dentro un render sono concesse in licenza per il tuo video finito, non per essere ricaricate come footage stock a sé stante. I piani a pagamento esportano l’MP4 pulito, senza filigrana.',
  'How long does one video take?': 'Quanto tempo richiede un video?',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'La modalità Fast di solito finisce in 3–7 minuti. I video generati dall’IA e cinematografici richiedono un po’ di più perché ogni scena viene generata prima della composizione dell’MP4 finale.',
  'How much does Kineo cost?': 'Quanto costa Kineo?',
  'Kineo has three monthly plans: Starter at $': 'Kineo ha tre piani mensili: Starter a $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'crediti. I crediti si spendono per video, e quanto costa un video dipende dal motore scelto: un render Fast e un film cinematografico attingono allo stesso saldo a ritmi molto diversi.',
  'Which AI video engines can I use in Kineo?': 'Quali motori video IA posso usare in Kineo?',
  ', behind one interface and one balance:': ', dietro un’unica interfaccia e un unico saldo:',
  'What is the best AI video generator for faceless YouTube channels?': 'Qual è il miglior generatore video IA per canali YouTube senza volto?',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'Sì. Gli utenti gratuiti che non hanno mai pagato possono scaricare, condividere e pubblicare l’MP4 con filigrana.',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'I film di prova hanno una piccola filigrana — puoi scaricare, condividere e pubblicare l’MP4. Dopo la prova, il video Fast gratuito ha la filigrana.',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'I download gratuiti hanno la filigrana; i piani a pagamento sbloccano l’MP4 pulito.',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'I download di prova hanno la filigrana, così come il video Fast gratuito dopo la prova, e i piani a pagamento esportano sempre puliti.',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'L’accesso gratuito dà ai nuovi utenti fino a 3 video Fast con filigrana ogni 24 ore, senza carta. Puoi scaricarli e condividerli.',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'Crea, scarica e condividi fino a 3 video Fast con filigrana ogni 24 h, senza carta.',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'Crea, guarda, scarica e condividi fino a 3 video Fast con filigrana ogni 24 h — senza carta.',
  'create, watch, download and share up to 3 Fast videos every 24h': 'crea, guarda, scarica e condividi fino a 3 video Fast ogni 24 h',
  '— no card, watermark included.': '— senza carta, filigrana inclusa.',
  'AI image generator — 6 engines': 'Generatore di immagini IA — 6 motori',
  'AI voice generator (text to speech)': 'Generatore vocale IA (da testo a voce)',
  'AI video upscaler & enhancer': 'Upscaler e miglioratore video IA',
  'Trending Shorts ideas today': 'Idee per Shorts di tendenza oggi',
  'AI Avatar video — your face, any script': 'Video avatar IA — il tuo volto, qualsiasi copione',
  'Kineo facts & numbers (citable)': 'Fatti e numeri di Kineo (citabili)',
  'Free AI Shorts generator': 'Generatore di Shorts IA gratuito',
  'YouTube Shorts from a topic': 'YouTube Shorts da un argomento',
  'ChatGPT script to YouTube Short': 'Da copione ChatGPT a Short YouTube',
  'Shorts without filming': 'Shorts senza girare',
  'Faceless niche picker': 'Selettore di nicchia senza volto',
  'State of AI Shorts 2026': 'Stato degli Shorts IA 2026',
  'AI Shorts for agencies & client work': 'Shorts IA per agenzie e lavori per clienti',
  'Trust Center — privacy, payments & ownership': 'Centro fiducia — privacy, pagamenti e proprietà',
  'Affiliate program - 30% recurring': 'Programma di affiliazione - 30% ricorrente',
  'Free AI Shorts by niche': 'Shorts IA gratuiti per nicchia',
  'Free script generator': 'Generatore di copioni gratuito',
  'Product video ad script': 'Copione per annuncio video di prodotto',
  'Client video brief generator': 'Generatore di brief video per clienti',
  'Free hook generator': 'Generatore di hook gratuito',
  'Shorts script timer': 'Timer per copioni di Shorts',
  'Shorts money calculator': 'Calcolatore di guadagni con gli Shorts',
  'How much do Shorts pay?': 'Quanto pagano gli Shorts?',
  'Best AI Shorts generators': 'Migliori generatori di Shorts IA',
  'TikTok vs Shorts: which pays more?': 'TikTok vs Shorts: quale paga di più?',
  'All comparisons': 'Tutti i confronti',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · Tutti i diritti riservati',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'Dipende se vuoi footage stock assemblato o footage generato. Strumenti come InVideo e AutoShorts tagliano clip stock sul tuo copione: è più economico e va bene per video a punti di discussione. Kineo genera il footage con modelli come Veo 3.1 e Kling 3, mantiene la tua narrazione parola per parola invece di riscriverla e punta a 60 secondi o più perché il video sia idoneo a TikTok Creator Rewards. Se il tuo canale vive di immagini che nessun altro ha, vince la generazione; se vive di volume, lo stock costa meno.',
  'Paste the complete script from ChatGPT here…': 'Incolla qui il copione completo da ChatGPT…',
  'Paste the idea from ChatGPT here…': 'Incolla qui l’idea da ChatGPT…',
  'What’s your video about? One idea in — a finished film out: voiced, scored and captioned.': 'Di cosa parla il tuo video? Entra un’idea — esce un film finito: con voce, colonna sonora e sottotitoli.',
  'Settings and generation': 'Impostazioni e generazione',
  'Search your videos…': 'Cerca nei tuoi video…',
  'Search your audio…': 'Cerca nel tuo audio…',
  'Search your images by engine': 'Cerca le tue immagini per motore',
  'No playable videos in your library yet. Check your latest project above.': 'Nessun video riproducibile nella tua libreria per ora. Controlla il tuo progetto più recente qui sopra.',
  'Make a finished Short →': 'Crea uno Short finito →',
  'Video Editing & Creator Tools': 'Montaggio video e strumenti per creator',
  'Trim, resize, change speed, mute or add text. Edit a file you already have, right in your browser. Your script and planning tools are still here below.': 'Taglia, ridimensiona, cambia velocità, silenzia o aggiungi testo. Modifica un file che hai già, direttamente nel browser. I tuoi strumenti di copione e pianificazione sono ancora qui sotto.',
  '5 local editing tools': '5 strumenti di montaggio locali',
  'No generation credits to edit': 'Nessun credito di generazione per modificare',
  'Edit video': 'Modifica video',
  'Files up to 100 MB and 3 minutes. Local, real-time export up to 1280 px on the long edge. MP4 or WebM depending on your browser; downloads are not saved to My Videos.': 'File fino a 100 MB e 3 minuti. Export locale in tempo reale fino a 1280 px sul lato lungo. MP4 o WebM a seconda del browser; i download non vengono salvati in I miei video.',
  'Video Trimmer': 'Taglia video',
  'Cut the beginning or end and keep only the clip you need.': 'Taglia l’inizio o la fine e tieni solo la clip che ti serve.',
  'Video Resizer': 'Ridimensiona video',
  'Go vertical, square or wide. Fit the frame or crop to fill.': 'Verticale, quadrato o largo. Adatta al fotogramma o ritaglia per riempire.',
  'Video Speed Changer': 'Cambia velocità video',
  'Slow it down or speed it up, from 0.5× to 2×.': 'Rallenta o accelera, da 0.5× a 2×.',
  'Remove Audio': 'Rimuovi audio',
  'Download a copy without the original audio.': 'Scarica una copia senza l’audio originale.',
  'Add Text to Video': 'Aggiungi testo al video',
  'Add a title or message that stays on screen. Not automatic subtitles.': 'Aggiungi un titolo o un messaggio che resta sullo schermo. Non sottotitoli automatici.',
  'No account · current Kineo plans': 'Nessun account · piani Kineo attuali',
  'No account · fair-use limit': 'Nessun account · limite di uso corretto',
  'No account · unlimited in browser': 'Nessun account · illimitato nel browser',
  'Edit an existing video here. Create a new one with Kineo.': 'Modifica qui un video esistente. Creane uno nuovo con Kineo.',
  'Create an AI video →': 'Crea un video IA →',
  'Edit your video, preview the changes, then export a copy.': 'Modifica il tuo video, guarda l’anteprima delle modifiche, poi esporta una copia.',
  'Video preview': 'Anteprima video',
  'Preview is silent. The download keeps audio unless Mute is selected.': 'L’anteprima è muta. Il download mantiene l’audio a meno che non sia selezionato Muto.',
  'Start with your video': 'Inizia dal tuo video',
  'Choose a local file. It stays on this device.': 'Scegli un file locale. Resta su questo dispositivo.',
  'Choose video file': 'Scegli file video',
  'Video file': 'File video',
  'Video settings': 'Impostazioni video',
  'Aspect ratio': 'Proporzioni',
  'Playback speed': 'Velocità di riproduzione',
  'On-screen text (100 characters, 3 lines)': 'Testo sullo schermo (100 caratteri, 3 righe)',
  'Add a title or message': 'Aggiungi un titolo o un messaggio',
  'Export edited video': 'Esporta il video modificato',
  'Export happens in real time. Keep this tab visible. Re-encoded at up to 1280 px on the long edge; format depends on your browser.': 'L’export avviene in tempo reale. Tieni visibile questa scheda. Ricodificato fino a 1280 px sul lato lungo; il formato dipende dal browser.',
  'Making a 4-second sample on your device…': 'Creazione di un campione di 4 secondi sul tuo dispositivo…',
  'Reading your file…': 'Lettura del tuo file…',
  'Export result': 'Risultato dell’export',
  'Your edited video': 'Il tuo video modificato',
  'Local download only. This copy is not saved to My Videos.': 'Solo download locale. Questa copia non viene salvata in I miei video.',
  'Exported video': 'Video esportato',
  'No upload. No generation credits. Your original is never overwritten.': 'Nessun upload. Nessun credito di generazione. L’originale non viene mai sovrascritto.',
  'Up to 100 MB · 3 minutes · MP4/WebM input recommended. These are basic editing tools, not the CapCut app.': 'Fino a 100 MB · 3 minuti · input MP4/WebM consigliato. Sono strumenti di montaggio di base, non l’app CapCut.',
  'Need a new video? Open Kineo Studio →': 'Ti serve un nuovo video? Apri Kineo Studio →',
  'This browser cannot export video here. Try the latest desktop Chrome or Edge.': 'Questo browser non può esportare video qui. Prova l’ultima versione di Chrome o Edge su desktop.',
  'Choose a non-empty video file of up to 100 MB.': 'Scegli un file video non vuoto fino a 100 MB.',
  'Use a playable clip of up to 3 minutes. Very large dimensions are not supported.': 'Usa una clip riproducibile fino a 3 minuti. Dimensioni molto grandi non sono supportate.',
  'Check the start and end: select at least 0.25 seconds within your clip.': 'Controlla inizio e fine: seleziona almeno 0.25 secondi dentro la tua clip.',
  'Choose a speed between 0.5× and 2×.': 'Scegli una velocità tra 0.5× e 2×.',
  'Use up to 100 characters and 3 lines of text.': 'Usa al massimo 100 caratteri e 3 righe di testo.',
  'Choose a supported aspect ratio, framing and text position.': 'Scegli proporzioni, inquadratura e posizione del testo supportate.',
  'This file could not be decoded. Try an MP4 (H.264) or WebM file.': 'Impossibile decodificare questo file. Prova un file MP4 (H.264) o WebM.',
  'Export stopped because this tab was hidden. Keep it open and visible, then export again. Your original is safe.': 'L’export si è fermato perché questa scheda era nascosta. Tienila aperta e visibile, poi esporta di nuovo. L’originale è al sicuro.',
  'Export stopped making progress. Try a shorter clip or desktop Chrome. Your original is unchanged.': 'L’export ha smesso di avanzare. Prova una clip più corta o Chrome su desktop. L’originale è invariato.',
  'Audio could not start. Try exporting again, or choose Mute video.': 'L’audio non è partito. Prova a esportare di nuovo o scegli Silenzia video.',
  'The browser blocked playback. Try exporting again from this tab.': 'Il browser ha bloccato la riproduzione. Prova a esportare di nuovo da questa scheda.',
  'Cancelled. Your original file is unchanged.': 'Annullato. Il tuo file originale è invariato.',
  'Could not finish this export. Try a shorter clip or another supported browser.': 'Impossibile completare questo export. Prova una clip più corta o un altro browser supportato.',
  'The browser produced an incomplete file, so we did not offer it for download. Try again with this tab visible, or use desktop Chrome.': 'Il browser ha prodotto un file incompleto, quindi non lo abbiamo offerto per il download. Riprova con questa scheda visibile o usa Chrome su desktop.',
  'Create new video': 'Crea nuovo video',
  'Your idea': 'La tua idea',
  'Natural': 'Naturale',
  'Working…': 'In lavorazione…',
  '🎲 Surprise me': '🎲 Sorprendimi',
  '📝 Use my script as is': '📝 Usa il mio copione così com’è',
  'Camera preset': 'Preset camera',
  'Your latest videos': 'I tuoi ultimi video',
  'Presenter': 'Presentatore',
  '1 · Who’s talking': '1 · Chi parla',
  '🎭 your characters': '🎭 i tuoi personaggi',
  '🎯 Max realism — animate my real photo': '🎯 Massimo realismo — anima la mia foto reale',
  '✓ Scene ready — preview on the right.': '✓ Scena pronta — anteprima a destra.',
  '2 · What they say': '2 · Cosa dicono',
  '3 · How it looks': '3 · Come appare',
  'Motion': 'Movimento',
  '⬇ Download MP4': '⬇ Scarica MP4',
  'One photo. Suddenly alive.': 'Una foto. All’improvviso viva.',
  'Cost per clip': 'Costo per clip',
  '↺ Animate another': '↺ Anima un’altra',
  'Grow': 'Cresci',
  'Sending to the motion engine…': 'Invio al motore di movimento…',
  '📊 Facts': '📊 Fatti',
  'Turn it into episode 2': 'Trasformalo nell’episodio 2',
  'Start here': 'Inizia qui',
  'Engine': 'Motore',
  'Highly aesthetic, by xAI': 'Altamente estetico, di xAI',
  'Google’s best image model': 'Il miglior modello di immagini di Google',
  'AI voiceover included': 'Voce narrante IA inclusa',
  '6 engines': '6 motori',
  'AI Presenter': 'Presentatore IA',
  'Lock a character →': 'Blocca un personaggio →',
  'Make a clip →': 'Crea una clip →',
  'Make an ad →': 'Crea un annuncio →',
  'Generate free →': 'Genera gratis →',
  'Creating…': 'Creazione in corso…',
  'Describe your image first': 'Descrivi prima la tua immagine',
  'Type your script first': 'Scrivi prima il tuo copione',
  'From the founder': 'Dal fondatore',
  'Faceless video generator': 'Generatore di video senza volto',
  'Text to video Shorts': 'Shorts da testo a video',
  'Cheapest AI Shorts maker': 'Il creatore di Shorts IA più economico',
  'Faceless channel ideas (2026)': 'Idee per canali senza volto (2026)',
  'Shorts idea widget': 'Widget di idee per Shorts',
  'Live case study: our channel on Autopilot': 'Caso studio dal vivo: il nostro canale in Autopilot',
  'Free YouTube Shorts scripts': 'Copioni gratuiti per YouTube Shorts',
  'Comment to Short script': 'Da commento a copione per Short',
  'Business video content planner': 'Pianificatore di contenuti video per aziende',
  'Real estate video maker': 'Creatore di video immobiliari',
  'Shorts title & hashtag generator': 'Generatore di titoli e hashtag per Shorts',
  'Free viral score': 'Punteggio virale gratuito',
  'Make money clipping with AI': 'Guadagna facendo clip con l’IA',
  'Shorts RPM by niche (2026)': 'RPM degli Shorts per nicchia (2026)',
  'Can you monetize AI videos?': 'Si possono monetizzare i video IA?',
}
