// KINEO-INTERFACE-16-LINGUAS-2026-09-21 — interface em nl. Só copy autoral da interface: nunca prompt,
// título, resultado, nome de motor ou erro de API. Frase fora daqui cai em inglês (components/InterfaceLanguage.tsx).
// Gerado de scratchpad/tr-nl.js sobre o corpus vivo de frases (415); números e "Kineo" preservados por construção.
export const DICT: Record<string, string> = {
  'Videos for businesses': 'Video’s voor bedrijven',
  'Generation failed': 'Genereren mislukt',
  'You can retry safely.': 'Je kunt het veilig opnieuw proberen.',
  'This engine is not available on your account right now': 'Deze engine is op dit moment niet beschikbaar op je account',
  'Retrying the same engine will stop at this same place. Pick another engine to keep going.': 'Opnieuw proberen met dezelfde engine stopt op precies dezelfde plek. Kies een andere engine om verder te gaan.',
  'The engine is cooling down after two refunded attempts': 'De engine koelt af na twee terugbetaalde pogingen',
  'Starting another one right now stops at this same place. Give it a few minutes.': 'Nu nog een starten stopt op dezelfde plek. Geef het een paar minuten.',
  'Starting another one right now stops at this same place. The button below unlocks by itself.': 'Nu nog een starten stopt op dezelfde plek. De knop hieronder ontgrendelt vanzelf.',
  'We stopped waiting on this render instead of leaving you hanging': 'We zijn gestopt met wachten op deze render in plaats van je te laten hangen',
  'This one ran far longer than any video that finishes here. Starting again is worth it.': 'Deze duurde veel langer dan elke video die hier klaarkomt. Opnieuw starten is de moeite waard.',
  'The video engine is busy — this is on our side, not your idea': 'De video-engine is druk — dit ligt aan ons, niet aan je idee',
  'Nothing about your text is wrong. Trying again in a few minutes usually goes straight through.': 'Er is niets mis met je tekst. Over een paar minuten opnieuw proberen gaat meestal in één keer goed.',
  'Create Video': 'Video maken',
  'Create a new video': 'Een nieuwe video maken',
  'AI Avatar Studio': 'AI-avatarstudio',
  'Viral Templates': 'Virale sjablonen',
  'Channel Builder': 'Kanaalbouwer',
  'Invite & Earn': 'Uitnodigen & verdienen',
  'Start free': 'Gratis starten',
  'Try 7 days for $1': 'Probeer 7 dagen voor $1',
  'Pick a lane': 'Kies een route',
  'All free tools': 'Alle gratis tools',
  'Terms of Service': 'Servicevoorwaarden',
  'Trust Center': 'Trust Center',
  'Review & publish': 'Controleren & publiceren',
  'Your image': 'Jouw afbeelding',
  'Cost per image': 'Kosten per afbeelding',
  'No videos yet': 'Nog geen video’s',
  'No audio yet': 'Nog geen audio',
  '🎬 Studio — generate video': '🎬 Studio — video genereren',
  '🎨 Images — create image': '🎨 Afbeeldingen — afbeelding maken',
  '🎙 Audio — text to speech': '🎙 Audio — tekst naar spraak',
  'Type it. See it. Six image engines, one screen.': 'Typ het. Zie het. Zes beeld-engines, één scherm.',
  'Type it. Hear it. Four voice engines, one screen.': 'Typ het. Hoor het. Vier stem-engines, één scherm.',
  'Everything you’ve created, in one place.': 'Alles wat je hebt gemaakt, op één plek.',
  'Add credits →': 'Credits toevoegen →',
  'Upscale any result to 2x for 1 credit.': 'Vergroot elk resultaat naar 2x voor 1 credit.',
  'We couldn’t load your images right now.': 'We konden je afbeeldingen nu niet laden.',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'Je afbeeldingen en credits zijn veilig — dit is slechts een tijdelijke leesstoring.',
  'We couldn’t load your audio right now.': 'We konden je audio nu niet laden.',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'Je audio en credits zijn veilig — dit is slechts een tijdelijke leesstoring.',
  'We couldn’t load part of your library right now.': 'We konden een deel van je bibliotheek nu niet laden.',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'Je video’s en credits zijn veilig — dit is slechts een tijdelijke leesstoring.',
  '↻ Try again': '↻ Opnieuw proberen',
  '⬇ Download': '⬇ Downloaden',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': 'Bevalt een stem je? De Studio bouwt de hele film eromheen — beelden, ondertitels en muziek.',
  'Open Studio →': 'Studio openen →',
  'open the Studio': 'open de Studio',
  'Next episode →': 'Volgende aflevering →',
  'create your first image': 'maak je eerste afbeelding',
  'generate your first voiceover': 'genereer je eerste voice-over',
  'Instant drafts': 'Directe concepten',
  'Deep prompt understanding': 'Diep promptbegrip',
  'Perfect text rendering': 'Perfecte tekstweergave',
  'Create Image': 'Afbeelding maken',
  'Click-magnet YouTube covers': 'YouTube-covers die klikken trekken',
  'Bring any image to life': 'Breng elke afbeelding tot leven',
  'Instant narration': 'Directe vertelstem',
  'Four voice engines': 'Vier stem-engines',
  'A face that speaks your script': 'Een gezicht dat jouw script spreekt',
  'Every control, one screen': 'Elke instelling, één scherm',
  'Today’s trending topics': 'Trending onderwerpen van vandaag',
  'Real renders, every engine': 'Echte renders, elke engine',
  'Type an idea — watch it become a film.': 'Typ een idee — zie het een film worden.',
  'Start with the full toolkit': 'Begin met de complete toolkit',
  'Kineo’s own engine — 3–7 min': 'Kineo’s eigen engine — 3–7 min',
  'The workhorse AI video engine': 'Het AI-video-werkpaard',
  'Cinematic motion & camera': 'Filmische beweging & camera',
  'Film scenes, native voice & lip sync': 'Filmscènes, eigen stem & lipsync',
  'Talking video from one photo': 'Pratende video van één foto',
  'From idea to posted Short in 3 steps.': 'Van idee naar geplaatste Short in 3 stappen.',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'Geen filmen, geen monteren, geen tijdlijn. Eén keer typen — Kineo doet de rest.',
  'Step 1': 'Stap 1',
  'Kineo builds it': 'Kineo bouwt het',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'AI schrijft een op retentie gebouwd script, neemt de voice-over op, koppelt de beelden en brandt ondertitels in — een afgewerkte 9:16-video.',
  'Download & post': 'Download & plaats',
  'Why Kineo': 'Waarom Kineo',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'De meeste tools knippen een lange video die je al hebt gefilmd. Kineo bouwt hem vanaf nul.',
  'See how to make Shorts without filming →': 'Zie hoe je Shorts maakt zonder te filmen →',
  'Generates the Short from just an idea': 'Genereert de Short uit alleen een idee',
  'Writes the script for you': 'Schrijft het script voor je',
  'Finds and matches footage': 'Vindt en koppelt beelden',
  'your upload': 'jouw upload',
  'AI image studio included': 'AI-beeldstudio inbegrepen',
  'Voice studio (text-to-speech)': 'Stemstudio (tekst naar spraak)',
  'One-click HD film enhance': 'HD-filmverbetering met één klik',
  'One idea — or a whole toolkit.': 'Eén idee — of een hele toolkit.',
  'Try AI Presenter →': 'Probeer de AI-presentator →',
  'Transparent Clips': 'Transparante clips',
  'UGC Product Ads': 'UGC-productadvertenties',
  'Animate a photo →': 'Een foto animeren →',
  'Make a thumbnail →': 'Een thumbnail maken →',
  'Free AI Shorts': 'Gratis AI-Shorts',
  'Start with a niche that already works.': 'Begin met een niche die al werkt.',
  'Not sure? Take the quiz →': 'Twijfel je? Doe de quiz →',
  'Pick your engine. Ship a Short today.': 'Kies je engine. Plaats vandaag een Short.',
  'Cancel anytime': 'Altijd opzegbaar',
  'Generate image →': 'Afbeelding genereren →',
  'Generate audio →': 'Audio genereren →',
  'Paid plans unlock clean MP4s.': 'Betaalde plannen ontgrendelen schone MP4’s.',
  'Best for starting out': 'Ideaal om te beginnen',
  'Best value per film': 'Beste waarde per film',
  'on Nano Banana': 'op Nano Banana',
  'Every video engine incl. MiniMax H3': 'Elke video-engine incl. MiniMax H3',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'MP4 zonder watermerk · 100 projecten · 90 dagen opslag',
  ', finished': ', afgewerkt',
  '— every engine unlocked': '— elke engine ontgrendeld',
  '· voice + karaoke captions + score': '· stem + karaoke-ondertitels + muziek',
  '500 projects · forever storage': '500 projecten · opslag voor altijd',
  'Cancel anytime — 7-day money-back': 'Altijd opzegbaar — 7 dagen geld terug',
  'films on Omni Flash': 'films op Omni Flash',
  '· 2 free HD enhances / month': '· 2 gratis HD-verbeteringen / maand',
  'Unlimited projects · forever storage': 'Onbeperkte projecten · opslag voor altijd',
  'Everything in Creator': 'Alles uit Creator',
  'Calculate your cost per Short →': 'Bereken je kosten per Short →',
  'How much do Shorts pay? →': 'Hoeveel betalen Shorts? →',
  'Highest-RPM niches →': 'Niches met de hoogste RPM →',
  'read the full review →': 'lees de volledige review →',
  'a single line is enough — or paste a full script': 'één regel is genoeg — of plak een volledig script',
  '1080×1920 · Full HD master': '1080×1920 · Full HD-master',
  'Every film is delivered as a 1080×1920 Full HD master (engines render natively at 720–768p and are mastered up). For maximum sharpness, run ✨HD Enhance on the finished film.': 'Elke film wordt geleverd als 1080×1920 Full HD-master (engines renderen native op 720–768p en worden opgemasterd). Voor maximale scherpte draai je ✨HD Enhance op de afgewerkte film.',
  'Your idea first. Review the settings, then generate.': 'Eerst je idee. Controleer de instellingen en genereer dan.',
  '📷 Photo': '📷 Foto',
  '🖼️ Upload a different photo': '🖼️ Een andere foto uploaden',
  '🎙️ Generating…': '🎙️ Genereren…',
  '🎙️ Cloning the voice…': '🎙️ Stem klonen…',
  '🎙️ Upload a different sample': '🎙️ Een ander sample uploaden',
  '⏹ Stop & clone': '⏹ Stoppen & klonen',
  '🎭 Generate my avatar video': '🎭 Mijn avatarvideo genereren',
  'Continue exactly where ChatGPT stopped.': 'Ga precies verder waar ChatGPT stopte.',
  '✨ Let AI structure it': '✨ Laat AI het structureren',
  'Optional settings': 'Optionele instellingen',
  'optional — a pre-tested move added to your prompt': 'optioneel — een vooraf geteste beweging toegevoegd aan je prompt',
  'Reference image': 'Referentieafbeelding',
  '🖼️ Start your video from an image — coming soon': '🖼️ Start je video vanuit een afbeelding — binnenkort',
  'Estimated cost': 'Geschatte kosten',
  'Your credits buy': 'Je credits zijn goed voor',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'Stem, karaoke-ondertitels en muziek inbegrepen. Mislukt een render, dan komen je credits meteen terug.',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'Zelfde onderwerp, nieuwe hook en payoff — het idee is al geschreven.',
  'Build next episode →': 'Volgende aflevering bouwen →',
  'Episode 2 →': 'Aflevering 2 →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'Pratende AI-presentator van één foto — lipsync, een eigen studio',
  'Your face. Your script.': 'Jouw gezicht. Jouw script.',
  'Everything you need to make yourself speak — nothing you don’t.': 'Alles wat je nodig hebt om jezelf te laten spreken — niets wat je niet nodig hebt.',
  'BEST MOTION': 'BESTE BEWEGING',
  '1.5 · Realism': '1.5 · Realisme',
  '🎬 Put me in a scene': '🎬 Zet me in een scène',
  'use original photo': 'originele foto gebruiken',
  '✍️ Say exactly this — word for word': '✍️ Zeg precies dit — woord voor woord',
  '✨ Expand into a full Short script (45–60s)': '✨ Uitbreiden tot een volledig Short-script (45–60 s)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 Productadvertentiemodus — verkoop een product in UGC-stijl',
  'Free — fills the script box above, then generate with your presenter.': 'Gratis — vult het scriptvak hierboven, genereer daarna met je presentator.',
  '2.5 · Speak in your own voice': '2.5 · Spreek met je eigen stem',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ Stem gekloond — de vertelstem gebruikt deze stem.',
  'use a default voice': 'een standaardstem gebruiken',
  '🎬 Full video — face the whole time': '🎬 Volledige video — de hele tijd in beeld',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 AI-presentator — snel & natuurlijk · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro — premium fotokwaliteit · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 Body Motion — bovenlichaam, handen & gebaren · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ Klassiek — talking head · 110 cr',
  'you have': 'je hebt',
  'to create your avatar video.': 'om je avatarvideo te maken.',
  '5 · Gesture clips — transparent background': '5 · Gebarenclips — transparante achtergrond',
  'auto-refunded if it fails': 'automatisch terugbetaald bij mislukking',
  '⬇️ Download transparent WebM': '⬇️ Transparante WebM downloaden',
  '⬇️ Original MP4 (with background)': '⬇️ Originele MP4 (met achtergrond)',
  'Pick a face to preview': 'Kies een gezicht om te bekijken',
  '↺ Make another': '↺ Nog een maken',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'Mensen, huisdieren, producten, oude familiefoto’s — upload een foto of plak een openbare afbeeldingslink en zie hem bewegen.',
  'The photo': 'De foto',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': 'JPG/PNG tot 8 MB. Openbare links worden veilig op onze server gedownload en gecontroleerd.',
  'sign in': 'inloggen',
  'Kineo will fetch and validate it on the server when you animate.': 'Kineo haalt en controleert hem op de server wanneer je animeert.',
  'Upload a photo to preview': 'Upload een foto om te bekijken',
  '🖼️ Upload a photo': '🖼️ Een foto uploaden',
  '✨ Bring it to life': '✨ Tot leven brengen',
  'Uploading your photo…': 'Je foto wordt geüpload…',
  'Bringing your photo to life… (1–3 min)': 'Je foto wordt tot leven gebracht… (1–3 min)',
  'Alive!': 'Levend!',
  '🌬️ Subtle & real': '🌬️ Subtiel & echt',
  '😊 Person comes alive': '😊 De persoon komt tot leven',
  'Type your idea first': 'Typ eerst je idee',
  '📖 True Story': '📖 Waargebeurd',
  'Paste your ChatGPT script': 'Plak je ChatGPT-script',
  'First Short complete': 'Eerste Short klaar',
  'Keep your show moving': 'Houd je show in beweging',
  'Cheapest way to see your idea as a film': 'De goedkoopste manier om je idee als film te zien',
  'Slow Dolly-In': 'Langzame dolly-in',
  'FPV Drone': 'FPV-drone',
  'Macro Detail': 'Macrodetail',
  'Sharing & creator options': 'Delen & creatoropties',
  'We couldn’t load your videos right now': 'We konden je video’s nu niet laden',
  'Your videos and credits are safe — this is a temporary read hiccup, not a lost library.': 'Je video’s en credits zijn veilig — dit is een tijdelijke leesstoring, geen verloren bibliotheek.',
  '⚡ Generate Video': '⚡ Video genereren',
  'Prefer clean exports now? Starter includes': 'Liever nu al schone exports? Starter bevat',
  'credits each month for': 'credits per maand voor',
  'Your existing files stay available. Starter applies to new exports after checkout.': 'Je bestaande bestanden blijven beschikbaar. Starter geldt voor nieuwe exports na de checkout.',
  'Build Next Episode First': 'Eerst de volgende aflevering bouwen',
  'Video unavailable': 'Video niet beschikbaar',
  'Free MP4 includes the Kineo watermark': 'De gratis MP4 bevat het Kineo-watermerk',
  'Free distribution · latest Short': 'Gratis verspreiding · nieuwste Short',
  'Send it to one person for feedback': 'Stuur hem naar één persoon voor feedback',
  'Copy a public watch page for your finished video. Your friend can watch it without logging in, then use “Make one like this” if the idea inspires them.': 'Kopieer een openbare kijkpagina van je afgewerkte video. Je vriend kan hem bekijken zonder in te loggen en daarna “Maak er zo een” gebruiken als het idee inspireert.',
  'Public watch links are temporarily paused': 'Openbare kijklinks zijn tijdelijk gepauzeerd',
  'Your video stays in your account. Download the MP4 if you want to send it directly; Kineo will not publish a public page without an explicit visibility choice.': 'Je video blijft in je account. Download de MP4 als je hem direct wilt sturen; Kineo publiceert geen openbare pagina zonder een expliciete zichtbaarheidskeuze.',
  'Loading…': 'Laden…',
  'For new videos ·': 'Voor nieuwe video’s ·',
  'Published it?': 'Geplaatst?',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'Scherp, recht van voren, één persoon. Voor lichaamsbeweging gebruik je een foto vanaf het middel of ten voeten uit met beide handen zichtbaar. Zwarte balken worden automatisch verwijderd.',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'Beste professionele resultaat: upload een verticale clip van 5–20 s met de echte gebaren die je wilt, ongeveer zo lang als het script. Sync-3 vervangt de spraak en behoudt het echte gezicht en de lichaamsbeweging. MP4/MOV tot 40 MB.',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'Ik bevestig dat ik het recht heb om het beeld van deze persoon te gebruiken en stem ermee in dat het door AI wordt geanimeerd.',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': 'Upload een helder stemsample van ~30-60 s (één spreker, weinig achtergrondgeluid) en de vertelstem spreekt met die stem. Gebruik alleen een stem die je mag gebruiken.',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'Woord-voor-woord-video’s tonen je gezicht de hele tijd (ze zijn kort — geen b-roll nodig).',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'Video’s met maximaal realisme en gebouwde scène houden de presentator de hele vertelling in beeld.',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ Hook-intro — jij opent, b-roll vertelt het verhaal',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'Korte clips van je presentator die zwaait, wijst, presenteert — geleverd als WebM met een ECHTE transparante achtergrond. Zet ze direct in Storyline, Premiere, CapCut of elke slide. Geen green screen, geen keying.',
  'Cinematic film — 9-image consistency': 'Filmische film — consistentie over 9 beelden',
  '#1-ranked video model — Aug 2026 arena': 'Nr. 1 videomodel — arena aug 2026',
  'Cinematic motion and camera work': 'Filmische beweging en camerawerk',
  'Shorts money & growth': 'Geld & groei met Shorts',
  'Compare Kineo with 27 AI video tools →': 'Vergelijk Kineo met 27 AI-videotools →',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'Pratende presentatoren, herbruikbare personages, transparante clips, productadvertenties — plus alles om een trend te vinden en te benutten.',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'Eén foto + jouw script — een pratende video met lipsync van studiokwaliteit, HeyGen-stijl.',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'Sla een personage één keer op — precies hetzelfde gezicht in elke video en thumbnail die je maakt.',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'Presentatorgebaren — zwaaien, wijzen, presenteren — als WebM met een echte transparante achtergrond.',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'Plak elk product — krijg een advertentie van 15-30 s in creatorstijl, geschreven en ingesproken voor jou.',
  'Bring any still photo to life as a moving, postable video.': 'Breng elke stilstaande foto tot leven als bewegende, plaatsbare video.',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'Klikwaardige thumbnails in de stijl van de grootste kanalen — vanuit een prompt.',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'Elke niche hieronder heeft een eigen generatorpagina, afgestemde prompts en echte voorbeelden.',
  'Is the video really mine to post?': 'Is de video echt van mij om te plaatsen?',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'Betaalde plannen ontgrendelen de schone MP4 zonder watermerk voor YouTube, TikTok of Reels.',
  'Do I need any editing skills?': 'Heb ik montagevaardigheden nodig?',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'Nee. Je typt één idee en de AI schrijft het script, neemt de stem op, vindt de beelden en voegt ondertitels toe.',
  'Is there a watermark?': 'Zit er een watermerk op?',
  'Paid plans export clean, watermark-free MP4s.': 'Betaalde plannen exporteren schone MP4’s zonder watermerk.',
  'Can Kineo also generate images and voiceovers?': 'Kan Kineo ook afbeeldingen en voice-overs genereren?',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'Ja — Kineo bevat een AI-beeldstudio (6 engines waaronder FLUX, Seedream en Nano Banana Pro, vanaf 1 credit per afbeelding) en een stemstudio met 4 tekst-naar-spraak-engines (vanaf 1 credit per 1000 tekens). Alles wat je maakt staat in je Bibliotheek.',
  'Can I make my videos sharper?': 'Kan ik mijn video’s scherper maken?',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'Elke video heeft een verbeteroptie met één klik, aangedreven door Topaz-filmrestauratie — verwijdert compressieartefacten, herstelt details en voegt fijne filmkorrel toe. 10 credits per video; het Studio-plan bevat 2 gratis verbeteringen per maand.',
  'Can I use my own script?': 'Kan ik mijn eigen script gebruiken?',
  'What if a generation fails?': 'Wat als een generatie mislukt?',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'Je credits komen automatisch terug zodra een render mislukt — geen supportticket, geen wachten. Je betaalt alleen voor video’s die je echt krijgt.',
  'Can I cancel anytime?': 'Kan ik altijd opzeggen?',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'Altijd, met één klik. Plannen lopen per maand en je credits worden elke maand ververst.',
  'Can I run a whole channel with the same host?': 'Kan ik een heel kanaal draaien met dezelfde host?',
  'Can I monetize the videos?': 'Kan ik de video’s monetiseren?',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'Ja. Elke video is van jou om te houden, te plaatsen en te monetiseren — inclusief het YouTube-partnerprogramma, TikTok en Reels. Geen extra licentie nodig.',
  'Can I use the videos commercially, or for client work?': 'Kan ik de video’s commercieel gebruiken, of voor klanten?',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'Ja. Onze voorwaarden staan toe dat je Kineo gebruikt voor legale persoonlijke of commerciële doeleinden en bevestigen dat je eigenaar blijft van de video’s die je genereert, dus je kunt ze plaatsen, monetiseren en aan een klant leveren als onderdeel van je eigen betaalde dienst. Geen extra licentie, geen royalty per video. Twee grenzen komen uit dezelfde voorwaarden: je mag Kineo zelf niet doorverkopen of herdistribueren, en de stockclips in een render zijn gelicentieerd voor je afgewerkte video, niet om opnieuw te uploaden als losse stockbeelden. Betaalde plannen exporteren de schone MP4 zonder watermerk.',
  'How long does one video take?': 'Hoe lang duurt één video?',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'Fast-modus is meestal klaar in 3–7 minuten. AI-gegenereerde en filmische video’s duren iets langer omdat elke scène wordt gegenereerd voordat de uiteindelijke MP4 wordt samengesteld.',
  'How much does Kineo cost?': 'Wat kost Kineo?',
  'Kineo has three monthly plans: Starter at $': 'Kineo heeft drie maandplannen: Starter vanaf $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'credits. Credits worden per video besteed, en hoeveel een video kost hangt af van de engine die je kiest, dus een Fast-render en een filmische film komen uit hetzelfde saldo tegen heel verschillende tarieven.',
  'Which AI video engines can I use in Kineo?': 'Welke AI-video-engines kan ik in Kineo gebruiken?',
  ', behind one interface and one balance:': ', achter één interface en één saldo:',
  'What is the best AI video generator for faceless YouTube channels?': 'Wat is de beste AI-videogenerator voor faceless YouTube-kanalen?',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'Ja. Gratis gebruikers die nooit hebben betaald kunnen de MP4 met watermerk downloaden, delen en plaatsen.',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'Proeffilms dragen een klein watermerk — je kunt de MP4 downloaden, delen en plaatsen. Na de proefperiode draagt de gratis Fast-video een watermerk.',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'Gratis downloads dragen een watermerk; betaalde plannen ontgrendelen de schone MP4.',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'Proefdownloads dragen een watermerk, net als de gratis Fast-video na de proefperiode, en betaalde plannen exporteren altijd schoon.',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'Gratis toegang geeft nieuwe gebruikers tot 3 Fast-video’s met watermerk per 24 uur, zonder kaart. Je kunt ze downloaden en delen.',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'Maak, download en deel tot 3 Fast-video’s met watermerk per 24 u, zonder kaart.',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'Maak, bekijk, download en deel tot 3 Fast-video’s met watermerk per 24 u — zonder kaart.',
  'create, watch, download and share up to 3 Fast videos every 24h': 'maak, bekijk, download en deel tot 3 Fast-video’s per 24 u',
  '— no card, watermark included.': '— zonder kaart, watermerk inbegrepen.',
  'AI image generator — 6 engines': 'AI-afbeeldingsgenerator — 6 engines',
  'AI voice generator (text to speech)': 'AI-stemgenerator (tekst naar spraak)',
  'AI video upscaler & enhancer': 'AI-video-upscaler & -verbeteraar',
  'Trending Shorts ideas today': 'Trending Shorts-ideeën vandaag',
  'AI Avatar video — your face, any script': 'AI-avatarvideo — jouw gezicht, elk script',
  'Kineo facts & numbers (citable)': 'Kineo-feiten & cijfers (citeerbaar)',
  'Free AI Shorts generator': 'Gratis AI-Shorts-generator',
  'YouTube Shorts from a topic': 'YouTube Shorts van een onderwerp',
  'ChatGPT script to YouTube Short': 'ChatGPT-script naar YouTube Short',
  'Shorts without filming': 'Shorts zonder filmen',
  'Faceless niche picker': 'Faceless-nichekiezer',
  'State of AI Shorts 2026': 'State of AI Shorts 2026',
  'AI Shorts for agencies & client work': 'AI-Shorts voor bureaus & klantwerk',
  'Trust Center — privacy, payments & ownership': 'Trust Center — privacy, betalingen & eigendom',
  'Affiliate program - 30% recurring': 'Affiliateprogramma - 30% terugkerend',
  'Free AI Shorts by niche': 'Gratis AI-Shorts per niche',
  'Free script generator': 'Gratis scriptgenerator',
  'Product video ad script': 'Productvideo-advertentiescript',
  'Client video brief generator': 'Klantvideobriefing-generator',
  'Free hook generator': 'Gratis hookgenerator',
  'Shorts script timer': 'Shorts-scripttimer',
  'Shorts money calculator': 'Shorts-verdiencalculator',
  'How much do Shorts pay?': 'Hoeveel betalen Shorts?',
  'Best AI Shorts generators': 'Beste AI-Shorts-generators',
  'TikTok vs Shorts: which pays more?': 'TikTok vs Shorts: wat betaalt meer?',
  'All comparisons': 'Alle vergelijkingen',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · Alle rechten voorbehouden',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'Het hangt ervan af of je gemonteerde stockbeelden of gegenereerde beelden wilt. Tools als InVideo en AutoShorts knippen stockclips op je script, wat goedkoper is en prima voor praatvideo’s. Kineo genereert de beelden met modellen als Veo 3.1 en Kling 3, houdt je vertelling woord voor woord in plaats van te herschrijven, en mikt op 60 seconden of meer zodat de video in aanmerking komt voor TikTok Creator Rewards. Leeft je kanaal van beelden die niemand anders heeft, dan wint genereren; leeft het van volume, dan is stock goedkoper.',
  'Paste the complete script from ChatGPT here…': 'Plak hier het volledige script uit ChatGPT…',
  'Paste the idea from ChatGPT here…': 'Plak hier het idee uit ChatGPT…',
  'What’s your video about? One idea in — a finished film out: voiced, scored and captioned.': 'Waar gaat je video over? Eén idee erin — een afgewerkte film eruit: ingesproken, met muziek en ondertitels.',
  'Settings and generation': 'Instellingen en generatie',
  'Search your videos…': 'Zoek in je video’s…',
  'Search your audio…': 'Zoek in je audio…',
  'Search your images by engine': 'Zoek je afbeeldingen per engine',
  'No playable videos in your library yet. Check your latest project above.': 'Nog geen afspeelbare video’s in je bibliotheek. Bekijk je nieuwste project hierboven.',
  'Make a finished Short →': 'Maak een afgewerkte Short →',
  'Video Editing & Creator Tools': 'Videobewerking & creatortools',
  'Trim, resize, change speed, mute or add text. Edit a file you already have, right in your browser. Your script and planning tools are still here below.': 'Knippen, formaat wijzigen, snelheid aanpassen, dempen of tekst toevoegen. Bewerk een bestand dat je al hebt, direct in je browser. Je script- en planningstools staan nog steeds hieronder.',
  '5 local editing tools': '5 lokale bewerkingstools',
  'No generation credits to edit': 'Geen generatiecredits om te bewerken',
  'Edit video': 'Video bewerken',
  'Files up to 100 MB and 3 minutes. Local, real-time export up to 1280 px on the long edge. MP4 or WebM depending on your browser; downloads are not saved to My Videos.': 'Bestanden tot 100 MB en 3 minuten. Lokale realtime-export tot 1280 px aan de lange zijde. MP4 of WebM afhankelijk van je browser; downloads worden niet opgeslagen in Mijn video’s.',
  'Video Trimmer': 'Video-trimmer',
  'Cut the beginning or end and keep only the clip you need.': 'Knip het begin of einde af en houd alleen de clip die je nodig hebt.',
  'Video Resizer': 'Video-resizer',
  'Go vertical, square or wide. Fit the frame or crop to fill.': 'Verticaal, vierkant of breed. Passend in het kader of bijsnijden om te vullen.',
  'Video Speed Changer': 'Videosnelheid aanpassen',
  'Slow it down or speed it up, from 0.5× to 2×.': 'Vertraag of versnel, van 0.5× tot 2×.',
  'Remove Audio': 'Audio verwijderen',
  'Download a copy without the original audio.': 'Download een kopie zonder het originele geluid.',
  'Add Text to Video': 'Tekst aan video toevoegen',
  'Add a title or message that stays on screen. Not automatic subtitles.': 'Voeg een titel of boodschap toe die in beeld blijft. Geen automatische ondertitels.',
  'No account · current Kineo plans': 'Geen account · huidige Kineo-plannen',
  'No account · fair-use limit': 'Geen account · fair-use-limiet',
  'No account · unlimited in browser': 'Geen account · onbeperkt in de browser',
  'Edit an existing video here. Create a new one with Kineo.': 'Bewerk hier een bestaande video. Maak een nieuwe met Kineo.',
  'Create an AI video →': 'Een AI-video maken →',
  'Edit your video, preview the changes, then export a copy.': 'Bewerk je video, bekijk de wijzigingen en exporteer dan een kopie.',
  'Video preview': 'Videovoorbeeld',
  'Preview is silent. The download keeps audio unless Mute is selected.': 'Het voorbeeld is stil. De download behoudt het geluid tenzij Dempen is geselecteerd.',
  'Start with your video': 'Begin met je video',
  'Choose a local file. It stays on this device.': 'Kies een lokaal bestand. Het blijft op dit apparaat.',
  'Choose video file': 'Videobestand kiezen',
  'Video file': 'Videobestand',
  'Video settings': 'Video-instellingen',
  'Aspect ratio': 'Beeldverhouding',
  'Playback speed': 'Afspeelsnelheid',
  'On-screen text (100 characters, 3 lines)': 'Tekst in beeld (100 tekens, 3 regels)',
  'Add a title or message': 'Voeg een titel of boodschap toe',
  'Export edited video': 'Bewerkte video exporteren',
  'Export happens in real time. Keep this tab visible. Re-encoded at up to 1280 px on the long edge; format depends on your browser.': 'Exporteren gebeurt in realtime. Houd dit tabblad zichtbaar. Opnieuw gecodeerd tot 1280 px aan de lange zijde; het formaat hangt af van je browser.',
  'Making a 4-second sample on your device…': 'Een sample van 4 seconden maken op je apparaat…',
  'Reading your file…': 'Je bestand wordt gelezen…',
  'Export result': 'Exportresultaat',
  'Your edited video': 'Je bewerkte video',
  'Local download only. This copy is not saved to My Videos.': 'Alleen lokale download. Deze kopie wordt niet opgeslagen in Mijn video’s.',
  'Exported video': 'Geëxporteerde video',
  'No upload. No generation credits. Your original is never overwritten.': 'Geen upload. Geen generatiecredits. Je origineel wordt nooit overschreven.',
  'Up to 100 MB · 3 minutes · MP4/WebM input recommended. These are basic editing tools, not the CapCut app.': 'Tot 100 MB · 3 minuten · MP4/WebM-invoer aanbevolen. Dit zijn basisbewerkingstools, niet de CapCut-app.',
  'Need a new video? Open Kineo Studio →': 'Nieuwe video nodig? Open Kineo Studio →',
  'This browser cannot export video here. Try the latest desktop Chrome or Edge.': 'Deze browser kan hier geen video exporteren. Probeer de nieuwste desktop-Chrome of -Edge.',
  'Choose a non-empty video file of up to 100 MB.': 'Kies een niet-leeg videobestand van maximaal 100 MB.',
  'Use a playable clip of up to 3 minutes. Very large dimensions are not supported.': 'Gebruik een afspeelbare clip van maximaal 3 minuten. Zeer grote afmetingen worden niet ondersteund.',
  'Check the start and end: select at least 0.25 seconds within your clip.': 'Controleer begin en einde: selecteer minstens 0.25 seconde binnen je clip.',
  'Choose a speed between 0.5× and 2×.': 'Kies een snelheid tussen 0.5× en 2×.',
  'Use up to 100 characters and 3 lines of text.': 'Gebruik maximaal 100 tekens en 3 regels tekst.',
  'Choose a supported aspect ratio, framing and text position.': 'Kies een ondersteunde beeldverhouding, kadrering en tekstpositie.',
  'This file could not be decoded. Try an MP4 (H.264) or WebM file.': 'Dit bestand kon niet worden gedecodeerd. Probeer een MP4- (H.264) of WebM-bestand.',
  'Export stopped because this tab was hidden. Keep it open and visible, then export again. Your original is safe.': 'Exporteren is gestopt omdat dit tabblad verborgen was. Houd het open en zichtbaar en exporteer opnieuw. Je origineel is veilig.',
  'Export stopped making progress. Try a shorter clip or desktop Chrome. Your original is unchanged.': 'Exporteren maakt geen voortgang meer. Probeer een kortere clip of desktop-Chrome. Je origineel is ongewijzigd.',
  'Audio could not start. Try exporting again, or choose Mute video.': 'Audio kon niet starten. Probeer opnieuw te exporteren of kies Video dempen.',
  'The browser blocked playback. Try exporting again from this tab.': 'De browser blokkeerde het afspelen. Probeer opnieuw te exporteren vanuit dit tabblad.',
  'Cancelled. Your original file is unchanged.': 'Geannuleerd. Je originele bestand is ongewijzigd.',
  'Could not finish this export. Try a shorter clip or another supported browser.': 'Deze export kon niet worden afgerond. Probeer een kortere clip of een andere ondersteunde browser.',
  'The browser produced an incomplete file, so we did not offer it for download. Try again with this tab visible, or use desktop Chrome.': 'De browser produceerde een onvolledig bestand, dus we hebben het niet aangeboden om te downloaden. Probeer opnieuw met dit tabblad zichtbaar, of gebruik desktop-Chrome.',
  'Create new video': 'Nieuwe video maken',
  'Your idea': 'Jouw idee',
  'Natural': 'Natuurlijk',
  'Working…': 'Bezig…',
  '🎲 Surprise me': '🎲 Verras me',
  '📝 Use my script as is': '📝 Mijn script ongewijzigd gebruiken',
  'Camera preset': 'Camerapreset',
  'Your latest videos': 'Je nieuwste video’s',
  'Presenter': 'Presentator',
  '1 · Who’s talking': '1 · Wie spreekt',
  '🎭 your characters': '🎭 jouw personages',
  '🎯 Max realism — animate my real photo': '🎯 Maximaal realisme — mijn echte foto animeren',
  '✓ Scene ready — preview on the right.': '✓ Scène klaar — voorbeeld rechts.',
  '2 · What they say': '2 · Wat ze zeggen',
  '3 · How it looks': '3 · Hoe het eruitziet',
  'Motion': 'Beweging',
  '⬇ Download MP4': '⬇ MP4 downloaden',
  'One photo. Suddenly alive.': 'Eén foto. Plotseling levend.',
  'Cost per clip': 'Kosten per clip',
  '↺ Animate another': '↺ Nog een animeren',
  'Grow': 'Groeien',
  'Sending to the motion engine…': 'Versturen naar de bewegingsengine…',
  '📊 Facts': '📊 Feiten',
  'Turn it into episode 2': 'Maak er aflevering 2 van',
  'Start here': 'Begin hier',
  'Engine': 'Engine',
  'Highly aesthetic, by xAI': 'Zeer esthetisch, van xAI',
  'Google’s best image model': 'Googles beste beeldmodel',
  'AI voiceover included': 'AI-voice-over inbegrepen',
  '6 engines': '6 engines',
  'AI Presenter': 'AI-presentator',
  'Lock a character →': 'Een personage vastleggen →',
  'Make a clip →': 'Een clip maken →',
  'Make an ad →': 'Een advertentie maken →',
  'Generate free →': 'Gratis genereren →',
  'Creating…': 'Maken…',
  'Describe your image first': 'Beschrijf eerst je afbeelding',
  'Type your script first': 'Typ eerst je script',
  'From the founder': 'Van de oprichter',
  'Faceless video generator': 'Faceless-videogenerator',
  'Text to video Shorts': 'Tekst-naar-video-Shorts',
  'Cheapest AI Shorts maker': 'Goedkoopste AI-Shorts-maker',
  'Faceless channel ideas (2026)': 'Faceless-kanaalideeën (2026)',
  'Shorts idea widget': 'Shorts-ideeënwidget',
  'Live case study: our channel on Autopilot': 'Live casestudy: ons kanaal op Autopilot',
  'Free YouTube Shorts scripts': 'Gratis YouTube Shorts-scripts',
  'Comment to Short script': 'Van reactie naar Short-script',
  'Business video content planner': 'Videocontentplanner voor bedrijven',
  'Real estate video maker': 'Vastgoedvideomaker',
  'Shorts title & hashtag generator': 'Shorts-titel- & hashtaggenerator',
  'Free viral score': 'Gratis virale score',
  'Make money clipping with AI': 'Geld verdienen met AI-clipping',
  'Shorts RPM by niche (2026)': 'Shorts-RPM per niche (2026)',
  'Can you monetize AI videos?': 'Kun je AI-video’s monetiseren?',
}
