// KINEO-INTERFACE-16-LINGUAS-2026-09-21 — interface em pl. Só copy autoral da interface: nunca prompt,
// título, resultado, nome de motor ou erro de API. Frase fora daqui cai em inglês (components/InterfaceLanguage.tsx).
// Gerado de scratchpad/tr-pl.js sobre o corpus vivo de frases (415); números e "Kineo" preservados por construção.
export const DICT: Record<string, string> = {
  'Generation failed': 'Generowanie nie powiodło się',
  'You can retry safely.': 'Możesz bezpiecznie spróbować ponownie.',
  'This engine is not available on your account right now': 'Ten silnik nie jest teraz dostępny na Twoim koncie',
  'Retrying the same engine will stop at this same place. Pick another engine to keep going.': 'Ponowna próba z tym samym silnikiem zatrzyma się w tym samym miejscu. Wybierz inny silnik, aby kontynuować.',
  'The engine is cooling down after two refunded attempts': 'Silnik chłodzi się po dwóch zwróconych próbach',
  'Starting another one right now stops at this same place. Give it a few minutes.': 'Uruchomienie kolejnej teraz zatrzyma się w tym samym miejscu. Daj mu kilka minut.',
  'Starting another one right now stops at this same place. The button below unlocks by itself.': 'Uruchomienie kolejnej teraz zatrzyma się w tym samym miejscu. Przycisk poniżej odblokuje się sam.',
  'We stopped waiting on this render instead of leaving you hanging': 'Przestaliśmy czekać na ten render, zamiast zostawiać Cię bez odpowiedzi',
  'This one ran far longer than any video that finishes here. Starting again is worth it.': 'Ten trwał o wiele dłużej niż jakiekolwiek wideo, które tu powstaje. Warto zacząć od nowa.',
  'The video engine is busy — this is on our side, not your idea': 'Silnik wideo jest zajęty — to po naszej stronie, nie w Twoim pomyśle',
  'Nothing about your text is wrong. Trying again in a few minutes usually goes straight through.': 'Z Twoim tekstem wszystko jest w porządku. Ponowna próba za kilka minut zwykle przechodzi od razu.',
  'Create Video': 'Utwórz wideo',
  'Create a new video': 'Utwórz nowe wideo',
  'AI Avatar Studio': 'Studio awatarów AI',
  'Viral Templates': 'Viralowe szablony',
  'Channel Builder': 'Kreator kanału',
  'Invite & Earn': 'Zaproś i zarabiaj',
  'Start free': 'Zacznij za darmo',
  'Try 7 days for $1': 'Wypróbuj 7 dni za $1',
  'Pick a lane': 'Wybierz ścieżkę',
  'All free tools': 'Wszystkie darmowe narzędzia',
  'Terms of Service': 'Regulamin',
  'Trust Center': 'Centrum zaufania',
  'Review & publish': 'Sprawdź i opublikuj',
  'Your image': 'Twój obraz',
  'Cost per image': 'Koszt za obraz',
  'No videos yet': 'Brak filmów',
  'No audio yet': 'Brak audio',
  '🎬 Studio — generate video': '🎬 Studio — generuj wideo',
  '🎨 Images — create image': '🎨 Obrazy — utwórz obraz',
  '🎙 Audio — text to speech': '🎙 Audio — tekst na mowę',
  'Type it. See it. Six image engines, one screen.': 'Wpisz. Zobacz. Sześć silników obrazu, jeden ekran.',
  'Type it. Hear it. Four voice engines, one screen.': 'Wpisz. Posłuchaj. Cztery silniki głosu, jeden ekran.',
  'Everything you’ve created, in one place.': 'Wszystko, co stworzyłeś, w jednym miejscu.',
  'Add credits →': 'Dodaj kredyty →',
  'Upscale any result to 2x for 1 credit.': 'Powiększ dowolny wynik 2x za 1 kredyt.',
  'We couldn’t load your images right now.': 'Nie udało się teraz wczytać Twoich obrazów.',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'Twoje obrazy i kredyty są bezpieczne — to tylko chwilowy problem z odczytem.',
  'We couldn’t load your audio right now.': 'Nie udało się teraz wczytać Twojego audio.',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'Twoje audio i kredyty są bezpieczne — to tylko chwilowy problem z odczytem.',
  'We couldn’t load part of your library right now.': 'Nie udało się teraz wczytać części Twojej biblioteki.',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'Twoje filmy i kredyty są bezpieczne — to tylko chwilowy problem z odczytem.',
  '↻ Try again': '↻ Spróbuj ponownie',
  '⬇ Download': '⬇ Pobierz',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': 'Podoba Ci się głos? Studio zbuduje wokół niego cały film — obraz, napisy i muzykę.',
  'Open Studio →': 'Otwórz Studio →',
  'open the Studio': 'otwórz Studio',
  'Next episode →': 'Następny odcinek →',
  'create your first image': 'utwórz swój pierwszy obraz',
  'generate your first voiceover': 'wygeneruj swój pierwszy lektor',
  'Instant drafts': 'Szkice od ręki',
  'Deep prompt understanding': 'Głębokie rozumienie promptu',
  'Perfect text rendering': 'Idealne renderowanie tekstu',
  'Create Image': 'Utwórz obraz',
  'Click-magnet YouTube covers': 'Okładki YouTube, które przyciągają kliknięcia',
  'Bring any image to life': 'Ożyw dowolny obraz',
  'Instant narration': 'Narracja od ręki',
  'Four voice engines': 'Cztery silniki głosu',
  'A face that speaks your script': 'Twarz, która mówi Twój skrypt',
  'Every control, one screen': 'Wszystkie ustawienia, jeden ekran',
  'Today’s trending topics': 'Dzisiejsze trendy',
  'Real renders, every engine': 'Prawdziwe rendery, każdy silnik',
  'Type an idea — watch it become a film.': 'Wpisz pomysł — zobacz, jak staje się filmem.',
  'Start with the full toolkit': 'Zacznij z pełnym zestawem narzędzi',
  'Kineo’s own engine — 3–7 min': 'Własny silnik Kineo — 3–7 min',
  'The workhorse AI video engine': 'Silnik wideo AI do codziennej pracy',
  'Cinematic motion & camera': 'Filmowy ruch i kamera',
  'Film scenes, native voice & lip sync': 'Sceny filmowe, natywny głos i synchronizacja ust',
  'Talking video from one photo': 'Mówiące wideo z jednego zdjęcia',
  'From idea to posted Short in 3 steps.': 'Od pomysłu do opublikowanego Shorta w 3 krokach.',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'Bez nagrywania, bez montażu, bez osi czasu. Wpisz raz — Kineo zrobi resztę.',
  'Step 1': 'Krok 1',
  'Kineo builds it': 'Kineo to buduje',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'AI pisze skrypt zbudowany pod retencję, nagrywa lektora, dobiera materiał i wypala napisy — gotowe wideo 9:16.',
  'Download & post': 'Pobierz i opublikuj',
  'Why Kineo': 'Dlaczego Kineo',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'Większość narzędzi tnie długie wideo, które już nagrałeś. Kineo buduje je od zera.',
  'See how to make Shorts without filming →': 'Zobacz, jak robić Shorty bez nagrywania →',
  'Generates the Short from just an idea': 'Generuje Shorta z samego pomysłu',
  'Writes the script for you': 'Pisze skrypt za Ciebie',
  'Finds and matches footage': 'Znajduje i dobiera materiał',
  'your upload': 'Twój plik',
  'AI image studio included': 'Studio obrazów AI w zestawie',
  'Voice studio (text-to-speech)': 'Studio głosu (tekst na mowę)',
  'One-click HD film enhance': 'Poprawa filmu do HD jednym kliknięciem',
  'One idea — or a whole toolkit.': 'Jeden pomysł — albo cały zestaw narzędzi.',
  'Try AI Presenter →': 'Wypróbuj Prezentera AI →',
  'Transparent Clips': 'Przezroczyste klipy',
  'UGC Product Ads': 'Reklamy produktów UGC',
  'Animate a photo →': 'Ożyw zdjęcie →',
  'Make a thumbnail →': 'Zrób miniaturę →',
  'Free AI Shorts': 'Darmowe Shorty AI',
  'Start with a niche that already works.': 'Zacznij od niszy, która już działa.',
  'Not sure? Take the quiz →': 'Nie wiesz? Zrób quiz →',
  'Pick your engine. Ship a Short today.': 'Wybierz silnik. Opublikuj Shorta dziś.',
  'Cancel anytime': 'Anuluj w każdej chwili',
  'Generate image →': 'Generuj obraz →',
  'Generate audio →': 'Generuj audio →',
  'Paid plans unlock clean MP4s.': 'Płatne plany odblokowują czyste MP4.',
  'Best for starting out': 'Najlepszy na start',
  'Best value per film': 'Najlepsza wartość za film',
  'on Nano Banana': 'na Nano Banana',
  'Every video engine incl. MiniMax H3': 'Każdy silnik wideo, w tym MiniMax H3',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'MP4 bez znaku wodnego · 100 projektów · 90 dni przechowywania',
  ', finished': ', gotowe',
  '— every engine unlocked': '— każdy silnik odblokowany',
  '· voice + karaoke captions + score': '· głos + napisy karaoke + muzyka',
  '500 projects · forever storage': '500 projektów · przechowywanie na zawsze',
  'Cancel anytime — 7-day money-back': 'Anuluj w każdej chwili — 7 dni zwrotu pieniędzy',
  'films on Omni Flash': 'filmów na Omni Flash',
  '· 2 free HD enhances / month': '· 2 darmowe poprawy HD / miesiąc',
  'Unlimited projects · forever storage': 'Nieograniczone projekty · przechowywanie na zawsze',
  'Everything in Creator': 'Wszystko z Creator',
  'Calculate your cost per Short →': 'Oblicz koszt jednego Shorta →',
  'How much do Shorts pay? →': 'Ile płacą Shorty? →',
  'Highest-RPM niches →': 'Nisze z najwyższym RPM →',
  'read the full review →': 'przeczytaj pełną recenzję →',
  'a single line is enough — or paste a full script': 'wystarczy jedna linijka — albo wklej cały skrypt',
  '1080×1920 · Full HD master': '1080×1920 · master Full HD',
  'Every film is delivered as a 1080×1920 Full HD master (engines render natively at 720–768p and are mastered up). For maximum sharpness, run ✨HD Enhance on the finished film.': 'Każdy film dostarczamy jako master 1080×1920 Full HD (silniki renderują natywnie w 720–768p i są masterowane w górę). Dla maksymalnej ostrości uruchom ✨HD Enhance na gotowym filmie.',
  'Your idea first. Review the settings, then generate.': 'Najpierw Twój pomysł. Sprawdź ustawienia, potem generuj.',
  '📷 Photo': '📷 Zdjęcie',
  '🖼️ Upload a different photo': '🖼️ Prześlij inne zdjęcie',
  '🎙️ Generating…': '🎙️ Generowanie…',
  '🎙️ Cloning the voice…': '🎙️ Klonowanie głosu…',
  '🎙️ Upload a different sample': '🎙️ Prześlij inną próbkę',
  '⏹ Stop & clone': '⏹ Zatrzymaj i sklonuj',
  '🎭 Generate my avatar video': '🎭 Wygeneruj moje wideo z awatarem',
  'Continue exactly where ChatGPT stopped.': 'Kontynuuj dokładnie tam, gdzie zatrzymał się ChatGPT.',
  '✨ Let AI structure it': '✨ Niech AI to uporządkuje',
  'Optional settings': 'Ustawienia opcjonalne',
  'optional — a pre-tested move added to your prompt': 'opcjonalnie — przetestowany ruch dodany do Twojego promptu',
  'Reference image': 'Obraz referencyjny',
  '🖼️ Start your video from an image — coming soon': '🖼️ Zacznij wideo od obrazu — wkrótce',
  'Estimated cost': 'Szacowany koszt',
  'Your credits buy': 'Za Twoje kredyty dostaniesz',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'Głos, napisy karaoke i muzyka w cenie. Jeśli render się nie uda, kredyty wracają od razu.',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'Ten sam temat, nowy hook i puenta — pomysł jest już napisany.',
  'Build next episode →': 'Zbuduj następny odcinek →',
  'Episode 2 →': 'Odcinek 2 →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'Mówiący prezenter AI ze zdjęcia — synchronizacja ust, własne studio',
  'Your face. Your script.': 'Twoja twarz. Twój skrypt.',
  'Everything you need to make yourself speak — nothing you don’t.': 'Wszystko, czego potrzebujesz, żeby przemówić — i nic ponadto.',
  'BEST MOTION': 'NAJLEPSZY RUCH',
  '1.5 · Realism': '1.5 · Realizm',
  '🎬 Put me in a scene': '🎬 Umieść mnie w scenie',
  'use original photo': 'użyj oryginalnego zdjęcia',
  '✍️ Say exactly this — word for word': '✍️ Powiedz dokładnie to — słowo w słowo',
  '✨ Expand into a full Short script (45–60s)': '✨ Rozwiń do pełnego skryptu Shorta (45–60 s)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 Tryb reklamy produktu — sprzedaj produkt w stylu UGC',
  'Free — fills the script box above, then generate with your presenter.': 'Za darmo — wypełnia pole skryptu powyżej, potem generuj ze swoim prezenterem.',
  '2.5 · Speak in your own voice': '2.5 · Mów własnym głosem',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ Głos sklonowany — narracja będzie mówić tym głosem.',
  'use a default voice': 'użyj domyślnego głosu',
  '🎬 Full video — face the whole time': '🎬 Pełne wideo — twarz przez cały czas',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 Prezenter AI — szybki i naturalny · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro — jakość zdjęcia premium · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 Body Motion — tułów, dłonie i gesty · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ Klasyczny — talking head · 110 cr',
  'you have': 'masz',
  'to create your avatar video.': 'aby utworzyć wideo z awatarem.',
  '5 · Gesture clips — transparent background': '5 · Klipy z gestami — przezroczyste tło',
  'auto-refunded if it fails': 'automatyczny zwrot w razie niepowodzenia',
  '⬇️ Download transparent WebM': '⬇️ Pobierz przezroczysty WebM',
  '⬇️ Original MP4 (with background)': '⬇️ Oryginalny MP4 (z tłem)',
  'Pick a face to preview': 'Wybierz twarz do podglądu',
  '↺ Make another': '↺ Zrób kolejne',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'Ludzie, zwierzęta, produkty, stare zdjęcia rodzinne — prześlij zdjęcie lub wklej publiczny link do obrazu i zobacz, jak się porusza.',
  'The photo': 'Zdjęcie',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': 'JPG/PNG do 8 MB. Publiczne linki są bezpiecznie pobierane i sprawdzane na naszym serwerze.',
  'sign in': 'zaloguj się',
  'Kineo will fetch and validate it on the server when you animate.': 'Kineo pobierze i sprawdzi go na serwerze, gdy uruchomisz animację.',
  'Upload a photo to preview': 'Prześlij zdjęcie do podglądu',
  '🖼️ Upload a photo': '🖼️ Prześlij zdjęcie',
  '✨ Bring it to life': '✨ Ożyw',
  'Uploading your photo…': 'Przesyłanie zdjęcia…',
  'Bringing your photo to life… (1–3 min)': 'Ożywianie Twojego zdjęcia… (1–3 min)',
  'Alive!': 'Żyje!',
  '🌬️ Subtle & real': '🌬️ Subtelnie i naturalnie',
  '😊 Person comes alive': '😊 Osoba ożywa',
  'Type your idea first': 'Najpierw wpisz swój pomysł',
  '📖 True Story': '📖 Prawdziwa historia',
  'Paste your ChatGPT script': 'Wklej swój skrypt z ChatGPT',
  'First Short complete': 'Pierwszy Short gotowy',
  'Keep your show moving': 'Utrzymaj swój program w ruchu',
  'Cheapest way to see your idea as a film': 'Najtańszy sposób, by zobaczyć swój pomysł jako film',
  'Slow Dolly-In': 'Powolny najazd',
  'FPV Drone': 'Dron FPV',
  'Macro Detail': 'Detal makro',
  'Sharing & creator options': 'Udostępnianie i opcje twórcy',
  'We couldn’t load your videos right now': 'Nie udało się teraz wczytać Twoich filmów',
  'Your videos and credits are safe — this is a temporary read hiccup, not a lost library.': 'Twoje filmy i kredyty są bezpieczne — to chwilowy problem z odczytem, nie utracona biblioteka.',
  '⚡ Generate Video': '⚡ Generuj wideo',
  'Prefer clean exports now? Starter includes': 'Wolisz czyste eksporty już teraz? Starter zawiera',
  'credits each month for': 'kredytów miesięcznie za',
  'Your existing files stay available. Starter applies to new exports after checkout.': 'Twoje obecne pliki pozostają dostępne. Starter dotyczy nowych eksportów po zakupie.',
  'Build Next Episode First': 'Najpierw zbuduj następny odcinek',
  'Video unavailable': 'Wideo niedostępne',
  'Free MP4 includes the Kineo watermark': 'Darmowy MP4 zawiera znak wodny Kineo',
  'Free distribution · latest Short': 'Darmowa dystrybucja · najnowszy Short',
  'Send it to one person for feedback': 'Wyślij jednej osobie po opinię',
  'Copy a public watch page for your finished video. Your friend can watch it without logging in, then use “Make one like this” if the idea inspires them.': 'Skopiuj publiczną stronę odtwarzania gotowego wideo. Znajomy obejrzy je bez logowania, a potem może użyć „Zrób taki sam”, jeśli pomysł go zainspiruje.',
  'Public watch links are temporarily paused': 'Publiczne linki do oglądania są tymczasowo wstrzymane',
  'Your video stays in your account. Download the MP4 if you want to send it directly; Kineo will not publish a public page without an explicit visibility choice.': 'Twoje wideo zostaje na Twoim koncie. Pobierz MP4, jeśli chcesz wysłać je bezpośrednio; Kineo nie opublikuje publicznej strony bez wyraźnego wyboru widoczności.',
  'Loading…': 'Ładowanie…',
  'For new videos ·': 'Dla nowych filmów ·',
  'Published it?': 'Opublikowane?',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'Ostre, na wprost, jedna osoba. Do ruchu ciała użyj zdjęcia od pasa w górę lub całej sylwetki z widocznymi obiema dłońmi. Czarne pasy są usuwane automatycznie.',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'Najlepszy profesjonalny wynik: prześlij pionowy klip 5–20 s z prawdziwymi gestami, które chcesz, o długości zbliżonej do skryptu. Sync-3 zastępuje mowę, zachowując prawdziwą twarz i ruch ciała. MP4/MOV do 40 MB.',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'Potwierdzam, że mam prawo do wykorzystania wizerunku tej osoby i zgadzam się na jego animację przez AI.',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': 'Prześlij wyraźną próbkę głosu ~30-60 s (jedna osoba, mało szumów w tle), a narracja będzie mówić tym głosem. Używaj tylko głosu, do którego masz prawo.',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'Filmy słowo w słowo pokazują Twoją twarz przez cały czas (są krótkie — b-roll niepotrzebny).',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'Filmy z maksymalnym realizmem i zbudowaną sceną utrzymują prezentera na ekranie przez całą narrację.',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ Intro z hookiem — Ty otwierasz, b-roll opowiada historię',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'Krótkie klipy Twojego prezentera, który macha, wskazuje, prezentuje — dostarczone jako WebM z PRAWDZIWYM przezroczystym tłem. Wrzuć je prosto do Storyline, Premiere, CapCut lub dowolnego slajdu. Bez green screena, bez kluczowania.',
  'Cinematic film — 9-image consistency': 'Film kinowy — spójność 9 obrazów',
  '#1-ranked video model — Aug 2026 arena': 'Model wideo nr 1 w rankingu — arena sie 2026',
  'Cinematic motion and camera work': 'Filmowy ruch i praca kamery',
  'Shorts money & growth': 'Pieniądze i wzrost z Shortów',
  'Compare Kineo with 27 AI video tools →': 'Porównaj Kineo z 27 narzędziami wideo AI →',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'Mówiący prezenterzy, postacie wielokrotnego użytku, przezroczyste klipy, reklamy produktów — plus wszystko, by znaleźć trend i na nim zyskać.',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'Jedno zdjęcie + Twój skrypt — mówiące wideo ze studyjną synchronizacją ust, w stylu HeyGen.',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'Zapisz postać raz — dokładnie ta sama twarz w każdym wideo i miniaturze, które zrobisz.',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'Gesty prezentera — machanie, wskazywanie, prezentowanie — jako WebM z prawdziwym przezroczystym tłem.',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'Wklej dowolny produkt — dostaniesz reklamę 15-30 s w stylu twórcy, napisaną i nagraną za Ciebie.',
  'Bring any still photo to life as a moving, postable video.': 'Ożyw dowolne zdjęcie jako ruchome wideo gotowe do publikacji.',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'Klikalne miniatury w stylu największych kanałów — z jednego promptu.',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'Każda nisza poniżej ma własną stronę generatora, dopasowane prompty i prawdziwe przykłady.',
  'Is the video really mine to post?': 'Czy wideo naprawdę jest moje i mogę je publikować?',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'Płatne plany odblokowują czysty MP4 bez znaku wodnego na YouTube, TikTok lub Reels.',
  'Do I need any editing skills?': 'Czy potrzebuję umiejętności montażu?',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'Żadnych. Wpisujesz jeden pomysł, a AI pisze skrypt, nagrywa głos, znajduje materiał i dodaje napisy.',
  'Is there a watermark?': 'Czy jest znak wodny?',
  'Paid plans export clean, watermark-free MP4s.': 'Płatne plany eksportują czyste MP4 bez znaku wodnego.',
  'Can Kineo also generate images and voiceovers?': 'Czy Kineo generuje też obrazy i lektora?',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'Tak — Kineo zawiera studio obrazów AI (6 silników, w tym FLUX, Seedream i Nano Banana Pro, od 1 kredytu za obraz) oraz studio głosu z 4 silnikami tekst na mowę (od 1 kredytu za 1000 znaków). Wszystko, co tworzysz, trafia do Twojej Biblioteki.',
  'Can I make my videos sharper?': 'Czy mogę wyostrzyć swoje filmy?',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'Każde wideo ma opcję poprawy jednym kliknięciem opartą na restauracji filmu Topaz — usuwa artefakty kompresji, odzyskuje detale i dodaje delikatne filmowe ziarno. 10 kredytów za wideo; plan Studio zawiera 2 darmowe poprawy miesięcznie.',
  'Can I use my own script?': 'Czy mogę użyć własnego skryptu?',
  'What if a generation fails?': 'Co, jeśli generowanie się nie uda?',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'Kredyty wracają automatycznie w chwili, gdy render się nie uda — bez zgłoszenia, bez czekania. Płacisz tylko za filmy, które naprawdę dostajesz.',
  'Can I cancel anytime?': 'Czy mogę anulować w każdej chwili?',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'W każdej chwili, jednym kliknięciem. Plany są miesięczne, a kredyty odnawiają się co miesiąc.',
  'Can I run a whole channel with the same host?': 'Czy mogę prowadzić cały kanał z tym samym prowadzącym?',
  'Can I monetize the videos?': 'Czy mogę monetyzować filmy?',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'Tak. Każde wideo jest Twoje — zachowaj, publikuj i monetyzuj, w tym w Programie partnerskim YouTube, na TikToku i w Reels. Bez dodatkowej licencji.',
  'Can I use the videos commercially, or for client work?': 'Czy mogę używać filmów komercyjnie lub dla klientów?',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'Tak. Nasz regulamin pozwala używać Kineo w legalnych celach prywatnych lub komercyjnych i potwierdza, że zachowujesz własność generowanych filmów, więc możesz je publikować, monetyzować i dostarczać klientowi w ramach własnej płatnej usługi. Bez dodatkowej licencji, bez opłat za wideo. Dwa ograniczenia wynikają z tego samego regulaminu: nie możesz odsprzedawać ani redystrybuować samego Kineo, a klipy stockowe w renderze są licencjonowane do użycia w Twoim gotowym wideo, nie do ponownego wgrania jako samodzielny materiał stockowy. Płatne plany eksportują czysty MP4 bez znaku wodnego.',
  'How long does one video take?': 'Ile trwa jedno wideo?',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'Tryb Fast zwykle kończy w 3–7 minut. Filmy generowane przez AI i filmowe trwają nieco dłużej, bo każda scena jest generowana przed złożeniem końcowego MP4.',
  'How much does Kineo cost?': 'Ile kosztuje Kineo?',
  'Kineo has three monthly plans: Starter at $': 'Kineo ma trzy plany miesięczne: Starter za $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'kredytów. Kredyty wydaje się na wideo, a ile kosztuje wideo, zależy od wybranego silnika — render Fast i film kinowy schodzą z tego samego salda w bardzo różnym tempie.',
  'Which AI video engines can I use in Kineo?': 'Których silników wideo AI mogę używać w Kineo?',
  ', behind one interface and one balance:': ', za jednym interfejsem i jednym saldem:',
  'What is the best AI video generator for faceless YouTube channels?': 'Jaki jest najlepszy generator wideo AI dla kanałów YouTube bez twarzy?',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'Tak. Darmowi użytkownicy, którzy nigdy nie płacili, mogą pobierać, udostępniać i publikować MP4 ze znakiem wodnym.',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'Filmy próbne mają mały znak wodny — możesz pobrać, udostępnić i opublikować MP4. Po okresie próbnym darmowe wideo Fast ma znak wodny.',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'Darmowe pobrania mają znak wodny; płatne plany odblokowują czysty MP4.',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'Pobrania próbne mają znak wodny, podobnie jak darmowe wideo Fast po okresie próbnym, a płatne plany zawsze eksportują czysto.',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'Darmowy dostęp daje nowym użytkownikom do 3 filmów Fast ze znakiem wodnym co 24 godziny, bez karty. Możesz je pobierać i udostępniać.',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'Twórz, pobieraj i udostępniaj do 3 filmów Fast ze znakiem wodnym co 24 h, bez karty.',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'Twórz, oglądaj, pobieraj i udostępniaj do 3 filmów Fast ze znakiem wodnym co 24 h — bez karty.',
  'create, watch, download and share up to 3 Fast videos every 24h': 'twórz, oglądaj, pobieraj i udostępniaj do 3 filmów Fast co 24 h',
  '— no card, watermark included.': '— bez karty, ze znakiem wodnym.',
  'AI image generator — 6 engines': 'Generator obrazów AI — 6 silników',
  'AI voice generator (text to speech)': 'Generator głosu AI (tekst na mowę)',
  'AI video upscaler & enhancer': 'Upscaler i ulepszacz wideo AI',
  'Trending Shorts ideas today': 'Dzisiejsze trendy na Shorty',
  'AI Avatar video — your face, any script': 'Wideo z awatarem AI — Twoja twarz, dowolny skrypt',
  'Kineo facts & numbers (citable)': 'Fakty i liczby Kineo (do cytowania)',
  'Free AI Shorts generator': 'Darmowy generator Shortów AI',
  'YouTube Shorts from a topic': 'YouTube Shorts z tematu',
  'ChatGPT script to YouTube Short': 'Skrypt z ChatGPT na YouTube Short',
  'Shorts without filming': 'Shorty bez nagrywania',
  'Faceless niche picker': 'Wybór niszy bez twarzy',
  'State of AI Shorts 2026': 'Stan Shortów AI 2026',
  'AI Shorts for agencies & client work': 'Shorty AI dla agencji i klientów',
  'Trust Center — privacy, payments & ownership': 'Centrum zaufania — prywatność, płatności i własność',
  'Affiliate program - 30% recurring': 'Program partnerski - 30% cyklicznie',
  'Free AI Shorts by niche': 'Darmowe Shorty AI według niszy',
  'Free script generator': 'Darmowy generator skryptów',
  'Product video ad script': 'Skrypt reklamy wideo produktu',
  'Client video brief generator': 'Generator briefu wideo dla klienta',
  'Free hook generator': 'Darmowy generator hooków',
  'Shorts script timer': 'Stoper skryptu Shorta',
  'Shorts money calculator': 'Kalkulator zarobków z Shortów',
  'How much do Shorts pay?': 'Ile płacą Shorty?',
  'Best AI Shorts generators': 'Najlepsze generatory Shortów AI',
  'TikTok vs Shorts: which pays more?': 'TikTok vs Shorty: co płaci więcej?',
  'All comparisons': 'Wszystkie porównania',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · Wszelkie prawa zastrzeżone',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'To zależy, czy chcesz zmontowanego materiału stockowego, czy wygenerowanego. Narzędzia takie jak InVideo i AutoShorts tną klipy stockowe pod Twój skrypt — taniej i wystarczająco do filmów z tezami. Kineo generuje materiał modelami takimi jak Veo 3.1 i Kling 3, zachowuje Twoją narrację słowo w słowo zamiast ją przepisywać i celuje w 60 sekund lub więcej, by wideo kwalifikowało się do TikTok Creator Rewards. Jeśli Twój kanał żyje z obrazów, których nikt inny nie ma, wygrywa generowanie; jeśli żyje z ilości, stock jest tańszy.',
  'Paste the complete script from ChatGPT here…': 'Wklej tutaj cały skrypt z ChatGPT…',
  'Paste the idea from ChatGPT here…': 'Wklej tutaj pomysł z ChatGPT…',
  'What’s your video about? One idea in — a finished film out: voiced, scored and captioned.': 'O czym jest Twoje wideo? Jeden pomysł na wejściu — gotowy film na wyjściu: z głosem, muzyką i napisami.',
  'Settings and generation': 'Ustawienia i generowanie',
  'Search your videos…': 'Szukaj w swoich filmach…',
  'Search your audio…': 'Szukaj w swoim audio…',
  'Search your images by engine': 'Szukaj obrazów według silnika',
  'No playable videos in your library yet. Check your latest project above.': 'W Twojej bibliotece nie ma jeszcze odtwarzalnych filmów. Sprawdź swój najnowszy projekt powyżej.',
  'Make a finished Short →': 'Zrób gotowego Shorta →',
  'Video Editing & Creator Tools': 'Edycja wideo i narzędzia dla twórców',
  'Trim, resize, change speed, mute or add text. Edit a file you already have, right in your browser. Your script and planning tools are still here below.': 'Przytnij, zmień rozmiar, zmień prędkość, wycisz lub dodaj tekst. Edytuj plik, który już masz, prosto w przeglądarce. Narzędzia do skryptów i planowania nadal są poniżej.',
  '5 local editing tools': '5 lokalnych narzędzi do edycji',
  'No generation credits to edit': 'Edycja nie zużywa kredytów generowania',
  'Edit video': 'Edytuj wideo',
  'Files up to 100 MB and 3 minutes. Local, real-time export up to 1280 px on the long edge. MP4 or WebM depending on your browser; downloads are not saved to My Videos.': 'Pliki do 100 MB i 3 minut. Lokalny eksport w czasie rzeczywistym do 1280 px na dłuższym boku. MP4 lub WebM zależnie od przeglądarki; pobrania nie są zapisywane w Moich filmach.',
  'Video Trimmer': 'Przycinanie wideo',
  'Cut the beginning or end and keep only the clip you need.': 'Utnij początek lub koniec i zostaw tylko potrzebny fragment.',
  'Video Resizer': 'Zmiana rozmiaru wideo',
  'Go vertical, square or wide. Fit the frame or crop to fill.': 'Pion, kwadrat lub panorama. Dopasuj do kadru lub przytnij, by wypełnić.',
  'Video Speed Changer': 'Zmiana prędkości wideo',
  'Slow it down or speed it up, from 0.5× to 2×.': 'Zwolnij lub przyspiesz, od 0.5× do 2×.',
  'Remove Audio': 'Usuń dźwięk',
  'Download a copy without the original audio.': 'Pobierz kopię bez oryginalnego dźwięku.',
  'Add Text to Video': 'Dodaj tekst do wideo',
  'Add a title or message that stays on screen. Not automatic subtitles.': 'Dodaj tytuł lub wiadomość, która zostaje na ekranie. To nie są automatyczne napisy.',
  'No account · current Kineo plans': 'Bez konta · aktualne plany Kineo',
  'No account · fair-use limit': 'Bez konta · limit uczciwego użytku',
  'No account · unlimited in browser': 'Bez konta · bez limitu w przeglądarce',
  'Edit an existing video here. Create a new one with Kineo.': 'Edytuj tutaj istniejące wideo. Nowe utwórz w Kineo.',
  'Create an AI video →': 'Utwórz wideo AI →',
  'Edit your video, preview the changes, then export a copy.': 'Edytuj wideo, obejrzyj zmiany, a potem wyeksportuj kopię.',
  'Video preview': 'Podgląd wideo',
  'Preview is silent. The download keeps audio unless Mute is selected.': 'Podgląd jest bez dźwięku. Pobrany plik zachowa dźwięk, chyba że wybrano Wycisz.',
  'Start with your video': 'Zacznij od swojego wideo',
  'Choose a local file. It stays on this device.': 'Wybierz plik lokalny. Zostaje na tym urządzeniu.',
  'Choose video file': 'Wybierz plik wideo',
  'Video file': 'Plik wideo',
  'Video settings': 'Ustawienia wideo',
  'Aspect ratio': 'Proporcje obrazu',
  'Playback speed': 'Prędkość odtwarzania',
  'On-screen text (100 characters, 3 lines)': 'Tekst na ekranie (100 znaków, 3 linie)',
  'Add a title or message': 'Dodaj tytuł lub wiadomość',
  'Export edited video': 'Eksportuj edytowane wideo',
  'Export happens in real time. Keep this tab visible. Re-encoded at up to 1280 px on the long edge; format depends on your browser.': 'Eksport odbywa się w czasie rzeczywistym. Trzymaj tę kartę widoczną. Przekodowane do 1280 px na dłuższym boku; format zależy od przeglądarki.',
  'Making a 4-second sample on your device…': 'Tworzenie 4-sekundowej próbki na Twoim urządzeniu…',
  'Reading your file…': 'Odczytywanie pliku…',
  'Export result': 'Wynik eksportu',
  'Your edited video': 'Twoje edytowane wideo',
  'Local download only. This copy is not saved to My Videos.': 'Tylko lokalne pobranie. Ta kopia nie jest zapisywana w Moich filmach.',
  'Exported video': 'Wyeksportowane wideo',
  'No upload. No generation credits. Your original is never overwritten.': 'Bez przesyłania. Bez kredytów generowania. Oryginał nigdy nie jest nadpisywany.',
  'Up to 100 MB · 3 minutes · MP4/WebM input recommended. These are basic editing tools, not the CapCut app.': 'Do 100 MB · 3 minuty · zalecane wejście MP4/WebM. To podstawowe narzędzia do edycji, nie aplikacja CapCut.',
  'Need a new video? Open Kineo Studio →': 'Potrzebujesz nowego wideo? Otwórz Kineo Studio →',
  'This browser cannot export video here. Try the latest desktop Chrome or Edge.': 'Ta przeglądarka nie może tu eksportować wideo. Wypróbuj najnowszy Chrome lub Edge na komputerze.',
  'Choose a non-empty video file of up to 100 MB.': 'Wybierz niepusty plik wideo do 100 MB.',
  'Use a playable clip of up to 3 minutes. Very large dimensions are not supported.': 'Użyj odtwarzalnego klipu do 3 minut. Bardzo duże wymiary nie są obsługiwane.',
  'Check the start and end: select at least 0.25 seconds within your clip.': 'Sprawdź początek i koniec: zaznacz co najmniej 0.25 sekundy w klipie.',
  'Choose a speed between 0.5× and 2×.': 'Wybierz prędkość między 0.5× a 2×.',
  'Use up to 100 characters and 3 lines of text.': 'Użyj maksymalnie 100 znaków i 3 linii tekstu.',
  'Choose a supported aspect ratio, framing and text position.': 'Wybierz obsługiwane proporcje, kadrowanie i pozycję tekstu.',
  'This file could not be decoded. Try an MP4 (H.264) or WebM file.': 'Nie udało się zdekodować tego pliku. Wypróbuj plik MP4 (H.264) lub WebM.',
  'Export stopped because this tab was hidden. Keep it open and visible, then export again. Your original is safe.': 'Eksport zatrzymał się, bo ta karta była ukryta. Trzymaj ją otwartą i widoczną, potem eksportuj ponownie. Oryginał jest bezpieczny.',
  'Export stopped making progress. Try a shorter clip or desktop Chrome. Your original is unchanged.': 'Eksport przestał postępować. Wypróbuj krótszy klip lub Chrome na komputerze. Oryginał jest bez zmian.',
  'Audio could not start. Try exporting again, or choose Mute video.': 'Nie udało się uruchomić dźwięku. Spróbuj eksportować ponownie lub wybierz Wycisz wideo.',
  'The browser blocked playback. Try exporting again from this tab.': 'Przeglądarka zablokowała odtwarzanie. Spróbuj eksportować ponownie z tej karty.',
  'Cancelled. Your original file is unchanged.': 'Anulowano. Oryginalny plik jest bez zmian.',
  'Could not finish this export. Try a shorter clip or another supported browser.': 'Nie udało się dokończyć eksportu. Wypróbuj krótszy klip lub inną obsługiwaną przeglądarkę.',
  'The browser produced an incomplete file, so we did not offer it for download. Try again with this tab visible, or use desktop Chrome.': 'Przeglądarka utworzyła niekompletny plik, więc nie udostępniliśmy go do pobrania. Spróbuj ponownie z widoczną kartą lub użyj Chrome na komputerze.',
  'Create new video': 'Utwórz nowe wideo',
  'Your idea': 'Twój pomysł',
  'Natural': 'Naturalny',
  'Working…': 'Pracuję…',
  '🎲 Surprise me': '🎲 Zaskocz mnie',
  '📝 Use my script as is': '📝 Użyj mojego skryptu bez zmian',
  'Camera preset': 'Ustawienie kamery',
  'Your latest videos': 'Twoje najnowsze filmy',
  'Presenter': 'Prezenter',
  '1 · Who’s talking': '1 · Kto mówi',
  '🎭 your characters': '🎭 Twoje postacie',
  '🎯 Max realism — animate my real photo': '🎯 Maksymalny realizm — ożyw moje prawdziwe zdjęcie',
  '✓ Scene ready — preview on the right.': '✓ Scena gotowa — podgląd po prawej.',
  '2 · What they say': '2 · Co mówią',
  '3 · How it looks': '3 · Jak to wygląda',
  'Motion': 'Ruch',
  '⬇ Download MP4': '⬇ Pobierz MP4',
  'One photo. Suddenly alive.': 'Jedno zdjęcie. Nagle żywe.',
  'Cost per clip': 'Koszt za klip',
  '↺ Animate another': '↺ Ożyw kolejne',
  'Grow': 'Rozwijaj się',
  'Sending to the motion engine…': 'Wysyłanie do silnika ruchu…',
  '📊 Facts': '📊 Fakty',
  'Turn it into episode 2': 'Zrób z tego odcinek 2',
  'Start here': 'Zacznij tutaj',
  'Engine': 'Silnik',
  'Highly aesthetic, by xAI': 'Bardzo estetyczny, od xAI',
  'Google’s best image model': 'Najlepszy model obrazu od Google',
  'AI voiceover included': 'Lektor AI w cenie',
  '6 engines': '6 silników',
  'AI Presenter': 'Prezenter AI',
  'Lock a character →': 'Zablokuj postać →',
  'Make a clip →': 'Zrób klip →',
  'Make an ad →': 'Zrób reklamę →',
  'Generate free →': 'Generuj za darmo →',
  'Creating…': 'Tworzenie…',
  'Describe your image first': 'Najpierw opisz swój obraz',
  'Type your script first': 'Najpierw wpisz swój skrypt',
  'From the founder': 'Od założyciela',
  'Faceless video generator': 'Generator wideo bez twarzy',
  'Text to video Shorts': 'Shorty z tekstu na wideo',
  'Cheapest AI Shorts maker': 'Najtańszy kreator Shortów AI',
  'Faceless channel ideas (2026)': 'Pomysły na kanał bez twarzy (2026)',
  'Shorts idea widget': 'Widżet pomysłów na Shorty',
  'Live case study: our channel on Autopilot': 'Studium przypadku na żywo: nasz kanał na Autopilocie',
  'Free YouTube Shorts scripts': 'Darmowe skrypty YouTube Shorts',
  'Comment to Short script': 'Z komentarza w skrypt Shorta',
  'Business video content planner': 'Planer treści wideo dla firm',
  'Real estate video maker': 'Kreator wideo dla nieruchomości',
  'Shorts title & hashtag generator': 'Generator tytułów i hashtagów do Shortów',
  'Free viral score': 'Darmowy wynik viralowy',
  'Make money clipping with AI': 'Zarabiaj na klipowaniu z AI',
  'Shorts RPM by niche (2026)': 'RPM Shortów według niszy (2026)',
  'Can you monetize AI videos?': 'Czy można monetyzować filmy AI?',
}
