// KINEO-INTERFACE-16-LINGUAS-2026-09-21 — interface em pt. Só copy autoral da interface: nunca prompt,
// título, resultado, nome de motor ou erro de API. Frase fora daqui cai em inglês (components/InterfaceLanguage.tsx).
// Gerado de scratchpad/tr-pt.js sobre o corpus vivo de frases (415); números e "Kineo" preservados por construção.
export const DICT: Record<string, string> = {
  'Generation failed': 'A geração falhou',
  'You can retry safely.': 'Você pode tentar de novo com segurança.',
  'This engine is not available on your account right now': 'Este motor não está disponível na sua conta agora',
  'Retrying the same engine will stop at this same place. Pick another engine to keep going.': 'Tentar de novo com o mesmo motor vai parar neste mesmo ponto. Escolha outro motor para continuar.',
  'The engine is cooling down after two refunded attempts': 'O motor está esfriando depois de duas tentativas reembolsadas',
  'Starting another one right now stops at this same place. Give it a few minutes.': 'Começar outra agora para neste mesmo ponto. Aguarde alguns minutos.',
  'Starting another one right now stops at this same place. The button below unlocks by itself.': 'Começar outra agora para neste mesmo ponto. O botão abaixo destrava sozinho.',
  'We stopped waiting on this render instead of leaving you hanging': 'Paramos de esperar esta renderização em vez de deixar você no vácuo',
  'This one ran far longer than any video that finishes here. Starting again is worth it.': 'Esta demorou muito mais do que qualquer vídeo que termina aqui. Vale a pena começar de novo.',
  'The video engine is busy — this is on our side, not your idea': 'O motor de vídeo está ocupado — o problema é do nosso lado, não da sua ideia',
  'Nothing about your text is wrong. Trying again in a few minutes usually goes straight through.': 'Não há nada errado com o seu texto. Tentar de novo em alguns minutos costuma funcionar de primeira.',
  'Create Video': 'Criar vídeo',
  'Create a new video': 'Criar um novo vídeo',
  'AI Avatar Studio': 'Estúdio de Avatar IA',
  'Viral Templates': 'Modelos virais',
  'Channel Builder': 'Construtor de canal',
  'Invite & Earn': 'Indique e ganhe',
  'Start free': 'Começar grátis',
  'Try 7 days for $1': 'Teste 7 dias por $1',
  'Pick a lane': 'Escolha um caminho',
  'All free tools': 'Todas as ferramentas grátis',
  'Terms of Service': 'Termos de serviço',
  'Trust Center': 'Central de confiança',
  'Review & publish': 'Revisar e publicar',
  'Your image': 'Sua imagem',
  'Cost per image': 'Custo por imagem',
  'No videos yet': 'Nenhum vídeo ainda',
  'No audio yet': 'Nenhum áudio ainda',
  '🎬 Studio — generate video': '🎬 Studio — gerar vídeo',
  '🎨 Images — create image': '🎨 Imagens — criar imagem',
  '🎙 Audio — text to speech': '🎙 Áudio — texto para fala',
  'Type it. See it. Six image engines, one screen.': 'Digite. Veja. Seis motores de imagem, uma tela.',
  'Type it. Hear it. Four voice engines, one screen.': 'Digite. Ouça. Quatro motores de voz, uma tela.',
  'Everything you’ve created, in one place.': 'Tudo o que você criou, em um só lugar.',
  'Add credits →': 'Adicionar créditos →',
  'Upscale any result to 2x for 1 credit.': 'Amplie qualquer resultado em 2x por 1 crédito.',
  'We couldn’t load your images right now.': 'Não conseguimos carregar suas imagens agora.',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'Suas imagens e créditos estão a salvo — é só uma falha temporária de leitura.',
  'We couldn’t load your audio right now.': 'Não conseguimos carregar seu áudio agora.',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'Seu áudio e créditos estão a salvo — é só uma falha temporária de leitura.',
  'We couldn’t load part of your library right now.': 'Não conseguimos carregar parte da sua biblioteca agora.',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'Seus vídeos e créditos estão a salvo — é só uma falha temporária de leitura.',
  '↻ Try again': '↻ Tentar de novo',
  '⬇ Download': '⬇ Baixar',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': 'Gostou de uma voz? O Studio constrói o filme inteiro em volta dela — visuais, legendas e trilha.',
  'Open Studio →': 'Abrir o Studio →',
  'open the Studio': 'abra o Studio',
  'Next episode →': 'Próximo episódio →',
  'create your first image': 'crie sua primeira imagem',
  'generate your first voiceover': 'gere sua primeira narração',
  'Instant drafts': 'Rascunhos instantâneos',
  'Deep prompt understanding': 'Entendimento profundo do prompt',
  'Perfect text rendering': 'Texto renderizado com perfeição',
  'Create Image': 'Criar imagem',
  'Click-magnet YouTube covers': 'Capas de YouTube que atraem cliques',
  'Bring any image to life': 'Dê vida a qualquer imagem',
  'Instant narration': 'Narração instantânea',
  'Four voice engines': 'Quatro motores de voz',
  'A face that speaks your script': 'Um rosto que fala o seu roteiro',
  'Every control, one screen': 'Todos os controles, uma tela',
  'Today’s trending topics': 'Temas em alta hoje',
  'Real renders, every engine': 'Renders reais, de todos os motores',
  'Type an idea — watch it become a film.': 'Digite uma ideia — veja virar um filme.',
  'Start with the full toolkit': 'Comece com o kit completo',
  'Kineo’s own engine — 3–7 min': 'O motor próprio da Kineo — 3–7 min',
  'The workhorse AI video engine': 'O motor de vídeo IA para o dia a dia',
  'Cinematic motion & camera': 'Movimento e câmera cinematográficos',
  'Film scenes, native voice & lip sync': 'Cenas de filme, voz nativa e sincronia labial',
  'Talking video from one photo': 'Vídeo falado a partir de uma foto',
  'From idea to posted Short in 3 steps.': 'Da ideia ao Short publicado em 3 passos.',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'Sem filmar, sem editar, sem linha do tempo. Digite uma vez — a Kineo faz o resto.',
  'Step 1': 'Passo 1',
  'Kineo builds it': 'A Kineo constrói',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'A IA escreve um roteiro estruturado para retenção, grava a narração, combina as imagens e grava as legendas — um vídeo 9:16 pronto.',
  'Download & post': 'Baixe e publique',
  'Why Kineo': 'Por que a Kineo',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'A maioria das ferramentas recorta um vídeo longo que você já filmou. A Kineo constrói do zero.',
  'See how to make Shorts without filming →': 'Veja como fazer Shorts sem filmar →',
  'Generates the Short from just an idea': 'Gera o Short a partir de uma simples ideia',
  'Writes the script for you': 'Escreve o roteiro para você',
  'Finds and matches footage': 'Encontra e combina as imagens',
  'your upload': 'seu upload',
  'AI image studio included': 'Estúdio de imagens IA incluído',
  'Voice studio (text-to-speech)': 'Estúdio de voz (texto para fala)',
  'One-click HD film enhance': 'Melhoria HD do filme em um clique',
  'One idea — or a whole toolkit.': 'Uma ideia — ou um kit completo.',
  'Try AI Presenter →': 'Testar o Apresentador IA →',
  'Transparent Clips': 'Clipes transparentes',
  'UGC Product Ads': 'Anúncios UGC de produto',
  'Animate a photo →': 'Animar uma foto →',
  'Make a thumbnail →': 'Criar uma thumbnail →',
  'Free AI Shorts': 'Shorts IA grátis',
  'Start with a niche that already works.': 'Comece por um nicho que já funciona.',
  'Not sure? Take the quiz →': 'Em dúvida? Faça o quiz →',
  'Pick your engine. Ship a Short today.': 'Escolha o motor. Publique um Short hoje.',
  'Cancel anytime': 'Cancele quando quiser',
  'Generate image →': 'Gerar imagem →',
  'Generate audio →': 'Gerar áudio →',
  'Paid plans unlock clean MP4s.': 'Os planos pagos liberam MP4 limpo.',
  'Best for starting out': 'Ideal para começar',
  'Best value per film': 'Melhor valor por filme',
  'on Nano Banana': 'no Nano Banana',
  'Every video engine incl. MiniMax H3': 'Todos os motores de vídeo, incl. MiniMax H3',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'MP4 sem marca d’água · 100 projetos · 90 dias de armazenamento',
  ', finished': ', finalizado',
  '— every engine unlocked': '— todos os motores liberados',
  '· voice + karaoke captions + score': '· voz + legendas karaokê + trilha',
  '500 projects · forever storage': '500 projetos · armazenamento para sempre',
  'Cancel anytime — 7-day money-back': 'Cancele quando quiser — 7 dias de garantia',
  'films on Omni Flash': 'filmes no Omni Flash',
  '· 2 free HD enhances / month': '· 2 melhorias HD grátis / mês',
  'Unlimited projects · forever storage': 'Projetos ilimitados · armazenamento para sempre',
  'Everything in Creator': 'Tudo do Creator',
  'Calculate your cost per Short →': 'Calcule seu custo por Short →',
  'How much do Shorts pay? →': 'Quanto pagam os Shorts? →',
  'Highest-RPM niches →': 'Nichos de maior RPM →',
  'read the full review →': 'leia a análise completa →',
  'a single line is enough — or paste a full script': 'uma linha basta — ou cole um roteiro completo',
  '1080×1920 · Full HD master': '1080×1920 · master em Full HD',
  'Every film is delivered as a 1080×1920 Full HD master (engines render natively at 720–768p and are mastered up). For maximum sharpness, run ✨HD Enhance on the finished film.': 'Todo filme é entregue como master 1080×1920 Full HD (os motores renderizam nativamente em 720–768p e são masterizados para cima). Para nitidez máxima, rode o ✨HD Enhance no filme pronto.',
  'Your idea first. Review the settings, then generate.': 'Sua ideia primeiro. Revise as configurações e depois gere.',
  '📷 Photo': '📷 Foto',
  '🖼️ Upload a different photo': '🖼️ Enviar outra foto',
  '🎙️ Generating…': '🎙️ Gerando…',
  '🎙️ Cloning the voice…': '🎙️ Clonando a voz…',
  '🎙️ Upload a different sample': '🎙️ Enviar outra amostra',
  '⏹ Stop & clone': '⏹ Parar e clonar',
  '🎭 Generate my avatar video': '🎭 Gerar meu vídeo com avatar',
  'Continue exactly where ChatGPT stopped.': 'Continue exatamente de onde o ChatGPT parou.',
  '✨ Let AI structure it': '✨ Deixar a IA estruturar',
  'Optional settings': 'Configurações opcionais',
  'optional — a pre-tested move added to your prompt': 'opcional — um movimento pré-testado adicionado ao seu prompt',
  'Reference image': 'Imagem de referência',
  '🖼️ Start your video from an image — coming soon': '🖼️ Comece seu vídeo a partir de uma imagem — em breve',
  'Estimated cost': 'Custo estimado',
  'Your credits buy': 'Seus créditos compram',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'Voz, legendas karaokê e trilha incluídas. Se uma renderização falhar, seus créditos voltam na hora.',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'Mesmo tema, gancho e desfecho novos — a ideia já vem escrita.',
  'Build next episode →': 'Criar o próximo episódio →',
  'Episode 2 →': 'Episódio 2 →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'Apresentador IA que fala, a partir de uma foto — sincronia labial, estúdio próprio',
  'Your face. Your script.': 'Seu rosto. Seu roteiro.',
  'Everything you need to make yourself speak — nothing you don’t.': 'Tudo o que você precisa para se fazer falar — nada do que não precisa.',
  'BEST MOTION': 'MELHOR MOVIMENTO',
  '1.5 · Realism': '1.5 · Realismo',
  '🎬 Put me in a scene': '🎬 Me coloque numa cena',
  'use original photo': 'usar a foto original',
  '✍️ Say exactly this — word for word': '✍️ Diga exatamente isto — palavra por palavra',
  '✨ Expand into a full Short script (45–60s)': '✨ Expandir para um roteiro de Short completo (45–60s)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 Modo anúncio de produto — venda um produto no estilo UGC',
  'Free — fills the script box above, then generate with your presenter.': 'Grátis — preenche a caixa de roteiro acima; depois gere com o seu apresentador.',
  '2.5 · Speak in your own voice': '2.5 · Fale com a sua própria voz',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ Voz clonada — a narração vai falar com esta voz.',
  'use a default voice': 'usar uma voz padrão',
  '🎬 Full video — face the whole time': '🎬 Vídeo completo — rosto o tempo todo',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 Apresentador IA — rápido e natural · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro — qualidade de foto premium · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 Body Motion — tronco, mãos e gestos · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ Clássico — talking head · 110 cr',
  'you have': 'você tem',
  'to create your avatar video.': 'para criar seu vídeo com avatar.',
  '5 · Gesture clips — transparent background': '5 · Clipes de gestos — fundo transparente',
  'auto-refunded if it fails': 'reembolso automático se falhar',
  '⬇️ Download transparent WebM': '⬇️ Baixar WebM transparente',
  '⬇️ Original MP4 (with background)': '⬇️ MP4 original (com fundo)',
  'Pick a face to preview': 'Escolha um rosto para pré-visualizar',
  '↺ Make another': '↺ Fazer outro',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'Pessoas, pets, produtos, fotos antigas de família — envie uma foto ou cole um link público de imagem e veja ela se mexer.',
  'The photo': 'A foto',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': 'JPG/PNG de até 8 MB. Links públicos são baixados e validados com segurança no nosso servidor.',
  'sign in': 'entrar',
  'Kineo will fetch and validate it on the server when you animate.': 'A Kineo vai buscar e validar no servidor quando você animar.',
  'Upload a photo to preview': 'Envie uma foto para pré-visualizar',
  '🖼️ Upload a photo': '🖼️ Enviar uma foto',
  '✨ Bring it to life': '✨ Dar vida',
  'Uploading your photo…': 'Enviando sua foto…',
  'Bringing your photo to life… (1–3 min)': 'Dando vida à sua foto… (1–3 min)',
  'Alive!': 'Viva!',
  '🌬️ Subtle & real': '🌬️ Sutil e real',
  '😊 Person comes alive': '😊 A pessoa ganha vida',
  'Type your idea first': 'Digite sua ideia primeiro',
  '📖 True Story': '📖 História real',
  'Paste your ChatGPT script': 'Cole seu roteiro do ChatGPT',
  'First Short complete': 'Primeiro Short concluído',
  'Keep your show moving': 'Mantenha seu programa em movimento',
  'Cheapest way to see your idea as a film': 'O jeito mais barato de ver sua ideia virar filme',
  'Slow Dolly-In': 'Dolly-in lento',
  'FPV Drone': 'Drone FPV',
  'Macro Detail': 'Detalhe macro',
  'Sharing & creator options': 'Compartilhamento e opções de criador',
  'We couldn’t load your videos right now': 'Não conseguimos carregar seus vídeos agora',
  'Your videos and credits are safe — this is a temporary read hiccup, not a lost library.': 'Seus vídeos e créditos estão a salvo — é uma falha temporária de leitura, não uma biblioteca perdida.',
  '⚡ Generate Video': '⚡ Gerar vídeo',
  'Prefer clean exports now? Starter includes': 'Prefere exportações limpas agora? O Starter inclui',
  'credits each month for': 'créditos por mês por',
  'Your existing files stay available. Starter applies to new exports after checkout.': 'Seus arquivos atuais continuam disponíveis. O Starter vale para novas exportações após o checkout.',
  'Build Next Episode First': 'Criar o próximo episódio primeiro',
  'Video unavailable': 'Vídeo indisponível',
  'Free MP4 includes the Kineo watermark': 'O MP4 grátis inclui a marca d’água da Kineo',
  'Free distribution · latest Short': 'Distribuição grátis · último Short',
  'Send it to one person for feedback': 'Envie para uma pessoa pedir feedback',
  'Copy a public watch page for your finished video. Your friend can watch it without logging in, then use “Make one like this” if the idea inspires them.': 'Copie uma página pública de exibição do seu vídeo pronto. Seu amigo assiste sem fazer login e depois usa “Fazer um assim” se a ideia inspirar.',
  'Public watch links are temporarily paused': 'Os links públicos de exibição estão temporariamente pausados',
  'Your video stays in your account. Download the MP4 if you want to send it directly; Kineo will not publish a public page without an explicit visibility choice.': 'Seu vídeo fica na sua conta. Baixe o MP4 se quiser enviar diretamente; a Kineo não publica uma página pública sem uma escolha explícita de visibilidade.',
  'Loading…': 'Carregando…',
  'For new videos ·': 'Para novos vídeos ·',
  'Published it?': 'Publicou?',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'Nítida, de frente, uma pessoa só. Para movimento do corpo, use uma foto da cintura para cima ou de corpo inteiro com as duas mãos visíveis. Barras pretas são removidas automaticamente.',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'Melhor resultado profissional: envie um clipe vertical de 5–20s fazendo os gestos reais que você quer, com duração parecida com a do roteiro. O Sync-3 substitui a fala preservando o rosto e o movimento reais. MP4/MOV de até 40 MB.',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'Confirmo que tenho o direito de usar a imagem desta pessoa e consinto que ela seja animada por IA.',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': 'Envie uma amostra de voz clara de ~30-60s (uma pessoa falando, pouco ruído de fundo) e a narração será falada com essa voz. Use apenas uma voz que você tem o direito de usar.',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'Vídeos palavra por palavra mostram seu rosto o tempo todo (são curtos — não precisam de b-roll).',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'Vídeos de realismo máximo e de cena construída mantêm o apresentador na tela durante toda a narração.',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ Abertura com gancho — você abre, o b-roll conta a história',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'Clipes curtos do seu apresentador acenando, apontando, apresentando — entregues em WebM com fundo transparente DE VERDADE. Jogue direto no Storyline, Premiere, CapCut ou em qualquer slide. Sem chroma key, sem recorte.',
  'Cinematic film — 9-image consistency': 'Filme cinematográfico — consistência de 9 imagens',
  '#1-ranked video model — Aug 2026 arena': 'Modelo de vídeo nº 1 do ranking — arena de ago 2026',
  'Cinematic motion and camera work': 'Movimento e trabalho de câmera cinematográficos',
  'Shorts money & growth': 'Dinheiro e crescimento com Shorts',
  'Compare Kineo with 27 AI video tools →': 'Compare a Kineo com 27 ferramentas de vídeo IA →',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'Apresentadores que falam, personagens reutilizáveis, clipes transparentes, anúncios de produto — e tudo para achar e surfar uma tendência.',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'Uma foto + seu roteiro — um vídeo falado com sincronia labial de estúdio, estilo HeyGen.',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'Salve um personagem uma vez — exatamente o mesmo rosto em todo vídeo e thumbnail que você fizer.',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'Gestos de apresentador — acenar, apontar, apresentar — em WebM com fundo transparente de verdade.',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'Cole qualquer produto — receba um anúncio de 15-30s no estilo criador, roteirizado e narrado para você.',
  'Bring any still photo to life as a moving, postable video.': 'Dê vida a qualquer foto parada como um vídeo em movimento, pronto para publicar.',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'Thumbnails que atraem cliques no estilo dos maiores canais — a partir de um prompt.',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'Cada nicho abaixo tem sua própria página de geração, prompts ajustados e exemplos reais.',
  'Is the video really mine to post?': 'O vídeo é mesmo meu para publicar?',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'Os planos pagos liberam o MP4 limpo, sem marca d’água, para YouTube, TikTok ou Reels.',
  'Do I need any editing skills?': 'Preciso saber editar?',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'Não. Você digita uma ideia e a IA escreve o roteiro, grava a voz, encontra as imagens e adiciona as legendas.',
  'Is there a watermark?': 'Tem marca d’água?',
  'Paid plans export clean, watermark-free MP4s.': 'Os planos pagos exportam MP4 limpo, sem marca d’água.',
  'Can Kineo also generate images and voiceovers?': 'A Kineo também gera imagens e narrações?',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'Sim — a Kineo inclui um estúdio de imagens IA (6 motores, incluindo FLUX, Seedream e Nano Banana Pro, a partir de 1 crédito por imagem) e um estúdio de voz com 4 motores de texto para fala (a partir de 1 crédito por 1000 caracteres). Tudo o que você cria fica na sua Biblioteca.',
  'Can I make my videos sharper?': 'Posso deixar meus vídeos mais nítidos?',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'Todo vídeo tem uma opção de melhoria em um clique, com a restauração de filme da Topaz — remove artefatos de compressão, recupera detalhes e adiciona um grão cinematográfico fino. 10 créditos por vídeo; o plano Studio inclui 2 melhorias grátis por mês.',
  'Can I use my own script?': 'Posso usar meu próprio roteiro?',
  'What if a generation fails?': 'E se uma geração falhar?',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'Seus créditos voltam automaticamente no momento em que uma renderização falha — sem ticket de suporte, sem espera. Você só paga pelos vídeos que realmente recebe.',
  'Can I cancel anytime?': 'Posso cancelar quando quiser?',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'Quando quiser, em um clique. Os planos são mensais e seus créditos renovam todo mês.',
  'Can I run a whole channel with the same host?': 'Posso tocar um canal inteiro com o mesmo apresentador?',
  'Can I monetize the videos?': 'Posso monetizar os vídeos?',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'Sim. Todo vídeo é seu para guardar, publicar e monetizar — inclusive no Programa de Parcerias do YouTube, no TikTok e no Reels. Sem licença extra.',
  'Can I use the videos commercially, or for client work?': 'Posso usar os vídeos comercialmente, ou em trabalhos para clientes?',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'Sim. Nossos termos permitem usar a Kineo para fins pessoais ou comerciais lícitos e confirmam que você mantém a propriedade dos vídeos que gera, então pode publicá-los, monetizá-los e entregá-los a um cliente como parte do seu próprio serviço pago. Sem licença extra, sem royalty por vídeo. Dois limites vêm dos mesmos termos: você não pode revender ou redistribuir a Kineo em si, e os clipes de banco dentro de uma renderização são licenciados para uso no seu vídeo final, não para reenvio como footage avulso. Os planos pagos exportam o MP4 limpo, sem marca d’água.',
  'How long does one video take?': 'Quanto tempo leva um vídeo?',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'O Modo Fast costuma terminar em 3–7 minutos. Vídeos gerados por IA e cinematográficos levam um pouco mais, porque cada cena é gerada antes de o MP4 final ser composto.',
  'How much does Kineo cost?': 'Quanto custa a Kineo?',
  'Kineo has three monthly plans: Starter at $': 'A Kineo tem três planos mensais: Starter a $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'créditos. Os créditos são gastos por vídeo, e quanto um vídeo custa depende do motor escolhido, então uma renderização Fast e um filme cinematográfico saem do mesmo saldo a taxas bem diferentes.',
  'Which AI video engines can I use in Kineo?': 'Quais motores de vídeo IA posso usar na Kineo?',
  ', behind one interface and one balance:': ', atrás de uma única interface e um único saldo:',
  'What is the best AI video generator for faceless YouTube channels?': 'Qual é o melhor gerador de vídeo IA para canais faceless no YouTube?',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'Sim. Usuários gratuitos que nunca pagaram podem baixar, compartilhar e publicar o MP4 com marca d’água.',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'Os filmes do teste levam uma marca d’água pequena — você pode baixar, compartilhar e publicar o MP4. Depois do teste, o vídeo Fast grátis leva marca d’água.',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'Downloads grátis levam marca d’água; os planos pagos liberam o MP4 limpo.',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'Downloads do teste levam marca d’água, assim como o vídeo Fast grátis depois do teste, e os planos pagos sempre exportam limpo.',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'O acesso gratuito dá a novos usuários até 3 vídeos Fast com marca d’água a cada 24 horas, sem cartão. Você pode baixar e compartilhar.',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'Crie, baixe e compartilhe até 3 vídeos Fast com marca d’água a cada 24h, sem cartão.',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'Crie, assista, baixe e compartilhe até 3 vídeos Fast com marca d’água a cada 24h — sem cartão.',
  'create, watch, download and share up to 3 Fast videos every 24h': 'crie, assista, baixe e compartilhe até 3 vídeos Fast a cada 24h',
  '— no card, watermark included.': '— sem cartão, com marca d’água.',
  'AI image generator — 6 engines': 'Gerador de imagens IA — 6 motores',
  'AI voice generator (text to speech)': 'Gerador de voz IA (texto para fala)',
  'AI video upscaler & enhancer': 'Upscaler e melhorador de vídeo IA',
  'Trending Shorts ideas today': 'Ideias de Shorts em alta hoje',
  'AI Avatar video — your face, any script': 'Vídeo com avatar IA — seu rosto, qualquer roteiro',
  'Kineo facts & numbers (citable)': 'Fatos e números da Kineo (citáveis)',
  'Free AI Shorts generator': 'Gerador de Shorts IA grátis',
  'YouTube Shorts from a topic': 'Shorts do YouTube a partir de um tema',
  'ChatGPT script to YouTube Short': 'Roteiro do ChatGPT para Short do YouTube',
  'Shorts without filming': 'Shorts sem filmar',
  'Faceless niche picker': 'Seletor de nicho faceless',
  'State of AI Shorts 2026': 'Estado dos Shorts IA 2026',
  'AI Shorts for agencies & client work': 'Shorts IA para agências e trabalhos para clientes',
  'Trust Center — privacy, payments & ownership': 'Central de confiança — privacidade, pagamentos e propriedade',
  'Affiliate program - 30% recurring': 'Programa de afiliados - 30% recorrente',
  'Free AI Shorts by niche': 'Shorts IA grátis por nicho',
  'Free script generator': 'Gerador de roteiro grátis',
  'Product video ad script': 'Roteiro de anúncio de produto em vídeo',
  'Client video brief generator': 'Gerador de briefing de vídeo para clientes',
  'Free hook generator': 'Gerador de ganchos grátis',
  'Shorts script timer': 'Cronômetro de roteiro para Shorts',
  'Shorts money calculator': 'Calculadora de ganhos com Shorts',
  'How much do Shorts pay?': 'Quanto pagam os Shorts?',
  'Best AI Shorts generators': 'Melhores geradores de Shorts IA',
  'TikTok vs Shorts: which pays more?': 'TikTok vs Shorts: qual paga mais?',
  'All comparisons': 'Todas as comparações',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · Todos os direitos reservados',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'Depende de você querer imagens de banco montadas ou imagens geradas. Ferramentas como InVideo e AutoShorts cortam clipes de banco sobre o seu roteiro, o que é mais barato e serve para vídeos de tópicos falados. A Kineo gera as imagens com modelos como Veo 3.1 e Kling 3, mantém sua narração palavra por palavra em vez de reescrevê-la, e mira 60 segundos ou mais para o vídeo se qualificar no TikTok Creator Rewards. Se o seu canal vive de visuais que ninguém mais tem, a geração vence; se vive de volume, o banco é mais barato.',
  'Paste the complete script from ChatGPT here…': 'Cole aqui o roteiro completo do ChatGPT…',
  'Paste the idea from ChatGPT here…': 'Cole aqui a ideia do ChatGPT…',
  'What’s your video about? One idea in — a finished film out: voiced, scored and captioned.': 'Sobre o que é o seu vídeo? Uma ideia entra — um filme pronto sai: narrado, com trilha e legendado.',
  'Settings and generation': 'Configurações e geração',
  'Search your videos…': 'Buscar nos seus vídeos…',
  'Search your audio…': 'Buscar no seu áudio…',
  'Search your images by engine': 'Buscar suas imagens por motor',
  'No playable videos in your library yet. Check your latest project above.': 'Ainda não há vídeos reproduzíveis na sua biblioteca. Veja seu projeto mais recente acima.',
  'Make a finished Short →': 'Fazer um Short pronto →',
  'Video Editing & Creator Tools': 'Edição de vídeo e ferramentas para criadores',
  'Trim, resize, change speed, mute or add text. Edit a file you already have, right in your browser. Your script and planning tools are still here below.': 'Corte, redimensione, mude a velocidade, silencie ou adicione texto. Edite um arquivo que você já tem, direto no navegador. Suas ferramentas de roteiro e planejamento continuam aqui embaixo.',
  '5 local editing tools': '5 ferramentas de edição locais',
  'No generation credits to edit': 'Editar não gasta créditos de geração',
  'Edit video': 'Editar vídeo',
  'Files up to 100 MB and 3 minutes. Local, real-time export up to 1280 px on the long edge. MP4 or WebM depending on your browser; downloads are not saved to My Videos.': 'Arquivos de até 100 MB e 3 minutos. Exportação local em tempo real de até 1280 px no lado maior. MP4 ou WebM conforme o navegador; os downloads não são salvos em Meus vídeos.',
  'Video Trimmer': 'Cortador de vídeo',
  'Cut the beginning or end and keep only the clip you need.': 'Corte o início ou o fim e fique só com o trecho que precisa.',
  'Video Resizer': 'Redimensionador de vídeo',
  'Go vertical, square or wide. Fit the frame or crop to fill.': 'Vertical, quadrado ou widescreen. Ajuste ao quadro ou corte para preencher.',
  'Video Speed Changer': 'Alterador de velocidade',
  'Slow it down or speed it up, from 0.5× to 2×.': 'Deixe mais lento ou mais rápido, de 0.5× a 2×.',
  'Remove Audio': 'Remover áudio',
  'Download a copy without the original audio.': 'Baixe uma cópia sem o áudio original.',
  'Add Text to Video': 'Adicionar texto ao vídeo',
  'Add a title or message that stays on screen. Not automatic subtitles.': 'Adicione um título ou mensagem que fica na tela. Não são legendas automáticas.',
  'No account · current Kineo plans': 'Sem conta · planos atuais da Kineo',
  'No account · fair-use limit': 'Sem conta · limite de uso justo',
  'No account · unlimited in browser': 'Sem conta · ilimitado no navegador',
  'Edit an existing video here. Create a new one with Kineo.': 'Edite um vídeo existente aqui. Crie um novo com a Kineo.',
  'Create an AI video →': 'Criar um vídeo IA →',
  'Edit your video, preview the changes, then export a copy.': 'Edite seu vídeo, veja as mudanças e exporte uma cópia.',
  'Video preview': 'Pré-visualização do vídeo',
  'Preview is silent. The download keeps audio unless Mute is selected.': 'A pré-visualização é sem som. O download mantém o áudio, a menos que Silenciar esteja marcado.',
  'Start with your video': 'Comece com o seu vídeo',
  'Choose a local file. It stays on this device.': 'Escolha um arquivo local. Ele fica neste dispositivo.',
  'Choose video file': 'Escolher arquivo de vídeo',
  'Video file': 'Arquivo de vídeo',
  'Video settings': 'Configurações do vídeo',
  'Aspect ratio': 'Proporção',
  'Playback speed': 'Velocidade de reprodução',
  'On-screen text (100 characters, 3 lines)': 'Texto na tela (100 caracteres, 3 linhas)',
  'Add a title or message': 'Adicione um título ou mensagem',
  'Export edited video': 'Exportar vídeo editado',
  'Export happens in real time. Keep this tab visible. Re-encoded at up to 1280 px on the long edge; format depends on your browser.': 'A exportação acontece em tempo real. Mantenha esta aba visível. Recodificado em até 1280 px no lado maior; o formato depende do navegador.',
  'Making a 4-second sample on your device…': 'Criando uma amostra de 4 segundos no seu dispositivo…',
  'Reading your file…': 'Lendo seu arquivo…',
  'Export result': 'Resultado da exportação',
  'Your edited video': 'Seu vídeo editado',
  'Local download only. This copy is not saved to My Videos.': 'Download apenas local. Esta cópia não é salva em Meus vídeos.',
  'Exported video': 'Vídeo exportado',
  'No upload. No generation credits. Your original is never overwritten.': 'Sem upload. Sem créditos de geração. Seu original nunca é sobrescrito.',
  'Up to 100 MB · 3 minutes · MP4/WebM input recommended. These are basic editing tools, not the CapCut app.': 'Até 100 MB · 3 minutos · entrada MP4/WebM recomendada. São ferramentas básicas de edição, não o app CapCut.',
  'Need a new video? Open Kineo Studio →': 'Precisa de um vídeo novo? Abra o Kineo Studio →',
  'This browser cannot export video here. Try the latest desktop Chrome or Edge.': 'Este navegador não consegue exportar vídeo aqui. Tente o Chrome ou o Edge mais recente no desktop.',
  'Choose a non-empty video file of up to 100 MB.': 'Escolha um arquivo de vídeo não vazio de até 100 MB.',
  'Use a playable clip of up to 3 minutes. Very large dimensions are not supported.': 'Use um clipe reproduzível de até 3 minutos. Dimensões muito grandes não são suportadas.',
  'Check the start and end: select at least 0.25 seconds within your clip.': 'Confira o início e o fim: selecione pelo menos 0.25 segundo dentro do clipe.',
  'Choose a speed between 0.5× and 2×.': 'Escolha uma velocidade entre 0.5× e 2×.',
  'Use up to 100 characters and 3 lines of text.': 'Use até 100 caracteres e 3 linhas de texto.',
  'Choose a supported aspect ratio, framing and text position.': 'Escolha uma proporção, enquadramento e posição de texto suportados.',
  'This file could not be decoded. Try an MP4 (H.264) or WebM file.': 'Não foi possível decodificar este arquivo. Tente um MP4 (H.264) ou WebM.',
  'Export stopped because this tab was hidden. Keep it open and visible, then export again. Your original is safe.': 'A exportação parou porque esta aba ficou oculta. Mantenha-a aberta e visível e exporte de novo. Seu original está a salvo.',
  'Export stopped making progress. Try a shorter clip or desktop Chrome. Your original is unchanged.': 'A exportação parou de avançar. Tente um clipe mais curto ou o Chrome no desktop. Seu original não mudou.',
  'Audio could not start. Try exporting again, or choose Mute video.': 'O áudio não pôde iniciar. Tente exportar de novo ou escolha Silenciar vídeo.',
  'The browser blocked playback. Try exporting again from this tab.': 'O navegador bloqueou a reprodução. Tente exportar de novo a partir desta aba.',
  'Cancelled. Your original file is unchanged.': 'Cancelado. Seu arquivo original não mudou.',
  'Could not finish this export. Try a shorter clip or another supported browser.': 'Não foi possível concluir esta exportação. Tente um clipe mais curto ou outro navegador suportado.',
  'The browser produced an incomplete file, so we did not offer it for download. Try again with this tab visible, or use desktop Chrome.': 'O navegador produziu um arquivo incompleto, por isso não oferecemos o download. Tente de novo com esta aba visível, ou use o Chrome no desktop.',
  'Create new video': 'Criar novo vídeo',
  'Your idea': 'Sua ideia',
  'Natural': 'Natural',
  'Working…': 'Trabalhando…',
  '🎲 Surprise me': '🎲 Me surpreenda',
  '📝 Use my script as is': '📝 Usar meu roteiro como está',
  'Camera preset': 'Preset de câmera',
  'Your latest videos': 'Seus vídeos mais recentes',
  'Presenter': 'Apresentador',
  '1 · Who’s talking': '1 · Quem fala',
  '🎭 your characters': '🎭 seus personagens',
  '🎯 Max realism — animate my real photo': '🎯 Realismo máximo — animar minha foto real',
  '✓ Scene ready — preview on the right.': '✓ Cena pronta — pré-visualização à direita.',
  '2 · What they say': '2 · O que dizem',
  '3 · How it looks': '3 · Como fica',
  'Motion': 'Movimento',
  '⬇ Download MP4': '⬇ Baixar MP4',
  'One photo. Suddenly alive.': 'Uma foto. De repente, viva.',
  'Cost per clip': 'Custo por clipe',
  '↺ Animate another': '↺ Animar outra',
  'Grow': 'Crescer',
  'Sending to the motion engine…': 'Enviando ao motor de movimento…',
  '📊 Facts': '📊 Fatos',
  'Turn it into episode 2': 'Transformar em episódio 2',
  'Start here': 'Comece aqui',
  'Engine': 'Motor',
  'Highly aesthetic, by xAI': 'Altamente estético, da xAI',
  'Google’s best image model': 'O melhor modelo de imagem do Google',
  'AI voiceover included': 'Narração IA incluída',
  '6 engines': '6 motores',
  'AI Presenter': 'Apresentador IA',
  'Lock a character →': 'Fixar um personagem →',
  'Make a clip →': 'Fazer um clipe →',
  'Make an ad →': 'Fazer um anúncio →',
  'Generate free →': 'Gerar grátis →',
  'Creating…': 'Criando…',
  'Describe your image first': 'Descreva sua imagem primeiro',
  'Type your script first': 'Digite seu roteiro primeiro',
  'From the founder': 'Do fundador',
  'Faceless video generator': 'Gerador de vídeo faceless',
  'Text to video Shorts': 'Shorts de texto para vídeo',
  'Cheapest AI Shorts maker': 'O criador de Shorts IA mais barato',
  'Faceless channel ideas (2026)': 'Ideias de canal faceless (2026)',
  'Shorts idea widget': 'Widget de ideias para Shorts',
  'Live case study: our channel on Autopilot': 'Estudo de caso ao vivo: nosso canal no Autopilot',
  'Free YouTube Shorts scripts': 'Roteiros grátis para Shorts do YouTube',
  'Comment to Short script': 'De comentário a roteiro de Short',
  'Business video content planner': 'Planejador de conteúdo em vídeo para empresas',
  'Real estate video maker': 'Criador de vídeos para imóveis',
  'Shorts title & hashtag generator': 'Gerador de título e hashtags para Shorts',
  'Free viral score': 'Pontuação viral grátis',
  'Make money clipping with AI': 'Ganhe dinheiro fazendo clipes com IA',
  'Shorts RPM by niche (2026)': 'RPM de Shorts por nicho (2026)',
  'Can you monetize AI videos?': 'Dá para monetizar vídeos feitos com IA?',
}
