// KINEO-INTERFACE-16-LINGUAS-2026-09-21 — interface em ru. Só copy autoral da interface: nunca prompt,
// título, resultado, nome de motor ou erro de API. Frase fora daqui cai em inglês (components/InterfaceLanguage.tsx).
// Gerado de scratchpad/tr-ru.js sobre o corpus vivo de frases (415); números e "Kineo" preservados por construção.
export const DICT: Record<string, string> = {
  'Videos for businesses': 'Видео для бизнеса',
  // KINEO-NAV-4-ITENS-2026-09-25 — rótulos do menu de 4 itens (decisão do fundador 24/09).
  'Create video': 'Создать видео',
  'For businesses': 'Для бизнеса',
  'More tools': 'Другие инструменты',
  'Ads': 'Реклама',
  'Log in': 'Войти',
  'More': 'Ещё',
  'Scripts': 'Сценарии',
  'Animate': 'Анимировать',
  'Examples': 'Примеры',
  'Pricing': 'Цены',
  'Library': 'Библиотека',
  'Generation failed': 'Генерация не удалась',
  'You can retry safely.': 'Можно спокойно попробовать ещё раз.',
  'This engine is not available on your account right now': 'Этот движок сейчас недоступен в вашем аккаунте',
  'Retrying the same engine will stop at this same place. Pick another engine to keep going.': 'Повтор на том же движке остановится в том же месте. Выберите другой движок, чтобы продолжить.',
  'The engine is cooling down after two refunded attempts': 'Движок остывает после двух возвращённых попыток',
  'Starting another one right now stops at this same place. Give it a few minutes.': 'Запуск ещё одной прямо сейчас остановится в том же месте. Подождите несколько минут.',
  'Starting another one right now stops at this same place. The button below unlocks by itself.': 'Запуск ещё одной прямо сейчас остановится в том же месте. Кнопка ниже разблокируется сама.',
  'We stopped waiting on this render instead of leaving you hanging': 'Мы перестали ждать этот рендер, чтобы не держать вас в подвешенном состоянии',
  'This one ran far longer than any video that finishes here. Starting again is worth it.': 'Этот шёл намного дольше любого видео, которое здесь завершается. Запустить заново стоит.',
  'The video engine is busy — this is on our side, not your idea': 'Видеодвижок занят — дело на нашей стороне, а не в вашей идее',
  'Nothing about your text is wrong. Trying again in a few minutes usually goes straight through.': 'С вашим текстом всё в порядке. Повтор через несколько минут обычно проходит с первого раза.',
  'Create Video': 'Создать видео',
  'Create a new video': 'Создать новое видео',
  'AI Avatar Studio': 'Студия AI-аватаров',
  'Viral Templates': 'Вирусные шаблоны',
  'Channel Builder': 'Конструктор канала',
  'Invite & Earn': 'Приглашай и зарабатывай',
  'Start free': 'Начать бесплатно',
  'Try 7 days for $1': 'Попробовать 7 дней за $1',
  'Pick a lane': 'Выберите путь',
  'All free tools': 'Все бесплатные инструменты',
  'Terms of Service': 'Условия использования',
  'Trust Center': 'Центр доверия',
  'Review & publish': 'Проверить и опубликовать',
  'Your image': 'Ваше изображение',
  'Cost per image': 'Стоимость за изображение',
  'No videos yet': 'Видео пока нет',
  'No audio yet': 'Аудио пока нет',
  '🎬 Studio — generate video': '🎬 Studio — создать видео',
  '🎨 Images — create image': '🎨 Изображения — создать изображение',
  '🎙 Audio — text to speech': '🎙 Аудио — текст в речь',
  'Type it. See it. Six image engines, one screen.': 'Напишите. Увидьте. Шесть движков изображений, один экран.',
  'Type it. Hear it. Four voice engines, one screen.': 'Напишите. Услышьте. Четыре голосовых движка, один экран.',
  'Everything you’ve created, in one place.': 'Всё, что вы создали, в одном месте.',
  'Add credits →': 'Добавить кредиты →',
  'Upscale any result to 2x for 1 credit.': 'Увеличьте любой результат в 2x за 1 кредит.',
  'We couldn’t load your images right now.': 'Не удалось загрузить ваши изображения прямо сейчас.',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'Ваши изображения и кредиты в безопасности — это лишь временный сбой чтения.',
  'We couldn’t load your audio right now.': 'Не удалось загрузить ваше аудио прямо сейчас.',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'Ваше аудио и кредиты в безопасности — это лишь временный сбой чтения.',
  'We couldn’t load part of your library right now.': 'Не удалось загрузить часть вашей библиотеки прямо сейчас.',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'Ваши видео и кредиты в безопасности — это лишь временный сбой чтения.',
  '↻ Try again': '↻ Попробовать снова',
  '⬇ Download': '⬇ Скачать',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': 'Понравился голос? Studio построит вокруг него весь фильм — визуал, субтитры и музыку.',
  'Open Studio →': 'Открыть Studio →',
  'open the Studio': 'откройте Studio',
  'Next episode →': 'Следующий эпизод →',
  'create your first image': 'создайте первое изображение',
  'generate your first voiceover': 'создайте первую озвучку',
  'Instant drafts': 'Мгновенные черновики',
  'Deep prompt understanding': 'Глубокое понимание промпта',
  'Perfect text rendering': 'Идеальный рендер текста',
  'Create Image': 'Создать изображение',
  'Click-magnet YouTube covers': 'Обложки YouTube, которые притягивают клики',
  'Bring any image to life': 'Оживите любое изображение',
  'Instant narration': 'Мгновенная озвучка',
  'Four voice engines': 'Четыре голосовых движка',
  'A face that speaks your script': 'Лицо, которое произносит ваш сценарий',
  'Every control, one screen': 'Все настройки, один экран',
  'Today’s trending topics': 'Темы в тренде сегодня',
  'Real renders, every engine': 'Реальные рендеры, каждый движок',
  'Type an idea — watch it become a film.': 'Напишите идею — смотрите, как она становится фильмом.',
  'Start with the full toolkit': 'Начните с полного набора инструментов',
  'Kineo’s own engine — 3–7 min': 'Собственный движок Kineo — 3–7 мин',
  'The workhorse AI video engine': 'Рабочая лошадка среди AI-видеодвижков',
  'Cinematic motion & camera': 'Кинематографичное движение и камера',
  'Film scenes, native voice & lip sync': 'Киносцены, родной голос и синхронизация губ',
  'Talking video from one photo': 'Говорящее видео из одного фото',
  'From idea to posted Short in 3 steps.': 'От идеи до опубликованного Short за 3 шага.',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'Без съёмки, без монтажа, без таймлайна. Напишите один раз — Kineo сделает остальное.',
  'Step 1': 'Шаг 1',
  'Kineo builds it': 'Kineo собирает',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'AI пишет сценарий, выстроенный под удержание, записывает озвучку, подбирает кадры и вшивает субтитры — готовое видео 9:16.',
  'Download & post': 'Скачайте и опубликуйте',
  'Why Kineo': 'Почему Kineo',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'Большинство инструментов перенарезают длинное видео, которое вы уже сняли. Kineo собирает его с нуля.',
  'See how to make Shorts without filming →': 'Как делать Shorts без съёмки →',
  'Generates the Short from just an idea': 'Создаёт Short из одной идеи',
  'Writes the script for you': 'Пишет сценарий за вас',
  'Finds and matches footage': 'Находит и подбирает кадры',
  'your upload': 'ваша загрузка',
  'AI image studio included': 'Студия AI-изображений включена',
  'Voice studio (text-to-speech)': 'Голосовая студия (текст в речь)',
  'One-click HD film enhance': 'HD-улучшение фильма в один клик',
  'One idea — or a whole toolkit.': 'Одна идея — или целый набор инструментов.',
  'Try AI Presenter →': 'Попробовать AI-ведущего →',
  'Transparent Clips': 'Прозрачные клипы',
  'UGC Product Ads': 'UGC-реклама товаров',
  'Animate a photo →': 'Оживить фото →',
  'Make a thumbnail →': 'Сделать превью →',
  'Free AI Shorts': 'Бесплатные AI Shorts',
  'Start with a niche that already works.': 'Начните с ниши, которая уже работает.',
  'Not sure? Take the quiz →': 'Не уверены? Пройдите тест →',
  'Pick your engine. Ship a Short today.': 'Выберите движок. Опубликуйте Short сегодня.',
  'Cancel anytime': 'Отмена в любой момент',
  'Generate image →': 'Создать изображение →',
  'Generate audio →': 'Создать аудио →',
  'Paid plans unlock clean MP4s.': 'Платные планы открывают чистые MP4.',
  'Best for starting out': 'Лучший для старта',
  'Best value per film': 'Лучшая цена за фильм',
  'on Nano Banana': 'на Nano Banana',
  'Every video engine incl. MiniMax H3': 'Все видеодвижки, включая MiniMax H3',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'MP4 без водяного знака · 100 проектов · хранение 90 дней',
  ', finished': ', готово',
  '— every engine unlocked': '— все движки открыты',
  '· voice + karaoke captions + score': '· голос + караоке-субтитры + музыка',
  '500 projects · forever storage': '500 проектов · хранение навсегда',
  'Cancel anytime — 7-day money-back': 'Отмена в любой момент — возврат денег 7 дней',
  'films on Omni Flash': 'фильмов на Omni Flash',
  '· 2 free HD enhances / month': '· 2 бесплатных HD-улучшения / месяц',
  'Unlimited projects · forever storage': 'Неограниченные проекты · хранение навсегда',
  'Everything in Creator': 'Всё из Creator',
  'Calculate your cost per Short →': 'Рассчитайте стоимость одного Short →',
  'How much do Shorts pay? →': 'Сколько платят за Shorts? →',
  'Highest-RPM niches →': 'Ниши с самым высоким RPM →',
  'read the full review →': 'читать полный обзор →',
  'a single line is enough — or paste a full script': 'достаточно одной строки — или вставьте полный сценарий',
  '1080×1920 · Full HD master': '1080×1920 · мастер Full HD',
  'Every film is delivered as a 1080×1920 Full HD master (engines render natively at 720–768p and are mastered up). For maximum sharpness, run ✨HD Enhance on the finished film.': 'Каждый фильм выдаётся как мастер 1080×1920 Full HD (движки рендерят нативно в 720–768p и мастерятся вверх). Для максимальной резкости запустите ✨HD Enhance на готовом фильме.',
  'Your idea first. Review the settings, then generate.': 'Сначала ваша идея. Проверьте настройки, затем создайте.',
  '📷 Photo': '📷 Фото',
  '🖼️ Upload a different photo': '🖼️ Загрузить другое фото',
  '🎙️ Generating…': '🎙️ Генерация…',
  '🎙️ Cloning the voice…': '🎙️ Клонирование голоса…',
  '🎙️ Upload a different sample': '🎙️ Загрузить другой образец',
  '⏹ Stop & clone': '⏹ Остановить и клонировать',
  '🎭 Generate my avatar video': '🎭 Создать моё видео с аватаром',
  'Continue exactly where ChatGPT stopped.': 'Продолжите ровно с того места, где остановился ChatGPT.',
  '✨ Let AI structure it': '✨ Пусть AI структурирует',
  'Optional settings': 'Необязательные настройки',
  'optional — a pre-tested move added to your prompt': 'необязательно — проверенное движение, добавленное к вашему промпту',
  'Reference image': 'Референсное изображение',
  '🖼️ Start your video from an image — coming soon': '🖼️ Начать видео с изображения — скоро',
  'Estimated cost': 'Ориентировочная стоимость',
  'Your credits buy': 'На ваши кредиты можно',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'Голос, караоке-субтитры и музыка включены. Если рендер не удастся, кредиты сразу вернутся.',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'Та же тема, новый хук и развязка — идея уже написана.',
  'Build next episode →': 'Собрать следующий эпизод →',
  'Episode 2 →': 'Эпизод 2 →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'Говорящий AI-ведущий из фото — с синхронизацией губ, в собственной студии',
  'Your face. Your script.': 'Ваше лицо. Ваш сценарий.',
  'Everything you need to make yourself speak — nothing you don’t.': 'Всё, что нужно, чтобы заговорить самому — и ничего лишнего.',
  'BEST MOTION': 'ЛУЧШЕЕ ДВИЖЕНИЕ',
  '1.5 · Realism': '1.5 · Реализм',
  '🎬 Put me in a scene': '🎬 Поместить меня в сцену',
  'use original photo': 'использовать исходное фото',
  '✍️ Say exactly this — word for word': '✍️ Сказать ровно это — слово в слово',
  '✨ Expand into a full Short script (45–60s)': '✨ Развернуть в полный сценарий Short (45–60 с)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 Режим рекламы товара — продать товар в стиле UGC',
  'Free — fills the script box above, then generate with your presenter.': 'Бесплатно — заполняет поле сценария выше, затем создайте с вашим ведущим.',
  '2.5 · Speak in your own voice': '2.5 · Говорите своим голосом',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ Голос клонирован — озвучка будет звучать этим голосом.',
  'use a default voice': 'использовать голос по умолчанию',
  '🎬 Full video — face the whole time': '🎬 Полное видео — лицо всё время',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 AI-ведущий — быстро и естественно · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro — премиальное качество фото · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 Body Motion — корпус, руки и жесты · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ Классика — говорящая голова · 110 cr',
  'you have': 'у вас',
  'to create your avatar video.': 'чтобы создать видео с аватаром.',
  '5 · Gesture clips — transparent background': '5 · Клипы с жестами — прозрачный фон',
  'auto-refunded if it fails': 'автоматический возврат при сбое',
  '⬇️ Download transparent WebM': '⬇️ Скачать прозрачный WebM',
  '⬇️ Original MP4 (with background)': '⬇️ Исходный MP4 (с фоном)',
  'Pick a face to preview': 'Выберите лицо для предпросмотра',
  '↺ Make another': '↺ Сделать ещё',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'Люди, питомцы, товары, старые семейные снимки — загрузите фото или вставьте публичную ссылку на изображение и смотрите, как оно движется.',
  'The photo': 'Фото',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': 'JPG/PNG до 8 МБ. Публичные ссылки безопасно скачиваются и проверяются на нашем сервере.',
  'sign in': 'войти',
  'Kineo will fetch and validate it on the server when you animate.': 'Kineo получит и проверит его на сервере, когда вы запустите анимацию.',
  'Upload a photo to preview': 'Загрузите фото для предпросмотра',
  '🖼️ Upload a photo': '🖼️ Загрузить фото',
  '✨ Bring it to life': '✨ Оживить',
  'Uploading your photo…': 'Загрузка вашего фото…',
  'Bringing your photo to life… (1–3 min)': 'Оживляем ваше фото… (1–3 мин)',
  'Alive!': 'Ожило!',
  '🌬️ Subtle & real': '🌬️ Тонко и естественно',
  '😊 Person comes alive': '😊 Человек оживает',
  'Type your idea first': 'Сначала напишите идею',
  '📖 True Story': '📖 Реальная история',
  'Paste your ChatGPT script': 'Вставьте сценарий из ChatGPT',
  'First Short complete': 'Первый Short готов',
  'Keep your show moving': 'Держите своё шоу в движении',
  'Cheapest way to see your idea as a film': 'Самый дешёвый способ увидеть свою идею в виде фильма',
  'Slow Dolly-In': 'Медленный наезд',
  'FPV Drone': 'FPV-дрон',
  'Macro Detail': 'Макродеталь',
  'Sharing & creator options': 'Шеринг и опции для авторов',
  'We couldn’t load your videos right now': 'Не удалось загрузить ваши видео прямо сейчас',
  'Your videos and credits are safe — this is a temporary read hiccup, not a lost library.': 'Ваши видео и кредиты в безопасности — это временный сбой чтения, а не потерянная библиотека.',
  '⚡ Generate Video': '⚡ Создать видео',
  'Prefer clean exports now? Starter includes': 'Хотите чистые экспорты уже сейчас? Starter включает',
  'credits each month for': 'кредитов в месяц за',
  'Your existing files stay available. Starter applies to new exports after checkout.': 'Ваши текущие файлы остаются доступными. Starter действует для новых экспортов после оплаты.',
  'Build Next Episode First': 'Сначала собрать следующий эпизод',
  'Video unavailable': 'Видео недоступно',
  'Free MP4 includes the Kineo watermark': 'Бесплатный MP4 содержит водяной знак Kineo',
  'Free distribution · latest Short': 'Бесплатное распространение · последний Short',
  'Send it to one person for feedback': 'Отправьте одному человеку за отзывом',
  'Copy a public watch page for your finished video. Your friend can watch it without logging in, then use “Make one like this” if the idea inspires them.': 'Скопируйте публичную страницу просмотра готового видео. Друг посмотрит без входа, а затем может нажать «Сделать такое же», если идея вдохновит.',
  'Public watch links are temporarily paused': 'Публичные ссылки на просмотр временно приостановлены',
  'Your video stays in your account. Download the MP4 if you want to send it directly; Kineo will not publish a public page without an explicit visibility choice.': 'Видео остаётся в вашем аккаунте. Скачайте MP4, если хотите отправить напрямую; Kineo не публикует публичную страницу без явного выбора видимости.',
  'Loading…': 'Загрузка…',
  'For new videos ·': 'Для новых видео ·',
  'Published it?': 'Опубликовали?',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'Чётко, анфас, один человек. Для движения тела используйте фото по пояс или в полный рост с обеими видимыми руками. Чёрные полосы убираются автоматически.',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'Лучший профессиональный результат: загрузите вертикальный клип 5–20 с с нужными реальными жестами, примерно равный по длине сценарию. Sync-3 заменяет речь, сохраняя реальное лицо и движения. MP4/MOV до 40 МБ.',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'Подтверждаю, что имею право использовать изображение этого человека, и согласен на его анимацию с помощью AI.',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': 'Загрузите чистый образец голоса ~30-60 с (один говорящий, мало фонового шума), и озвучка будет звучать этим голосом. Используйте только голос, на который у вас есть права.',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'Видео слово в слово показывают ваше лицо всё время (они короткие — b-roll не нужен).',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'Видео с максимальным реализмом и построенной сценой держат ведущего в кадре всю озвучку.',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ Вступление-хук — вы открываете, историю рассказывает b-roll',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'Короткие клипы вашего ведущего: машет, указывает, презентует — в формате WebM с НАСТОЯЩИМ прозрачным фоном. Вставляйте прямо в Storyline, Premiere, CapCut или любой слайд. Без хромакея, без кеинга.',
  'Cinematic film — 9-image consistency': 'Кинематографичный фильм — согласованность 9 кадров',
  '#1-ranked video model — Aug 2026 arena': 'Видеомодель № 1 в рейтинге — арена, авг 2026',
  'Cinematic motion and camera work': 'Кинематографичное движение и работа камеры',
  'Shorts money & growth': 'Деньги и рост на Shorts',
  'Compare Kineo with 27 AI video tools →': 'Сравните Kineo с 27 AI-видеоинструментами →',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'Говорящие ведущие, переиспользуемые персонажи, прозрачные клипы, реклама товаров — плюс всё, чтобы найти тренд и оседлать его.',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'Одно фото + ваш сценарий — говорящее видео со студийной синхронизацией губ, в стиле HeyGen.',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'Сохраните персонажа один раз — точно то же лицо в каждом видео и превью.',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'Жесты ведущего — помахать, указать, представить — в WebM с настоящим прозрачным фоном.',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'Вставьте любой товар — получите рекламу 15-30 с в стиле блогера, со сценарием и озвучкой.',
  'Bring any still photo to life as a moving, postable video.': 'Оживите любую статичную фотографию как движущееся видео, готовое к публикации.',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'Кликабельные превью в стиле крупнейших каналов — из одного промпта.',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'У каждой ниши ниже есть своя страница генератора, настроенные промпты и реальные примеры.',
  'Is the video really mine to post?': 'Видео действительно моё, и я могу его публиковать?',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'Платные планы открывают чистый MP4 без водяного знака для YouTube, TikTok или Reels.',
  'Do I need any editing skills?': 'Нужны ли навыки монтажа?',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'Нет. Вы пишете одну идею, а AI пишет сценарий, записывает голос, находит кадры и добавляет субтитры.',
  'Is there a watermark?': 'Есть ли водяной знак?',
  'Paid plans export clean, watermark-free MP4s.': 'Платные планы экспортируют чистые MP4 без водяного знака.',
  'Can Kineo also generate images and voiceovers?': 'Kineo также создаёт изображения и озвучку?',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'Да — в Kineo есть студия AI-изображений (6 движков, включая FLUX, Seedream и Nano Banana Pro, от 1 кредита за изображение) и голосовая студия с 4 движками текст-в-речь (от 1 кредита за 1000 символов). Всё, что вы создаёте, живёт в вашей Библиотеке.',
  'Can I make my videos sharper?': 'Можно сделать видео резче?',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'У каждого видео есть улучшение в один клик на базе реставрации плёнки Topaz — убирает артефакты сжатия, восстанавливает детали и добавляет тонкое киношное зерно. 10 кредитов за видео; план Studio включает 2 бесплатных улучшения в месяц.',
  'Can I use my own script?': 'Можно использовать свой сценарий?',
  'What if a generation fails?': 'А если генерация не удастся?',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'Кредиты возвращаются автоматически в момент сбоя рендера — без тикета, без ожидания. Вы платите только за видео, которые действительно получаете.',
  'Can I cancel anytime?': 'Можно отменить в любой момент?',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'В любой момент, в один клик. Планы помесячные, кредиты обновляются каждый месяц.',
  'Can I run a whole channel with the same host?': 'Можно вести целый канал с одним и тем же ведущим?',
  'Can I monetize the videos?': 'Можно монетизировать видео?',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'Да. Каждое видео ваше — храните, публикуйте и монетизируйте, включая партнёрскую программу YouTube, TikTok и Reels. Дополнительная лицензия не нужна.',
  'Can I use the videos commercially, or for client work?': 'Можно использовать видео в коммерческих целях или для клиентов?',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'Да. Наши условия позволяют использовать Kineo в законных личных или коммерческих целях и подтверждают, что вы сохраняете право собственности на созданные видео, поэтому можете их публиковать, монетизировать и передавать клиенту в рамках собственной платной услуги. Без дополнительной лицензии и роялти за видео. Из тех же условий следуют два ограничения: нельзя перепродавать или распространять сам Kineo, а стоковые клипы внутри рендера лицензированы для использования в вашем готовом видео, а не для повторной загрузки как самостоятельный сток. Платные планы экспортируют чистый MP4 без водяного знака.',
  'How long does one video take?': 'Сколько времени занимает одно видео?',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'Режим Fast обычно завершается за 3–7 минут. AI-сгенерированные и кинематографичные видео занимают чуть больше, потому что каждая сцена генерируется до сборки финального MP4.',
  'How much does Kineo cost?': 'Сколько стоит Kineo?',
  'Kineo has three monthly plans: Starter at $': 'У Kineo три месячных плана: Starter за $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'кредитов. Кредиты тратятся на каждое видео, а стоимость видео зависит от выбранного движка, поэтому рендер Fast и кинематографичный фильм списываются с одного баланса по очень разным ставкам.',
  'Which AI video engines can I use in Kineo?': 'Какие AI-видеодвижки можно использовать в Kineo?',
  ', behind one interface and one balance:': ', за одним интерфейсом и одним балансом:',
  'What is the best AI video generator for faceless YouTube channels?': 'Какой AI-видеогенератор лучший для безликих YouTube-каналов?',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'Да. Бесплатные пользователи, никогда не платившие, могут скачивать, делиться и публиковать MP4 с водяным знаком.',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'Пробные фильмы несут небольшой водяной знак — MP4 можно скачать, отправить и опубликовать. После пробного периода бесплатное видео Fast несёт водяной знак.',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'Бесплатные загрузки несут водяной знак; платные планы открывают чистый MP4.',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'Пробные загрузки несут водяной знак, как и бесплатное видео Fast после пробного периода, а платные планы всегда экспортируют чисто.',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'Бесплатный доступ даёт новым пользователям до 3 видео Fast с водяным знаком каждые 24 часа, без карты. Их можно скачивать и отправлять.',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'Создавайте, скачивайте и делитесь до 3 видео Fast с водяным знаком каждые 24 ч, без карты.',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'Создавайте, смотрите, скачивайте и делитесь до 3 видео Fast с водяным знаком каждые 24 ч — без карты.',
  'create, watch, download and share up to 3 Fast videos every 24h': 'создавайте, смотрите, скачивайте и делитесь до 3 видео Fast каждые 24 ч',
  '— no card, watermark included.': '— без карты, с водяным знаком.',
  'AI image generator — 6 engines': 'AI-генератор изображений — 6 движков',
  'AI voice generator (text to speech)': 'AI-генератор голоса (текст в речь)',
  'AI video upscaler & enhancer': 'AI-апскейлер и улучшитель видео',
  'Trending Shorts ideas today': 'Идеи для Shorts в тренде сегодня',
  'AI Avatar video — your face, any script': 'Видео с AI-аватаром — ваше лицо, любой сценарий',
  'Kineo facts & numbers (citable)': 'Факты и цифры Kineo (можно цитировать)',
  'Free AI Shorts generator': 'Бесплатный генератор AI Shorts',
  'YouTube Shorts from a topic': 'YouTube Shorts из темы',
  'ChatGPT script to YouTube Short': 'Сценарий ChatGPT в YouTube Short',
  'Shorts without filming': 'Shorts без съёмки',
  'Faceless niche picker': 'Подбор безликой ниши',
  'State of AI Shorts 2026': 'Состояние AI Shorts 2026',
  'AI Shorts for agencies & client work': 'AI Shorts для агентств и клиентов',
  'Trust Center — privacy, payments & ownership': 'Центр доверия — приватность, платежи и права',
  'Affiliate program - 30% recurring': 'Партнёрская программа - 30% регулярно',
  'Free AI Shorts by niche': 'Бесплатные AI Shorts по нишам',
  'Free script generator': 'Бесплатный генератор сценариев',
  'Product video ad script': 'Сценарий видеорекламы товара',
  'Client video brief generator': 'Генератор видеобрифа для клиента',
  'Free hook generator': 'Бесплатный генератор хуков',
  'Shorts script timer': 'Таймер сценария Shorts',
  'Shorts money calculator': 'Калькулятор дохода с Shorts',
  'How much do Shorts pay?': 'Сколько платят за Shorts?',
  'Best AI Shorts generators': 'Лучшие генераторы AI Shorts',
  'TikTok vs Shorts: which pays more?': 'TikTok vs Shorts: где платят больше?',
  'All comparisons': 'Все сравнения',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · Все права защищены',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'Зависит от того, нужны ли вам собранные стоковые кадры или сгенерированные. Инструменты вроде InVideo и AutoShorts нарезают стоковые клипы под ваш сценарий — это дешевле и подходит для видео с тезисами. Kineo генерирует кадры моделями вроде Veo 3.1 и Kling 3, сохраняет вашу озвучку слово в слово вместо переписывания и целится в 60 секунд и больше, чтобы видео подходило под TikTok Creator Rewards. Если ваш канал живёт на визуале, которого больше ни у кого нет, генерация выигрывает; если на объёме — сток дешевле.',
  'Paste the complete script from ChatGPT here…': 'Вставьте сюда полный сценарий из ChatGPT…',
  'Paste the idea from ChatGPT here…': 'Вставьте сюда идею из ChatGPT…',
  'What’s your video about? One idea in — a finished film out: voiced, scored and captioned.': 'О чём ваше видео? Одна идея на входе — готовый фильм на выходе: с голосом, музыкой и субтитрами.',
  'Settings and generation': 'Настройки и генерация',
  'Search your videos…': 'Искать в ваших видео…',
  'Search your audio…': 'Искать в вашем аудио…',
  'Search your images by engine': 'Искать изображения по движку',
  'No playable videos in your library yet. Check your latest project above.': 'В библиотеке пока нет воспроизводимых видео. Проверьте свой последний проект выше.',
  'Make a finished Short →': 'Сделать готовый Short →',
  'Video Editing & Creator Tools': 'Видеомонтаж и инструменты для авторов',
  'Trim, resize, change speed, mute or add text. Edit a file you already have, right in your browser. Your script and planning tools are still here below.': 'Обрежьте, измените размер и скорость, уберите звук или добавьте текст. Редактируйте уже имеющийся файл прямо в браузере. Инструменты для сценария и планирования по-прежнему ниже.',
  '5 local editing tools': '5 локальных инструментов монтажа',
  'No generation credits to edit': 'Монтаж не тратит кредиты генерации',
  'Edit video': 'Редактировать видео',
  'Files up to 100 MB and 3 minutes. Local, real-time export up to 1280 px on the long edge. MP4 or WebM depending on your browser; downloads are not saved to My Videos.': 'Файлы до 100 МБ и 3 минут. Локальный экспорт в реальном времени до 1280 px по длинной стороне. MP4 или WebM в зависимости от браузера; загрузки не сохраняются в «Мои видео».',
  'Video Trimmer': 'Обрезка видео',
  'Cut the beginning or end and keep only the clip you need.': 'Отрежьте начало или конец и оставьте только нужный фрагмент.',
  'Video Resizer': 'Изменение размера видео',
  'Go vertical, square or wide. Fit the frame or crop to fill.': 'Вертикально, квадрат или широко. Вписать в кадр или обрезать до заполнения.',
  'Video Speed Changer': 'Изменение скорости видео',
  'Slow it down or speed it up, from 0.5× to 2×.': 'Замедлите или ускорьте, от 0.5× до 2×.',
  'Remove Audio': 'Удалить звук',
  'Download a copy without the original audio.': 'Скачайте копию без исходного звука.',
  'Add Text to Video': 'Добавить текст на видео',
  'Add a title or message that stays on screen. Not automatic subtitles.': 'Добавьте заголовок или сообщение, которое остаётся на экране. Не автоматические субтитры.',
  'No account · current Kineo plans': 'Без аккаунта · текущие планы Kineo',
  'No account · fair-use limit': 'Без аккаунта · лимит добросовестного использования',
  'No account · unlimited in browser': 'Без аккаунта · без ограничений в браузере',
  'Edit an existing video here. Create a new one with Kineo.': 'Редактируйте здесь существующее видео. Новое создайте с Kineo.',
  'Create an AI video →': 'Создать AI-видео →',
  'Edit your video, preview the changes, then export a copy.': 'Отредактируйте видео, просмотрите изменения, затем экспортируйте копию.',
  'Video preview': 'Предпросмотр видео',
  'Preview is silent. The download keeps audio unless Mute is selected.': 'Предпросмотр без звука. В загрузке звук сохраняется, если не выбрано «Без звука».',
  'Start with your video': 'Начните со своего видео',
  'Choose a local file. It stays on this device.': 'Выберите локальный файл. Он остаётся на этом устройстве.',
  'Choose video file': 'Выбрать видеофайл',
  'Video file': 'Видеофайл',
  'Video settings': 'Настройки видео',
  'Aspect ratio': 'Соотношение сторон',
  'Playback speed': 'Скорость воспроизведения',
  'On-screen text (100 characters, 3 lines)': 'Текст на экране (100 символов, 3 строки)',
  'Add a title or message': 'Добавьте заголовок или сообщение',
  'Export edited video': 'Экспортировать отредактированное видео',
  'Export happens in real time. Keep this tab visible. Re-encoded at up to 1280 px on the long edge; format depends on your browser.': 'Экспорт идёт в реальном времени. Держите эту вкладку видимой. Перекодируется до 1280 px по длинной стороне; формат зависит от браузера.',
  'Making a 4-second sample on your device…': 'Создаём 4-секундный образец на вашем устройстве…',
  'Reading your file…': 'Читаем ваш файл…',
  'Export result': 'Результат экспорта',
  'Your edited video': 'Ваше отредактированное видео',
  'Local download only. This copy is not saved to My Videos.': 'Только локальная загрузка. Эта копия не сохраняется в «Мои видео».',
  'Exported video': 'Экспортированное видео',
  'No upload. No generation credits. Your original is never overwritten.': 'Без загрузки на сервер. Без кредитов генерации. Оригинал никогда не перезаписывается.',
  'Up to 100 MB · 3 minutes · MP4/WebM input recommended. These are basic editing tools, not the CapCut app.': 'До 100 МБ · 3 минуты · рекомендуется вход MP4/WebM. Это базовые инструменты монтажа, а не приложение CapCut.',
  'Need a new video? Open Kineo Studio →': 'Нужно новое видео? Откройте Kineo Studio →',
  'This browser cannot export video here. Try the latest desktop Chrome or Edge.': 'Этот браузер не может экспортировать видео здесь. Попробуйте последний Chrome или Edge на компьютере.',
  'Choose a non-empty video file of up to 100 MB.': 'Выберите непустой видеофайл до 100 МБ.',
  'Use a playable clip of up to 3 minutes. Very large dimensions are not supported.': 'Используйте воспроизводимый клип до 3 минут. Очень большие размеры не поддерживаются.',
  'Check the start and end: select at least 0.25 seconds within your clip.': 'Проверьте начало и конец: выделите не менее 0.25 секунды внутри клипа.',
  'Choose a speed between 0.5× and 2×.': 'Выберите скорость от 0.5× до 2×.',
  'Use up to 100 characters and 3 lines of text.': 'Используйте не более 100 символов и 3 строк текста.',
  'Choose a supported aspect ratio, framing and text position.': 'Выберите поддерживаемое соотношение сторон, кадрирование и положение текста.',
  'This file could not be decoded. Try an MP4 (H.264) or WebM file.': 'Не удалось декодировать этот файл. Попробуйте MP4 (H.264) или WebM.',
  'Export stopped because this tab was hidden. Keep it open and visible, then export again. Your original is safe.': 'Экспорт остановлен, потому что вкладка была скрыта. Держите её открытой и видимой, затем экспортируйте снова. Оригинал в безопасности.',
  'Export stopped making progress. Try a shorter clip or desktop Chrome. Your original is unchanged.': 'Экспорт перестал продвигаться. Попробуйте более короткий клип или Chrome на компьютере. Оригинал не изменён.',
  'Audio could not start. Try exporting again, or choose Mute video.': 'Не удалось запустить звук. Попробуйте экспортировать снова или выберите «Видео без звука».',
  'The browser blocked playback. Try exporting again from this tab.': 'Браузер заблокировал воспроизведение. Попробуйте экспортировать снова из этой вкладки.',
  'Cancelled. Your original file is unchanged.': 'Отменено. Исходный файл не изменён.',
  'Could not finish this export. Try a shorter clip or another supported browser.': 'Не удалось завершить экспорт. Попробуйте более короткий клип или другой поддерживаемый браузер.',
  'The browser produced an incomplete file, so we did not offer it for download. Try again with this tab visible, or use desktop Chrome.': 'Браузер создал неполный файл, поэтому мы не предложили его для загрузки. Попробуйте снова с видимой вкладкой или используйте Chrome на компьютере.',
  'Create new video': 'Создать новое видео',
  'Your idea': 'Ваша идея',
  'Natural': 'Естественный',
  'Working…': 'Работаем…',
  '🎲 Surprise me': '🎲 Удивите меня',
  '📝 Use my script as is': '📝 Использовать мой сценарий как есть',
  'Camera preset': 'Пресет камеры',
  'Your latest videos': 'Ваши последние видео',
  'Presenter': 'Ведущий',
  '1 · Who’s talking': '1 · Кто говорит',
  '🎭 your characters': '🎭 ваши персонажи',
  '🎯 Max realism — animate my real photo': '🎯 Максимальный реализм — оживить моё реальное фото',
  '✓ Scene ready — preview on the right.': '✓ Сцена готова — предпросмотр справа.',
  '2 · What they say': '2 · Что говорят',
  '3 · How it looks': '3 · Как выглядит',
  'Motion': 'Движение',
  '⬇ Download MP4': '⬇ Скачать MP4',
  'One photo. Suddenly alive.': 'Одно фото. Вдруг живое.',
  'Cost per clip': 'Стоимость за клип',
  '↺ Animate another': '↺ Оживить ещё',
  'Grow': 'Расти',
  'Sending to the motion engine…': 'Отправляем в движок движения…',
  '📊 Facts': '📊 Факты',
  'Turn it into episode 2': 'Превратить в эпизод 2',
  'Start here': 'Начните здесь',
  'Engine': 'Движок',
  'Highly aesthetic, by xAI': 'Очень эстетичный, от xAI',
  'Google’s best image model': 'Лучшая модель изображений Google',
  'AI voiceover included': 'AI-озвучка включена',
  '6 engines': '6 движков',
  'AI Presenter': 'AI-ведущий',
  'Lock a character →': 'Закрепить персонажа →',
  'Make a clip →': 'Сделать клип →',
  'Make an ad →': 'Сделать рекламу →',
  'Generate free →': 'Создать бесплатно →',
  'Creating…': 'Создаём…',
  'Describe your image first': 'Сначала опишите изображение',
  'Type your script first': 'Сначала напишите сценарий',
  'From the founder': 'От основателя',
  'Faceless video generator': 'Генератор безликих видео',
  'Text to video Shorts': 'Shorts из текста в видео',
  'Cheapest AI Shorts maker': 'Самый дешёвый создатель AI Shorts',
  'Faceless channel ideas (2026)': 'Идеи безликих каналов (2026)',
  'Shorts idea widget': 'Виджет идей для Shorts',
  'Live case study: our channel on Autopilot': 'Живой кейс: наш канал на Autopilot',
  'Free YouTube Shorts scripts': 'Бесплатные сценарии YouTube Shorts',
  'Comment to Short script': 'Из комментария в сценарий Short',
  'Business video content planner': 'Планировщик видеоконтента для бизнеса',
  'Real estate video maker': 'Создатель видео о недвижимости',
  'Shorts title & hashtag generator': 'Генератор заголовков и хэштегов для Shorts',
  'Free viral score': 'Бесплатная оценка виральности',
  'Make money clipping with AI': 'Зарабатывайте на клипах с AI',
  'Shorts RPM by niche (2026)': 'RPM Shorts по нишам (2026)',
  'Can you monetize AI videos?': 'Можно ли монетизировать AI-видео?',
}
