// KINEO-INTERFACE-16-LINGUAS-2026-09-21 — interface em tr. Só copy autoral da interface: nunca prompt,
// título, resultado, nome de motor ou erro de API. Frase fora daqui cai em inglês (components/InterfaceLanguage.tsx).
// Gerado de scratchpad/tr-tr.js sobre o corpus vivo de frases (415); números e "Kineo" preservados por construção.
export const DICT: Record<string, string> = {
  'Videos for businesses': 'İşletmeler için videolar',
  // KINEO-NAV-4-ITENS-2026-09-25 — rótulos do menu de 4 itens (decisão do fundador 24/09).
  'Create video': 'Video oluştur',
  'For businesses': 'İşletmeler için',
  'More tools': 'Diğer araçlar',
  'Ads': 'Reklamlar',
  'Log in': 'Giriş yap',
  'More': 'Daha fazla',
  'Scripts': 'Senaryolar',
  'Animate': 'Canlandır',
  'Examples': 'Örnekler',
  'Pricing': 'Fiyatlar',
  'Library': 'Kütüphane',
  'Generation failed': 'Oluşturma başarısız oldu',
  'You can retry safely.': 'Güvenle tekrar deneyebilirsiniz.',
  'This engine is not available on your account right now': 'Bu motor şu anda hesabınızda kullanılamıyor',
  'Retrying the same engine will stop at this same place. Pick another engine to keep going.': 'Aynı motorla tekrar denemek aynı yerde duracak. Devam etmek için başka bir motor seçin.',
  'The engine is cooling down after two refunded attempts': 'Motor, iade edilen iki denemeden sonra soğuyor',
  'Starting another one right now stops at this same place. Give it a few minutes.': 'Şimdi bir tane daha başlatmak aynı yerde durur. Birkaç dakika bekleyin.',
  'Starting another one right now stops at this same place. The button below unlocks by itself.': 'Şimdi bir tane daha başlatmak aynı yerde durur. Aşağıdaki düğme kendiliğinden açılır.',
  'We stopped waiting on this render instead of leaving you hanging': 'Sizi bekletmek yerine bu render’ı beklemeyi bıraktık',
  'This one ran far longer than any video that finishes here. Starting again is worth it.': 'Bu, burada biten her videodan çok daha uzun sürdü. Yeniden başlamaya değer.',
  'The video engine is busy — this is on our side, not your idea': 'Video motoru meşgul — sorun bizde, fikrinizde değil',
  'Nothing about your text is wrong. Trying again in a few minutes usually goes straight through.': 'Metninizde yanlış bir şey yok. Birkaç dakika sonra tekrar denemek genellikle doğrudan geçer.',
  'Create Video': 'Video Oluştur',
  'Create a new video': 'Yeni bir video oluştur',
  'AI Avatar Studio': 'AI Avatar Stüdyosu',
  'Viral Templates': 'Viral Şablonlar',
  'Channel Builder': 'Kanal Kurucu',
  'Invite & Earn': 'Davet Et ve Kazan',
  'Start free': 'Ücretsiz başla',
  'Try 7 days for $1': '7 günü $1’a dene',
  'Pick a lane': 'Bir yol seçin',
  'All free tools': 'Tüm ücretsiz araçlar',
  'Terms of Service': 'Hizmet Şartları',
  'Trust Center': 'Güven Merkezi',
  'Review & publish': 'İncele ve yayınla',
  'Your image': 'Görseliniz',
  'Cost per image': 'Görsel başına maliyet',
  'No videos yet': 'Henüz video yok',
  'No audio yet': 'Henüz ses yok',
  '🎬 Studio — generate video': '🎬 Studio — video oluştur',
  '🎨 Images — create image': '🎨 Görseller — görsel oluştur',
  '🎙 Audio — text to speech': '🎙 Ses — metinden konuşmaya',
  'Type it. See it. Six image engines, one screen.': 'Yaz. Gör. Altı görsel motoru, tek ekran.',
  'Type it. Hear it. Four voice engines, one screen.': 'Yaz. Dinle. Dört ses motoru, tek ekran.',
  'Everything you’ve created, in one place.': 'Oluşturduğunuz her şey, tek bir yerde.',
  'Add credits →': 'Kredi ekle →',
  'Upscale any result to 2x for 1 credit.': 'Herhangi bir sonucu 1 krediye 2x büyütün.',
  'We couldn’t load your images right now.': 'Görsellerinizi şu anda yükleyemedik.',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'Görselleriniz ve kredileriniz güvende — bu yalnızca geçici bir okuma aksaklığı.',
  'We couldn’t load your audio right now.': 'Sesinizi şu anda yükleyemedik.',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'Sesiniz ve kredileriniz güvende — bu yalnızca geçici bir okuma aksaklığı.',
  'We couldn’t load part of your library right now.': 'Kitaplığınızın bir kısmını şu anda yükleyemedik.',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'Videolarınız ve kredileriniz güvende — bu yalnızca geçici bir okuma aksaklığı.',
  '↻ Try again': '↻ Tekrar dene',
  '⬇ Download': '⬇ İndir',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': 'Bir sesi beğendiniz mi? Studio tüm filmi onun etrafında kurar — görseller, altyazılar ve müzik.',
  'Open Studio →': 'Studio’yu aç →',
  'open the Studio': 'Studio’yu açın',
  'Next episode →': 'Sonraki bölüm →',
  'create your first image': 'ilk görselinizi oluşturun',
  'generate your first voiceover': 'ilk seslendirmenizi oluşturun',
  'Instant drafts': 'Anında taslaklar',
  'Deep prompt understanding': 'Derin prompt anlayışı',
  'Perfect text rendering': 'Kusursuz metin işleme',
  'Create Image': 'Görsel Oluştur',
  'Click-magnet YouTube covers': 'Tık çeken YouTube kapakları',
  'Bring any image to life': 'Her görsele hayat verin',
  'Instant narration': 'Anında anlatım',
  'Four voice engines': 'Dört ses motoru',
  'A face that speaks your script': 'Senaryonuzu konuşan bir yüz',
  'Every control, one screen': 'Her kontrol, tek ekran',
  'Today’s trending topics': 'Bugünün trend konuları',
  'Real renders, every engine': 'Gerçek render’lar, her motor',
  'Type an idea — watch it become a film.': 'Bir fikir yazın — filme dönüşmesini izleyin.',
  'Start with the full toolkit': 'Tam araç setiyle başlayın',
  'Kineo’s own engine — 3–7 min': 'Kineo’nun kendi motoru — 3–7 dk',
  'The workhorse AI video engine': 'İş atı AI video motoru',
  'Cinematic motion & camera': 'Sinematik hareket ve kamera',
  'Film scenes, native voice & lip sync': 'Film sahneleri, doğal ses ve dudak senkronu',
  'Talking video from one photo': 'Tek fotoğraftan konuşan video',
  'From idea to posted Short in 3 steps.': 'Fikirden yayınlanmış Short’a 3 adımda.',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'Çekim yok, kurgu yok, zaman çizelgesi yok. Bir kez yazın — gerisini Kineo yapar.',
  'Step 1': 'Adım 1',
  'Kineo builds it': 'Kineo inşa eder',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'AI, izlenmeye göre yapılandırılmış bir senaryo yazar, seslendirmeyi kaydeder, görüntüleri eşleştirir ve altyazıları gömer — bitmiş bir 9:16 video.',
  'Download & post': 'İndir ve paylaş',
  'Why Kineo': 'Neden Kineo',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'Çoğu araç zaten çektiğiniz uzun bir videoyu yeniden kırpar. Kineo sıfırdan inşa eder.',
  'See how to make Shorts without filming →': 'Çekim yapmadan Shorts nasıl yapılır →',
  'Generates the Short from just an idea': 'Short’u yalnızca bir fikirden oluşturur',
  'Writes the script for you': 'Senaryoyu sizin için yazar',
  'Finds and matches footage': 'Görüntüleri bulur ve eşleştirir',
  'your upload': 'yüklemeniz',
  'AI image studio included': 'AI görsel stüdyosu dahil',
  'Voice studio (text-to-speech)': 'Ses stüdyosu (metinden konuşmaya)',
  'One-click HD film enhance': 'Tek tıkla HD film iyileştirme',
  'One idea — or a whole toolkit.': 'Tek fikir — ya da bütün bir araç seti.',
  'Try AI Presenter →': 'AI Sunucu’yu dene →',
  'Transparent Clips': 'Şeffaf Klipler',
  'UGC Product Ads': 'UGC Ürün Reklamları',
  'Animate a photo →': 'Bir fotoğrafı canlandır →',
  'Make a thumbnail →': 'Bir küçük resim yap →',
  'Free AI Shorts': 'Ücretsiz AI Shorts',
  'Start with a niche that already works.': 'Zaten işe yarayan bir nişle başlayın.',
  'Not sure? Take the quiz →': 'Emin değil misiniz? Testi çözün →',
  'Pick your engine. Ship a Short today.': 'Motorunuzu seçin. Bugün bir Short yayınlayın.',
  'Cancel anytime': 'İstediğiniz zaman iptal edin',
  'Generate image →': 'Görsel oluştur →',
  'Generate audio →': 'Ses oluştur →',
  'Paid plans unlock clean MP4s.': 'Ücretli planlar temiz MP4’lerin kilidini açar.',
  'Best for starting out': 'Başlamak için en iyisi',
  'Best value per film': 'Film başına en iyi değer',
  'on Nano Banana': 'Nano Banana ile',
  'Every video engine incl. MiniMax H3': 'MiniMax H3 dahil her video motoru',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'Filigransız MP4 · 100 proje · 90 gün depolama',
  ', finished': ', bitmiş',
  '— every engine unlocked': '— her motorun kilidi açık',
  '· voice + karaoke captions + score': '· ses + karaoke altyazı + müzik',
  '500 projects · forever storage': '500 proje · sonsuza dek depolama',
  'Cancel anytime — 7-day money-back': 'İstediğiniz zaman iptal edin — 7 gün para iadesi',
  'films on Omni Flash': 'Omni Flash ile film',
  '· 2 free HD enhances / month': '· ayda 2 ücretsiz HD iyileştirme',
  'Unlimited projects · forever storage': 'Sınırsız proje · sonsuza dek depolama',
  'Everything in Creator': 'Creator’daki her şey',
  'Calculate your cost per Short →': 'Short başına maliyetinizi hesaplayın →',
  'How much do Shorts pay? →': 'Shorts ne kadar kazandırır? →',
  'Highest-RPM niches →': 'En yüksek RPM’li nişler →',
  'read the full review →': 'tam incelemeyi oku →',
  'a single line is enough — or paste a full script': 'tek satır yeter — ya da tam bir senaryo yapıştırın',
  '1080×1920 · Full HD master': '1080×1920 · Full HD master',
  'Every film is delivered as a 1080×1920 Full HD master (engines render natively at 720–768p and are mastered up). For maximum sharpness, run ✨HD Enhance on the finished film.': 'Her film 1080×1920 Full HD master olarak teslim edilir (motorlar doğal olarak 720–768p’de render alır ve yukarı masterlanır). Maksimum netlik için bitmiş filmde ✨HD Enhance çalıştırın.',
  'Your idea first. Review the settings, then generate.': 'Önce fikriniz. Ayarları gözden geçirin, sonra oluşturun.',
  '📷 Photo': '📷 Fotoğraf',
  '🖼️ Upload a different photo': '🖼️ Farklı bir fotoğraf yükle',
  '🎙️ Generating…': '🎙️ Oluşturuluyor…',
  '🎙️ Cloning the voice…': '🎙️ Ses klonlanıyor…',
  '🎙️ Upload a different sample': '🎙️ Farklı bir örnek yükle',
  '⏹ Stop & clone': '⏹ Durdur ve klonla',
  '🎭 Generate my avatar video': '🎭 Avatar videomu oluştur',
  'Continue exactly where ChatGPT stopped.': 'ChatGPT’nin kaldığı yerden tam olarak devam edin.',
  '✨ Let AI structure it': '✨ AI yapılandırsın',
  'Optional settings': 'İsteğe bağlı ayarlar',
  'optional — a pre-tested move added to your prompt': 'isteğe bağlı — prompt’unuza eklenen önceden test edilmiş bir hareket',
  'Reference image': 'Referans görsel',
  '🖼️ Start your video from an image — coming soon': '🖼️ Videonuzu bir görselden başlatın — yakında',
  'Estimated cost': 'Tahmini maliyet',
  'Your credits buy': 'Kredileriniz şunları alır',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'Ses, karaoke altyazı ve müzik dahil. Bir render başarısız olursa kredileriniz hemen geri gelir.',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'Aynı konu, yeni kanca ve final — fikir önceden yazılmış geliyor.',
  'Build next episode →': 'Sonraki bölümü oluştur →',
  'Episode 2 →': 'Bölüm 2 →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'Fotoğraftan konuşan AI sunucu — dudak senkronlu, kendi stüdyosu',
  'Your face. Your script.': 'Sizin yüzünüz. Sizin senaryonuz.',
  'Everything you need to make yourself speak — nothing you don’t.': 'Kendinizi konuşturmak için gereken her şey — gereksiz hiçbir şey yok.',
  'BEST MOTION': 'EN İYİ HAREKET',
  '1.5 · Realism': '1.5 · Gerçekçilik',
  '🎬 Put me in a scene': '🎬 Beni bir sahneye koy',
  'use original photo': 'orijinal fotoğrafı kullan',
  '✍️ Say exactly this — word for word': '✍️ Tam olarak bunu söyle — kelimesi kelimesine',
  '✨ Expand into a full Short script (45–60s)': '✨ Tam bir Short senaryosuna genişlet (45–60 sn)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 Ürün Reklamı modu — bir ürünü UGC tarzında sat',
  'Free — fills the script box above, then generate with your presenter.': 'Ücretsiz — yukarıdaki senaryo kutusunu doldurur, sonra sunucunuzla oluşturun.',
  '2.5 · Speak in your own voice': '2.5 · Kendi sesinizle konuşun',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ Ses klonlandı — anlatım bu sesle konuşacak.',
  'use a default voice': 'varsayılan bir ses kullan',
  '🎬 Full video — face the whole time': '🎬 Tam video — baştan sona yüz',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 AI Sunucu — hızlı ve doğal · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro — premium fotoğraf kalitesi · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 Body Motion — gövde, eller ve jestler · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ Klasik — talking head · 110 cr',
  'you have': 'sahip olduğunuz',
  'to create your avatar video.': 'avatar videonuzu oluşturmak için.',
  '5 · Gesture clips — transparent background': '5 · Jest klipleri — şeffaf arka plan',
  'auto-refunded if it fails': 'başarısız olursa otomatik iade',
  '⬇️ Download transparent WebM': '⬇️ Şeffaf WebM indir',
  '⬇️ Original MP4 (with background)': '⬇️ Orijinal MP4 (arka planlı)',
  'Pick a face to preview': 'Önizlemek için bir yüz seçin',
  '↺ Make another': '↺ Bir tane daha yap',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'İnsanlar, evcil hayvanlar, ürünler, eski aile fotoğrafları — bir fotoğraf yükleyin ya da herkese açık bir görsel bağlantısı yapıştırın ve hareket etmesini izleyin.',
  'The photo': 'Fotoğraf',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': '8 MB’a kadar JPG/PNG. Herkese açık bağlantılar sunucumuzda güvenle indirilir ve doğrulanır.',
  'sign in': 'giriş yap',
  'Kineo will fetch and validate it on the server when you animate.': 'Kineo, canlandırdığınızda onu sunucuda alıp doğrulayacak.',
  'Upload a photo to preview': 'Önizlemek için bir fotoğraf yükleyin',
  '🖼️ Upload a photo': '🖼️ Fotoğraf yükle',
  '✨ Bring it to life': '✨ Hayat ver',
  'Uploading your photo…': 'Fotoğrafınız yükleniyor…',
  'Bringing your photo to life… (1–3 min)': 'Fotoğrafınıza hayat veriliyor… (1–3 dk)',
  'Alive!': 'Canlı!',
  '🌬️ Subtle & real': '🌬️ İnce ve gerçek',
  '😊 Person comes alive': '😊 Kişi canlanıyor',
  'Type your idea first': 'Önce fikrinizi yazın',
  '📖 True Story': '📖 Gerçek Hikâye',
  'Paste your ChatGPT script': 'ChatGPT senaryonuzu yapıştırın',
  'First Short complete': 'İlk Short tamamlandı',
  'Keep your show moving': 'Programınızı hareket halinde tutun',
  'Cheapest way to see your idea as a film': 'Fikrinizi film olarak görmenin en ucuz yolu',
  'Slow Dolly-In': 'Yavaş Dolly-In',
  'FPV Drone': 'FPV Drone',
  'Macro Detail': 'Makro Detay',
  'Sharing & creator options': 'Paylaşım ve içerik üretici seçenekleri',
  'We couldn’t load your videos right now': 'Videolarınızı şu anda yükleyemedik',
  'Your videos and credits are safe — this is a temporary read hiccup, not a lost library.': 'Videolarınız ve kredileriniz güvende — bu geçici bir okuma aksaklığı, kaybolmuş bir kitaplık değil.',
  '⚡ Generate Video': '⚡ Video Oluştur',
  'Prefer clean exports now? Starter includes': 'Temiz dışa aktarmaları şimdi mi istiyorsunuz? Starter şunu içerir',
  'credits each month for': 'kredi her ay,',
  'Your existing files stay available. Starter applies to new exports after checkout.': 'Mevcut dosyalarınız erişilebilir kalır. Starter, ödemeden sonraki yeni dışa aktarmalara uygulanır.',
  'Build Next Episode First': 'Önce Sonraki Bölümü Oluştur',
  'Video unavailable': 'Video kullanılamıyor',
  'Free MP4 includes the Kineo watermark': 'Ücretsiz MP4, Kineo filigranını içerir',
  'Free distribution · latest Short': 'Ücretsiz dağıtım · en son Short',
  'Send it to one person for feedback': 'Geri bildirim için bir kişiye gönderin',
  'Copy a public watch page for your finished video. Your friend can watch it without logging in, then use “Make one like this” if the idea inspires them.': 'Bitmiş videonuz için herkese açık bir izleme sayfası kopyalayın. Arkadaşınız giriş yapmadan izleyebilir, fikir ilham verirse “Bunun gibi bir tane yap”ı kullanabilir.',
  'Public watch links are temporarily paused': 'Herkese açık izleme bağlantıları geçici olarak duraklatıldı',
  'Your video stays in your account. Download the MP4 if you want to send it directly; Kineo will not publish a public page without an explicit visibility choice.': 'Videonuz hesabınızda kalır. Doğrudan göndermek isterseniz MP4’ü indirin; Kineo açık bir görünürlük tercihi olmadan herkese açık sayfa yayınlamaz.',
  'Loading…': 'Yükleniyor…',
  'For new videos ·': 'Yeni videolar için ·',
  'Published it?': 'Yayınladınız mı?',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'Net, önden, tek kişi. Vücut hareketi için iki elin göründüğü bel üstü veya tam boy bir fotoğraf kullanın. Siyah bantlar otomatik kaldırılır.',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'En iyi profesyonel sonuç: istediğiniz gerçek jestleri yapan, senaryo uzunluğuna yakın 5–20 sn’lik dikey bir klip yükleyin. Sync-3 gerçek yüzü ve vücut hareketini koruyarak konuşmayı değiştirir. 40 MB’a kadar MP4/MOV.',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'Bu kişinin görüntüsünü kullanma hakkım olduğunu onaylıyor ve AI ile canlandırılmasına izin veriyorum.',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': '~30-60 sn’lik net bir ses örneği yükleyin (tek konuşmacı, az arka plan gürültüsü); anlatım o sesle konuşulur. Yalnızca kullanma hakkınız olan bir sesi kullanın.',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'Kelimesi kelimesine videolar yüzünüzü baştan sona gösterir (kısadırlar — b-roll gerekmez).',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'Maksimum gerçekçilik ve kurulu sahne videoları sunucuyu anlatım boyunca ekranda tutar.',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ Kanca girişi — siz açarsınız, hikâyeyi b-roll anlatır',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'Sunucunuzun el sallayan, işaret eden, sunan kısa klipleri — GERÇEK şeffaf arka planlı WebM olarak teslim edilir. Doğrudan Storyline, Premiere, CapCut veya herhangi bir slayta bırakın. Yeşil perde yok, keying yok.',
  'Cinematic film — 9-image consistency': 'Sinematik film — 9 görsel tutarlılığı',
  '#1-ranked video model — Aug 2026 arena': '1 numaralı video modeli — Ağu 2026 arenası',
  'Cinematic motion and camera work': 'Sinematik hareket ve kamera çalışması',
  'Shorts money & growth': 'Shorts ile para ve büyüme',
  'Compare Kineo with 27 AI video tools →': 'Kineo’yu 27 AI video aracıyla karşılaştırın →',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'Konuşan sunucular, yeniden kullanılabilir karakterler, şeffaf klipler, ürün reklamları — artı bir trendi bulup yakalamak için gereken her şey.',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'Bir fotoğraf + senaryonuz — stüdyo kalitesinde dudak senkronlu konuşan video, HeyGen tarzında.',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'Bir karakteri bir kez kaydedin — yaptığınız her video ve küçük resimde birebir aynı yüz.',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'Sunucu jestleri — el sallama, işaret etme, sunma — gerçek şeffaf arka planlı WebM olarak.',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'Herhangi bir ürünü yapıştırın — sizin için yazılmış ve seslendirilmiş 15-30 sn’lik içerik üretici tarzı bir reklam alın.',
  'Bring any still photo to life as a moving, postable video.': 'Herhangi bir durağan fotoğrafa hareketli, paylaşılabilir bir video olarak hayat verin.',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'En büyük kanalların tarzında tık çeken küçük resimler — tek bir prompt’tan.',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'Aşağıdaki her nişin kendi oluşturucu sayfası, ayarlanmış prompt’ları ve gerçek örnekleri var.',
  'Is the video really mine to post?': 'Video gerçekten paylaşmam için benim mi?',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'Ücretli planlar YouTube, TikTok veya Reels için temiz, filigransız MP4’ün kilidini açar.',
  'Do I need any editing skills?': 'Kurgu becerisine ihtiyacım var mı?',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'Hayır. Bir fikir yazarsınız; AI senaryoyu yazar, sesi kaydeder, görüntüleri bulur ve altyazı ekler.',
  'Is there a watermark?': 'Filigran var mı?',
  'Paid plans export clean, watermark-free MP4s.': 'Ücretli planlar temiz, filigransız MP4 dışa aktarır.',
  'Can Kineo also generate images and voiceovers?': 'Kineo görsel ve seslendirme de üretebilir mi?',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'Evet — Kineo bir AI görsel stüdyosu (FLUX, Seedream ve Nano Banana Pro dahil 6 motor, görsel başına 1 krediden) ve 4 metinden konuşmaya motorlu bir ses stüdyosu (1000 karakter başına 1 krediden) içerir. Yaptığınız her şey Kitaplığınızda yaşar.',
  'Can I make my videos sharper?': 'Videolarımı daha net yapabilir miyim?',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'Her videoda Topaz film restorasyonuyla çalışan tek tıklık bir İyileştir seçeneği var — sıkıştırma bozukluklarını kaldırır, detayı geri kazandırır ve ince sinematik gren ekler. Video başına 10 kredi; Studio planı ayda 2 ücretsiz iyileştirme içerir.',
  'Can I use my own script?': 'Kendi senaryomu kullanabilir miyim?',
  'What if a generation fails?': 'Bir oluşturma başarısız olursa?',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'Bir render başarısız olduğu anda kredileriniz otomatik geri gelir — destek talebi yok, bekleme yok. Yalnızca gerçekten aldığınız videolar için ödersiniz.',
  'Can I cancel anytime?': 'İstediğim zaman iptal edebilir miyim?',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'İstediğiniz zaman, tek tıkla. Planlar aylıktır ve kredileriniz her ay yenilenir.',
  'Can I run a whole channel with the same host?': 'Aynı sunucuyla bütün bir kanal yürütebilir miyim?',
  'Can I monetize the videos?': 'Videoları para kazanmak için kullanabilir miyim?',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'Evet. Her video sizindir — saklayın, paylaşın ve para kazanın; YouTube Partner Programı, TikTok ve Reels dahil. Ek lisans gerekmez.',
  'Can I use the videos commercially, or for client work?': 'Videoları ticari olarak ya da müşteri işlerinde kullanabilir miyim?',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'Evet. Şartlarımız Kineo’yu yasal kişisel veya ticari amaçlarla kullanmanıza izin verir ve oluşturduğunuz videoların sahipliğinin sizde kaldığını onaylar; bu sayede onları yayınlayabilir, para kazanabilir ve kendi ücretli hizmetinizin parçası olarak bir müşteriye teslim edebilirsiniz. Ek lisans yok, video başına telif yok. Aynı şartlardan iki sınır gelir: Kineo’nun kendisini yeniden satamaz veya dağıtamazsınız ve bir render içindeki stok klipler bitmiş videonuzda kullanım için lisanslıdır, bağımsız stok görüntü olarak yeniden yüklemek için değil. Ücretli planlar temiz, filigransız MP4 dışa aktarır.',
  'How long does one video take?': 'Bir video ne kadar sürer?',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'Fast Modu genellikle 3–7 dakikada biter. AI ile üretilen ve sinematik videolar biraz daha uzun sürer çünkü son MP4 oluşturulmadan önce her sahne üretilir.',
  'How much does Kineo cost?': 'Kineo ne kadar?',
  'Kineo has three monthly plans: Starter at $': 'Kineo’nun üç aylık planı var: Starter $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'kredi. Krediler video başına harcanır ve bir videonun maliyeti seçtiğiniz motora bağlıdır; bir Fast render ile sinematik bir film aynı bakiyeden çok farklı oranlarda çıkar.',
  'Which AI video engines can I use in Kineo?': 'Kineo’da hangi AI video motorlarını kullanabilirim?',
  ', behind one interface and one balance:': ', tek bir arayüz ve tek bir bakiye arkasında:',
  'What is the best AI video generator for faceless YouTube channels?': 'Yüzsüz YouTube kanalları için en iyi AI video oluşturucu hangisi?',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'Evet. Hiç ödeme yapmamış ücretsiz kullanıcılar filigranlı MP4’ü indirebilir, paylaşabilir ve yayınlayabilir.',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'Deneme filmleri küçük bir filigran taşır — MP4’ü indirebilir, paylaşabilir ve yayınlayabilirsiniz. Denemeden sonra ücretsiz Fast video filigran taşır.',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'Ücretsiz indirmeler filigran taşır; ücretli planlar temiz MP4’ün kilidini açar.',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'Deneme indirmeleri filigran taşır, denemeden sonraki ücretsiz Fast video da öyle; ücretli planlar her zaman temiz dışa aktarır.',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'Ücretsiz erişim yeni kullanıcılara kartsız, her 24 saatte 3 filigranlı Fast video verir. İndirip paylaşabilirsiniz.',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'Her 24 saatte 3 filigranlı Fast video oluşturun, indirin ve paylaşın, kartsız.',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'Her 24 saatte 3 filigranlı Fast video oluşturun, izleyin, indirin ve paylaşın — kartsız.',
  'create, watch, download and share up to 3 Fast videos every 24h': 'her 24 saatte 3 Fast video oluşturun, izleyin, indirin ve paylaşın',
  '— no card, watermark included.': '— kartsız, filigran dahil.',
  'AI image generator — 6 engines': 'AI görsel oluşturucu — 6 motor',
  'AI voice generator (text to speech)': 'AI ses oluşturucu (metinden konuşmaya)',
  'AI video upscaler & enhancer': 'AI video büyütücü ve iyileştirici',
  'Trending Shorts ideas today': 'Bugünün trend Shorts fikirleri',
  'AI Avatar video — your face, any script': 'AI Avatar videosu — sizin yüzünüz, her senaryo',
  'Kineo facts & numbers (citable)': 'Kineo gerçekleri ve rakamları (alıntılanabilir)',
  'Free AI Shorts generator': 'Ücretsiz AI Shorts oluşturucu',
  'YouTube Shorts from a topic': 'Konudan YouTube Shorts',
  'ChatGPT script to YouTube Short': 'ChatGPT senaryosundan YouTube Short’a',
  'Shorts without filming': 'Çekim yapmadan Shorts',
  'Faceless niche picker': 'Yüzsüz niş seçici',
  'State of AI Shorts 2026': 'AI Shorts’un Durumu 2026',
  'AI Shorts for agencies & client work': 'Ajanslar ve müşteri işleri için AI Shorts',
  'Trust Center — privacy, payments & ownership': 'Güven Merkezi — gizlilik, ödemeler ve sahiplik',
  'Affiliate program - 30% recurring': 'Ortaklık programı - %30 yinelenen',
  'Free AI Shorts by niche': 'Nişe göre ücretsiz AI Shorts',
  'Free script generator': 'Ücretsiz senaryo oluşturucu',
  'Product video ad script': 'Ürün video reklam senaryosu',
  'Client video brief generator': 'Müşteri video brifi oluşturucu',
  'Free hook generator': 'Ücretsiz kanca oluşturucu',
  'Shorts script timer': 'Shorts senaryo zamanlayıcı',
  'Shorts money calculator': 'Shorts kazanç hesaplayıcı',
  'How much do Shorts pay?': 'Shorts ne kadar kazandırır?',
  'Best AI Shorts generators': 'En iyi AI Shorts oluşturucular',
  'TikTok vs Shorts: which pays more?': 'TikTok mu Shorts mu: hangisi daha çok kazandırır?',
  'All comparisons': 'Tüm karşılaştırmalar',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · Tüm hakları saklıdır',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'Stok görüntülerin birleştirilmesini mi yoksa görüntülerin üretilmesini mi istediğinize bağlı. InVideo ve AutoShorts gibi araçlar stok klipleri senaryonuza göre keser; daha ucuzdur ve konuşma noktalı videolar için yeterlidir. Kineo görüntüleri Veo 3.1 ve Kling 3 gibi modellerle üretir, anlatımınızı yeniden yazmak yerine kelimesi kelimesine korur ve videonun TikTok Creator Rewards’a uygun olması için 60 saniye veya daha uzun süreyi hedefler. Kanalınız kimsede olmayan görsellerle yaşıyorsa üretim kazanır; hacimle yaşıyorsa stok daha ucuzdur.',
  'Paste the complete script from ChatGPT here…': 'ChatGPT’den tam senaryoyu buraya yapıştırın…',
  'Paste the idea from ChatGPT here…': 'ChatGPT’den fikri buraya yapıştırın…',
  'What’s your video about? One idea in — a finished film out: voiced, scored and captioned.': 'Videonuz ne hakkında? Bir fikir girer — bitmiş bir film çıkar: seslendirilmiş, müzikli ve altyazılı.',
  'Settings and generation': 'Ayarlar ve oluşturma',
  'Search your videos…': 'Videolarınızda arayın…',
  'Search your audio…': 'Sesinizde arayın…',
  'Search your images by engine': 'Görsellerinizi motora göre arayın',
  'No playable videos in your library yet. Check your latest project above.': 'Kitaplığınızda henüz oynatılabilir video yok. Yukarıdaki en son projenize bakın.',
  'Make a finished Short →': 'Bitmiş bir Short yap →',
  'Video Editing & Creator Tools': 'Video Düzenleme ve İçerik Üretici Araçları',
  'Trim, resize, change speed, mute or add text. Edit a file you already have, right in your browser. Your script and planning tools are still here below.': 'Kırpın, yeniden boyutlandırın, hızı değiştirin, sesi kapatın veya metin ekleyin. Zaten sahip olduğunuz bir dosyayı doğrudan tarayıcınızda düzenleyin. Senaryo ve planlama araçlarınız hâlâ aşağıda.',
  '5 local editing tools': '5 yerel düzenleme aracı',
  'No generation credits to edit': 'Düzenlemek için oluşturma kredisi gerekmez',
  'Edit video': 'Videoyu düzenle',
  'Files up to 100 MB and 3 minutes. Local, real-time export up to 1280 px on the long edge. MP4 or WebM depending on your browser; downloads are not saved to My Videos.': '100 MB ve 3 dakikaya kadar dosyalar. Uzun kenarda 1280 px’e kadar yerel, gerçek zamanlı dışa aktarma. Tarayıcınıza göre MP4 veya WebM; indirmeler Videolarım’a kaydedilmez.',
  'Video Trimmer': 'Video Kırpıcı',
  'Cut the beginning or end and keep only the clip you need.': 'Başı veya sonu kesin ve yalnızca ihtiyacınız olan klibi tutun.',
  'Video Resizer': 'Video Yeniden Boyutlandırıcı',
  'Go vertical, square or wide. Fit the frame or crop to fill.': 'Dikey, kare veya geniş. Kareye sığdırın veya doldurmak için kırpın.',
  'Video Speed Changer': 'Video Hız Değiştirici',
  'Slow it down or speed it up, from 0.5× to 2×.': '0.5× ile 2× arasında yavaşlatın veya hızlandırın.',
  'Remove Audio': 'Sesi Kaldır',
  'Download a copy without the original audio.': 'Orijinal ses olmadan bir kopya indirin.',
  'Add Text to Video': 'Videoya Metin Ekle',
  'Add a title or message that stays on screen. Not automatic subtitles.': 'Ekranda kalan bir başlık veya mesaj ekleyin. Otomatik altyazı değildir.',
  'No account · current Kineo plans': 'Hesap yok · güncel Kineo planları',
  'No account · fair-use limit': 'Hesap yok · adil kullanım sınırı',
  'No account · unlimited in browser': 'Hesap yok · tarayıcıda sınırsız',
  'Edit an existing video here. Create a new one with Kineo.': 'Mevcut bir videoyu burada düzenleyin. Yenisini Kineo ile oluşturun.',
  'Create an AI video →': 'AI video oluştur →',
  'Edit your video, preview the changes, then export a copy.': 'Videonuzu düzenleyin, değişiklikleri önizleyin, sonra bir kopya dışa aktarın.',
  'Video preview': 'Video önizleme',
  'Preview is silent. The download keeps audio unless Mute is selected.': 'Önizleme sessizdir. Sessiz seçilmedikçe indirme sesi korur.',
  'Start with your video': 'Videonuzla başlayın',
  'Choose a local file. It stays on this device.': 'Yerel bir dosya seçin. Bu cihazda kalır.',
  'Choose video file': 'Video dosyası seç',
  'Video file': 'Video dosyası',
  'Video settings': 'Video ayarları',
  'Aspect ratio': 'En boy oranı',
  'Playback speed': 'Oynatma hızı',
  'On-screen text (100 characters, 3 lines)': 'Ekran metni (100 karakter, 3 satır)',
  'Add a title or message': 'Bir başlık veya mesaj ekleyin',
  'Export edited video': 'Düzenlenen videoyu dışa aktar',
  'Export happens in real time. Keep this tab visible. Re-encoded at up to 1280 px on the long edge; format depends on your browser.': 'Dışa aktarma gerçek zamanlı olur. Bu sekmeyi görünür tutun. Uzun kenarda 1280 px’e kadar yeniden kodlanır; format tarayıcınıza bağlıdır.',
  'Making a 4-second sample on your device…': 'Cihazınızda 4 saniyelik bir örnek hazırlanıyor…',
  'Reading your file…': 'Dosyanız okunuyor…',
  'Export result': 'Dışa aktarma sonucu',
  'Your edited video': 'Düzenlenen videonuz',
  'Local download only. This copy is not saved to My Videos.': 'Yalnızca yerel indirme. Bu kopya Videolarım’a kaydedilmez.',
  'Exported video': 'Dışa aktarılan video',
  'No upload. No generation credits. Your original is never overwritten.': 'Yükleme yok. Oluşturma kredisi yok. Orijinaliniz asla üzerine yazılmaz.',
  'Up to 100 MB · 3 minutes · MP4/WebM input recommended. These are basic editing tools, not the CapCut app.': '100 MB’a kadar · 3 dakika · MP4/WebM girişi önerilir. Bunlar temel düzenleme araçlarıdır, CapCut uygulaması değil.',
  'Need a new video? Open Kineo Studio →': 'Yeni bir video mu lazım? Kineo Studio’yu açın →',
  'This browser cannot export video here. Try the latest desktop Chrome or Edge.': 'Bu tarayıcı burada video dışa aktaramıyor. En yeni masaüstü Chrome veya Edge’i deneyin.',
  'Choose a non-empty video file of up to 100 MB.': '100 MB’a kadar boş olmayan bir video dosyası seçin.',
  'Use a playable clip of up to 3 minutes. Very large dimensions are not supported.': '3 dakikaya kadar oynatılabilir bir klip kullanın. Çok büyük boyutlar desteklenmez.',
  'Check the start and end: select at least 0.25 seconds within your clip.': 'Başlangıç ve bitişi kontrol edin: klibinizde en az 0.25 saniye seçin.',
  'Choose a speed between 0.5× and 2×.': '0.5× ile 2× arasında bir hız seçin.',
  'Use up to 100 characters and 3 lines of text.': 'En fazla 100 karakter ve 3 satır metin kullanın.',
  'Choose a supported aspect ratio, framing and text position.': 'Desteklenen bir en boy oranı, kadraj ve metin konumu seçin.',
  'This file could not be decoded. Try an MP4 (H.264) or WebM file.': 'Bu dosya çözümlenemedi. MP4 (H.264) veya WebM dosyası deneyin.',
  'Export stopped because this tab was hidden. Keep it open and visible, then export again. Your original is safe.': 'Bu sekme gizlendiği için dışa aktarma durdu. Açık ve görünür tutun, sonra tekrar dışa aktarın. Orijinaliniz güvende.',
  'Export stopped making progress. Try a shorter clip or desktop Chrome. Your original is unchanged.': 'Dışa aktarma ilerlemiyor. Daha kısa bir klip veya masaüstü Chrome deneyin. Orijinaliniz değişmedi.',
  'Audio could not start. Try exporting again, or choose Mute video.': 'Ses başlatılamadı. Tekrar dışa aktarmayı deneyin veya Videoyu sessize al’ı seçin.',
  'The browser blocked playback. Try exporting again from this tab.': 'Tarayıcı oynatmayı engelledi. Bu sekmeden tekrar dışa aktarmayı deneyin.',
  'Cancelled. Your original file is unchanged.': 'İptal edildi. Orijinal dosyanız değişmedi.',
  'Could not finish this export. Try a shorter clip or another supported browser.': 'Bu dışa aktarma tamamlanamadı. Daha kısa bir klip veya desteklenen başka bir tarayıcı deneyin.',
  'The browser produced an incomplete file, so we did not offer it for download. Try again with this tab visible, or use desktop Chrome.': 'Tarayıcı eksik bir dosya üretti, bu yüzden indirmeye sunmadık. Bu sekme görünürken tekrar deneyin veya masaüstü Chrome kullanın.',
  'Create new video': 'Yeni video oluştur',
  'Your idea': 'Fikriniz',
  'Natural': 'Doğal',
  'Working…': 'Çalışıyor…',
  '🎲 Surprise me': '🎲 Beni şaşırt',
  '📝 Use my script as is': '📝 Senaryomu olduğu gibi kullan',
  'Camera preset': 'Kamera ön ayarı',
  'Your latest videos': 'En son videolarınız',
  'Presenter': 'Sunucu',
  '1 · Who’s talking': '1 · Kim konuşuyor',
  '🎭 your characters': '🎭 karakterleriniz',
  '🎯 Max realism — animate my real photo': '🎯 Maksimum gerçekçilik — gerçek fotoğrafımı canlandır',
  '✓ Scene ready — preview on the right.': '✓ Sahne hazır — önizleme sağda.',
  '2 · What they say': '2 · Ne söylüyorlar',
  '3 · How it looks': '3 · Nasıl görünüyor',
  'Motion': 'Hareket',
  '⬇ Download MP4': '⬇ MP4 indir',
  'One photo. Suddenly alive.': 'Bir fotoğraf. Birden canlı.',
  'Cost per clip': 'Klip başına maliyet',
  '↺ Animate another': '↺ Bir tane daha canlandır',
  'Grow': 'Büyü',
  'Sending to the motion engine…': 'Hareket motoruna gönderiliyor…',
  '📊 Facts': '📊 Gerçekler',
  'Turn it into episode 2': 'Bölüm 2’ye dönüştür',
  'Start here': 'Buradan başlayın',
  'Engine': 'Motor',
  'Highly aesthetic, by xAI': 'Son derece estetik, xAI’dan',
  'Google’s best image model': 'Google’ın en iyi görsel modeli',
  'AI voiceover included': 'AI seslendirme dahil',
  '6 engines': '6 motor',
  'AI Presenter': 'AI Sunucu',
  'Lock a character →': 'Bir karakter sabitle →',
  'Make a clip →': 'Bir klip yap →',
  'Make an ad →': 'Bir reklam yap →',
  'Generate free →': 'Ücretsiz oluştur →',
  'Creating…': 'Oluşturuluyor…',
  'Describe your image first': 'Önce görselinizi tarif edin',
  'Type your script first': 'Önce senaryonuzu yazın',
  'From the founder': 'Kurucudan',
  'Faceless video generator': 'Yüzsüz video oluşturucu',
  'Text to video Shorts': 'Metinden video Shorts',
  'Cheapest AI Shorts maker': 'En ucuz AI Shorts yapıcı',
  'Faceless channel ideas (2026)': 'Yüzsüz kanal fikirleri (2026)',
  'Shorts idea widget': 'Shorts fikir widget’ı',
  'Live case study: our channel on Autopilot': 'Canlı vaka çalışması: Autopilot’taki kanalımız',
  'Free YouTube Shorts scripts': 'Ücretsiz YouTube Shorts senaryoları',
  'Comment to Short script': 'Yorumdan Short senaryosuna',
  'Business video content planner': 'İşletmeler için video içerik planlayıcı',
  'Real estate video maker': 'Gayrimenkul video yapıcı',
  'Shorts title & hashtag generator': 'Shorts başlık ve hashtag oluşturucu',
  'Free viral score': 'Ücretsiz viral puan',
  'Make money clipping with AI': 'AI ile klip yaparak para kazanın',
  'Shorts RPM by niche (2026)': 'Nişe göre Shorts RPM (2026)',
  'Can you monetize AI videos?': 'AI videolarından para kazanılabilir mi?',
}
