// KINEO-INTERFACE-16-LINGUAS-2026-09-21 — interface em uk. Só copy autoral da interface: nunca prompt,
// título, resultado, nome de motor ou erro de API. Frase fora daqui cai em inglês (components/InterfaceLanguage.tsx).
// Gerado de scratchpad/tr-uk.js sobre o corpus vivo de frases (415); números e "Kineo" preservados por construção.
export const DICT: Record<string, string> = {
  'Generation failed': 'Генерація не вдалася',
  'You can retry safely.': 'Можна спокійно спробувати ще раз.',
  'This engine is not available on your account right now': 'Цей рушій зараз недоступний у вашому акаунті',
  'Retrying the same engine will stop at this same place. Pick another engine to keep going.': 'Повтор на тому самому рушії зупиниться в тому ж місці. Оберіть інший рушій, щоб продовжити.',
  'The engine is cooling down after two refunded attempts': 'Рушій охолоджується після двох повернутих спроб',
  'Starting another one right now stops at this same place. Give it a few minutes.': 'Запуск ще однієї зараз зупиниться в тому ж місці. Зачекайте кілька хвилин.',
  'Starting another one right now stops at this same place. The button below unlocks by itself.': 'Запуск ще однієї зараз зупиниться в тому ж місці. Кнопка нижче розблокується сама.',
  'We stopped waiting on this render instead of leaving you hanging': 'Ми перестали чекати на цей рендер, щоб не тримати вас у підвішеному стані',
  'This one ran far longer than any video that finishes here. Starting again is worth it.': 'Цей тривав набагато довше за будь-яке відео, що тут завершується. Варто почати знову.',
  'The video engine is busy — this is on our side, not your idea': 'Відеорушій зайнятий — справа на нашому боці, а не у вашій ідеї',
  'Nothing about your text is wrong. Trying again in a few minutes usually goes straight through.': 'З вашим текстом усе гаразд. Повтор за кілька хвилин зазвичай проходить одразу.',
  'Create Video': 'Створити відео',
  'Create a new video': 'Створити нове відео',
  'AI Avatar Studio': 'Студія AI-аватарів',
  'Viral Templates': 'Вірусні шаблони',
  'Channel Builder': 'Конструктор каналу',
  'Invite & Earn': 'Запрошуй і заробляй',
  'Start free': 'Почати безкоштовно',
  'Try 7 days for $1': 'Спробувати 7 днів за $1',
  'Pick a lane': 'Оберіть шлях',
  'All free tools': 'Усі безкоштовні інструменти',
  'Terms of Service': 'Умови використання',
  'Trust Center': 'Центр довіри',
  'Review & publish': 'Перевірити й опублікувати',
  'Your image': 'Ваше зображення',
  'Cost per image': 'Вартість за зображення',
  'No videos yet': 'Відео поки немає',
  'No audio yet': 'Аудіо поки немає',
  '🎬 Studio — generate video': '🎬 Studio — створити відео',
  '🎨 Images — create image': '🎨 Зображення — створити зображення',
  '🎙 Audio — text to speech': '🎙 Аудіо — текст у мовлення',
  'Type it. See it. Six image engines, one screen.': 'Напишіть. Побачте. Шість рушіїв зображень, один екран.',
  'Type it. Hear it. Four voice engines, one screen.': 'Напишіть. Почуйте. Чотири голосові рушії, один екран.',
  'Everything you’ve created, in one place.': 'Усе, що ви створили, в одному місці.',
  'Add credits →': 'Додати кредити →',
  'Upscale any result to 2x for 1 credit.': 'Збільште будь-який результат у 2x за 1 кредит.',
  'We couldn’t load your images right now.': 'Не вдалося завантажити ваші зображення просто зараз.',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'Ваші зображення та кредити в безпеці — це лише тимчасовий збій читання.',
  'We couldn’t load your audio right now.': 'Не вдалося завантажити ваше аудіо просто зараз.',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'Ваше аудіо та кредити в безпеці — це лише тимчасовий збій читання.',
  'We couldn’t load part of your library right now.': 'Не вдалося завантажити частину вашої бібліотеки просто зараз.',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'Ваші відео та кредити в безпеці — це лише тимчасовий збій читання.',
  '↻ Try again': '↻ Спробувати знову',
  '⬇ Download': '⬇ Завантажити',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': 'Сподобався голос? Studio збудує навколо нього весь фільм — візуал, субтитри й музику.',
  'Open Studio →': 'Відкрити Studio →',
  'open the Studio': 'відкрийте Studio',
  'Next episode →': 'Наступний епізод →',
  'create your first image': 'створіть перше зображення',
  'generate your first voiceover': 'створіть першу озвучку',
  'Instant drafts': 'Миттєві чернетки',
  'Deep prompt understanding': 'Глибоке розуміння промпту',
  'Perfect text rendering': 'Ідеальний рендер тексту',
  'Create Image': 'Створити зображення',
  'Click-magnet YouTube covers': 'Обкладинки YouTube, що притягують кліки',
  'Bring any image to life': 'Оживіть будь-яке зображення',
  'Instant narration': 'Миттєва озвучка',
  'Four voice engines': 'Чотири голосові рушії',
  'A face that speaks your script': 'Обличчя, що промовляє ваш сценарій',
  'Every control, one screen': 'Усі налаштування, один екран',
  'Today’s trending topics': 'Теми в тренді сьогодні',
  'Real renders, every engine': 'Реальні рендери, кожен рушій',
  'Type an idea — watch it become a film.': 'Напишіть ідею — дивіться, як вона стає фільмом.',
  'Start with the full toolkit': 'Почніть із повного набору інструментів',
  'Kineo’s own engine — 3–7 min': 'Власний рушій Kineo — 3–7 хв',
  'The workhorse AI video engine': 'Робочий кінь серед AI-відеорушіїв',
  'Cinematic motion & camera': 'Кінематографічний рух і камера',
  'Film scenes, native voice & lip sync': 'Кіносцени, рідний голос і синхронізація губ',
  'Talking video from one photo': 'Відео, що говорить, з одного фото',
  'From idea to posted Short in 3 steps.': 'Від ідеї до опублікованого Short за 3 кроки.',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'Без зйомки, без монтажу, без таймлайну. Напишіть один раз — Kineo зробить решту.',
  'Step 1': 'Крок 1',
  'Kineo builds it': 'Kineo збирає',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'AI пише сценарій, вибудуваний під утримання, записує озвучку, добирає кадри й вшиває субтитри — готове відео 9:16.',
  'Download & post': 'Завантажте й опублікуйте',
  'Why Kineo': 'Чому Kineo',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'Більшість інструментів перенарізають довге відео, яке ви вже зняли. Kineo збирає його з нуля.',
  'See how to make Shorts without filming →': 'Як робити Shorts без зйомки →',
  'Generates the Short from just an idea': 'Створює Short з однієї ідеї',
  'Writes the script for you': 'Пише сценарій за вас',
  'Finds and matches footage': 'Знаходить і добирає кадри',
  'your upload': 'ваше завантаження',
  'AI image studio included': 'Студія AI-зображень включена',
  'Voice studio (text-to-speech)': 'Голосова студія (текст у мовлення)',
  'One-click HD film enhance': 'HD-покращення фільму в один клік',
  'One idea — or a whole toolkit.': 'Одна ідея — або цілий набір інструментів.',
  'Try AI Presenter →': 'Спробувати AI-ведучого →',
  'Transparent Clips': 'Прозорі кліпи',
  'UGC Product Ads': 'UGC-реклама товарів',
  'Animate a photo →': 'Оживити фото →',
  'Make a thumbnail →': 'Зробити прев’ю →',
  'Free AI Shorts': 'Безкоштовні AI Shorts',
  'Start with a niche that already works.': 'Почніть із ніші, яка вже працює.',
  'Not sure? Take the quiz →': 'Не впевнені? Пройдіть тест →',
  'Pick your engine. Ship a Short today.': 'Оберіть рушій. Опублікуйте Short сьогодні.',
  'Cancel anytime': 'Скасування будь-коли',
  'Generate image →': 'Створити зображення →',
  'Generate audio →': 'Створити аудіо →',
  'Paid plans unlock clean MP4s.': 'Платні плани відкривають чисті MP4.',
  'Best for starting out': 'Найкращий для старту',
  'Best value per film': 'Найкраща ціна за фільм',
  'on Nano Banana': 'на Nano Banana',
  'Every video engine incl. MiniMax H3': 'Усі відеорушії, включно з MiniMax H3',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'MP4 без водяного знака · 100 проєктів · зберігання 90 днів',
  ', finished': ', готово',
  '— every engine unlocked': '— усі рушії відкриті',
  '· voice + karaoke captions + score': '· голос + караоке-субтитри + музика',
  '500 projects · forever storage': '500 проєктів · зберігання назавжди',
  'Cancel anytime — 7-day money-back': 'Скасування будь-коли — повернення грошей 7 днів',
  'films on Omni Flash': 'фільмів на Omni Flash',
  '· 2 free HD enhances / month': '· 2 безкоштовні HD-покращення / місяць',
  'Unlimited projects · forever storage': 'Необмежені проєкти · зберігання назавжди',
  'Everything in Creator': 'Усе з Creator',
  'Calculate your cost per Short →': 'Розрахуйте вартість одного Short →',
  'How much do Shorts pay? →': 'Скільки платять за Shorts? →',
  'Highest-RPM niches →': 'Ніші з найвищим RPM →',
  'read the full review →': 'читати повний огляд →',
  'a single line is enough — or paste a full script': 'достатньо одного рядка — або вставте повний сценарій',
  '1080×1920 · Full HD master': '1080×1920 · майстер Full HD',
  'Every film is delivered as a 1080×1920 Full HD master (engines render natively at 720–768p and are mastered up). For maximum sharpness, run ✨HD Enhance on the finished film.': 'Кожен фільм видається як майстер 1080×1920 Full HD (рушії рендерять нативно у 720–768p і мастеряться вгору). Для максимальної різкості запустіть ✨HD Enhance на готовому фільмі.',
  'Your idea first. Review the settings, then generate.': 'Спершу ваша ідея. Перевірте налаштування, потім створіть.',
  '📷 Photo': '📷 Фото',
  '🖼️ Upload a different photo': '🖼️ Завантажити інше фото',
  '🎙️ Generating…': '🎙️ Генерація…',
  '🎙️ Cloning the voice…': '🎙️ Клонування голосу…',
  '🎙️ Upload a different sample': '🎙️ Завантажити інший зразок',
  '⏹ Stop & clone': '⏹ Зупинити й клонувати',
  '🎭 Generate my avatar video': '🎭 Створити моє відео з аватаром',
  'Continue exactly where ChatGPT stopped.': 'Продовжте рівно з того місця, де зупинився ChatGPT.',
  '✨ Let AI structure it': '✨ Нехай AI структурує',
  'Optional settings': 'Необов’язкові налаштування',
  'optional — a pre-tested move added to your prompt': 'необов’язково — перевірений рух, доданий до вашого промпту',
  'Reference image': 'Референсне зображення',
  '🖼️ Start your video from an image — coming soon': '🖼️ Почати відео із зображення — незабаром',
  'Estimated cost': 'Орієнтовна вартість',
  'Your credits buy': 'На ваші кредити можна',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'Голос, караоке-субтитри й музика включені. Якщо рендер не вдасться, кредити одразу повернуться.',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'Та сама тема, новий хук і розв’язка — ідея вже написана.',
  'Build next episode →': 'Зібрати наступний епізод →',
  'Episode 2 →': 'Епізод 2 →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'AI-ведучий, що говорить, із фото — із синхронізацією губ, у власній студії',
  'Your face. Your script.': 'Ваше обличчя. Ваш сценарій.',
  'Everything you need to make yourself speak — nothing you don’t.': 'Усе, що потрібно, щоб заговорити самому — і нічого зайвого.',
  'BEST MOTION': 'НАЙКРАЩИЙ РУХ',
  '1.5 · Realism': '1.5 · Реалізм',
  '🎬 Put me in a scene': '🎬 Помістити мене в сцену',
  'use original photo': 'використати оригінальне фото',
  '✍️ Say exactly this — word for word': '✍️ Сказати рівно це — слово в слово',
  '✨ Expand into a full Short script (45–60s)': '✨ Розгорнути в повний сценарій Short (45–60 с)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 Режим реклами товару — продати товар у стилі UGC',
  'Free — fills the script box above, then generate with your presenter.': 'Безкоштовно — заповнює поле сценарію вище, потім створіть із вашим ведучим.',
  '2.5 · Speak in your own voice': '2.5 · Говоріть своїм голосом',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ Голос клоновано — озвучка звучатиме цим голосом.',
  'use a default voice': 'використати голос за замовчуванням',
  '🎬 Full video — face the whole time': '🎬 Повне відео — обличчя весь час',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 AI-ведучий — швидко й природно · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro — преміальна якість фото · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 Body Motion — тулуб, руки та жести · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ Класика — говорить голова · 110 cr',
  'you have': 'у вас',
  'to create your avatar video.': 'щоб створити відео з аватаром.',
  '5 · Gesture clips — transparent background': '5 · Кліпи з жестами — прозорий фон',
  'auto-refunded if it fails': 'автоматичне повернення в разі збою',
  '⬇️ Download transparent WebM': '⬇️ Завантажити прозорий WebM',
  '⬇️ Original MP4 (with background)': '⬇️ Оригінальний MP4 (з фоном)',
  'Pick a face to preview': 'Оберіть обличчя для попереднього перегляду',
  '↺ Make another': '↺ Зробити ще',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'Люди, улюбленці, товари, старі сімейні світлини — завантажте фото або вставте публічне посилання на зображення й дивіться, як воно рухається.',
  'The photo': 'Фото',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': 'JPG/PNG до 8 МБ. Публічні посилання безпечно завантажуються та перевіряються на нашому сервері.',
  'sign in': 'увійти',
  'Kineo will fetch and validate it on the server when you animate.': 'Kineo отримає й перевірить його на сервері, коли ви запустите анімацію.',
  'Upload a photo to preview': 'Завантажте фото для попереднього перегляду',
  '🖼️ Upload a photo': '🖼️ Завантажити фото',
  '✨ Bring it to life': '✨ Оживити',
  'Uploading your photo…': 'Завантаження вашого фото…',
  'Bringing your photo to life… (1–3 min)': 'Оживляємо ваше фото… (1–3 хв)',
  'Alive!': 'Ожило!',
  '🌬️ Subtle & real': '🌬️ Тонко й природно',
  '😊 Person comes alive': '😊 Людина оживає',
  'Type your idea first': 'Спершу напишіть ідею',
  '📖 True Story': '📖 Реальна історія',
  'Paste your ChatGPT script': 'Вставте сценарій із ChatGPT',
  'First Short complete': 'Перший Short готовий',
  'Keep your show moving': 'Тримайте своє шоу в русі',
  'Cheapest way to see your idea as a film': 'Найдешевший спосіб побачити свою ідею як фільм',
  'Slow Dolly-In': 'Повільний наїзд',
  'FPV Drone': 'FPV-дрон',
  'Macro Detail': 'Макродеталь',
  'Sharing & creator options': 'Поширення та опції для авторів',
  'We couldn’t load your videos right now': 'Не вдалося завантажити ваші відео просто зараз',
  'Your videos and credits are safe — this is a temporary read hiccup, not a lost library.': 'Ваші відео та кредити в безпеці — це тимчасовий збій читання, а не втрачена бібліотека.',
  '⚡ Generate Video': '⚡ Створити відео',
  'Prefer clean exports now? Starter includes': 'Хочете чисті експорти вже зараз? Starter включає',
  'credits each month for': 'кредитів на місяць за',
  'Your existing files stay available. Starter applies to new exports after checkout.': 'Ваші наявні файли залишаються доступними. Starter діє для нових експортів після оплати.',
  'Build Next Episode First': 'Спершу зібрати наступний епізод',
  'Video unavailable': 'Відео недоступне',
  'Free MP4 includes the Kineo watermark': 'Безкоштовний MP4 містить водяний знак Kineo',
  'Free distribution · latest Short': 'Безкоштовне поширення · останній Short',
  'Send it to one person for feedback': 'Надішліть одній людині для відгуку',
  'Copy a public watch page for your finished video. Your friend can watch it without logging in, then use “Make one like this” if the idea inspires them.': 'Скопіюйте публічну сторінку перегляду готового відео. Друг подивиться без входу, а потім може натиснути «Зробити таке саме», якщо ідея надихне.',
  'Public watch links are temporarily paused': 'Публічні посилання на перегляд тимчасово призупинені',
  'Your video stays in your account. Download the MP4 if you want to send it directly; Kineo will not publish a public page without an explicit visibility choice.': 'Відео залишається у вашому акаунті. Завантажте MP4, якщо хочете надіслати напряму; Kineo не публікує публічну сторінку без явного вибору видимості.',
  'Loading…': 'Завантаження…',
  'For new videos ·': 'Для нових відео ·',
  'Published it?': 'Опублікували?',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'Чітко, анфас, одна людина. Для руху тіла використовуйте фото по пояс або на повний зріст з обома видимими руками. Чорні смуги прибираються автоматично.',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'Найкращий професійний результат: завантажте вертикальний кліп 5–20 с із потрібними реальними жестами, приблизно рівний за довжиною сценарію. Sync-3 замінює мовлення, зберігаючи реальне обличчя й рухи. MP4/MOV до 40 МБ.',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'Підтверджую, що маю право використовувати зображення цієї людини, і погоджуюся на її анімацію за допомогою AI.',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': 'Завантажте чистий зразок голосу ~30-60 с (один мовець, мало фонового шуму), і озвучка звучатиме цим голосом. Використовуйте лише голос, на який маєте права.',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'Відео слово в слово показують ваше обличчя весь час (вони короткі — b-roll не потрібен).',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'Відео з максимальним реалізмом і побудованою сценою тримають ведучого в кадрі всю озвучку.',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ Вступ-хук — ви відкриваєте, історію розповідає b-roll',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'Короткі кліпи вашого ведучого: махає, вказує, презентує — у форматі WebM зі СПРАВЖНІМ прозорим фоном. Вставляйте прямо в Storyline, Premiere, CapCut або будь-який слайд. Без хромакею, без кеїнгу.',
  'Cinematic film — 9-image consistency': 'Кінематографічний фільм — узгодженість 9 кадрів',
  '#1-ranked video model — Aug 2026 arena': 'Відеомодель № 1 у рейтингу — арена, серп 2026',
  'Cinematic motion and camera work': 'Кінематографічний рух і робота камери',
  'Shorts money & growth': 'Гроші та зростання на Shorts',
  'Compare Kineo with 27 AI video tools →': 'Порівняйте Kineo з 27 AI-відеоінструментами →',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'Ведучі, що говорять, багаторазові персонажі, прозорі кліпи, реклама товарів — плюс усе, щоб знайти тренд і осідлати його.',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'Одне фото + ваш сценарій — відео, що говорить, зі студійною синхронізацією губ, у стилі HeyGen.',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'Збережіть персонажа один раз — точно те саме обличчя в кожному відео та прев’ю.',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'Жести ведучого — помахати, вказати, представити — у WebM зі справжнім прозорим фоном.',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'Вставте будь-який товар — отримайте рекламу 15-30 с у стилі блогера, зі сценарієм і озвучкою.',
  'Bring any still photo to life as a moving, postable video.': 'Оживіть будь-яку статичну світлину як рухоме відео, готове до публікації.',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'Клікабельні прев’ю в стилі найбільших каналів — з одного промпту.',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'Кожна ніша нижче має свою сторінку генератора, налаштовані промпти й реальні приклади.',
  'Is the video really mine to post?': 'Відео справді моє, і я можу його публікувати?',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'Платні плани відкривають чистий MP4 без водяного знака для YouTube, TikTok або Reels.',
  'Do I need any editing skills?': 'Чи потрібні навички монтажу?',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'Ні. Ви пишете одну ідею, а AI пише сценарій, записує голос, знаходить кадри й додає субтитри.',
  'Is there a watermark?': 'Чи є водяний знак?',
  'Paid plans export clean, watermark-free MP4s.': 'Платні плани експортують чисті MP4 без водяного знака.',
  'Can Kineo also generate images and voiceovers?': 'Kineo також створює зображення та озвучку?',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'Так — у Kineo є студія AI-зображень (6 рушіїв, включно з FLUX, Seedream і Nano Banana Pro, від 1 кредиту за зображення) і голосова студія з 4 рушіями текст-у-мовлення (від 1 кредиту за 1000 символів). Усе, що ви створюєте, живе у вашій Бібліотеці.',
  'Can I make my videos sharper?': 'Чи можна зробити відео різкішим?',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'У кожного відео є покращення в один клік на базі реставрації плівки Topaz — прибирає артефакти стиснення, відновлює деталі й додає тонке кінематографічне зерно. 10 кредитів за відео; план Studio включає 2 безкоштовні покращення на місяць.',
  'Can I use my own script?': 'Чи можна використати свій сценарій?',
  'What if a generation fails?': 'А якщо генерація не вдасться?',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'Кредити повертаються автоматично в момент збою рендера — без тікета, без очікування. Ви платите лише за відео, які справді отримуєте.',
  'Can I cancel anytime?': 'Чи можна скасувати будь-коли?',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'Будь-коли, в один клік. Плани помісячні, кредити оновлюються щомісяця.',
  'Can I run a whole channel with the same host?': 'Чи можна вести цілий канал з одним і тим самим ведучим?',
  'Can I monetize the videos?': 'Чи можна монетизувати відео?',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'Так. Кожне відео ваше — зберігайте, публікуйте й монетизуйте, включно з партнерською програмою YouTube, TikTok і Reels. Додаткова ліцензія не потрібна.',
  'Can I use the videos commercially, or for client work?': 'Чи можна використовувати відео комерційно або для клієнтів?',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'Так. Наші умови дозволяють використовувати Kineo із законною особистою або комерційною метою й підтверджують, що ви зберігаєте право власності на створені відео, тож можете їх публікувати, монетизувати й передавати клієнту в межах власної платної послуги. Без додаткової ліцензії та роялті за відео. З тих самих умов випливають два обмеження: не можна перепродавати або поширювати сам Kineo, а стокові кліпи всередині рендера ліцензовані для використання у вашому готовому відео, а не для повторного завантаження як самостійний сток. Платні плани експортують чистий MP4 без водяного знака.',
  'How long does one video take?': 'Скільки часу займає одне відео?',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'Режим Fast зазвичай завершується за 3–7 хвилин. AI-згенеровані та кінематографічні відео займають трохи більше, бо кожна сцена генерується до збирання фінального MP4.',
  'How much does Kineo cost?': 'Скільки коштує Kineo?',
  'Kineo has three monthly plans: Starter at $': 'У Kineo три місячні плани: Starter за $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'кредитів. Кредити витрачаються на кожне відео, а вартість відео залежить від обраного рушія, тож рендер Fast і кінематографічний фільм списуються з одного балансу за дуже різними ставками.',
  'Which AI video engines can I use in Kineo?': 'Які AI-відеорушії можна використовувати в Kineo?',
  ', behind one interface and one balance:': ', за одним інтерфейсом і одним балансом:',
  'What is the best AI video generator for faceless YouTube channels?': 'Який AI-відеогенератор найкращий для безликих YouTube-каналів?',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'Так. Безкоштовні користувачі, які ніколи не платили, можуть завантажувати, ділитися й публікувати MP4 з водяним знаком.',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'Пробні фільми мають невеликий водяний знак — MP4 можна завантажити, надіслати й опублікувати. Після пробного періоду безкоштовне відео Fast має водяний знак.',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'Безкоштовні завантаження мають водяний знак; платні плани відкривають чистий MP4.',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'Пробні завантаження мають водяний знак, як і безкоштовне відео Fast після пробного періоду, а платні плани завжди експортують чисто.',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'Безкоштовний доступ дає новим користувачам до 3 відео Fast з водяним знаком кожні 24 години, без картки. Їх можна завантажувати й надсилати.',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'Створюйте, завантажуйте й діліться до 3 відео Fast з водяним знаком кожні 24 год, без картки.',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'Створюйте, дивіться, завантажуйте й діліться до 3 відео Fast з водяним знаком кожні 24 год — без картки.',
  'create, watch, download and share up to 3 Fast videos every 24h': 'створюйте, дивіться, завантажуйте й діліться до 3 відео Fast кожні 24 год',
  '— no card, watermark included.': '— без картки, з водяним знаком.',
  'AI image generator — 6 engines': 'AI-генератор зображень — 6 рушіїв',
  'AI voice generator (text to speech)': 'AI-генератор голосу (текст у мовлення)',
  'AI video upscaler & enhancer': 'AI-апскейлер і покращувач відео',
  'Trending Shorts ideas today': 'Ідеї для Shorts у тренді сьогодні',
  'AI Avatar video — your face, any script': 'Відео з AI-аватаром — ваше обличчя, будь-який сценарій',
  'Kineo facts & numbers (citable)': 'Факти й цифри Kineo (можна цитувати)',
  'Free AI Shorts generator': 'Безкоштовний генератор AI Shorts',
  'YouTube Shorts from a topic': 'YouTube Shorts із теми',
  'ChatGPT script to YouTube Short': 'Сценарій ChatGPT у YouTube Short',
  'Shorts without filming': 'Shorts без зйомки',
  'Faceless niche picker': 'Підбір безликої ніші',
  'State of AI Shorts 2026': 'Стан AI Shorts 2026',
  'AI Shorts for agencies & client work': 'AI Shorts для агенцій і клієнтів',
  'Trust Center — privacy, payments & ownership': 'Центр довіри — приватність, платежі та права',
  'Affiliate program - 30% recurring': 'Партнерська програма - 30% регулярно',
  'Free AI Shorts by niche': 'Безкоштовні AI Shorts за нішами',
  'Free script generator': 'Безкоштовний генератор сценаріїв',
  'Product video ad script': 'Сценарій відеореклами товару',
  'Client video brief generator': 'Генератор відеобрифу для клієнта',
  'Free hook generator': 'Безкоштовний генератор хуків',
  'Shorts script timer': 'Таймер сценарію Shorts',
  'Shorts money calculator': 'Калькулятор доходу зі Shorts',
  'How much do Shorts pay?': 'Скільки платять за Shorts?',
  'Best AI Shorts generators': 'Найкращі генератори AI Shorts',
  'TikTok vs Shorts: which pays more?': 'TikTok vs Shorts: де платять більше?',
  'All comparisons': 'Усі порівняння',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · Усі права захищено',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'Залежить від того, чи потрібні вам зібрані стокові кадри, чи згенеровані. Інструменти на кшталт InVideo та AutoShorts нарізають стокові кліпи під ваш сценарій — це дешевше й підходить для відео з тезами. Kineo генерує кадри моделями на кшталт Veo 3.1 і Kling 3, зберігає вашу озвучку слово в слово замість переписування й цілить у 60 секунд і більше, щоб відео підходило під TikTok Creator Rewards. Якщо ваш канал живе на візуалі, якого більше ні в кого немає, генерація виграє; якщо на обсязі — сток дешевший.',
  'Paste the complete script from ChatGPT here…': 'Вставте сюди повний сценарій із ChatGPT…',
  'Paste the idea from ChatGPT here…': 'Вставте сюди ідею із ChatGPT…',
  'What’s your video about? One idea in — a finished film out: voiced, scored and captioned.': 'Про що ваше відео? Одна ідея на вході — готовий фільм на виході: з голосом, музикою та субтитрами.',
  'Settings and generation': 'Налаштування та генерація',
  'Search your videos…': 'Шукати у ваших відео…',
  'Search your audio…': 'Шукати у вашому аудіо…',
  'Search your images by engine': 'Шукати зображення за рушієм',
  'No playable videos in your library yet. Check your latest project above.': 'У бібліотеці поки немає відтворюваних відео. Перевірте свій останній проєкт вище.',
  'Make a finished Short →': 'Зробити готовий Short →',
  'Video Editing & Creator Tools': 'Відеомонтаж та інструменти для авторів',
  'Trim, resize, change speed, mute or add text. Edit a file you already have, right in your browser. Your script and planning tools are still here below.': 'Обріжте, змініть розмір і швидкість, приберіть звук або додайте текст. Редагуйте вже наявний файл прямо в браузері. Інструменти для сценарію та планування як і раніше нижче.',
  '5 local editing tools': '5 локальних інструментів монтажу',
  'No generation credits to edit': 'Монтаж не витрачає кредити генерації',
  'Edit video': 'Редагувати відео',
  'Files up to 100 MB and 3 minutes. Local, real-time export up to 1280 px on the long edge. MP4 or WebM depending on your browser; downloads are not saved to My Videos.': 'Файли до 100 МБ і 3 хвилин. Локальний експорт у реальному часі до 1280 px по довгій стороні. MP4 або WebM залежно від браузера; завантаження не зберігаються в «Мої відео».',
  'Video Trimmer': 'Обрізання відео',
  'Cut the beginning or end and keep only the clip you need.': 'Відріжте початок або кінець і залиште лише потрібний фрагмент.',
  'Video Resizer': 'Зміна розміру відео',
  'Go vertical, square or wide. Fit the frame or crop to fill.': 'Вертикально, квадрат або широко. Вписати в кадр або обрізати до заповнення.',
  'Video Speed Changer': 'Зміна швидкості відео',
  'Slow it down or speed it up, from 0.5× to 2×.': 'Сповільніть або пришвидшіть, від 0.5× до 2×.',
  'Remove Audio': 'Прибрати звук',
  'Download a copy without the original audio.': 'Завантажте копію без оригінального звуку.',
  'Add Text to Video': 'Додати текст на відео',
  'Add a title or message that stays on screen. Not automatic subtitles.': 'Додайте заголовок або повідомлення, яке залишається на екрані. Не автоматичні субтитри.',
  'No account · current Kineo plans': 'Без акаунта · поточні плани Kineo',
  'No account · fair-use limit': 'Без акаунта · ліміт добросовісного використання',
  'No account · unlimited in browser': 'Без акаунта · без обмежень у браузері',
  'Edit an existing video here. Create a new one with Kineo.': 'Редагуйте тут наявне відео. Нове створіть із Kineo.',
  'Create an AI video →': 'Створити AI-відео →',
  'Edit your video, preview the changes, then export a copy.': 'Відредагуйте відео, перегляньте зміни, потім експортуйте копію.',
  'Video preview': 'Попередній перегляд відео',
  'Preview is silent. The download keeps audio unless Mute is selected.': 'Попередній перегляд без звуку. У завантаженні звук зберігається, якщо не обрано «Без звуку».',
  'Start with your video': 'Почніть зі свого відео',
  'Choose a local file. It stays on this device.': 'Оберіть локальний файл. Він залишається на цьому пристрої.',
  'Choose video file': 'Обрати відеофайл',
  'Video file': 'Відеофайл',
  'Video settings': 'Налаштування відео',
  'Aspect ratio': 'Співвідношення сторін',
  'Playback speed': 'Швидкість відтворення',
  'On-screen text (100 characters, 3 lines)': 'Текст на екрані (100 символів, 3 рядки)',
  'Add a title or message': 'Додайте заголовок або повідомлення',
  'Export edited video': 'Експортувати відредаговане відео',
  'Export happens in real time. Keep this tab visible. Re-encoded at up to 1280 px on the long edge; format depends on your browser.': 'Експорт іде в реальному часі. Тримайте цю вкладку видимою. Перекодовується до 1280 px по довгій стороні; формат залежить від браузера.',
  'Making a 4-second sample on your device…': 'Створюємо 4-секундний зразок на вашому пристрої…',
  'Reading your file…': 'Читаємо ваш файл…',
  'Export result': 'Результат експорту',
  'Your edited video': 'Ваше відредаговане відео',
  'Local download only. This copy is not saved to My Videos.': 'Лише локальне завантаження. Ця копія не зберігається в «Мої відео».',
  'Exported video': 'Експортоване відео',
  'No upload. No generation credits. Your original is never overwritten.': 'Без завантаження на сервер. Без кредитів генерації. Оригінал ніколи не перезаписується.',
  'Up to 100 MB · 3 minutes · MP4/WebM input recommended. These are basic editing tools, not the CapCut app.': 'До 100 МБ · 3 хвилини · рекомендовано вхід MP4/WebM. Це базові інструменти монтажу, а не застосунок CapCut.',
  'Need a new video? Open Kineo Studio →': 'Потрібне нове відео? Відкрийте Kineo Studio →',
  'This browser cannot export video here. Try the latest desktop Chrome or Edge.': 'Цей браузер не може експортувати відео тут. Спробуйте останній Chrome або Edge на комп’ютері.',
  'Choose a non-empty video file of up to 100 MB.': 'Оберіть непорожній відеофайл до 100 МБ.',
  'Use a playable clip of up to 3 minutes. Very large dimensions are not supported.': 'Використовуйте відтворюваний кліп до 3 хвилин. Дуже великі розміри не підтримуються.',
  'Check the start and end: select at least 0.25 seconds within your clip.': 'Перевірте початок і кінець: виділіть щонайменше 0.25 секунди всередині кліпу.',
  'Choose a speed between 0.5× and 2×.': 'Оберіть швидкість від 0.5× до 2×.',
  'Use up to 100 characters and 3 lines of text.': 'Використовуйте не більше 100 символів і 3 рядків тексту.',
  'Choose a supported aspect ratio, framing and text position.': 'Оберіть підтримуване співвідношення сторін, кадрування та положення тексту.',
  'This file could not be decoded. Try an MP4 (H.264) or WebM file.': 'Не вдалося декодувати цей файл. Спробуйте MP4 (H.264) або WebM.',
  'Export stopped because this tab was hidden. Keep it open and visible, then export again. Your original is safe.': 'Експорт зупинено, бо вкладка була прихована. Тримайте її відкритою й видимою, потім експортуйте знову. Оригінал у безпеці.',
  'Export stopped making progress. Try a shorter clip or desktop Chrome. Your original is unchanged.': 'Експорт перестав просуватися. Спробуйте коротший кліп або Chrome на комп’ютері. Оригінал не змінено.',
  'Audio could not start. Try exporting again, or choose Mute video.': 'Не вдалося запустити звук. Спробуйте експортувати знову або оберіть «Відео без звуку».',
  'The browser blocked playback. Try exporting again from this tab.': 'Браузер заблокував відтворення. Спробуйте експортувати знову з цієї вкладки.',
  'Cancelled. Your original file is unchanged.': 'Скасовано. Оригінальний файл не змінено.',
  'Could not finish this export. Try a shorter clip or another supported browser.': 'Не вдалося завершити експорт. Спробуйте коротший кліп або інший підтримуваний браузер.',
  'The browser produced an incomplete file, so we did not offer it for download. Try again with this tab visible, or use desktop Chrome.': 'Браузер створив неповний файл, тому ми не запропонували його для завантаження. Спробуйте знову з видимою вкладкою або використайте Chrome на комп’ютері.',
  'Create new video': 'Створити нове відео',
  'Your idea': 'Ваша ідея',
  'Natural': 'Природний',
  'Working…': 'Працюємо…',
  '🎲 Surprise me': '🎲 Здивуйте мене',
  '📝 Use my script as is': '📝 Використати мій сценарій як є',
  'Camera preset': 'Пресет камери',
  'Your latest videos': 'Ваші останні відео',
  'Presenter': 'Ведучий',
  '1 · Who’s talking': '1 · Хто говорить',
  '🎭 your characters': '🎭 ваші персонажі',
  '🎯 Max realism — animate my real photo': '🎯 Максимальний реалізм — оживити моє реальне фото',
  '✓ Scene ready — preview on the right.': '✓ Сцена готова — попередній перегляд праворуч.',
  '2 · What they say': '2 · Що говорять',
  '3 · How it looks': '3 · Як виглядає',
  'Motion': 'Рух',
  '⬇ Download MP4': '⬇ Завантажити MP4',
  'One photo. Suddenly alive.': 'Одне фото. Раптом живе.',
  'Cost per clip': 'Вартість за кліп',
  '↺ Animate another': '↺ Оживити ще',
  'Grow': 'Зростати',
  'Sending to the motion engine…': 'Надсилаємо в рушій руху…',
  '📊 Facts': '📊 Факти',
  'Turn it into episode 2': 'Перетворити на епізод 2',
  'Start here': 'Почніть тут',
  'Engine': 'Рушій',
  'Highly aesthetic, by xAI': 'Дуже естетичний, від xAI',
  'Google’s best image model': 'Найкраща модель зображень Google',
  'AI voiceover included': 'AI-озвучка включена',
  '6 engines': '6 рушіїв',
  'AI Presenter': 'AI-ведучий',
  'Lock a character →': 'Закріпити персонажа →',
  'Make a clip →': 'Зробити кліп →',
  'Make an ad →': 'Зробити рекламу →',
  'Generate free →': 'Створити безкоштовно →',
  'Creating…': 'Створюємо…',
  'Describe your image first': 'Спершу опишіть зображення',
  'Type your script first': 'Спершу напишіть сценарій',
  'From the founder': 'Від засновника',
  'Faceless video generator': 'Генератор безликих відео',
  'Text to video Shorts': 'Shorts із тексту у відео',
  'Cheapest AI Shorts maker': 'Найдешевший творець AI Shorts',
  'Faceless channel ideas (2026)': 'Ідеї безликих каналів (2026)',
  'Shorts idea widget': 'Віджет ідей для Shorts',
  'Live case study: our channel on Autopilot': 'Живий кейс: наш канал на Autopilot',
  'Free YouTube Shorts scripts': 'Безкоштовні сценарії YouTube Shorts',
  'Comment to Short script': 'З коментаря у сценарій Short',
  'Business video content planner': 'Планувальник відеоконтенту для бізнесу',
  'Real estate video maker': 'Творець відео про нерухомість',
  'Shorts title & hashtag generator': 'Генератор заголовків і хештегів для Shorts',
  'Free viral score': 'Безкоштовна оцінка віральності',
  'Make money clipping with AI': 'Заробляйте на кліпах з AI',
  'Shorts RPM by niche (2026)': 'RPM Shorts за нішами (2026)',
  'Can you monetize AI videos?': 'Чи можна монетизувати AI-відео?',
}
