// KINEO-INTERFACE-16-LINGUAS-2026-09-21 — interface em ur. Só copy autoral da interface: nunca prompt,
// título, resultado, nome de motor ou erro de API. Frase fora daqui cai em inglês (components/InterfaceLanguage.tsx).
// Gerado de scratchpad/tr-ur.js sobre o corpus vivo de frases (415); números e "Kineo" preservados por construção.
export const DICT: Record<string, string> = {
  'Videos for businesses': 'کاروبار کے لیے ویڈیوز',
  // KINEO-NAV-4-ITENS-2026-09-25 — rótulos do menu de 4 itens (decisão do fundador 24/09).
  'Create video': 'ویڈیو بنائیں',
  'For businesses': 'کاروبار کے لیے',
  'More tools': 'مزید ٹولز',
  'Ads': 'اشتہارات',
  'Log in': 'لاگ ان کریں',
  'More': 'مزید',
  'Scripts': 'اسکرپٹس',
  'Animate': 'اینیمیٹ کریں',
  'Examples': 'مثالیں',
  'Pricing': 'قیمتیں',
  'Library': 'لائبریری',
  'Generation failed': 'جنریشن ناکام ہو گئی',
  'You can retry safely.': 'آپ بلا خطر دوبارہ کوشش کر سکتے ہیں۔',
  'This engine is not available on your account right now': 'یہ انجن اس وقت آپ کے اکاؤنٹ پر دستیاب نہیں ہے',
  'Retrying the same engine will stop at this same place. Pick another engine to keep going.': 'اسی انجن سے دوبارہ کوشش اسی جگہ رک جائے گی۔ جاری رکھنے کے لیے دوسرا انجن چنیں۔',
  'The engine is cooling down after two refunded attempts': 'دو رقم واپس شدہ کوششوں کے بعد انجن ٹھنڈا ہو رہا ہے',
  'Starting another one right now stops at this same place. Give it a few minutes.': 'ابھی ایک اور شروع کرنا اسی جگہ رک جاتا ہے۔ اسے چند منٹ دیں۔',
  'Starting another one right now stops at this same place. The button below unlocks by itself.': 'ابھی ایک اور شروع کرنا اسی جگہ رک جاتا ہے۔ نیچے کا بٹن خود کھل جاتا ہے۔',
  'We stopped waiting on this render instead of leaving you hanging': 'ہم نے آپ کو انتظار میں چھوڑنے کے بجائے اس رینڈر کا انتظار روک دیا',
  'This one ran far longer than any video that finishes here. Starting again is worth it.': 'یہ یہاں مکمل ہونے والی کسی بھی ویڈیو سے کہیں زیادہ دیر چلا۔ دوبارہ شروع کرنا فائدہ مند ہے۔',
  'The video engine is busy — this is on our side, not your idea': 'ویڈیو انجن مصروف ہے — مسئلہ ہماری طرف ہے، آپ کے آئیڈیا میں نہیں',
  'Nothing about your text is wrong. Trying again in a few minutes usually goes straight through.': 'آپ کے متن میں کچھ غلط نہیں۔ چند منٹ بعد دوبارہ کوشش عموماً سیدھی کامیاب ہوتی ہے۔',
  'Create Video': 'ویڈیو بنائیں',
  'Create a new video': 'نئی ویڈیو بنائیں',
  'AI Avatar Studio': 'AI اوتار اسٹوڈیو',
  'Viral Templates': 'وائرل ٹیمپلیٹس',
  'Channel Builder': 'چینل بلڈر',
  'Invite & Earn': 'مدعو کریں اور کمائیں',
  'Start free': 'مفت شروع کریں',
  'Try 7 days for $1': '7 دن $1 میں آزمائیں',
  'Pick a lane': 'ایک راستہ چنیں',
  'All free tools': 'تمام مفت ٹولز',
  'Terms of Service': 'شرائطِ خدمت',
  'Trust Center': 'ٹرسٹ سینٹر',
  'Review & publish': 'جائزہ لیں اور شائع کریں',
  'Your image': 'آپ کی تصویر',
  'Cost per image': 'فی تصویر لاگت',
  'No videos yet': 'ابھی کوئی ویڈیو نہیں',
  'No audio yet': 'ابھی کوئی آڈیو نہیں',
  '🎬 Studio — generate video': '🎬 Studio — ویڈیو بنائیں',
  '🎨 Images — create image': '🎨 تصاویر — تصویر بنائیں',
  '🎙 Audio — text to speech': '🎙 آڈیو — متن سے آواز',
  'Type it. See it. Six image engines, one screen.': 'لکھیں۔ دیکھیں۔ چھ امیج انجن، ایک اسکرین۔',
  'Type it. Hear it. Four voice engines, one screen.': 'لکھیں۔ سنیں۔ چار وائس انجن، ایک اسکرین۔',
  'Everything you’ve created, in one place.': 'آپ نے جو کچھ بنایا، ایک جگہ پر۔',
  'Add credits →': 'کریڈٹس شامل کریں →',
  'Upscale any result to 2x for 1 credit.': 'کسی بھی نتیجے کو 1 کریڈٹ میں 2x بڑا کریں۔',
  'We couldn’t load your images right now.': 'ہم ابھی آپ کی تصاویر لوڈ نہیں کر سکے۔',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'آپ کی تصاویر اور کریڈٹس محفوظ ہیں — یہ صرف عارضی ریڈنگ کا مسئلہ ہے۔',
  'We couldn’t load your audio right now.': 'ہم ابھی آپ کا آڈیو لوڈ نہیں کر سکے۔',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'آپ کا آڈیو اور کریڈٹس محفوظ ہیں — یہ صرف عارضی ریڈنگ کا مسئلہ ہے۔',
  'We couldn’t load part of your library right now.': 'ہم ابھی آپ کی لائبریری کا کچھ حصہ لوڈ نہیں کر سکے۔',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'آپ کی ویڈیوز اور کریڈٹس محفوظ ہیں — یہ صرف عارضی ریڈنگ کا مسئلہ ہے۔',
  '↻ Try again': '↻ دوبارہ کوشش کریں',
  '⬇ Download': '⬇ ڈاؤن لوڈ',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': 'کوئی آواز پسند آئی؟ Studio اس کے گرد پوری فلم بناتا ہے — مناظر، کیپشن اور موسیقی۔',
  'Open Studio →': 'Studio کھولیں →',
  'open the Studio': 'Studio کھولیں',
  'Next episode →': 'اگلی قسط →',
  'create your first image': 'اپنی پہلی تصویر بنائیں',
  'generate your first voiceover': 'اپنا پہلا وائس اوور بنائیں',
  'Instant drafts': 'فوری مسودے',
  'Deep prompt understanding': 'پرامپٹ کی گہری سمجھ',
  'Perfect text rendering': 'بے عیب ٹیکسٹ رینڈرنگ',
  'Create Image': 'تصویر بنائیں',
  'Click-magnet YouTube covers': 'کلک کھینچنے والے YouTube کور',
  'Bring any image to life': 'کسی بھی تصویر میں جان ڈالیں',
  'Instant narration': 'فوری بیانیہ',
  'Four voice engines': 'چار وائس انجن',
  'A face that speaks your script': 'ایک چہرہ جو آپ کا اسکرپٹ بولتا ہے',
  'Every control, one screen': 'ہر کنٹرول، ایک اسکرین',
  'Today’s trending topics': 'آج کے ٹرینڈنگ موضوعات',
  'Real renders, every engine': 'حقیقی رینڈرز، ہر انجن',
  'Type an idea — watch it become a film.': 'ایک آئیڈیا لکھیں — اسے فلم بنتے دیکھیں۔',
  'Start with the full toolkit': 'مکمل ٹول کٹ کے ساتھ شروع کریں',
  'Kineo’s own engine — 3–7 min': 'Kineo کا اپنا انجن — 3–7 منٹ',
  'The workhorse AI video engine': 'روزمرہ کا AI ویڈیو انجن',
  'Cinematic motion & camera': 'سینمائی حرکت اور کیمرہ',
  'Film scenes, native voice & lip sync': 'فلمی مناظر، اصل آواز اور لب سنک',
  'Talking video from one photo': 'ایک تصویر سے بولتی ویڈیو',
  'From idea to posted Short in 3 steps.': 'آئیڈیا سے شائع شدہ Short تک 3 مراحل میں۔',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'نہ فلمنگ، نہ ایڈیٹنگ، نہ ٹائم لائن۔ ایک بار لکھیں — باقی Kineo کرتا ہے۔',
  'Step 1': 'مرحلہ 1',
  'Kineo builds it': 'Kineo اسے بناتا ہے',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'AI ریٹینشن پر مبنی اسکرپٹ لکھتا ہے، وائس اوور ریکارڈ کرتا ہے، فوٹیج ملاتا ہے اور کیپشن لگاتا ہے — ایک مکمل 9:16 ویڈیو۔',
  'Download & post': 'ڈاؤن لوڈ کریں اور پوسٹ کریں',
  'Why Kineo': 'Kineo کیوں',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'زیادہ تر ٹولز آپ کی پہلے سے فلمائی لمبی ویڈیو کو دوبارہ کاٹتے ہیں۔ Kineo اسے صفر سے بناتا ہے۔',
  'See how to make Shorts without filming →': 'دیکھیں فلمنگ کے بغیر Shorts کیسے بنائیں →',
  'Generates the Short from just an idea': 'صرف ایک آئیڈیا سے Short بناتا ہے',
  'Writes the script for you': 'آپ کے لیے اسکرپٹ لکھتا ہے',
  'Finds and matches footage': 'فوٹیج تلاش کر کے ملاتا ہے',
  'your upload': 'آپ کا اپ لوڈ',
  'AI image studio included': 'AI امیج اسٹوڈیو شامل',
  'Voice studio (text-to-speech)': 'وائس اسٹوڈیو (متن سے آواز)',
  'One-click HD film enhance': 'ایک کلک میں فلم کی HD بہتری',
  'One idea — or a whole toolkit.': 'ایک آئیڈیا — یا پورا ٹول کٹ۔',
  'Try AI Presenter →': 'AI پریزینٹر آزمائیں →',
  'Transparent Clips': 'شفاف کلپس',
  'UGC Product Ads': 'UGC پروڈکٹ اشتہارات',
  'Animate a photo →': 'تصویر کو حرکت دیں →',
  'Make a thumbnail →': 'تھمب نیل بنائیں →',
  'Free AI Shorts': 'مفت AI Shorts',
  'Start with a niche that already works.': 'ایسے نیش سے شروع کریں جو پہلے سے کام کرتا ہے۔',
  'Not sure? Take the quiz →': 'یقین نہیں؟ کوئز کریں →',
  'Pick your engine. Ship a Short today.': 'اپنا انجن چنیں۔ آج ہی Short پوسٹ کریں۔',
  'Cancel anytime': 'کبھی بھی منسوخ کریں',
  'Generate image →': 'تصویر بنائیں →',
  'Generate audio →': 'آڈیو بنائیں →',
  'Paid plans unlock clean MP4s.': 'ادا شدہ پلان صاف MP4 کھولتے ہیں۔',
  'Best for starting out': 'شروعات کے لیے بہترین',
  'Best value per film': 'فی فلم بہترین قیمت',
  'on Nano Banana': 'Nano Banana پر',
  'Every video engine incl. MiniMax H3': 'ہر ویڈیو انجن بشمول MiniMax H3',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'واٹر مارک کے بغیر MP4 · 100 پروجیکٹس · 90 دن اسٹوریج',
  ', finished': '، مکمل',
  '— every engine unlocked': '— ہر انجن کھلا',
  '· voice + karaoke captions + score': '· آواز + کراوکے کیپشن + موسیقی',
  '500 projects · forever storage': '500 پروجیکٹس · ہمیشہ کے لیے اسٹوریج',
  'Cancel anytime — 7-day money-back': 'کبھی بھی منسوخ کریں — 7 دن رقم واپسی',
  'films on Omni Flash': 'فلمیں Omni Flash پر',
  '· 2 free HD enhances / month': '· 2 مفت HD بہتری / ماہ',
  'Unlimited projects · forever storage': 'لامحدود پروجیکٹس · ہمیشہ کے لیے اسٹوریج',
  'Everything in Creator': 'Creator کی ہر چیز',
  'Calculate your cost per Short →': 'اپنی فی Short لاگت نکالیں →',
  'How much do Shorts pay? →': 'Shorts کتنا دیتے ہیں؟ →',
  'Highest-RPM niches →': 'سب سے زیادہ RPM والے نیش →',
  'read the full review →': 'مکمل جائزہ پڑھیں →',
  'a single line is enough — or paste a full script': 'ایک سطر کافی ہے — یا پورا اسکرپٹ پیسٹ کریں',
  '1080×1920 · Full HD master': '1080×1920 · Full HD ماسٹر',
  'Every film is delivered as a 1080×1920 Full HD master (engines render natively at 720–768p and are mastered up). For maximum sharpness, run ✨HD Enhance on the finished film.': 'ہر فلم 1080×1920 Full HD ماسٹر کے طور پر دی جاتی ہے (انجن اصل میں 720–768p پر رینڈر کرتے ہیں اور اوپر ماسٹر کیے جاتے ہیں)۔ زیادہ سے زیادہ وضاحت کے لیے مکمل فلم پر ✨HD Enhance چلائیں۔',
  'Your idea first. Review the settings, then generate.': 'پہلے آپ کا آئیڈیا۔ سیٹنگز دیکھیں، پھر بنائیں۔',
  '📷 Photo': '📷 تصویر',
  '🖼️ Upload a different photo': '🖼️ دوسری تصویر اپ لوڈ کریں',
  '🎙️ Generating…': '🎙️ بن رہا ہے…',
  '🎙️ Cloning the voice…': '🎙️ آواز کلون ہو رہی ہے…',
  '🎙️ Upload a different sample': '🎙️ دوسرا نمونہ اپ لوڈ کریں',
  '⏹ Stop & clone': '⏹ روکیں اور کلون کریں',
  '🎭 Generate my avatar video': '🎭 میری اوتار ویڈیو بنائیں',
  'Continue exactly where ChatGPT stopped.': 'بالکل وہیں سے جاری رکھیں جہاں ChatGPT رکا تھا۔',
  '✨ Let AI structure it': '✨ AI کو ترتیب دینے دیں',
  'Optional settings': 'اختیاری سیٹنگز',
  'optional — a pre-tested move added to your prompt': 'اختیاری — آپ کے پرامپٹ میں شامل پہلے سے آزمودہ حرکت',
  'Reference image': 'حوالہ تصویر',
  '🖼️ Start your video from an image — coming soon': '🖼️ اپنی ویڈیو ایک تصویر سے شروع کریں — جلد آ رہا ہے',
  'Estimated cost': 'تخمینی لاگت',
  'Your credits buy': 'آپ کے کریڈٹس سے ملتا ہے',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'آواز، کراوکے کیپشن اور موسیقی شامل ہیں۔ رینڈر ناکام ہو تو کریڈٹس فوراً واپس آتے ہیں۔',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'وہی موضوع، نیا ہک اور اختتام — آئیڈیا پہلے سے لکھا ہوا آتا ہے۔',
  'Build next episode →': 'اگلی قسط بنائیں →',
  'Episode 2 →': 'قسط 2 →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'ایک تصویر سے بولتا AI پریزینٹر — لب سنک، اپنا اسٹوڈیو',
  'Your face. Your script.': 'آپ کا چہرہ۔ آپ کا اسکرپٹ۔',
  'Everything you need to make yourself speak — nothing you don’t.': 'خود کو بولتا دکھانے کے لیے جو چاہیے سب کچھ — فالتو کچھ نہیں۔',
  'BEST MOTION': 'بہترین حرکت',
  '1.5 · Realism': '1.5 · حقیقت پسندی',
  '🎬 Put me in a scene': '🎬 مجھے ایک منظر میں رکھیں',
  'use original photo': 'اصل تصویر استعمال کریں',
  '✍️ Say exactly this — word for word': '✍️ بالکل یہی کہیں — لفظ بہ لفظ',
  '✨ Expand into a full Short script (45–60s)': '✨ مکمل Short اسکرپٹ میں پھیلائیں (45–60 سیکنڈ)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 پروڈکٹ اشتہار موڈ — UGC انداز میں پروڈکٹ بیچیں',
  'Free — fills the script box above, then generate with your presenter.': 'مفت — اوپر اسکرپٹ باکس بھرتا ہے، پھر اپنے پریزینٹر کے ساتھ بنائیں۔',
  '2.5 · Speak in your own voice': '2.5 · اپنی آواز میں بولیں',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ آواز کلون ہو گئی — بیانیہ اسی آواز میں ہوگا۔',
  'use a default voice': 'ڈیفالٹ آواز استعمال کریں',
  '🎬 Full video — face the whole time': '🎬 مکمل ویڈیو — پورا وقت چہرہ',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 AI پریزینٹر — تیز اور قدرتی · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro — پریمیم تصویری معیار · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 Body Motion — دھڑ، ہاتھ اور اشارے · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ کلاسک — ٹاکنگ ہیڈ · 110 cr',
  'you have': 'آپ کے پاس ہیں',
  'to create your avatar video.': 'اپنی اوتار ویڈیو بنانے کے لیے۔',
  '5 · Gesture clips — transparent background': '5 · اشاروں کے کلپس — شفاف پس منظر',
  'auto-refunded if it fails': 'ناکامی پر خودکار رقم واپسی',
  '⬇️ Download transparent WebM': '⬇️ شفاف WebM ڈاؤن لوڈ کریں',
  '⬇️ Original MP4 (with background)': '⬇️ اصل MP4 (پس منظر کے ساتھ)',
  'Pick a face to preview': 'پیش نظارے کے لیے چہرہ چنیں',
  '↺ Make another': '↺ ایک اور بنائیں',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'لوگ، پالتو جانور، پروڈکٹس، پرانی خاندانی تصاویر — تصویر اپ لوڈ کریں یا عوامی امیج لنک پیسٹ کریں اور اسے حرکت کرتے دیکھیں۔',
  'The photo': 'تصویر',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': '8 MB تک JPG/PNG۔ عوامی لنکس ہمارے سرور پر محفوظ طریقے سے ڈاؤن لوڈ اور تصدیق کیے جاتے ہیں۔',
  'sign in': 'سائن ان کریں',
  'Kineo will fetch and validate it on the server when you animate.': 'جب آپ اینیمیٹ کریں گے تو Kineo اسے سرور پر لا کر تصدیق کرے گا۔',
  'Upload a photo to preview': 'پیش نظارے کے لیے تصویر اپ لوڈ کریں',
  '🖼️ Upload a photo': '🖼️ تصویر اپ لوڈ کریں',
  '✨ Bring it to life': '✨ جان ڈالیں',
  'Uploading your photo…': 'آپ کی تصویر اپ لوڈ ہو رہی ہے…',
  'Bringing your photo to life… (1–3 min)': 'آپ کی تصویر میں جان ڈالی جا رہی ہے… (1–3 منٹ)',
  'Alive!': 'زندہ!',
  '🌬️ Subtle & real': '🌬️ ہلکا اور حقیقی',
  '😊 Person comes alive': '😊 شخص جاندار ہو جاتا ہے',
  'Type your idea first': 'پہلے اپنا آئیڈیا لکھیں',
  '📖 True Story': '📖 سچی کہانی',
  'Paste your ChatGPT script': 'اپنا ChatGPT اسکرپٹ پیسٹ کریں',
  'First Short complete': 'پہلا Short مکمل',
  'Keep your show moving': 'اپنے شو کو چلتا رکھیں',
  'Cheapest way to see your idea as a film': 'اپنے آئیڈیا کو فلم کے طور پر دیکھنے کا سستا ترین طریقہ',
  'Slow Dolly-In': 'آہستہ ڈولی اِن',
  'FPV Drone': 'FPV ڈرون',
  'Macro Detail': 'میکرو تفصیل',
  'Sharing & creator options': 'شیئرنگ اور کریئیٹر آپشنز',
  'We couldn’t load your videos right now': 'ہم ابھی آپ کی ویڈیوز لوڈ نہیں کر سکے',
  'Your videos and credits are safe — this is a temporary read hiccup, not a lost library.': 'آپ کی ویڈیوز اور کریڈٹس محفوظ ہیں — یہ عارضی ریڈنگ کا مسئلہ ہے، کھوئی ہوئی لائبریری نہیں۔',
  '⚡ Generate Video': '⚡ ویڈیو بنائیں',
  'Prefer clean exports now? Starter includes': 'ابھی صاف ایکسپورٹ چاہیے؟ Starter میں شامل ہے',
  'credits each month for': 'کریڈٹس ہر ماہ برائے',
  'Your existing files stay available. Starter applies to new exports after checkout.': 'آپ کی موجودہ فائلیں دستیاب رہیں گی۔ Starter چیک آؤٹ کے بعد نئے ایکسپورٹ پر لاگو ہوتا ہے۔',
  'Build Next Episode First': 'پہلے اگلی قسط بنائیں',
  'Video unavailable': 'ویڈیو دستیاب نہیں',
  'Free MP4 includes the Kineo watermark': 'مفت MP4 میں Kineo واٹر مارک شامل ہے',
  'Free distribution · latest Short': 'مفت تقسیم · تازہ ترین Short',
  'Send it to one person for feedback': 'رائے کے لیے ایک شخص کو بھیجیں',
  'Copy a public watch page for your finished video. Your friend can watch it without logging in, then use “Make one like this” if the idea inspires them.': 'اپنی مکمل ویڈیو کا عوامی واچ پیج کاپی کریں۔ آپ کا دوست لاگ ان کیے بغیر دیکھ سکتا ہے، پھر آئیڈیا پسند آئے تو "ایسا ہی بنائیں" استعمال کر سکتا ہے۔',
  'Public watch links are temporarily paused': 'عوامی واچ لنکس عارضی طور پر روکے گئے ہیں',
  'Your video stays in your account. Download the MP4 if you want to send it directly; Kineo will not publish a public page without an explicit visibility choice.': 'آپ کی ویڈیو آپ کے اکاؤنٹ میں رہتی ہے۔ براہِ راست بھیجنا ہو تو MP4 ڈاؤن لوڈ کریں؛ Kineo واضح مرئیت کے انتخاب کے بغیر عوامی صفحہ شائع نہیں کرتا۔',
  'Loading…': 'لوڈ ہو رہا ہے…',
  'For new videos ·': 'نئی ویڈیوز کے لیے ·',
  'Published it?': 'شائع کر دیا؟',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'واضح، سامنے سے، ایک شخص۔ جسمانی حرکت کے لیے کمر سے اوپر یا پورے قد کی تصویر استعمال کریں جس میں دونوں ہاتھ نظر آئیں۔ سیاہ پٹیاں خود بخود ہٹ جاتی ہیں۔',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'بہترین پیشہ ورانہ نتیجہ: 5–20 سیکنڈ کا عمودی کلپ اپ لوڈ کریں جس میں آپ کے مطلوبہ اصل اشارے ہوں، تقریباً اسکرپٹ جتنی لمبائی کا۔ Sync-3 اصل چہرے اور جسمانی حرکت کو برقرار رکھتے ہوئے گفتگو بدل دیتا ہے۔ 40 MB تک MP4/MOV۔',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'میں تصدیق کرتا ہوں کہ مجھے اس شخص کی تصویر استعمال کرنے کا حق ہے اور AI سے اسے اینیمیٹ کرنے کی رضامندی دیتا ہوں۔',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': '~30-60 سیکنڈ کا واضح آواز کا نمونہ اپ لوڈ کریں (ایک بولنے والا، کم پس منظر شور) اور بیانیہ اسی آواز میں ہوگا۔ صرف وہی آواز استعمال کریں جس کا آپ کو حق ہے۔',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'لفظ بہ لفظ ویڈیوز پورا وقت آپ کا چہرہ دکھاتی ہیں (یہ مختصر ہیں — بی رول کی ضرورت نہیں)۔',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'زیادہ سے زیادہ حقیقت پسندی اور بنائے گئے منظر والی ویڈیوز پورے بیانیے میں پریزینٹر کو اسکرین پر رکھتی ہیں۔',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ ہک انٹرو — آپ شروع کریں، بی رول کہانی سناتا ہے',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'آپ کے پریزینٹر کے مختصر کلپس: ہاتھ ہلاتے، اشارہ کرتے، پیش کرتے — WebM میں اصل شفاف پس منظر کے ساتھ۔ انہیں سیدھا Storyline، Premiere، CapCut یا کسی بھی سلائیڈ میں ڈالیں۔ نہ گرین اسکرین، نہ کیئنگ۔',
  'Cinematic film — 9-image consistency': 'سینمائی فلم — 9 تصویری تسلسل',
  '#1-ranked video model — Aug 2026 arena': 'نمبر 1 رینک ویڈیو ماڈل — اگست 2026 ارینا',
  'Cinematic motion and camera work': 'سینمائی حرکت اور کیمرہ ورک',
  'Shorts money & growth': 'Shorts سے پیسہ اور ترقی',
  'Compare Kineo with 27 AI video tools →': 'Kineo کا 27 AI ویڈیو ٹولز سے موازنہ کریں →',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'بولتے پریزینٹرز، دوبارہ استعمال ہونے والے کردار، شفاف کلپس، پروڈکٹ اشتہارات — اور ٹرینڈ ڈھونڈنے اور اس پر سوار ہونے کا ہر ذریعہ۔',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'ایک تصویر + آپ کا اسکرپٹ — اسٹوڈیو معیار کے لب سنک والی بولتی ویڈیو، HeyGen انداز میں۔',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'کردار ایک بار محفوظ کریں — آپ کی ہر ویڈیو اور تھمب نیل میں بالکل وہی چہرہ۔',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'پریزینٹر کے اشارے — ہاتھ ہلانا، اشارہ کرنا، پیش کرنا — اصل شفاف پس منظر کے ساتھ WebM میں۔',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'کوئی بھی پروڈکٹ پیسٹ کریں — 15-30 سیکنڈ کا کریئیٹر انداز اشتہار پائیں، آپ کے لیے لکھا اور بولا ہوا۔',
  'Bring any still photo to life as a moving, postable video.': 'کسی بھی ساکن تصویر کو حرکت کرتی، پوسٹ کے قابل ویڈیو کی صورت زندہ کریں۔',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'بڑے چینلز کے انداز میں کلک کے قابل تھمب نیلز — ایک پرامپٹ سے۔',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'نیچے ہر نیش کا اپنا جنریٹر پیج، ٹیونڈ پرامپٹس اور حقیقی مثالیں ہیں۔',
  'Is the video really mine to post?': 'کیا ویڈیو واقعی پوسٹ کرنے کے لیے میری ہے؟',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'ادا شدہ پلان YouTube، TikTok یا Reels کے لیے صاف، واٹر مارک کے بغیر MP4 کھولتے ہیں۔',
  'Do I need any editing skills?': 'کیا مجھے ایڈیٹنگ کی مہارت چاہیے؟',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'بالکل نہیں۔ آپ ایک آئیڈیا لکھتے ہیں اور AI اسکرپٹ لکھتا ہے، آواز ریکارڈ کرتا ہے، فوٹیج ڈھونڈتا ہے اور کیپشن لگاتا ہے۔',
  'Is there a watermark?': 'کیا واٹر مارک ہے؟',
  'Paid plans export clean, watermark-free MP4s.': 'ادا شدہ پلان صاف، واٹر مارک کے بغیر MP4 ایکسپورٹ کرتے ہیں۔',
  'Can Kineo also generate images and voiceovers?': 'کیا Kineo تصاویر اور وائس اوور بھی بنا سکتا ہے؟',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'جی ہاں — Kineo میں AI امیج اسٹوڈیو (6 انجن بشمول FLUX، Seedream اور Nano Banana Pro، فی تصویر 1 کریڈٹ سے) اور 4 ٹیکسٹ ٹو اسپیچ انجنوں والا وائس اسٹوڈیو (فی 1000 حروف 1 کریڈٹ سے) شامل ہے۔ آپ جو بھی بناتے ہیں وہ آپ کی لائبریری میں رہتا ہے۔',
  'Can I make my videos sharper?': 'کیا میں اپنی ویڈیوز زیادہ واضح کر سکتا ہوں؟',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'ہر ویڈیو میں Topaz فلم ریسٹوریشن سے چلنے والا ایک کلک Enhance آپشن ہے — یہ کمپریشن کے نقائص ہٹاتا ہے، تفصیل واپس لاتا ہے اور باریک سینمائی گرین شامل کرتا ہے۔ فی ویڈیو 10 کریڈٹس؛ Studio پلان میں ہر ماہ 2 مفت بہتریاں شامل ہیں۔',
  'Can I use my own script?': 'کیا میں اپنا اسکرپٹ استعمال کر سکتا ہوں؟',
  'What if a generation fails?': 'اگر جنریشن ناکام ہو جائے تو؟',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'رینڈر ناکام ہوتے ہی آپ کے کریڈٹس خود بخود واپس آ جاتے ہیں — نہ سپورٹ ٹکٹ، نہ انتظار۔ آپ صرف ان ویڈیوز کی ادائیگی کرتے ہیں جو واقعی ملتی ہیں۔',
  'Can I cancel anytime?': 'کیا میں کبھی بھی منسوخ کر سکتا ہوں؟',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'کبھی بھی، ایک کلک میں۔ پلان ماہانہ ہیں اور آپ کے کریڈٹس ہر ماہ تازہ ہوتے ہیں۔',
  'Can I run a whole channel with the same host?': 'کیا میں ایک ہی میزبان کے ساتھ پورا چینل چلا سکتا ہوں؟',
  'Can I monetize the videos?': 'کیا میں ویڈیوز سے کما سکتا ہوں؟',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'جی ہاں۔ ہر ویڈیو آپ کی ہے — رکھیں، پوسٹ کریں اور کمائیں — بشمول YouTube پارٹنر پروگرام، TikTok اور Reels۔ اضافی لائسنس کی ضرورت نہیں۔',
  'Can I use the videos commercially, or for client work?': 'کیا میں ویڈیوز تجارتی طور پر یا کلائنٹ کے کام کے لیے استعمال کر سکتا ہوں؟',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'جی ہاں۔ ہماری شرائط Kineo کو جائز ذاتی یا تجارتی مقاصد کے لیے استعمال کرنے کی اجازت دیتی ہیں اور تصدیق کرتی ہیں کہ بنائی گئی ویڈیوز کی ملکیت آپ کے پاس رہتی ہے، لہٰذا آپ انہیں پوسٹ کر سکتے ہیں، کما سکتے ہیں اور اپنی ادا شدہ سروس کے حصے کے طور پر کلائنٹ کو دے سکتے ہیں۔ نہ اضافی لائسنس، نہ فی ویڈیو رائلٹی۔ انہی شرائط سے دو حدیں آتی ہیں: آپ خود Kineo کو دوبارہ بیچ یا تقسیم نہیں کر سکتے، اور رینڈر کے اندر اسٹاک کلپس آپ کی مکمل ویڈیو میں استعمال کے لیے لائسنس یافتہ ہیں، الگ اسٹاک فوٹیج کے طور پر دوبارہ اپ لوڈ کے لیے نہیں۔ ادا شدہ پلان صاف، واٹر مارک کے بغیر MP4 ایکسپورٹ کرتے ہیں۔',
  'How long does one video take?': 'ایک ویڈیو میں کتنا وقت لگتا ہے؟',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'Fast موڈ عموماً 3–7 منٹ میں مکمل ہوتا ہے۔ AI سے بنی اور سینمائی ویڈیوز تھوڑا زیادہ وقت لیتی ہیں کیونکہ حتمی MP4 بننے سے پہلے ہر منظر بنایا جاتا ہے۔',
  'How much does Kineo cost?': 'Kineo کی قیمت کیا ہے؟',
  'Kineo has three monthly plans: Starter at $': 'Kineo کے تین ماہانہ پلان ہیں: Starter $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'کریڈٹس۔ کریڈٹس فی ویڈیو خرچ ہوتے ہیں اور ویڈیو کی لاگت آپ کے چنے ہوئے انجن پر منحصر ہے، اس لیے Fast رینڈر اور سینمائی فلم ایک ہی بیلنس سے بہت مختلف شرح پر نکلتے ہیں۔',
  'Which AI video engines can I use in Kineo?': 'میں Kineo میں کون سے AI ویڈیو انجن استعمال کر سکتا ہوں؟',
  ', behind one interface and one balance:': '، ایک انٹرفیس اور ایک بیلنس کے پیچھے:',
  'What is the best AI video generator for faceless YouTube channels?': 'بغیر چہرے والے YouTube چینلز کے لیے بہترین AI ویڈیو جنریٹر کون سا ہے؟',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'جی ہاں۔ کبھی ادائیگی نہ کرنے والے مفت صارفین واٹر مارک والا MP4 ڈاؤن لوڈ، شیئر اور پوسٹ کر سکتے ہیں۔',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'آزمائشی فلموں پر چھوٹا واٹر مارک ہوتا ہے — آپ MP4 ڈاؤن لوڈ، شیئر اور پوسٹ کر سکتے ہیں۔ آزمائش کے بعد مفت Fast ویڈیو پر واٹر مارک ہوتا ہے۔',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'مفت ڈاؤن لوڈز پر واٹر مارک ہوتا ہے؛ ادا شدہ پلان صاف MP4 کھولتے ہیں۔',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'آزمائشی ڈاؤن لوڈز پر واٹر مارک ہوتا ہے، آزمائش کے بعد مفت Fast ویڈیو پر بھی، اور ادا شدہ پلان ہمیشہ صاف ایکسپورٹ کرتے ہیں۔',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'مفت رسائی نئے صارفین کو ہر 24 گھنٹے میں 3 تک واٹر مارک والی Fast ویڈیوز دیتی ہے، بغیر کارڈ کے۔ آپ انہیں ڈاؤن لوڈ اور شیئر کر سکتے ہیں۔',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'ہر 24 گھنٹے میں 3 تک واٹر مارک والی Fast ویڈیوز بنائیں، ڈاؤن لوڈ اور شیئر کریں، بغیر کارڈ کے۔',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'ہر 24 گھنٹے میں 3 تک واٹر مارک والی Fast ویڈیوز بنائیں، دیکھیں، ڈاؤن لوڈ اور شیئر کریں — بغیر کارڈ کے۔',
  'create, watch, download and share up to 3 Fast videos every 24h': 'ہر 24 گھنٹے میں 3 تک Fast ویڈیوز بنائیں، دیکھیں، ڈاؤن لوڈ اور شیئر کریں',
  '— no card, watermark included.': '— بغیر کارڈ، واٹر مارک شامل۔',
  'AI image generator — 6 engines': 'AI امیج جنریٹر — 6 انجن',
  'AI voice generator (text to speech)': 'AI وائس جنریٹر (متن سے آواز)',
  'AI video upscaler & enhancer': 'AI ویڈیو اپ اسکیلر اور اینہانسر',
  'Trending Shorts ideas today': 'آج کے ٹرینڈنگ Shorts آئیڈیاز',
  'AI Avatar video — your face, any script': 'AI اوتار ویڈیو — آپ کا چہرہ، کوئی بھی اسکرپٹ',
  'Kineo facts & numbers (citable)': 'Kineo حقائق اور اعداد (حوالے کے قابل)',
  'Free AI Shorts generator': 'مفت AI Shorts جنریٹر',
  'YouTube Shorts from a topic': 'موضوع سے YouTube Shorts',
  'ChatGPT script to YouTube Short': 'ChatGPT اسکرپٹ سے YouTube Short',
  'Shorts without filming': 'فلمنگ کے بغیر Shorts',
  'Faceless niche picker': 'بغیر چہرے والا نیش پکر',
  'State of AI Shorts 2026': 'AI Shorts کی صورتحال 2026',
  'AI Shorts for agencies & client work': 'ایجنسیوں اور کلائنٹ کام کے لیے AI Shorts',
  'Trust Center — privacy, payments & ownership': 'ٹرسٹ سینٹر — رازداری، ادائیگیاں اور ملکیت',
  'Affiliate program - 30% recurring': 'ایفیلی ایٹ پروگرام - 30% بار بار',
  'Free AI Shorts by niche': 'نیش کے مطابق مفت AI Shorts',
  'Free script generator': 'مفت اسکرپٹ جنریٹر',
  'Product video ad script': 'پروڈکٹ ویڈیو اشتہار اسکرپٹ',
  'Client video brief generator': 'کلائنٹ ویڈیو بریف جنریٹر',
  'Free hook generator': 'مفت ہک جنریٹر',
  'Shorts script timer': 'Shorts اسکرپٹ ٹائمر',
  'Shorts money calculator': 'Shorts آمدنی کیلکولیٹر',
  'How much do Shorts pay?': 'Shorts کتنا دیتے ہیں؟',
  'Best AI Shorts generators': 'بہترین AI Shorts جنریٹرز',
  'TikTok vs Shorts: which pays more?': 'TikTok بمقابلہ Shorts: کون زیادہ دیتا ہے؟',
  'All comparisons': 'تمام موازنے',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · جملہ حقوق محفوظ ہیں',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'یہ اس پر منحصر ہے کہ آپ کو جوڑی گئی اسٹاک فوٹیج چاہیے یا بنائی گئی فوٹیج۔ InVideo اور AutoShorts جیسے ٹولز آپ کے اسکرپٹ پر اسٹاک کلپس کاٹتے ہیں، جو سستا ہے اور بات چیت والی ویڈیوز کے لیے ٹھیک ہے۔ Kineo فوٹیج Veo 3.1 اور Kling 3 جیسے ماڈلز سے بناتا ہے، آپ کے بیانیے کو دوبارہ لکھنے کے بجائے لفظ بہ لفظ رکھتا ہے، اور 60 سیکنڈ یا زیادہ کا ہدف رکھتا ہے تاکہ ویڈیو TikTok Creator Rewards کے لیے اہل ہو۔ اگر آپ کا چینل ایسے بصری مواد پر چلتا ہے جو کسی اور کے پاس نہیں، تو جنریشن جیتتی ہے؛ اگر حجم پر چلتا ہے تو اسٹاک سستا ہے۔',
  'Paste the complete script from ChatGPT here…': 'ChatGPT سے مکمل اسکرپٹ یہاں پیسٹ کریں…',
  'Paste the idea from ChatGPT here…': 'ChatGPT سے آئیڈیا یہاں پیسٹ کریں…',
  'What’s your video about? One idea in — a finished film out: voiced, scored and captioned.': 'آپ کی ویڈیو کس بارے میں ہے؟ ایک آئیڈیا اندر — ایک مکمل فلم باہر: آواز، موسیقی اور کیپشن کے ساتھ۔',
  'Settings and generation': 'سیٹنگز اور جنریشن',
  'Search your videos…': 'اپنی ویڈیوز تلاش کریں…',
  'Search your audio…': 'اپنا آڈیو تلاش کریں…',
  'Search your images by engine': 'انجن کے مطابق اپنی تصاویر تلاش کریں',
  'No playable videos in your library yet. Check your latest project above.': 'آپ کی لائبریری میں ابھی کوئی چلنے والی ویڈیو نہیں۔ اوپر اپنا تازہ ترین پروجیکٹ دیکھیں۔',
  'Make a finished Short →': 'مکمل Short بنائیں →',
  'Video Editing & Creator Tools': 'ویڈیو ایڈیٹنگ اور کریئیٹر ٹولز',
  'Trim, resize, change speed, mute or add text. Edit a file you already have, right in your browser. Your script and planning tools are still here below.': 'کاٹیں، سائز بدلیں، رفتار بدلیں، آواز بند کریں یا ٹیکسٹ شامل کریں۔ اپنی موجودہ فائل براہِ راست براؤزر میں ایڈٹ کریں۔ آپ کے اسکرپٹ اور منصوبہ بندی کے ٹولز نیچے موجود ہیں۔',
  '5 local editing tools': '5 مقامی ایڈیٹنگ ٹولز',
  'No generation credits to edit': 'ایڈٹ کرنے میں جنریشن کریڈٹس خرچ نہیں ہوتے',
  'Edit video': 'ویڈیو ایڈٹ کریں',
  'Files up to 100 MB and 3 minutes. Local, real-time export up to 1280 px on the long edge. MP4 or WebM depending on your browser; downloads are not saved to My Videos.': '100 MB اور 3 منٹ تک کی فائلیں۔ لمبی طرف 1280 px تک مقامی، ریئل ٹائم ایکسپورٹ۔ براؤزر کے مطابق MP4 یا WebM؛ ڈاؤن لوڈز میری ویڈیوز میں محفوظ نہیں ہوتے۔',
  'Video Trimmer': 'ویڈیو ٹرمر',
  'Cut the beginning or end and keep only the clip you need.': 'شروع یا آخر کاٹیں اور صرف مطلوبہ کلپ رکھیں۔',
  'Video Resizer': 'ویڈیو ری سائزر',
  'Go vertical, square or wide. Fit the frame or crop to fill.': 'عمودی، مربع یا چوڑا۔ فریم میں فٹ کریں یا بھرنے کے لیے کراپ کریں۔',
  'Video Speed Changer': 'ویڈیو اسپیڈ چینجر',
  'Slow it down or speed it up, from 0.5× to 2×.': '0.5× سے 2× تک آہستہ یا تیز کریں۔',
  'Remove Audio': 'آڈیو ہٹائیں',
  'Download a copy without the original audio.': 'اصل آڈیو کے بغیر کاپی ڈاؤن لوڈ کریں۔',
  'Add Text to Video': 'ویڈیو میں ٹیکسٹ شامل کریں',
  'Add a title or message that stays on screen. Not automatic subtitles.': 'ایسا عنوان یا پیغام شامل کریں جو اسکرین پر رہے۔ خودکار سب ٹائٹل نہیں۔',
  'No account · current Kineo plans': 'بغیر اکاؤنٹ · موجودہ Kineo پلانز',
  'No account · fair-use limit': 'بغیر اکاؤنٹ · منصفانہ استعمال کی حد',
  'No account · unlimited in browser': 'بغیر اکاؤنٹ · براؤزر میں لامحدود',
  'Edit an existing video here. Create a new one with Kineo.': 'موجودہ ویڈیو یہاں ایڈٹ کریں۔ نئی Kineo سے بنائیں۔',
  'Create an AI video →': 'AI ویڈیو بنائیں →',
  'Edit your video, preview the changes, then export a copy.': 'اپنی ویڈیو ایڈٹ کریں، تبدیلیاں دیکھیں، پھر کاپی ایکسپورٹ کریں۔',
  'Video preview': 'ویڈیو پیش نظارہ',
  'Preview is silent. The download keeps audio unless Mute is selected.': 'پیش نظارہ خاموش ہے۔ ڈاؤن لوڈ میں آڈیو رہتا ہے جب تک Mute منتخب نہ ہو۔',
  'Start with your video': 'اپنی ویڈیو سے شروع کریں',
  'Choose a local file. It stays on this device.': 'مقامی فائل چنیں۔ یہ اسی ڈیوائس پر رہتی ہے۔',
  'Choose video file': 'ویڈیو فائل چنیں',
  'Video file': 'ویڈیو فائل',
  'Video settings': 'ویڈیو سیٹنگز',
  'Aspect ratio': 'اسپیکٹ ریشو',
  'Playback speed': 'پلے بیک رفتار',
  'On-screen text (100 characters, 3 lines)': 'اسکرین ٹیکسٹ (100 حروف، 3 سطریں)',
  'Add a title or message': 'عنوان یا پیغام شامل کریں',
  'Export edited video': 'ایڈٹ شدہ ویڈیو ایکسپورٹ کریں',
  'Export happens in real time. Keep this tab visible. Re-encoded at up to 1280 px on the long edge; format depends on your browser.': 'ایکسپورٹ ریئل ٹائم میں ہوتا ہے۔ یہ ٹیب نظر میں رکھیں۔ لمبی طرف 1280 px تک دوبارہ انکوڈ؛ فارمیٹ براؤزر پر منحصر ہے۔',
  'Making a 4-second sample on your device…': 'آپ کی ڈیوائس پر 4 سیکنڈ کا نمونہ بن رہا ہے…',
  'Reading your file…': 'آپ کی فائل پڑھی جا رہی ہے…',
  'Export result': 'ایکسپورٹ نتیجہ',
  'Your edited video': 'آپ کی ایڈٹ شدہ ویڈیو',
  'Local download only. This copy is not saved to My Videos.': 'صرف مقامی ڈاؤن لوڈ۔ یہ کاپی میری ویڈیوز میں محفوظ نہیں ہوتی۔',
  'Exported video': 'ایکسپورٹ شدہ ویڈیو',
  'No upload. No generation credits. Your original is never overwritten.': 'نہ اپ لوڈ۔ نہ جنریشن کریڈٹس۔ آپ کی اصل فائل کبھی اوور رائٹ نہیں ہوتی۔',
  'Up to 100 MB · 3 minutes · MP4/WebM input recommended. These are basic editing tools, not the CapCut app.': '100 MB تک · 3 منٹ · MP4/WebM ان پٹ تجویز کردہ۔ یہ بنیادی ایڈیٹنگ ٹولز ہیں، CapCut ایپ نہیں۔',
  'Need a new video? Open Kineo Studio →': 'نئی ویڈیو چاہیے؟ Kineo Studio کھولیں →',
  'This browser cannot export video here. Try the latest desktop Chrome or Edge.': 'یہ براؤزر یہاں ویڈیو ایکسپورٹ نہیں کر سکتا۔ ڈیسک ٹاپ پر تازہ ترین Chrome یا Edge آزمائیں۔',
  'Choose a non-empty video file of up to 100 MB.': '100 MB تک کی غیر خالی ویڈیو فائل چنیں۔',
  'Use a playable clip of up to 3 minutes. Very large dimensions are not supported.': '3 منٹ تک کا چلنے والا کلپ استعمال کریں۔ بہت بڑے ابعاد معاون نہیں۔',
  'Check the start and end: select at least 0.25 seconds within your clip.': 'شروع اور آخر چیک کریں: اپنے کلپ کے اندر کم از کم 0.25 سیکنڈ منتخب کریں۔',
  'Choose a speed between 0.5× and 2×.': '0.5× اور 2× کے درمیان رفتار چنیں۔',
  'Use up to 100 characters and 3 lines of text.': 'زیادہ سے زیادہ 100 حروف اور 3 سطریں استعمال کریں۔',
  'Choose a supported aspect ratio, framing and text position.': 'معاون اسپیکٹ ریشو، فریمنگ اور ٹیکسٹ پوزیشن چنیں۔',
  'This file could not be decoded. Try an MP4 (H.264) or WebM file.': 'یہ فائل ڈی کوڈ نہ ہو سکی۔ MP4 (H.264) یا WebM فائل آزمائیں۔',
  'Export stopped because this tab was hidden. Keep it open and visible, then export again. Your original is safe.': 'ایکسپورٹ رک گیا کیونکہ یہ ٹیب چھپا ہوا تھا۔ اسے کھلا اور نظر میں رکھیں، پھر دوبارہ ایکسپورٹ کریں۔ آپ کی اصل فائل محفوظ ہے۔',
  'Export stopped making progress. Try a shorter clip or desktop Chrome. Your original is unchanged.': 'ایکسپورٹ آگے نہیں بڑھ رہا۔ چھوٹا کلپ یا ڈیسک ٹاپ Chrome آزمائیں۔ آپ کی اصل فائل جوں کی توں ہے۔',
  'Audio could not start. Try exporting again, or choose Mute video.': 'آڈیو شروع نہ ہو سکا۔ دوبارہ ایکسپورٹ کریں، یا Mute video چنیں۔',
  'The browser blocked playback. Try exporting again from this tab.': 'براؤزر نے پلے بیک روک دیا۔ اسی ٹیب سے دوبارہ ایکسپورٹ کریں۔',
  'Cancelled. Your original file is unchanged.': 'منسوخ۔ آپ کی اصل فائل جوں کی توں ہے۔',
  'Could not finish this export. Try a shorter clip or another supported browser.': 'یہ ایکسپورٹ مکمل نہ ہو سکا۔ چھوٹا کلپ یا کوئی اور معاون براؤزر آزمائیں۔',
  'The browser produced an incomplete file, so we did not offer it for download. Try again with this tab visible, or use desktop Chrome.': 'براؤزر نے نامکمل فائل بنائی، اس لیے ہم نے اسے ڈاؤن لوڈ کے لیے پیش نہیں کیا۔ یہ ٹیب نظر میں رکھ کر دوبارہ کوشش کریں، یا ڈیسک ٹاپ Chrome استعمال کریں۔',
  'Create new video': 'نئی ویڈیو بنائیں',
  'Your idea': 'آپ کا آئیڈیا',
  'Natural': 'قدرتی',
  'Working…': 'کام جاری ہے…',
  '🎲 Surprise me': '🎲 مجھے حیران کریں',
  '📝 Use my script as is': '📝 میرا اسکرپٹ جوں کا توں استعمال کریں',
  'Camera preset': 'کیمرہ پری سیٹ',
  'Your latest videos': 'آپ کی تازہ ترین ویڈیوز',
  'Presenter': 'پریزینٹر',
  '1 · Who’s talking': '1 · کون بول رہا ہے',
  '🎭 your characters': '🎭 آپ کے کردار',
  '🎯 Max realism — animate my real photo': '🎯 زیادہ سے زیادہ حقیقت — میری اصل تصویر کو حرکت دیں',
  '✓ Scene ready — preview on the right.': '✓ منظر تیار — پیش نظارہ دائیں طرف۔',
  '2 · What they say': '2 · وہ کیا کہتے ہیں',
  '3 · How it looks': '3 · یہ کیسا لگتا ہے',
  'Motion': 'حرکت',
  '⬇ Download MP4': '⬇ MP4 ڈاؤن لوڈ کریں',
  'One photo. Suddenly alive.': 'ایک تصویر۔ اچانک زندہ۔',
  'Cost per clip': 'فی کلپ لاگت',
  '↺ Animate another': '↺ ایک اور اینیمیٹ کریں',
  'Grow': 'بڑھیں',
  'Sending to the motion engine…': 'موشن انجن کو بھیجا جا رہا ہے…',
  '📊 Facts': '📊 حقائق',
  'Turn it into episode 2': 'اسے قسط 2 بنائیں',
  'Start here': 'یہاں سے شروع کریں',
  'Engine': 'انجن',
  'Highly aesthetic, by xAI': 'انتہائی خوبصورت، xAI سے',
  'Google’s best image model': 'Google کا بہترین امیج ماڈل',
  'AI voiceover included': 'AI وائس اوور شامل',
  '6 engines': '6 انجن',
  'AI Presenter': 'AI پریزینٹر',
  'Lock a character →': 'کردار لاک کریں →',
  'Make a clip →': 'کلپ بنائیں →',
  'Make an ad →': 'اشتہار بنائیں →',
  'Generate free →': 'مفت بنائیں →',
  'Creating…': 'بن رہا ہے…',
  'Describe your image first': 'پہلے اپنی تصویر بیان کریں',
  'Type your script first': 'پہلے اپنا اسکرپٹ لکھیں',
  'From the founder': 'بانی کی طرف سے',
  'Faceless video generator': 'بغیر چہرے والا ویڈیو جنریٹر',
  'Text to video Shorts': 'متن سے ویڈیو Shorts',
  'Cheapest AI Shorts maker': 'سستا ترین AI Shorts میکر',
  'Faceless channel ideas (2026)': 'بغیر چہرے والے چینل آئیڈیاز (2026)',
  'Shorts idea widget': 'Shorts آئیڈیا ویجٹ',
  'Live case study: our channel on Autopilot': 'لائیو کیس اسٹڈی: Autopilot پر ہمارا چینل',
  'Free YouTube Shorts scripts': 'مفت YouTube Shorts اسکرپٹس',
  'Comment to Short script': 'کمنٹ سے Short اسکرپٹ',
  'Business video content planner': 'کاروباری ویڈیو کانٹینٹ پلانر',
  'Real estate video maker': 'ریئل اسٹیٹ ویڈیو میکر',
  'Shorts title & hashtag generator': 'Shorts عنوان اور ہیش ٹیگ جنریٹر',
  'Free viral score': 'مفت وائرل اسکور',
  'Make money clipping with AI': 'AI سے کلپنگ کر کے پیسہ کمائیں',
  'Shorts RPM by niche (2026)': 'نیش کے مطابق Shorts RPM (2026)',
  'Can you monetize AI videos?': 'کیا AI ویڈیوز سے کمایا جا سکتا ہے؟',
}
