// KINEO-INTERFACE-16-LINGUAS-2026-09-21 — interface em vi. Só copy autoral da interface: nunca prompt,
// título, resultado, nome de motor ou erro de API. Frase fora daqui cai em inglês (components/InterfaceLanguage.tsx).
// Gerado de scratchpad/tr-vi.js sobre o corpus vivo de frases (415); números e "Kineo" preservados por construção.
export const DICT: Record<string, string> = {
  'Videos for businesses': 'Video cho doanh nghiệp',
  'Generation failed': 'Tạo video thất bại',
  'You can retry safely.': 'Bạn có thể thử lại an toàn.',
  'This engine is not available on your account right now': 'Engine này hiện không khả dụng trên tài khoản của bạn',
  'Retrying the same engine will stop at this same place. Pick another engine to keep going.': 'Thử lại với cùng engine sẽ dừng ở đúng chỗ này. Chọn engine khác để tiếp tục.',
  'The engine is cooling down after two refunded attempts': 'Engine đang nghỉ sau hai lần thử đã được hoàn tín dụng',
  'Starting another one right now stops at this same place. Give it a few minutes.': 'Bắt đầu một video khác ngay bây giờ sẽ dừng ở đúng chỗ này. Hãy đợi vài phút.',
  'Starting another one right now stops at this same place. The button below unlocks by itself.': 'Bắt đầu một video khác ngay bây giờ sẽ dừng ở đúng chỗ này. Nút bên dưới sẽ tự mở khóa.',
  'We stopped waiting on this render instead of leaving you hanging': 'Chúng tôi ngừng chờ bản render này thay vì để bạn chờ mãi',
  'This one ran far longer than any video that finishes here. Starting again is worth it.': 'Bản này chạy lâu hơn nhiều so với bất kỳ video nào hoàn thành ở đây. Bắt đầu lại là đáng.',
  'The video engine is busy — this is on our side, not your idea': 'Engine video đang bận — lỗi ở phía chúng tôi, không phải ý tưởng của bạn',
  'Nothing about your text is wrong. Trying again in a few minutes usually goes straight through.': 'Văn bản của bạn không có gì sai. Thử lại sau vài phút thường sẽ chạy ngay.',
  'Create Video': 'Tạo Video',
  'Create a new video': 'Tạo video mới',
  'AI Avatar Studio': 'Studio Avatar AI',
  'Viral Templates': 'Mẫu viral',
  'Channel Builder': 'Trình xây kênh',
  'Invite & Earn': 'Mời & Kiếm tiền',
  'Start free': 'Bắt đầu miễn phí',
  'Try 7 days for $1': 'Dùng thử 7 ngày với $1',
  'Pick a lane': 'Chọn một hướng',
  'All free tools': 'Tất cả công cụ miễn phí',
  'Terms of Service': 'Điều khoản dịch vụ',
  'Trust Center': 'Trung tâm tin cậy',
  'Review & publish': 'Xem lại & đăng',
  'Your image': 'Hình ảnh của bạn',
  'Cost per image': 'Chi phí mỗi ảnh',
  'No videos yet': 'Chưa có video',
  'No audio yet': 'Chưa có audio',
  '🎬 Studio — generate video': '🎬 Studio — tạo video',
  '🎨 Images — create image': '🎨 Hình ảnh — tạo ảnh',
  '🎙 Audio — text to speech': '🎙 Audio — chuyển văn bản thành giọng nói',
  'Type it. See it. Six image engines, one screen.': 'Gõ. Xem. Sáu engine ảnh, một màn hình.',
  'Type it. Hear it. Four voice engines, one screen.': 'Gõ. Nghe. Bốn engine giọng nói, một màn hình.',
  'Everything you’ve created, in one place.': 'Mọi thứ bạn đã tạo, ở một nơi.',
  'Add credits →': 'Thêm tín dụng →',
  'Upscale any result to 2x for 1 credit.': 'Phóng to bất kỳ kết quả nào lên 2x với 1 tín dụng.',
  'We couldn’t load your images right now.': 'Hiện không tải được hình ảnh của bạn.',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'Hình ảnh và tín dụng của bạn vẫn an toàn — chỉ là trục trặc đọc tạm thời.',
  'We couldn’t load your audio right now.': 'Hiện không tải được audio của bạn.',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'Audio và tín dụng của bạn vẫn an toàn — chỉ là trục trặc đọc tạm thời.',
  'We couldn’t load part of your library right now.': 'Hiện không tải được một phần thư viện của bạn.',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'Video và tín dụng của bạn vẫn an toàn — chỉ là trục trặc đọc tạm thời.',
  '↻ Try again': '↻ Thử lại',
  '⬇ Download': '⬇ Tải xuống',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': 'Thích một giọng nói? Studio dựng cả bộ phim quanh nó — hình ảnh, phụ đề và nhạc nền.',
  'Open Studio →': 'Mở Studio →',
  'open the Studio': 'mở Studio',
  'Next episode →': 'Tập tiếp theo →',
  'create your first image': 'tạo ảnh đầu tiên của bạn',
  'generate your first voiceover': 'tạo lồng tiếng đầu tiên của bạn',
  'Instant drafts': 'Bản nháp tức thì',
  'Deep prompt understanding': 'Hiểu prompt sâu sắc',
  'Perfect text rendering': 'Kết xuất chữ hoàn hảo',
  'Create Image': 'Tạo ảnh',
  'Click-magnet YouTube covers': 'Ảnh bìa YouTube hút click',
  'Bring any image to life': 'Thổi hồn vào bất kỳ bức ảnh nào',
  'Instant narration': 'Lồng tiếng tức thì',
  'Four voice engines': 'Bốn engine giọng nói',
  'A face that speaks your script': 'Một gương mặt nói kịch bản của bạn',
  'Every control, one screen': 'Mọi điều khiển, một màn hình',
  'Today’s trending topics': 'Chủ đề đang thịnh hành hôm nay',
  'Real renders, every engine': 'Render thật, mọi engine',
  'Type an idea — watch it become a film.': 'Gõ một ý tưởng — xem nó thành phim.',
  'Start with the full toolkit': 'Bắt đầu với bộ công cụ đầy đủ',
  'Kineo’s own engine — 3–7 min': 'Engine riêng của Kineo — 3–7 phút',
  'The workhorse AI video engine': 'Engine video AI chủ lực',
  'Cinematic motion & camera': 'Chuyển động & máy quay điện ảnh',
  'Film scenes, native voice & lip sync': 'Cảnh phim, giọng gốc & khớp môi',
  'Talking video from one photo': 'Video biết nói từ một bức ảnh',
  'From idea to posted Short in 3 steps.': 'Từ ý tưởng đến Short đã đăng trong 3 bước.',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'Không quay, không dựng, không timeline. Gõ một lần — Kineo lo phần còn lại.',
  'Step 1': 'Bước 1',
  'Kineo builds it': 'Kineo dựng nó',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'AI viết kịch bản có cấu trúc giữ chân người xem, thu lồng tiếng, ghép footage và gắn phụ đề — một video 9:16 hoàn chỉnh.',
  'Download & post': 'Tải về & đăng',
  'Why Kineo': 'Vì sao chọn Kineo',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'Hầu hết công cụ cắt lại một video dài bạn đã quay. Kineo dựng nó từ đầu.',
  'See how to make Shorts without filming →': 'Xem cách làm Shorts không cần quay →',
  'Generates the Short from just an idea': 'Tạo Short chỉ từ một ý tưởng',
  'Writes the script for you': 'Viết kịch bản cho bạn',
  'Finds and matches footage': 'Tìm và ghép footage',
  'your upload': 'tệp bạn tải lên',
  'AI image studio included': 'Kèm studio ảnh AI',
  'Voice studio (text-to-speech)': 'Studio giọng nói (văn bản thành giọng)',
  'One-click HD film enhance': 'Nâng cấp HD phim chỉ một cú click',
  'One idea — or a whole toolkit.': 'Một ý tưởng — hay cả bộ công cụ.',
  'Try AI Presenter →': 'Thử Người dẫn AI →',
  'Transparent Clips': 'Clip nền trong suốt',
  'UGC Product Ads': 'Quảng cáo sản phẩm UGC',
  'Animate a photo →': 'Làm ảnh chuyển động →',
  'Make a thumbnail →': 'Tạo thumbnail →',
  'Free AI Shorts': 'Shorts AI miễn phí',
  'Start with a niche that already works.': 'Bắt đầu với một ngách đã hiệu quả.',
  'Not sure? Take the quiz →': 'Chưa chắc? Làm bài trắc nghiệm →',
  'Pick your engine. Ship a Short today.': 'Chọn engine. Đăng một Short ngay hôm nay.',
  'Cancel anytime': 'Hủy bất cứ lúc nào',
  'Generate image →': 'Tạo ảnh →',
  'Generate audio →': 'Tạo audio →',
  'Paid plans unlock clean MP4s.': 'Gói trả phí mở khóa MP4 sạch.',
  'Best for starting out': 'Tốt nhất để bắt đầu',
  'Best value per film': 'Giá trị tốt nhất mỗi phim',
  'on Nano Banana': 'trên Nano Banana',
  'Every video engine incl. MiniMax H3': 'Mọi engine video, kể cả MiniMax H3',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'MP4 không watermark · 100 dự án · lưu trữ 90 ngày',
  ', finished': ', hoàn chỉnh',
  '— every engine unlocked': '— mọi engine đã mở khóa',
  '· voice + karaoke captions + score': '· giọng nói + phụ đề karaoke + nhạc nền',
  '500 projects · forever storage': '500 dự án · lưu trữ vĩnh viễn',
  'Cancel anytime — 7-day money-back': 'Hủy bất cứ lúc nào — hoàn tiền trong 7 ngày',
  'films on Omni Flash': 'phim trên Omni Flash',
  '· 2 free HD enhances / month': '· 2 lần nâng cấp HD miễn phí / tháng',
  'Unlimited projects · forever storage': 'Dự án không giới hạn · lưu trữ vĩnh viễn',
  'Everything in Creator': 'Mọi thứ trong Creator',
  'Calculate your cost per Short →': 'Tính chi phí mỗi Short của bạn →',
  'How much do Shorts pay? →': 'Shorts trả bao nhiêu? →',
  'Highest-RPM niches →': 'Các ngách RPM cao nhất →',
  'read the full review →': 'đọc bài đánh giá đầy đủ →',
  'a single line is enough — or paste a full script': 'một dòng là đủ — hoặc dán cả kịch bản',
  '1080×1920 · Full HD master': '1080×1920 · bản master Full HD',
  'Every film is delivered as a 1080×1920 Full HD master (engines render natively at 720–768p and are mastered up). For maximum sharpness, run ✨HD Enhance on the finished film.': 'Mỗi phim được giao dưới dạng bản master 1080×1920 Full HD (các engine render gốc ở 720–768p rồi được master lên). Để sắc nét tối đa, chạy ✨HD Enhance trên phim đã hoàn thành.',
  'Your idea first. Review the settings, then generate.': 'Ý tưởng của bạn trước. Xem lại cài đặt, rồi tạo.',
  '📷 Photo': '📷 Ảnh',
  '🖼️ Upload a different photo': '🖼️ Tải ảnh khác',
  '🎙️ Generating…': '🎙️ Đang tạo…',
  '🎙️ Cloning the voice…': '🎙️ Đang nhân bản giọng nói…',
  '🎙️ Upload a different sample': '🎙️ Tải mẫu khác',
  '⏹ Stop & clone': '⏹ Dừng & nhân bản',
  '🎭 Generate my avatar video': '🎭 Tạo video avatar của tôi',
  'Continue exactly where ChatGPT stopped.': 'Tiếp tục đúng chỗ ChatGPT dừng lại.',
  '✨ Let AI structure it': '✨ Để AI sắp xếp',
  'Optional settings': 'Cài đặt tùy chọn',
  'optional — a pre-tested move added to your prompt': 'tùy chọn — một chuyển động đã kiểm thử được thêm vào prompt của bạn',
  'Reference image': 'Ảnh tham chiếu',
  '🖼️ Start your video from an image — coming soon': '🖼️ Bắt đầu video từ một bức ảnh — sắp ra mắt',
  'Estimated cost': 'Chi phí ước tính',
  'Your credits buy': 'Tín dụng của bạn đủ cho',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'Đã gồm giọng nói, phụ đề karaoke và nhạc nền. Nếu render thất bại, tín dụng được hoàn ngay.',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'Cùng chủ đề, hook và kết mới — ý tưởng đã được viết sẵn.',
  'Build next episode →': 'Dựng tập tiếp theo →',
  'Episode 2 →': 'Tập 2 →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'Người dẫn AI biết nói từ một bức ảnh — khớp môi, studio riêng',
  'Your face. Your script.': 'Gương mặt của bạn. Kịch bản của bạn.',
  'Everything you need to make yourself speak — nothing you don’t.': 'Mọi thứ bạn cần để tự mình lên tiếng — không thừa thứ gì.',
  'BEST MOTION': 'CHUYỂN ĐỘNG TỐT NHẤT',
  '1.5 · Realism': '1.5 · Chân thực',
  '🎬 Put me in a scene': '🎬 Đưa tôi vào một cảnh',
  'use original photo': 'dùng ảnh gốc',
  '✍️ Say exactly this — word for word': '✍️ Nói đúng như thế này — từng chữ một',
  '✨ Expand into a full Short script (45–60s)': '✨ Mở rộng thành kịch bản Short đầy đủ (45–60 giây)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 Chế độ quảng cáo sản phẩm — bán sản phẩm kiểu UGC',
  'Free — fills the script box above, then generate with your presenter.': 'Miễn phí — điền vào ô kịch bản ở trên, rồi tạo với người dẫn của bạn.',
  '2.5 · Speak in your own voice': '2.5 · Nói bằng chính giọng của bạn',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ Đã nhân bản giọng — phần lồng tiếng sẽ dùng giọng này.',
  'use a default voice': 'dùng giọng mặc định',
  '🎬 Full video — face the whole time': '🎬 Video đầy đủ — gương mặt suốt thời gian',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 Người dẫn AI — nhanh & tự nhiên · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro — chất lượng ảnh cao cấp · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 Body Motion — thân, tay & cử chỉ · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ Cổ điển — talking head · 110 cr',
  'you have': 'bạn có',
  'to create your avatar video.': 'để tạo video avatar của bạn.',
  '5 · Gesture clips — transparent background': '5 · Clip cử chỉ — nền trong suốt',
  'auto-refunded if it fails': 'tự động hoàn tín dụng nếu thất bại',
  '⬇️ Download transparent WebM': '⬇️ Tải WebM nền trong suốt',
  '⬇️ Original MP4 (with background)': '⬇️ MP4 gốc (có nền)',
  'Pick a face to preview': 'Chọn một gương mặt để xem trước',
  '↺ Make another': '↺ Làm cái khác',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'Người, thú cưng, sản phẩm, ảnh gia đình cũ — tải ảnh lên hoặc dán liên kết ảnh công khai và xem nó chuyển động.',
  'The photo': 'Bức ảnh',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': 'JPG/PNG tối đa 8 MB. Liên kết công khai được tải xuống và kiểm tra an toàn trên máy chủ của chúng tôi.',
  'sign in': 'đăng nhập',
  'Kineo will fetch and validate it on the server when you animate.': 'Kineo sẽ lấy và kiểm tra nó trên máy chủ khi bạn tạo chuyển động.',
  'Upload a photo to preview': 'Tải ảnh lên để xem trước',
  '🖼️ Upload a photo': '🖼️ Tải ảnh lên',
  '✨ Bring it to life': '✨ Thổi hồn',
  'Uploading your photo…': 'Đang tải ảnh của bạn…',
  'Bringing your photo to life… (1–3 min)': 'Đang thổi hồn vào ảnh của bạn… (1–3 phút)',
  'Alive!': 'Sống động!',
  '🌬️ Subtle & real': '🌬️ Tinh tế & chân thực',
  '😊 Person comes alive': '😊 Người trong ảnh sống dậy',
  'Type your idea first': 'Gõ ý tưởng của bạn trước',
  '📖 True Story': '📖 Chuyện có thật',
  'Paste your ChatGPT script': 'Dán kịch bản ChatGPT của bạn',
  'First Short complete': 'Hoàn thành Short đầu tiên',
  'Keep your show moving': 'Giữ chương trình của bạn tiếp diễn',
  'Cheapest way to see your idea as a film': 'Cách rẻ nhất để thấy ý tưởng của bạn thành phim',
  'Slow Dolly-In': 'Dolly-In chậm',
  'FPV Drone': 'Drone FPV',
  'Macro Detail': 'Chi tiết macro',
  'Sharing & creator options': 'Chia sẻ & tùy chọn cho nhà sáng tạo',
  'We couldn’t load your videos right now': 'Hiện không tải được video của bạn',
  'Your videos and credits are safe — this is a temporary read hiccup, not a lost library.': 'Video và tín dụng của bạn vẫn an toàn — đây là trục trặc đọc tạm thời, không phải mất thư viện.',
  '⚡ Generate Video': '⚡ Tạo Video',
  'Prefer clean exports now? Starter includes': 'Muốn xuất bản sạch ngay? Starter bao gồm',
  'credits each month for': 'tín dụng mỗi tháng với',
  'Your existing files stay available. Starter applies to new exports after checkout.': 'Các tệp hiện có của bạn vẫn khả dụng. Starter áp dụng cho các bản xuất mới sau khi thanh toán.',
  'Build Next Episode First': 'Dựng tập tiếp theo trước',
  'Video unavailable': 'Video không khả dụng',
  'Free MP4 includes the Kineo watermark': 'MP4 miễn phí có watermark Kineo',
  'Free distribution · latest Short': 'Phân phối miễn phí · Short mới nhất',
  'Send it to one person for feedback': 'Gửi cho một người để nhận phản hồi',
  'Copy a public watch page for your finished video. Your friend can watch it without logging in, then use “Make one like this” if the idea inspires them.': 'Sao chép trang xem công khai cho video đã hoàn thành. Bạn của bạn có thể xem mà không cần đăng nhập, rồi dùng “Làm một cái như này” nếu ý tưởng truyền cảm hứng.',
  'Public watch links are temporarily paused': 'Liên kết xem công khai tạm thời bị tạm dừng',
  'Your video stays in your account. Download the MP4 if you want to send it directly; Kineo will not publish a public page without an explicit visibility choice.': 'Video vẫn ở trong tài khoản của bạn. Tải MP4 nếu muốn gửi trực tiếp; Kineo sẽ không đăng trang công khai nếu không có lựa chọn hiển thị rõ ràng.',
  'Loading…': 'Đang tải…',
  'For new videos ·': 'Cho video mới ·',
  'Published it?': 'Đã đăng chưa?',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'Rõ nét, nhìn thẳng, một người. Với chuyển động cơ thể, dùng ảnh nửa người/toàn thân với cả hai tay nhìn thấy. Dải đen được tự động loại bỏ.',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'Kết quả chuyên nghiệp nhất: tải clip dọc 5–20 giây thực hiện đúng cử chỉ bạn muốn, dài tương đương kịch bản. Sync-3 thay phần nói trong khi giữ nguyên gương mặt và chuyển động thật. MP4/MOV tối đa 40 MB.',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'Tôi xác nhận có quyền sử dụng hình ảnh người này và đồng ý để AI tạo chuyển động.',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': 'Tải mẫu giọng rõ ~30-60 giây (một người nói, ít tạp âm) và phần lồng tiếng sẽ dùng giọng đó. Chỉ dùng giọng bạn có quyền sử dụng.',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'Video nói từng chữ luôn hiện gương mặt bạn suốt thời gian (chúng ngắn — không cần b-roll).',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'Video chân thực tối đa và cảnh dựng giữ người dẫn trên màn hình suốt phần lồng tiếng.',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ Mở đầu bằng hook — bạn mở màn, b-roll kể câu chuyện',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'Clip ngắn người dẫn của bạn vẫy tay, chỉ tay, thuyết trình — giao dưới dạng WebM với nền trong suốt THẬT. Kéo thẳng vào Storyline, Premiere, CapCut hoặc bất kỳ slide nào. Không phông xanh, không keying.',
  'Cinematic film — 9-image consistency': 'Phim điện ảnh — nhất quán 9 ảnh',
  '#1-ranked video model — Aug 2026 arena': 'Mô hình video xếp hạng #1 — arena tháng 8/2026',
  'Cinematic motion and camera work': 'Chuyển động và máy quay điện ảnh',
  'Shorts money & growth': 'Tiền & tăng trưởng từ Shorts',
  'Compare Kineo with 27 AI video tools →': 'So sánh Kineo với 27 công cụ video AI →',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'Người dẫn biết nói, nhân vật tái sử dụng, clip nền trong suốt, quảng cáo sản phẩm — cùng mọi thứ để tìm và bắt trend.',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'Một bức ảnh + kịch bản của bạn — video biết nói với khớp môi chuẩn studio, kiểu HeyGen.',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'Lưu nhân vật một lần — đúng gương mặt đó trong mọi video và thumbnail bạn làm.',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'Cử chỉ người dẫn — vẫy tay, chỉ tay, thuyết trình — dưới dạng WebM với nền trong suốt thật.',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'Dán bất kỳ sản phẩm nào — nhận quảng cáo 15-30 giây kiểu nhà sáng tạo, có kịch bản và lồng tiếng sẵn.',
  'Bring any still photo to life as a moving, postable video.': 'Thổi hồn vào bất kỳ ảnh tĩnh nào thành video chuyển động, sẵn sàng đăng.',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'Thumbnail đáng click theo phong cách các kênh lớn nhất — từ một prompt.',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'Mỗi ngách bên dưới có trang tạo riêng, prompt đã tinh chỉnh và ví dụ thật.',
  'Is the video really mine to post?': 'Video có thật sự là của tôi để đăng không?',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'Gói trả phí mở khóa MP4 sạch, không watermark cho YouTube, TikTok hoặc Reels.',
  'Do I need any editing skills?': 'Tôi có cần kỹ năng dựng phim không?',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'Không. Bạn gõ một ý tưởng và AI viết kịch bản, thu giọng, tìm footage và thêm phụ đề.',
  'Is there a watermark?': 'Có watermark không?',
  'Paid plans export clean, watermark-free MP4s.': 'Gói trả phí xuất MP4 sạch, không watermark.',
  'Can Kineo also generate images and voiceovers?': 'Kineo có tạo được ảnh và lồng tiếng không?',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'Có — Kineo gồm studio ảnh AI (6 engine gồm FLUX, Seedream và Nano Banana Pro, từ 1 tín dụng mỗi ảnh) và studio giọng nói với 4 engine văn bản thành giọng (từ 1 tín dụng mỗi 1000 ký tự). Mọi thứ bạn tạo nằm trong Thư viện của bạn.',
  'Can I make my videos sharper?': 'Tôi có thể làm video sắc nét hơn không?',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'Mỗi video có tùy chọn Enhance một cú click dùng công nghệ phục chế phim Topaz — loại bỏ lỗi nén, khôi phục chi tiết và thêm hạt phim điện ảnh mịn. 10 tín dụng mỗi video; gói Studio gồm 2 lần nâng cấp miễn phí mỗi tháng.',
  'Can I use my own script?': 'Tôi có thể dùng kịch bản riêng không?',
  'What if a generation fails?': 'Nếu tạo video thất bại thì sao?',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'Tín dụng của bạn tự động hoàn lại ngay khi render thất bại — không ticket hỗ trợ, không chờ đợi. Bạn chỉ trả cho video thực sự nhận được.',
  'Can I cancel anytime?': 'Tôi có thể hủy bất cứ lúc nào không?',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'Bất cứ lúc nào, một cú click. Gói theo tháng và tín dụng làm mới mỗi tháng.',
  'Can I run a whole channel with the same host?': 'Tôi có thể chạy cả kênh với cùng một người dẫn không?',
  'Can I monetize the videos?': 'Tôi có thể kiếm tiền từ video không?',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'Có. Mọi video là của bạn để giữ, đăng và kiếm tiền — kể cả Chương trình Đối tác YouTube, TikTok và Reels. Không cần giấy phép thêm.',
  'Can I use the videos commercially, or for client work?': 'Tôi có thể dùng video cho mục đích thương mại hoặc cho khách hàng không?',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'Có. Điều khoản của chúng tôi cho phép bạn dùng Kineo cho mục đích cá nhân hoặc thương mại hợp pháp và xác nhận bạn giữ quyền sở hữu video đã tạo, nên bạn có thể đăng, kiếm tiền và giao cho khách hàng như một phần dịch vụ trả phí của mình. Không giấy phép thêm, không phí bản quyền mỗi video. Hai giới hạn đến từ cùng điều khoản: bạn không được bán lại hoặc phân phối lại chính Kineo, và các clip stock trong bản render được cấp phép để dùng trong video hoàn chỉnh của bạn, không phải để tải lại làm footage stock riêng lẻ. Gói trả phí xuất MP4 sạch, không watermark.',
  'How long does one video take?': 'Một video mất bao lâu?',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'Chế độ Fast thường xong trong 3–7 phút. Video do AI tạo và điện ảnh mất lâu hơn một chút vì mỗi cảnh được tạo trước khi ghép MP4 cuối.',
  'How much does Kineo cost?': 'Kineo giá bao nhiêu?',
  'Kineo has three monthly plans: Starter at $': 'Kineo có ba gói tháng: Starter giá $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'tín dụng. Tín dụng tiêu theo từng video, và chi phí một video phụ thuộc engine bạn chọn, nên một bản render Fast và một phim điện ảnh trừ từ cùng số dư với mức rất khác nhau.',
  'Which AI video engines can I use in Kineo?': 'Tôi có thể dùng những engine video AI nào trong Kineo?',
  ', behind one interface and one balance:': ', sau một giao diện và một số dư:',
  'What is the best AI video generator for faceless YouTube channels?': 'Trình tạo video AI tốt nhất cho kênh YouTube không lộ mặt là gì?',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'Có. Người dùng miễn phí chưa từng trả phí có thể tải, chia sẻ và đăng MP4 có watermark.',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'Phim dùng thử có watermark nhỏ — bạn có thể tải, chia sẻ và đăng MP4. Sau thời gian dùng thử, video Fast miễn phí có watermark.',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'Tải xuống miễn phí có watermark; gói trả phí mở khóa MP4 sạch.',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'Tải xuống dùng thử có watermark, video Fast miễn phí sau dùng thử cũng vậy, còn gói trả phí luôn xuất sạch.',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'Truy cập miễn phí cho người dùng mới tối đa 3 video Fast có watermark mỗi 24 giờ, không cần thẻ. Bạn có thể tải và chia sẻ.',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'Tạo, tải và chia sẻ tối đa 3 video Fast có watermark mỗi 24 giờ, không cần thẻ.',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'Tạo, xem, tải và chia sẻ tối đa 3 video Fast có watermark mỗi 24 giờ — không cần thẻ.',
  'create, watch, download and share up to 3 Fast videos every 24h': 'tạo, xem, tải và chia sẻ tối đa 3 video Fast mỗi 24 giờ',
  '— no card, watermark included.': '— không cần thẻ, có watermark.',
  'AI image generator — 6 engines': 'Trình tạo ảnh AI — 6 engine',
  'AI voice generator (text to speech)': 'Trình tạo giọng nói AI (văn bản thành giọng)',
  'AI video upscaler & enhancer': 'Trình nâng cấp & cải thiện video AI',
  'Trending Shorts ideas today': 'Ý tưởng Shorts thịnh hành hôm nay',
  'AI Avatar video — your face, any script': 'Video Avatar AI — gương mặt của bạn, kịch bản bất kỳ',
  'Kineo facts & numbers (citable)': 'Số liệu & dữ kiện Kineo (có thể trích dẫn)',
  'Free AI Shorts generator': 'Trình tạo Shorts AI miễn phí',
  'YouTube Shorts from a topic': 'YouTube Shorts từ một chủ đề',
  'ChatGPT script to YouTube Short': 'Kịch bản ChatGPT thành YouTube Short',
  'Shorts without filming': 'Shorts không cần quay',
  'Faceless niche picker': 'Chọn ngách không lộ mặt',
  'State of AI Shorts 2026': 'Toàn cảnh Shorts AI 2026',
  'AI Shorts for agencies & client work': 'Shorts AI cho agency & khách hàng',
  'Trust Center — privacy, payments & ownership': 'Trung tâm tin cậy — quyền riêng tư, thanh toán & sở hữu',
  'Affiliate program - 30% recurring': 'Chương trình liên kết - 30% định kỳ',
  'Free AI Shorts by niche': 'Shorts AI miễn phí theo ngách',
  'Free script generator': 'Trình tạo kịch bản miễn phí',
  'Product video ad script': 'Kịch bản quảng cáo video sản phẩm',
  'Client video brief generator': 'Trình tạo brief video cho khách hàng',
  'Free hook generator': 'Trình tạo hook miễn phí',
  'Shorts script timer': 'Bộ đếm giờ kịch bản Shorts',
  'Shorts money calculator': 'Máy tính thu nhập Shorts',
  'How much do Shorts pay?': 'Shorts trả bao nhiêu?',
  'Best AI Shorts generators': 'Trình tạo Shorts AI tốt nhất',
  'TikTok vs Shorts: which pays more?': 'TikTok vs Shorts: bên nào trả nhiều hơn?',
  'All comparisons': 'Tất cả so sánh',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · Bảo lưu mọi quyền',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'Tùy bạn muốn ghép footage stock hay tạo footage mới. Các công cụ như InVideo và AutoShorts cắt clip stock theo kịch bản của bạn, rẻ hơn và đủ tốt cho video nói ý. Kineo tạo footage bằng các mô hình như Veo 3.1 và Kling 3, giữ nguyên lời dẫn từng chữ thay vì viết lại, và nhắm tới 60 giây trở lên để video đủ điều kiện TikTok Creator Rewards. Nếu kênh của bạn sống bằng hình ảnh không ai có, tạo mới thắng; nếu sống bằng số lượng, stock rẻ hơn.',
  'Paste the complete script from ChatGPT here…': 'Dán kịch bản đầy đủ từ ChatGPT vào đây…',
  'Paste the idea from ChatGPT here…': 'Dán ý tưởng từ ChatGPT vào đây…',
  'What’s your video about? One idea in — a finished film out: voiced, scored and captioned.': 'Video của bạn nói về gì? Một ý tưởng vào — một bộ phim hoàn chỉnh ra: có lồng tiếng, nhạc nền và phụ đề.',
  'Settings and generation': 'Cài đặt và tạo video',
  'Search your videos…': 'Tìm trong video của bạn…',
  'Search your audio…': 'Tìm trong audio của bạn…',
  'Search your images by engine': 'Tìm ảnh của bạn theo engine',
  'No playable videos in your library yet. Check your latest project above.': 'Chưa có video phát được trong thư viện. Kiểm tra dự án mới nhất ở trên.',
  'Make a finished Short →': 'Làm một Short hoàn chỉnh →',
  'Video Editing & Creator Tools': 'Chỉnh sửa video & công cụ cho nhà sáng tạo',
  'Trim, resize, change speed, mute or add text. Edit a file you already have, right in your browser. Your script and planning tools are still here below.': 'Cắt, đổi kích thước, đổi tốc độ, tắt tiếng hoặc thêm chữ. Chỉnh sửa tệp bạn đã có, ngay trong trình duyệt. Công cụ kịch bản và lập kế hoạch vẫn ở bên dưới.',
  '5 local editing tools': '5 công cụ chỉnh sửa cục bộ',
  'No generation credits to edit': 'Chỉnh sửa không tốn tín dụng tạo video',
  'Edit video': 'Chỉnh sửa video',
  'Files up to 100 MB and 3 minutes. Local, real-time export up to 1280 px on the long edge. MP4 or WebM depending on your browser; downloads are not saved to My Videos.': 'Tệp tối đa 100 MB và 3 phút. Xuất cục bộ thời gian thực tối đa 1280 px cạnh dài. MP4 hoặc WebM tùy trình duyệt; bản tải xuống không lưu vào Video của tôi.',
  'Video Trimmer': 'Cắt video',
  'Cut the beginning or end and keep only the clip you need.': 'Cắt đầu hoặc cuối và chỉ giữ đoạn bạn cần.',
  'Video Resizer': 'Đổi kích thước video',
  'Go vertical, square or wide. Fit the frame or crop to fill.': 'Dọc, vuông hoặc ngang. Vừa khung hoặc cắt để lấp đầy.',
  'Video Speed Changer': 'Đổi tốc độ video',
  'Slow it down or speed it up, from 0.5× to 2×.': 'Làm chậm hoặc tăng tốc, từ 0.5× đến 2×.',
  'Remove Audio': 'Xóa audio',
  'Download a copy without the original audio.': 'Tải bản sao không có audio gốc.',
  'Add Text to Video': 'Thêm chữ vào video',
  'Add a title or message that stays on screen. Not automatic subtitles.': 'Thêm tiêu đề hoặc thông điệp giữ trên màn hình. Không phải phụ đề tự động.',
  'No account · current Kineo plans': 'Không cần tài khoản · gói Kineo hiện tại',
  'No account · fair-use limit': 'Không cần tài khoản · giới hạn sử dụng hợp lý',
  'No account · unlimited in browser': 'Không cần tài khoản · không giới hạn trong trình duyệt',
  'Edit an existing video here. Create a new one with Kineo.': 'Chỉnh sửa video có sẵn tại đây. Tạo video mới với Kineo.',
  'Create an AI video →': 'Tạo video AI →',
  'Edit your video, preview the changes, then export a copy.': 'Chỉnh sửa video, xem trước thay đổi, rồi xuất một bản sao.',
  'Video preview': 'Xem trước video',
  'Preview is silent. The download keeps audio unless Mute is selected.': 'Bản xem trước không có tiếng. Bản tải xuống giữ audio trừ khi chọn Tắt tiếng.',
  'Start with your video': 'Bắt đầu với video của bạn',
  'Choose a local file. It stays on this device.': 'Chọn tệp cục bộ. Tệp ở lại trên thiết bị này.',
  'Choose video file': 'Chọn tệp video',
  'Video file': 'Tệp video',
  'Video settings': 'Cài đặt video',
  'Aspect ratio': 'Tỷ lệ khung hình',
  'Playback speed': 'Tốc độ phát',
  'On-screen text (100 characters, 3 lines)': 'Chữ trên màn hình (100 ký tự, 3 dòng)',
  'Add a title or message': 'Thêm tiêu đề hoặc thông điệp',
  'Export edited video': 'Xuất video đã chỉnh sửa',
  'Export happens in real time. Keep this tab visible. Re-encoded at up to 1280 px on the long edge; format depends on your browser.': 'Xuất diễn ra theo thời gian thực. Giữ tab này hiển thị. Mã hóa lại tối đa 1280 px cạnh dài; định dạng tùy trình duyệt.',
  'Making a 4-second sample on your device…': 'Đang tạo mẫu 4 giây trên thiết bị của bạn…',
  'Reading your file…': 'Đang đọc tệp của bạn…',
  'Export result': 'Kết quả xuất',
  'Your edited video': 'Video đã chỉnh sửa của bạn',
  'Local download only. This copy is not saved to My Videos.': 'Chỉ tải cục bộ. Bản sao này không lưu vào Video của tôi.',
  'Exported video': 'Video đã xuất',
  'No upload. No generation credits. Your original is never overwritten.': 'Không tải lên. Không tốn tín dụng tạo video. Bản gốc không bao giờ bị ghi đè.',
  'Up to 100 MB · 3 minutes · MP4/WebM input recommended. These are basic editing tools, not the CapCut app.': 'Tối đa 100 MB · 3 phút · khuyến nghị đầu vào MP4/WebM. Đây là công cụ chỉnh sửa cơ bản, không phải ứng dụng CapCut.',
  'Need a new video? Open Kineo Studio →': 'Cần video mới? Mở Kineo Studio →',
  'This browser cannot export video here. Try the latest desktop Chrome or Edge.': 'Trình duyệt này không xuất được video ở đây. Thử Chrome hoặc Edge mới nhất trên máy tính.',
  'Choose a non-empty video file of up to 100 MB.': 'Chọn tệp video không trống, tối đa 100 MB.',
  'Use a playable clip of up to 3 minutes. Very large dimensions are not supported.': 'Dùng clip phát được tối đa 3 phút. Kích thước quá lớn không được hỗ trợ.',
  'Check the start and end: select at least 0.25 seconds within your clip.': 'Kiểm tra điểm đầu và cuối: chọn ít nhất 0.25 giây trong clip.',
  'Choose a speed between 0.5× and 2×.': 'Chọn tốc độ từ 0.5× đến 2×.',
  'Use up to 100 characters and 3 lines of text.': 'Dùng tối đa 100 ký tự và 3 dòng chữ.',
  'Choose a supported aspect ratio, framing and text position.': 'Chọn tỷ lệ khung hình, bố cục và vị trí chữ được hỗ trợ.',
  'This file could not be decoded. Try an MP4 (H.264) or WebM file.': 'Không giải mã được tệp này. Thử tệp MP4 (H.264) hoặc WebM.',
  'Export stopped because this tab was hidden. Keep it open and visible, then export again. Your original is safe.': 'Xuất bị dừng vì tab này bị ẩn. Giữ nó mở và hiển thị, rồi xuất lại. Bản gốc của bạn vẫn an toàn.',
  'Export stopped making progress. Try a shorter clip or desktop Chrome. Your original is unchanged.': 'Xuất không tiến triển. Thử clip ngắn hơn hoặc Chrome trên máy tính. Bản gốc không thay đổi.',
  'Audio could not start. Try exporting again, or choose Mute video.': 'Không khởi động được audio. Thử xuất lại, hoặc chọn Tắt tiếng video.',
  'The browser blocked playback. Try exporting again from this tab.': 'Trình duyệt đã chặn phát. Thử xuất lại từ tab này.',
  'Cancelled. Your original file is unchanged.': 'Đã hủy. Tệp gốc của bạn không thay đổi.',
  'Could not finish this export. Try a shorter clip or another supported browser.': 'Không hoàn tất được lần xuất này. Thử clip ngắn hơn hoặc trình duyệt khác được hỗ trợ.',
  'The browser produced an incomplete file, so we did not offer it for download. Try again with this tab visible, or use desktop Chrome.': 'Trình duyệt tạo ra tệp không hoàn chỉnh nên chúng tôi không cung cấp để tải. Thử lại với tab này hiển thị, hoặc dùng Chrome trên máy tính.',
  'Create new video': 'Tạo video mới',
  'Your idea': 'Ý tưởng của bạn',
  'Natural': 'Tự nhiên',
  'Working…': 'Đang xử lý…',
  '🎲 Surprise me': '🎲 Gây bất ngờ cho tôi',
  '📝 Use my script as is': '📝 Dùng nguyên kịch bản của tôi',
  'Camera preset': 'Thiết lập máy quay',
  'Your latest videos': 'Video mới nhất của bạn',
  'Presenter': 'Người dẫn',
  '1 · Who’s talking': '1 · Ai đang nói',
  '🎭 your characters': '🎭 nhân vật của bạn',
  '🎯 Max realism — animate my real photo': '🎯 Chân thực tối đa — làm ảnh thật của tôi chuyển động',
  '✓ Scene ready — preview on the right.': '✓ Cảnh đã sẵn sàng — xem trước ở bên phải.',
  '2 · What they say': '2 · Họ nói gì',
  '3 · How it looks': '3 · Trông thế nào',
  'Motion': 'Chuyển động',
  '⬇ Download MP4': '⬇ Tải MP4',
  'One photo. Suddenly alive.': 'Một bức ảnh. Bỗng sống động.',
  'Cost per clip': 'Chi phí mỗi clip',
  '↺ Animate another': '↺ Làm chuyển động ảnh khác',
  'Grow': 'Phát triển',
  'Sending to the motion engine…': 'Đang gửi tới engine chuyển động…',
  '📊 Facts': '📊 Dữ kiện',
  'Turn it into episode 2': 'Biến thành tập 2',
  'Start here': 'Bắt đầu tại đây',
  'Engine': 'Engine',
  'Highly aesthetic, by xAI': 'Tính thẩm mỹ cao, từ xAI',
  'Google’s best image model': 'Mô hình ảnh tốt nhất của Google',
  'AI voiceover included': 'Kèm lồng tiếng AI',
  '6 engines': '6 engine',
  'AI Presenter': 'Người dẫn AI',
  'Lock a character →': 'Khóa một nhân vật →',
  'Make a clip →': 'Làm một clip →',
  'Make an ad →': 'Làm một quảng cáo →',
  'Generate free →': 'Tạo miễn phí →',
  'Creating…': 'Đang tạo…',
  'Describe your image first': 'Mô tả ảnh của bạn trước',
  'Type your script first': 'Gõ kịch bản của bạn trước',
  'From the founder': 'Từ nhà sáng lập',
  'Faceless video generator': 'Trình tạo video không lộ mặt',
  'Text to video Shorts': 'Shorts từ văn bản thành video',
  'Cheapest AI Shorts maker': 'Trình làm Shorts AI rẻ nhất',
  'Faceless channel ideas (2026)': 'Ý tưởng kênh không lộ mặt (2026)',
  'Shorts idea widget': 'Widget ý tưởng Shorts',
  'Live case study: our channel on Autopilot': 'Case study trực tiếp: kênh của chúng tôi chạy Autopilot',
  'Free YouTube Shorts scripts': 'Kịch bản YouTube Shorts miễn phí',
  'Comment to Short script': 'Từ bình luận thành kịch bản Short',
  'Business video content planner': 'Lập kế hoạch nội dung video cho doanh nghiệp',
  'Real estate video maker': 'Trình làm video bất động sản',
  'Shorts title & hashtag generator': 'Trình tạo tiêu đề & hashtag Shorts',
  'Free viral score': 'Điểm viral miễn phí',
  'Make money clipping with AI': 'Kiếm tiền bằng cắt clip với AI',
  'Shorts RPM by niche (2026)': 'RPM Shorts theo ngách (2026)',
  'Can you monetize AI videos?': 'Có kiếm tiền được từ video AI không?',
}
