export const CITATION_COST_DECISION_CSS = `
.kc-answer .kccd-actions{display:flex;align-items:center;flex-wrap:wrap;gap:12px}
.kc-answer .kccd-compare{display:inline-block;padding:13px 21px;border:1px solid #5e8eb8;border-radius:8px;font-weight:700;line-height:1.4;text-align:center;text-decoration:none;color:#a8d3ff}
.kc-answer .kccd-compare:hover{background:#132b42}.kc-answer .kccd-compare:focus-visible{outline:3px solid #8bc6ff;outline-offset:5px}
.kccd{margin-top:24px}.kccd-plan{display:flex;align-items:baseline;justify-content:space-between;flex-wrap:wrap;gap:8px;margin:0;color:#dbe9f9}.kccd-plan strong{font-size:20px}.kccd-plan span{font-size:14px;color:#a9bdd2}.kccd-intro{font-size:14px;color:#b8c8da;margin:10px 0 18px}
.kccd-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.kccd-engine{min-width:0;border:1px solid #35506e;border-radius:12px;background:#0d1825;padding:22px}.kccd-engine h3{margin:0;font-size:22px}.kccd-visuals{margin:4px 0 19px;font-size:13px;color:#a6b7cb}.kccd-amount{margin:0 0 20px;padding-bottom:18px;border-bottom:1px solid #294057}.kccd-amount strong{display:block;font-size:34px;font-weight:800;line-height:1.15;letter-spacing:-1px;color:#f5f9ff}.kccd-amount span{display:block;font-size:12px;margin-top:7px;color:#a9c2db}.kccd-engine dl{margin:0;display:grid;gap:11px;font-size:14px}.kccd-engine dl div{display:flex;justify-content:space-between;align-items:baseline;gap:18px}.kccd-engine dt{color:#b2c3d7}.kccd-engine dd{margin:0;font-weight:800;color:#edf5ff}.kccd-equation{font-size:12px;color:#91aac5;margin:19px 0 0}
.kccd-limit{font-size:13px;line-height:1.65;color:#acbfd3;margin:18px 0 0;max-width:900px}.kccd-limit strong{color:#d5e4f4}.kccd-currency{font-size:13px;color:#d2e0ef;margin:15px 0 10px}.kccd-calculator{font-size:14px;font-weight:700;text-underline-offset:4px}
@media(max-width:600px){.kc-answer .kccd-actions{display:grid;grid-template-columns:1fr;gap:10px}.kc-answer .kccd-compare{width:100%;padding:14px 12px}.kccd-grid{grid-template-columns:1fr;gap:12px}.kccd-engine{padding:19px}.kccd-amount strong{font-size:32px}.kccd-plan{display:block}.kccd-plan span{display:block;margin-top:4px}.kccd-engine dl{font-size:13px}.kccd-limit{font-size:12px}}
`
