/** Reviewed UI labels. Product names and user-created content are not translated. */
export const INTERFACE_ES: Record<string, string> = {
  'Your idea first. Review the settings, then generate.': 'Primero tu idea. Revisa los ajustes y después genera el vídeo.',
  '🎲 Surprise me': '🎲 Sorpréndeme',
  'Continue exactly where ChatGPT stopped.': 'Continúa justo donde lo dejó ChatGPT.',
  '✨ Let AI structure it': '✨ Deja que la IA lo estructure',
  '📝 Use my script as is': '📝 Usar mi guion tal cual',
  'Optional settings': 'Ajustes opcionales',
  'Camera preset': 'Movimiento de cámara',
  'optional — a pre-tested move added to your prompt': 'opcional: un movimiento probado que se añade a tu descripción',
  'Reference image': 'Imagen de referencia', 'SOON': 'PRÓXIMAMENTE',
  '🖼️ Start your video from an image — coming soon': '🖼️ Empieza tu vídeo con una imagen — próximamente',
  'Estimated cost': 'Coste estimado', 'Usually takes': 'Tiempo habitual',
  'Your credits buy': 'Tus créditos alcanzan para', 'like this': 'como este',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'Incluye voz, subtítulos karaoke y música. Si falla la generación, se te devuelven los créditos.',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'Mismo tema, nuevo gancho y desenlace: la idea ya viene escrita.',
  'Build next episode →': 'Crear el siguiente episodio →',
  'Your latest videos': 'Tus últimos vídeos', 'Episode 2 →': 'Episodio 2 →',
  'Presenter': 'Presentador', 'Avatar Studio →': 'Estudio de avatares →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'Presentador IA a partir de una foto, con sincronización labial y estudio propio',
  'Your face. Your script.': 'Tu rostro. Tu guion.', 'One video.': 'Un vídeo.',
  'Everything you need to make yourself speak — nothing you don’t.': 'Todo lo necesario para dar voz a tu imagen, sin complicaciones.',
  'Preview & result ↓': 'Vista previa y resultado ↓',
  '1 · Who’s talking': '1 · Quién habla', 'BEST MOTION': 'MEJOR MOVIMIENTO',
  '🎭 your characters': '🎭 tus personajes', 'your saved faces': 'tus rostros guardados',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'Una persona, de frente y con nitidez. Para movimiento corporal, usa una foto de cintura para arriba o de cuerpo entero con ambas manos visibles. Las barras negras se eliminan automáticamente.',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'Para el mejor resultado profesional, sube un clip vertical de 5–20s con los gestos que deseas y una duración similar al guion. Sync-3 sustituye el habla conservando el rostro y el movimiento corporal reales. MP4/MOV de hasta 40 MB.',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'Confirmo que tengo derecho a utilizar la imagen de esta persona y consiento que se anime mediante IA.',
  '1.5 · Realism': '1.5 · Realismo',
  '🎯 Max realism — animate my real photo': '🎯 Máximo realismo: animar mi foto real',
  '🎬 Put me in a scene': '🎬 Ponerme en una escena',
  '✓ Scene ready — preview on the right.': '✓ Escena lista: consulta la vista previa.',
  'use original photo': 'usar la foto original',
  '2 · What they say': '2 · Qué dice', 'Language': 'Idioma',
  '✍️ Say exactly this — word for word': '✍️ Decir exactamente esto, palabra por palabra',
  '✨ Expand into a full Short script (45–60s)': '✨ Ampliar a un guion completo de Short (45–60s)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 Anuncio de producto: vender al estilo UGC',
  'Free — fills the script box above, then generate with your presenter.': 'Gratis: completa el guion de arriba; después genera el vídeo con tu presentador.',
  '2.5 · Speak in your own voice': '2.5 · Habla con tu propia voz', '(optional)': '(opcional)',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': 'Sube una muestra de voz clara de ~30-60s, con una sola persona y poco ruido de fondo. La narración usará esa voz. Utiliza únicamente una voz que tengas derecho a usar.',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ Voz clonada: la narración utilizará esta voz.',
  'use a default voice': 'usar una voz predeterminada',
  '3 · How it looks': '3 · Cómo se ve',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'Los vídeos palabra por palabra muestran tu rostro todo el tiempo; son cortos y no necesitan imágenes de apoyo.',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'Los vídeos de máximo realismo y con escena creada mantienen al presentador en pantalla durante toda la narración.',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ Introducción con gancho: tú empiezas y las imágenes cuentan la historia',
  '🎬 Full video — face the whole time': '🎬 Vídeo completo: rostro visible todo el tiempo',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 Presentador IA: rápido y natural · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro: calidad fotográfica prémium · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 Movimiento corporal: torso, manos y gestos · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ Clásico: rostro parlante · 110 cr',
  'Motion': 'Movimiento', 'credits · debited only on success ·': 'créditos · solo se cobran si se completa ·',
  'you have': 'tienes', 'get credits from': 'consigue créditos desde',
  'to create your avatar video.': 'para crear tu vídeo de avatar.',
  '5 · Gesture clips — transparent background': '5 · Clips de gestos: fondo transparente',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'Clips cortos de tu presentador saludando, señalando o presentando, en WebM con fondo realmente transparente. Úsalos en Storyline, Premiere, CapCut o una diapositiva. Sin pantalla verde ni recorte por color.',
  'auto-refunded if it fails': 'devolución automática si falla',
  '⬇️ Download transparent WebM': '⬇️ Descargar WebM transparente',
  '⬇️ Original MP4 (with background)': '⬇️ MP4 original (con fondo)',
  'Pick a face to preview': 'Elige un rostro para ver la vista previa',
  '⬇ Download MP4': '⬇ Descargar MP4', '↺ Make another': '↺ Crear otro',
  'One photo. Suddenly alive.': 'Una foto que cobra vida.',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'Personas, mascotas, productos o fotos familiares antiguas: sube una foto o pega un enlace público y mira cómo se mueve.',
  'The photo': 'La foto', 'The motion': 'El movimiento',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': 'JPG/PNG de hasta 8 MB. Los enlaces públicos se descargan y validan de forma segura en nuestro servidor.',
  'Cost per clip': 'Coste por clip', 'credits ·': 'créditos ·',
  'sign in': 'iniciar sesión', 'Image link ready': 'Enlace de imagen listo',
  'Kineo will fetch and validate it on the server when you animate.': 'Kineo la descargará y validará en el servidor al animarla.',
  'Upload a photo to preview': 'Sube una foto para ver la vista previa',
  '↺ Animate another': '↺ Animar otra',
  '🖼️ Upload a photo': '🖼️ Subir una foto', '🖼️ Choose a different photo': '🖼️ Elegir otra foto',
  '✨ Bring it to life': '✨ Darle vida', 'Generate →': 'Generar →',
  "Google's flagship cinematic engine": 'El motor cinematográfico insignia de Google',
  'Cinematic film — 9-image consistency': 'Cine con coherencia entre 9 imágenes',
  '#1-ranked video model — Aug 2026 arena': 'Modelo de vídeo n.º 1 en la arena de agosto de 2026',
  'Cinematic motion and camera work': 'Movimiento y cámara cinematográficos',
  'Grow': 'Crecer',
  'Uploading your photo…': 'Subiendo tu foto…',
  'Sending to the motion engine…': 'Enviando al motor de movimiento…',
  'Bringing your photo to life… (1–3 min)': 'Dando vida a tu foto… (1–3 min)',
  'Alive!': '¡Ya tiene vida!', 'Something went wrong.': 'Algo salió mal.',
  '🌬️ Subtle & real': '🌬️ Sutil y real', '🎥 Slow camera push': '🎥 Acercamiento lento',
  '😊 Person comes alive': '😊 La persona cobra vida', '🌊 Scenery flows': '🌊 Paisaje en movimiento',
  'Type your idea first': 'Primero escribe tu idea',
  '📊 Facts': '📊 Curiosidades', '🕵️ Mystery': '🕵️ Misterio',
  '📖 True Story': '📖 Historia real', '📝 My Script': '📝 Mi guion',
  'Paste your ChatGPT script': 'Pega tu guion de ChatGPT', 'Paste your ChatGPT idea': 'Pega tu idea de ChatGPT',
  'First Short complete': 'Primer Short terminado',
  'Turn it into episode 2': 'Conviértelo en el episodio 2', 'Keep your show moving': 'Continúa tu serie',
  'Start here': 'Empieza aquí', 'Best value': 'Mejor relación calidad-precio',
  'Cheapest way to see your idea as a film': 'La forma más económica de convertir tu idea en un vídeo',
  'Slow Dolly-In': 'Acercamiento lento', 'Crash Zoom': 'Zoom rápido', 'Orbit': 'Órbita',
  'FPV Drone': 'Dron FPV', 'Crane Up': 'Ascenso de grúa', 'Handheld': 'Cámara en mano',
  'Macro Detail': 'Detalle macro', 'Locked Tripod': 'Trípode fijo',
  Home: 'Inicio', Dashboard: 'Panel', 'Creator Hub': 'Centro de creación',
  Studio: 'Studio', 'Create Video': 'Crear vídeo', 'Generate New Short': 'Crear un Short',
  Images: 'Imágenes', Audio: 'Audio', Library: 'Biblioteca', 'My Videos': 'Mis vídeos',
  'AI Avatar Studio': 'Estudio de avatares IA', 'Animate a Photo': 'Animar una foto',
  Examples: 'Ejemplos', Pricing: 'Planes', Plans: 'Planes', Account: 'Cuenta',
  'Viral Templates': 'Plantillas virales', 'Video Studio': 'Estudio de vídeo',
  'Channel Builder': 'Crear un canal', 'AI Thumbnail Generator': 'Crear miniaturas con IA',
  'Invite & Earn': 'Invita y gana', 'Affiliate Dashboard': 'Panel de afiliados',
  Tools: 'Herramientas', More: 'Más', 'Free tools': 'Herramientas gratuitas',
  'Start free': 'Empezar gratis', 'Sign in': 'Iniciar sesión', 'Log in': 'Iniciar sesión',
  Explore: 'Explorar', Scripts: 'Guiones', Animate: 'Animar', Thumbnails: 'Miniaturas',
  'Real videos': 'Vídeos reales', 'How it works': 'Cómo funciona', 'The toolkit': 'Las herramientas',
  'Pick a lane': 'Elige una temática', 'Common questions': 'Preguntas frecuentes',
  'All free tools': 'Todas las herramientas gratuitas', 'Product': 'Producto',
  Compare: 'Comparar', 'Shorts money & growth': 'Ingresos y crecimiento con Shorts',
  'Terms of Service': 'Términos del servicio', 'Privacy Policy': 'Política de privacidad',
  'Trust Center': 'Centro de confianza', Contact: 'Contacto',
  Write: 'Escribir', Plan: 'Planificar', 'Review & publish': 'Revisar y publicar',
  'Engine': 'Motor', 'Your image': 'Tu imagen', 'Your script': 'Tu guion', Format: 'Formato',
  Voice: 'Voz', 'Your images': 'Tus imágenes', 'Your audio': 'Tus audios',
  'Cost per image': 'Coste por imagen', Cost: 'Coste', 'Try again': 'Volver a intentar',
  Download: 'Descargar', 'Download audio': 'Descargar audio', 'Download image': 'Descargar imagen',
  'No videos yet': 'Todavía no tienes vídeos', 'No images yet': 'Todavía no tienes imágenes',
  'No audio yet': 'Todavía no tienes audios', Videos: 'Vídeos',
  'Make a video': 'Crear un vídeo', 'Create an image': 'Crear una imagen',
  'Create a voiceover': 'Crear una narración', 'Clear search': 'Borrar búsqueda',
  '🎬 Studio — generate video': '🎬 Studio — crear vídeo',
  '🎨 Images — create image': '🎨 Imágenes — crear imagen',
  '🎙 Audio — text to speech': '🎙 Audio — texto a voz',
  'Type it. See it. Six image engines, one screen.': 'Escribe y visualiza. Seis motores de imagen en una pantalla.',
  'Type it. Hear it. Four voice engines, one screen.': 'Escribe y escucha. Cuatro motores de voz en una pantalla.',
  'Everything you’ve created, in one place.': 'Todo lo que has creado, en un solo lugar.',
  'Add credits →': 'Añadir créditos →', 'Sign in →': 'Iniciar sesión →',
  'Upscale any result to 2x for 1 credit.': 'Amplía cualquier resultado a 2× por 1 crédito.',
  'We couldn’t load your images right now.': 'No pudimos cargar tus imágenes en este momento.',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'Tus imágenes y créditos están a salvo: es un fallo temporal de lectura.',
  'We couldn’t load your audio right now.': 'No pudimos cargar tus audios en este momento.',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'Tus audios y créditos están a salvo: es un fallo temporal de lectura.',
  'We couldn’t load part of your library right now.': 'No pudimos cargar parte de tu biblioteca en este momento.',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'Tus vídeos y créditos están a salvo: es un fallo temporal de lectura.',
  '↻ Try again': '↻ Volver a intentar', 'My Images': 'Mis imágenes', 'My Audio': 'Mis audios',
  '⬇ Download': '⬇ Descargar', '🎬 Animate': '🎬 Animar', '✏️ Edit · 3 cr': '✏️ Editar · 3 cr',
  chars: 'caracteres', 'cr per 1000 characters · MP3 download included.': 'cr por cada 1000 caracteres · Descarga MP3 incluida.',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': '¿Te gusta una voz? Studio crea el vídeo completo a su alrededor: imágenes, subtítulos y música.',
  'Open Studio →': 'Abrir Studio →', '🎬 Use in Studio': '🎬 Usar en Studio',
  '⚡ New video': '⚡ Nuevo vídeo', 'No videos yet —': 'Todavía no tienes vídeos —',
  'open the Studio': 'abre Studio', 'and make your first film.': 'y crea tu primer vídeo.',
  'No videos match “': 'No hay vídeos que coincidan con “',
  'No images match “': 'No hay imágenes que coincidan con “',
  'No audio matches “': 'No hay audios que coincidan con “',
  'Next episode →': 'Siguiente episodio →', 'No images yet —': 'Todavía no tienes imágenes —',
  'create your first image': 'crea tu primera imagen', 'No audio yet —': 'Todavía no tienes audios —',
  'generate your first voiceover': 'crea tu primera narración',
  Image: 'Imagen', Video: 'Vídeo', Engines: 'Motores', Create: 'Crear',
  'Instant drafts': 'Borradores al instante', 'Sharp & photorealistic': 'Nítido y fotorrealista',
  'Deep prompt understanding': 'Interpretación detallada de instrucciones',
  'Highly aesthetic, by xAI': 'Estética cuidada, de xAI', 'Perfect text rendering': 'Texto preciso en la imagen',
  'Google’s best image model': 'El mejor modelo de imagen de Google',
  'Create Image': 'Crear imagen', 'Six engines, one screen': 'Seis motores, una pantalla',
  'Click-magnet YouTube covers': 'Portadas de YouTube que atraen clics',
  'Bring any image to life': 'Dale vida a una imagen', 'High-fidelity narration': 'Narración de alta fidelidad',
  'Emotion & delivery tags': 'Etiquetas de emoción e interpretación', 'Two-speaker scenes': 'Escenas con dos voces',
  'Instant narration': 'Narración al instante', 'Text to Speech': 'Texto a voz',
  'Four voice engines': 'Cuatro motores de voz', 'Talking Avatar': 'Avatar parlante',
  'A face that speaks your script': 'Un rostro que cuenta tu guion',
  'Every control, one screen': 'Todos los controles en una pantalla',
  'Today’s trending topics': 'Las tendencias de hoy', 'Ready-to-shoot viral scripts': 'Guiones virales listos para producir',
  'Real renders, every engine': 'Vídeos reales de cada motor',
  'Kineo — real AI Shorts, straight from the engines': 'Kineo — Shorts reales con IA, directamente de cada motor',
  'video engines — including Omni Flash, the #1-ranked model (Aug 2026) — six image models, four voices. Every card below is a real render.': 'motores de vídeo, incluido Omni Flash, el modelo n.º 1 (agosto de 2026), seis modelos de imagen y cuatro voces. Cada tarjeta muestra un vídeo real.',
  'Start with the full toolkit': 'Empieza con todas las herramientas', Popular: 'Popular', New: 'Nuevo',
  'Kineo’s own engine — 3–7 min': 'El motor propio de Kineo — 3–7 min',
  'The workhorse AI video engine': 'El motor de vídeo IA para el día a día',
  'Cinematic motion & camera': 'Movimiento y cámara cinematográficos',
  'Google’s flagship, on Studio': 'El modelo insignia de Google, en Studio',
  'Film scenes, native voice & lip sync': 'Escenas de cine, voz nativa y sincronización labial',
  'Talking video from one photo': 'Un vídeo parlante a partir de una foto', 'Explore all →': 'Explorar todo →',
  'From idea to posted Short in 3 steps.': 'De la idea a un Short publicado en 3 pasos.',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'Sin grabar, editar ni usar una línea de tiempo. Escribe una vez y Kineo hace el resto.',
  'Step 1': 'Paso 1', 'Step 2': 'Paso 2', 'Step 3': 'Paso 3', 'Type a topic': 'Escribe un tema',
  '“the island too dangerous to visit”': '“la isla demasiado peligrosa para visitar”',
  'One line — “the island too dangerous to visit” — or paste your own script. Pick a niche and go.': 'Escribe una frase, como “la isla demasiado peligrosa para visitar”, o pega tu guion. Elige una temática y empieza.',
  'Kineo builds it': 'Kineo lo crea',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'La IA escribe un guion orientado a la retención, graba la voz, selecciona las imágenes e incorpora los subtítulos: un vídeo 9:16 terminado.',
  'Download & post': 'Descarga y publica',
  'Grab the clean MP4 and post to YouTube Shorts, TikTok or Reels. It’s yours to keep and monetize.': 'Descarga el MP4 sin marca de agua y publícalo en YouTube Shorts, TikTok o Reels. Es tuyo para conservarlo y monetizarlo.',
  'Why Kineo': 'Por qué Kineo', 'One idea in. A finished Short out.': 'Entra una idea. Sale un Short terminado.',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'Muchas herramientas recortan un vídeo largo que ya grabaste. Kineo lo crea desde cero.',
  'See how to make Shorts without filming →': 'Descubre cómo crear Shorts sin grabar →',
  'Generates the Short from just an idea': 'Crea un Short a partir de una idea', 'Writes the script for you': 'Escribe el guion por ti',
  'AI voiceover included': 'Narración IA incluida', 'Finds and matches footage': 'Busca y combina imágenes',
  'your upload': 'tu archivo', 'avatar only': 'solo avatar', 'No per-minute caps': 'Sin límite por minuto',
  credits: 'créditos', partial: 'parcial', limited: 'limitado', trial: 'prueba',
  'Reusable AI host — same voice & style every episode': 'Presentador IA reutilizable: misma voz y estilo en cada episodio',
  'Free videos, no credit card': 'Vídeos gratuitos, sin tarjeta', 'AI image studio included': 'Estudio de imágenes IA incluido',
  '6 engines': '6 motores', '4 engines': '4 motores', 'Voice studio (text-to-speech)': 'Estudio de voz (texto a voz)',
  'One-click HD film enhance': 'Mejora HD del vídeo con un clic', 'Starting price': 'Precio inicial',
  'Compare Kineo with 27 AI video tools →': 'Compara Kineo con 27 herramientas de vídeo IA →',
  'One idea — or a whole toolkit.': 'Una idea o todo un conjunto de herramientas.',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'Presentadores, personajes reutilizables, clips transparentes y anuncios de productos, además de herramientas para descubrir y aprovechar tendencias.',
  'AI Presenter': 'Presentador IA',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'Una foto y tu guion: un vídeo parlante con sincronización labial de estudio, al estilo de HeyGen.',
  'Try AI Presenter →': 'Probar el presentador IA →',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'Guarda un personaje una vez y utiliza el mismo rostro en cada vídeo y miniatura.',
  'Lock a character →': 'Guardar un personaje →', 'Transparent Clips': 'Clips transparentes',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'Gestos del presentador — saludar, señalar y presentar — en WebM con fondo transparente real.',
  'Make a clip →': 'Crear un clip →', 'UGC Product Ads': 'Anuncios UGC de productos',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'Pega un producto y obtén un anuncio de 15–30 s al estilo de un creador, con guion y voz.',
  'Make an ad →': 'Crear un anuncio →',
  'Bring any still photo to life as a moving, postable video.': 'Transforma una foto en un vídeo en movimiento, listo para publicar.',
  'Animate a photo →': 'Animar una foto →', 'AI Thumbnails': 'Miniaturas con IA',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'Miniaturas atractivas al estilo de los grandes canales, a partir de una descripción.',
  'Make a thumbnail →': 'Crear una miniatura →',
  'Today’s trending topics, ready to turn into a Short with one click.': 'Las tendencias de hoy, listas para convertirse en un Short con un clic.',
  'Today\'s trending topics, ready to turn into a Short with one click.': 'Las tendencias de hoy, listas para convertirse en un Short con un clic.',
  'See what\'s trending →': 'Ver las tendencias →', 'Free AI Shorts': 'Shorts gratuitos con IA',
  'Type one idea and test the full Fast workflow with no card.': 'Escribe una idea y prueba el flujo completo de Fast sin tarjeta.',
  'Generate free →': 'Crear gratis →', 'Start with a niche that already works.': 'Empieza con una temática que ya funciona.',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'Cada temática tiene su página de creación, instrucciones adaptadas y ejemplos reales.',
  Mystery: 'Misterio', Money: 'Dinero', 'True Crime': 'Crímenes reales', Billionaires: 'Multimillonarios',
  History: 'Historia', Facts: 'Curiosidades', AI: 'IA', Space: 'Espacio', Psychology: 'Psicología',
  Motivation: 'Motivación', Horror: 'Terror', Geography: 'Geografía', Stoicism: 'Estoicismo',
  'Not sure? Take the quiz →': '¿Tienes dudas? Haz el cuestionario →',
  'Pick your engine. Ship a Short today.': 'Elige tu motor. Publica un Short hoy.',
  'Cancel anytime': 'Cancela cuando quieras',
  'Creating…': 'Creando…', 'Generate image →': 'Crear imagen →',
  'Describe your image first': 'Primero describe tu imagen', 'Generate audio →': 'Crear audio →',
  'Type your script first': 'Primero escribe tu guion',
  'Simple pricing. Try Fast free first.': 'Planes sencillos. Prueba Fast gratis primero.',
  'Paid plans unlock clean MP4s.': 'Los planes de pago desbloquean MP4 sin marca de agua.',
  'Best for starting out': 'Ideal para empezar', 'Most popular': 'El más popular',
  'Best value per film': 'Mejor coste por vídeo', 'Up to': 'Hasta', 'AI images': 'imágenes con IA',
  'on Nano Banana': 'con Nano Banana', 'AI voiceovers': 'narraciones con IA', '· 4 voices': '· 4 voces',
  'Every video engine incl. MiniMax H3': 'Todos los motores de vídeo, incluido MiniMax H3',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'MP4 sin marca de agua · 100 proyectos · 90 días de almacenamiento',
  ', finished': ', terminados', Or: 'O', 'Kling 2.5 cinematic films': 'vídeos cinematográficos con Kling 2.5',
  '— every engine unlocked': '— todos los motores desbloqueados',
  '· voice + karaoke captions + score': '· voz, subtítulos karaoke y música',
  '500 projects · forever storage': '500 proyectos · almacenamiento permanente',
  'Cancel anytime — 7-day money-back': 'Cancela cuando quieras · devolución durante 7 días',
  'films on Omni Flash': 'vídeos con Omni Flash', '— the #1-ranked model': '— el modelo n.º 1',
  '· 2 free HD enhances / month': '· 2 mejoras HD gratuitas al mes',
  'Unlimited projects · forever storage': 'Proyectos ilimitados · almacenamiento permanente',
  'Everything in Creator': 'Todo lo incluido en Creator', 'Try it first:': 'Pruébalo primero:',
  'Secure checkout by Stripe · Cancel in one click · Credits refunded automatically if a render fails': 'Pago seguro con Stripe · Cancela con un clic · Devolución automática de créditos si falla la generación',
  'Full pricing, FAQ & plan comparison →': 'Todos los precios, preguntas y comparación de planes →',
  'Calculate your cost per Short →': 'Calcula el coste de tu Short →',
  'How much do Shorts pay? →': '¿Cuánto pagan los Shorts? →', 'Highest-RPM niches →': 'Temáticas con mayor RPM →',
  'From the founder': 'Del fundador', 'read the full review →': 'leer la reseña completa →',
  'Is the video really mine to post?': '¿Puedo publicar el vídeo como mío?',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'Los planes de pago desbloquean el MP4 sin marca de agua para YouTube, TikTok o Reels.',
  'Do I need any editing skills?': '¿Necesito saber editar?',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'No. Escribes una idea y la IA redacta el guion, graba la voz, busca las imágenes y añade subtítulos.',
  'Is there a watermark?': '¿Hay marca de agua?',
  'Paid plans export clean, watermark-free MP4s.': 'Los planes de pago exportan MP4 sin marca de agua.',
  'Can Kineo also generate images and voiceovers?': '¿Kineo también crea imágenes y narraciones?',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'Sí. Kineo incluye un estudio de imágenes IA (6 motores, incluidos FLUX, Seedream y Nano Banana Pro, desde 1 crédito por imagen) y un estudio de voz con 4 motores de texto a voz (desde 1 crédito por cada 1000 caracteres). Todo lo que creas se guarda en tu biblioteca.',
  'Can I make my videos sharper?': '¿Puedo mejorar la nitidez de mis vídeos?',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'Cada vídeo tiene una opción de mejora con un clic mediante restauración Topaz: elimina artefactos de compresión, recupera detalles y añade grano cinematográfico fino. Cuesta 10 créditos por vídeo; Studio incluye 2 mejoras gratuitas al mes.',
  'Can I use my own script?': '¿Puedo usar mi propio guion?',
  'Yes — paste your script and pick “Use my script as is” and the AI narrates it word for word.': 'Sí. Pega tu guion y elige “Use my script as is” para que la IA lo narre palabra por palabra.',
  'What if a generation fails?': '¿Qué pasa si falla una generación?',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'Tus créditos vuelven automáticamente cuando falla la generación, sin abrir una solicitud de soporte ni esperar. Solo pagas por los vídeos que recibes.',
  'Can I cancel anytime?': '¿Puedo cancelar cuando quiera?',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'Cuando quieras, con un clic. Los planes son mensuales y los créditos se renuevan cada mes.',
  'Can I run a whole channel with the same host?': '¿Puedo mantener el mismo presentador en todo el canal?',
  'Yes — that’s the point. Keep the same voice, style and captions across every episode so your channel looks consistent, without filming a single frame.': 'Sí. Mantén la misma voz, el mismo estilo y los mismos subtítulos en todos los episodios para que tu canal sea coherente, sin grabar una sola imagen.',
  'Can I monetize the videos?': '¿Puedo monetizar los vídeos?',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'Sí. Cada vídeo es tuyo para conservarlo, publicarlo y monetizarlo, incluido el Programa de Socios de YouTube, TikTok y Reels. No necesitas una licencia adicional.',
  'Can I use the videos commercially, or for client work?': '¿Puedo usar los vídeos comercialmente o para clientes?',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'Sí. Nuestros términos permiten usar Kineo con fines personales o comerciales lícitos y confirman que conservas la propiedad de los vídeos que generas. Puedes publicarlos, monetizarlos y entregarlos a un cliente como parte de tu servicio de pago, sin licencia adicional ni regalías por vídeo. Los mismos términos establecen dos límites: no puedes revender ni redistribuir Kineo, y la licencia de los clips de archivo cubre su uso en el vídeo terminado, no su redistribución como archivos independientes. Los planes de pago exportan el MP4 sin marca de agua.',
  'How long does one video take?': '¿Cuánto tarda un vídeo?',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'Fast suele terminar en 3–7 minutos. Los vídeos generados con IA y los cinematográficos tardan algo más porque se genera cada escena antes de componer el MP4 final.',
  'How much does Kineo cost?': '¿Cuánto cuesta Kineo?',
  'Kineo has three monthly plans: Starter at $': 'Kineo tiene tres planes mensuales: Starter por $',
  for: 'por', 'credits, Creator at $': 'créditos, Creator por $', 'credits and Studio at $': 'créditos y Studio por $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'créditos. El consumo por vídeo depende del motor que elijas: un vídeo Fast y uno cinematográfico utilizan el mismo saldo, pero a costes muy distintos.',
  'New accounts get free credits to make a first video before paying anything.': 'Las cuentas nuevas reciben créditos gratuitos para crear su primer vídeo antes de pagar.',
  'Which AI video engines can I use in Kineo?': '¿Qué motores de vídeo IA puedo usar en Kineo?',
  ', behind one interface and one balance:': ', con una sola interfaz y un solo saldo:',
  'Omni Flash (Google’s #1-ranked video model, Aug 2026), Veo 3.1, Kling 3, MiniMax H3, Kling 2.5, Seedance 1.5, Kineo 1 and Avatar. You choose the engine per video, so a cheap explainer and a cinematic flagship can come out of the same account on the same day. Every clip on this page is a real render from the engine named on the card — the badge always tells the truth about which model made it.': 'Omni Flash (modelo de vídeo n.º 1 de Google, agosto de 2026), Veo 3.1, Kling 3, MiniMax H3, Kling 2.5, Seedance 1.5, Kineo 1 y Avatar. Elige el motor para cada vídeo: puedes crear una explicación económica y una pieza cinematográfica desde la misma cuenta y el mismo día. Cada clip de esta página es un vídeo real del motor indicado en su tarjeta.',
  'What is the best AI video generator for faceless YouTube channels?': '¿Cuál es el mejor generador de vídeo IA para canales sin presentador?',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'Sí. Los usuarios gratuitos que nunca han pagado pueden descargar, compartir y publicar el MP4 con marca de agua.',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'Los vídeos de prueba llevan una pequeña marca de agua: puedes descargar, compartir y publicar el MP4. Tras la prueba, el vídeo Fast gratuito también lleva marca de agua.',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'Las descargas gratuitas llevan marca de agua; los planes de pago desbloquean el MP4 sin ella.',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'Las descargas de prueba y el vídeo Fast gratuito posterior llevan marca de agua. Los planes de pago exportan sin ella.',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'El acceso gratuito permite a los usuarios nuevos crear hasta 3 vídeos Fast con marca de agua cada 24 horas, sin tarjeta. Puedes descargarlos y compartirlos.',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'Crea, descarga y comparte hasta 3 vídeos Fast con marca de agua cada 24h, sin tarjeta.',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'Crea, mira, descarga y comparte hasta 3 vídeos Fast con marca de agua cada 24h, sin tarjeta.',
  'create, watch, download and share up to 3 Fast videos every 24h': 'crear, mirar, descargar y compartir hasta 3 vídeos Fast cada 24h',
  '— no card, watermark included.': '— sin tarjeta, con marca de agua.', '— no card.': '— sin tarjeta.',
  Eight: 'Ocho', Nine: 'Nueve', 'Create a video': 'Crear un vídeo',
  Start: 'Empezar', 'Go Creator': 'Elegir Creator', 'Go Studio': 'Elegir Studio', '/mo': '/mes',
  'AI image generator — 6 engines': 'Generador de imágenes IA — 6 motores',
  'AI voice generator (text to speech)': 'Generador de voz IA (texto a voz)',
  'AI video upscaler & enhancer': 'Ampliar y mejorar vídeos con IA',
  'Trending Shorts ideas today': 'Ideas de Shorts en tendencia hoy',
  'AI Avatar video — your face, any script': 'Vídeo con avatar IA: tu rostro y tu guion',
  'Kineo facts & numbers (citable)': 'Datos y cifras de Kineo (citables)',
  'Free AI Shorts generator': 'Generador gratuito de Shorts con IA',
  'Faceless video generator': 'Generador de vídeos sin presentador',
  'YouTube Shorts from a topic': 'YouTube Shorts a partir de un tema',
  'Text to video Shorts': 'Del texto a un Short',
  'ChatGPT script to YouTube Short': 'Del guion de ChatGPT a un YouTube Short',
  'Cheapest AI Shorts maker': 'El creador de Shorts IA más económico',
  'Shorts without filming': 'Shorts sin grabar',
  'Faceless channel ideas (2026)': 'Ideas de canales sin presentador (2026)',
  'Faceless niche picker': 'Elegir una temática sin presentador',
  'Shorts idea widget': 'Widget de ideas para Shorts',
  'State of AI Shorts 2026': 'Estado de los Shorts IA en 2026',
  'Live case study: our channel on Autopilot': 'Caso práctico: nuestro canal en Autopilot',
  'AI Shorts for agencies & client work': 'Shorts IA para agencias y clientes',
  'Trust Center — privacy, payments & ownership': 'Centro de confianza: privacidad, pagos y propiedad',
  'Affiliate program - 40% recurring': 'Programa de afiliados: 40% recurrente',
  'Free AI Shorts by niche': 'Shorts IA gratuitos por temática',
  'Free YouTube Shorts scripts': 'Guiones gratuitos para YouTube Shorts',
  'Free script generator': 'Generador gratuito de guiones',
  'Comment to Short script': 'De un comentario a un guion de Short',
  'Product video ad script': 'Guion de anuncio de producto',
  'Business video content planner': 'Planificador de vídeos para empresas',
  'Client video brief generator': 'Generador de briefs de vídeo para clientes',
  'Real estate video maker': 'Creador de vídeos inmobiliarios',
  'Free hook generator': 'Generador gratuito de ganchos',
  'Shorts title & hashtag generator': 'Generador de títulos y hashtags para Shorts',
  'Shorts script timer': 'Medidor de duración de guiones',
  'Free viral score': 'Evaluación viral gratuita',
  'Shorts money calculator': 'Calculadora de ingresos de Shorts',
  'Make money clipping with AI': 'Ganar dinero con clips e IA',
  'How much do Shorts pay?': '¿Cuánto pagan los Shorts?',
  'Shorts RPM by niche (2026)': 'RPM de Shorts por temática (2026)',
  'Best AI Shorts generators': 'Los mejores generadores de Shorts IA',
  'Can you monetize AI videos?': '¿Se pueden monetizar los vídeos con IA?',
  'TikTok vs Shorts: which pays more?': 'TikTok frente a Shorts: ¿cuál paga más?',
  'All comparisons': 'Todas las comparaciones', 'Vidyo.ai / Quso pricing': 'Planes de Vidyo.ai / Quso',
  'Turn one idea into a ready-to-post faceless YouTube Short — script, AI voiceover, footage & captions in a few minutes.': 'Convierte una idea en un YouTube Short sin presentador, listo para publicar: guion, voz IA, imágenes y subtítulos en unos minutos.',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · Todos los derechos reservados',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'Depende de si quieres montar imágenes de archivo o generar imágenes nuevas. InVideo y AutoShorts adaptan clips de archivo al guion, una opción más económica para vídeos explicativos. Kineo genera imágenes con modelos como Veo 3.1 y Kling 3, conserva la narración palabra por palabra y apunta a 60 segundos o más para TikTok Creator Rewards. Si tu canal depende de imágenes únicas, conviene la generación; si depende del volumen, el archivo es más económico.',
}
