/** Authored interface copy only. Never translate a prompt, title, result or API error.
 * Unknown copy explicitly falls back to English; country never selects this locale.
 */
export const INTERFACE_HI: Record<string, string> = {
  Home: 'होम', Dashboard: 'डैशबोर्ड', 'Creator Hub': 'क्रिएटर हब', Studio: 'Studio',
  'Create Video': 'वीडियो बनाएँ', 'Create a video': 'वीडियो बनाएँ', 'Create new video': 'नया वीडियो बनाएँ',
  'Create a new video': 'नया वीडियो बनाएँ', 'Generate New Short': 'नया Short बनाएँ',
  Images: 'चित्र', Audio: 'ऑडियो', Library: 'लाइब्रेरी', 'My Videos': 'मेरे वीडियो',
  'AI Avatar Studio': 'AI अवतार स्टूडियो', 'Animate a Photo': 'फ़ोटो एनिमेट करें',
  Examples: 'उदाहरण', Pricing: 'प्लान', Plans: 'प्लान', Account: 'खाता',
  'Viral Templates': 'वायरल टेम्पलेट', 'Video Studio': 'वीडियो स्टूडियो',
  'Channel Builder': 'चैनल बनाएँ', 'AI Thumbnail Generator': 'AI थंबनेल बनाएँ',
  'Invite & Earn': 'आमंत्रित करें और कमाएँ', 'Affiliate Dashboard': 'अफ़िलिएट डैशबोर्ड',
  Tools: 'टूल', More: 'और', 'Free tools': 'मुफ़्त टूल', 'Editing tools': 'एडिटिंग टूल',
  'Start free': 'मुफ़्त शुरू करें', 'Sign in': 'साइन इन करें', 'Log in': 'लॉग इन करें',
  // KINEO-VERSAO-B-2026-09-08 (tarefa 8) — rótulos da porta de $1 e dos planos
  'Try 7 days for $1': '$1 में 7 दिन आज़माएँ', 'Try Creator 7 days for $1 →': 'Creator को $1 में 7 दिन आज़माएँ →', 'Simple pricing. Start with 7 days for $1.': 'सरल कीमतें। $1 में 7 दिन से शुरू करें।', 'Type one idea, start your $1 trial and make the film.': 'एक आइडिया लिखें, $1 ट्रायल शुरू करें और फ़िल्म बनाएँ।', 'Entry': 'प्रवेश', 'Continue now': 'अभी जारी रखें', 'Start for $1: 7 days of Creator with 80 credits, Kineo 1 and Seedance unlocked. Then $29/month, cancel anytime.': '$1 में शुरू करें: Creator के 7 दिन, 80 क्रेडिट, Kineo 1 और Seedance अनलॉक। फिर $29/माह, कभी भी रद्द करें।',
  Explore: 'देखें', Scripts: 'स्क्रिप्ट', Animate: 'एनिमेट करें', Thumbnails: 'थंबनेल',
  'Real videos': 'असली वीडियो', 'How it works': 'यह कैसे काम करता है', 'The toolkit': 'टूलकिट',
  'Pick a lane': 'विषय चुनें', 'Common questions': 'आम सवाल',
  'All free tools': 'सभी मुफ़्त टूल', Product: 'प्रोडक्ट', Compare: 'तुलना करें',
  'Terms of Service': 'सेवा की शर्तें', 'Privacy Policy': 'गोपनीयता नीति',
  'Trust Center': 'ट्रस्ट सेंटर', Contact: 'संपर्क', Write: 'लिखें', Plan: 'योजना बनाएँ',
  'Review & publish': 'समीक्षा करें और प्रकाशित करें', Engine: 'इंजन', Format: 'फ़ॉर्मैट',
  'Your image': 'आपका चित्र', 'Your script': 'आपकी स्क्रिप्ट', 'Your idea': 'आपका विचार',
  Voice: 'आवाज़', 'Your images': 'आपके चित्र', 'Your audio': 'आपका ऑडियो',
  'Cost per image': 'प्रति चित्र लागत', Cost: 'लागत', 'Try again': 'फिर कोशिश करें',
  Download: 'डाउनलोड', 'Download audio': 'ऑडियो डाउनलोड करें', 'Download image': 'चित्र डाउनलोड करें',
  'No videos yet': 'अभी कोई वीडियो नहीं है', 'No images yet': 'अभी कोई चित्र नहीं है',
  'No audio yet': 'अभी कोई ऑडियो नहीं है', Videos: 'वीडियो',
  'Make a video': 'वीडियो बनाएँ', 'Create an image': 'चित्र बनाएँ',
  'Create a voiceover': 'वॉइसओवर बनाएँ', 'Clear search': 'खोज साफ़ करें',
  '🎬 Studio — generate video': '🎬 Studio — वीडियो बनाएँ',
  '🎨 Images — create image': '🎨 चित्र — चित्र बनाएँ',
  '🎙 Audio — text to speech': '🎙 ऑडियो — टेक्स्ट से आवाज़',
  'Type it. See it. Six image engines, one screen.': 'लिखें और देखें। एक स्क्रीन पर छह चित्र इंजन।',
  'Type it. Hear it. Four voice engines, one screen.': 'लिखें और सुनें। एक स्क्रीन पर चार वॉइस इंजन।',
  'Everything you’ve created, in one place.': 'आपकी सारी रचनाएँ, एक जगह।',
  'Add credits →': 'क्रेडिट जोड़ें →', 'Sign in →': 'साइन इन करें →',
  'Upscale any result to 2x for 1 credit.': '1 क्रेडिट में किसी भी परिणाम को 2x बड़ा करें।',
  'We couldn’t load your images right now.': 'अभी आपके चित्र लोड नहीं हो सके।',
  'Your images and credits are safe — this is just a temporary read hiccup.': 'आपके चित्र और क्रेडिट सुरक्षित हैं — यह डेटा पढ़ने में एक अस्थायी समस्या है।',
  'We couldn’t load your audio right now.': 'अभी आपका ऑडियो लोड नहीं हो सका।',
  'Your audio and credits are safe — this is just a temporary read hiccup.': 'आपका ऑडियो और क्रेडिट सुरक्षित हैं — यह डेटा पढ़ने में एक अस्थायी समस्या है।',
  'We couldn’t load part of your library right now.': 'अभी आपकी लाइब्रेरी का कुछ हिस्सा लोड नहीं हो सका।',
  'Your videos and credits are safe — this is just a temporary read hiccup.': 'आपके वीडियो और क्रेडिट सुरक्षित हैं — यह डेटा पढ़ने में एक अस्थायी समस्या है।',
  '↻ Try again': '↻ फिर कोशिश करें', 'My Images': 'मेरे चित्र', 'My Audio': 'मेरा ऑडियो',
  '⬇ Download': '⬇ डाउनलोड', '🎬 Animate': '🎬 एनिमेट करें', '✏️ Edit · 3 cr': '✏️ संपादित करें · 3 cr',
  chars: 'अक्षर', 'cr per 1000 characters · MP3 download included.': 'cr प्रति 1000 अक्षर · MP3 डाउनलोड शामिल है।',
  'Like a voice? The Studio builds the whole film around it — visuals, captions and score.': 'आवाज़ पसंद आई? Studio उसके साथ पूरा वीडियो बनाता है — दृश्य, कैप्शन और संगीत।',
  'Open Studio →': 'Studio खोलें →', '🎬 Use in Studio': '🎬 Studio में इस्तेमाल करें',
  '⚡ New video': '⚡ नया वीडियो', 'No videos yet —': 'अभी कोई वीडियो नहीं है —',
  'open the Studio': 'Studio खोलें', 'and make your first film.': 'और अपना पहला वीडियो बनाएँ।',
  'No videos match “': 'इस खोज से कोई वीडियो नहीं मिला: “',
  'No images match “': 'इस खोज से कोई चित्र नहीं मिला: “',
  'No audio matches “': 'इस खोज से कोई ऑडियो नहीं मिला: “',
  'Next episode →': 'अगला एपिसोड →', 'No images yet —': 'अभी कोई चित्र नहीं है —',
  'create your first image': 'अपना पहला चित्र बनाएँ', 'No audio yet —': 'अभी कोई ऑडियो नहीं है —',
  'generate your first voiceover': 'अपना पहला वॉइसओवर बनाएँ',
  Image: 'चित्र', Video: 'वीडियो', Engines: 'इंजन', Create: 'बनाएँ',
  'Instant drafts': 'तुरंत ड्राफ़्ट', 'Sharp & photorealistic': 'स्पष्ट और फ़ोटो जैसा वास्तविक',
  'Deep prompt understanding': 'निर्देशों की गहरी समझ', 'Highly aesthetic, by xAI': 'xAI की आकर्षक शैली',
  'Perfect text rendering': 'चित्र में सटीक टेक्स्ट', 'Google’s best image model': 'Google का सर्वश्रेष्ठ चित्र मॉडल',
  'Create Image': 'चित्र बनाएँ', 'Six engines, one screen': 'छह इंजन, एक स्क्रीन',
  'Click-magnet YouTube covers': 'क्लिक आकर्षित करने वाले YouTube कवर',
  'Bring any image to life': 'चित्र में जान डालें', 'High-fidelity narration': 'उच्च गुणवत्ता की नैरेशन',
  'Emotion & delivery tags': 'भावना और बोलने की शैली के टैग', 'Two-speaker scenes': 'दो वक्ताओं वाले दृश्य',
  'Instant narration': 'तुरंत नैरेशन', 'Text to Speech': 'टेक्स्ट से आवाज़',
  'Four voice engines': 'चार वॉइस इंजन', 'Talking Avatar': 'बोलता अवतार',
  'A face that speaks your script': 'आपकी स्क्रिप्ट बोलता एक चेहरा',
  'Every control, one screen': 'सारे कंट्रोल, एक स्क्रीन',
  'Today’s trending topics': 'आज के ट्रेंडिंग विषय', 'Ready-to-shoot viral scripts': 'वीडियो के लिए तैयार वायरल स्क्रिप्ट',
  'Real renders, every engine': 'हर इंजन के असली वीडियो',
  'Type an idea — watch it become a film.': 'एक विचार लिखें — उसे वीडियो बनते देखें।',
  'Start with the full toolkit': 'पूरे टूलकिट के साथ शुरू करें', Popular: 'लोकप्रिय', New: 'नया',
  'Kineo’s own engine — 3–7 min': 'Kineo का अपना इंजन — 3–7 मिनट',
  'The workhorse AI video engine': 'रोज़मर्रा के काम के लिए AI वीडियो इंजन',
  'Cinematic motion & camera': 'सिनेमाई गति और कैमरा',
  'Google’s flagship, on Studio': 'Studio पर Google का फ़्लैगशिप',
  'Film scenes, native voice & lip sync': 'फ़िल्मी दृश्य, मूल आवाज़ और लिप सिंक',
  'Talking video from one photo': 'एक फ़ोटो से बोलता वीडियो', 'Explore all →': 'सभी देखें →',
  'From idea to posted Short in 3 steps.': 'विचार से प्रकाशित Short तक, 3 चरणों में।',
  'No filming, no editing, no timeline. Type once — Kineo does the rest.': 'न शूटिंग, न एडिटिंग, न टाइमलाइन। एक बार लिखें — बाकी Kineo करेगा।',
  'Step 1': 'चरण 1', 'Step 2': 'चरण 2', 'Step 3': 'चरण 3', 'Type a topic': 'विषय लिखें',
  '“the island too dangerous to visit”': '“वह द्वीप जहाँ जाना बहुत ख़तरनाक है”',
  'One line — “the island too dangerous to visit” — or paste your own script. Pick a niche and go.': 'एक पंक्ति लिखें — “वह द्वीप जहाँ जाना बहुत ख़तरनाक है” — या अपनी स्क्रिप्ट पेस्ट करें। विषय चुनें और शुरू करें।',
  'Kineo builds it': 'Kineo वीडियो बनाता है',
  'AI writes a retention-structured script, records the voiceover, matches the footage and burns in captions — a finished 9:16 video.': 'AI दर्शक को जोड़े रखने वाली स्क्रिप्ट लिखता है, वॉइसओवर रिकॉर्ड करता है, दृश्य मिलाता है और कैप्शन जोड़ता है — तैयार 9:16 वीडियो।',
  'Download & post': 'डाउनलोड करें और पोस्ट करें',
  'Why Kineo': 'Kineo क्यों', 'One idea in. A finished Short out.': 'एक विचार दें। तैयार Short पाएँ।',
  'Most tools re-clip a long video you already filmed. Kineo builds it from scratch.': 'ज़्यादातर टूल आपके पहले से रिकॉर्ड किए लंबे वीडियो को काटते हैं। Kineo उसे शुरुआत से बनाता है।',
  'See how to make Shorts without filming →': 'बिना शूटिंग Shorts बनाना सीखें →',
  'Generates the Short from just an idea': 'सिर्फ़ एक विचार से Short बनाता है',
  'Writes the script for you': 'आपके लिए स्क्रिप्ट लिखता है', 'AI voiceover included': 'AI वॉइसओवर शामिल',
  'Finds and matches footage': 'सही दृश्य ढूँढता और मिलाता है',
  'your upload': 'आपका अपलोड', 'avatar only': 'सिर्फ़ अवतार', 'No per-minute caps': 'प्रति मिनट सीमा नहीं',
  credits: 'क्रेडिट', partial: 'आंशिक', limited: 'सीमित', trial: 'ट्रायल',
  'Free videos, no credit card': 'मुफ़्त वीडियो, क्रेडिट कार्ड की ज़रूरत नहीं',
  'AI image studio included': 'AI चित्र स्टूडियो शामिल', '6 engines': '6 इंजन', '4 engines': '4 इंजन',
  'Voice studio (text-to-speech)': 'वॉइस स्टूडियो (टेक्स्ट से आवाज़)',
  'One-click HD film enhance': 'एक क्लिक में HD वीडियो सुधार', 'Starting price': 'शुरुआती कीमत',
  'One idea — or a whole toolkit.': 'एक विचार — या पूरा टूलकिट।', 'AI Presenter': 'AI प्रस्तुतकर्ता',
  'Try AI Presenter →': 'AI प्रस्तुतकर्ता आज़माएँ →', 'Lock a character →': 'किरदार सहेजें →',
  'Transparent Clips': 'पारदर्शी क्लिप', 'Make a clip →': 'क्लिप बनाएँ →',
  'UGC Product Ads': 'UGC प्रोडक्ट विज्ञापन', 'Make an ad →': 'विज्ञापन बनाएँ →',
  'Animate a photo →': 'फ़ोटो एनिमेट करें →', 'AI Thumbnails': 'AI थंबनेल',
  'Make a thumbnail →': 'थंबनेल बनाएँ →', "See what's trending →": 'ट्रेंड देखें →',
  'Free AI Shorts': 'मुफ़्त AI Shorts', 'Generate free →': 'मुफ़्त बनाएँ →',
  'Start with a niche that already works.': 'ऐसे विषय से शुरू करें जो पहले से लोकप्रिय है।',
  Mystery: 'रहस्य', Money: 'पैसा', 'True Crime': 'सच्चे अपराध', Billionaires: 'अरबपति',
  History: 'इतिहास', Facts: 'तथ्य', AI: 'AI', Space: 'अंतरिक्ष', Psychology: 'मनोविज्ञान',
  Motivation: 'प्रेरणा', Horror: 'डरावनी कहानियाँ', Geography: 'भूगोल', Stoicism: 'स्टोइक दर्शन',
  'Not sure? Take the quiz →': 'तय नहीं कर पा रहे? क्विज़ लें →',
  'Pick your engine. Ship a Short today.': 'इंजन चुनें। आज ही Short प्रकाशित करें।',
  'Cancel anytime': 'कभी भी रद्द करें', 'Creating…': 'बन रहा है…',
  'Generate image →': 'चित्र बनाएँ →', 'Describe your image first': 'पहले अपने चित्र का वर्णन करें',
  'Generate audio →': 'ऑडियो बनाएँ →', 'Type your script first': 'पहले अपनी स्क्रिप्ट लिखें',
  'Simple pricing. Try Fast free first.': 'सरल प्लान। पहले Fast मुफ़्त आज़माएँ।',
  'Paid plans unlock clean MP4s.': 'सशुल्क प्लान बिना वॉटरमार्क MP4 उपलब्ध कराते हैं।',
  'Best for starting out': 'शुरुआत के लिए', 'Most popular': 'सबसे लोकप्रिय',
  'Best value per film': 'प्रति वीडियो बेहतर मूल्य', 'Up to': 'अधिकतम', 'AI images': 'AI चित्र',
  'on Nano Banana': 'Nano Banana पर', 'AI voiceovers': 'AI वॉइसओवर', '· 4 voices': '· 4 आवाज़ें',
  'Every video engine incl. MiniMax H3': 'MiniMax H3 सहित सभी वीडियो इंजन',
  'Watermark-free MP4 · 100 projects · 90-day storage': 'बिना वॉटरमार्क MP4 · 100 प्रोजेक्ट · 90-दिन स्टोरेज',
  ', finished': ', तैयार', Or: 'या', 'Kling 2.5 cinematic films': 'Kling 2.5 सिनेमाई वीडियो',
  '— every engine unlocked': '— सभी इंजन उपलब्ध',
  '· voice + karaoke captions + score': '· आवाज़ + कराओके कैप्शन + संगीत',
  '500 projects · forever storage': '500 प्रोजेक्ट · स्थायी स्टोरेज',
  'Cancel anytime — 7-day money-back': 'कभी भी रद्द करें — 7-दिन की धनवापसी',
  'films on Omni Flash': 'Omni Flash पर वीडियो', '— the #1-ranked model': '— #1 स्थान वाला मॉडल',
  '· 2 free HD enhances / month': '· प्रति माह 2 मुफ़्त HD सुधार',
  'Unlimited projects · forever storage': 'असीमित प्रोजेक्ट · स्थायी स्टोरेज',
  'Everything in Creator': 'Creator की सभी सुविधाएँ', 'Try it first:': 'पहले आज़माएँ:',
  'Full pricing, FAQ & plan comparison →': 'सभी कीमतें, सवाल और प्लान की तुलना →',
  'Calculate your cost per Short →': 'प्रति Short लागत निकालें →',
  'How much do Shorts pay? →': 'Shorts से कितनी कमाई होती है? →',
  'Highest-RPM niches →': 'अधिक RPM वाले विषय →', 'From the founder': 'संस्थापक की ओर से',
  'read the full review →': 'पूरी समीक्षा पढ़ें →',
  Eight: 'आठ', Nine: 'नौ', Start: 'शुरू करें', 'Go Creator': 'Creator चुनें', 'Go Studio': 'Studio चुनें', '/mo': '/माह',
  'a single line is enough — or paste a full script': 'एक पंक्ति काफ़ी है — या पूरी स्क्रिप्ट पेस्ट करें',
  '1080×1920 · Full HD master': '1080×1920 · Full HD फ़ाइनल वीडियो',
  'Every film is delivered as a 1080×1920 Full HD master (engines render natively at 720–768p and are mastered up). For maximum sharpness, run ✨HD Enhance on the finished film.': 'हर वीडियो 1080×1920 Full HD में मिलता है (इंजन मूलतः 720–768p पर बनाते हैं, फिर रिज़ॉल्यूशन बढ़ता है)। अधिक स्पष्टता के लिए तैयार वीडियो पर ✨HD Enhance चलाएँ।',
  'Your idea first. Review the settings, then generate.': 'पहले अपना विचार लिखें। सेटिंग जाँचें, फिर वीडियो बनाएँ।',
  '📷 Photo': '📷 फ़ोटो', '🎥 Real video': '🎥 असली वीडियो',
  '🖼️ Upload a different photo': '🖼️ दूसरी फ़ोटो अपलोड करें',
  '🎙️ Generating…': '🎙️ बन रहा है…', '🔊 Preview the voice — free': '🔊 आवाज़ सुनें — मुफ़्त',
  '🎙️ Cloning the voice…': '🎙️ आवाज़ क्लोन हो रही है…',
  '🎙️ Upload a different sample': '🎙️ दूसरा नमूना अपलोड करें', '🎙️ Upload a voice sample': '🎙️ आवाज़ का नमूना अपलोड करें',
  '⏹ Stop & clone': '⏹ रोकें और क्लोन करें', '🔴 Record a sample': '🔴 नमूना रिकॉर्ड करें',
  Natural: 'स्वाभाविक', '⚡ Energetic': '⚡ ऊर्जावान', 'Working…': 'काम हो रहा है…',
  '🎭 Generate my avatar video': '🎭 मेरा अवतार वीडियो बनाएँ', '🎲 Surprise me': '🎲 कोई नया विचार दें',
  'Continue exactly where ChatGPT stopped.': 'जहाँ ChatGPT रुका था, वहीं से आगे बढ़ें।',
  '✨ Let AI structure it': '✨ AI से संरचना बनवाएँ', '📝 Use my script as is': '📝 मेरी स्क्रिप्ट ज्यों की त्यों रखें',
  'Optional settings': 'वैकल्पिक सेटिंग', 'Camera preset': 'कैमरा प्रीसेट',
  'optional — a pre-tested move added to your prompt': 'वैकल्पिक — आपके निर्देश में पहले से जाँची हुई कैमरा गति जोड़ें',
  'Reference image': 'संदर्भ चित्र', SOON: 'जल्द आ रहा है',
  '🖼️ Start your video from an image — coming soon': '🖼️ चित्र से वीडियो शुरू करें — जल्द आ रहा है',
  'Estimated cost': 'अनुमानित लागत', 'Usually takes': 'आम तौर पर लगने वाला समय',
  'Your credits buy': 'आपके क्रेडिट से बनेंगे', 'like this': 'इस तरह के',
  'Voice, karaoke captions and score included. If a render fails, your credits come straight back.': 'आवाज़, कराओके कैप्शन और संगीत शामिल हैं। वीडियो बनना विफल होने पर आपके क्रेडिट वापस आते हैं।',
  'Same topic, new hook and payoff — the idea comes pre-written.': 'वही विषय, नया हुक और अंत — विचार पहले से लिखा मिलता है।',
  'Build next episode →': 'अगला एपिसोड बनाएँ →', 'Your latest videos': 'आपके हाल के वीडियो',
  'Episode 2 →': 'एपिसोड 2 →', Presenter: 'प्रस्तुतकर्ता', 'Avatar Studio →': 'अवतार स्टूडियो →',
  'Talking AI presenter from a photo — lip-synced, its own studio': 'फ़ोटो से बोलता AI प्रस्तुतकर्ता — लिप सिंक के साथ, अलग स्टूडियो में',
  'Your face. Your script.': 'आपका चेहरा। आपकी स्क्रिप्ट।', 'One video.': 'एक वीडियो।',
  'Everything you need to make yourself speak — nothing you don’t.': 'अपनी छवि को बोलने के लिए जो चाहिए, बस वही।',
  'Preview & result ↓': 'प्रीव्यू और परिणाम ↓', '1 · Who’s talking': '1 · कौन बोल रहा है',
  'BEST MOTION': 'बेहतरीन गति', '🎭 your characters': '🎭 आपके किरदार', 'your saved faces': 'आपके सहेजे चेहरे',
  '1.5 · Realism': '1.5 · वास्तविकता', '🎯 Max realism — animate my real photo': '🎯 अधिकतम वास्तविकता — मेरी असली फ़ोटो एनिमेट करें',
  '🎬 Put me in a scene': '🎬 मुझे एक दृश्य में रखें', '✓ Scene ready — preview on the right.': '✓ दृश्य तैयार है — दाईं ओर प्रीव्यू देखें।',
  'use original photo': 'मूल फ़ोटो इस्तेमाल करें', '2 · What they say': '2 · क्या बोलना है', Language: 'भाषा',
  '✍️ Say exactly this — word for word': '✍️ बिल्कुल यही कहें — शब्दशः',
  '✨ Expand into a full Short script (45–60s)': '✨ पूरी Short स्क्रिप्ट में बढ़ाएँ (45–60s)',
  '📦 Product Ad mode — sell a product UGC-style': '📦 प्रोडक्ट विज्ञापन — UGC शैली में बेचें',
  'Free — fills the script box above, then generate with your presenter.': 'मुफ़्त — ऊपर स्क्रिप्ट भरता है, फिर अपने प्रस्तुतकर्ता के साथ वीडियो बनाएँ।',
  '2.5 · Speak in your own voice': '2.5 · अपनी आवाज़ में बोलें', '(optional)': '(वैकल्पिक)',
  '✓ Voice cloned — the narration will speak in this voice.': '✓ आवाज़ क्लोन हो गई — नैरेशन इसी आवाज़ में होगा।',
  'use a default voice': 'डिफ़ॉल्ट आवाज़ चुनें', '3 · How it looks': '3 · कैसा दिखेगा',
  '🎬 Full video — face the whole time': '🎬 पूरा वीडियो — हर समय चेहरा',
  '🎬 AI Presenter — fast & natural · 70 cr': '🎬 AI प्रस्तुतकर्ता — तेज़ और स्वाभाविक · 70 cr',
  '✨ Presenter Pro — premium photo quality · 110 cr': '✨ Presenter Pro — प्रीमियम फ़ोटो गुणवत्ता · 110 cr',
  '🕺 Body Motion — torso, hands & gestures · 110 cr': '🕺 शारीरिक गति — धड़, हाथ और हावभाव · 110 cr',
  '🎙️ Classic — talking head · 110 cr': '🎙️ क्लासिक — बोलता चेहरा · 110 cr',
  Motion: 'गति', 'credits · debited only on success ·': 'क्रेडिट · सफलता पर ही कटते हैं ·',
  'you have': 'आपके पास हैं', 'get credits from': 'क्रेडिट पाएँ, शुरुआत',
  'to create your avatar video.': 'अपना अवतार वीडियो बनाने के लिए।',
  '5 · Gesture clips — transparent background': '5 · हावभाव की क्लिप — पारदर्शी पृष्ठभूमि',
  'auto-refunded if it fails': 'विफल होने पर अपने आप वापस',
  '⬇️ Download transparent WebM': '⬇️ पारदर्शी WebM डाउनलोड करें',
  '⬇️ Original MP4 (with background)': '⬇️ मूल MP4 (पृष्ठभूमि के साथ)',
  'Pick a face to preview': 'प्रीव्यू के लिए चेहरा चुनें', '⬇ Download MP4': '⬇ MP4 डाउनलोड करें',
  '↺ Make another': '↺ एक और बनाएँ', 'One photo. Suddenly alive.': 'एक फ़ोटो। अब जीवंत।',
  'People, pets, products, old family pictures — upload a photo or paste a public image link and watch it move.': 'लोग, पालतू जानवर, प्रोडक्ट या पुरानी पारिवारिक तस्वीरें — फ़ोटो अपलोड करें या सार्वजनिक चित्र लिंक पेस्ट करें और उसे हिलते देखें।',
  'The photo': 'फ़ोटो', 'The motion': 'गति', 'Cost per clip': 'प्रति क्लिप लागत', 'credits ·': 'क्रेडिट ·',
  'JPG/PNG up to 8 MB. Public links are downloaded and validated securely on our server.': 'अधिकतम 8 MB की JPG/PNG। सार्वजनिक लिंक हमारे सर्वर पर सुरक्षित रूप से डाउनलोड और जाँचे जाते हैं।',
  'sign in': 'साइन इन करें', 'Image link ready': 'चित्र लिंक तैयार है',
  'Kineo will fetch and validate it on the server when you animate.': 'एनिमेट करते समय Kineo इसे सर्वर पर डाउनलोड करके जाँचेगा।',
  'Upload a photo to preview': 'प्रीव्यू के लिए फ़ोटो अपलोड करें', '↺ Animate another': '↺ दूसरी फ़ोटो एनिमेट करें',
  '🖼️ Upload a photo': '🖼️ फ़ोटो अपलोड करें', '🖼️ Choose a different photo': '🖼️ दूसरी फ़ोटो चुनें',
  '✨ Bring it to life': '✨ इसमें जान डालें', 'Generate →': 'बनाएँ →', Grow: 'बढ़ें',
  'Uploading your photo…': 'फ़ोटो अपलोड हो रही है…', 'Sending to the motion engine…': 'मोशन इंजन को भेजा जा रहा है…',
  'Bringing your photo to life… (1–3 min)': 'आपकी फ़ोटो जीवंत हो रही है… (1–3 मिनट)',
  'Alive!': 'जीवंत हो गई!', 'Something went wrong.': 'कुछ गड़बड़ हुई।',
  '🌬️ Subtle & real': '🌬️ हल्का और वास्तविक', '🎥 Slow camera push': '🎥 कैमरा धीरे आगे बढ़े',
  '😊 Person comes alive': '😊 व्यक्ति जीवंत हो', '🌊 Scenery flows': '🌊 गतिमान दृश्य',
  'Type your idea first': 'पहले अपना विचार लिखें', '📊 Facts': '📊 तथ्य', '🕵️ Mystery': '🕵️ रहस्य',
  '📖 True Story': '📖 सच्ची कहानी', '📝 My Script': '📝 मेरी स्क्रिप्ट',
  'Paste your ChatGPT script': 'ChatGPT की स्क्रिप्ट पेस्ट करें', 'Paste your ChatGPT idea': 'ChatGPT का विचार पेस्ट करें',
  'First Short complete': 'पहला Short पूरा हुआ', 'Turn it into episode 2': 'इसे एपिसोड 2 बनाएँ',
  'Keep your show moving': 'अपनी सीरीज़ जारी रखें', 'Start here': 'यहाँ से शुरू करें', 'Best value': 'बेहतर मूल्य',
  'Cheapest way to see your idea as a film': 'अपने विचार को वीडियो में देखने का सबसे किफ़ायती तरीका',
  'Slow Dolly-In': 'धीरे आगे बढ़ता कैमरा', 'Crash Zoom': 'तेज़ ज़ूम', Orbit: 'परिक्रमा',
  'FPV Drone': 'FPV ड्रोन', 'Crane Up': 'ऊपर उठता कैमरा', Handheld: 'हाथ में कैमरा',
  'Macro Detail': 'बारीक क्लोज़-अप', 'Locked Tripod': 'स्थिर ट्राइपॉड',
  'Sharing & creator options': 'शेयरिंग और क्रिएटर विकल्प',
  'We couldn’t load your videos right now': 'अभी आपके वीडियो लोड नहीं हो सके',
  'Your videos and credits are safe — this is a temporary read hiccup, not a lost library.': 'आपके वीडियो और क्रेडिट सुरक्षित हैं — यह डेटा पढ़ने की अस्थायी समस्या है, लाइब्रेरी गुम नहीं हुई है।',
  Your: 'आपके', 'Generate your first AI Short and it’ll appear here automatically.': 'अपना पहला AI Short बनाएँ। वह यहाँ अपने आप दिखेगा।',
  '⚡ Generate Video': '⚡ वीडियो बनाएँ', '⚡ New Video': '⚡ नया वीडियो',
  'Prefer clean exports now? Starter includes': 'अभी बिना वॉटरमार्क निर्यात चाहिए? Starter में शामिल हैं',
  'credits each month for': 'क्रेडिट हर महीने, कीमत', '/month. Cancel anytime.': '/माह। कभी भी रद्द करें।',
  'Your existing files stay available. Starter applies to new exports after checkout.': 'आपकी मौजूदा फ़ाइलें उपलब्ध रहती हैं। भुगतान के बाद नए निर्यात पर Starter लागू होता है।',
  'Build Next Episode First': 'पहले अगला एपिसोड बनाएँ', 'Try again →': 'फिर कोशिश करें →',
  'Video unavailable': 'वीडियो उपलब्ध नहीं है', Private: 'निजी',
  'Free MP4 includes the Kineo watermark': 'मुफ़्त MP4 में Kineo वॉटरमार्क शामिल है',
  'Free distribution · latest Short': 'मुफ़्त वितरण · हाल का Short',
  'Send it to one person for feedback': 'राय लेने के लिए किसी एक व्यक्ति को भेजें',
  'Copy a public watch page for your finished video. Your friend can watch it without logging in, then use “Make one like this” if the idea inspires them.': 'तैयार वीडियो का सार्वजनिक पेज कॉपी करें। आपका दोस्त बिना लॉग इन देख सकता है और विचार पसंद आने पर “Make one like this” चुन सकता है।',
  Preview: 'प्रीव्यू', 'Private by default': 'डिफ़ॉल्ट रूप से निजी',
  'Public watch links are temporarily paused': 'सार्वजनिक वीडियो लिंक अस्थायी रूप से बंद हैं',
  'Your video stays in your account. Download the MP4 if you want to send it directly; Kineo will not publish a public page without an explicit visibility choice.': 'वीडियो आपके खाते में रहता है। सीधे भेजने के लिए MP4 डाउनलोड करें; स्पष्ट दृश्यता चयन के बिना Kineo सार्वजनिक पेज प्रकाशित नहीं करेगा।',
  'Loading…': 'लोड हो रहा है…', 'Unlock clean exports — Start Starter for': 'बिना वॉटरमार्क निर्यात पाएँ — Starter शुरू करें, कीमत',
  'For new videos ·': 'नए वीडियो के लिए ·', '/month · cancel anytime': '/माह · कभी भी रद्द करें',
  'Published it?': 'पोस्ट कर दिया?', 'Paste the link and get on the wall →': 'लिंक पेस्ट करें और वॉल पर आएँ →', Close: 'बंद करें',
  'Sharp, front-facing, one person. For body motion, use a waist-up/full-body photo with both hands visible. Black bars are removed automatically.': 'स्पष्ट, सामने से ली गई, एक व्यक्ति की फ़ोटो। शारीरिक गति के लिए कमर से ऊपर या पूरे शरीर की फ़ोटो लें जिसमें दोनों हाथ दिखें। काली पट्टियाँ अपने आप हट जाती हैं।',
  'Best professional result: upload a 5–20s vertical clip doing the real gestures you want, roughly matching the script length. Sync-3 replaces the speech while preserving the real face and body motion. MP4/MOV up to 40 MB.': 'बेहतर पेशेवर परिणाम के लिए, अपने मनचाहे असली हावभाव की 5–20s लंबवत क्लिप अपलोड करें, जिसकी अवधि लगभग स्क्रिप्ट जितनी हो। Sync-3 असली चेहरा और शारीरिक गति बनाए रखते हुए संवाद बदलता है। अधिकतम 40 MB की MP4/MOV।',
  'I confirm I have the right to use this person’s image and consent to it being animated by AI.': 'मैं पुष्टि करता/करती हूँ कि मुझे इस व्यक्ति की छवि इस्तेमाल करने का अधिकार है और मैं इसे AI से एनिमेट करने के लिए सहमत हूँ।',
  'Upload a clear ~30-60s voice sample (one speaker, little background noise) and the narration will be spoken in that voice. Only use a voice you have the right to use.': 'लगभग ~30-60s का स्पष्ट वॉइस नमूना अपलोड करें (एक वक्ता, कम पृष्ठभूमि शोर)। नैरेशन उसी आवाज़ में होगा। सिर्फ़ वही आवाज़ इस्तेमाल करें जिसे इस्तेमाल करने का अधिकार आपके पास है।',
  'Word-for-word videos always show your face the whole time (they’re short — no b-roll needed).': 'शब्दशः वीडियो में हर समय आपका चेहरा दिखता है (वे छोटे हैं — अतिरिक्त दृश्यों की ज़रूरत नहीं)।',
  'Max-realism and built-scene videos keep the presenter on screen for the full narration.': 'अधिकतम वास्तविकता और बनाए गए दृश्य वाले वीडियो में पूरी नैरेशन के दौरान प्रस्तुतकर्ता स्क्रीन पर रहता है।',
  '⚡ Hook intro — you open, b-roll tells the story': '⚡ हुक से शुरुआत — आप शुरू करें, दृश्य कहानी सुनाएँ',
  'Short clips of your presenter waving, pointing, presenting — delivered as WebM with a REAL transparent background. Drop them straight into Storyline, Premiere, CapCut or any slide. No green screen, no keying.': 'आपके प्रस्तुतकर्ता की हाथ हिलाने, इशारा करने या प्रस्तुत करने वाली छोटी क्लिप — असली पारदर्शी पृष्ठभूमि के साथ WebM में। सीधे Storyline, Premiere, CapCut या स्लाइड में जोड़ें। ग्रीन स्क्रीन या कीइंग नहीं चाहिए।',
  "Google's flagship cinematic engine": 'Google का फ़्लैगशिप सिनेमाई इंजन',
  'Cinematic film — 9-image consistency': 'सिनेमाई फ़िल्म — 9-चित्रों में निरंतरता',
  '#1-ranked video model — Aug 2026 arena': '#1 स्थान वाला वीडियो मॉडल — अगस्त 2026 एरीना',
  'Cinematic motion and camera work': 'सिनेमाई गति और कैमरा संचालन',
  'Shorts money & growth': 'Shorts से कमाई और विकास',
  'Kineo — real AI Shorts, straight from the engines': 'Kineo — सीधे इंजन से बने असली AI Shorts',
  'video engines — including Omni Flash, the #1-ranked model (Aug 2026) — six image models, four voices. Every card below is a real render.': 'वीडियो इंजन — Omni Flash, #1 मॉडल (अगस्त 2026), सहित — छह चित्र मॉडल और चार आवाज़ें। नीचे हर कार्ड में असली तैयार वीडियो है।',
  'Grab the clean MP4 and post to YouTube Shorts, TikTok or Reels. It’s yours to keep and monetize.': 'बिना वॉटरमार्क MP4 डाउनलोड करें और YouTube Shorts, TikTok या Reels पर पोस्ट करें। इसे रखना और इससे कमाना आपका अधिकार है।',
  'Reusable AI host — same voice & style every episode': 'दोबारा इस्तेमाल योग्य AI होस्ट — हर एपिसोड में वही आवाज़ और शैली',
  'Compare Kineo with 27 AI video tools →': 'Kineo की 27 AI वीडियो टूल से तुलना करें →',
  'Talking presenters, reusable characters, transparent clips, product ads — plus everything to find and ride a trend.': 'बोलते प्रस्तुतकर्ता, बार-बार इस्तेमाल करने योग्य किरदार, पारदर्शी क्लिप, प्रोडक्ट विज्ञापन — और ट्रेंड ढूँढने व अपनाने के टूल।',
  'One photo + your script — a talking video with studio-grade lip-sync, HeyGen-style.': 'एक फ़ोटो + आपकी स्क्रिप्ट — HeyGen शैली में स्टूडियो-स्तर लिप सिंक वाला बोलता वीडियो।',
  'Save a character once — the exact same face in every video and thumbnail you make.': 'एक बार किरदार सहेजें — आपके हर वीडियो और थंबनेल में बिल्कुल वही चेहरा।',
  'Presenter gestures — wave, point, present — as WebM with a real transparent background.': 'प्रस्तुतकर्ता के हावभाव — हाथ हिलाना, इशारा करना, प्रस्तुत करना — असली पारदर्शी पृष्ठभूमि वाली WebM में।',
  'Paste any product — get a 15-30s creator-style ad, scripted and spoken for you.': 'प्रोडक्ट पेस्ट करें — आपके लिए लिखे और बोले गए संवाद के साथ 15-30s का क्रिएटर-शैली विज्ञापन पाएँ।',
  'Bring any still photo to life as a moving, postable video.': 'स्थिर फ़ोटो को जीवंत, पोस्ट करने योग्य वीडियो बनाएँ।',
  'Click-worthy thumbnails in the style of the biggest channels — from a prompt.': 'निर्देश से बड़े चैनलों की शैली में आकर्षक थंबनेल बनाएँ।',
  'Today’s trending topics, ready to turn into a Short with one click.': 'आज के ट्रेंडिंग विषय, एक क्लिक में Short बनाने के लिए तैयार।',
  "Today's trending topics, ready to turn into a Short with one click.": 'आज के ट्रेंडिंग विषय, एक क्लिक में Short बनाने के लिए तैयार।',
  'Type one idea and test the full Fast workflow with no card.': 'एक विचार लिखें और बिना कार्ड पूरा Fast वर्कफ़्लो आज़माएँ।',
  'Every niche below has its own generator page, tuned prompts and real examples.': 'नीचे हर विषय के लिए अलग जनरेटर पेज, अनुकूलित निर्देश और असली उदाहरण हैं।',
  'Secure checkout by Stripe · Cancel in one click · Credits refunded automatically if a render fails': 'Stripe से सुरक्षित भुगतान · एक क्लिक में रद्द करें · वीडियो बनना विफल होने पर क्रेडिट अपने आप वापस',
  'Is the video really mine to post?': 'क्या मैं वीडियो अपना मानकर पोस्ट कर सकता/सकती हूँ?',
  'Paid plans unlock the clean, watermark-free MP4 for YouTube, TikTok or Reels.': 'सशुल्क प्लान YouTube, TikTok या Reels के लिए बिना वॉटरमार्क MP4 उपलब्ध कराते हैं।',
  'Do I need any editing skills?': 'क्या एडिटिंग आना ज़रूरी है?',
  'None. You type one idea and the AI writes the script, records the voice, finds the footage and adds captions.': 'नहीं। आप एक विचार लिखते हैं और AI स्क्रिप्ट लिखता है, आवाज़ रिकॉर्ड करता है, दृश्य ढूँढता है और कैप्शन जोड़ता है।',
  'Is there a watermark?': 'क्या वॉटरमार्क होता है?',
  'Paid plans export clean, watermark-free MP4s.': 'सशुल्क प्लान बिना वॉटरमार्क MP4 निर्यात करते हैं।',
  'Can Kineo also generate images and voiceovers?': 'क्या Kineo चित्र और वॉइसओवर भी बना सकता है?',
  'Yes — Kineo includes an AI image studio (6 engines including FLUX, Seedream and Nano Banana Pro, from 1 credit per image) and a voice studio with 4 text-to-speech engines (from 1 credit per 1000 characters). Everything you make lives in your Library.': 'हाँ — Kineo में AI चित्र स्टूडियो है (FLUX, Seedream और Nano Banana Pro सहित 6 इंजन, प्रति चित्र 1 क्रेडिट से) और 4 टेक्स्ट-टू-स्पीच इंजन वाला वॉइस स्टूडियो (प्रति 1000 अक्षर 1 क्रेडिट से)। आपकी सारी रचनाएँ लाइब्रेरी में रहती हैं।',
  'Can I make my videos sharper?': 'क्या मैं वीडियो की स्पष्टता बढ़ा सकता/सकती हूँ?',
  'Every video has a one-click Enhance option powered by Topaz film restoration — it removes compression artifacts, recovers detail and adds fine cinematic grain. 10 credits per video; the Studio plan includes 2 free enhances a month.': 'हर वीडियो में Topaz फ़िल्म रिस्टोरेशन वाला एक-क्लिक Enhance विकल्प है — यह कम्प्रेशन के निशान हटाता है, विवरण सुधारता है और बारीक सिनेमाई ग्रेन जोड़ता है। प्रति वीडियो 10 क्रेडिट; Studio प्लान में महीने के 2 मुफ़्त सुधार शामिल हैं।',
  'Can I use my own script?': 'क्या मैं अपनी स्क्रिप्ट इस्तेमाल कर सकता/सकती हूँ?',
  'Yes — paste your script and pick “Use my script as is” and the AI narrates it word for word.': 'हाँ — अपनी स्क्रिप्ट पेस्ट करें और “मेरी स्क्रिप्ट ज्यों की त्यों रखें” चुनें। AI उसे शब्दशः बोलेगा।',
  'What if a generation fails?': 'वीडियो बनना विफल हो जाए तो?',
  'Your credits come back automatically the moment a render fails — no support ticket, no waiting. You only pay for videos you actually get.': 'वीडियो बनना विफल होते ही आपके क्रेडिट अपने आप वापस आते हैं — सपोर्ट टिकट या प्रतीक्षा नहीं। आप सिर्फ़ मिलने वाले वीडियो के लिए भुगतान करते हैं।',
  'Can I cancel anytime?': 'क्या कभी भी रद्द कर सकता/सकती हूँ?',
  'Anytime, in one click. Plans are month to month and your credits refresh every month.': 'कभी भी, एक क्लिक में। प्लान मासिक हैं और आपके क्रेडिट हर महीने नवीनीकृत होते हैं।',
  'Can I run a whole channel with the same host?': 'क्या पूरे चैनल में वही होस्ट रख सकता/सकती हूँ?',
  'Yes — that’s the point. Keep the same voice, style and captions across every episode so your channel looks consistent, without filming a single frame.': 'हाँ। बिना शूटिंग, हर एपिसोड में वही आवाज़, शैली और कैप्शन रखें ताकि चैनल में निरंतरता दिखे।',
  'Can I monetize the videos?': 'क्या वीडियो से कमाई कर सकता/सकती हूँ?',
  'Yes. Every video is yours to keep, post and monetize — including the YouTube Partner Program, TikTok and Reels. No extra license needed.': 'हाँ। हर वीडियो को रखना, पोस्ट करना और उससे कमाना आपका अधिकार है — YouTube Partner Program, TikTok और Reels सहित। अतिरिक्त लाइसेंस नहीं चाहिए।',
  'Can I use the videos commercially, or for client work?': 'क्या वीडियो का व्यावसायिक या क्लाइंट के काम में उपयोग कर सकता/सकती हूँ?',
  'Yes. Our terms let you use Kineo for lawful personal or commercial purposes and confirm that you keep ownership of the videos you generate, so you can post them, monetize them and deliver them to a client as part of your own paid service. No extra license, no per-video royalty. Two limits come from the same terms: you cannot resell or redistribute Kineo itself, and the stock clips inside a render are licensed for use in your finished video, not for re-upload as standalone stock footage. Paid plans export the clean, watermark-free MP4.': 'हाँ। हमारी शर्तें Kineo का वैध व्यक्तिगत या व्यावसायिक उपयोग करने देती हैं और आपके बनाए वीडियो का स्वामित्व आपके पास रखती हैं। इसलिए आप उन्हें पोस्ट कर सकते हैं, उनसे कमा सकते हैं और अपनी सशुल्क सेवा के तहत क्लाइंट को दे सकते हैं। अतिरिक्त लाइसेंस या प्रति वीडियो रॉयल्टी नहीं। दो सीमाएँ हैं: Kineo को स्वयं दोबारा बेचना या वितरित करना मना है; और वीडियो में इस्तेमाल स्टॉक क्लिप का लाइसेंस तैयार वीडियो के लिए है, उन्हें अलग स्टॉक फ़ुटेज के रूप में दोबारा अपलोड करने के लिए नहीं। सशुल्क प्लान बिना वॉटरमार्क MP4 निर्यात करते हैं।',
  'How long does one video take?': 'एक वीडियो बनने में कितना समय लगता है?',
  'Fast Mode usually finishes in 3–7 minutes. AI-generated and cinematic videos take a little longer because every scene is generated before the final MP4 is composed.': 'Fast Mode आम तौर पर 3–7 मिनट में पूरा होता है। AI और सिनेमाई वीडियो थोड़ा अधिक समय लेते हैं क्योंकि अंतिम MP4 बनाने से पहले हर दृश्य तैयार होता है।',
  'How much does Kineo cost?': 'Kineo की कीमत कितनी है?',
  'Kineo has three monthly plans: Starter at $': 'Kineo के तीन मासिक प्लान हैं: Starter $',
  for: 'में', 'credits, Creator at $': 'क्रेडिट, Creator $', 'credits and Studio at $': 'क्रेडिट और Studio $',
  'credits. Credits are spent per video and how many a video costs depends on the engine you pick, so a Fast render and a cinematic film come out of the same balance at very different rates.': 'क्रेडिट। प्रति वीडियो खर्च चुने हुए इंजन पर निर्भर है, इसलिए Fast और सिनेमाई वीडियो एक ही बैलेंस से अलग-अलग मात्रा में क्रेडिट लेते हैं।',
  'New accounts get free credits to make a first video before paying anything.': 'नए खातों को भुगतान करने से पहले पहला वीडियो बनाने के लिए मुफ़्त क्रेडिट मिलते हैं।',
  'Which AI video engines can I use in Kineo?': 'Kineo में कौन से AI वीडियो इंजन इस्तेमाल कर सकता/सकती हूँ?',
  ', behind one interface and one balance:': ', एक इंटरफ़ेस और एक बैलेंस में:',
  'Omni Flash (Google’s #1-ranked video model, Aug 2026), Veo 3.1, Kling 3, MiniMax H3, Kling 2.5, Seedance 1.5, Kineo 1 and Avatar. You choose the engine per video, so a cheap explainer and a cinematic flagship can come out of the same account on the same day. Every clip on this page is a real render from the engine named on the card — the badge always tells the truth about which model made it.': 'Omni Flash (Google का #1 वीडियो मॉडल, अगस्त 2026), Veo 3.1, Kling 3, MiniMax H3, Kling 2.5, Seedance 1.5, Kineo 1 और Avatar। हर वीडियो के लिए इंजन चुनें — उसी खाते में, उसी दिन किफ़ायती जानकारी वाला वीडियो और सिनेमाई वीडियो बना सकते हैं। इस पेज की हर क्लिप कार्ड पर बताए इंजन का असली परिणाम है — बैज सही मॉडल बताता है।',
  'What is the best AI video generator for faceless YouTube channels?': 'बिना चेहरा दिखाए YouTube चैनल के लिए सबसे अच्छा AI वीडियो जनरेटर कौन सा है?',
  'Yes. Never-paid free users can download, share and post the watermarked MP4.': 'हाँ। जिन मुफ़्त उपयोगकर्ताओं ने कभी भुगतान नहीं किया, वे वॉटरमार्क वाला MP4 डाउनलोड, शेयर और पोस्ट कर सकते हैं।',
  'Trial films carry a small watermark — you can download, share and post the MP4. After the trial, the free Fast video carries a watermark.': 'ट्रायल वीडियो पर छोटा वॉटरमार्क होता है — आप MP4 डाउनलोड, शेयर और पोस्ट कर सकते हैं। ट्रायल के बाद मुफ़्त Fast वीडियो पर भी वॉटरमार्क होता है।',
  'Free downloads carry a watermark; paid plans unlock the clean MP4.': 'मुफ़्त डाउनलोड पर वॉटरमार्क होता है; सशुल्क प्लान बिना वॉटरमार्क MP4 उपलब्ध कराते हैं।',
  'Trial downloads carry a watermark, and so does the free Fast video after the trial, and paid plans always export clean.': 'ट्रायल डाउनलोड और उसके बाद मुफ़्त Fast वीडियो पर वॉटरमार्क होता है। सशुल्क प्लान हमेशा बिना वॉटरमार्क निर्यात करते हैं।',
  'Free access gives new users up to 3 watermarked Fast videos every 24 hours, with no card. You can download and share them.': 'मुफ़्त पहुँच नए उपयोगकर्ताओं को बिना कार्ड हर 24 घंटे में अधिकतम 3 वॉटरमार्क वाले Fast वीडियो देती है। आप उन्हें डाउनलोड और शेयर कर सकते हैं।',
  'Create, download and share up to 3 watermarked Fast videos every 24h, no card.': 'बिना कार्ड हर 24h में अधिकतम 3 वॉटरमार्क वाले Fast वीडियो बनाएँ, डाउनलोड करें और शेयर करें।',
  'Create, watch, download and share up to 3 watermarked Fast videos every 24h — no card.': 'हर 24h में अधिकतम 3 वॉटरमार्क वाले Fast वीडियो बनाएँ, देखें, डाउनलोड और शेयर करें — बिना कार्ड।',
  'create, watch, download and share up to 3 Fast videos every 24h': 'हर 24h में अधिकतम 3 Fast वीडियो बनाएँ, देखें, डाउनलोड और शेयर करें',
  '— no card, watermark included.': '— कार्ड नहीं चाहिए, वॉटरमार्क शामिल है।', '— no card.': '— कार्ड नहीं चाहिए।',
  'AI image generator — 6 engines': 'AI चित्र जनरेटर — 6 इंजन',
  'AI voice generator (text to speech)': 'AI आवाज़ जनरेटर (टेक्स्ट से आवाज़)',
  'AI video upscaler & enhancer': 'AI वीडियो रिज़ॉल्यूशन और गुणवत्ता सुधार',
  'Trending Shorts ideas today': 'आज के ट्रेंडिंग Shorts विचार',
  'AI Avatar video — your face, any script': 'AI अवतार वीडियो — आपका चेहरा, कोई भी स्क्रिप्ट',
  'Kineo facts & numbers (citable)': 'Kineo तथ्य और आँकड़े (उद्धृत करने योग्य)',
  'Free AI Shorts generator': 'मुफ़्त AI Shorts जनरेटर', 'Faceless video generator': 'बिना चेहरा दिखाए वीडियो जनरेटर',
  'YouTube Shorts from a topic': 'विषय से YouTube Shorts', 'Text to video Shorts': 'टेक्स्ट से वीडियो Shorts',
  'ChatGPT script to YouTube Short': 'ChatGPT स्क्रिप्ट से YouTube Short', 'Cheapest AI Shorts maker': 'सबसे किफ़ायती AI Shorts निर्माता',
  'Shorts without filming': 'बिना शूटिंग Shorts', 'Faceless channel ideas (2026)': 'बिना चेहरा दिखाए चैनल के विचार (2026)',
  'Faceless niche picker': 'बिना चेहरा दिखाए चैनल का विषय चुनें', 'Shorts idea widget': 'Shorts विचार विजेट',
  'State of AI Shorts 2026': 'AI Shorts की स्थिति 2026', 'Live case study: our channel on Autopilot': 'लाइव केस स्टडी: Autopilot पर हमारा चैनल',
  'AI Shorts for agencies & client work': 'एजेंसी और क्लाइंट के काम के लिए AI Shorts',
  'Trust Center — privacy, payments & ownership': 'ट्रस्ट सेंटर — गोपनीयता, भुगतान और स्वामित्व',
  'Affiliate program - 30% recurring': 'अफ़िलिएट प्रोग्राम - 40% आवर्ती',
  'Free AI Shorts by niche': 'विषय के अनुसार मुफ़्त AI Shorts', 'Free YouTube Shorts scripts': 'मुफ़्त YouTube Shorts स्क्रिप्ट',
  'Free script generator': 'मुफ़्त स्क्रिप्ट जनरेटर', 'Comment to Short script': 'कमेंट से Short स्क्रिप्ट',
  'Product video ad script': 'प्रोडक्ट वीडियो विज्ञापन स्क्रिप्ट', 'Business video content planner': 'व्यवसाय के वीडियो कंटेंट की योजना',
  'Client video brief generator': 'क्लाइंट वीडियो ब्रीफ़ जनरेटर', 'Real estate video maker': 'रियल एस्टेट वीडियो निर्माता',
  'Free hook generator': 'मुफ़्त हुक जनरेटर', 'Shorts title & hashtag generator': 'Shorts शीर्षक और हैशटैग जनरेटर',
  'Shorts script timer': 'Shorts स्क्रिप्ट का समय', 'Free viral score': 'मुफ़्त वायरल स्कोर',
  'Shorts money calculator': 'Shorts कमाई कैलकुलेटर', 'Make money clipping with AI': 'AI क्लिप बनाकर कमाएँ',
  'How much do Shorts pay?': 'Shorts से कितनी कमाई होती है?', 'Shorts RPM by niche (2026)': 'विषय के अनुसार Shorts RPM (2026)',
  'Best AI Shorts generators': 'सर्वश्रेष्ठ AI Shorts जनरेटर', 'Can you monetize AI videos?': 'क्या AI वीडियो से कमाई कर सकते हैं?',
  'TikTok vs Shorts: which pays more?': 'TikTok बनाम Shorts: किससे अधिक कमाई होती है?',
  'All comparisons': 'सभी तुलनाएँ', 'Vidyo.ai / Quso pricing': 'Vidyo.ai / Quso के प्लान',
  'Turn one idea into a ready-to-post faceless YouTube Short — script, AI voiceover, footage & captions in a few minutes.': 'एक विचार से बिना चेहरा दिखाए, पोस्ट करने योग्य YouTube Short बनाएँ — कुछ मिनटों में स्क्रिप्ट, AI वॉइसओवर, दृश्य और कैप्शन।',
  '© 2026 Kineo · All rights reserved': '© 2026 Kineo · सर्वाधिकार सुरक्षित',
  'It depends on whether you want stock footage assembled or footage generated. Tools like InVideo and AutoShorts cut stock clips to your script, which is cheaper and fine for talking-point videos. Kineo generates the footage with models such as Veo 3.1 and Kling 3, keeps your narration word for word instead of rewriting it, and targets 60 seconds or more so the video qualifies for TikTok Creator Rewards. If your channel lives on visuals nobody else has, generation wins; if it lives on volume, stock is cheaper.': 'यह इस पर निर्भर है कि आपको स्टॉक फ़ुटेज का संयोजन चाहिए या नए दृश्य। InVideo और AutoShorts जैसे टूल स्क्रिप्ट के अनुसार स्टॉक क्लिप काटते हैं; जानकारी वाले वीडियो के लिए यह किफ़ायती विकल्प है। Kineo Veo 3.1 और Kling 3 जैसे मॉडल से दृश्य बनाता है, नैरेशन दोबारा लिखने के बजाय शब्दशः रखता है और 60 सेकंड या अधिक की अवधि लक्ष्य करता है ताकि वीडियो TikTok Creator Rewards के लिए योग्य हो। अनोखे दृश्यों पर आधारित चैनल के लिए जनरेशन बेहतर है; अधिक संख्या में वीडियो के लिए स्टॉक सस्ता है।',
  'Paste the complete script from ChatGPT here…': 'ChatGPT की पूरी स्क्रिप्ट यहाँ पेस्ट करें…',
  'Paste the idea from ChatGPT here…': 'ChatGPT का विचार यहाँ पेस्ट करें…',
  'What’s your video about? One idea in — a finished film out: voiced, scored and captioned.': 'आपका वीडियो किस बारे में है? एक विचार दें — आवाज़, संगीत और कैप्शन के साथ तैयार वीडियो पाएँ।',
  words: 'शब्द', '· narrated word for word': '· शब्दशः नैरेशन',
  'Settings and generation': 'सेटिंग और वीडियो बनाना', film: 'वीडियो', films: 'वीडियो',
  'Search your videos…': 'अपने वीडियो खोजें…', 'Search your images…': 'अपने चित्र खोजें…',
  'Search your audio…': 'अपना ऑडियो खोजें…', 'Search your videos by title': 'शीर्षक से वीडियो खोजें',
  'Search your images by engine': 'इंजन से चित्र खोजें', 'Search your audio by text or voice': 'टेक्स्ट या आवाज़ से ऑडियो खोजें',
  'No playable videos in your library yet. Check your latest project above.': 'लाइब्रेरी में अभी चलाने योग्य वीडियो नहीं हैं। ऊपर अपने हाल के प्रोजेक्ट की स्थिति देखें।',
  'Make a finished Short →': 'पूरा Short बनाएँ →', 'Editing & creator tools': 'एडिटिंग और क्रिएटर टूल',
  'Video Editing & Creator Tools': 'वीडियो एडिटिंग और क्रिएटर टूल',
  'Trim, resize, change speed, mute or add text. Edit a file you already have, right in your browser. Your script and planning tools are still here below.': 'वीडियो काटें, आकार या गति बदलें, आवाज़ हटाएँ या टेक्स्ट जोड़ें। अपनी मौजूदा फ़ाइल ब्राउज़र में संपादित करें। स्क्रिप्ट और योजना के टूल नीचे उपलब्ध हैं।',
  '5 local editing tools': '5 स्थानीय एडिटिंग टूल', 'No video upload': 'वीडियो अपलोड नहीं होता',
  'No generation credits to edit': 'एडिटिंग में जनरेशन क्रेडिट नहीं लगते',
  'Edit video': 'वीडियो संपादित करें', 'Edit your video': 'अपना वीडियो संपादित करें',
  'Files up to 100 MB and 3 minutes. Local, real-time export up to 1280 px on the long edge. MP4 or WebM depending on your browser; downloads are not saved to My Videos.': 'अधिकतम 100 MB और 3 मिनट की फ़ाइलें। लंबे किनारे पर अधिकतम 1280 px में, डिवाइस पर रियल-टाइम निर्यात। ब्राउज़र के अनुसार MP4 या WebM; डाउनलोड मेरे वीडियो में नहीं सहेजे जाते।',
  'Video Trimmer': 'वीडियो काटें', 'Trim video': 'वीडियो काटें',
  'Cut the beginning or end and keep only the clip you need.': 'शुरुआत या अंत काटकर सिर्फ़ ज़रूरी हिस्सा रखें।',
  'Video Resizer': 'वीडियो का आकार बदलें', 'Resize video': 'वीडियो का आकार बदलें',
  'Go vertical, square or wide. Fit the frame or crop to fill.': 'लंबवत, चौकोर या चौड़ा फ़ॉर्मैट चुनें। फ़्रेम में फ़िट करें या भरने के लिए काटें।',
  'Video Speed Changer': 'वीडियो की गति बदलें', 'Change video speed': 'वीडियो की गति बदलें',
  'Slow it down or speed it up, from 0.5× to 2×.': '0.5× से 2× तक धीमा या तेज़ करें।',
  'Remove Audio': 'ऑडियो हटाएँ', 'Remove audio': 'ऑडियो हटाएँ',
  'Download a copy without the original audio.': 'मूल ऑडियो के बिना एक कॉपी डाउनलोड करें।',
  'Add Text to Video': 'वीडियो पर टेक्स्ट जोड़ें', 'Add text to video': 'वीडियो पर टेक्स्ट जोड़ें',
  'Add a title or message that stays on screen. Not automatic subtitles.': 'स्क्रीन पर बना रहने वाला शीर्षक या संदेश जोड़ें। यह अपने आप सबटाइटल नहीं बनाता।',
  'No account · current Kineo plans': 'खाते की ज़रूरत नहीं · मौजूदा Kineo प्लान',
  'No account · fair-use limit': 'खाते की ज़रूरत नहीं · उचित उपयोग सीमा',
  'No account · unlimited in browser': 'खाते की ज़रूरत नहीं · ब्राउज़र में असीमित',
  'Edit an existing video here. Create a new one with Kineo.': 'मौजूदा वीडियो यहाँ संपादित करें। Kineo के साथ नया वीडियो बनाएँ।',
  'When your idea is ready, Kineo can turn it into a finished vertical Short with voice, footage and captions. That next step needs an account; the free trial does not require a card.': 'विचार तैयार होने पर Kineo उसे आवाज़, दृश्यों और कैप्शन वाले पूरे लंबवत Short में बदल सकता है। उस चरण के लिए खाता चाहिए; मुफ़्त ट्रायल में कार्ड नहीं चाहिए।',
  'Create an AI video →': 'AI वीडियो बनाएँ →',
  Primary: 'मुख्य', 'All tools': 'सभी टूल', 'EDITING TOOLS': 'एडिटिंग टूल',
  'Edit your video, preview the changes, then export a copy.': 'वीडियो संपादित करें, बदलावों का प्रीव्यू देखें, फिर एक कॉपी निर्यात करें।',
  'Video preview': 'वीडियो प्रीव्यू', 'Edited video preview': 'संपादित वीडियो का प्रीव्यू',
  Pause: 'रोकें', 'Play preview': 'प्रीव्यू चलाएँ', 'Preview position': 'प्रीव्यू की स्थिति',
  'Preview is silent. The download keeps audio unless Mute is selected.': 'प्रीव्यू में आवाज़ नहीं है। म्यूट चुनने के अलावा, डाउनलोड में ऑडियो रहता है।',
  'Start with your video': 'अपने वीडियो से शुरू करें',
  'Choose a local file. It stays on this device.': 'डिवाइस की फ़ाइल चुनें। वह इसी डिवाइस पर रहती है।',
  'Choose video file': 'वीडियो फ़ाइल चुनें', 'Try a sample clip': 'नमूना क्लिप आज़माएँ',
  'Video file': 'वीडियो फ़ाइल', 'Change video': 'वीडियो बदलें', 'Edit settings': 'एडिटिंग सेटिंग',
  'Video settings': 'वीडियो सेटिंग', 'Start (seconds)': 'शुरुआत (सेकंड)', 'End (seconds)': 'अंत (सेकंड)',
  'Aspect ratio': 'आस्पेक्ट रेशियो', Original: 'मूल', Vertical: 'लंबवत', Square: 'चौकोर', Wide: 'चौड़ा',
  Framing: 'फ़्रेमिंग', 'Fit — add borders': 'फ़िट — बॉर्डर जोड़ें', 'Fill — crop to frame': 'भरें — फ़्रेम के अनुसार काटें',
  'Playback speed': 'प्लेबैक गति', 'Remove audio from export': 'निर्यात से ऑडियो हटाएँ',
  'On-screen text (100 characters, 3 lines)': 'स्क्रीन पर टेक्स्ट (100 अक्षर, 3 पंक्तियाँ)',
  'Add a title or message': 'शीर्षक या संदेश जोड़ें', 'Text position': 'टेक्स्ट की जगह',
  Top: 'ऊपर', Center: 'बीच', Bottom: 'नीचे', 'Checking browser…': 'ब्राउज़र जाँचा जा रहा है…',
  'Export edited video': 'संपादित वीडियो निर्यात करें',
  'Export happens in real time. Keep this tab visible. Re-encoded at up to 1280 px on the long edge; format depends on your browser.': 'निर्यात रियल-टाइम में होता है। यह टैब दिखाई देता रखें। लंबे किनारे पर अधिकतम 1280 px में दोबारा एन्कोड होता है; फ़ॉर्मैट ब्राउज़र पर निर्भर है।',
  'Making a 4-second sample on your device…': 'आपके डिवाइस पर 4-सेकंड का नमूना बन रहा है…',
  'Reading your file…': 'फ़ाइल पढ़ी जा रही है…', Cancel: 'रद्द करें',
  'Export result': 'निर्यात का परिणाम', 'EXPORT READY': 'निर्यात तैयार',
  'Your edited video': 'आपका संपादित वीडियो', 'Download video': 'वीडियो डाउनलोड करें',
  'Local download only. This copy is not saved to My Videos.': 'सिर्फ़ स्थानीय डाउनलोड। यह कॉपी मेरे वीडियो में नहीं सहेजी जाती।',
  'Exported video': 'निर्यात किया गया वीडियो',
  'No upload. No generation credits. Your original is never overwritten.': 'अपलोड नहीं। जनरेशन क्रेडिट नहीं। आपकी मूल फ़ाइल कभी नहीं बदली जाती।',
  'Up to 100 MB · 3 minutes · MP4/WebM input recommended. These are basic editing tools, not the CapCut app.': 'अधिकतम 100 MB · 3 मिनट · MP4/WebM फ़ाइल अनुशंसित। ये बुनियादी एडिटिंग टूल हैं, CapCut ऐप नहीं।',
  'Need a new video? Open Kineo Studio →': 'नया वीडियो चाहिए? Kineo Studio खोलें →',
  'This browser cannot export video here. Try the latest desktop Chrome or Edge.': 'यह ब्राउज़र यहाँ वीडियो निर्यात नहीं कर सकता। नवीनतम डेस्कटॉप Chrome या Edge आज़माएँ।',
  'Choose a non-empty video file of up to 100 MB.': 'अधिकतम 100 MB की ऐसी वीडियो फ़ाइल चुनें जो खाली न हो।',
  'Use a playable clip of up to 3 minutes. Very large dimensions are not supported.': 'अधिकतम 3 मिनट की चलने योग्य क्लिप चुनें। बहुत बड़े आयाम समर्थित नहीं हैं।',
  'Check the start and end: select at least 0.25 seconds within your clip.': 'शुरुआत और अंत जाँचें: क्लिप के भीतर कम से कम 0.25 सेकंड चुनें।',
  'Choose a speed between 0.5× and 2×.': '0.5× और 2× के बीच गति चुनें।',
  'Use up to 100 characters and 3 lines of text.': 'अधिकतम 100 अक्षर और 3 पंक्तियाँ इस्तेमाल करें।',
  'Choose a supported aspect ratio, framing and text position.': 'समर्थित आस्पेक्ट रेशियो, फ़्रेमिंग और टेक्स्ट की जगह चुनें।',
  'This file could not be decoded. Try an MP4 (H.264) or WebM file.': 'फ़ाइल पढ़ी नहीं जा सकी। MP4 (H.264) या WebM फ़ाइल आज़माएँ।',
  'Export stopped because this tab was hidden. Keep it open and visible, then export again. Your original is safe.': 'टैब छिपने से निर्यात रुक गया। इसे खुला और दिखाई देता रखें, फिर दोबारा निर्यात करें। आपकी मूल फ़ाइल सुरक्षित है।',
  'Export stopped making progress. Try a shorter clip or desktop Chrome. Your original is unchanged.': 'निर्यात आगे नहीं बढ़ रहा था। छोटी क्लिप या डेस्कटॉप Chrome आज़माएँ। आपकी मूल फ़ाइल बदली नहीं है।',
  'Audio could not start. Try exporting again, or choose Mute video.': 'ऑडियो शुरू नहीं हो सका। फिर निर्यात करें या वीडियो म्यूट करें।',
  'The browser blocked playback. Try exporting again from this tab.': 'ब्राउज़र ने प्लेबैक रोक दिया। इसी टैब से फिर निर्यात करें।',
  'Cancelled. Your original file is unchanged.': 'रद्द हुआ। आपकी मूल फ़ाइल बदली नहीं है।',
  'Could not finish this export. Try a shorter clip or another supported browser.': 'निर्यात पूरा नहीं हुआ। छोटी क्लिप या दूसरा समर्थित ब्राउज़र आज़माएँ।',
  'The browser produced an incomplete file, so we did not offer it for download. Try again with this tab visible, or use desktop Chrome.': 'ब्राउज़र ने अधूरी फ़ाइल बनाई, इसलिए डाउनलोड उपलब्ध नहीं कराया गया। टैब दिखाई देते हुए फिर कोशिश करें या डेस्कटॉप Chrome इस्तेमाल करें।',
}

/** Only known UI templates; captured numbers and currency are never converted. */
export function canonicalCopyHindi(text: string): string | undefined {
  let m: RegExpMatchArray | null
  if ((m = text.match(/^(\d+) of (\d+) projects$/))) return `${m[1]} / ${m[2]} प्रोजेक्ट`
  if ((m = text.match(/^(\d+) projects · unlimited$/))) return `${m[1]} प्रोजेक्ट · असीमित`
  if ((m = text.match(/^(\d+) Shorts made$/))) return `${m[1]} Shorts बनाए गए`
  if ((m = text.match(/^(\d+) of your first 4 Shorts$/))) return `आपके पहले 4 Shorts में से ${m[1]}`
  if ((m = text.match(/^Generate · (\d+) cr →$/))) return `बनाएँ · ${m[1]} cr →`
  if ((m = text.match(/^Need (\d+) more credits$/))) return `${m[1]} और क्रेडिट चाहिए`
  if ((m = text.match(/^Trim ([\d,]+) characters to continue$/))) return `जारी रखने के लिए ${m[1]} अक्षर कम करें`
  if ((m = text.match(/^(\d+) credits \/ video$/))) return `${m[1]} क्रेडिट / वीडियो`
  if ((m = text.match(/^≈ (\d+) finished films? — (\d+) AI scenes$/))) return `≈ ${m[1]} तैयार वीडियो — ${m[2]} AI दृश्य`
  if ((m = text.match(/^Exporting (\d+)% — keep this tab visible$/))) return `निर्यात ${m[1]}% — यह टैब खुला और दिखाई देता रखें`
  if ((m = text.match(/^Kineo lists and charges plan prices in (USD) worldwide\. Your bank may convert the charge to your local currency and may add conversion or cross-border fees\.$/))) return `Kineo दुनिया भर में प्लान की कीमतें ${m[1]} में दिखाता और वसूलता है। आपका बैंक राशि को स्थानीय मुद्रा में बदल सकता है और मुद्रा परिवर्तन या अंतरराष्ट्रीय लेनदेन शुल्क ले सकता है।`
  return undefined
}
