/** Spanish presentation of the existing tool contracts, not new capabilities. */
export const TOOL_SPANISH: Record<string, { eyebrow: string; prompt: string; cta: string; what: string }> = {
  '/free-script-generator': { eyebrow: 'Empieza con un tema', prompt: 'Generador de guiones de vídeo', cta: 'Escribir mi guion', what: 'Escribe un tema y recibe un guion completo para un Short, con gancho, desarrollo y desenlace, dentro de la página.' },
  '/free-hook-generator': { eyebrow: 'Empieza con un tema', prompt: 'Generador de ganchos', cta: 'Crear cinco ganchos', what: 'Escribe un tema y recibe ganchos de apertura para un Short. Solo texto: no genera un vídeo.' },
  '/comment-to-video': { eyebrow: 'Empieza con tu audiencia', prompt: 'De comentario a guion', cta: 'Crear un guion de respuesta', what: 'Pega un comentario, una pregunta frecuente de un cliente o una objeción de venta para obtener un guion estructurado de respuesta. Solo texto: no genera un vídeo.' },
  '/product-to-video-script': { eyebrow: 'Empieza con hechos verificados', prompt: 'Guiones de vídeo de producto', cta: 'Crear mi guion de producto', what: 'Pega datos verificados del producto y, si quieres, su público para obtener un guion de anuncio sin presentador. No extrae datos de enlaces, inventa afirmaciones ni genera un vídeo.' },
  '/free-ai-shorts/localbusiness': { eyebrow: 'Empieza con una oferta real', prompt: 'Guion de anuncio local', cta: 'Crear mi anuncio', what: 'Añade el nombre del negocio, el servicio, el cliente ideal, un diferenciador verificado y una llamada a la acción para recibir un borrador editable de anuncio de 35 segundos. No inventa afirmaciones, llama a una IA ni genera un vídeo.' },
  '/client-video-brief-generator': { eyebrow: 'Empieza con la petición de un cliente', prompt: 'Brief de vídeo para clientes', cta: 'Crear el brief del cliente', what: 'Convierte la oferta, el público, el objetivo, las pruebas aportadas y la llamada a la acción en un brief de Short sin presentador de 35 segundos, con una lista de aprobación. Funciona en el navegador y no inventa pruebas ni genera un vídeo.' },
  '/business-video-content-plan': { eyebrow: 'Empieza con un objetivo de negocio', prompt: 'Planificador semanal de contenido', cta: 'Planificar mis Shorts', what: 'Elige una oferta, un público, un objetivo y una frecuencia para crear un plan semanal de vídeos cortos. No investiga afirmaciones, programa publicaciones, publica contenido ni genera un vídeo.' },
  '/shorts-money-calculator': { eyebrow: 'Empieza con tus cifras', prompt: 'Calculadora de ingresos de Shorts', cta: 'Calcular ingresos de Shorts', what: 'Estima los ingresos de Shorts a partir de las visualizaciones y el RPM de la temática.' },
  '/cheapest-ai-shorts-maker': { eyebrow: 'Empieza con tu frecuencia de publicación', prompt: 'Calculadora de costes de vídeo', cta: 'Encontrar el plan más económico', what: 'Elige el motor, la duración final del vídeo y la frecuencia mensual para ver los créditos necesarios, el plan actual más económico que los cubre y una alternativa de menor volumen cuando reduce el coste o permite utilizar los planes disponibles. Usa los mismos costes de motores y créditos de los planes que el checkout; no estima ingresos de plataformas ni genera un vídeo.' },
  '/business-pilot-review': { eyebrow: 'Empieza con una decisión interna', prompt: 'Brief de aprobación empresarial', cta: 'Preparar la nota de decisión', what: 'Elige un caso de uso, una frecuencia de publicación y un responsable de revisión para preparar una nota factual y compartir una respuesta de aprobación, cambio o aplazamiento. No recopila datos de la empresa, crea contratos, promete retorno económico ni genera un vídeo.' },
  '/youtube-shorts-title-generator': { eyebrow: 'Empieza con un tema', prompt: 'Generador de títulos y descripciones', cta: 'Crear mi kit de publicación', what: 'Convierte un tema en 10 opciones de título, una descripción editable y hasta 10 hashtags específicos. No sube ni genera un vídeo.' },
  '/youtube-shorts-script-timer': { eyebrow: 'Empieza con un borrador terminado', prompt: 'Calculadora de duración del guion', cta: 'Medir mi narración', what: 'Pega un guion de producción para estimar su duración hablada, ver cuántas palabras faltan para 35 o 60 segundos y excluir del recuento los títulos, las instrucciones visuales y las notas de edición.' },
  '/viral-score': { eyebrow: 'Empieza con una idea', prompt: 'Evaluador de ideas de vídeo', cta: 'Evaluar mi idea', what: 'Pega una idea de Short y recibe una puntuación de 0–100 sobre gancho, retención, tendencia y potencial para compartir, con consejos concretos para mejorarla.' },
}
