// KINEO-ESPACOS-LANCAMENTO-2026-09-30 — textos do /spaces e do vídeo nas 16 línguas da interface
// (lib/ui/interfaceLanguage.ts). Fundador (30/09): "vamos lançar… também colocar em inglês… a pessoa pudesse tirar
// qualquer fala de IA do vídeo". A língua vem do mesmo contexto do resto do site (useInterfaceLanguage); os rótulos do
// vídeo (Antes/Depois, "Apresentado por", "Imagem ilustrativa") saem na língua de quem gera.
// Módulo puro: o guardião confere que as 16 línguas têm TODAS as chaves e os mesmos marcadores {n} {name}.
import type { InterfaceLanguage } from '@/lib/ui/interfaceLanguage'

export const SPACES_COPY_EN = {
  badge: 'New',
  title: 'Spaces',
  sub: 'Photograph an empty space, say what goes inside, and get it finished in photos and in a before → after video — same camera, same structure.',
  s1Title: 'Photos of the empty space',
  s1Hint: 'Up to {n} vertical photos, or a video walking through the space — we take 3 frames from it.',
  addPhotos: '+ Add photos or a video',
  remove: 'Remove photo',
  rights: 'I have permission to use these photos (the space is mine or my client’s).',
  s2Title: 'What goes inside the space',
  s2Hint: 'You can name a brand or a style. Kineo searches the web for how that space really looks and builds the design brief.',
  kind_store: 'Store',
  kind_food: 'Café, bar or restaurant',
  kind_office: 'Office',
  kind_home: 'Apartment or house',
  kind_other: 'Other',
  placeholder: 'E.g.: a Starbucks coffee shop · a Burger King · a japandi-style apartment',
  research: 'Research and build the design brief',
  researching: 'Researching…',
  researchAgain: 'Research again',
  briefLabel: 'Design brief (one detail per line — edit freely)',
  notesLabel: 'Your requests (optional)',
  notesPlaceholder: 'E.g.: counter on the left, more plants, wooden floor',
  s3Title: 'The finished space, photo by photo',
  s3Hint: 'Nano Banana Pro · {n} credits per photo. Drag to compare before and after; redo only the one you don’t like.',
  generatePhotos: 'Create the finished space · {n} credits',
  generatePhotosIdle: 'Create the finished space',
  generating: 'Creating…',
  allDone: 'All created',
  checkRights: 'Tick the photo permission in step 1.',
  waiting: 'Waiting',
  uploading: 'Uploading the photo…',
  staging: 'Building the space…',
  redo: 'Redo this one · {n} credits',
  s4Title: 'The before → after video',
  s4Hint: 'Kling 2.5 · {n} credits per photo.',
  presentedByLabel: 'Presented by (optional)',
  presentedByPlaceholder: 'Your name or your company',
  presentedByHint: 'Only the name of who presents it. Don’t credit another person or brand as the author.',
  sealLabel: 'Add an “Illustrative image” note to the video',
  makeVideo: 'Create the video · {n} credits',
  makeVideoIdle: 'Create the video',
  makingClips: 'Creating the clips (1–3 min)…',
  montage: 'Editing the video… {n}%',
  remake: 'Edit the video again',
  needStaged: 'Create the finished space for every photo first.',
  download: 'Download the video',
  compare: 'Compare before and after',
  emptyAlt: 'Empty space',
  readyAlt: 'Finished space',
  before: 'BEFORE',
  after: 'AFTER',
  presentedBy: 'Presented by {name}',
  seal: 'Illustrative image',
  errCredits: 'Not enough credits for this step.',
  errModeration: 'Moderation declined this photo or request.',
  errLimit: 'Daily limit reached. Try again tomorrow.',
  errGeneric: 'That didn’t work. Try again.',
  errFile: 'Couldn’t read one of the files. Use JPG, PNG, WEBP or an MP4/MOV video.',
  errNoBrief: 'The research found no reliable details. Write how the space should look yourself, or create it from the description only.',
  errClip: 'The clip failed (credits refunded). Try again.',
  errClipSlow: 'The clip is taking long. It will show up in your Library; try editing the video again later.',
  errSomeClips: 'A clip isn’t ready. Fix the flagged photo and edit the video again.',
  errMontage: 'Editing the video failed. Try again.',
  errMontageSlow: 'Editing is taking long. Try again in a few minutes.',
  // KINEO-NUVEM-A5-2026-10-02 — "vários destinos" (um espaço, vários negócios)
  multiLink: 'One space, several businesses →',
  multiTitle: 'One space, several businesses',
  multiSub: 'Show the same empty space as 2 to 4 different businesses in one before → after video, each one named on screen.',
  multiS1Hint: 'One vertical photo of the empty space, or a video — we take one frame from it.',
  multiS2Title: 'Which businesses could it be?',
  multiS2Hint: 'Two to {n}. Give each one a short name for the video and say what goes inside.',
  destLabelPlaceholder: 'Name on the video (e.g. Café)',
  addDestination: '+ Add a business',
  multiTotal: '{n} credits in total — a finished photo and a clip for each business',
  backToSingle: '← Back to one business per photo',
}
export type SpacesCopyKey = keyof typeof SPACES_COPY_EN
type Dict = Record<SpacesCopyKey, string>

export const SPACES_COPY: Record<Exclude<InterfaceLanguage, 'en'>, Dict> = {
  pt: {
    badge: 'Novo',
    title: 'Espaços',
    sub: 'Fotografe um espaço vazio, diga o que vai dentro dele e receba o espaço pronto em fotos e em vídeo antes → depois — mesma câmera, mesma estrutura.',
    s1Title: 'Fotos do espaço vazio',
    s1Hint: 'Até {n} fotos em pé (vertical), ou um vídeo andando pelo espaço — tiramos 3 quadros dele.',
    addPhotos: '+ Adicionar fotos ou vídeo',
    remove: 'Remover foto',
    rights: 'Tenho autorização para usar estas fotos (o espaço é meu ou do meu cliente).',
    s2Title: 'O que vai dentro do espaço',
    s2Hint: 'Pode citar uma marca ou um estilo. A Kineo pesquisa na web como esse espaço é de verdade e monta a curadoria.',
    kind_store: 'Loja',
    kind_food: 'Café, bar ou restaurante',
    kind_office: 'Escritório',
    kind_home: 'Apartamento ou casa',
    kind_other: 'Outro',
    placeholder: 'Ex.: uma cafeteria Starbucks · uma loja Burger King · apartamento em estilo japandi',
    research: 'Pesquisar e montar a curadoria',
    researching: 'Pesquisando…',
    researchAgain: 'Pesquisar de novo',
    briefLabel: 'Curadoria (um detalhe por linha — edite à vontade)',
    notesLabel: 'Pedidos seus (opcional)',
    notesPlaceholder: 'Ex.: balcão à esquerda, mais plantas, piso de madeira',
    s3Title: 'O espaço pronto, foto a foto',
    s3Hint: 'Nano Banana Pro · {n} créditos por foto. Arraste para comparar antes e depois; refaça só a que não gostar.',
    generatePhotos: 'Gerar o espaço pronto · {n} créditos',
    generatePhotosIdle: 'Gerar o espaço pronto',
    generating: 'Gerando…',
    allDone: 'Tudo gerado',
    checkRights: 'Marque a autorização das fotos no passo 1.',
    waiting: 'Aguardando',
    uploading: 'Enviando a foto…',
    staging: 'Montando o espaço…',
    redo: 'Refazer esta · {n} créditos',
    s4Title: 'O vídeo antes → depois',
    s4Hint: 'Kling 2.5 · {n} créditos por foto.',
    presentedByLabel: 'Apresentado por (opcional)',
    presentedByPlaceholder: 'Seu nome ou da sua empresa',
    presentedByHint: 'Só o nome de quem apresenta. Não use outra pessoa ou marca como autora.',
    sealLabel: 'Colocar a nota “Imagem ilustrativa” no vídeo',
    makeVideo: 'Gerar o vídeo · {n} créditos',
    makeVideoIdle: 'Gerar o vídeo',
    makingClips: 'Gerando os clipes (1–3 min)…',
    montage: 'Montando o vídeo… {n}%',
    remake: 'Montar o vídeo de novo',
    needStaged: 'Gere o espaço pronto de todas as fotos primeiro.',
    download: 'Baixar o vídeo',
    compare: 'Comparar antes e depois',
    emptyAlt: 'Espaço vazio',
    readyAlt: 'Espaço pronto',
    before: 'ANTES',
    after: 'DEPOIS',
    presentedBy: 'Apresentado por {name}',
    seal: 'Imagem ilustrativa',
    errCredits: 'Créditos insuficientes para esta etapa.',
    errModeration: 'A moderação recusou esta foto ou este pedido.',
    errLimit: 'Limite diário atingido. Tente amanhã.',
    errGeneric: 'Não deu certo. Tente de novo.',
    errFile: 'Não consegui ler um dos arquivos. Use JPG, PNG, WEBP ou um vídeo MP4/MOV.',
    errNoBrief: 'A pesquisa não achou detalhes confiáveis. Escreva você mesmo como o espaço deve ficar, ou gere só com a descrição.',
    errClip: 'O clipe falhou (crédito devolvido). Tente de novo.',
    errClipSlow: 'O clipe está demorando. Ele vai aparecer na Biblioteca; tente montar de novo depois.',
    errSomeClips: 'Algum clipe não ficou pronto. Corrija a foto marcada e monte de novo.',
    errMontage: 'A montagem falhou. Tente de novo.',
    errMontageSlow: 'A montagem está demorando. Tente de novo em alguns minutos.',
    multiLink: 'Um espaço, vários negócios →',
    multiTitle: 'Um espaço, vários negócios',
    multiSub: 'Mostre o mesmo espaço vazio como 2 a 4 negócios diferentes num só vídeo antes → depois, cada um com o nome na tela.',
    multiS1Hint: 'Uma foto vertical do espaço vazio, ou um vídeo — tiramos um quadro dele.',
    multiS2Title: 'Que negócios ele pode virar?',
    multiS2Hint: 'De dois a {n}. Dê a cada um um nome curto para o vídeo e diga o que vai dentro.',
    destLabelPlaceholder: 'Nome no vídeo (ex.: Café)',
    addDestination: '+ Adicionar negócio',
    multiTotal: '{n} créditos no total — uma foto pronta e um clipe para cada negócio',
    backToSingle: '← Voltar para um negócio por foto',
  },
  es: {
    badge: 'Nuevo',
    title: 'Espacios',
    sub: 'Fotografía un espacio vacío, di qué va dentro y recíbelo terminado en fotos y en un video antes → después — misma cámara, misma estructura.',
    s1Title: 'Fotos del espacio vacío',
    s1Hint: 'Hasta {n} fotos verticales, o un video recorriendo el espacio — tomamos 3 cuadros de él.',
    addPhotos: '+ Añadir fotos o un video',
    remove: 'Quitar foto',
    rights: 'Tengo permiso para usar estas fotos (el espacio es mío o de mi cliente).',
    s2Title: 'Qué va dentro del espacio',
    s2Hint: 'Puedes nombrar una marca o un estilo. Kineo busca en la web cómo es ese espacio de verdad y arma la curaduría.',
    kind_store: 'Tienda',
    kind_food: 'Café, bar o restaurante',
    kind_office: 'Oficina',
    kind_home: 'Apartamento o casa',
    kind_other: 'Otro',
    placeholder: 'Ej.: una cafetería Starbucks · un Burger King · un apartamento estilo japandi',
    research: 'Investigar y armar la curaduría',
    researching: 'Investigando…',
    researchAgain: 'Investigar de nuevo',
    briefLabel: 'Curaduría (un detalle por línea — edítala libremente)',
    notesLabel: 'Tus pedidos (opcional)',
    notesPlaceholder: 'Ej.: mostrador a la izquierda, más plantas, piso de madera',
    s3Title: 'El espacio terminado, foto por foto',
    s3Hint: 'Nano Banana Pro · {n} créditos por foto. Arrastra para comparar antes y después; rehaz solo la que no te guste.',
    generatePhotos: 'Crear el espacio terminado · {n} créditos',
    generatePhotosIdle: 'Crear el espacio terminado',
    generating: 'Creando…',
    allDone: 'Todo creado',
    checkRights: 'Marca el permiso de las fotos en el paso 1.',
    waiting: 'En espera',
    uploading: 'Subiendo la foto…',
    staging: 'Armando el espacio…',
    redo: 'Rehacer esta · {n} créditos',
    s4Title: 'El video antes → después',
    s4Hint: 'Kling 2.5 · {n} créditos por foto.',
    presentedByLabel: 'Presentado por (opcional)',
    presentedByPlaceholder: 'Tu nombre o el de tu empresa',
    presentedByHint: 'Solo el nombre de quien lo presenta. No pongas a otra persona o marca como autora.',
    sealLabel: 'Añadir la nota “Imagen ilustrativa” al video',
    makeVideo: 'Crear el video · {n} créditos',
    makeVideoIdle: 'Crear el video',
    makingClips: 'Creando los clips (1–3 min)…',
    montage: 'Editando el video… {n}%',
    remake: 'Editar el video de nuevo',
    needStaged: 'Primero crea el espacio terminado de todas las fotos.',
    download: 'Descargar el video',
    compare: 'Comparar antes y después',
    emptyAlt: 'Espacio vacío',
    readyAlt: 'Espacio terminado',
    before: 'ANTES',
    after: 'DESPUÉS',
    presentedBy: 'Presentado por {name}',
    seal: 'Imagen ilustrativa',
    errCredits: 'No tienes créditos suficientes para este paso.',
    errModeration: 'La moderación rechazó esta foto o este pedido.',
    errLimit: 'Límite diario alcanzado. Inténtalo mañana.',
    errGeneric: 'No funcionó. Inténtalo de nuevo.',
    errFile: 'No pude leer uno de los archivos. Usa JPG, PNG, WEBP o un video MP4/MOV.',
    errNoBrief: 'La búsqueda no encontró detalles confiables. Escribe tú cómo debe verse el espacio, o créalo solo con la descripción.',
    errClip: 'El clip falló (créditos devueltos). Inténtalo de nuevo.',
    errClipSlow: 'El clip está tardando. Aparecerá en tu Biblioteca; intenta editar el video más tarde.',
    errSomeClips: 'Un clip no está listo. Corrige la foto marcada y edita el video de nuevo.',
    errMontage: 'La edición del video falló. Inténtalo de nuevo.',
    errMontageSlow: 'La edición está tardando. Inténtalo en unos minutos.',
    multiLink: 'Un espacio, varios negocios →',
    multiTitle: 'Un espacio, varios negocios',
    multiSub: 'Muestra el mismo espacio vacío como 2 a 4 negocios distintos en un solo video antes → después, cada uno con su nombre en pantalla.',
    multiS1Hint: 'Una foto vertical del espacio vacío, o un video: tomamos un cuadro.',
    multiS2Title: '¿Qué negocios podría ser?',
    multiS2Hint: 'De dos a {n}. Ponle a cada uno un nombre corto para el video y di qué va dentro.',
    destLabelPlaceholder: 'Nombre en el video (ej.: Café)',
    addDestination: '+ Añadir negocio',
    multiTotal: '{n} créditos en total: una foto lista y un clip por cada negocio',
    backToSingle: '← Volver a un negocio por foto',
  },
  fr: {
    badge: 'Nouveau',
    title: 'Espaces',
    sub: 'Photographiez un espace vide, dites ce qui va dedans et recevez-le terminé en photos et en vidéo avant → après — même caméra, même structure.',
    s1Title: 'Photos de l’espace vide',
    s1Hint: 'Jusqu’à {n} photos verticales, ou une vidéo qui parcourt l’espace — nous en tirons 3 images.',
    addPhotos: '+ Ajouter des photos ou une vidéo',
    remove: 'Retirer la photo',
    rights: 'J’ai l’autorisation d’utiliser ces photos (l’espace est à moi ou à mon client).',
    s2Title: 'Ce qui va dans l’espace',
    s2Hint: 'Vous pouvez citer une marque ou un style. Kineo cherche sur le web à quoi ressemble vraiment cet espace et prépare le brief.',
    kind_store: 'Boutique',
    kind_food: 'Café, bar ou restaurant',
    kind_office: 'Bureau',
    kind_home: 'Appartement ou maison',
    kind_other: 'Autre',
    placeholder: 'Ex. : un café Starbucks · un Burger King · un appartement style japandi',
    research: 'Rechercher et préparer le brief',
    researching: 'Recherche…',
    researchAgain: 'Rechercher à nouveau',
    briefLabel: 'Brief déco (un détail par ligne — modifiez librement)',
    notesLabel: 'Vos demandes (facultatif)',
    notesPlaceholder: 'Ex. : comptoir à gauche, plus de plantes, parquet',
    s3Title: 'L’espace terminé, photo par photo',
    s3Hint: 'Nano Banana Pro · {n} crédits par photo. Glissez pour comparer avant et après ; refaites seulement celle qui ne vous plaît pas.',
    generatePhotos: 'Créer l’espace terminé · {n} crédits',
    generatePhotosIdle: 'Créer l’espace terminé',
    generating: 'Création…',
    allDone: 'Tout est créé',
    checkRights: 'Cochez l’autorisation des photos à l’étape 1.',
    waiting: 'En attente',
    uploading: 'Envoi de la photo…',
    staging: 'Aménagement de l’espace…',
    redo: 'Refaire celle-ci · {n} crédits',
    s4Title: 'La vidéo avant → après',
    s4Hint: 'Kling 2.5 · {n} crédits par photo.',
    presentedByLabel: 'Présenté par (facultatif)',
    presentedByPlaceholder: 'Votre nom ou celui de votre entreprise',
    presentedByHint: 'Seulement le nom de qui présente. Ne citez pas une autre personne ou une marque comme auteur.',
    sealLabel: 'Ajouter la mention « Image d’illustration » à la vidéo',
    makeVideo: 'Créer la vidéo · {n} crédits',
    makeVideoIdle: 'Créer la vidéo',
    makingClips: 'Création des clips (1–3 min)…',
    montage: 'Montage de la vidéo… {n}%',
    remake: 'Refaire le montage',
    needStaged: 'Créez d’abord l’espace terminé pour chaque photo.',
    download: 'Télécharger la vidéo',
    compare: 'Comparer avant et après',
    emptyAlt: 'Espace vide',
    readyAlt: 'Espace terminé',
    before: 'AVANT',
    after: 'APRÈS',
    presentedBy: 'Présenté par {name}',
    seal: 'Image d’illustration',
    errCredits: 'Crédits insuffisants pour cette étape.',
    errModeration: 'La modération a refusé cette photo ou cette demande.',
    errLimit: 'Limite quotidienne atteinte. Réessayez demain.',
    errGeneric: 'Ça n’a pas marché. Réessayez.',
    errFile: 'Impossible de lire un des fichiers. Utilisez JPG, PNG, WEBP ou une vidéo MP4/MOV.',
    errNoBrief: 'La recherche n’a trouvé aucun détail fiable. Décrivez vous-même l’espace, ou créez-le avec la description seule.',
    errClip: 'Le clip a échoué (crédits remboursés). Réessayez.',
    errClipSlow: 'Le clip prend du temps. Il apparaîtra dans votre Bibliothèque ; relancez le montage plus tard.',
    errSomeClips: 'Un clip n’est pas prêt. Corrigez la photo signalée et relancez le montage.',
    errMontage: 'Le montage a échoué. Réessayez.',
    errMontageSlow: 'Le montage prend du temps. Réessayez dans quelques minutes.',
    multiLink: 'Un espace, plusieurs commerces →',
    multiTitle: 'Un espace, plusieurs commerces',
    multiSub: 'Montrez le même espace vide sous 2 à 4 commerces différents dans une seule vidéo avant → après, chacun nommé à l’écran.',
    multiS1Hint: 'Une photo verticale de l’espace vide, ou une vidéo — nous en tirons une image.',
    multiS2Title: 'Quels commerces pourrait-il accueillir ?',
    multiS2Hint: 'De deux à {n}. Donnez à chacun un nom court pour la vidéo et dites ce qu’il y a dedans.',
    destLabelPlaceholder: 'Nom dans la vidéo (ex. : Café)',
    addDestination: '+ Ajouter un commerce',
    multiTotal: '{n} crédits au total — une photo finie et un clip par commerce',
    backToSingle: '← Revenir à un commerce par photo',
  },
  de: {
    badge: 'Neu',
    title: 'Räume',
    sub: 'Fotografiere einen leeren Raum, sag, was hinein soll, und erhalte ihn fertig als Fotos und als Vorher → Nachher-Video — gleiche Kamera, gleiche Struktur.',
    s1Title: 'Fotos des leeren Raums',
    s1Hint: 'Bis zu {n} Hochformat-Fotos oder ein Video durch den Raum — wir nehmen 3 Bilder daraus.',
    addPhotos: '+ Fotos oder ein Video hinzufügen',
    remove: 'Foto entfernen',
    rights: 'Ich darf diese Fotos verwenden (der Raum gehört mir oder meinem Kunden).',
    s2Title: 'Was in den Raum kommt',
    s2Hint: 'Du kannst eine Marke oder einen Stil nennen. Kineo recherchiert im Web, wie dieser Raum wirklich aussieht, und erstellt das Design-Briefing.',
    kind_store: 'Laden',
    kind_food: 'Café, Bar oder Restaurant',
    kind_office: 'Büro',
    kind_home: 'Wohnung oder Haus',
    kind_other: 'Anderes',
    placeholder: 'Z. B.: ein Starbucks-Café · ein Burger King · eine Wohnung im Japandi-Stil',
    research: 'Recherchieren und Briefing erstellen',
    researching: 'Recherche läuft…',
    researchAgain: 'Erneut recherchieren',
    briefLabel: 'Design-Briefing (ein Detail pro Zeile — frei bearbeitbar)',
    notesLabel: 'Deine Wünsche (optional)',
    notesPlaceholder: 'Z. B.: Theke links, mehr Pflanzen, Holzboden',
    s3Title: 'Der fertige Raum, Foto für Foto',
    s3Hint: 'Nano Banana Pro · {n} Credits pro Foto. Ziehen zum Vergleichen; nur das neu machen, das dir nicht gefällt.',
    generatePhotos: 'Fertigen Raum erstellen · {n} Credits',
    generatePhotosIdle: 'Fertigen Raum erstellen',
    generating: 'Wird erstellt…',
    allDone: 'Alles erstellt',
    checkRights: 'Bestätige in Schritt 1 die Erlaubnis für die Fotos.',
    waiting: 'Wartet',
    uploading: 'Foto wird hochgeladen…',
    staging: 'Raum wird eingerichtet…',
    redo: 'Dieses neu machen · {n} Credits',
    s4Title: 'Das Vorher → Nachher-Video',
    s4Hint: 'Kling 2.5 · {n} Credits pro Foto.',
    presentedByLabel: 'Präsentiert von (optional)',
    presentedByPlaceholder: 'Dein Name oder deine Firma',
    presentedByHint: 'Nur der Name dessen, der präsentiert. Keine andere Person oder Marke als Urheber angeben.',
    sealLabel: 'Hinweis „Illustrative Darstellung“ ins Video setzen',
    makeVideo: 'Video erstellen · {n} Credits',
    makeVideoIdle: 'Video erstellen',
    makingClips: 'Clips werden erstellt (1–3 Min.)…',
    montage: 'Video wird geschnitten… {n}%',
    remake: 'Video neu schneiden',
    needStaged: 'Erstelle zuerst für jedes Foto den fertigen Raum.',
    download: 'Video herunterladen',
    compare: 'Vorher und nachher vergleichen',
    emptyAlt: 'Leerer Raum',
    readyAlt: 'Fertiger Raum',
    before: 'VORHER',
    after: 'NACHHER',
    presentedBy: 'Präsentiert von {name}',
    seal: 'Illustrative Darstellung',
    errCredits: 'Nicht genug Credits für diesen Schritt.',
    errModeration: 'Die Moderation hat dieses Foto oder diese Anfrage abgelehnt.',
    errLimit: 'Tageslimit erreicht. Versuch es morgen erneut.',
    errGeneric: 'Das hat nicht geklappt. Versuch es erneut.',
    errFile: 'Eine Datei konnte nicht gelesen werden. Nutze JPG, PNG, WEBP oder ein MP4/MOV-Video.',
    errNoBrief: 'Die Recherche fand keine verlässlichen Details. Beschreibe den Raum selbst oder erstelle ihn nur mit der Beschreibung.',
    errClip: 'Der Clip ist fehlgeschlagen (Credits erstattet). Versuch es erneut.',
    errClipSlow: 'Der Clip dauert. Er erscheint in deiner Bibliothek; schneide das Video später neu.',
    errSomeClips: 'Ein Clip ist nicht fertig. Korrigiere das markierte Foto und schneide erneut.',
    errMontage: 'Der Videoschnitt ist fehlgeschlagen. Versuch es erneut.',
    errMontageSlow: 'Der Schnitt dauert. Versuch es in ein paar Minuten erneut.',
    multiLink: 'Ein Raum, mehrere Geschäfte →',
    multiTitle: 'Ein Raum, mehrere Geschäfte',
    multiSub: 'Zeige denselben leeren Raum als 2 bis 4 verschiedene Geschäfte in einem Vorher → Nachher-Video, jedes mit Namen im Bild.',
    multiS1Hint: 'Ein Hochformatfoto des leeren Raums oder ein Video — wir nehmen ein Bild daraus.',
    multiS2Title: 'Welche Geschäfte könnten es sein?',
    multiS2Hint: 'Zwei bis {n}. Gib jedem einen kurzen Namen fürs Video und beschreibe, was hineinkommt.',
    destLabelPlaceholder: 'Name im Video (z. B. Café)',
    addDestination: '+ Geschäft hinzufügen',
    multiTotal: '{n} Credits insgesamt — ein fertiges Foto und ein Clip pro Geschäft',
    backToSingle: '← Zurück zu einem Geschäft pro Foto',
  },
  it: {
    badge: 'Nuovo',
    title: 'Spazi',
    sub: 'Fotografa uno spazio vuoto, di’ cosa va dentro e ricevilo finito in foto e in un video prima → dopo — stessa inquadratura, stessa struttura.',
    s1Title: 'Foto dello spazio vuoto',
    s1Hint: 'Fino a {n} foto verticali, o un video che attraversa lo spazio — ne prendiamo 3 fotogrammi.',
    addPhotos: '+ Aggiungi foto o un video',
    remove: 'Rimuovi foto',
    rights: 'Ho il permesso di usare queste foto (lo spazio è mio o del mio cliente).',
    s2Title: 'Cosa va dentro lo spazio',
    s2Hint: 'Puoi citare un marchio o uno stile. Kineo cerca sul web com’è davvero quello spazio e prepara il brief.',
    kind_store: 'Negozio',
    kind_food: 'Caffè, bar o ristorante',
    kind_office: 'Ufficio',
    kind_home: 'Appartamento o casa',
    kind_other: 'Altro',
    placeholder: 'Es.: una caffetteria Starbucks · un Burger King · un appartamento stile japandi',
    research: 'Cerca e prepara il brief',
    researching: 'Ricerca in corso…',
    researchAgain: 'Cerca di nuovo',
    briefLabel: 'Brief di design (un dettaglio per riga — modificalo liberamente)',
    notesLabel: 'Le tue richieste (facoltativo)',
    notesPlaceholder: 'Es.: bancone a sinistra, più piante, pavimento in legno',
    s3Title: 'Lo spazio finito, foto per foto',
    s3Hint: 'Nano Banana Pro · {n} crediti per foto. Trascina per confrontare prima e dopo; rifai solo quella che non ti piace.',
    generatePhotos: 'Crea lo spazio finito · {n} crediti',
    generatePhotosIdle: 'Crea lo spazio finito',
    generating: 'Creazione…',
    allDone: 'Tutto creato',
    checkRights: 'Spunta il permesso delle foto al passo 1.',
    waiting: 'In attesa',
    uploading: 'Caricamento della foto…',
    staging: 'Allestimento dello spazio…',
    redo: 'Rifai questa · {n} crediti',
    s4Title: 'Il video prima → dopo',
    s4Hint: 'Kling 2.5 · {n} crediti per foto.',
    presentedByLabel: 'Presentato da (facoltativo)',
    presentedByPlaceholder: 'Il tuo nome o quello della tua azienda',
    presentedByHint: 'Solo il nome di chi presenta. Non indicare un’altra persona o un marchio come autore.',
    sealLabel: 'Aggiungi la nota “Immagine illustrativa” al video',
    makeVideo: 'Crea il video · {n} crediti',
    makeVideoIdle: 'Crea il video',
    makingClips: 'Creazione delle clip (1–3 min)…',
    montage: 'Montaggio del video… {n}%',
    remake: 'Rifai il montaggio',
    needStaged: 'Crea prima lo spazio finito per ogni foto.',
    download: 'Scarica il video',
    compare: 'Confronta prima e dopo',
    emptyAlt: 'Spazio vuoto',
    readyAlt: 'Spazio finito',
    before: 'PRIMA',
    after: 'DOPO',
    presentedBy: 'Presentato da {name}',
    seal: 'Immagine illustrativa',
    errCredits: 'Crediti insufficienti per questo passaggio.',
    errModeration: 'La moderazione ha rifiutato questa foto o richiesta.',
    errLimit: 'Limite giornaliero raggiunto. Riprova domani.',
    errGeneric: 'Non ha funzionato. Riprova.',
    errFile: 'Impossibile leggere uno dei file. Usa JPG, PNG, WEBP o un video MP4/MOV.',
    errNoBrief: 'La ricerca non ha trovato dettagli affidabili. Descrivi tu lo spazio, o crealo solo con la descrizione.',
    errClip: 'La clip non è riuscita (crediti rimborsati). Riprova.',
    errClipSlow: 'La clip richiede tempo. Comparirà nella Libreria; rifai il montaggio più tardi.',
    errSomeClips: 'Una clip non è pronta. Correggi la foto segnalata e rifai il montaggio.',
    errMontage: 'Il montaggio non è riuscito. Riprova.',
    errMontageSlow: 'Il montaggio richiede tempo. Riprova tra qualche minuto.',
    multiLink: 'Uno spazio, più attività →',
    multiTitle: 'Uno spazio, più attività',
    multiSub: 'Mostra lo stesso spazio vuoto come 2–4 attività diverse in un unico video prima → dopo, ognuna con il nome a schermo.',
    multiS1Hint: 'Una foto verticale dello spazio vuoto, o un video — ne prendiamo un fotogramma.',
    multiS2Title: 'Che attività potrebbe diventare?',
    multiS2Hint: 'Da due a {n}. Dai a ciascuna un nome breve per il video e descrivi cosa c’è dentro.',
    destLabelPlaceholder: 'Nome nel video (es.: Café)',
    addDestination: '+ Aggiungi attività',
    multiTotal: '{n} crediti in totale — una foto finita e una clip per ogni attività',
    backToSingle: '← Torna a un’attività per foto',
  },
  nl: {
    badge: 'Nieuw',
    title: 'Ruimtes',
    sub: 'Fotografeer een lege ruimte, zeg wat erin komt en krijg hem af in foto’s en in een voor → na-video — zelfde camera, zelfde structuur.',
    s1Title: 'Foto’s van de lege ruimte',
    s1Hint: 'Tot {n} staande foto’s, of een video door de ruimte — we halen er 3 beelden uit.',
    addPhotos: '+ Foto’s of een video toevoegen',
    remove: 'Foto verwijderen',
    rights: 'Ik mag deze foto’s gebruiken (de ruimte is van mij of van mijn klant).',
    s2Title: 'Wat er in de ruimte komt',
    s2Hint: 'Je kunt een merk of een stijl noemen. Kineo zoekt op het web hoe die ruimte er echt uitziet en maakt de ontwerpbrief.',
    kind_store: 'Winkel',
    kind_food: 'Café, bar of restaurant',
    kind_office: 'Kantoor',
    kind_home: 'Appartement of huis',
    kind_other: 'Anders',
    placeholder: 'Bijv.: een Starbucks-koffiezaak · een Burger King · een appartement in japandi-stijl',
    research: 'Onderzoeken en ontwerpbrief maken',
    researching: 'Bezig met zoeken…',
    researchAgain: 'Opnieuw zoeken',
    briefLabel: 'Ontwerpbrief (één detail per regel — vrij aan te passen)',
    notesLabel: 'Jouw wensen (optioneel)',
    notesPlaceholder: 'Bijv.: toonbank links, meer planten, houten vloer',
    s3Title: 'De afgewerkte ruimte, foto voor foto',
    s3Hint: 'Nano Banana Pro · {n} credits per foto. Sleep om voor en na te vergelijken; maak alleen opnieuw wat je niet bevalt.',
    generatePhotos: 'Afgewerkte ruimte maken · {n} credits',
    generatePhotosIdle: 'Afgewerkte ruimte maken',
    generating: 'Bezig…',
    allDone: 'Alles gemaakt',
    checkRights: 'Vink in stap 1 de toestemming voor de foto’s aan.',
    waiting: 'Wacht',
    uploading: 'Foto uploaden…',
    staging: 'Ruimte inrichten…',
    redo: 'Deze opnieuw · {n} credits',
    s4Title: 'De voor → na-video',
    s4Hint: 'Kling 2.5 · {n} credits per foto.',
    presentedByLabel: 'Gepresenteerd door (optioneel)',
    presentedByPlaceholder: 'Je naam of je bedrijf',
    presentedByHint: 'Alleen de naam van wie presenteert. Vermeld geen andere persoon of merk als maker.',
    sealLabel: 'Voeg de vermelding “Illustratieve afbeelding” toe aan de video',
    makeVideo: 'Video maken · {n} credits',
    makeVideoIdle: 'Video maken',
    makingClips: 'Clips maken (1–3 min)…',
    montage: 'Video monteren… {n}%',
    remake: 'Video opnieuw monteren',
    needStaged: 'Maak eerst de afgewerkte ruimte voor elke foto.',
    download: 'Video downloaden',
    compare: 'Voor en na vergelijken',
    emptyAlt: 'Lege ruimte',
    readyAlt: 'Afgewerkte ruimte',
    before: 'VOOR',
    after: 'NA',
    presentedBy: 'Gepresenteerd door {name}',
    seal: 'Illustratieve afbeelding',
    errCredits: 'Niet genoeg credits voor deze stap.',
    errModeration: 'De moderatie heeft deze foto of dit verzoek geweigerd.',
    errLimit: 'Daglimiet bereikt. Probeer het morgen opnieuw.',
    errGeneric: 'Dat lukte niet. Probeer het opnieuw.',
    errFile: 'Een bestand kon niet worden gelezen. Gebruik JPG, PNG, WEBP of een MP4/MOV-video.',
    errNoBrief: 'Het onderzoek vond geen betrouwbare details. Beschrijf de ruimte zelf, of maak hem alleen met de beschrijving.',
    errClip: 'De clip is mislukt (credits terug). Probeer het opnieuw.',
    errClipSlow: 'De clip duurt lang. Hij verschijnt in je Bibliotheek; monteer de video later opnieuw.',
    errSomeClips: 'Een clip is niet klaar. Herstel de gemarkeerde foto en monteer opnieuw.',
    errMontage: 'Het monteren is mislukt. Probeer het opnieuw.',
    errMontageSlow: 'Het monteren duurt lang. Probeer het over een paar minuten opnieuw.',
    multiLink: 'Eén ruimte, meerdere zaken →',
    multiTitle: 'Eén ruimte, meerdere zaken',
    multiSub: 'Laat dezelfde lege ruimte zien als 2 tot 4 verschillende zaken in één voor → na-video, elk met de naam in beeld.',
    multiS1Hint: 'Eén staande foto van de lege ruimte, of een video — wij halen er één beeld uit.',
    multiS2Title: 'Welke zaken zou het kunnen worden?',
    multiS2Hint: 'Twee tot {n}. Geef elk een korte naam voor de video en zeg wat erin komt.',
    destLabelPlaceholder: 'Naam in de video (bijv. Café)',
    addDestination: '+ Zaak toevoegen',
    multiTotal: '{n} credits in totaal — een afgewerkte foto en een clip per zaak',
    backToSingle: '← Terug naar één zaak per foto',
  },
  pl: {
    badge: 'Nowość',
    title: 'Przestrzenie',
    sub: 'Sfotografuj pustą przestrzeń, powiedz, co ma się w niej znaleźć, i otrzymaj ją gotową na zdjęciach i w filmie przed → po — ta sama kamera, ta sama konstrukcja.',
    s1Title: 'Zdjęcia pustej przestrzeni',
    s1Hint: 'Do {n} pionowych zdjęć albo film z przejścia przez przestrzeń — weźmiemy z niego 3 klatki.',
    addPhotos: '+ Dodaj zdjęcia lub film',
    remove: 'Usuń zdjęcie',
    rights: 'Mam zgodę na użycie tych zdjęć (przestrzeń jest moja lub mojego klienta).',
    s2Title: 'Co ma być w przestrzeni',
    s2Hint: 'Możesz podać markę lub styl. Kineo sprawdza w sieci, jak ta przestrzeń naprawdę wygląda, i przygotowuje brief.',
    kind_store: 'Sklep',
    kind_food: 'Kawiarnia, bar lub restauracja',
    kind_office: 'Biuro',
    kind_home: 'Mieszkanie lub dom',
    kind_other: 'Inne',
    placeholder: 'Np.: kawiarnia Starbucks · Burger King · mieszkanie w stylu japandi',
    research: 'Sprawdź i przygotuj brief',
    researching: 'Szukam…',
    researchAgain: 'Szukaj ponownie',
    briefLabel: 'Brief projektowy (jeden szczegół w linii — edytuj dowolnie)',
    notesLabel: 'Twoje życzenia (opcjonalnie)',
    notesPlaceholder: 'Np.: lada po lewej, więcej roślin, drewniana podłoga',
    s3Title: 'Gotowa przestrzeń, zdjęcie po zdjęciu',
    s3Hint: 'Nano Banana Pro · {n} kredytów za zdjęcie. Przeciągnij, by porównać przed i po; popraw tylko to, które ci się nie podoba.',
    generatePhotos: 'Utwórz gotową przestrzeń · {n} kredytów',
    generatePhotosIdle: 'Utwórz gotową przestrzeń',
    generating: 'Tworzę…',
    allDone: 'Wszystko gotowe',
    checkRights: 'Zaznacz zgodę na zdjęcia w kroku 1.',
    waiting: 'Czeka',
    uploading: 'Wysyłam zdjęcie…',
    staging: 'Urządzam przestrzeń…',
    redo: 'Popraw to · {n} kredytów',
    s4Title: 'Film przed → po',
    s4Hint: 'Kling 2.5 · {n} kredytów za zdjęcie.',
    presentedByLabel: 'Prezentuje (opcjonalnie)',
    presentedByPlaceholder: 'Twoje imię lub nazwa firmy',
    presentedByHint: 'Tylko nazwa osoby, która prezentuje. Nie podawaj innej osoby ani marki jako autora.',
    sealLabel: 'Dodaj do filmu dopisek „Obraz poglądowy”',
    makeVideo: 'Utwórz film · {n} kredytów',
    makeVideoIdle: 'Utwórz film',
    makingClips: 'Tworzę klipy (1–3 min)…',
    montage: 'Montuję film… {n}%',
    remake: 'Zmontuj film ponownie',
    needStaged: 'Najpierw utwórz gotową przestrzeń dla każdego zdjęcia.',
    download: 'Pobierz film',
    compare: 'Porównaj przed i po',
    emptyAlt: 'Pusta przestrzeń',
    readyAlt: 'Gotowa przestrzeń',
    before: 'PRZED',
    after: 'PO',
    presentedBy: 'Prezentuje {name}',
    seal: 'Obraz poglądowy',
    errCredits: 'Za mało kredytów na ten krok.',
    errModeration: 'Moderacja odrzuciła to zdjęcie lub prośbę.',
    errLimit: 'Osiągnięto dzienny limit. Spróbuj jutro.',
    errGeneric: 'Nie udało się. Spróbuj ponownie.',
    errFile: 'Nie udało się odczytać pliku. Użyj JPG, PNG, WEBP lub filmu MP4/MOV.',
    errNoBrief: 'Wyszukiwanie nie znalazło pewnych szczegółów. Opisz przestrzeń sam lub utwórz ją tylko z opisu.',
    errClip: 'Klip się nie udał (kredyty zwrócone). Spróbuj ponownie.',
    errClipSlow: 'Klip trwa długo. Pojawi się w Bibliotece; zmontuj film później.',
    errSomeClips: 'Jeden klip nie jest gotowy. Popraw oznaczone zdjęcie i zmontuj ponownie.',
    errMontage: 'Montaż się nie udał. Spróbuj ponownie.',
    errMontageSlow: 'Montaż trwa długo. Spróbuj za kilka minut.',
    multiLink: 'Jedno miejsce, kilka biznesów →',
    multiTitle: 'Jedno miejsce, kilka biznesów',
    multiSub: 'Pokaż to samo puste miejsce jako 2–4 różne biznesy w jednym filmie przed → po, każdy z nazwą na ekranie.',
    multiS1Hint: 'Jedno pionowe zdjęcie pustego miejsca albo film — weźmiemy z niego jedną klatkę.',
    multiS2Title: 'Czym mogłoby się stać?',
    multiS2Hint: 'Od dwóch do {n}. Nadaj każdemu krótką nazwę do filmu i opisz, co jest w środku.',
    destLabelPlaceholder: 'Nazwa w filmie (np. Kawiarnia)',
    addDestination: '+ Dodaj biznes',
    multiTotal: '{n} kredytów łącznie — gotowe zdjęcie i klip dla każdego biznesu',
    backToSingle: '← Wróć do jednego biznesu na zdjęcie',
  },
  tr: {
    badge: 'Yeni',
    title: 'Mekânlar',
    sub: 'Boş bir mekânın fotoğrafını çek, içine ne gireceğini söyle; onu fotoğraflarda ve önce → sonra videosunda hazır al — aynı kamera, aynı yapı.',
    s1Title: 'Boş mekânın fotoğrafları',
    s1Hint: 'En fazla {n} dikey fotoğraf ya da mekânda yürüyen bir video — içinden 3 kare alırız.',
    addPhotos: '+ Fotoğraf veya video ekle',
    remove: 'Fotoğrafı kaldır',
    rights: 'Bu fotoğrafları kullanma iznim var (mekân benim ya da müşterimin).',
    s2Title: 'Mekânın içine ne girecek',
    s2Hint: 'Bir marka ya da stil yazabilirsin. Kineo o mekânın gerçekte nasıl göründüğünü web’de araştırır ve tasarım özetini hazırlar.',
    kind_store: 'Mağaza',
    kind_food: 'Kafe, bar veya restoran',
    kind_office: 'Ofis',
    kind_home: 'Daire veya ev',
    kind_other: 'Diğer',
    placeholder: 'Örn.: bir Starbucks kafe · bir Burger King · japandi tarzı bir daire',
    research: 'Araştır ve tasarım özetini hazırla',
    researching: 'Araştırılıyor…',
    researchAgain: 'Yeniden araştır',
    briefLabel: 'Tasarım özeti (her satıra bir ayrıntı — dilediğin gibi düzenle)',
    notesLabel: 'İsteklerin (isteğe bağlı)',
    notesPlaceholder: 'Örn.: tezgâh solda, daha çok bitki, ahşap zemin',
    s3Title: 'Hazır mekân, fotoğraf fotoğraf',
    s3Hint: 'Nano Banana Pro · fotoğraf başına {n} kredi. Önce ve sonrayı karşılaştırmak için sürükle; yalnızca beğenmediğini yeniden yap.',
    generatePhotos: 'Hazır mekânı oluştur · {n} kredi',
    generatePhotosIdle: 'Hazır mekânı oluştur',
    generating: 'Oluşturuluyor…',
    allDone: 'Hepsi oluşturuldu',
    checkRights: '1. adımda fotoğraf iznini işaretle.',
    waiting: 'Bekliyor',
    uploading: 'Fotoğraf yükleniyor…',
    staging: 'Mekân düzenleniyor…',
    redo: 'Bunu yeniden yap · {n} kredi',
    s4Title: 'Önce → sonra videosu',
    s4Hint: 'Kling 2.5 · fotoğraf başına {n} kredi.',
    presentedByLabel: 'Sunan (isteğe bağlı)',
    presentedByPlaceholder: 'Adın veya şirketinin adı',
    presentedByHint: 'Yalnızca sunanın adı. Başka bir kişiyi veya markayı yazar olarak gösterme.',
    sealLabel: 'Videoya “Temsili görsel” notu ekle',
    makeVideo: 'Videoyu oluştur · {n} kredi',
    makeVideoIdle: 'Videoyu oluştur',
    makingClips: 'Klipler oluşturuluyor (1–3 dk)…',
    montage: 'Video kurgulanıyor… %{n}',
    remake: 'Videoyu yeniden kurgula',
    needStaged: 'Önce her fotoğraf için hazır mekânı oluştur.',
    download: 'Videoyu indir',
    compare: 'Önce ve sonrayı karşılaştır',
    emptyAlt: 'Boş mekân',
    readyAlt: 'Hazır mekân',
    before: 'ÖNCE',
    after: 'SONRA',
    presentedBy: 'Sunan: {name}',
    seal: 'Temsili görsel',
    errCredits: 'Bu adım için yeterli kredi yok.',
    errModeration: 'Moderasyon bu fotoğrafı veya isteği reddetti.',
    errLimit: 'Günlük sınıra ulaşıldı. Yarın tekrar dene.',
    errGeneric: 'Olmadı. Tekrar dene.',
    errFile: 'Dosyalardan biri okunamadı. JPG, PNG, WEBP veya MP4/MOV video kullan.',
    errNoBrief: 'Araştırma güvenilir ayrıntı bulamadı. Mekânın nasıl olacağını kendin yaz ya da yalnızca açıklamayla oluştur.',
    errClip: 'Klip başarısız oldu (krediler iade edildi). Tekrar dene.',
    errClipSlow: 'Klip uzun sürüyor. Kitaplığında görünecek; videoyu daha sonra yeniden kurgula.',
    errSomeClips: 'Bir klip hazır değil. İşaretli fotoğrafı düzelt ve yeniden kurgula.',
    errMontage: 'Kurgu başarısız oldu. Tekrar dene.',
    errMontageSlow: 'Kurgu uzun sürüyor. Birkaç dakika sonra tekrar dene.',
    multiLink: 'Tek mekân, birden çok işletme →',
    multiTitle: 'Tek mekân, birden çok işletme',
    multiSub: 'Aynı boş mekânı tek bir önce → sonra videosunda 2–4 farklı işletme olarak göster; her birinin adı ekranda.',
    multiS1Hint: 'Boş mekânın dikey bir fotoğrafı ya da bir video — videodan bir kare alırız.',
    multiS2Title: 'Hangi işletmeler olabilir?',
    multiS2Hint: 'İkiden {n} taneye kadar. Her birine video için kısa bir ad ver ve içine ne geleceğini yaz.',
    destLabelPlaceholder: 'Videodaki ad (örn. Kafe)',
    addDestination: '+ İşletme ekle',
    multiTotal: 'Toplam {n} kredi — her işletme için hazır bir fotoğraf ve bir klip',
    backToSingle: '← İşletme başına bir fotoğrafa dön',
  },
  ru: {
    badge: 'Новое',
    title: 'Пространства',
    sub: 'Сфотографируйте пустое помещение, скажите, что в нём должно быть, и получите его готовым на фото и в видео «до → после» — та же камера, та же конструкция.',
    s1Title: 'Фото пустого помещения',
    s1Hint: 'До {n} вертикальных фото или видео с проходом по помещению — мы возьмём из него 3 кадра.',
    addPhotos: '+ Добавить фото или видео',
    remove: 'Удалить фото',
    rights: 'У меня есть право использовать эти фото (помещение моё или моего клиента).',
    s2Title: 'Что будет в помещении',
    s2Hint: 'Можно назвать бренд или стиль. Kineo ищет в интернете, как такое пространство выглядит на самом деле, и собирает дизайн-бриф.',
    kind_store: 'Магазин',
    kind_food: 'Кафе, бар или ресторан',
    kind_office: 'Офис',
    kind_home: 'Квартира или дом',
    kind_other: 'Другое',
    placeholder: 'Напр.: кофейня Starbucks · Burger King · квартира в стиле джапанди',
    research: 'Изучить и собрать бриф',
    researching: 'Ищем…',
    researchAgain: 'Искать снова',
    briefLabel: 'Дизайн-бриф (одна деталь в строке — редактируйте свободно)',
    notesLabel: 'Ваши пожелания (необязательно)',
    notesPlaceholder: 'Напр.: стойка слева, больше растений, деревянный пол',
    s3Title: 'Готовое помещение, фото за фото',
    s3Hint: 'Nano Banana Pro · {n} кредитов за фото. Перетащите, чтобы сравнить «до» и «после»; переделайте только то, что не нравится.',
    generatePhotos: 'Создать готовое помещение · {n} кредитов',
    generatePhotosIdle: 'Создать готовое помещение',
    generating: 'Создаём…',
    allDone: 'Всё создано',
    checkRights: 'Отметьте разрешение на фото в шаге 1.',
    waiting: 'Ожидание',
    uploading: 'Загружаем фото…',
    staging: 'Обустраиваем помещение…',
    redo: 'Переделать это · {n} кредитов',
    s4Title: 'Видео «до → после»',
    s4Hint: 'Kling 2.5 · {n} кредитов за фото.',
    presentedByLabel: 'Представляет (необязательно)',
    presentedByPlaceholder: 'Ваше имя или название компании',
    presentedByHint: 'Только имя того, кто представляет. Не указывайте другого человека или бренд как автора.',
    sealLabel: 'Добавить в видео пометку «Иллюстративное изображение»',
    makeVideo: 'Создать видео · {n} кредитов',
    makeVideoIdle: 'Создать видео',
    makingClips: 'Создаём клипы (1–3 мин)…',
    montage: 'Монтируем видео… {n}%',
    remake: 'Смонтировать заново',
    needStaged: 'Сначала создайте готовое помещение для каждого фото.',
    download: 'Скачать видео',
    compare: 'Сравнить «до» и «после»',
    emptyAlt: 'Пустое помещение',
    readyAlt: 'Готовое помещение',
    before: 'ДО',
    after: 'ПОСЛЕ',
    presentedBy: 'Представляет {name}',
    seal: 'Иллюстративное изображение',
    errCredits: 'Недостаточно кредитов для этого шага.',
    errModeration: 'Модерация отклонила это фото или запрос.',
    errLimit: 'Дневной лимит исчерпан. Попробуйте завтра.',
    errGeneric: 'Не получилось. Попробуйте ещё раз.',
    errFile: 'Не удалось прочитать файл. Используйте JPG, PNG, WEBP или видео MP4/MOV.',
    errNoBrief: 'Поиск не нашёл надёжных деталей. Опишите помещение сами или создайте его только по описанию.',
    errClip: 'Клип не удался (кредиты возвращены). Попробуйте ещё раз.',
    errClipSlow: 'Клип создаётся долго. Он появится в Библиотеке; смонтируйте видео позже.',
    errSomeClips: 'Один клип не готов. Исправьте отмеченное фото и смонтируйте заново.',
    errMontage: 'Монтаж не удался. Попробуйте ещё раз.',
    errMontageSlow: 'Монтаж идёт долго. Попробуйте через несколько минут.',
    multiLink: 'Одно помещение — несколько бизнесов →',
    multiTitle: 'Одно помещение — несколько бизнесов',
    multiSub: 'Покажите одно и то же пустое помещение как 2–4 разных бизнеса в одном видео «до → после», с названием каждого на экране.',
    multiS1Hint: 'Одно вертикальное фото пустого помещения или видео — мы возьмём из него один кадр.',
    multiS2Title: 'Чем оно может стать?',
    multiS2Hint: 'От двух до {n}. Дайте каждому короткое название для видео и опишите, что внутри.',
    destLabelPlaceholder: 'Название в видео (напр. Кафе)',
    addDestination: '+ Добавить бизнес',
    multiTotal: 'Всего {n} кредитов — готовое фото и клип для каждого бизнеса',
    backToSingle: '← Назад: один бизнес на фото',
  },
  uk: {
    badge: 'Нове',
    title: 'Простори',
    sub: 'Сфотографуйте порожнє приміщення, скажіть, що в ньому має бути, і отримайте його готовим на фото й у відео «до → після» — та сама камера, та сама конструкція.',
    s1Title: 'Фото порожнього приміщення',
    s1Hint: 'До {n} вертикальних фото або відео з проходом приміщенням — ми візьмемо з нього 3 кадри.',
    addPhotos: '+ Додати фото або відео',
    remove: 'Видалити фото',
    rights: 'Я маю право використовувати ці фото (приміщення моє або мого клієнта).',
    s2Title: 'Що буде в приміщенні',
    s2Hint: 'Можна назвати бренд чи стиль. Kineo шукає в інтернеті, як такий простір виглядає насправді, і складає дизайн-бриф.',
    kind_store: 'Магазин',
    kind_food: 'Кав’ярня, бар або ресторан',
    kind_office: 'Офіс',
    kind_home: 'Квартира або будинок',
    kind_other: 'Інше',
    placeholder: 'Напр.: кав’ярня Starbucks · Burger King · квартира в стилі джапанді',
    research: 'Дослідити й скласти бриф',
    researching: 'Шукаємо…',
    researchAgain: 'Шукати знову',
    briefLabel: 'Дизайн-бриф (одна деталь у рядку — редагуйте вільно)',
    notesLabel: 'Ваші побажання (необов’язково)',
    notesPlaceholder: 'Напр.: стійка ліворуч, більше рослин, дерев’яна підлога',
    s3Title: 'Готове приміщення, фото за фото',
    s3Hint: 'Nano Banana Pro · {n} кредитів за фото. Перетягніть, щоб порівняти «до» і «після»; переробіть лише те, що не подобається.',
    generatePhotos: 'Створити готове приміщення · {n} кредитів',
    generatePhotosIdle: 'Створити готове приміщення',
    generating: 'Створюємо…',
    allDone: 'Усе створено',
    checkRights: 'Позначте дозвіл на фото в кроці 1.',
    waiting: 'Очікування',
    uploading: 'Завантажуємо фото…',
    staging: 'Облаштовуємо приміщення…',
    redo: 'Переробити це · {n} кредитів',
    s4Title: 'Відео «до → після»',
    s4Hint: 'Kling 2.5 · {n} кредитів за фото.',
    presentedByLabel: 'Представляє (необов’язково)',
    presentedByPlaceholder: 'Ваше ім’я або назва компанії',
    presentedByHint: 'Лише ім’я того, хто представляє. Не вказуйте іншу людину чи бренд як автора.',
    sealLabel: 'Додати у відео позначку «Ілюстративне зображення»',
    makeVideo: 'Створити відео · {n} кредитів',
    makeVideoIdle: 'Створити відео',
    makingClips: 'Створюємо кліпи (1–3 хв)…',
    montage: 'Монтуємо відео… {n}%',
    remake: 'Змонтувати знову',
    needStaged: 'Спочатку створіть готове приміщення для кожного фото.',
    download: 'Завантажити відео',
    compare: 'Порівняти «до» і «після»',
    emptyAlt: 'Порожнє приміщення',
    readyAlt: 'Готове приміщення',
    before: 'ДО',
    after: 'ПІСЛЯ',
    presentedBy: 'Представляє {name}',
    seal: 'Ілюстративне зображення',
    errCredits: 'Недостатньо кредитів для цього кроку.',
    errModeration: 'Модерація відхилила це фото або запит.',
    errLimit: 'Денний ліміт вичерпано. Спробуйте завтра.',
    errGeneric: 'Не вийшло. Спробуйте ще раз.',
    errFile: 'Не вдалося прочитати файл. Використовуйте JPG, PNG, WEBP або відео MP4/MOV.',
    errNoBrief: 'Пошук не знайшов надійних деталей. Опишіть приміщення самі або створіть його лише за описом.',
    errClip: 'Кліп не вдався (кредити повернено). Спробуйте ще раз.',
    errClipSlow: 'Кліп створюється довго. Він з’явиться в Бібліотеці; змонтуйте відео пізніше.',
    errSomeClips: 'Один кліп не готовий. Виправте позначене фото й змонтуйте знову.',
    errMontage: 'Монтаж не вдався. Спробуйте ще раз.',
    errMontageSlow: 'Монтаж триває довго. Спробуйте за кілька хвилин.',
    multiLink: 'Одне приміщення — кілька бізнесів →',
    multiTitle: 'Одне приміщення — кілька бізнесів',
    multiSub: 'Покажіть те саме порожнє приміщення як 2–4 різні бізнеси в одному відео «до → після», з назвою кожного на екрані.',
    multiS1Hint: 'Одне вертикальне фото порожнього приміщення або відео — ми візьмемо з нього один кадр.',
    multiS2Title: 'Чим воно може стати?',
    multiS2Hint: 'Від двох до {n}. Дайте кожному коротку назву для відео й опишіть, що всередині.',
    destLabelPlaceholder: 'Назва у відео (напр. Кав’ярня)',
    addDestination: '+ Додати бізнес',
    multiTotal: 'Усього {n} кредитів — готове фото й кліп для кожного бізнесу',
    backToSingle: '← Назад: один бізнес на фото',
  },
  ar: {
    badge: 'جديد',
    title: 'المساحات',
    sub: 'صوّر مساحة فارغة، وقل ما سيكون داخلها، واحصل عليها جاهزة بالصور وبفيديو قبل ← بعد — الكاميرا نفسها والبنية نفسها.',
    s1Title: 'صور المساحة الفارغة',
    s1Hint: 'حتى {n} صور عمودية، أو فيديو تتجول فيه داخل المساحة — نأخذ منه 3 لقطات.',
    addPhotos: '+ أضف صورًا أو فيديو',
    remove: 'إزالة الصورة',
    rights: 'لدي إذن باستخدام هذه الصور (المساحة ملكي أو ملك عميلي).',
    s2Title: 'ما الذي سيكون داخل المساحة',
    s2Hint: 'يمكنك ذكر علامة تجارية أو أسلوب. تبحث Kineo على الويب عن الشكل الحقيقي لتلك المساحة وتعدّ ملخص التصميم.',
    kind_store: 'متجر',
    kind_food: 'مقهى أو بار أو مطعم',
    kind_office: 'مكتب',
    kind_home: 'شقة أو منزل',
    kind_other: 'أخرى',
    placeholder: 'مثال: مقهى ستاربكس · برجر كنج · شقة بأسلوب جابندي',
    research: 'ابحث وأعدّ ملخص التصميم',
    researching: 'جارٍ البحث…',
    researchAgain: 'ابحث مرة أخرى',
    briefLabel: 'ملخص التصميم (تفصيلة واحدة في كل سطر — عدّل بحرية)',
    notesLabel: 'طلباتك (اختياري)',
    notesPlaceholder: 'مثال: الكاونتر على اليسار، نباتات أكثر، أرضية خشبية',
    s3Title: 'المساحة الجاهزة، صورة بصورة',
    s3Hint: 'Nano Banana Pro · {n} رصيد لكل صورة. اسحب للمقارنة بين قبل وبعد؛ أعد فقط الصورة التي لا تعجبك.',
    generatePhotos: 'أنشئ المساحة الجاهزة · {n} رصيد',
    generatePhotosIdle: 'أنشئ المساحة الجاهزة',
    generating: 'جارٍ الإنشاء…',
    allDone: 'تم إنشاء الكل',
    checkRights: 'فعّل إذن الصور في الخطوة 1.',
    waiting: 'في الانتظار',
    uploading: 'جارٍ رفع الصورة…',
    staging: 'جارٍ تجهيز المساحة…',
    redo: 'أعد هذه · {n} رصيد',
    s4Title: 'فيديو قبل ← بعد',
    s4Hint: 'Kling 2.5 · {n} رصيد لكل صورة.',
    presentedByLabel: 'مقدَّم من (اختياري)',
    presentedByPlaceholder: 'اسمك أو اسم شركتك',
    presentedByHint: 'اسم من يقدّم فقط. لا تنسب التصميم إلى شخص آخر أو علامة تجارية.',
    sealLabel: 'أضف ملاحظة «صورة توضيحية» إلى الفيديو',
    makeVideo: 'أنشئ الفيديو · {n} رصيد',
    makeVideoIdle: 'أنشئ الفيديو',
    makingClips: 'جارٍ إنشاء المقاطع (1–3 دقائق)…',
    montage: 'جارٍ مونتاج الفيديو… {n}%',
    remake: 'أعد مونتاج الفيديو',
    needStaged: 'أنشئ المساحة الجاهزة لكل الصور أولًا.',
    download: 'تنزيل الفيديو',
    compare: 'قارن بين قبل وبعد',
    emptyAlt: 'مساحة فارغة',
    readyAlt: 'مساحة جاهزة',
    before: 'قبل',
    after: 'بعد',
    presentedBy: 'مقدَّم من {name}',
    seal: 'صورة توضيحية',
    errCredits: 'الرصيد غير كافٍ لهذه الخطوة.',
    errModeration: 'رفضت المراجعة هذه الصورة أو هذا الطلب.',
    errLimit: 'تم بلوغ الحد اليومي. حاول غدًا.',
    errGeneric: 'لم ينجح ذلك. حاول مرة أخرى.',
    errFile: 'تعذّرت قراءة أحد الملفات. استخدم JPG أو PNG أو WEBP أو فيديو MP4/MOV.',
    errNoBrief: 'لم يجد البحث تفاصيل موثوقة. اكتب بنفسك كيف يجب أن تبدو المساحة، أو أنشئها بالوصف فقط.',
    errClip: 'فشل المقطع (تمت إعادة الرصيد). حاول مرة أخرى.',
    errClipSlow: 'المقطع يستغرق وقتًا. سيظهر في مكتبتك؛ أعد المونتاج لاحقًا.',
    errSomeClips: 'أحد المقاطع غير جاهز. صحّح الصورة المحددة وأعد المونتاج.',
    errMontage: 'فشل المونتاج. حاول مرة أخرى.',
    errMontageSlow: 'المونتاج يستغرق وقتًا. حاول بعد بضع دقائق.',
    multiLink: 'مساحة واحدة، أنشطة متعددة ←',
    multiTitle: 'مساحة واحدة، أنشطة متعددة',
    multiSub: 'اعرض المساحة الفارغة نفسها كنشاطين إلى أربعة أنشطة مختلفة في فيديو واحد قبل ← بعد، مع اسم كل نشاط على الشاشة.',
    multiS1Hint: 'صورة عمودية واحدة للمساحة الفارغة، أو فيديو — نأخذ منه لقطة واحدة.',
    multiS2Title: 'ما الأنشطة التي يمكن أن تصبحها؟',
    multiS2Hint: 'من اثنين إلى {n}. أعطِ كل نشاط اسمًا قصيرًا للفيديو وصِف ما بداخله.',
    destLabelPlaceholder: 'الاسم في الفيديو (مثل: مقهى)',
    addDestination: '+ إضافة نشاط',
    multiTotal: '{n} رصيدًا إجمالًا — صورة جاهزة ومقطع لكل نشاط',
    backToSingle: '→ العودة إلى نشاط واحد لكل صورة',
  },
  ur: {
    badge: 'نیا',
    title: 'اسپیسز',
    sub: 'خالی جگہ کی تصویر لیں، بتائیں اندر کیا ہوگا، اور اسے تیار حالت میں تصاویر اور پہلے ← بعد ویڈیو میں پائیں — وہی کیمرہ، وہی ڈھانچہ۔',
    s1Title: 'خالی جگہ کی تصاویر',
    s1Hint: 'زیادہ سے زیادہ {n} عمودی تصاویر، یا جگہ میں چلتے ہوئے ایک ویڈیو — ہم اس سے 3 فریم لیتے ہیں۔',
    addPhotos: '+ تصاویر یا ویڈیو شامل کریں',
    remove: 'تصویر ہٹائیں',
    rights: 'مجھے یہ تصاویر استعمال کرنے کی اجازت ہے (جگہ میری یا میرے کلائنٹ کی ہے)۔',
    s2Title: 'جگہ کے اندر کیا ہوگا',
    s2Hint: 'آپ کوئی برانڈ یا اسٹائل لکھ سکتے ہیں۔ Kineo ویب پر دیکھتا ہے کہ وہ جگہ اصل میں کیسی لگتی ہے اور ڈیزائن بریف بناتا ہے۔',
    kind_store: 'دکان',
    kind_food: 'کیفے، بار یا ریستوران',
    kind_office: 'دفتر',
    kind_home: 'اپارٹمنٹ یا گھر',
    kind_other: 'دیگر',
    placeholder: 'مثلاً: اسٹاربکس کیفے · برگر کنگ · جاپانڈی اسٹائل اپارٹمنٹ',
    research: 'تحقیق کریں اور ڈیزائن بریف بنائیں',
    researching: 'تحقیق جاری ہے…',
    researchAgain: 'دوبارہ تحقیق کریں',
    briefLabel: 'ڈیزائن بریف (ہر لائن میں ایک تفصیل — آزادی سے ترمیم کریں)',
    notesLabel: 'آپ کی درخواستیں (اختیاری)',
    notesPlaceholder: 'مثلاً: کاؤنٹر بائیں طرف، زیادہ پودے، لکڑی کا فرش',
    s3Title: 'تیار جگہ، تصویر بہ تصویر',
    s3Hint: 'Nano Banana Pro · فی تصویر {n} کریڈٹس۔ پہلے اور بعد کا موازنہ کرنے کے لیے کھینچیں؛ صرف وہی دوبارہ بنائیں جو پسند نہ آئے۔',
    generatePhotos: 'تیار جگہ بنائیں · {n} کریڈٹس',
    generatePhotosIdle: 'تیار جگہ بنائیں',
    generating: 'بن رہا ہے…',
    allDone: 'سب بن گیا',
    checkRights: 'مرحلہ 1 میں تصاویر کی اجازت پر نشان لگائیں۔',
    waiting: 'انتظار میں',
    uploading: 'تصویر اپ لوڈ ہو رہی ہے…',
    staging: 'جگہ سجائی جا رہی ہے…',
    redo: 'اسے دوبارہ بنائیں · {n} کریڈٹس',
    s4Title: 'پہلے ← بعد ویڈیو',
    s4Hint: 'Kling 2.5 · فی تصویر {n} کریڈٹس۔',
    presentedByLabel: 'پیش کردہ (اختیاری)',
    presentedByPlaceholder: 'آپ کا نام یا آپ کی کمپنی',
    presentedByHint: 'صرف پیش کرنے والے کا نام۔ کسی اور شخص یا برانڈ کو مصنف نہ بتائیں۔',
    sealLabel: 'ویڈیو میں «مثالی تصویر» کا نوٹ شامل کریں',
    makeVideo: 'ویڈیو بنائیں · {n} کریڈٹس',
    makeVideoIdle: 'ویڈیو بنائیں',
    makingClips: 'کلپس بن رہے ہیں (1–3 منٹ)…',
    montage: 'ویڈیو ایڈٹ ہو رہی ہے… {n}%',
    remake: 'ویڈیو دوبارہ ایڈٹ کریں',
    needStaged: 'پہلے ہر تصویر کے لیے تیار جگہ بنائیں۔',
    download: 'ویڈیو ڈاؤن لوڈ کریں',
    compare: 'پہلے اور بعد کا موازنہ کریں',
    emptyAlt: 'خالی جگہ',
    readyAlt: 'تیار جگہ',
    before: 'پہلے',
    after: 'بعد',
    presentedBy: 'پیش کردہ: {name}',
    seal: 'مثالی تصویر',
    errCredits: 'اس مرحلے کے لیے کریڈٹس کافی نہیں۔',
    errModeration: 'ماڈریشن نے یہ تصویر یا درخواست مسترد کر دی۔',
    errLimit: 'روزانہ کی حد پوری ہو گئی۔ کل دوبارہ کوشش کریں۔',
    errGeneric: 'یہ نہیں ہو سکا۔ دوبارہ کوشش کریں۔',
    errFile: 'ایک فائل پڑھی نہیں جا سکی۔ JPG، PNG، WEBP یا MP4/MOV ویڈیو استعمال کریں۔',
    errNoBrief: 'تحقیق کو قابلِ اعتماد تفصیلات نہیں ملیں۔ خود لکھیں کہ جگہ کیسی ہو، یا صرف تفصیل سے بنائیں۔',
    errClip: 'کلپ ناکام ہو گیا (کریڈٹس واپس)۔ دوبارہ کوشش کریں۔',
    errClipSlow: 'کلپ میں وقت لگ رہا ہے۔ یہ آپ کی لائبریری میں آ جائے گا؛ بعد میں ویڈیو دوبارہ ایڈٹ کریں۔',
    errSomeClips: 'ایک کلپ تیار نہیں۔ نشان زدہ تصویر درست کریں اور دوبارہ ایڈٹ کریں۔',
    errMontage: 'ایڈیٹنگ ناکام ہو گئی۔ دوبارہ کوشش کریں۔',
    errMontageSlow: 'ایڈیٹنگ میں وقت لگ رہا ہے۔ چند منٹ بعد کوشش کریں۔',
    multiLink: 'ایک جگہ، کئی کاروبار ←',
    multiTitle: 'ایک جگہ، کئی کاروبار',
    multiSub: 'ایک ہی خالی جگہ کو ایک ہی پہلے ← بعد ویڈیو میں 2 سے 4 مختلف کاروباروں کی صورت میں دکھائیں، ہر ایک کا نام اسکرین پر۔',
    multiS1Hint: 'خالی جگہ کی ایک عمودی تصویر، یا ایک ویڈیو — ہم اس سے ایک فریم لیں گے۔',
    multiS2Title: 'یہ کون سے کاروبار بن سکتی ہے؟',
    multiS2Hint: 'دو سے {n} تک۔ ہر ایک کو ویڈیو کے لیے مختصر نام دیں اور بتائیں اندر کیا ہوگا۔',
    destLabelPlaceholder: 'ویڈیو میں نام (مثلاً کیفے)',
    addDestination: '+ کاروبار شامل کریں',
    multiTotal: 'کل {n} کریڈٹس — ہر کاروبار کے لیے ایک تیار تصویر اور ایک کلپ',
    backToSingle: '→ ہر تصویر پر ایک کاروبار پر واپس',
  },
  hi: {
    badge: 'नया',
    title: 'स्पेसेज़',
    sub: 'खाली जगह की फ़ोटो लें, बताएँ अंदर क्या होगा, और उसे तैयार रूप में फ़ोटो और पहले → बाद वीडियो में पाएँ — वही कैमरा, वही ढाँचा।',
    s1Title: 'खाली जगह की फ़ोटो',
    s1Hint: 'अधिकतम {n} वर्टिकल फ़ोटो, या जगह में घूमते हुए एक वीडियो — हम उससे 3 फ़्रेम लेते हैं।',
    addPhotos: '+ फ़ोटो या वीडियो जोड़ें',
    remove: 'फ़ोटो हटाएँ',
    rights: 'मुझे ये फ़ोटो इस्तेमाल करने की अनुमति है (जगह मेरी या मेरे क्लाइंट की है)।',
    s2Title: 'जगह के अंदर क्या होगा',
    s2Hint: 'आप कोई ब्रांड या स्टाइल लिख सकते हैं। Kineo वेब पर खोजता है कि वह जगह असल में कैसी दिखती है और डिज़ाइन ब्रीफ़ बनाता है।',
    kind_store: 'दुकान',
    kind_food: 'कैफ़े, बार या रेस्टोरेंट',
    kind_office: 'ऑफ़िस',
    kind_home: 'अपार्टमेंट या घर',
    kind_other: 'अन्य',
    placeholder: 'जैसे: एक Starbucks कैफ़े · एक Burger King · जापांडी स्टाइल अपार्टमेंट',
    research: 'खोजें और डिज़ाइन ब्रीफ़ बनाएँ',
    researching: 'खोज जारी है…',
    researchAgain: 'फिर से खोजें',
    briefLabel: 'डिज़ाइन ब्रीफ़ (हर पंक्ति में एक विवरण — खुलकर बदलें)',
    notesLabel: 'आपके अनुरोध (वैकल्पिक)',
    notesPlaceholder: 'जैसे: काउंटर बाईं ओर, ज़्यादा पौधे, लकड़ी का फ़र्श',
    s3Title: 'तैयार जगह, फ़ोटो दर फ़ोटो',
    s3Hint: 'Nano Banana Pro · प्रति फ़ोटो {n} क्रेडिट। पहले और बाद की तुलना के लिए खींचें; सिर्फ़ वही दोबारा बनाएँ जो पसंद न आए।',
    generatePhotos: 'तैयार जगह बनाएँ · {n} क्रेडिट',
    generatePhotosIdle: 'तैयार जगह बनाएँ',
    generating: 'बन रहा है…',
    allDone: 'सब बन गया',
    checkRights: 'चरण 1 में फ़ोटो की अनुमति पर टिक करें।',
    waiting: 'प्रतीक्षा में',
    uploading: 'फ़ोटो अपलोड हो रही है…',
    staging: 'जगह सजाई जा रही है…',
    redo: 'इसे दोबारा बनाएँ · {n} क्रेडिट',
    s4Title: 'पहले → बाद वीडियो',
    s4Hint: 'Kling 2.5 · प्रति फ़ोटो {n} क्रेडिट।',
    presentedByLabel: 'प्रस्तुतकर्ता (वैकल्पिक)',
    presentedByPlaceholder: 'आपका नाम या आपकी कंपनी',
    presentedByHint: 'सिर्फ़ प्रस्तुत करने वाले का नाम। किसी और व्यक्ति या ब्रांड को लेखक न बताएँ।',
    sealLabel: 'वीडियो में “उदाहरण चित्र” नोट जोड़ें',
    makeVideo: 'वीडियो बनाएँ · {n} क्रेडिट',
    makeVideoIdle: 'वीडियो बनाएँ',
    makingClips: 'क्लिप बन रहे हैं (1–3 मिनट)…',
    montage: 'वीडियो एडिट हो रहा है… {n}%',
    remake: 'वीडियो फिर से एडिट करें',
    needStaged: 'पहले हर फ़ोटो के लिए तैयार जगह बनाएँ।',
    download: 'वीडियो डाउनलोड करें',
    compare: 'पहले और बाद की तुलना करें',
    emptyAlt: 'खाली जगह',
    readyAlt: 'तैयार जगह',
    before: 'पहले',
    after: 'बाद',
    presentedBy: 'प्रस्तुतकर्ता: {name}',
    seal: 'उदाहरण चित्र',
    errCredits: 'इस चरण के लिए पर्याप्त क्रेडिट नहीं हैं।',
    errModeration: 'मॉडरेशन ने यह फ़ोटो या अनुरोध अस्वीकार कर दिया।',
    errLimit: 'दैनिक सीमा पूरी हो गई। कल फिर कोशिश करें।',
    errGeneric: 'यह नहीं हो पाया। फिर कोशिश करें।',
    errFile: 'एक फ़ाइल पढ़ी नहीं जा सकी। JPG, PNG, WEBP या MP4/MOV वीडियो इस्तेमाल करें।',
    errNoBrief: 'खोज को भरोसेमंद विवरण नहीं मिले। खुद लिखें कि जगह कैसी हो, या सिर्फ़ विवरण से बनाएँ।',
    errClip: 'क्लिप विफल रहा (क्रेडिट वापस)। फिर कोशिश करें।',
    errClipSlow: 'क्लिप में समय लग रहा है। यह आपकी लाइब्रेरी में आ जाएगा; बाद में वीडियो फिर से एडिट करें।',
    errSomeClips: 'एक क्लिप तैयार नहीं है। चिह्नित फ़ोटो ठीक करें और फिर से एडिट करें।',
    errMontage: 'एडिटिंग विफल रही। फिर कोशिश करें।',
    errMontageSlow: 'एडिटिंग में समय लग रहा है। कुछ मिनट बाद कोशिश करें।',
    multiLink: 'एक जगह, कई कारोबार →',
    multiTitle: 'एक जगह, कई कारोबार',
    multiSub: 'उसी खाली जगह को एक ही पहले → बाद वीडियो में 2 से 4 अलग कारोबारों के रूप में दिखाएँ, हर एक का नाम स्क्रीन पर।',
    multiS1Hint: 'खाली जगह की एक वर्टिकल फ़ोटो, या एक वीडियो — हम उसमें से एक फ़्रेम लेंगे।',
    multiS2Title: 'यह कौन-से कारोबार बन सकती है?',
    multiS2Hint: 'दो से {n} तक। हर एक को वीडियो के लिए छोटा नाम दें और बताएँ अंदर क्या होगा।',
    destLabelPlaceholder: 'वीडियो में नाम (जैसे कैफ़े)',
    addDestination: '+ कारोबार जोड़ें',
    multiTotal: 'कुल {n} क्रेडिट — हर कारोबार के लिए एक तैयार फ़ोटो और एक क्लिप',
    backToSingle: '← हर फ़ोटो पर एक कारोबार पर लौटें',
  },
  id: {
    badge: 'Baru',
    title: 'Ruang',
    sub: 'Foto ruang kosong, sebutkan apa yang akan ada di dalamnya, dan terima ruang jadi dalam foto dan video sebelum → sesudah — kamera sama, struktur sama.',
    s1Title: 'Foto ruang kosong',
    s1Hint: 'Hingga {n} foto vertikal, atau video berjalan menyusuri ruang — kami ambil 3 bingkai darinya.',
    addPhotos: '+ Tambah foto atau video',
    remove: 'Hapus foto',
    rights: 'Saya punya izin memakai foto ini (ruangnya milik saya atau klien saya).',
    s2Title: 'Apa yang ada di dalam ruang',
    s2Hint: 'Anda bisa menyebut merek atau gaya. Kineo mencari di web seperti apa ruang itu sebenarnya dan menyusun brief desain.',
    kind_store: 'Toko',
    kind_food: 'Kafe, bar, atau restoran',
    kind_office: 'Kantor',
    kind_home: 'Apartemen atau rumah',
    kind_other: 'Lainnya',
    placeholder: 'Mis.: kedai kopi Starbucks · Burger King · apartemen bergaya japandi',
    research: 'Riset dan susun brief desain',
    researching: 'Meriset…',
    researchAgain: 'Riset lagi',
    briefLabel: 'Brief desain (satu detail per baris — ubah sesuka Anda)',
    notesLabel: 'Permintaan Anda (opsional)',
    notesPlaceholder: 'Mis.: meja kasir di kiri, lebih banyak tanaman, lantai kayu',
    s3Title: 'Ruang jadi, foto demi foto',
    s3Hint: 'Nano Banana Pro · {n} kredit per foto. Geser untuk membandingkan sebelum dan sesudah; ulangi hanya yang tidak Anda suka.',
    generatePhotos: 'Buat ruang jadi · {n} kredit',
    generatePhotosIdle: 'Buat ruang jadi',
    generating: 'Membuat…',
    allDone: 'Semua selesai',
    checkRights: 'Centang izin foto di langkah 1.',
    waiting: 'Menunggu',
    uploading: 'Mengunggah foto…',
    staging: 'Menata ruang…',
    redo: 'Ulangi yang ini · {n} kredit',
    s4Title: 'Video sebelum → sesudah',
    s4Hint: 'Kling 2.5 · {n} kredit per foto.',
    presentedByLabel: 'Dipersembahkan oleh (opsional)',
    presentedByPlaceholder: 'Nama Anda atau perusahaan Anda',
    presentedByHint: 'Hanya nama yang mempresentasikan. Jangan cantumkan orang atau merek lain sebagai pembuatnya.',
    sealLabel: 'Tambahkan catatan “Gambar ilustrasi” ke video',
    makeVideo: 'Buat video · {n} kredit',
    makeVideoIdle: 'Buat video',
    makingClips: 'Membuat klip (1–3 mnt)…',
    montage: 'Menyunting video… {n}%',
    remake: 'Sunting video lagi',
    needStaged: 'Buat dulu ruang jadi untuk setiap foto.',
    download: 'Unduh video',
    compare: 'Bandingkan sebelum dan sesudah',
    emptyAlt: 'Ruang kosong',
    readyAlt: 'Ruang jadi',
    before: 'SEBELUM',
    after: 'SESUDAH',
    presentedBy: 'Dipersembahkan oleh {name}',
    seal: 'Gambar ilustrasi',
    errCredits: 'Kredit tidak cukup untuk langkah ini.',
    errModeration: 'Moderasi menolak foto atau permintaan ini.',
    errLimit: 'Batas harian tercapai. Coba lagi besok.',
    errGeneric: 'Tidak berhasil. Coba lagi.',
    errFile: 'Salah satu file tidak bisa dibaca. Gunakan JPG, PNG, WEBP, atau video MP4/MOV.',
    errNoBrief: 'Riset tidak menemukan detail yang andal. Tulis sendiri bentuk ruangnya, atau buat hanya dari deskripsi.',
    errClip: 'Klip gagal (kredit dikembalikan). Coba lagi.',
    errClipSlow: 'Klip butuh waktu. Klip akan muncul di Pustaka; sunting video lagi nanti.',
    errSomeClips: 'Ada klip yang belum siap. Perbaiki foto yang ditandai lalu sunting lagi.',
    errMontage: 'Penyuntingan gagal. Coba lagi.',
    errMontageSlow: 'Penyuntingan butuh waktu. Coba lagi beberapa menit lagi.',
    multiLink: 'Satu ruang, beberapa usaha →',
    multiTitle: 'Satu ruang, beberapa usaha',
    multiSub: 'Tampilkan ruang kosong yang sama sebagai 2–4 usaha berbeda dalam satu video sebelum → sesudah, masing-masing dengan nama di layar.',
    multiS1Hint: 'Satu foto vertikal ruang kosong, atau video — kami ambil satu bingkai darinya.',
    multiS2Title: 'Bisa menjadi usaha apa saja?',
    multiS2Hint: 'Dua sampai {n}. Beri nama pendek untuk video dan jelaskan isinya.',
    destLabelPlaceholder: 'Nama di video (mis. Kafe)',
    addDestination: '+ Tambah usaha',
    multiTotal: 'Total {n} kredit — satu foto jadi dan satu klip untuk setiap usaha',
    backToSingle: '← Kembali ke satu usaha per foto',
  },
  vi: {
    badge: 'Mới',
    title: 'Không gian',
    sub: 'Chụp một không gian trống, nói bên trong sẽ có gì, và nhận nó hoàn thiện qua ảnh và video trước → sau — cùng góc máy, cùng kết cấu.',
    s1Title: 'Ảnh không gian trống',
    s1Hint: 'Tối đa {n} ảnh dọc, hoặc một video đi quanh không gian — chúng tôi lấy 3 khung hình từ đó.',
    addPhotos: '+ Thêm ảnh hoặc video',
    remove: 'Xóa ảnh',
    rights: 'Tôi được phép dùng những ảnh này (không gian là của tôi hoặc khách hàng của tôi).',
    s2Title: 'Bên trong không gian sẽ có gì',
    s2Hint: 'Bạn có thể nêu một thương hiệu hoặc phong cách. Kineo tìm trên web xem không gian đó thực sự trông thế nào và lập bản mô tả thiết kế.',
    kind_store: 'Cửa hàng',
    kind_food: 'Quán cà phê, quán bar hoặc nhà hàng',
    kind_office: 'Văn phòng',
    kind_home: 'Căn hộ hoặc nhà',
    kind_other: 'Khác',
    placeholder: 'VD: quán cà phê Starbucks · một Burger King · căn hộ phong cách japandi',
    research: 'Tìm hiểu và lập bản mô tả thiết kế',
    researching: 'Đang tìm…',
    researchAgain: 'Tìm lại',
    briefLabel: 'Bản mô tả thiết kế (mỗi dòng một chi tiết — sửa thoải mái)',
    notesLabel: 'Yêu cầu của bạn (không bắt buộc)',
    notesPlaceholder: 'VD: quầy bên trái, thêm cây xanh, sàn gỗ',
    s3Title: 'Không gian hoàn thiện, từng ảnh',
    s3Hint: 'Nano Banana Pro · {n} tín dụng mỗi ảnh. Kéo để so sánh trước và sau; chỉ làm lại ảnh bạn không thích.',
    generatePhotos: 'Tạo không gian hoàn thiện · {n} tín dụng',
    generatePhotosIdle: 'Tạo không gian hoàn thiện',
    generating: 'Đang tạo…',
    allDone: 'Đã tạo xong',
    checkRights: 'Đánh dấu quyền dùng ảnh ở bước 1.',
    waiting: 'Đang chờ',
    uploading: 'Đang tải ảnh lên…',
    staging: 'Đang bài trí không gian…',
    redo: 'Làm lại ảnh này · {n} tín dụng',
    s4Title: 'Video trước → sau',
    s4Hint: 'Kling 2.5 · {n} tín dụng mỗi ảnh.',
    presentedByLabel: 'Trình bày bởi (không bắt buộc)',
    presentedByPlaceholder: 'Tên bạn hoặc tên công ty',
    presentedByHint: 'Chỉ tên người trình bày. Đừng ghi người hoặc thương hiệu khác là tác giả.',
    sealLabel: 'Thêm ghi chú “Hình ảnh minh họa” vào video',
    makeVideo: 'Tạo video · {n} tín dụng',
    makeVideoIdle: 'Tạo video',
    makingClips: 'Đang tạo clip (1–3 phút)…',
    montage: 'Đang dựng video… {n}%',
    remake: 'Dựng lại video',
    needStaged: 'Hãy tạo không gian hoàn thiện cho mọi ảnh trước.',
    download: 'Tải video',
    compare: 'So sánh trước và sau',
    emptyAlt: 'Không gian trống',
    readyAlt: 'Không gian hoàn thiện',
    before: 'TRƯỚC',
    after: 'SAU',
    presentedBy: 'Trình bày bởi {name}',
    seal: 'Hình ảnh minh họa',
    errCredits: 'Không đủ tín dụng cho bước này.',
    errModeration: 'Bộ kiểm duyệt đã từ chối ảnh hoặc yêu cầu này.',
    errLimit: 'Đã đạt giới hạn hằng ngày. Thử lại vào ngày mai.',
    errGeneric: 'Không thành công. Thử lại.',
    errFile: 'Không đọc được một tệp. Dùng JPG, PNG, WEBP hoặc video MP4/MOV.',
    errNoBrief: 'Tìm kiếm không thấy chi tiết đáng tin. Hãy tự viết không gian sẽ trông thế nào, hoặc tạo chỉ từ mô tả.',
    errClip: 'Clip thất bại (đã hoàn tín dụng). Thử lại.',
    errClipSlow: 'Clip đang lâu. Nó sẽ xuất hiện trong Thư viện; hãy dựng lại video sau.',
    errSomeClips: 'Có clip chưa xong. Sửa ảnh được đánh dấu rồi dựng lại.',
    errMontage: 'Dựng video thất bại. Thử lại.',
    errMontageSlow: 'Dựng video đang lâu. Thử lại sau vài phút.',
    multiLink: 'Một mặt bằng, nhiều mô hình kinh doanh →',
    multiTitle: 'Một mặt bằng, nhiều mô hình kinh doanh',
    multiSub: 'Cho thấy cùng một mặt bằng trống thành 2–4 mô hình kinh doanh khác nhau trong một video trước → sau, mỗi mô hình có tên trên màn hình.',
    multiS1Hint: 'Một ảnh dọc của mặt bằng trống, hoặc một video — chúng tôi lấy một khung hình.',
    multiS2Title: 'Nó có thể thành mô hình nào?',
    multiS2Hint: 'Từ hai đến {n}. Đặt cho mỗi mô hình một tên ngắn cho video và mô tả bên trong.',
    destLabelPlaceholder: 'Tên trên video (vd: Quán cà phê)',
    addDestination: '+ Thêm mô hình',
    multiTotal: 'Tổng {n} tín dụng — một ảnh hoàn thiện và một clip cho mỗi mô hình',
    backToSingle: '← Quay lại một mô hình mỗi ảnh',
  },
}

/** Texto da chave na língua, com {n} {name} preenchidos. Chave sem tradução cai no inglês, nunca em branco. */
export function spacesCopy(language: InterfaceLanguage | string, key: SpacesCopyKey, vars: Record<string, string | number> = {}): string {
  const dict = language === 'en' ? SPACES_COPY_EN : (SPACES_COPY as Record<string, Dict>)[language]
  const base = dict?.[key] ?? SPACES_COPY_EN[key]
  return base.replace(/\{(n|name)\}/g, (_, k: string) => (vars[k] === undefined ? `{${k}}` : String(vars[k])))
}

/** Rótulos do vídeo na língua de quem gera (a rota de montagem usa isto; língua desconhecida = inglês). */
export function spacesVideoLabels(language: string): { before: string; after: string; presentedBy: string; seal: string } {
  return {
    before: spacesCopy(language, 'before'),
    after: spacesCopy(language, 'after'),
    presentedBy: spacesCopy(language, 'presentedBy'),
    seal: spacesCopy(language, 'seal'),
  }
}
