export const CHECKOUT_AUTH_SESSION_BRIDGE_VERSION = 'checkout_auth_session_bridge_v1'

// `lib/analytics.ts` already owns the opaque session ID. Checkout auth copies
// that same value into a short-lived companion cookie for the OAuth round-trip;
// this adds no second identifier and generic events never rewrite the pin.
export const EVENT_SESSION_COOKIE = 'kineo_event_session_id'
export const CHECKOUT_AUTH_SESSION_COOKIE = 'kineo_checkout_auth_session_id'
export const CHECKOUT_AUTH_SESSION_MAX_AGE_SECONDS = 30 * 60

export type CheckoutAuthSelectionKind = 'automatic' | 'explicit'

/**
 * Accept only the opaque IDs generated by `lib/analytics.ts`. A visitor can
 * edit their own cookie, so never let free-form text reach the events table.
 */
export function normalizeEventSessionId(value: unknown): string | null {
  if (typeof value !== 'string') return null
  const normalized = value.trim()
  if (!/^[A-Za-z0-9][A-Za-z0-9_-]{7,63}$/.test(normalized)) return null
  return normalized
}
