WITH bounds AS (SELECT timestamptz '2026-09-01 06:00:00+00' AS lo,timestamptz '2026-10-01 06:00:00+00' AS hi),
patterns(pat) AS (VALUES ('josephsskaf@gmail.com'),('josephskaf@hotmail.com'),('victoriaskaf96@gmail.com'),('joseph+teste01@gmail.com'),('teste01@shortsforgeai.com'),('josephsskaf+%@gmail.com'),('joseph+%@gmail.com'),('joseph+%'),('victoriaskaf%'),('%@theresanaiforthat.com'),('josephsskaf%'),('josephskaf%'),('%@shortsforgeai.com'),('test%'),('%mailinator%'),('smoketest%')),
people AS (SELECT p.id,p.created_at,coalesce(nullif(trim(p.signup_utm_source),''),nullif(trim(p.utm_source),''),'unknown') source,p.signup_utm_campaign campaign FROM profiles p WHERE NOT EXISTS (SELECT 1 FROM patterns i WHERE lower(trim(coalesce(p.email,''))) LIKE i.pat)),
cohort AS (SELECT p.* FROM people p,bounds b WHERE p.created_at>=b.lo AND p.created_at<b.hi),
ev AS (SELECT e.* FROM events e JOIN people p ON p.id=e.user_id CROSS JOIN bounds b WHERE e.created_at>=b.lo AND e.created_at<b.hi),
video_counts AS (SELECT v.user_id,count(*) n FROM videos v CROSS JOIN bounds b WHERE v.created_at>=b.lo AND v.created_at<b.hi AND v.status='completed' AND coalesce(nullif(v.final_video_url,''),nullif(v.video_url,'')) IS NOT NULL GROUP BY v.user_id),
flags AS (SELECT p.*,
 EXISTS(SELECT 1 FROM ev e WHERE e.user_id=p.id AND e.created_at>=p.created_at AND e.path='/studio' AND nullif(trim(e.session_id),'') IS NOT NULL) observed_studio,
 EXISTS(SELECT 1 FROM ev e WHERE e.user_id=p.id AND e.created_at>=p.created_at AND e.name='generate_page_view' AND nullif(trim(e.session_id),'') IS NOT NULL) create_view,
 EXISTS(SELECT 1 FROM ev e WHERE e.user_id=p.id AND e.created_at>=p.created_at AND e.name='generate_started' AND nullif(trim(e.session_id),'') IS NOT NULL) generated,
 coalesce(v.n,0) videos,
 EXISTS(SELECT 1 FROM ev e WHERE e.user_id=p.id AND e.created_at>=p.created_at AND e.name='checkout_started' AND nullif(trim(e.session_id),'') IS NOT NULL) checkout,
 EXISTS(SELECT 1 FROM ev e WHERE e.user_id=p.id AND e.created_at>=p.created_at AND e.name='payment_success') paid
 FROM cohort p LEFT JOIN video_counts v ON v.user_id=p.id),
summary AS (SELECT 'cohort_30d' scope,count(*) signup,count(*) FILTER(WHERE observed_studio) studio_observed_lower_bound,count(*) FILTER(WHERE create_view) create_view,count(*) FILTER(WHERE generated) generated,count(*) FILTER(WHERE videos>=1) first_video,count(*) FILTER(WHERE videos>=2) second_video,count(*) FILTER(WHERE checkout) checkout,count(*) FILTER(WHERE paid) paid,count(*) FILTER(WHERE generated AND videos>=1) generated_with_video,count(*) FILTER(WHERE generated AND paid) generated_and_paid,count(*) FILTER(WHERE paid AND videos=0) paid_without_video FROM flags
 UNION ALL SELECT 'cohort_at_least_7d',count(*),count(*) FILTER(WHERE observed_studio),count(*) FILTER(WHERE create_view),count(*) FILTER(WHERE generated),count(*) FILTER(WHERE videos>=1),count(*) FILTER(WHERE videos>=2),count(*) FILTER(WHERE checkout),count(*) FILTER(WHERE paid),count(*) FILTER(WHERE generated AND videos>=1),count(*) FILTER(WHERE generated AND paid),count(*) FILTER(WHERE paid AND videos=0) FROM flags,bounds b WHERE created_at<b.hi-interval '7 days')
SELECT jsonb_build_object('window',jsonb_build_object('start','2026-09-01T06:00:00Z','end_exclusive','2026-10-01T06:00:00Z'),'cohort_summary',(SELECT jsonb_agg(s) FROM summary s),'by_source',(SELECT jsonb_agg(s) FROM (SELECT source,count(*) signups,count(*) FILTER(WHERE generated) generated,count(*) FILTER(WHERE videos>=1) first_video,count(*) FILTER(WHERE checkout) checkout,count(*) FILTER(WHERE paid) paid FROM flags GROUP BY source ORDER BY count(*) DESC) s),'external_window_events',(SELECT jsonb_agg(s) FROM (SELECT name,count(*) events,count(distinct user_id) people,count(distinct user_id) FILTER(WHERE nullif(trim(session_id),'') IS NOT NULL) people_with_session FROM ev WHERE name IN('generate_started','generate_completed','checkout_started','payment_success','studio_tiles_shown') GROUP BY name) s),'video_statuses',(SELECT jsonb_agg(s) FROM (SELECT status,count(*) videos FROM videos,bounds b WHERE created_at>=b.lo AND created_at<b.hi GROUP BY status) s)) AS measurement;
