import type { InterfaceLanguage } from '@/lib/ui/interfaceLanguage'

// All authored showcase copy, including media captions and accessible controls.
// Engine/product names are proper names; the clips keep their original embedded captions.
const en = {
  showcase: 'Showcase',
  headline: 'Everything here was made on Kineo — from one sentence or a few photos',
  intro: 'For marketing agencies, real estate teams and property developers.',
  start: 'Start free', pricing: 'See pricing',
  films: 'Films', images: 'Images', spaces: 'Spaces', ads: 'Ads',
  filmsDesc: 'An idea becomes a film. Explore stories, atmosphere and a different engine behind every look.',
  imagesDesc: 'Campaign images from a few words. Give your next brief a visual direction.',
  spacesDesc: 'From an empty floor to a place people can imagine. Explore the same space, redesigned.',
  adsDesc: 'One product. Three looks. See how a single idea can become a campaign.',
  filmsCta: 'Create in Studio', imagesCta: 'Create images', spacesCta: 'Transform a space', adsCta: 'Create an ad',
  made: 'Made with', before: 'Before', after: 'After',
  play: 'Play preview', pause: 'Pause preview', reveal: 'Reveal transformation',
  preview: 'Preview', house: 'Made on Kineo',
  closing: 'Your next client project starts with an idea.',
  castle: 'The castle hidden inside a university', storm: 'Storm over Lake Maracaibo',
  dyatlov: 'The Dyatlov Pass incident', vanished: 'The man who jumped and vanished',
  gulf: 'Something spreading across the Gulf', lake: 'The lake that turns animals to stone',
  perfume: 'Perfume campaign', astronaut: 'Astronaut in a sunflower field', lighthouse: 'Lighthouse in the storm',
  cafe: 'Empty floor → coffee shop', store: 'Empty floor → sneaker store', coworking: 'Empty floor → coworking',
  bottle: 'Water bottle · 3 looks', headphones: 'Headphones · 3 looks', sneakers: 'Sneakers · 3 looks',
  skip: 'Skip to portfolio',
} as const
export type ShowcaseCopy = { [K in keyof typeof en]: string }
const keys = Object.keys(en) as (keyof ShowcaseCopy)[]

// Positional rows are checked against the complete English key list by the guardian.
const rows: Record<Exclude<InterfaceLanguage, 'en'>, string> = {
  pt: 'Portfólio|Tudo aqui foi feito na Kineo — a partir de uma frase ou algumas fotos|Para agências de marketing, imobiliárias e construtoras.|Começar grátis|Ver preços|Filmes|Imagens|Espaços|Anúncios|Uma ideia vira filme. Explore histórias, atmosferas e o motor por trás de cada visual.|Imagens de campanha a partir de poucas palavras. Dê uma direção visual ao próximo briefing.|De um andar vazio a um lugar que as pessoas conseguem imaginar. Veja o mesmo espaço transformado.|Um produto. Três visuais. Veja uma ideia se transformar em campanha.|Criar no Studio|Criar imagens|Transformar um espaço|Criar um anúncio|Feito com|Antes|Depois|Reproduzir prévia|Pausar prévia|Revelar transformação|Prévia|Feito na Kineo|O próximo projeto do seu cliente começa com uma ideia.|O castelo escondido dentro de uma universidade|Tempestade no Lago Maracaibo|O incidente do Passo Dyatlov|O homem que saltou e desapareceu|Algo se espalha pelo Golfo|O lago que transforma animais em pedra|Campanha de perfume|Astronauta em um campo de girassóis|Farol na tempestade|Andar vazio → cafeteria|Andar vazio → loja de tênis|Andar vazio → coworking|Garrafa de água · 3 visuais|Fones de ouvido · 3 visuais|Tênis · 3 visuais|Ir para o portfólio',
  es: 'Portafolio|Todo aquí se hizo en Kineo — a partir de una frase o unas fotos|Para agencias de marketing, inmobiliarias y promotoras.|Empezar gratis|Ver precios|Películas|Imágenes|Espacios|Anuncios|Una idea se convierte en película. Explora historias, atmósferas y el motor detrás de cada estilo.|Imágenes de campaña con pocas palabras. Dale una dirección visual a tu próximo proyecto.|De una planta vacía a un lugar que puedes imaginar. Explora el mismo espacio transformado.|Un producto. Tres estilos. Mira cómo una idea se convierte en campaña.|Crear en Studio|Crear imágenes|Transformar un espacio|Crear un anuncio|Hecho con|Antes|Después|Reproducir vista previa|Pausar vista previa|Revelar transformación|Vista previa|Hecho en Kineo|El próximo proyecto de tu cliente empieza con una idea.|El castillo escondido en una universidad|Tormenta sobre el lago Maracaibo|El incidente del paso Dyatlov|El hombre que saltó y desapareció|Algo se extiende por el Golfo|El lago que convierte animales en piedra|Campaña de perfume|Astronauta en un campo de girasoles|Faro en la tormenta|Planta vacía → cafetería|Planta vacía → tienda de zapatillas|Planta vacía → coworking|Botella de agua · 3 estilos|Auriculares · 3 estilos|Zapatillas · 3 estilos|Ir al portafolio',
  fr: 'Portfolio|Tout ici a été créé sur Kineo — à partir d’une phrase ou de quelques photos|Pour les agences marketing, immobilières et les promoteurs.|Commencer gratuitement|Voir les tarifs|Films|Images|Espaces|Publicités|Une idée devient un film. Explorez des récits, des ambiances et le moteur derrière chaque style.|Des images de campagne en quelques mots. Donnez une direction visuelle à votre prochain brief.|D’un plateau vide à un lieu que l’on peut imaginer. Découvrez le même espace réinventé.|Un produit. Trois styles. Voyez une idée devenir une campagne.|Créer dans Studio|Créer des images|Transformer un espace|Créer une publicité|Créé avec|Avant|Après|Lire l’aperçu|Mettre en pause|Révéler la transformation|Aperçu|Créé sur Kineo|Le prochain projet de votre client commence par une idée.|Le château caché dans une université|Tempête sur le lac Maracaibo|L’incident du col Dyatlov|L’homme qui a sauté et disparu|Quelque chose se répand dans le Golfe|Le lac qui pétrifie les animaux|Campagne de parfum|Astronaute dans un champ de tournesols|Phare dans la tempête|Plateau vide → café|Plateau vide → magasin de baskets|Plateau vide → coworking|Bouteille d’eau · 3 styles|Casque audio · 3 styles|Baskets · 3 styles|Aller au portfolio',
  de: 'Portfolio|Alles hier wurde mit Kineo erstellt — aus einem Satz oder ein paar Fotos|Für Marketingagenturen, Immobilienbüros und Bauträger.|Kostenlos starten|Preise ansehen|Filme|Bilder|Räume|Werbung|Aus einer Idee wird ein Film. Entdecke Geschichten, Stimmungen und die Engine hinter jedem Look.|Kampagnenbilder aus wenigen Worten. Gib deinem nächsten Briefing eine visuelle Richtung.|Von einer leeren Etage zu einem Ort voller Möglichkeiten. Entdecke denselben Raum neu gestaltet.|Ein Produkt. Drei Looks. Sieh, wie aus einer Idee eine Kampagne wird.|In Studio erstellen|Bilder erstellen|Raum verwandeln|Werbung erstellen|Erstellt mit|Vorher|Nachher|Vorschau abspielen|Vorschau pausieren|Verwandlung zeigen|Vorschau|Mit Kineo erstellt|Das nächste Kundenprojekt beginnt mit einer Idee.|Das Schloss in einer Universität|Sturm über dem Maracaibo-See|Das Unglück am Djatlow-Pass|Der Mann, der sprang und verschwand|Etwas breitet sich im Golf aus|Der See, der Tiere versteinert|Parfümkampagne|Astronaut im Sonnenblumenfeld|Leuchtturm im Sturm|Leere Etage → Café|Leere Etage → Sneakerladen|Leere Etage → Coworking|Wasserflasche · 3 Looks|Kopfhörer · 3 Looks|Sneaker · 3 Looks|Zum Portfolio',
  it: 'Portfolio|Tutto qui è stato creato su Kineo — da una frase o poche foto|Per agenzie di marketing, immobiliari e imprese edili.|Inizia gratis|Vedi i prezzi|Film|Immagini|Spazi|Annunci|Un’idea diventa un film. Esplora storie, atmosfere e il motore dietro ogni stile.|Immagini per campagne da poche parole. Dai una direzione visiva al prossimo brief.|Da un piano vuoto a un luogo da immaginare. Esplora lo stesso spazio trasformato.|Un prodotto. Tre stili. Guarda un’idea diventare una campagna.|Crea in Studio|Crea immagini|Trasforma uno spazio|Crea un annuncio|Creato con|Prima|Dopo|Riproduci anteprima|Pausa anteprima|Mostra trasformazione|Anteprima|Creato su Kineo|Il prossimo progetto del tuo cliente inizia da un’idea.|Il castello nascosto in un’università|Tempesta sul lago Maracaibo|L’incidente del passo Djatlov|L’uomo che saltò e scomparve|Qualcosa si diffonde nel Golfo|Il lago che pietrifica gli animali|Campagna di profumo|Astronauta in un campo di girasoli|Faro nella tempesta|Piano vuoto → caffetteria|Piano vuoto → negozio di sneakers|Piano vuoto → coworking|Borraccia · 3 stili|Cuffie · 3 stili|Sneakers · 3 stili|Vai al portfolio',
  nl: 'Portfolio|Alles hier is gemaakt met Kineo — vanuit één zin of een paar foto’s|Voor marketingbureaus, makelaars en projectontwikkelaars.|Gratis beginnen|Bekijk prijzen|Films|Afbeeldingen|Ruimtes|Advertenties|Een idee wordt een film. Ontdek verhalen, sfeer en de engine achter elke stijl.|Campagnebeelden vanuit een paar woorden. Geef je volgende briefing een visuele richting.|Van een lege verdieping naar een plek die je voor je ziet. Ontdek dezelfde ruimte, opnieuw ingericht.|Eén product. Drie stijlen. Zie hoe een idee een campagne wordt.|Maken in Studio|Afbeeldingen maken|Een ruimte transformeren|Een advertentie maken|Gemaakt met|Voor|Na|Voorbeeld afspelen|Voorbeeld pauzeren|Transformatie tonen|Voorbeeld|Gemaakt met Kineo|Het volgende klantproject begint met een idee.|Het kasteel verborgen in een universiteit|Storm boven het Maracaibomeer|Het incident bij de Djatlovpas|De man die sprong en verdween|Er verspreidt zich iets over de Golf|Het meer dat dieren versteent|Parfumcampagne|Astronaut in een zonnebloemenveld|Vuurtoren in de storm|Lege verdieping → café|Lege verdieping → sneakerwinkel|Lege verdieping → coworking|Waterfles · 3 stijlen|Koptelefoon · 3 stijlen|Sneakers · 3 stijlen|Naar het portfolio',
  pl: 'Portfolio|Wszystko powstało w Kineo — z jednego zdania lub kilku zdjęć|Dla agencji marketingowych, biur nieruchomości i deweloperów.|Zacznij za darmo|Zobacz ceny|Filmy|Obrazy|Przestrzenie|Reklamy|Pomysł staje się filmem. Odkryj historie, atmosferę i silnik stojący za każdym stylem.|Obrazy do kampanii z kilku słów. Nadaj kolejnemu briefowi kierunek wizualny.|Od pustego piętra do miejsca, które można sobie wyobrazić. Odkryj tę samą przestrzeń po zmianie.|Jeden produkt. Trzy style. Zobacz, jak pomysł zmienia się w kampanię.|Twórz w Studio|Twórz obrazy|Zmień przestrzeń|Stwórz reklamę|Utworzono za pomocą|Przed|Po|Odtwórz podgląd|Wstrzymaj podgląd|Pokaż przemianę|Podgląd|Stworzono w Kineo|Kolejny projekt klienta zaczyna się od pomysłu.|Zamek ukryty w uniwersytecie|Burza nad jeziorem Maracaibo|Incydent na Przełęczy Diatłowa|Człowiek, który skoczył i zniknął|Coś rozprzestrzenia się po Zatoce|Jezioro, które zamienia zwierzęta w kamień|Kampania perfum|Astronauta na polu słoneczników|Latarnia morska podczas burzy|Puste piętro → kawiarnia|Puste piętro → sklep z butami|Puste piętro → coworking|Butelka wody · 3 style|Słuchawki · 3 style|Buty · 3 style|Przejdź do portfolio',
  tr: 'Portfolyo|Buradaki her şey Kineo’da üretildi — tek bir cümleden veya birkaç fotoğraftan|Pazarlama ajansları, emlak ofisleri ve inşaat şirketleri için.|Ücretsiz başla|Fiyatları gör|Filmler|Görseller|Mekânlar|Reklamlar|Bir fikir filme dönüşür. Hikâyeleri, atmosferi ve her görünümün arkasındaki motoru keşfedin.|Birkaç kelimeden kampanya görselleri. Sonraki projenize görsel bir yön verin.|Boş bir kattan hayal edilebilen bir mekâna. Aynı alanın dönüşümünü keşfedin.|Bir ürün. Üç görünüm. Bir fikrin kampanyaya dönüşmesini izleyin.|Studio’da oluştur|Görsel oluştur|Bir mekânı dönüştür|Reklam oluştur|Kullanılan motor|Önce|Sonra|Önizlemeyi oynat|Önizlemeyi duraklat|Dönüşümü göster|Önizleme|Kineo’da üretildi|Müşterinizin sonraki projesi bir fikirle başlar.|Üniversitenin içindeki gizli kale|Maracaibo Gölü üzerinde fırtına|Dyatlov Geçidi olayı|Atlayıp kaybolan adam|Körfeze yayılan bir şey|Hayvanları taşa çeviren göl|Parfüm kampanyası|Ayçiçeği tarlasında astronot|Fırtınada deniz feneri|Boş kat → kafe|Boş kat → spor ayakkabı mağazası|Boş kat → ortak çalışma alanı|Su şişesi · 3 görünüm|Kulaklık · 3 görünüm|Spor ayakkabı · 3 görünüm|Portfolyoya geç',
  ru: 'Портфолио|Всё здесь создано в Kineo — из одного предложения или нескольких фото|Для маркетинговых агентств, риелторов и застройщиков.|Начать бесплатно|Посмотреть цены|Фильмы|Изображения|Пространства|Реклама|Идея становится фильмом. Откройте истории, атмосферу и модель за каждым визуальным стилем.|Изображения для кампаний из нескольких слов. Задайте визуальное направление новому брифу.|От пустого этажа к месту, которое легко представить. Посмотрите на то же пространство после преображения.|Один товар. Три образа. Посмотрите, как идея становится кампанией.|Создать в Studio|Создать изображения|Преобразить пространство|Создать рекламу|Создано с помощью|До|После|Воспроизвести превью|Приостановить превью|Показать преображение|Превью|Создано в Kineo|Следующий проект клиента начинается с идеи.|Замок, скрытый внутри университета|Буря над озером Маракайбо|Трагедия на перевале Дятлова|Человек, который прыгнул и исчез|Что-то распространяется по заливу|Озеро, превращающее животных в камень|Реклама парфюма|Астронавт в поле подсолнухов|Маяк во время бури|Пустой этаж → кофейня|Пустой этаж → магазин кроссовок|Пустой этаж → коворкинг|Бутылка воды · 3 образа|Наушники · 3 образа|Кроссовки · 3 образа|Перейти к портфолио',
  uk: 'Портфоліо|Усе тут створено в Kineo — з одного речення або кількох фото|Для маркетингових агенцій, рієлторів і забудовників.|Почати безкоштовно|Переглянути ціни|Фільми|Зображення|Простори|Реклама|Ідея стає фільмом. Відкрийте історії, атмосферу та модель за кожним візуальним стилем.|Зображення для кампаній із кількох слів. Задайте візуальний напрям новому брифу.|Від порожнього поверху до місця, яке легко уявити. Побачте той самий простір після перетворення.|Один товар. Три образи. Побачте, як ідея стає кампанією.|Створити в Studio|Створити зображення|Перетворити простір|Створити рекламу|Створено за допомогою|До|Після|Відтворити прев’ю|Призупинити прев’ю|Показати перетворення|Прев’ю|Створено в Kineo|Наступний проєкт клієнта починається з ідеї.|Замок, прихований в університеті|Буря над озером Маракайбо|Трагедія на перевалі Дятлова|Чоловік, який стрибнув і зник|Щось поширюється затокою|Озеро, що перетворює тварин на камінь|Кампанія парфумів|Астронавт у полі соняшників|Маяк під час бурі|Порожній поверх → кав’ярня|Порожній поверх → магазин кросівок|Порожній поверх → коворкінг|Пляшка води · 3 образи|Навушники · 3 образи|Кросівки · 3 образи|Перейти до портфоліо',
  ar: 'معرض الأعمال|كل ما هنا صُنع على Kineo — من جملة واحدة أو بضع صور|لوكالات التسويق والوكالات العقارية وشركات التطوير العقاري.|ابدأ مجانًا|عرض الأسعار|أفلام|صور|مساحات|إعلانات|تتحول الفكرة إلى فيلم. استكشف القصص والأجواء والنموذج وراء كل أسلوب.|صور للحملات من بضع كلمات. امنح مشروعك القادم اتجاهًا بصريًا.|من طابق فارغ إلى مكان يمكن تخيله. استكشف المساحة نفسها بتصميم جديد.|منتج واحد. ثلاثة أساليب. شاهد كيف تتحول الفكرة إلى حملة.|أنشئ في Studio|أنشئ صورًا|حوّل مساحة|أنشئ إعلانًا|صُنع باستخدام|قبل|بعد|تشغيل المعاينة|إيقاف المعاينة مؤقتًا|إظهار التحول|معاينة|صُنع على Kineo|مشروع عميلك القادم يبدأ بفكرة.|القلعة المخفية داخل جامعة|عاصفة فوق بحيرة ماراكايبو|حادثة ممر دياتلوف|الرجل الذي قفز واختفى|شيء ينتشر عبر الخليج|البحيرة التي تحوّل الحيوانات إلى حجر|حملة عطر|رائد فضاء في حقل عباد الشمس|منارة وسط العاصفة|طابق فارغ ← مقهى|طابق فارغ ← متجر أحذية رياضية|طابق فارغ ← مساحة عمل مشتركة|زجاجة ماء · ثلاثة أساليب|سماعات · ثلاثة أساليب|أحذية رياضية · ثلاثة أساليب|انتقل إلى معرض الأعمال',
  ur: 'پورٹ فولیو|یہاں سب کچھ Kineo پر بنا ہے — ایک جملے یا چند تصاویر سے|مارکیٹنگ ایجنسیوں، رئیل اسٹیٹ ٹیموں اور تعمیراتی کمپنیوں کے لیے۔|مفت شروع کریں|قیمتیں دیکھیں|فلمیں|تصاویر|جگہیں|اشتہارات|ایک خیال فلم بن جاتا ہے۔ کہانیوں، ماحول اور ہر انداز کے پیچھے ماڈل کو دیکھیں۔|چند الفاظ سے مہم کی تصاویر۔ اپنے اگلے منصوبے کو بصری سمت دیں۔|خالی منزل سے ایک ایسی جگہ تک جس کا تصور کیا جا سکے۔ اسی جگہ کا نیا روپ دیکھیں۔|ایک پروڈکٹ۔ تین انداز۔ دیکھیں ایک خیال کیسے مہم بن جاتا ہے۔|Studio میں بنائیں|تصاویر بنائیں|جگہ تبدیل کریں|اشتہار بنائیں|اس سے بنایا گیا|پہلے|بعد|پیش نظارہ چلائیں|پیش نظارہ روکیں|تبدیلی دکھائیں|پیش نظارہ|Kineo پر بنایا گیا|آپ کے کلائنٹ کا اگلا منصوبہ ایک خیال سے شروع ہوتا ہے۔|یونیورسٹی کے اندر چھپا قلعہ|ماراکائیبو جھیل پر طوفان|دیاتلوف پاس کا واقعہ|وہ شخص جو کود کر غائب ہو گیا|خلیج میں کچھ پھیل رہا ہے|جانوروں کو پتھر بنانے والی جھیل|پرفیوم کی مہم|سورج مکھی کے کھیت میں خلا باز|طوفان میں مینارۂ نور|خالی منزل ← کافی شاپ|خالی منزل ← جوتوں کی دکان|خالی منزل ← مشترکہ کام کی جگہ|پانی کی بوتل · تین انداز|ہیڈ فون · تین انداز|جوتے · تین انداز|پورٹ فولیو پر جائیں',
  hi: 'पोर्टफ़ोलियो|यहाँ सब कुछ Kineo पर बना है — एक वाक्य या कुछ तस्वीरों से|मार्केटिंग एजेंसियों, रियल एस्टेट टीमों और बिल्डरों के लिए।|मुफ़्त शुरू करें|कीमतें देखें|फ़िल्में|तस्वीरें|जगहें|विज्ञापन|एक विचार फ़िल्म बनता है। कहानियाँ, माहौल और हर शैली के पीछे का मॉडल देखें।|कुछ शब्दों से अभियान की तस्वीरें। अपने अगले ब्रीफ़ को एक दृश्य दिशा दें।|खाली फ़्लोर से एक ऐसी जगह तक जिसकी कल्पना की जा सके। उसी जगह का नया रूप देखें।|एक उत्पाद। तीन अंदाज़। देखें एक विचार कैसे अभियान बनता है।|Studio में बनाएँ|तस्वीरें बनाएँ|जगह बदलें|विज्ञापन बनाएँ|इससे बनाया गया|पहले|बाद में|प्रीव्यू चलाएँ|प्रीव्यू रोकें|बदलाव दिखाएँ|प्रीव्यू|Kineo पर बनाया गया|आपके ग्राहक का अगला प्रोजेक्ट एक विचार से शुरू होता है।|विश्वविद्यालय में छिपा महल|माराकाइबो झील पर तूफ़ान|डायटलोव दर्रे की घटना|वह आदमी जो कूदा और गायब हो गया|खाड़ी में कुछ फैल रहा है|जानवरों को पत्थर बनाने वाली झील|परफ़्यूम अभियान|सूरजमुखी के खेत में अंतरिक्ष यात्री|तूफ़ान में प्रकाशस्तंभ|खाली फ़्लोर → कैफ़े|खाली फ़्लोर → जूतों की दुकान|खाली फ़्लोर → साझा कार्यस्थल|पानी की बोतल · 3 अंदाज़|हेडफ़ोन · 3 अंदाज़|जूते · 3 अंदाज़|पोर्टफ़ोलियो पर जाएँ',
  id: 'Portofolio|Semua di sini dibuat di Kineo — dari satu kalimat atau beberapa foto|Untuk agensi pemasaran, tim properti, dan pengembang.|Mulai gratis|Lihat harga|Film|Gambar|Ruang|Iklan|Ide menjadi film. Jelajahi cerita, suasana, dan mesin di balik setiap tampilan.|Gambar kampanye dari beberapa kata. Beri arahan visual untuk proyek berikutnya.|Dari lantai kosong menjadi tempat yang bisa dibayangkan. Jelajahi ruang yang sama, didesain ulang.|Satu produk. Tiga tampilan. Lihat ide menjadi kampanye.|Buat di Studio|Buat gambar|Ubah ruang|Buat iklan|Dibuat dengan|Sebelum|Sesudah|Putar pratinjau|Jeda pratinjau|Tampilkan perubahan|Pratinjau|Dibuat di Kineo|Proyek klien berikutnya dimulai dari sebuah ide.|Kastel tersembunyi di dalam universitas|Badai di Danau Maracaibo|Insiden Celah Dyatlov|Pria yang melompat lalu menghilang|Sesuatu menyebar di Teluk|Danau yang mengubah hewan menjadi batu|Kampanye parfum|Astronaut di ladang bunga matahari|Mercusuar di tengah badai|Lantai kosong → kedai kopi|Lantai kosong → toko sepatu|Lantai kosong → ruang kerja bersama|Botol air · 3 tampilan|Headphone · 3 tampilan|Sepatu · 3 tampilan|Ke portofolio',
  vi: 'Hồ sơ tác phẩm|Mọi thứ ở đây đều được tạo trên Kineo — từ một câu hoặc vài bức ảnh|Dành cho công ty marketing, môi giới bất động sản và chủ đầu tư.|Bắt đầu miễn phí|Xem giá|Phim|Hình ảnh|Không gian|Quảng cáo|Ý tưởng trở thành phim. Khám phá câu chuyện, bầu không khí và mô hình đằng sau mỗi phong cách.|Hình ảnh chiến dịch từ vài từ. Định hướng hình ảnh cho bản yêu cầu tiếp theo.|Từ tầng trống đến nơi có thể hình dung. Khám phá cùng một không gian với thiết kế mới.|Một sản phẩm. Ba phong cách. Xem ý tưởng trở thành chiến dịch.|Tạo trong Studio|Tạo hình ảnh|Biến đổi không gian|Tạo quảng cáo|Được tạo bằng|Trước|Sau|Phát bản xem trước|Tạm dừng bản xem trước|Hiện sự biến đổi|Xem trước|Được tạo trên Kineo|Dự án tiếp theo của khách hàng bắt đầu từ một ý tưởng.|Lâu đài ẩn trong trường đại học|Bão trên hồ Maracaibo|Sự cố đèo Dyatlov|Người đàn ông nhảy rồi biến mất|Thứ gì đó đang lan khắp vùng Vịnh|Hồ biến động vật thành đá|Chiến dịch nước hoa|Phi hành gia giữa cánh đồng hướng dương|Hải đăng trong bão|Tầng trống → quán cà phê|Tầng trống → cửa hàng giày|Tầng trống → không gian làm việc chung|Chai nước · 3 phong cách|Tai nghe · 3 phong cách|Giày · 3 phong cách|Đến hồ sơ tác phẩm',
}

export const SHOWCASE_COPY = { en, ...Object.fromEntries(Object.entries(rows).map(([language, row]) => {
  const values = row.split('|')
  if (values.length !== keys.length || values.some(value => !value.trim())) throw new Error(`Incomplete showcase copy: ${language}`)
  return [language, Object.fromEntries(keys.map((key, i) => [key, values[i]]))]
})) } as Record<InterfaceLanguage, ShowcaseCopy>

export const SHOWCASE_CAPTIONS = {
  films: ['castle', 'storm', 'dyatlov', 'vanished', 'gulf', 'lake'],
  images: ['perfume', 'astronaut', 'lighthouse'],
  spaces: ['cafe', 'store', 'coworking'],
  ads: ['bottle', 'headphones', 'sneakers'],
} as const satisfies Record<string, readonly (keyof ShowcaseCopy)[]>
