// ═══ KINEO-MODELS-PRICING-2026-09-02 ═══════════════════════════════════════
// A página pública de custo por motor. Nasce de uma auditoria de nove
// concorrentes (02/09) com uma conclusão nítida: quem tem MUITOS motores
// publica a tabela e mostra o número antes do clique — a Higgsfield lista ~70
// modelos em `créditos/5s` e imprime o custo dentro do botão Generate; a Runway
// mantém academy.runwayml.com/models-pricing com `12/sec`, `5/sec`, aberto e
// sem login. Quem esconde (Canva, InVideo, Luma) tem 3 tiers de qualidade, não
// 8 motores. Nós tínhamos o perfil do primeiro grupo e a comunicação do
// segundo — e nenhuma página de preço por motor.
//
// A UNIDADE É O FILME, NÃO O CLIPE DE 5 SEGUNDOS. Esse é o buraco que o
// mercado inteiro deixou aberto: todos precificam 5s/8s isolados e devolvem a
// aritmética para o usuário. Aqui a linha diz o que a pessoa realmente compra —
// um filme de 35s, 60s ou 90s, com voz, legenda karaokê e trilha inclusas.
import type { Metadata } from 'next'
import Link from 'next/link'
import { creditCostForDuration, type Quality } from '@/lib/credits/engineCost'
// Preço e créditos vêm da MESMA fonte que a Stripe cobra (lib/marketingPrice
// deriva de checkoutPricing) — um reprice chega aqui sozinho.
import { STARTER_CREDITS, STARTER_USD_AMOUNT } from '@/lib/marketingPrice'
import { S25_PUBLIC } from '@/lib/engineLaunch'
import { ENGINE_LANDING_PUBLIC_PATHS } from '@/lib/growth/engineLandingIntent'

export const metadata: Metadata = {
  title: 'AI video model pricing — credits per film | Kineo',
  description:
    'What every AI video engine costs on Kineo, in credits per finished film (35s, 60s, 90s) — Kineo 1, Seedance 1.5, Kling 2.5, Kling 3, Veo 3.1, MiniMax H3, Omni Flash. Voice, captions and score included. Failed renders are refunded.',
  alternates: { canonical: 'https://www.usekineo.com/models-pricing' },
  openGraph: {
    title: 'AI video model pricing — credits per film',
    description:
      'Every engine, every length, priced per finished film instead of per 5-second clip.',
    url: 'https://www.usekineo.com/models-pricing',
    type: 'website',
  },
}

type Row = {
  key: string
  name: string
  quality: Quality
  what: string
  path?: string
}

const ROWS: Row[] = [
  { key: 'fast', name: 'Kineo 1', quality: 'fast', what: 'Our own engine — real footage, cut to your script', path: ENGINE_LANDING_PUBLIC_PATHS.fast },
  { key: 'seedance', name: 'Seedance 1.5', quality: 'cinematic_ai', what: 'Every scene generated by AI', path: ENGINE_LANDING_PUBLIC_PATHS.seedance },
  { key: 'h3', name: 'MiniMax H3', quality: 'cinematic_h3', what: 'Cinematic film with 9-image consistency', path: ENGINE_LANDING_PUBLIC_PATHS.h3 },
  { key: 'kling', name: 'Kling 2.5', quality: 'cinematic_kling', what: 'Cinematic motion and camera work', path: ENGINE_LANDING_PUBLIC_PATHS.kling },
  { key: 'veo', name: 'Veo 3.1', quality: 'cinematic_veo', what: 'Google’s flagship cinematic engine', path: ENGINE_LANDING_PUBLIC_PATHS.veo },
  { key: 'hollywood', name: 'Kling 3', quality: 'cinematic_hollywood', what: 'Film scenes, native voice and lip sync', path: ENGINE_LANDING_PUBLIC_PATHS.hollywood },
  { key: 'omni', name: 'Omni Flash', quality: 'cinematic_omni', what: 'Gemini Omni Flash — #1 ranked, Aug 2026 arena', path: ENGINE_LANDING_PUBLIC_PATHS.omni },
  // O S25 só aparece quando o interruptor único abrir para o público — mostrar
  // preço de motor que ninguém pode escolher é a lição do Seedance 2.0.
  ...(S25_PUBLIC
    ? [{ key: 's25', name: 'Seedance 2.5', quality: 'cinematic_s25' as Quality, what: 'ByteDance’s newest engine — 480p master + HD Enhance', path: ENGINE_LANDING_PUBLIC_PATHS.s25 }]
    : []),
]

const LENGTHS = [35, 60, 90] as const

export default function ModelsPricingPage() {
  const starterCredits = STARTER_CREDITS
  const starterPrice = STARTER_USD_AMOUNT

  return (
    <main style={{ maxWidth: 980, margin: '0 auto', padding: '56px 20px 80px', color: '#e9e9ee' }}>
      <h1 style={{ fontSize: 34, fontWeight: 800, margin: '0 0 12px', letterSpacing: '-0.02em' }}>
        What each AI video engine costs
      </h1>
      <p style={{ fontSize: 17, lineHeight: 1.7, color: '#a9a9b6', margin: '0 0 8px', maxWidth: 720 }}>
        Priced per <strong style={{ color: '#e9e9ee' }}>finished film</strong>, not per 5-second clip — voice,
        karaoke captions and score included in every number below.
      </p>
      <p style={{ fontSize: 15, lineHeight: 1.7, color: '#a9a9b6', margin: '0 0 32px', maxWidth: 720 }}>
        Your free trial starts with <strong style={{ color: '#e9e9ee' }}>25 credits</strong>. On Kineo 1 that is
        twelve films; on the biggest engines it is part of one. Both are fine — just know which one you picked.
      </p>

      <div style={{ overflowX: 'auto', border: '1px solid rgba(255,255,255,.12)', borderRadius: 14 }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 15, minWidth: 640 }}>
          <thead>
            <tr style={{ background: 'rgba(255,255,255,.04)' }}>
              <th style={{ textAlign: 'left', padding: '14px 16px', fontWeight: 700 }}>Engine</th>
              {LENGTHS.map((s) => (
                <th key={s} style={{ textAlign: 'right', padding: '14px 16px', fontWeight: 700, whiteSpace: 'nowrap' }}>
                  {s}s film
                </th>
              ))}
              <th style={{ textAlign: 'right', padding: '14px 16px', fontWeight: 700, whiteSpace: 'nowrap' }}>
                Films from 25 free credits
              </th>
            </tr>
          </thead>
          <tbody>
            {ROWS.map((r) => {
              const c60 = creditCostForDuration(r.quality, true, 60)
              const free = c60 > 0 ? Math.floor(25 / c60) : 0
              return (
                <tr key={r.key} style={{ borderTop: '1px solid rgba(255,255,255,.08)' }}>
                  <td style={{ padding: '14px 16px' }}>
                    <div style={{ fontWeight: 700 }}>
                      {r.path ? (
                        <Link href={r.path} style={{ color: '#5cb3ff', textDecoration: 'none' }}>
                          {r.name}
                        </Link>
                      ) : (
                        r.name
                      )}
                    </div>
                    <div style={{ color: '#8f8f9c', fontSize: 13.5, marginTop: 2 }}>{r.what}</div>
                  </td>
                  {LENGTHS.map((s) => (
                    <td key={s} style={{ padding: '14px 16px', textAlign: 'right', whiteSpace: 'nowrap' }}>
                      {creditCostForDuration(r.quality, true, s)} cr
                    </td>
                  ))}
                  <td style={{ padding: '14px 16px', textAlign: 'right', whiteSpace: 'nowrap', color: free >= 1 ? '#7ee2a8' : '#8f8f9c' }}>
                    {free >= 1 ? `${free} film${free === 1 ? '' : 's'}` : 'part of one'}
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>

      <p style={{ fontSize: 14, lineHeight: 1.7, color: '#8f8f9c', margin: '16px 0 40px' }}>
        A 35-second film costs about 60% of the 60-second price and a 90-second film about 150% — the same
        function that prints these numbers is the one that charges your account, so the screen and the invoice
        can never disagree. <strong style={{ color: '#e9e9ee' }}>If a render fails, the credits come straight
        back.</strong>
      </p>

      <h2 style={{ fontSize: 22, fontWeight: 800, margin: '0 0 12px' }}>How credits turn into money</h2>
      <p style={{ fontSize: 16, lineHeight: 1.7, color: '#a9a9b6', margin: '0 0 28px', maxWidth: 720 }}>
        The Starter plan is ${starterPrice}/month for {starterCredits} credits — {Math.floor(starterCredits / creditCostForDuration('fast', true, 60))} films
        on Kineo 1, or {Math.floor(starterCredits / creditCostForDuration('cinematic_ai', true, 60))} on Seedance 1.5.
        See every plan on the <Link href="/pricing" style={{ color: '#5cb3ff' }}>pricing page</Link>, or start
        free in the <Link href="/studio" style={{ color: '#5cb3ff' }}>studio</Link>.
      </p>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'FAQPage',
            mainEntity: [
              {
                '@type': 'Question',
                name: 'How much does one AI video cost on Kineo?',
                acceptedAnswer: {
                  '@type': 'Answer',
                  text: `A 60-second film costs ${creditCostForDuration('fast', true, 60)} credits on Kineo 1 and ${creditCostForDuration('cinematic_ai', true, 60)} credits on Seedance 1.5, with voice, captions and score included. The free trial gives 25 credits.`,
                },
              },
              {
                '@type': 'Question',
                name: 'What happens to my credits if a render fails?',
                acceptedAnswer: {
                  '@type': 'Answer',
                  text: 'They are returned automatically. A failed render never costs credits on Kineo.',
                },
              },
              {
                '@type': 'Question',
                name: 'Is the price per clip or per finished video?',
                acceptedAnswer: {
                  '@type': 'Answer',
                  text: 'Per finished video. Most AI video tools quote a price per 5-second clip; Kineo prices the whole film, including narration, karaoke captions and soundtrack.',
                },
              },
            ],
          }),
        }}
      />
    </main>
  )
}
