// KINEO-DATA-PR-2026-07-24 (PUSH #87) — "State of AI Shorts 2026" study.
// Data-driven PR asset: original numbers from Kineo's own production database,
// published as a citable, dated study. Built to earn backlinks and press
// mentions — journalists and bloggers cite pages with original data, not
// feature pages. Every figure below was pulled from the live database on
// July 24, 2026 (methodology at the bottom). Anonymous aggregates only.

import type { Metadata } from 'next'

export const dynamic = 'force-static'

const PUBLISHED = 'July 24, 2026'

export const metadata: Metadata = {
  title: 'State of AI Shorts 2026 — Original Data from 568 AI-Generated Videos',
  description:
    'What 206 real creators generated with AI in 2026: the most in-demand faceless niches, engine choices, growth curve and completion rates. Original platform data, free to cite.',
  alternates: { canonical: 'https://www.usekineo.com/state-of-ai-shorts-2026' },
  openGraph: {
    title: 'State of AI Shorts 2026 — Original Platform Data',
    description:
      'The most in-demand faceless niches, engine mix and growth curve, from 568 real AI-generated Shorts. Free to cite.',
    url: 'https://www.usekineo.com/state-of-ai-shorts-2026',
    type: 'article',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'State of AI Shorts 2026',
    description:
      'Original data from 568 AI-generated Shorts: niche demand, engine mix, growth. Free to cite.',
  },
}

const FINDINGS: { stat: string; label: string; detail: string }[] = [
  {
    stat: '568',
    label: 'AI Shorts generated by real creators',
    detail:
      'Between May 12 and July 24, 2026, 206 distinct creators generated 568 videos on Kineo — an average of 2.8 videos per active creator.',
  },
  {
    stat: '99.3%',
    label: 'render completion rate',
    detail:
      '564 of 568 started renders finished successfully. Failed renders refund credits automatically, so the effective cost of a failure to the creator is zero.',
  },
  {
    stat: '+50%',
    label: 'month-over-month growth in July',
    detail:
      'Monthly volume: 163 videos in May, 161 in June, and 244 in July with a week still remaining — the steepest adoption curve since launch.',
  },
  {
    stat: '48%',
    label: 'of videos use Fast Mode (stock footage)',
    detail:
      '271 of 568 videos used Fast Mode at 1 credit each. Premium AI-scene engines (Seedance, Kling and other cinematic modes) account for roughly one in four videos — creators start cheap and upgrade the winners.',
  },
]

// Keyword-bucketed topic analysis over all 568 video topics/titles.
// Buckets overlap (a "top 5 richest animals" video counts in two), so
// percentages are of mentions, not videos — stated in the methodology.
const NICHE_DEMAND: { niche: string; mentions: number; note: string }[] = [
  { niche: 'Animals & nature', mentions: 185, note: 'The sleeper #1 — low competition, universally watchable' },
  { niche: 'Geography & countries', mentions: 167, note: '"Countries that…" formats dominate' },
  { niche: 'History & empires', mentions: 160, note: 'Rome, Egypt and war stories lead' },
  { niche: 'Finance & money', mentions: 123, note: 'Highest RPM niche in the set' },
  { niche: 'Mystery, crime & horror', mentions: 99, note: 'Strong retention formats' },
  { niche: 'Luxury & cars', mentions: 90, note: 'Aspirational content, strong on TikTok' },
  { niche: 'Facts & curiosities', mentions: 65, note: 'The classic faceless entry point' },
  { niche: 'Space & science', mentions: 51, note: 'Evergreen, zero-decay topics' },
  { niche: 'Motivation & stoicism', mentions: 46, note: 'Saturated — harder to stand out in 2026' },
  { niche: 'Fitness & health', mentions: 12, note: 'Underserved on AI tools today' },
]

const PAGE_BG = '#000'
const CARD = { background: '#161618', border: '1px solid #2a2a2d', borderRadius: 14 }
const ACCENT = '#2997ff'
const MUTED = '#86868b'

export default function StateOfAiShortsPage() {
  const articleJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: 'State of AI Shorts 2026 — Original Data from 568 AI-Generated Videos',
    datePublished: '2026-07-24',
    dateModified: '2026-07-24',
    author: { '@type': 'Organization', name: 'Kineo', url: 'https://www.usekineo.com' },
    publisher: { '@type': 'Organization', name: 'Kineo', url: 'https://www.usekineo.com' },
    mainEntityOfPage: 'https://www.usekineo.com/state-of-ai-shorts-2026',
    description:
      'Original platform data on what creators generate with AI: niche demand ranking, engine mix, growth curve and completion rates from 568 AI-generated YouTube Shorts.',
  }

  return (
    <main
      style={{
        background: PAGE_BG,
        minHeight: '100vh',
        color: '#f5f5f7',
        fontFamily:
          'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        padding: '64px 20px 96px',
      }}
    >
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd).replace(/</g, '\\u003c') }}
      />
      <div style={{ maxWidth: 820, margin: '0 auto' }}>
        <p
          style={{
            color: ACCENT,
            fontWeight: 700,
            fontSize: '0.85rem',
            letterSpacing: '0.08em',
            textTransform: 'uppercase',
            margin: '0 0 12px',
          }}
        >
          Original research — published {PUBLISHED}
        </p>
        <h1 style={{ fontSize: '2.2rem', fontWeight: 800, lineHeight: 1.15, margin: '0 0 16px' }}>
          State of AI Shorts 2026
        </h1>
        <p style={{ color: MUTED, fontSize: '1.08rem', lineHeight: 1.6, margin: '0 0 8px' }}>
          What do people actually make when an AI can turn any idea into a finished
          faceless video? We pulled the numbers from every Short generated on Kineo
          between May 12 and July 24, 2026 — 568 videos by 206 creators — and ranked
          what the data says about niches, engines and growth.
        </p>
        <p style={{ color: MUTED, fontSize: '0.9rem', lineHeight: 1.6, margin: '0 0 40px' }}>
          Free to cite with a link to this page. Anonymous aggregates only — no
          individual creator data.
        </p>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, margin: '0 0 16px' }}>Key findings</h2>
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
            gap: 10,
            margin: '0 0 48px',
          }}
        >
          {FINDINGS.map((f, i) => (
            <section key={i} style={{ ...CARD, padding: '18px 18px' }}>
              <p style={{ color: ACCENT, fontSize: '1.9rem', fontWeight: 800, margin: '0 0 4px' }}>
                {f.stat}
              </p>
              <h3 style={{ fontSize: '0.98rem', fontWeight: 700, margin: '0 0 8px' }}>{f.label}</h3>
              <p style={{ color: '#d2d2d7', fontSize: '0.88rem', lineHeight: 1.55, margin: 0 }}>
                {f.detail}
              </p>
            </section>
          ))}
        </div>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, margin: '0 0 6px' }}>
          The 2026 faceless niche demand ranking
        </h2>
        <p style={{ color: MUTED, fontSize: '0.95rem', lineHeight: 1.6, margin: '0 0 16px' }}>
          Topic mentions across all 568 generated videos, bucketed by keyword. The
          surprise: animals and geography out-demand the &ldquo;classic&rdquo;
          motivation niche by 4×.
        </p>
        <ol style={{ listStyle: 'none', padding: 0, margin: '0 0 48px', display: 'grid', gap: 8 }}>
          {NICHE_DEMAND.map((n, i) => (
            <li
              key={n.niche}
              style={{ ...CARD, padding: '12px 16px', display: 'flex', alignItems: 'center', gap: 14 }}
            >
              <span style={{ color: ACCENT, fontWeight: 800, minWidth: 28 }}>{i + 1}.</span>
              <div style={{ flex: 1 }}>
                <p style={{ fontWeight: 700, fontSize: '0.95rem', margin: 0 }}>{n.niche}</p>
                <p style={{ color: MUTED, fontSize: '0.85rem', margin: '2px 0 0' }}>{n.note}</p>
              </div>
              <div style={{ textAlign: 'right', minWidth: 120 }}>
                <div
                  style={{
                    height: 6,
                    width: `${Math.max(8, Math.round((n.mentions / 185) * 120))}px`,
                    background: ACCENT,
                    borderRadius: 3,
                    marginLeft: 'auto',
                    marginBottom: 4,
                    opacity: 0.85,
                  }}
                />
                <span style={{ color: '#d2d2d7', fontSize: '0.85rem', fontWeight: 600 }}>
                  {n.mentions} mentions
                </span>
              </div>
            </li>
          ))}
        </ol>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, margin: '0 0 16px' }}>
          What this means if you are starting a channel now
        </h2>
        <div style={{ display: 'grid', gap: 10, margin: '0 0 48px' }}>
          <section style={{ ...CARD, padding: '16px 18px' }}>
            <h3 style={{ fontSize: '1rem', fontWeight: 700, margin: '0 0 8px' }}>
              The contrarian pick is animals, not motivation
            </h3>
            <p style={{ color: '#d2d2d7', lineHeight: 1.55, fontSize: '0.95rem', margin: 0 }}>
              Motivation content is what everyone thinks faceless channels make — it
              ranked 9th of 10 in actual demand. Animals, geography and history rank
              1–3: visually rich, endlessly repeatable, and far less saturated.
            </p>
          </section>
          <section style={{ ...CARD, padding: '16px 18px' }}>
            <h3 style={{ fontSize: '1rem', fontWeight: 700, margin: '0 0 8px' }}>
              Creators start cheap and upgrade winners
            </h3>
            <p style={{ color: '#d2d2d7', lineHeight: 1.55, fontSize: '0.95rem', margin: 0 }}>
              Nearly half of all videos use the 1-credit Fast Mode. The winning
              workflow in the data: validate a topic with a cheap render, then re-make
              proven concepts with premium AI scenes.
            </p>
          </section>
          <section style={{ ...CARD, padding: '16px 18px' }}>
            <h3 style={{ fontSize: '1rem', fontWeight: 700, margin: '0 0 8px' }}>
              Reliability is a solved problem
            </h3>
            <p style={{ color: '#d2d2d7', lineHeight: 1.55, fontSize: '0.95rem', margin: 0 }}>
              With a 99.3% completion rate and automatic credit refunds on failure,
              the bottleneck for faceless channels in 2026 is no longer production —
              it is topic selection and consistency.
            </p>
          </section>
        </div>

        <section style={{ ...CARD, padding: '20px 20px', margin: '0 0 48px', borderColor: ACCENT }}>
          <h2 style={{ fontSize: '1.15rem', fontWeight: 700, margin: '0 0 8px' }}>
            Test the data yourself — free
          </h2>
          <p style={{ color: '#d2d2d7', lineHeight: 1.6, fontSize: '0.95rem', margin: '0 0 14px' }}>
            Pick one of the top-3 niches above and generate your first faceless Short
            in about 2–4 minutes. Up to 3 watermarked videos every 24 hours, no card.
          </p>
          <a
            href="https://www.usekineo.com/free-ai-shorts-generator?utm_source=state-of-ai-shorts&utm_medium=study&utm_campaign=acq5"
            style={{
              display: 'inline-block',
              background: ACCENT,
              color: '#000',
              fontWeight: 700,
              padding: '12px 22px',
              borderRadius: 10,
              textDecoration: 'none',
              fontSize: '0.95rem',
            }}
          >
            Generate a free Short →
          </a>
        </section>

        <h2 style={{ fontSize: '1.25rem', fontWeight: 700, margin: '0 0 12px' }}>Methodology</h2>
        <p style={{ color: MUTED, fontSize: '0.9rem', lineHeight: 1.7, margin: '0 0 10px' }}>
          Data covers every video generated on Kineo (usekineo.com) from May 12
          through July 24, 2026: 568 videos by 206 distinct creators. Completion rate
          is finished renders over started renders (564/568). Niche demand is
          keyword-bucket analysis over video topics and titles; buckets can overlap
          (a &ldquo;richest animals&rdquo; video counts in both finance and animals),
          so figures are topic mentions, not exclusive video counts. Engine mix is
          the share of videos per render engine. Separately measured Fast Mode
          delivery speed (seven-day sample ending July 23, 2026): 2.30-minute median,
          3.50-minute p90 — see{' '}
          <a href="/facts" style={{ color: ACCENT, textDecoration: 'none' }}>
            usekineo.com/facts
          </a>
          . Aggregates only; no personal data.
        </p>
        <p style={{ color: MUTED, fontSize: '0.9rem', lineHeight: 1.7 }}>
          Citing this study: &ldquo;State of AI Shorts 2026&rdquo;, Kineo,
          usekineo.com/state-of-ai-shorts-2026, published {PUBLISHED}. Press &amp;
          data questions: hello@usekineo.com.
        </p>
      </div>
    </main>
  )
}
