// KINEO-CLIPES-2026-09-29 — os textos da tela /clips nas 16 línguas da interface (lib/ui/interfaceLanguage.ts).
// A língua vem do MESMO contexto do resto do site (useInterfaceLanguage); o dicionário mora aqui, e não em
// lib/ui/refinementCopy.json, para não disputar o mesmo arquivo com as sessões paralelas de 29/09. Módulo puro: o
// guardião confere que as 16 línguas têm TODAS as chaves e os mesmos marcadores {engine} {s} {n}.
import type { InterfaceLanguage } from '@/lib/ui/interfaceLanguage'

export const CLIP_COPY_EN = {
  title: 'Clips',
  sub: 'One scene, 5 to 15 seconds, no narration. Type it or start from a photo.',
  engine: 'Engine',
  from: 'from {n} cr',
  photoOnly: 'Photo only',
  yourClip: 'Your clip',
  placeholder: 'A drone shot over a stormy sea at dusk, waves crashing on black rocks',
  placeholderMotion: 'Describe the motion (optional) — e.g. slow push-in, hair moving in the wind',
  photo: 'Photo (optional)',
  photoHint: 'Your photo becomes the first frame.',
  addPhoto: 'Add photo',
  removePhoto: 'Remove photo',
  uploading: 'Uploading…',
  length: 'Length',
  format: 'Format',
  vertical: 'Vertical',
  wide: 'Wide',
  square: 'Square',
  samePhoto: 'Same as your photo',
  notLength: '{engine} doesn’t make {s} s clips. These engines do:',
  needsPhoto: '{engine} only starts from a photo. Add a photo or pick another engine.',
  noPhoto: '{engine} can’t start from a photo.',
  cost: 'Cost',
  credits: 'credits',
  generate: 'Generate clip',
  creating: 'Creating…',
  describeFirst: 'Describe your clip or add a photo',
  myClips: 'My clips',
  inProgress: 'In progress — usually 1 to 5 minutes. You can leave this page.',
  failedRefunded: 'Failed — {n} credits refunded.',
  failed: 'Failed.',
  download: 'Download',
  empty: 'No clips yet.',
  loadFailed: 'We couldn’t load your clips right now.',
  tryAgain: 'Try again',
  addCredits: 'Add credits →',
  signIn: 'Sign in →',
  // KINEO-CLIP-EFEITOS-2026-10-05 — galeria de efeitos de 1 clique e upsell para o filme narrado.
  effectsTitle: 'One-click effects',
  effectsSub: 'Pick an effect, add a photo and get a clip in about a minute.',
  previewSoon: 'Preview coming soon',
  madeWith: 'Made with {engine}',
  effectLabel: 'Effect',
  effectPhoto: 'This effect starts from your photo — it becomes the first frame.',
  effectPersonHint: 'Use a photo of yourself or of someone who agreed to it.',
  effectAddPhoto: 'Add a photo to start',
  effectBack: 'Write my own clip instead',
  filmUpsell: 'Turn into a narrated film (60 s)',
  // KINEO-S25-CLIPES-2026-10-06 — card do motor só de planos pagos (as mesmas frases do card do filme do 2.5, codex/s25-abre-0610).
  paidBadge: 'NEW · paid plans',
  paidHint: 'Available on paid plans — see plans',
  seePlans: 'See plans →',
} as const

export type ClipCopyKey = keyof typeof CLIP_COPY_EN
type Dict = Record<ClipCopyKey, string>

export const CLIP_COPY: Record<Exclude<InterfaceLanguage, 'en'>, Dict> = {
  pt: {
    title: 'Clipes',
    sub: 'Uma cena, de 5 a 15 segundos, sem narração. Escreva ou comece de uma foto.',
    engine: 'Motor',
    from: 'a partir de {n} cr',
    photoOnly: 'Só com foto',
    yourClip: 'Seu clipe',
    placeholder: 'Um drone sobre um mar em tempestade ao entardecer, ondas batendo em rochas negras',
    placeholderMotion: 'Descreva o movimento (opcional) — ex.: aproximação lenta, cabelo ao vento',
    photo: 'Foto (opcional)',
    photoHint: 'Sua foto vira o primeiro quadro.',
    addPhoto: 'Adicionar foto',
    removePhoto: 'Remover foto',
    uploading: 'Enviando…',
    length: 'Duração',
    format: 'Formato',
    vertical: 'Vertical',
    wide: 'Horizontal',
    square: 'Quadrado',
    samePhoto: 'O mesmo da sua foto',
    notLength: 'O {engine} não faz clipes de {s} s. Estes motores fazem:',
    needsPhoto: 'O {engine} só começa de uma foto. Adicione uma foto ou escolha outro motor.',
    noPhoto: 'O {engine} não começa de uma foto.',
    cost: 'Custo',
    credits: 'créditos',
    generate: 'Gerar clipe',
    creating: 'Criando…',
    describeFirst: 'Descreva seu clipe ou adicione uma foto',
    myClips: 'Meus clipes',
    inProgress: 'Em andamento — normalmente de 1 a 5 minutos. Você pode sair desta página.',
    failedRefunded: 'Falhou — {n} créditos devolvidos.',
    failed: 'Falhou.',
    download: 'Baixar',
    empty: 'Nenhum clipe ainda.',
    loadFailed: 'Não conseguimos carregar seus clipes agora.',
    tryAgain: 'Tentar de novo',
    addCredits: 'Adicionar créditos →',
    signIn: 'Entrar →',
    effectsTitle: 'Efeitos de 1 clique',
    effectsSub: 'Escolha um efeito, adicione uma foto e receba um clipe em cerca de um minuto.',
    previewSoon: 'Prévia em breve',
    madeWith: 'Feito com {engine}',
    effectLabel: 'Efeito',
    effectPhoto: 'Este efeito começa da sua foto — ela vira o primeiro quadro.',
    effectPersonHint: 'Use uma foto sua ou de alguém que concordou com isso.',
    effectAddPhoto: 'Adicione uma foto para começar',
    effectBack: 'Prefiro escrever meu próprio clipe',
    filmUpsell: 'Transformar em filme narrado (60 s)',
    paidBadge: 'NOVO · planos pagos',
    paidHint: 'Disponível nos planos pagos — ver planos',
    seePlans: 'Ver planos →',
  },
  es: {
    title: 'Clips',
    sub: 'Una escena, de 5 a 15 segundos, sin narración. Escríbela o empieza desde una foto.',
    engine: 'Motor',
    from: 'desde {n} cr',
    photoOnly: 'Solo con foto',
    yourClip: 'Tu clip',
    placeholder: 'Un dron sobre un mar en tormenta al atardecer, olas rompiendo en rocas negras',
    placeholderMotion: 'Describe el movimiento (opcional) — p. ej. acercamiento lento, pelo al viento',
    photo: 'Foto (opcional)',
    photoHint: 'Tu foto se convierte en el primer fotograma.',
    addPhoto: 'Añadir foto',
    removePhoto: 'Quitar foto',
    uploading: 'Subiendo…',
    length: 'Duración',
    format: 'Formato',
    vertical: 'Vertical',
    wide: 'Horizontal',
    square: 'Cuadrado',
    samePhoto: 'El mismo de tu foto',
    notLength: '{engine} no hace clips de {s} s. Estos motores sí:',
    needsPhoto: '{engine} solo empieza desde una foto. Añade una foto o elige otro motor.',
    noPhoto: '{engine} no puede empezar desde una foto.',
    cost: 'Costo',
    credits: 'créditos',
    generate: 'Generar clip',
    creating: 'Creando…',
    describeFirst: 'Describe tu clip o añade una foto',
    myClips: 'Mis clips',
    inProgress: 'En curso — normalmente de 1 a 5 minutos. Puedes salir de esta página.',
    failedRefunded: 'Falló — {n} créditos devueltos.',
    failed: 'Falló.',
    download: 'Descargar',
    empty: 'Aún no hay clips.',
    loadFailed: 'No pudimos cargar tus clips ahora.',
    tryAgain: 'Reintentar',
    addCredits: 'Añadir créditos →',
    signIn: 'Iniciar sesión →',
    effectsTitle: 'Efectos de un clic',
    effectsSub: 'Elige un efecto, añade una foto y recibe un clip en un minuto aproximadamente.',
    previewSoon: 'Vista previa próximamente',
    madeWith: 'Hecho con {engine}',
    effectLabel: 'Efecto',
    effectPhoto: 'Este efecto empieza desde tu foto — se convierte en el primer fotograma.',
    effectPersonHint: 'Usa una foto tuya o de alguien que haya dado su permiso.',
    effectAddPhoto: 'Añade una foto para empezar',
    effectBack: 'Prefiero escribir mi propio clip',
    filmUpsell: 'Convertir en película narrada (60 s)',
    paidBadge: 'NUEVO · planes de pago',
    paidHint: 'Disponible en los planes de pago — ver planes',
    seePlans: 'Ver planes →',
  },
  fr: {
    title: 'Clips',
    sub: 'Une scène, de 5 à 15 secondes, sans narration. Décrivez-la ou partez d’une photo.',
    engine: 'Moteur',
    from: 'dès {n} cr',
    photoOnly: 'Photo uniquement',
    yourClip: 'Votre clip',
    placeholder: 'Un drone au-dessus d’une mer déchaînée au crépuscule, des vagues sur des rochers noirs',
    placeholderMotion: 'Décrivez le mouvement (facultatif) — ex. travelling lent, cheveux dans le vent',
    photo: 'Photo (facultatif)',
    photoHint: 'Votre photo devient la première image.',
    addPhoto: 'Ajouter une photo',
    removePhoto: 'Retirer la photo',
    uploading: 'Envoi…',
    length: 'Durée',
    format: 'Format',
    vertical: 'Vertical',
    wide: 'Horizontal',
    square: 'Carré',
    samePhoto: 'Celui de votre photo',
    notLength: '{engine} ne fait pas de clips de {s} s. Ces moteurs, oui :',
    needsPhoto: '{engine} part uniquement d’une photo. Ajoutez une photo ou choisissez un autre moteur.',
    noPhoto: '{engine} ne peut pas partir d’une photo.',
    cost: 'Coût',
    credits: 'crédits',
    generate: 'Générer le clip',
    creating: 'Création…',
    describeFirst: 'Décrivez votre clip ou ajoutez une photo',
    myClips: 'Mes clips',
    inProgress: 'En cours — en général 1 à 5 minutes. Vous pouvez quitter cette page.',
    failedRefunded: 'Échec — {n} crédits remboursés.',
    failed: 'Échec.',
    download: 'Télécharger',
    empty: 'Aucun clip pour l’instant.',
    loadFailed: 'Impossible de charger vos clips pour le moment.',
    tryAgain: 'Réessayer',
    addCredits: 'Ajouter des crédits →',
    signIn: 'Se connecter →',
    effectsTitle: 'Effets en un clic',
    effectsSub: 'Choisissez un effet, ajoutez une photo et recevez un clip en une minute environ.',
    previewSoon: 'Aperçu bientôt disponible',
    madeWith: 'Réalisé avec {engine}',
    effectLabel: 'Effet',
    effectPhoto: 'Cet effet part de votre photo — elle devient la première image.',
    effectPersonHint: 'Utilisez une photo de vous ou d’une personne qui a donné son accord.',
    effectAddPhoto: 'Ajoutez une photo pour commencer',
    effectBack: 'Écrire plutôt mon propre clip',
    filmUpsell: 'Transformer en film narré (60 s)',
    paidBadge: 'NOUVEAU · offres payantes',
    paidHint: 'Disponible avec les offres payantes — voir les offres',
    seePlans: 'Voir les offres →',
  },
  de: {
    title: 'Clips',
    sub: 'Eine Szene, 5 bis 15 Sekunden, ohne Sprecher. Beschreiben oder mit einem Foto starten.',
    engine: 'Engine',
    from: 'ab {n} Cr',
    photoOnly: 'Nur mit Foto',
    yourClip: 'Dein Clip',
    placeholder: 'Drohnenflug über ein stürmisches Meer in der Dämmerung, Wellen brechen an schwarzen Felsen',
    placeholderMotion: 'Beschreibe die Bewegung (optional) — z. B. langsame Kamerafahrt, Haare im Wind',
    photo: 'Foto (optional)',
    photoHint: 'Dein Foto wird das erste Bild.',
    addPhoto: 'Foto hinzufügen',
    removePhoto: 'Foto entfernen',
    uploading: 'Wird hochgeladen…',
    length: 'Länge',
    format: 'Format',
    vertical: 'Hochformat',
    wide: 'Querformat',
    square: 'Quadrat',
    samePhoto: 'Wie dein Foto',
    notLength: '{engine} macht keine {s}-s-Clips. Diese Engines schon:',
    needsPhoto: '{engine} startet nur mit einem Foto. Füge ein Foto hinzu oder wähle eine andere Engine.',
    noPhoto: '{engine} kann nicht mit einem Foto starten.',
    cost: 'Kosten',
    credits: 'Credits',
    generate: 'Clip erstellen',
    creating: 'Wird erstellt…',
    describeFirst: 'Beschreibe deinen Clip oder füge ein Foto hinzu',
    myClips: 'Meine Clips',
    inProgress: 'Läuft — meist 1 bis 5 Minuten. Du kannst diese Seite verlassen.',
    failedRefunded: 'Fehlgeschlagen — {n} Credits erstattet.',
    failed: 'Fehlgeschlagen.',
    download: 'Herunterladen',
    empty: 'Noch keine Clips.',
    loadFailed: 'Deine Clips konnten gerade nicht geladen werden.',
    tryAgain: 'Erneut versuchen',
    addCredits: 'Credits aufladen →',
    signIn: 'Anmelden →',
    effectsTitle: 'Effekte mit einem Klick',
    effectsSub: 'Wähle einen Effekt, füge ein Foto hinzu und erhalte in etwa einer Minute einen Clip.',
    previewSoon: 'Vorschau folgt in Kürze',
    madeWith: 'Erstellt mit {engine}',
    effectLabel: 'Effekt',
    effectPhoto: 'Dieser Effekt startet mit deinem Foto — es wird das erste Bild.',
    effectPersonHint: 'Nutze ein Foto von dir oder von jemandem, der zugestimmt hat.',
    effectAddPhoto: 'Füge ein Foto hinzu, um zu starten',
    effectBack: 'Lieber meinen eigenen Clip schreiben',
    filmUpsell: 'In einen erzählten Film verwandeln (60 s)',
    paidBadge: 'NEU · bezahlte Pläne',
    paidHint: 'In bezahlten Plänen verfügbar — Pläne ansehen',
    seePlans: 'Pläne ansehen →',
  },
  it: {
    title: 'Clip',
    sub: 'Una scena, da 5 a 15 secondi, senza narrazione. Scrivila o parti da una foto.',
    engine: 'Motore',
    from: 'da {n} cr',
    photoOnly: 'Solo con foto',
    yourClip: 'Il tuo clip',
    placeholder: 'Un drone sopra un mare in tempesta al tramonto, onde che si infrangono su rocce nere',
    placeholderMotion: 'Descrivi il movimento (facoltativo) — es. avvicinamento lento, capelli al vento',
    photo: 'Foto (facoltativa)',
    photoHint: 'La tua foto diventa il primo fotogramma.',
    addPhoto: 'Aggiungi foto',
    removePhoto: 'Rimuovi foto',
    uploading: 'Caricamento…',
    length: 'Durata',
    format: 'Formato',
    vertical: 'Verticale',
    wide: 'Orizzontale',
    square: 'Quadrato',
    samePhoto: 'Uguale alla tua foto',
    notLength: '{engine} non fa clip da {s} s. Questi motori sì:',
    needsPhoto: '{engine} parte solo da una foto. Aggiungi una foto o scegli un altro motore.',
    noPhoto: '{engine} non può partire da una foto.',
    cost: 'Costo',
    credits: 'crediti',
    generate: 'Genera clip',
    creating: 'Creazione…',
    describeFirst: 'Descrivi il tuo clip o aggiungi una foto',
    myClips: 'I miei clip',
    inProgress: 'In corso — di solito da 1 a 5 minuti. Puoi lasciare questa pagina.',
    failedRefunded: 'Non riuscito — {n} crediti rimborsati.',
    failed: 'Non riuscito.',
    download: 'Scarica',
    empty: 'Ancora nessun clip.',
    loadFailed: 'Non riusciamo a caricare i tuoi clip in questo momento.',
    tryAgain: 'Riprova',
    addCredits: 'Aggiungi crediti →',
    signIn: 'Accedi →',
    effectsTitle: 'Effetti con un clic',
    effectsSub: 'Scegli un effetto, aggiungi una foto e ricevi una clip in circa un minuto.',
    previewSoon: 'Anteprima in arrivo',
    madeWith: 'Realizzato con {engine}',
    effectLabel: 'Effetto',
    effectPhoto: 'Questo effetto parte dalla tua foto — diventa il primo fotogramma.',
    effectPersonHint: 'Usa una tua foto o di qualcuno che ha dato il consenso.',
    effectAddPhoto: 'Aggiungi una foto per iniziare',
    effectBack: 'Preferisco scrivere la mia clip',
    filmUpsell: 'Trasforma in un film narrato (60 s)',
    paidBadge: 'NUOVO · piani a pagamento',
    paidHint: 'Disponibile nei piani a pagamento — vedi i piani',
    seePlans: 'Vedi i piani →',
  },
  nl: {
    title: 'Clips',
    sub: 'Eén scène, 5 tot 15 seconden, zonder voice-over. Beschrijf het of begin met een foto.',
    engine: 'Engine',
    from: 'vanaf {n} cr',
    photoOnly: 'Alleen met foto',
    yourClip: 'Jouw clip',
    placeholder: 'Een drone boven een stormachtige zee bij zonsondergang, golven op zwarte rotsen',
    placeholderMotion: 'Beschrijf de beweging (optioneel) — bijv. langzaam inzoomen, haar in de wind',
    photo: 'Foto (optioneel)',
    photoHint: 'Je foto wordt het eerste beeld.',
    addPhoto: 'Foto toevoegen',
    removePhoto: 'Foto verwijderen',
    uploading: 'Uploaden…',
    length: 'Lengte',
    format: 'Formaat',
    vertical: 'Verticaal',
    wide: 'Breed',
    square: 'Vierkant',
    samePhoto: 'Zoals je foto',
    notLength: '{engine} maakt geen clips van {s} s. Deze engines wel:',
    needsPhoto: '{engine} start alleen vanaf een foto. Voeg een foto toe of kies een andere engine.',
    noPhoto: '{engine} kan niet vanaf een foto starten.',
    cost: 'Kosten',
    credits: 'credits',
    generate: 'Clip maken',
    creating: 'Bezig…',
    describeFirst: 'Beschrijf je clip of voeg een foto toe',
    myClips: 'Mijn clips',
    inProgress: 'Bezig — meestal 1 tot 5 minuten. Je kunt deze pagina verlaten.',
    failedRefunded: 'Mislukt — {n} credits terugbetaald.',
    failed: 'Mislukt.',
    download: 'Downloaden',
    empty: 'Nog geen clips.',
    loadFailed: 'We konden je clips nu niet laden.',
    tryAgain: 'Opnieuw proberen',
    addCredits: 'Credits toevoegen →',
    signIn: 'Inloggen →',
    effectsTitle: 'Effecten met één klik',
    effectsSub: 'Kies een effect, voeg een foto toe en krijg binnen ongeveer een minuut een clip.',
    previewSoon: 'Voorbeeld volgt binnenkort',
    madeWith: 'Gemaakt met {engine}',
    effectLabel: 'Effect',
    effectPhoto: 'Dit effect begint bij je foto — die wordt het eerste beeld.',
    effectPersonHint: 'Gebruik een foto van jezelf of van iemand die ermee heeft ingestemd.',
    effectAddPhoto: 'Voeg een foto toe om te beginnen',
    effectBack: 'Liever mijn eigen clip schrijven',
    filmUpsell: 'Maak er een vertelde film van (60 s)',
    paidBadge: 'NIEUW · betaalde plannen',
    paidHint: 'Beschikbaar in betaalde plannen — bekijk de plannen',
    seePlans: 'Bekijk de plannen →',
  },
  pl: {
    title: 'Klipy',
    sub: 'Jedna scena, od 5 do 15 sekund, bez lektora. Opisz ją albo zacznij od zdjęcia.',
    engine: 'Silnik',
    from: 'od {n} kr',
    photoOnly: 'Tylko ze zdjęciem',
    yourClip: 'Twój klip',
    placeholder: 'Dron nad wzburzonym morzem o zmierzchu, fale rozbijają się o czarne skały',
    placeholderMotion: 'Opisz ruch (opcjonalnie) — np. powolny najazd, włosy na wietrze',
    photo: 'Zdjęcie (opcjonalnie)',
    photoHint: 'Twoje zdjęcie staje się pierwszą klatką.',
    addPhoto: 'Dodaj zdjęcie',
    removePhoto: 'Usuń zdjęcie',
    uploading: 'Wysyłanie…',
    length: 'Długość',
    format: 'Format',
    vertical: 'Pionowy',
    wide: 'Poziomy',
    square: 'Kwadrat',
    samePhoto: 'Taki jak zdjęcie',
    notLength: '{engine} nie robi klipów {s} s. Te silniki robią:',
    needsPhoto: '{engine} zaczyna tylko od zdjęcia. Dodaj zdjęcie albo wybierz inny silnik.',
    noPhoto: '{engine} nie może zacząć od zdjęcia.',
    cost: 'Koszt',
    credits: 'kredytów',
    generate: 'Generuj klip',
    creating: 'Tworzenie…',
    describeFirst: 'Opisz klip albo dodaj zdjęcie',
    myClips: 'Moje klipy',
    inProgress: 'W toku — zwykle od 1 do 5 minut. Możesz opuścić tę stronę.',
    failedRefunded: 'Nie udało się — zwrócono {n} kredytów.',
    failed: 'Nie udało się.',
    download: 'Pobierz',
    empty: 'Brak klipów.',
    loadFailed: 'Nie udało się teraz wczytać Twoich klipów.',
    tryAgain: 'Spróbuj ponownie',
    addCredits: 'Dodaj kredyty →',
    signIn: 'Zaloguj się →',
    effectsTitle: 'Efekty jednym kliknięciem',
    effectsSub: 'Wybierz efekt, dodaj zdjęcie i odbierz klip w około minutę.',
    previewSoon: 'Podgląd wkrótce',
    madeWith: 'Zrobione w {engine}',
    effectLabel: 'Efekt',
    effectPhoto: 'Ten efekt zaczyna się od Twojego zdjęcia — staje się pierwszą klatką.',
    effectPersonHint: 'Użyj swojego zdjęcia albo zdjęcia osoby, która się na to zgodziła.',
    effectAddPhoto: 'Dodaj zdjęcie, aby zacząć',
    effectBack: 'Wolę napisać własny klip',
    filmUpsell: 'Zamień w film z narracją (60 s)',
    paidBadge: 'NOWOŚĆ · płatne plany',
    paidHint: 'Dostępne w płatnych planach — zobacz plany',
    seePlans: 'Zobacz plany →',
  },
  tr: {
    title: 'Klipler',
    sub: 'Tek sahne, 5 ile 15 saniye, anlatım yok. Yazın ya da bir fotoğrafla başlayın.',
    engine: 'Motor',
    from: '{n} kr’den başlayan',
    photoOnly: 'Yalnızca fotoğrafla',
    yourClip: 'Klibiniz',
    placeholder: 'Gün batımında fırtınalı bir denizin üzerinde drone çekimi, siyah kayalara çarpan dalgalar',
    placeholderMotion: 'Hareketi anlatın (isteğe bağlı) — ör. yavaş yaklaşma, rüzgârda uçuşan saçlar',
    photo: 'Fotoğraf (isteğe bağlı)',
    photoHint: 'Fotoğrafınız ilk kare olur.',
    addPhoto: 'Fotoğraf ekle',
    removePhoto: 'Fotoğrafı kaldır',
    uploading: 'Yükleniyor…',
    length: 'Süre',
    format: 'Format',
    vertical: 'Dikey',
    wide: 'Yatay',
    square: 'Kare',
    samePhoto: 'Fotoğrafınızla aynı',
    notLength: '{engine} {s} sn klip yapmaz. Bu motorlar yapar:',
    needsPhoto: '{engine} yalnızca fotoğraftan başlar. Fotoğraf ekleyin ya da başka motor seçin.',
    noPhoto: '{engine} fotoğraftan başlayamaz.',
    cost: 'Maliyet',
    credits: 'kredi',
    generate: 'Klip oluştur',
    creating: 'Oluşturuluyor…',
    describeFirst: 'Klibinizi anlatın ya da fotoğraf ekleyin',
    myClips: 'Kliplerim',
    inProgress: 'Sürüyor — genellikle 1 ile 5 dakika. Bu sayfadan çıkabilirsiniz.',
    failedRefunded: 'Başarısız — {n} kredi iade edildi.',
    failed: 'Başarısız.',
    download: 'İndir',
    empty: 'Henüz klip yok.',
    loadFailed: 'Klipleriniz şu anda yüklenemedi.',
    tryAgain: 'Tekrar dene',
    addCredits: 'Kredi ekle →',
    signIn: 'Giriş yap →',
    effectsTitle: 'Tek tıkla efektler',
    effectsSub: 'Bir efekt seçin, fotoğraf ekleyin ve yaklaşık bir dakikada klibinizi alın.',
    previewSoon: 'Önizleme yakında',
    madeWith: '{engine} ile yapıldı',
    effectLabel: 'Efekt',
    effectPhoto: 'Bu efekt fotoğrafınızdan başlar — fotoğraf ilk kare olur.',
    effectPersonHint: 'Kendi fotoğrafınızı ya da buna onay vermiş birinin fotoğrafını kullanın.',
    effectAddPhoto: 'Başlamak için fotoğraf ekleyin',
    effectBack: 'Kendi klibimi yazmayı tercih ederim',
    filmUpsell: 'Anlatımlı filme dönüştür (60 sn)',
    paidBadge: 'YENİ · ücretli planlar',
    paidHint: 'Ücretli planlarda kullanılabilir — planları gör',
    seePlans: 'Planları gör →',
  },
  ru: {
    title: 'Клипы',
    sub: 'Одна сцена, от 5 до 15 секунд, без закадрового голоса. Опишите её или начните с фото.',
    engine: 'Движок',
    from: 'от {n} кр',
    photoOnly: 'Только с фото',
    yourClip: 'Ваш клип',
    placeholder: 'Съёмка с дрона над штормовым морем на закате, волны бьются о чёрные скалы',
    placeholderMotion: 'Опишите движение (необязательно) — напр. медленный наезд, волосы на ветру',
    photo: 'Фото (необязательно)',
    photoHint: 'Ваше фото станет первым кадром.',
    addPhoto: 'Добавить фото',
    removePhoto: 'Убрать фото',
    uploading: 'Загрузка…',
    length: 'Длительность',
    format: 'Формат',
    vertical: 'Вертикальный',
    wide: 'Горизонтальный',
    square: 'Квадрат',
    samePhoto: 'Как у фото',
    notLength: '{engine} не делает клипы по {s} с. Эти движки делают:',
    needsPhoto: '{engine} работает только от фото. Добавьте фото или выберите другой движок.',
    noPhoto: '{engine} не может начать с фото.',
    cost: 'Стоимость',
    credits: 'кредитов',
    generate: 'Создать клип',
    creating: 'Создаётся…',
    describeFirst: 'Опишите клип или добавьте фото',
    myClips: 'Мои клипы',
    inProgress: 'В работе — обычно от 1 до 5 минут. Можно закрыть страницу.',
    failedRefunded: 'Не получилось — {n} кредитов возвращено.',
    failed: 'Не получилось.',
    download: 'Скачать',
    empty: 'Клипов пока нет.',
    loadFailed: 'Не удалось загрузить ваши клипы.',
    tryAgain: 'Повторить',
    addCredits: 'Пополнить кредиты →',
    signIn: 'Войти →',
    effectsTitle: 'Эффекты в один клик',
    effectsSub: 'Выберите эффект, добавьте фото и получите клип примерно за минуту.',
    previewSoon: 'Превью скоро появится',
    madeWith: 'Сделано на {engine}',
    effectLabel: 'Эффект',
    effectPhoto: 'Этот эффект начинается с вашего фото — оно станет первым кадром.',
    effectPersonHint: 'Используйте своё фото или фото человека, который на это согласился.',
    effectAddPhoto: 'Добавьте фото, чтобы начать',
    effectBack: 'Лучше напишу свой клип',
    filmUpsell: 'Превратить в фильм с озвучкой (60 с)',
    paidBadge: 'НОВИНКА · платные планы',
    paidHint: 'Доступно в платных планах — посмотреть планы',
    seePlans: 'Посмотреть планы →',
  },
  uk: {
    title: 'Кліпи',
    sub: 'Одна сцена, від 5 до 15 секунд, без закадрового голосу. Опишіть її або почніть із фото.',
    engine: 'Рушій',
    from: 'від {n} кр',
    photoOnly: 'Лише з фото',
    yourClip: 'Ваш кліп',
    placeholder: 'Зйомка з дрона над штормовим морем на заході сонця, хвилі б’ються об чорні скелі',
    placeholderMotion: 'Опишіть рух (необов’язково) — напр. повільний наїзд, волосся на вітрі',
    photo: 'Фото (необов’язково)',
    photoHint: 'Ваше фото стане першим кадром.',
    addPhoto: 'Додати фото',
    removePhoto: 'Прибрати фото',
    uploading: 'Завантаження…',
    length: 'Тривалість',
    format: 'Формат',
    vertical: 'Вертикальний',
    wide: 'Горизонтальний',
    square: 'Квадрат',
    samePhoto: 'Як у фото',
    notLength: '{engine} не робить кліпи по {s} с. Ці рушії роблять:',
    needsPhoto: '{engine} працює лише від фото. Додайте фото або виберіть інший рушій.',
    noPhoto: '{engine} не може почати з фото.',
    cost: 'Вартість',
    credits: 'кредитів',
    generate: 'Створити кліп',
    creating: 'Створюється…',
    describeFirst: 'Опишіть кліп або додайте фото',
    myClips: 'Мої кліпи',
    inProgress: 'Триває — зазвичай від 1 до 5 хвилин. Можна залишити сторінку.',
    failedRefunded: 'Не вдалося — повернено {n} кредитів.',
    failed: 'Не вдалося.',
    download: 'Завантажити',
    empty: 'Кліпів поки немає.',
    loadFailed: 'Не вдалося завантажити ваші кліпи.',
    tryAgain: 'Спробувати ще',
    addCredits: 'Поповнити кредити →',
    signIn: 'Увійти →',
    effectsTitle: 'Ефекти в один клік',
    effectsSub: 'Оберіть ефект, додайте фото й отримайте кліп приблизно за хвилину.',
    previewSoon: 'Прев’ю незабаром',
    madeWith: 'Зроблено на {engine}',
    effectLabel: 'Ефект',
    effectPhoto: 'Цей ефект починається з вашого фото — воно стане першим кадром.',
    effectPersonHint: 'Використовуйте своє фото або фото людини, яка на це погодилася.',
    effectAddPhoto: 'Додайте фото, щоб почати',
    effectBack: 'Краще напишу свій кліп',
    filmUpsell: 'Перетворити на фільм з озвученням (60 с)',
    paidBadge: 'НОВИНКА · платні плани',
    paidHint: 'Доступно в платних планах — переглянути плани',
    seePlans: 'Переглянути плани →',
  },
  ar: {
    title: 'مقاطع',
    sub: 'مشهد واحد، من 5 إلى 15 ثانية، بدون تعليق صوتي. اكتبه أو ابدأ من صورة.',
    engine: 'المحرك',
    from: 'من {n} رصيد',
    photoOnly: 'بصورة فقط',
    yourClip: 'مقطعك',
    placeholder: 'لقطة درون فوق بحر عاصف عند الغروب، وأمواج ترتطم بصخور سوداء',
    placeholderMotion: 'صف الحركة (اختياري) — مثل اقتراب بطيء، شعر يتطاير مع الريح',
    photo: 'صورة (اختياري)',
    photoHint: 'تصبح صورتك الإطار الأول.',
    addPhoto: 'أضف صورة',
    removePhoto: 'أزل الصورة',
    uploading: 'جارٍ الرفع…',
    length: 'المدة',
    format: 'الأبعاد',
    vertical: 'عمودي',
    wide: 'أفقي',
    square: 'مربع',
    samePhoto: 'نفس أبعاد صورتك',
    notLength: '{engine} لا يصنع مقاطع مدتها {s} ث. هذه المحركات تفعل:',
    needsPhoto: '{engine} يبدأ من صورة فقط. أضف صورة أو اختر محركًا آخر.',
    noPhoto: '{engine} لا يمكنه البدء من صورة.',
    cost: 'التكلفة',
    credits: 'رصيد',
    generate: 'أنشئ المقطع',
    creating: 'جارٍ الإنشاء…',
    describeFirst: 'صف مقطعك أو أضف صورة',
    myClips: 'مقاطعي',
    inProgress: 'قيد التنفيذ — عادةً من 1 إلى 5 دقائق. يمكنك مغادرة هذه الصفحة.',
    failedRefunded: 'فشل — تمت إعادة {n} رصيد.',
    failed: 'فشل.',
    download: 'تنزيل',
    empty: 'لا توجد مقاطع بعد.',
    loadFailed: 'تعذر تحميل مقاطعك الآن.',
    tryAgain: 'حاول مرة أخرى',
    addCredits: 'أضف رصيدًا ←',
    signIn: 'تسجيل الدخول ←',
    effectsTitle: 'تأثيرات بنقرة واحدة',
    effectsSub: 'اختر تأثيرًا وأضف صورة واحصل على مقطع خلال دقيقة تقريبًا.',
    previewSoon: 'المعاينة قريبًا',
    madeWith: 'صُنع باستخدام {engine}',
    effectLabel: 'التأثير',
    effectPhoto: 'يبدأ هذا التأثير من صورتك — تصبح الإطار الأول.',
    effectPersonHint: 'استخدم صورتك أو صورة شخص وافق على ذلك.',
    effectAddPhoto: 'أضف صورة للبدء',
    effectBack: 'أفضّل كتابة مقطعي بنفسي',
    filmUpsell: 'حوّله إلى فيلم مروي (60 ث)',
    paidBadge: 'جديد · الخطط المدفوعة',
    paidHint: 'متاح في الخطط المدفوعة — اعرض الخطط',
    seePlans: 'اعرض الخطط ←',
  },
  ur: {
    title: 'کلپس',
    sub: 'ایک منظر، 5 سے 15 سیکنڈ، بغیر آواز کے بیان کے۔ لکھیں یا کسی تصویر سے شروع کریں۔',
    engine: 'انجن',
    from: '{n} کریڈٹ سے',
    photoOnly: 'صرف تصویر سے',
    yourClip: 'آپ کا کلپ',
    placeholder: 'شام کے وقت طوفانی سمندر پر ڈرون شاٹ، سیاہ چٹانوں سے ٹکراتی لہریں',
    placeholderMotion: 'حرکت بیان کریں (اختیاری) — مثلاً آہستہ قریب آنا، ہوا میں اڑتے بال',
    photo: 'تصویر (اختیاری)',
    photoHint: 'آپ کی تصویر پہلا فریم بنتی ہے۔',
    addPhoto: 'تصویر شامل کریں',
    removePhoto: 'تصویر ہٹائیں',
    uploading: 'اپ لوڈ ہو رہا ہے…',
    length: 'دورانیہ',
    format: 'فارمیٹ',
    vertical: 'عمودی',
    wide: 'افقی',
    square: 'مربع',
    samePhoto: 'آپ کی تصویر جیسا',
    notLength: '{engine} {s} سیکنڈ کے کلپ نہیں بناتا۔ یہ انجن بناتے ہیں:',
    needsPhoto: '{engine} صرف تصویر سے شروع ہوتا ہے۔ تصویر شامل کریں یا دوسرا انجن چنیں۔',
    noPhoto: '{engine} تصویر سے شروع نہیں ہو سکتا۔',
    cost: 'قیمت',
    credits: 'کریڈٹ',
    generate: 'کلپ بنائیں',
    creating: 'بن رہا ہے…',
    describeFirst: 'اپنا کلپ بیان کریں یا تصویر شامل کریں',
    myClips: 'میرے کلپس',
    inProgress: 'جاری ہے — عموماً 1 سے 5 منٹ۔ آپ یہ صفحہ چھوڑ سکتے ہیں۔',
    failedRefunded: 'ناکام — {n} کریڈٹ واپس کر دیے گئے۔',
    failed: 'ناکام۔',
    download: 'ڈاؤن لوڈ',
    empty: 'ابھی کوئی کلپ نہیں۔',
    loadFailed: 'ہم ابھی آپ کے کلپس لوڈ نہیں کر سکے۔',
    tryAgain: 'دوبارہ کوشش کریں',
    addCredits: 'کریڈٹ شامل کریں ←',
    signIn: 'سائن ان کریں ←',
    effectsTitle: 'ایک کلک والے ایفیکٹس',
    effectsSub: 'ایک ایفیکٹ چنیں، تصویر شامل کریں اور تقریباً ایک منٹ میں کلپ پائیں۔',
    previewSoon: 'پیش منظر جلد آ رہا ہے',
    madeWith: '{engine} سے بنایا گیا',
    effectLabel: 'ایفیکٹ',
    effectPhoto: 'یہ ایفیکٹ آپ کی تصویر سے شروع ہوتا ہے — وہ پہلا فریم بنتی ہے۔',
    effectPersonHint: 'اپنی تصویر یا کسی ایسے شخص کی تصویر استعمال کریں جس نے اجازت دی ہو۔',
    effectAddPhoto: 'شروع کرنے کے لیے تصویر شامل کریں',
    effectBack: 'میں اپنا کلپ خود لکھنا چاہتا ہوں',
    filmUpsell: 'بیان والی فلم میں بدلیں (60 سیکنڈ)',
    paidBadge: 'نیا · بامعاوضہ پلانز',
    paidHint: 'بامعاوضہ پلانز میں دستیاب — پلانز دیکھیں',
    seePlans: 'پلانز دیکھیں ←',
  },
  hi: {
    title: 'क्लिप्स',
    sub: 'एक दृश्य, 5 से 15 सेकंड, बिना नैरेशन के। लिखें या किसी फ़ोटो से शुरू करें।',
    engine: 'इंजन',
    from: '{n} क्रेडिट से',
    photoOnly: 'सिर्फ़ फ़ोटो से',
    yourClip: 'आपकी क्लिप',
    placeholder: 'शाम को तूफ़ानी समुद्र के ऊपर ड्रोन शॉट, काली चट्टानों से टकराती लहरें',
    placeholderMotion: 'हलचल बताएँ (वैकल्पिक) — जैसे धीमा ज़ूम-इन, हवा में उड़ते बाल',
    photo: 'फ़ोटो (वैकल्पिक)',
    photoHint: 'आपकी फ़ोटो पहला फ़्रेम बनती है।',
    addPhoto: 'फ़ोटो जोड़ें',
    removePhoto: 'फ़ोटो हटाएँ',
    uploading: 'अपलोड हो रहा है…',
    length: 'अवधि',
    format: 'फ़ॉर्मेट',
    vertical: 'वर्टिकल',
    wide: 'हॉरिज़ॉन्टल',
    square: 'स्क्वेयर',
    samePhoto: 'आपकी फ़ोटो जैसा',
    notLength: '{engine} {s} सेकंड की क्लिप नहीं बनाता। ये इंजन बनाते हैं:',
    needsPhoto: '{engine} सिर्फ़ फ़ोटो से शुरू होता है। फ़ोटो जोड़ें या दूसरा इंजन चुनें।',
    noPhoto: '{engine} फ़ोटो से शुरू नहीं कर सकता।',
    cost: 'क़ीमत',
    credits: 'क्रेडिट',
    generate: 'क्लिप बनाएँ',
    creating: 'बन रही है…',
    describeFirst: 'अपनी क्लिप बताएँ या फ़ोटो जोड़ें',
    myClips: 'मेरी क्लिप्स',
    inProgress: 'जारी है — आमतौर पर 1 से 5 मिनट। आप यह पेज छोड़ सकते हैं।',
    failedRefunded: 'विफल — {n} क्रेडिट लौटा दिए गए।',
    failed: 'विफल।',
    download: 'डाउनलोड',
    empty: 'अभी कोई क्लिप नहीं।',
    loadFailed: 'हम अभी आपकी क्लिप्स लोड नहीं कर सके।',
    tryAgain: 'फिर कोशिश करें',
    addCredits: 'क्रेडिट जोड़ें →',
    signIn: 'साइन इन करें →',
    effectsTitle: 'एक क्लिक वाले इफ़ेक्ट',
    effectsSub: 'एक इफ़ेक्ट चुनें, फ़ोटो जोड़ें और लगभग एक मिनट में क्लिप पाएँ।',
    previewSoon: 'प्रीव्यू जल्द आ रहा है',
    madeWith: '{engine} से बना',
    effectLabel: 'इफ़ेक्ट',
    effectPhoto: 'यह इफ़ेक्ट आपकी फ़ोटो से शुरू होता है — वही पहला फ़्रेम बनती है।',
    effectPersonHint: 'अपनी फ़ोटो या किसी ऐसे व्यक्ति की फ़ोटो इस्तेमाल करें जिसने इसकी सहमति दी हो।',
    effectAddPhoto: 'शुरू करने के लिए फ़ोटो जोड़ें',
    effectBack: 'मैं अपनी क्लिप खुद लिखूँगा',
    filmUpsell: 'नैरेशन वाली फ़िल्म बनाएँ (60 सेकंड)',
    paidBadge: 'नया · पेड प्लान',
    paidHint: 'पेड प्लान में उपलब्ध — प्लान देखें',
    seePlans: 'प्लान देखें →',
  },
  id: {
    title: 'Klip',
    sub: 'Satu adegan, 5 sampai 15 detik, tanpa narasi. Tulis atau mulai dari foto.',
    engine: 'Mesin',
    from: 'mulai {n} kr',
    photoOnly: 'Hanya dengan foto',
    yourClip: 'Klip Anda',
    placeholder: 'Bidikan drone di atas laut berbadai saat senja, ombak menghantam batu hitam',
    placeholderMotion: 'Jelaskan gerakannya (opsional) — mis. zoom perlahan, rambut tertiup angin',
    photo: 'Foto (opsional)',
    photoHint: 'Foto Anda menjadi bingkai pertama.',
    addPhoto: 'Tambah foto',
    removePhoto: 'Hapus foto',
    uploading: 'Mengunggah…',
    length: 'Durasi',
    format: 'Format',
    vertical: 'Vertikal',
    wide: 'Lebar',
    square: 'Persegi',
    samePhoto: 'Sama dengan foto Anda',
    notLength: '{engine} tidak membuat klip {s} dtk. Mesin ini bisa:',
    needsPhoto: '{engine} hanya mulai dari foto. Tambahkan foto atau pilih mesin lain.',
    noPhoto: '{engine} tidak bisa mulai dari foto.',
    cost: 'Biaya',
    credits: 'kredit',
    generate: 'Buat klip',
    creating: 'Membuat…',
    describeFirst: 'Jelaskan klip Anda atau tambahkan foto',
    myClips: 'Klip saya',
    inProgress: 'Sedang diproses — biasanya 1 sampai 5 menit. Anda boleh meninggalkan halaman ini.',
    failedRefunded: 'Gagal — {n} kredit dikembalikan.',
    failed: 'Gagal.',
    download: 'Unduh',
    empty: 'Belum ada klip.',
    loadFailed: 'Kami tidak dapat memuat klip Anda sekarang.',
    tryAgain: 'Coba lagi',
    addCredits: 'Tambah kredit →',
    signIn: 'Masuk →',
    effectsTitle: 'Efek sekali klik',
    effectsSub: 'Pilih efek, tambahkan foto, dan dapatkan klip dalam sekitar satu menit.',
    previewSoon: 'Pratinjau segera hadir',
    madeWith: 'Dibuat dengan {engine}',
    effectLabel: 'Efek',
    effectPhoto: 'Efek ini dimulai dari foto Anda — foto menjadi bingkai pertama.',
    effectPersonHint: 'Gunakan foto Anda sendiri atau foto orang yang sudah setuju.',
    effectAddPhoto: 'Tambahkan foto untuk mulai',
    effectBack: 'Saya tulis klip sendiri saja',
    filmUpsell: 'Jadikan film bernarasi (60 dtk)',
    paidBadge: 'BARU · paket berbayar',
    paidHint: 'Tersedia di paket berbayar — lihat paket',
    seePlans: 'Lihat paket →',
  },
  vi: {
    title: 'Clip',
    sub: 'Một cảnh, 5 đến 15 giây, không lời dẫn. Viết mô tả hoặc bắt đầu từ một bức ảnh.',
    engine: 'Mô hình',
    from: 'từ {n} tín dụng',
    photoOnly: 'Chỉ từ ảnh',
    yourClip: 'Clip của bạn',
    placeholder: 'Cảnh flycam trên biển động lúc hoàng hôn, sóng vỗ vào đá đen',
    placeholderMotion: 'Mô tả chuyển động (không bắt buộc) — vd. tiến máy chậm, tóc bay trong gió',
    photo: 'Ảnh (không bắt buộc)',
    photoHint: 'Ảnh của bạn trở thành khung hình đầu tiên.',
    addPhoto: 'Thêm ảnh',
    removePhoto: 'Bỏ ảnh',
    uploading: 'Đang tải lên…',
    length: 'Thời lượng',
    format: 'Khung hình',
    vertical: 'Dọc',
    wide: 'Ngang',
    square: 'Vuông',
    samePhoto: 'Giống ảnh của bạn',
    notLength: '{engine} không làm clip {s} giây. Các mô hình này thì có:',
    needsPhoto: '{engine} chỉ bắt đầu từ ảnh. Hãy thêm ảnh hoặc chọn mô hình khác.',
    noPhoto: '{engine} không thể bắt đầu từ ảnh.',
    cost: 'Chi phí',
    credits: 'tín dụng',
    generate: 'Tạo clip',
    creating: 'Đang tạo…',
    describeFirst: 'Mô tả clip hoặc thêm ảnh',
    myClips: 'Clip của tôi',
    inProgress: 'Đang xử lý — thường 1 đến 5 phút. Bạn có thể rời trang này.',
    failedRefunded: 'Thất bại — đã hoàn {n} tín dụng.',
    failed: 'Thất bại.',
    download: 'Tải xuống',
    empty: 'Chưa có clip nào.',
    loadFailed: 'Hiện chưa tải được clip của bạn.',
    tryAgain: 'Thử lại',
    addCredits: 'Thêm tín dụng →',
    signIn: 'Đăng nhập →',
    effectsTitle: 'Hiệu ứng một chạm',
    effectsSub: 'Chọn hiệu ứng, thêm ảnh và nhận clip trong khoảng một phút.',
    previewSoon: 'Bản xem trước sắp có',
    madeWith: 'Tạo bằng {engine}',
    effectLabel: 'Hiệu ứng',
    effectPhoto: 'Hiệu ứng này bắt đầu từ ảnh của bạn — ảnh trở thành khung hình đầu tiên.',
    effectPersonHint: 'Hãy dùng ảnh của chính bạn hoặc của người đã đồng ý.',
    effectAddPhoto: 'Thêm ảnh để bắt đầu',
    effectBack: 'Tôi muốn tự viết clip',
    filmUpsell: 'Biến thành phim có lời dẫn (60 giây)',
    paidBadge: 'MỚI · gói trả phí',
    paidHint: 'Có trong các gói trả phí — xem các gói',
    seePlans: 'Xem các gói →',
  },
}

/** Texto da chave na língua, com {engine} {s} {n} preenchidos. Chave sem tradução cai no inglês, nunca em branco. */
export function clipCopy(language: InterfaceLanguage, key: ClipCopyKey, vars: Record<string, string | number> = {}): string {
  const base = language === 'en' ? CLIP_COPY_EN[key] : (CLIP_COPY[language]?.[key] ?? CLIP_COPY_EN[key])
  return base.replace(/\{(engine|s|n)\}/g, (_, k: string) => (vars[k] === undefined ? `{${k}}` : String(vars[k])))
}
